import type { PairedQuizSeed } from "../paired-quiz-bank";

const q = (
  bm: string,
  dlp: string,
  correct: PairedQuizSeed["correct"],
  distractors: PairedQuizSeed["distractors"],
  bmExplanation: string,
  dlpExplanation: string,
): PairedQuizSeed => ({
  question: [bm, dlp],
  correct,
  distractors,
  explanation: [bmExplanation, dlpExplanation],
});

export const mathF2C3PairedSeeds: readonly PairedQuizSeed[] = [
  // Objective 1 — Foundation: meaning and components (5)
  q(
    "Apakah rumus algebra?",
    "What is an algebraic formula?",
    [
      "Persamaan yang menghubungkan dua atau lebih pemboleh ubah",
      "An equation relating two or more variables",
    ],
    [
      ["Ungkapan yang hanya mengandungi nombor", "An expression containing numbers only"],
      ["Senarai nombor mengikut tertib", "A list of numbers in order"],
      ["Pernyataan tanpa tanda sama dengan", "A statement without an equals sign"],
    ],
    "Rumus algebra ialah persamaan yang menunjukkan hubungan antara pemboleh ubah.",
    "An algebraic formula is an equation that shows a relationship between variables.",
  ),
  q(
    "Dalam rumus P = 2l + 2w, yang manakah pemboleh ubah?",
    "In the formula P = 2l + 2w, which are the variables?",
    "P, l dan w",
    ["2 sahaja", "P dan 2", "l dan 2w"],
    "P, l dan w boleh berubah nilainya, manakala 2 ialah pemalar.",
    "P, l and w can change in value, while 2 is a constant.",
  ),
  q(
    "Apakah pekali x dalam rumus y = 7x − 3?",
    "What is the coefficient of x in y = 7x − 3?",
    "7",
    ["−3", "3", "x"],
    "Pekali ialah nombor yang mendarab pemboleh ubah; pekali x ialah 7.",
    "A coefficient is the number multiplying a variable; the coefficient of x is 7.",
  ),
  q(
    "Dalam A = lw, apakah perkara rumus?",
    "In A = lw, what is the subject of the formula?",
    "A",
    ["l", "w", "lw"],
    "Perkara rumus ialah pemboleh ubah yang bersendirian di sebelah tanda sama dengan.",
    "The subject is the variable written alone on one side of the equals sign.",
  ),
  q(
    "Dalam C = 5n + 8, apakah pemalar yang ditambah?",
    "In C = 5n + 8, what constant is added?",
    "8",
    ["5", "n", "C"],
    "Nilai 8 tidak berubah apabila n berubah, jadi 8 ialah pemalar yang ditambah.",
    "The value 8 does not change when n changes, so it is the added constant.",
  ),

  // Straightforward substitution (7)
  q(
    "Gantikan x = 4 ke dalam y = 3x + 2. Cari y.",
    "Substitute x = 4 into y = 3x + 2. Find y.",
    "14",
    ["9", "12", "18"],
    "y = 3(4) + 2 = 14.",
    "y = 3(4) + 2 = 14.",
  ),
  q(
    "Jika P = 2a + 6 dan a = 5, tentukan P.",
    "If P = 2a + 6 and a = 5, determine P.",
    "16",
    ["13", "17", "22"],
    "P = 2(5) + 6 = 16.",
    "P = 2(5) + 6 = 16.",
  ),
  q(
    "Diberi m = 5n − 1. Cari m apabila n = 3.",
    "Given m = 5n − 1, find m when n = 3.",
    "14",
    ["9", "12", "16"],
    "m = 5(3) − 1 = 14.",
    "m = 5(3) − 1 = 14.",
  ),
  q(
    "Hitung k daripada k = 18 ÷ p apabila p = 3.",
    "Calculate k from k = 18 ÷ p when p = 3.",
    "6",
    ["5", "15", "54"],
    "k = 18 ÷ 3 = 6.",
    "k = 18 ÷ 3 = 6.",
  ),
  q(
    "Jika t = 2r − 7 dan r = −2, apakah nilai t?",
    "If t = 2r − 7 and r = −2, what is t?",
    "−11",
    ["−3", "3", "11"],
    "t = 2(−2) − 7 = −4 − 7 = −11.",
    "t = 2(−2) − 7 = −4 − 7 = −11.",
  ),
  q(
    "Diberi V = s³. Tentukan V apabila s = 3.",
    "Given V = s³, determine V when s = 3.",
    "27",
    ["6", "9", "81"],
    "V = 3³ = 27.",
    "V = 3³ = 27.",
  ),
  q(
    "Jika z = a/4 + 2 dan a = 12, cari z.",
    "If z = a/4 + 2 and a = 12, find z.",
    "5",
    ["3", "6", "14"],
    "z = 12/4 + 2 = 3 + 2 = 5.",
    "z = 12/4 + 2 = 3 + 2 = 5.",
  ),

  // One-operation changes of subject (8)
  q(
    "Diberi y = x + 9. Ungkapkan x sebagai perkara rumus.",
    "Given y = x + 9. Express x as the subject.",
    "x = y − 9",
    ["x = y + 9", "x = 9 − y", "x = 9y"],
    "Tolak 9 pada kedua-dua belah: x = y − 9.",
    "Subtract 9 from both sides: x = y − 9.",
  ),
  q(
    "Diberi p = q − 6. Ungkapkan q sebagai perkara rumus.",
    "Given p = q − 6. Express q as the subject.",
    "q = p + 6",
    ["q = p − 6", "q = 6 − p", "q = 6p"],
    "Tambah 6 pada kedua-dua belah: q = p + 6.",
    "Add 6 to both sides: q = p + 6.",
  ),
  q(
    "Diberi A = 5b. Ungkapkan b sebagai perkara rumus.",
    "Given A = 5b. Express b as the subject.",
    "b = A/5",
    ["b = 5A", "b = A − 5", "b = 5/A"],
    "Bahagi kedua-dua belah dengan 5: b = A/5.",
    "Divide both sides by 5: b = A/5.",
  ),
  q(
    "Diberi k = m/7. Ungkapkan m sebagai perkara rumus.",
    "Given k = m/7. Express m as the subject.",
    "m = 7k",
    ["m = k/7", "m = 7/k", "m = k − 7"],
    "Darab kedua-dua belah dengan 7: m = 7k.",
    "Multiply both sides by 7: m = 7k.",
  ),
  q(
    "Dalam rumus C = n + d, jadikan d perkara rumus.",
    "In C = n + d, make d the subject.",
    "d = C − n",
    ["d = C + n", "d = n − C", "d = Cn"],
    "Tolak n daripada kedua-dua belah untuk mendapat d = C − n.",
    "Subtract n from both sides to obtain d = C − n.",
  ),
  q(
    "Diberi R = ab. Ungkapkan a sebagai perkara rumus.",
    "Given R = ab. Express a as the subject.",
    "a = R/b",
    ["a = Rb", "a = b/R", "a = R − b"],
    "Bahagi kedua-dua belah dengan b: a = R/b.",
    "Divide both sides by b: a = R/b.",
  ),
  q(
    "Diberi h = v − u. Jadikan v perkara rumus.",
    "Given h = v − u. Make v the subject.",
    "v = h + u",
    ["v = h − u", "v = u − h", "v = hu"],
    "Tambah u pada kedua-dua belah: v = h + u.",
    "Add u to both sides: v = h + u.",
  ),
  q(
    "Diberi g = f/c. Jadikan c perkara rumus.",
    "Given g = f/c. Make c the subject.",
    "c = f/g",
    ["c = fg", "c = g/f", "c = f − g"],
    "Darab dengan c dan bahagi dengan g: c = f/g.",
    "Multiply by c and divide by g: c = f/g.",
  ),

  // Forming simple formulae (5)
  q(
    "Harga sebuah buku ialah RMb. Apakah rumus kos C bagi 6 buah buku?",
    "A book costs RMb. What is the formula for the cost C of 6 books?",
    "C = 6b",
    ["C = b + 6", "C = b/6", "C = 6/b"],
    "Enam buku pada harga RMb setiap satu berjumlah C = 6b.",
    "Six books at RMb each cost C = 6b.",
  ),
  q(
    "Aina menyimpan RMx setiap minggu selama w minggu. Bentukkan rumus jumlah simpanan S.",
    "Aina saves RMx each week for w weeks. Form a formula for total savings S.",
    "S = xw",
    ["S = x + w", "S = x/w", "S = w − x"],
    "Jumlah simpanan ialah kadar mingguan × bilangan minggu: S = xw.",
    "Total savings equal weekly amount × number of weeks: S = xw.",
  ),
  q(
    "Umur Ravi ialah r tahun dan kakaknya 4 tahun lebih tua. Bentukkan rumus umur kakaknya, k.",
    "Ravi is r years old and his sister is 4 years older. Form a formula for her age k.",
    "k = r + 4",
    ["k = 4r", "k = r − 4", "k = 4 − r"],
    "Empat tahun lebih tua bermaksud tambah 4: k = r + 4.",
    "Four years older means add 4: k = r + 4.",
  ),
  q(
    "Sebuah segi empat tepat mempunyai panjang p dan lebar l. Bentukkan rumus luas A.",
    "A rectangle has length p and width l. Form the formula for area A.",
    "A = pl",
    ["A = 2p + 2l", "A = p + l", "A = p/l"],
    "Luas segi empat tepat = panjang × lebar, jadi A = pl.",
    "Rectangle area = length × width, so A = pl.",
  ),
  q(
    "Sebuah teksi mengenakan tambang asas RM3 dan RMm bagi setiap kilometer k. Bentukkan rumus tambang T.",
    "A taxi charges a RM3 base fare and RMm per kilometre for k kilometres. Form the fare formula T.",
    "T = 3 + mk",
    ["T = 3mk", "T = m + 3k", "T = (3 + m)k"],
    "Caj perjalanan ialah mk dan tambang asas ditambah sekali: T = 3 + mk.",
    "The journey charge is mk and the base fare is added once: T = 3 + mk.",
  ),

  // Direct interpretation (5)
  q(
    "Rumus C = 12 + 4n mewakili suatu kos. Apakah maksud 12?",
    "The formula C = 12 + 4n represents a cost. What does 12 mean?",
    ["Kos tetap RM12", "A fixed cost of RM12"],
    [
      ["Kos setiap item ialah RM12", "Each item costs RM12"],
      ["Bilangan item ialah 12", "There are 12 items"],
      ["Jumlah kos sentiasa RM12", "The total cost is always RM12"],
    ],
    "Nilai 12 tidak bergantung pada n, maka ia ialah kos tetap.",
    "The value 12 does not depend on n, so it is the fixed cost.",
  ),
  q(
    "Dalam d = 60t, d ialah jarak dalam km dan t ialah masa dalam jam. Apakah maksud 60?",
    "In d = 60t, d is distance in km and t is time in hours. What does 60 represent?",
    ["Laju 60 km/j", "A speed of 60 km/h"],
    [
      ["Jarak tetap 60 km", "A fixed distance of 60 km"],
      ["Masa 60 jam", "A time of 60 hours"],
      ["Tambahan 60 km setiap perjalanan", "An extra 60 km per journey"],
    ],
    "Pekali t ialah jarak bagi setiap jam, iaitu laju 60 km/j.",
    "The coefficient of t is distance per hour, which is a speed of 60 km/h.",
  ),
  q(
    "Rumus P = 2l + 2w digunakan untuk segi empat tepat. Apakah yang diwakili P?",
    "The formula P = 2l + 2w is used for a rectangle. What does P represent?",
    ["Perimeter", "Perimeter"],
    [
      ["Luas", "Area"],
      ["Panjang", "Length"],
      ["Lebar", "Width"],
    ],
    "Dua panjang dan dua lebar membentuk perimeter segi empat tepat.",
    "Two lengths and two widths form the perimeter of a rectangle.",
  ),
  q(
    "Dalam B = 20 − 2h, apakah kesan apabila h bertambah 1?",
    "In B = 20 − 2h, what happens when h increases by 1?",
    ["B berkurang 2", "B decreases by 2"],
    [
      ["B bertambah 2", "B increases by 2"],
      ["B berkurang 1", "B decreases by 1"],
      ["B tidak berubah", "B does not change"],
    ],
    "Pekali h ialah −2, jadi setiap pertambahan 1 pada h mengurangkan B sebanyak 2.",
    "The coefficient of h is −2, so each increase of 1 in h decreases B by 2.",
  ),
  q(
    "Berdasarkan M = 5p, apakah berlaku kepada M jika p digandakan?",
    "Based on M = 5p, what happens to M if p is doubled?",
    ["M juga digandakan", "M is also doubled"],
    [
      ["M menjadi lima kali ganda", "M becomes five times as large"],
      ["M bertambah 5 sahaja", "M increases by only 5"],
      ["M menjadi separuh", "M is halved"],
    ],
    "M berkadar terus dengan p; menggandakan p menggandakan M.",
    "M is directly proportional to p; doubling p doubles M.",
  ),

  // Objective 2 — Practice: substitution with several variables (6)
  q(
    "Diberi P = 2l + 2w. Cari P apabila l = 8 cm dan w = 5 cm.",
    "Given P = 2l + 2w, find P when l = 8 cm and w = 5 cm.",
    "26 cm",
    ["13 cm", "40 cm", "80 cm"],
    "P = 2(8) + 2(5) = 16 + 10 = 26 cm.",
    "P = 2(8) + 2(5) = 16 + 10 = 26 cm.",
  ),
  q(
    "Jika v = u + at, tentukan v apabila u = 6, a = 3 dan t = 4.",
    "If v = u + at, determine v when u = 6, a = 3 and t = 4.",
    "18",
    ["13", "30", "36"],
    "v = 6 + 3(4) = 18.",
    "v = 6 + 3(4) = 18.",
  ),
  q(
    "Diberi Q = 3a − 2b. Hitung Q apabila a = 5 dan b = −2.",
    "Given Q = 3a − 2b, calculate Q when a = 5 and b = −2.",
    "19",
    ["11", "13", "17"],
    "Q = 3(5) − 2(−2) = 15 + 4 = 19.",
    "Q = 3(5) − 2(−2) = 15 + 4 = 19.",
  ),
  q(
    "Gunakan A = 1/2 bh untuk mencari A apabila b = 12 cm dan h = 7 cm.",
    "Use A = 1/2 bh to find A when b = 12 cm and h = 7 cm.",
    "42 cm²",
    ["19 cm²", "84 cm²", "168 cm²"],
    "A = 1/2(12)(7) = 42 cm².",
    "A = 1/2(12)(7) = 42 cm².",
  ),
  q(
    "Diberi E = mc². Cari E apabila m = 2 dan c = 5.",
    "Given E = mc², find E when m = 2 and c = 5.",
    "50",
    ["20", "25", "100"],
    "E = 2(5²) = 2(25) = 50.",
    "E = 2(5²) = 2(25) = 50.",
  ),
  q(
    "Jika R = (p + q)/s, hitung R apabila p = 7, q = 5 dan s = 3.",
    "If R = (p + q)/s, calculate R when p = 7, q = 5 and s = 3.",
    "4",
    ["2/3", "6", "12"],
    "R = (7 + 5)/3 = 12/3 = 4.",
    "R = (7 + 5)/3 = 12/3 = 4.",
  ),

  // Multi-operation changes of subject (10)
  q(
    "Rumus y = 3x + 5 hendak disusun semula supaya x berdiri sendiri. Ungkapan manakah terhasil?",
    "The formula y = 3x + 5 is rearranged so that x stands alone. Which expression results?",
    "x = (y − 5)/3",
    ["x = y/3 − 5", "x = (y + 5)/3", "x = 3(y − 5)"],
    "Tolak 5, kemudian bahagi dengan 3: x = (y − 5)/3.",
    "Subtract 5, then divide by 3: x = (y − 5)/3.",
  ),
  q(
    "Dalam P = 2l + 2w, jadikan l perkara rumus.",
    "In P = 2l + 2w, make l the subject.",
    "l = (P − 2w)/2",
    ["l = P/2 − 2w", "l = (P + 2w)/2", "l = P − w"],
    "P − 2w = 2l, maka l = (P − 2w)/2.",
    "P − 2w = 2l, so l = (P − 2w)/2.",
  ),
  q(
    "Diberi A = 1/2 bh. Ungkapkan h sebagai perkara rumus.",
    "Given A = 1/2 bh, express h as the subject.",
    "h = 2A/b",
    ["h = A/(2b)", "h = Ab/2", "h = 2Ab"],
    "Darab dengan 2 dan bahagi dengan b: h = 2A/b.",
    "Multiply by 2 and divide by b: h = 2A/b.",
  ),
  q(
    "Diberi C = (F − 32) × 5/9. Jadikan F perkara rumus.",
    "Given C = (F − 32) × 5/9, make F the subject.",
    "F = 9C/5 + 32",
    ["F = 5C/9 + 32", "F = 9(C + 32)/5", "F = 9C/5 − 32"],
    "Darab C dengan 9/5, kemudian tambah 32: F = 9C/5 + 32.",
    "Multiply C by 9/5, then add 32: F = 9C/5 + 32.",
  ),
  q(
    "Diberi V = πr²h. Ungkapkan h sebagai perkara rumus.",
    "Given V = πr²h, express h as the subject.",
    "h = V/(πr²)",
    ["h = Vπr²", "h = πr²/V", "h = V/(2πr)"],
    "Bahagi kedua-dua belah dengan πr²: h = V/(πr²).",
    "Divide both sides by πr²: h = V/(πr²).",
  ),
  q(
    "Dalam k = (m + n)/p, jadikan n perkara rumus.",
    "In k = (m + n)/p, make n the subject.",
    "n = kp − m",
    ["n = k/p − m", "n = kp + m", "n = p/k − m"],
    "Darab dengan p: kp = m + n. Kemudian n = kp − m.",
    "Multiply by p: kp = m + n. Then n = kp − m.",
  ),
  q(
    "Diberi s = (u + v)t/2. Ungkapkan v sebagai perkara rumus.",
    "Given s = (u + v)t/2, express v as the subject.",
    "v = 2s/t − u",
    ["v = 2s/(t − u)", "v = 2st − u", "v = 2s/t + u"],
    "2s/t = u + v, maka v = 2s/t − u.",
    "2s/t = u + v, so v = 2s/t − u.",
  ),
  q(
    "Diberi a = (b − c)/d. Jadikan c perkara rumus.",
    "Given a = (b − c)/d, make c the subject.",
    "c = b − ad",
    ["c = ad − b", "c = b + ad", "c = (b − a)/d"],
    "ad = b − c, jadi c = b − ad.",
    "ad = b − c, hence c = b − ad.",
  ),
  q(
    "Dalam R = x/(y + 2), ungkapkan y sebagai perkara rumus.",
    "In R = x/(y + 2), express y as the subject.",
    "y = x/R − 2",
    ["y = xR − 2", "y = x/(R − 2)", "y = x/R + 2"],
    "R(y + 2) = x, maka y + 2 = x/R dan y = x/R − 2.",
    "R(y + 2) = x, so y + 2 = x/R and y = x/R − 2.",
  ),
  q(
    "Diberi z = 4 − 3x/5. Jadikan x perkara rumus.",
    "Given z = 4 − 3x/5, make x the subject.",
    "x = 5(4 − z)/3",
    ["x = 5(z − 4)/3", "x = (4 − 5z)/3", "x = 3(4 − z)/5"],
    "4 − z = 3x/5. Darab dengan 5/3 untuk memperoleh x = 5(4 − z)/3.",
    "4 − z = 3x/5. Multiply by 5/3 to obtain x = 5(4 − z)/3.",
  ),

  // Forming formulae (6)
  q(
    "Sebuah dewan mengenakan sewa RM120 dan RM8 bagi setiap kerusi n. Bentukkan rumus jumlah kos C.",
    "A hall charges RM120 rent and RM8 for each of n chairs. Form the total cost formula C.",
    "C = 120 + 8n",
    ["C = 128n", "C = 120n + 8", "C = 120 + n/8"],
    "Sewa tetap ditambah kepada kos kerusi: C = 120 + 8n.",
    "Add the fixed rent to the chair cost: C = 120 + 8n.",
  ),
  q(
    "Selepas diskaun RMd, harga sebuah beg RMp menjadi RMH. Bentukkan rumus H.",
    "After a discount of RMd, a bag priced at RMp costs RMH. Form the formula H.",
    "H = p − d",
    ["H = p + d", "H = pd", "H = d − p"],
    "Harga selepas diskaun ialah harga asal tolak diskaun: H = p − d.",
    "The discounted price is original price minus discount: H = p − d.",
  ),
  q(
    "Siti mempunyai RMm dan menyimpan RMk sehari selama 7 hari. Bentukkan rumus wang akhirnya W.",
    "Siti has RMm and saves RMk per day for 7 days. Form her final amount W.",
    "W = m + 7k",
    ["W = 7m + k", "W = 7(m + k)", "W = m + k/7"],
    "Simpanan baharu ialah 7k, lalu W = m + 7k.",
    "The new savings are 7k, so W = m + 7k.",
  ),
  q(
    "Sebuah segi tiga mempunyai tapak b dan tinggi h. Bentukkan rumus luas L.",
    "A triangle has base b and height h. Form its area formula L.",
    "L = bh/2",
    ["L = 2bh", "L = b + h/2", "L = (b + h)/2"],
    "Luas segi tiga ialah separuh hasil darab tapak dengan tinggi: L = bh/2.",
    "A triangle's area is half the product of base and height: L = bh/2.",
  ),
  q(
    "Jarak d ditempuh pada laju v selama t jam. Bentukkan rumus d.",
    "A distance d is travelled at speed v for t hours. Form the formula d.",
    "d = vt",
    ["d = v/t", "d = t/v", "d = v + t"],
    "Jarak = laju × masa, maka d = vt.",
    "Distance = speed × time, so d = vt.",
  ),
  q(
    "Harga n pen masing-masing RMp dikenakan caj penghantaran RMc. Bentukkan rumus jumlah bayaran B.",
    "The price of n pens at RMp each includes an RMc delivery charge. Form the total payment formula B.",
    "B = np + c",
    ["B = n(p + c)", "B = np − c", "B = n + p + c"],
    "Kos pen ialah np dan caj c dibayar sekali: B = np + c.",
    "The pens cost np and charge c is paid once: B = np + c.",
  ),

  // Squares and square roots (4)
  q(
    "Diberi A = s². Ungkapkan s sebagai perkara rumus jika s positif.",
    "Given A = s², express s as the subject if s is positive.",
    "s = √A",
    ["s = A²", "s = A/2", "s = 2√A"],
    "Ambil punca kuasa dua kedua-dua belah: s = √A.",
    "Take the square root of both sides: s = √A.",
  ),
  q(
    "Jika K = 4x² dan x positif, jadikan x perkara rumus.",
    "If K = 4x² and x is positive, make x the subject.",
    "x = √K/2",
    ["x = √(K/2)", "x = K/4", "x = 2√K"],
    "x² = K/4, jadi x = √(K/4) = √K/2.",
    "x² = K/4, so x = √(K/4) = √K/2.",
  ),
  q(
    "Diberi V = a³. Cari a apabila V = 125.",
    "Given V = a³, find a when V = 125.",
    "5",
    ["15", "25", "625"],
    "a = ∛125 = 5 kerana 5³ = 125.",
    "a = ∛125 = 5 because 5³ = 125.",
  ),
  q(
    "Diberi y = √(x + 1). Cari y apabila x = 24.",
    "Given y = √(x + 1), find y when x = 24.",
    "5",
    ["4", "6", "25"],
    "y = √(24 + 1) = √25 = 5.",
    "y = √(24 + 1) = √25 = 5.",
  ),

  // Contextual applications (4)
  q(
    "Tambang T diberi oleh T = 4 + 1.5k, dengan k jarak dalam km. Berapakah tambang untuk 8 km?",
    "A fare T is given by T = 4 + 1.5k, where k is distance in km. What is the fare for 8 km?",
    "RM16",
    ["RM12", "RM15.50", "RM20"],
    "T = 4 + 1.5(8) = 4 + 12 = RM16.",
    "T = 4 + 1.5(8) = 4 + 12 = RM16.",
  ),
  q(
    "Suhu F diberi oleh F = 9C/5 + 32. Tentukan F apabila C = 20.",
    "Temperature F is given by F = 9C/5 + 32. Determine F when C = 20.",
    "68",
    ["36", "52", "84"],
    "F = 9(20)/5 + 32 = 36 + 32 = 68.",
    "F = 9(20)/5 + 32 = 36 + 32 = 68.",
  ),
  q(
    "Jumlah mata M = 10w − 3l. Cari M jika sebuah pasukan menang 6 kali dan kalah 4 kali.",
    "A score is M = 10w − 3l. Find M if a team wins 6 times and loses 4 times.",
    "48",
    ["42", "54", "72"],
    "M = 10(6) − 3(4) = 60 − 12 = 48.",
    "M = 10(6) − 3(4) = 60 − 12 = 48.",
  ),
  q(
    "Perimeter taman ialah P = 2(l + w). Jika P = 34 m dan l = 10 m, cari w.",
    "A garden perimeter is P = 2(l + w). If P = 34 m and l = 10 m, find w.",
    "7 m",
    ["4 m", "12 m", "14 m"],
    "34/2 = 10 + w, jadi 17 = 10 + w dan w = 7 m.",
    "34/2 = 10 + w, so 17 = 10 + w and w = 7 m.",
  ),

  // Objective 3 — Challenge: multi-step changes of subject (8)
  q(
    "Diberi y = (3x − 4)/5. Ungkapkan x sebagai perkara rumus.",
    "Given y = (3x − 4)/5. Express x as the subject.",
    "x = (5y + 4)/3",
    ["x = (5y − 4)/3", "x = 5(y + 4)/3", "x = (3y + 4)/5"],
    "5y = 3x − 4, maka 3x = 5y + 4 dan x = (5y + 4)/3.",
    "5y = 3x − 4, so 3x = 5y + 4 and x = (5y + 4)/3.",
  ),
  q(
    "Dalam A = (a + b)h/2, jadikan b perkara rumus.",
    "In A = (a + b)h/2, make b the subject.",
    "b = 2A/h − a",
    ["b = 2A/(h − a)", "b = 2Ah − a", "b = 2A/h + a"],
    "2A/h = a + b, jadi b = 2A/h − a.",
    "2A/h = a + b, hence b = 2A/h − a.",
  ),
  q(
    "Diberi v² = u² + 2as. Ungkapkan s sebagai perkara rumus.",
    "Given v² = u² + 2as, express s as the subject.",
    "s = (v² − u²)/(2a)",
    ["s = (v − u)²/(2a)", "s = (v² + u²)/(2a)", "s = 2a(v² − u²)"],
    "Tolak u² dan bahagi dengan 2a: s = (v² − u²)/(2a).",
    "Subtract u² and divide by 2a: s = (v² − u²)/(2a).",
  ),
  q(
    "Diberi R = ab/(c + d). Jadikan d perkara rumus.",
    "Given R = ab/(c + d), make d the subject.",
    "d = ab/R − c",
    ["d = abR − c", "d = ab/(R − c)", "d = ab/R + c"],
    "R(c + d) = ab, maka c + d = ab/R dan d = ab/R − c.",
    "R(c + d) = ab, so c + d = ab/R and d = ab/R − c.",
  ),
  q(
    "Dalam p = √((q − r)/s), ungkapkan q sebagai perkara rumus.",
    "In p = √((q − r)/s), express q as the subject.",
    "q = sp² + r",
    ["q = sp + r", "q = s(p² + r)", "q = sp² − r"],
    "Kuasa duakan: p² = (q − r)/s. Maka q = sp² + r.",
    "Square both sides: p² = (q − r)/s. Hence q = sp² + r.",
  ),
  q(
    "Diberi T = 2π√(L/g). Jadikan L perkara rumus.",
    "Given T = 2π√(L/g), make L the subject.",
    "L = gT²/(4π²)",
    ["L = gT/(2π)", "L = 4π²gT²", "L = T²/(4π²g)"],
    "T/(2π) = √(L/g). Kuasa duakan dan darab g: L = gT²/(4π²).",
    "T/(2π) = √(L/g). Square and multiply by g: L = gT²/(4π²).",
  ),
  q(
    "Diberi 1/f = 1/u + 1/v. Ungkapkan v sebagai perkara rumus.",
    "Given 1/f = 1/u + 1/v. Express v as the subject.",
    "v = fu/(u − f)",
    ["v = fu/(f − u)", "v = (u − f)/(fu)", "v = f + u"],
    "1/v = 1/f − 1/u = (u − f)/(fu), maka v = fu/(u − f).",
    "1/v = 1/f − 1/u = (u − f)/(fu), so v = fu/(u − f).",
  ),
  q(
    "Dalam z = a/(b − cx), jadikan x perkara rumus.",
    "In z = a/(b − cx), make x the subject.",
    "x = (bz − a)/(cz)",
    ["x = (a − bz)/(cz)", "x = (b − az)/c", "x = a/(bz − c)"],
    "z(b − cx) = a, jadi bz − a = czx dan x = (bz − a)/(cz).",
    "z(b − cx) = a, so bz − a = czx and x = (bz − a)/(cz).",
  ),

  // Deriving formulae from situations (6)
  q(
    "Sebuah kelab mengenakan yuran RMf serta RMm sebulan selama n bulan. Bentukkan rumus jumlah bayaran J, kemudian jadikan n perkara rumus.",
    "A club charges an RMf fee plus RMm per month for n months. Form total payment J, then make n the subject.",
    "J = f + mn; n = (J − f)/m",
    ["J = n(f + m); n = J/(f + m)", "J = fm + n; n = J − fm", "J = f + m + n; n = J − f − m"],
    "Jumlah ialah f + mn. Menolak f dan membahagi m memberi n = (J − f)/m.",
    "The total is f + mn. Subtracting f and dividing by m gives n = (J − f)/m.",
  ),
  q(
    "Umur ibu ialah tiga kali umur anak ditambah 5 tahun. Jika umur ibu I dan anak a, formula manakah betul?",
    "A mother's age is five more than three times her child's age. If their ages are M and a, which formula is correct?",
    ["I = 3a + 5", "M = 3a + 5"],
    [
      ["I = 3(a + 5)", "M = 3(a + 5)"],
      ["I = a + 15", "M = a + 15"],
      ["I = 5a + 3", "M = 5a + 3"],
    ],
    "Tiga kali umur anak ialah 3a, kemudian tambah 5: I = 3a + 5.",
    "Three times the child's age is 3a, then add 5: M = 3a + 5.",
  ),
  q(
    "Sebuah reben panjang L cm dipotong kepada n bahagian sama panjang x cm dan berbaki 2 cm. Bentukkan rumus L.",
    "A ribbon of length L cm is cut into n equal pieces of x cm with 2 cm left. Form the formula L.",
    "L = nx + 2",
    ["L = n(x + 2)", "L = nx − 2", "L = n + x + 2"],
    "Panjang bahagian ialah nx dan baki 2 cm ditambah sekali: L = nx + 2.",
    "The pieces total nx and the 2 cm remainder is added once: L = nx + 2.",
  ),
  q(
    "Sebuah kedai memberi diskaun 20% pada harga asal p. Bentukkan rumus harga jualan H.",
    "A shop gives a 20% discount on original price p. Form the selling-price formula H.",
    "H = 0.8p",
    ["H = 0.2p", "H = p − 20", "H = 1.2p"],
    "Harga jualan ialah 100% − 20% = 80% daripada p, iaitu H = 0.8p.",
    "The selling price is 100% − 20% = 80% of p, so H = 0.8p.",
  ),
  q(
    "Sebuah bingkai segi empat tepat mempunyai perimeter P, panjang l dan lebar w. Formula manakah memberi w terus?",
    "A rectangular frame has perimeter P, length l and width w. Which formula gives w directly?",
    "w = P/2 − l",
    ["w = P − 2l", "w = P/2 + l", "w = (P − l)/2"],
    "Daripada P = 2(l + w), P/2 = l + w, jadi w = P/2 − l.",
    "From P = 2(l + w), P/2 = l + w, so w = P/2 − l.",
  ),
  q(
    "Jumlah kos menghasilkan n cenderamata ialah K = a + bn. Apakah formula kos purata setiap cenderamata, M?",
    "The total cost of making n souvenirs is K = a + bn. What is the average cost per souvenir, M?",
    "M = a/n + b",
    ["M = a + b/n", "M = an + b", "M = (a + b)n"],
    "M = K/n = (a + bn)/n = a/n + b.",
    "M = K/n = (a + bn)/n = a/n + b.",
  ),

  // Determine an unknown (6)
  q(
    "Diberi y = 4x − 7. Jika y = 21, tentukan x.",
    "Given y = 4x − 7. If y = 21, determine x.",
    "7",
    ["3.5", "5", "14"],
    "21 = 4x − 7, jadi 4x = 28 dan x = 7.",
    "21 = 4x − 7, so 4x = 28 and x = 7.",
  ),
  q(
    "Luas segi tiga A = bh/2 ialah 54 cm². Jika b = 12 cm, cari h.",
    "A triangle has area A = bh/2 of 54 cm². If b = 12 cm, find h.",
    "9 cm",
    ["4.5 cm", "18 cm", "42 cm"],
    "54 = 12h/2 = 6h, maka h = 9 cm.",
    "54 = 12h/2 = 6h, so h = 9 cm.",
  ),
  q(
    "Diberi v = u + at. Jika v = 25, u = 7 dan t = 6, cari a.",
    "Given v = u + at. If v = 25, u = 7 and t = 6, find a.",
    "3",
    ["2", "4", "5⅓"],
    "25 = 7 + 6a, jadi 18 = 6a dan a = 3.",
    "25 = 7 + 6a, so 18 = 6a and a = 3.",
  ),
  q(
    "Jika C = 5n + 12 dan C = 47, berapakah n?",
    "If C = 5n + 12 and C = 47, what is n?",
    "7",
    ["5", "9", "11.8"],
    "47 − 12 = 5n, maka 35 = 5n dan n = 7.",
    "47 − 12 = 5n, so 35 = 5n and n = 7.",
  ),
  q(
    "Diberi Q = (p − 2q)/3. Jika Q = 4 dan q = 3, cari p.",
    "Given Q = (p − 2q)/3. If Q = 4 and q = 3, find p.",
    "18",
    ["6", "10", "30"],
    "4 = (p − 6)/3, jadi 12 = p − 6 dan p = 18.",
    "4 = (p − 6)/3, so 12 = p − 6 and p = 18.",
  ),
  q(
    "Rumus S = a(1 + r) memberi S = 240 apabila a = 200. Cari r.",
    "The formula S = a(1 + r) gives S = 240 when a = 200. Find r.",
    "0.2",
    ["0.04", "0.8", "1.2"],
    "240/200 = 1 + r, jadi 1.2 = 1 + r dan r = 0.2.",
    "240/200 = 1 + r, so 1.2 = 1 + r and r = 0.2.",
  ),

  // Powers and roots (5)
  q(
    "Diberi A = πr². Jika A = 154 cm² dan π = 22/7, cari r.",
    "Given A = πr². If A = 154 cm² and π = 22/7, find r.",
    "7 cm",
    ["3.5 cm", "14 cm", "49 cm"],
    "r² = 154 ÷ (22/7) = 49, maka r = 7 cm.",
    "r² = 154 ÷ (22/7) = 49, so r = 7 cm.",
  ),
  q(
    "Jika y = √(3x + 1) dan y = 5, tentukan x.",
    "If y = √(3x + 1) and y = 5, determine x.",
    "8",
    ["4/3", "24/3", "26/3"],
    "Kuasa duakan: 25 = 3x + 1. Maka 3x = 24 dan x = 8.",
    "Square both sides: 25 = 3x + 1. Hence 3x = 24 and x = 8.",
  ),
  q(
    "Diberi V = l³. Jika panjang sisi l digandakan, berapa kali ganda V berubah?",
    "Given V = l³. If side length l is doubled, by what factor does V change?",
    ["8 kali ganda", "8 times"],
    [
      ["2 kali ganda", "2 times"],
      ["4 kali ganda", "4 times"],
      ["6 kali ganda", "6 times"],
    ],
    "(2l)³ = 8l³, jadi V menjadi 8 kali ganda.",
    "(2l)³ = 8l³, so V becomes 8 times as large.",
  ),
  q(
    "Dalam K = m² − n², jadikan m perkara rumus jika m positif.",
    "In K = m² − n², make m the subject if m is positive.",
    "m = √(K + n²)",
    ["m = √K + n", "m = √(K − n²)", "m = K + n²"],
    "m² = K + n², lalu m = √(K + n²).",
    "m² = K + n², hence m = √(K + n²).",
  ),
  q(
    "Diberi p = ∛(q/2). Ungkapkan q sebagai perkara rumus.",
    "Given p = ∛(q/2), express q as the subject.",
    "q = 2p³",
    ["q = 2p", "q = p³/2", "q = 2√p"],
    "Kuasa tiga kedua-dua belah: p³ = q/2, maka q = 2p³.",
    "Cube both sides: p³ = q/2, so q = 2p³.",
  ),

  // Problem solving / KBAT (5)
  q(
    "Dua pelan data diberi oleh A = 20 + 3g dan B = 8 + 5g, dengan g dalam GB. Pada penggunaan berapakah kos sama?",
    "Two data plans are A = 20 + 3g and B = 8 + 5g, with g in GB. At what usage are the costs equal?",
    "6 GB",
    ["4 GB", "10 GB", "14 GB"],
    "Samakan kos: 20 + 3g = 8 + 5g. Maka 12 = 2g dan g = 6 GB.",
    "Equate costs: 20 + 3g = 8 + 5g. Thus 12 = 2g and g = 6 GB.",
  ),
  q(
    "Rumus masa perjalanan ialah t = d/v. Jika jarak dinaikkan 20% dan laju tidak berubah, apakah perubahan t?",
    "Travel time is t = d/v. If distance increases by 20% while speed is unchanged, how does t change?",
    ["Bertambah 20%", "It increases by 20%"],
    [
      ["Berkurang 20%", "It decreases by 20%"],
      ["Bertambah 10%", "It increases by 10%"],
      ["Tidak berubah", "It is unchanged"],
    ],
    "t berkadar terus dengan d apabila v tetap, jadi t bertambah 20%.",
    "t is directly proportional to d when v is fixed, so t increases by 20%.",
  ),
  q(
    "Sebuah segi empat tepat mempunyai luas 48 cm² dan panjangnya 2 cm lebih daripada lebarnya w. Persamaan manakah perlu diselesaikan?",
    "A rectangle has area 48 cm² and its length is 2 cm more than width w. Which equation should be solved?",
    "w(w + 2) = 48",
    ["2w + 2(w + 2) = 48", "w + 2 = 48w", "2w(w + 2) = 48"],
    "Panjang = w + 2 dan luas = panjang × lebar, maka w(w + 2) = 48.",
    "Length = w + 2 and area = length × width, so w(w + 2) = 48.",
  ),
  q(
    "Formula C = 50 + 4n digunakan untuk tempahan. Selepas baucar RM18, bayaran ialah RM92. Berapa item ditempah?",
    "The formula C = 50 + 4n is used for an order. After an RM18 voucher, the payment is RM92. How many items were ordered?",
    "15",
    ["6", "10", "19"],
    "Kos sebelum baucar = 92 + 18 = 110. Jadi 50 + 4n = 110, maka n = 15.",
    "Cost before the voucher = 92 + 18 = 110. Thus 50 + 4n = 110, so n = 15.",
  ),
  q(
    "Diberi A = bh/2. Tapak dikurangkan separuh tetapi luas hendak dikekalkan. Apakah perlu berlaku kepada tinggi?",
    "Given A = bh/2, the base is halved but the area must stay the same. What must happen to the height?",
    ["Tinggi digandakan", "The height must double"],
    [
      ["Tinggi juga diseparuhkan", "The height must also halve"],
      ["Tinggi ditambah 2", "The height must increase by 2"],
      ["Tinggi tidak berubah", "The height is unchanged"],
    ],
    "Hasil darab bh mesti kekal. Jika b menjadi separuh, h mesti digandakan.",
    "The product bh must remain constant. If b is halved, h must double.",
  ),
];
