import type { Flashcard } from "@/data/content";

export const scienceF2C8FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c8-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya?",
    back: "Tarikan atau tolakan ke atas sesuatu objek.",
  },
  {
    id: "sci-f2-c8-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah daya ialah kuantiti vektor?",
    back: "Kerana daya mempunyai magnitud dan arah, serta titik tindakan.",
  },
  {
    id: "sci-f2-c8-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud titik tindakan (point of application)?",
    back: "Kawasan di mana daya yang dikenakan tertumpu.",
  },
  {
    id: "sci-f2-c8-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah unit SI bagi daya?",
    back: "Newton (N).",
  },
  {
    id: "sci-f2-c8-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berapakah berat objek berjisim 1 kg di Bumi?",
    back: "10 N (objek berjisim 100 g mempunyai berat 1 N).",
  },
  {
    id: "sci-f2-c8-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah alat yang digunakan untuk mengukur daya?",
    back: "Penimbang spring (spring balance), berdasarkan prinsip pengembangan spring.",
  },
  {
    id: "sci-f2-c8-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya graviti?",
    back: "Daya yang menumpu ke arah pusat Bumi, menyebabkan objek yang dilemparkan ke atas jatuh semula ke Bumi.",
  },
  {
    id: "sci-f2-c8-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya geseran?",
    back: "Daya yang merintangi pergerakan antara dua permukaan yang bersentuhan, bertindak bertentangan dengan arah gerakan.",
  },
  {
    id: "sci-f2-c8-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya normal?",
    back: "Daya yang terhasil apabila sesuatu objek bersentuhan dengan permukaan.",
  },
  {
    id: "sci-f2-c8-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah definisi berat?",
    back: "Daya graviti yang bertindak ke atas sesuatu objek.",
  },
  {
    id: "sci-f2-c8-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya keapungan?",
    back: "Daya tujahan yang bertindak ke atas objek yang terapung di permukaan bendalir.",
  },
  {
    id: "sci-f2-c8-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya kenyal?",
    back: "Daya yang wujud apabila sesuatu bahan diregangkan atau dimampatkan, contoh spring.",
  },
  {
    id: "sci-f2-c8-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Namakan lima jenis daya utama yang dipelajari.",
    back: "Daya graviti, daya geseran, daya normal, daya kenyal, daya keapungan.",
  },
  {
    id: "sci-f2-c8-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah prinsip pasangan tindakan-tindak balas?",
    back: "Bagi setiap daya tindakan, wujud daya tindak balas dengan magnitud sama tetapi dalam arah bertentangan.",
  },
  {
    id: "sci-f2-c8-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Namakan lima kesan daya ke atas objek.",
    back: "Menggerakkan objek pegun, menghentikan objek bergerak, mengubah kelajuan, mengubah arah, mengubah bentuk dan saiz.",
  },
  {
    id: "sci-f2-c8-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah formula bagi daya keapungan?",
    back: "Daya keapungan = Berat sebenar − Berat ketara.",
  },
  {
    id: "sci-f2-c8-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud berat sebenar dan berat ketara?",
    back: "Berat sebenar: berat objek di udara. Berat ketara: berat objek yang direndam dalam bendalir.",
  },
  {
    id: "sci-f2-c8-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud momen daya?",
    back: "Kesan putaran yang dihasilkan oleh daya yang bertindak ke atas objek pada titik tetap (pangsi/fulkrum).",
  },
  {
    id: "sci-f2-c8-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah formula bagi momen daya dan unitnya?",
    back: "Momen daya = Daya (N) × Jarak berserenjang daripada pangsi kepada daya (m); unit newton meter (N m).",
  },
  {
    id: "sci-f2-c8-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah formula bagi tekanan dan unitnya?",
    back: "Tekanan = Daya (N) / Luas permukaan (m²); unit pascal (Pa), 1 Pa = 1 N m⁻².",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c8-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan situasi objek di atas meja dan objek terapung di atas air dari segi pasangan tindakan-tindak balas.",
    back: "Di atas meja: berat seimbang dengan daya normal. Terapung di air: berat seimbang dengan daya keapungan.",
  },
  {
    id: "sci-f2-c8-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah yang berlaku kepada dua troli bersentuhan yang dilancarkan dengan mekanisme spring?",
    back: "Kedua-dua troli bergerak pada jarak yang sama tetapi dalam arah bertentangan.",
  },
  {
    id: "sci-f2-c8-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan keadaan objek terapung dan tenggelam dari segi daya keapungan dan berat.",
    back: "Terapung: daya keapungan = berat objek. Tenggelam: daya keapungan kurang daripada berat objek.",
  },
  {
    id: "sci-f2-c8-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan ketumpatan objek yang terapung dan tenggelam berbanding cecair.",
    back: "Terapung: objek kurang tumpat daripada cecair (F > W). Tenggelam: objek lebih tumpat daripada cecair (F < W).",
  },
  {
    id: "sci-f2-c8-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berdasarkan jadual ketumpatan, kenapa gabus terapung tetapi besi tenggelam dalam air?",
    back: "Gabus (0.24 g cm⁻³) kurang tumpat daripada air (1.0 g cm⁻³); besi (7.9 g cm⁻³) lebih tumpat daripada air.",
  },
  {
    id: "sci-f2-c8-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah faktor yang mempengaruhi momen daya?",
    back: "Magnitud daya yang dikenakan dan jarak berserenjang daripada pangsi kepada daya.",
  },
  {
    id: "sci-f2-c8-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah prinsip momen tuil?",
    back: "Beban (N) × Jarak beban daripada fulkrum (m) = Daya kuasa (N) × Jarak daya kuasa daripada fulkrum (m).",
  },
  {
    id: "sci-f2-c8-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Namakan tiga bahagian tuil dan fungsinya.",
    back: "Daya kuasa (effort): daya yang dikenakan. Beban (load): berat yang diangkat. Fulkrum: titik sokongan tetap.",
  },
  {
    id: "sci-f2-c8-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan tuil kelas pertama, kedua dan ketiga.",
    back: "Kelas 1: fulkrum antara beban & daya kuasa (gunting). Kelas 2: beban antara fulkrum & daya kuasa (kereta sorong). Kelas 3: daya kuasa antara fulkrum & beban (joran pancing).",
  },
  {
    id: "sci-f2-c8-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berikan contoh setiap kelas tuil.",
    back: "Kelas 1: gunting, playar, pembuka tin. Kelas 2: kereta sorong, pemecah kacang. Kelas 3: penyepit ais, joran pancing.",
  },
  {
    id: "sci-f2-c8-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan kesan luas permukaan yang besar dan kecil terhadap tekanan.",
    back: "Luas kecil: tekanan lebih besar. Luas besar: tekanan lebih kecil (daya sama dikenakan).",
  },
  {
    id: "sci-f2-c8-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah teori kinetik gas berkaitan tekanan udara?",
    back: "Molekul udara bergerak bebas dan berlanggar dengan dinding bekas; kekerapan perlanggaran menghasilkan daya yang menolak dinding (tekanan udara).",
  },
  {
    id: "sci-f2-c8-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah dua faktor yang mempengaruhi tekanan udara/gas?",
    back: "Isi padu (semakin kecil isi padu, semakin tinggi tekanan); suhu (semakin tinggi suhu, semakin tinggi tekanan).",
  },
  {
    id: "sci-f2-c8-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud tekanan atmosfera dan bagaimana ia berubah dengan altitud?",
    back: "Tekanan yang dikenakan oleh atmosfera ke atas Bumi dan objek di atasnya; berkurang apabila altitud meningkat kerana tarikan graviti lebih lemah.",
  },
  {
    id: "sci-f2-c8-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bagaimanakah kedalaman mempengaruhi tekanan cecair?",
    back: "Tekanan cecair berkurang apabila kedalaman berkurang, contohnya gelembung udara membesar semasa naik ke permukaan air.",
  },
  {
    id: "sci-f2-c8-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berikan contoh aplikasi konsep tekanan udara/atmosfera dalam kehidupan harian.",
    back: "Tukul kebawa (plunger), bola Magdeburg, penyedut minuman, sifon, picagari dan pembersih vakum.",
  },
  {
    id: "sci-f2-c8-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berikan contoh aplikasi konsep tekanan dalam kehidupan harian.",
    back: "Bilah skid dan bilah kapak nipis (tekanan tinggi); jejari tayar traktor lebar dan tapak kaki gajah besar (tekanan rendah); stad pada but bola sepak.",
  },
  {
    id: "sci-f2-c8-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah tin susu pekat dengan dua lubang membolehkan susu mengalir lebih lancar?",
    back: "Kerana tekanan udara di dalam dan di luar tin menjadi sama dengan dua lubang, berbanding satu lubang.",
  },
  {
    id: "sci-f2-c8-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah dinding empangan direka lebih tebal di bahagian asas?",
    back: "Untuk menahan tekanan air yang lebih tinggi pada kedalaman yang lebih dalam.",
  },
  {
    id: "sci-f2-c8-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan kesan daya dari arah bertentangan dan dari arah sama terhadap kelajuan objek bergerak.",
    back: "Arah bertentangan: memperlahankan objek. Arah sama: mempercepatkan objek.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c8-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Daya 50 N dikenakan pada jarak 0.2 m daripada pangsi untuk mengetatkan nat. Berapakah momen daya?",
    back: "Momen daya = 50 N × 0.2 m = 10 N m.",
  },
  {
    id: "sci-f2-c8-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Daya 10 N digunakan untuk membuka penutup tin dengan sudu sepanjang 0.15 m. Berapakah momen daya?",
    back: "Momen daya = 10 N × 0.15 m = 1.5 N m.",
  },
  {
    id: "sci-f2-c8-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Jia Yin (200 N) dan Wei Hong (300 N) di jongkang-jongket; Wei Hong 2 m daripada fulkrum. Berapa jauh Jia Yin perlu duduk?",
    back: "200 N × d = 300 N × 2 m → d = 3 m daripada fulkrum.",
  },
  {
    id: "sci-f2-c8-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Batu besar 100 kg dipindahkan dengan fulkrum; jarak batu-fulkrum 0.5 m, jarak lelaki-fulkrum 2 m, daya graviti 10 N kg⁻¹. Berapakah daya kuasa?",
    back: "Beban = 1000 N. 1000 N × 0.5 m = Daya kuasa × 2 m → Daya kuasa = 250 N.",
  },
  {
    id: "sci-f2-c8-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Mengapakah gajah seberat 5000 kg tidak tenggelam ke dalam tanah?",
    back: "Luas permukaan tapak kakinya yang besar menghasilkan tekanan yang kecil ke atas tanah (Tekanan = Daya/Luas).",
  },
  {
    id: "sci-f2-c8-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah daya keapungan sama dengan berat sebenar?",
    back: "Tidak. Daya keapungan = Berat sebenar − Berat ketara, bukan sama dengan berat sebenar.",
  },
  {
    id: "sci-f2-c8-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah objek yang kurang tumpat daripada cecair akan tenggelam?",
    back: "Tidak. Objek yang kurang tumpat akan terapung kerana daya keapungan F > berat W.",
  },
  {
    id: "sci-f2-c8-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Mengapakah kapal kargo ditandakan dengan garis Plimsoll?",
    back: "Untuk tujuan keselamatan, kerana ketumpatan air laut berbeza mengikut suhu dan kepekatan garam di pelbagai bahagian dunia.",
  },
  {
    id: "sci-f2-c8-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Mengapakah tekanan atmosfera berkurang apabila altitud meningkat?",
    back: "Tarikan graviti yang lebih lemah pada altitud tinggi menjadikan udara kurang tumpat dan mengembang dengan lebih mudah.",
  },
  {
    id: "sci-f2-c8-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Mengapakah tin susu pekat berlubang dua mengalir lebih lancar berbanding berlubang satu?",
    back: "Tekanan udara di dalam dan di luar tin menjadi sama apabila ada dua lubang, membolehkan susu mengalir lebih lancar.",
  },
  {
    id: "sci-f2-c8-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[Fakta Penting] Sempena siapakah unit newton (N) dinamakan?",
    back: "Sir Isaac Newton, saintis dan ahli matematik yang menemui daya graviti.",
  },
  {
    id: "sci-f2-c8-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan pengiraan momen daya dengan markah penuh?",
    back: "Tuliskan formula Momen daya = Daya × Jarak berserenjang, gantikan nilai dengan unit yang betul, dan nyatakan unit jawapan (N m).",
  },
  {
    id: "sci-f2-c8-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Mengapakah dinding empangan direka lebih tebal di bahagian asas?",
    back: "Kerana tekanan cecair meningkat dengan kedalaman, jadi bahagian asas perlu menahan tekanan air yang lebih tinggi.",
  },
  {
    id: "sci-f2-c8-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah momen daya hanya bergantung kepada magnitud daya?",
    back: "Tidak. Momen daya bergantung kepada magnitud daya DAN jarak berserenjang daripada pangsi kepada daya.",
  },
  {
    id: "sci-f2-c8-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Apakah gelembung udara yang membesar semasa naik ke permukaan air membuktikan tentang tekanan cecair?",
    back: "Membuktikan tekanan cecair berkurang apabila kedalaman berkurang (semakin dekat permukaan, tekanan semakin rendah).",
  },
  {
    id: "sci-f2-c8-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[Fakta Penting] Susunkan bahan berikut mengikut ketumpatan menaik: emas, air, gabus, besi.",
    back: "Gabus (0.24) < Air (1.0) < Besi (7.9) < Emas (19.3) g cm⁻³.",
  },
  {
    id: "sci-f2-c8-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Mengapakah jejari tayar traktor dibuat besar dan lebar?",
    back: "Untuk meningkatkan luas permukaan sentuhan dengan tanah, mengurangkan tekanan supaya traktor tidak terbenam dalam tanah lembut.",
  },
  {
    id: "sci-f2-c8-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[KBAT] Mengapakah bilah kapak dan bilah skid dibuat nipis?",
    back: "Untuk mengurangkan luas permukaan supaya daya yang sama menghasilkan tekanan yang lebih besar, memudahkan pemotongan/luncuran.",
  },
  {
    id: "sci-f2-c8-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah daya tindakan dan daya tindak balas bertindak pada arah yang sama?",
    back: "Tidak. Daya tindak balas mempunyai magnitud yang sama tetapi bertindak dalam arah bertentangan dengan daya tindakan.",
  },
  {
    id: "sci-f2-c8-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Ringkaskan peta konsep Bab 8 dalam satu ayat.",
    back: "Daya (vektor dengan magnitud, arah, titik tindakan) mempunyai pelbagai jenis dan kesan, termasuk daya keapungan, momen daya pada tuil, dan tekanan (gas, atmosfera, cecair).",
  },
];
