import type { Flashcard } from "@/data/content";

export const scienceF2C8FlashcardsBM: Flashcard[] = [
  // Set 1: Jenis Daya & Kesannya
  {
    id: "sci-f2-c8-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya?",
    back: "Tarikan atau tolakan ke atas sesuatu objek.",
  },
  {
    id: "sci-f2-c8-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah daya ialah kuantiti vektor?",
    back: "Kerana daya mempunyai magnitud dan arah, serta titik aplikasi.",
  },
  {
    id: "sci-f2-c8-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud titik aplikasi (point of application)?",
    back: "Kawasan di mana daya yang dikenakan tertumpu.",
  },
  {
    id: "sci-f2-c8-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah unit SI bagi daya?",
    back: "Newton (N).",
  },
  {
    id: "sci-f2-c8-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah perbezaan antara jisim dan berat?",
    back: "Jisim ialah kuantiti jirim dalam objek (kg) dan tidak berubah; berat ialah daya graviti ke atas objek (N) dan bergantung pada graviti.",
  },
  {
    id: "sci-f2-c8-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah definisi berat?",
    back: "Daya graviti yang bertindak ke atas sesuatu objek.",
  },
  {
    id: "sci-f2-c8-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berapakah berat objek berjisim 1 kg di Bumi?",
    back: "10 N (objek berjisim 100 g mempunyai berat 1 N).",
  },
  {
    id: "sci-f2-c8-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah alat yang digunakan untuk mengukur daya?",
    back: "Neraca spring (spring balance), berdasarkan prinsip pengembangan spring.",
  },
  {
    id: "sci-f2-c8-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Namakan lima jenis daya utama yang dipelajari.",
    back: "Daya graviti, daya geseran, daya normal, daya kenyal, daya keapungan.",
  },
  {
    id: "sci-f2-c8-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya graviti?",
    back: "Daya yang menumpu ke arah pusat Bumi, menyebabkan objek yang dilemparkan ke atas jatuh semula ke Bumi.",
  },
  {
    id: "sci-f2-c8-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya geseran?",
    back: "Daya yang merintangi pergerakan antara dua permukaan yang bersentuhan, bertindak bertentangan dengan arah gerakan.",
  },
  {
    id: "sci-f2-c8-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya normal?",
    back: "Daya yang terhasil apabila sesuatu objek bersentuhan dengan permukaan.",
  },
  {
    id: "sci-f2-c8-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya kenyal?",
    back: "Daya yang wujud apabila sesuatu bahan diregangkan atau dimampatkan, contoh spring.",
  },
  {
    id: "sci-f2-c8-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud daya keapungan?",
    back: "Daya tujahan ke atas yang dikenakan oleh bendalir ke atas objek di dalam bendalir itu.",
  },
  {
    id: "sci-f2-c8-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah prinsip pasangan tindakan-tindak balas?",
    back: "Bagi setiap daya tindakan, wujud daya tindak balas dengan magnitud sama tetapi dalam arah bertentangan.",
  },
  {
    id: "sci-f2-c8-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Adakah daya tindakan dan daya tindak balas bertindak pada arah yang sama?",
    back: "Tidak. Daya tindak balas mempunyai magnitud yang sama tetapi bertindak dalam arah bertentangan dengan daya tindakan.",
  },
  {
    id: "sci-f2-c8-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Sebuah objek terletak di atas meja. Apakah dua daya yang bertindak ke atasnya dan saling mengimbangi?",
    back: "Beratnya (ke bawah) dan daya normal daripada meja (ke atas). Kedua-duanya daya seimbang pada objek yang sama, bukan pasangan tindakan-tindak balas.",
  },
  {
    id: "sci-f2-c8-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Apakah yang berlaku kepada dua troli bersentuhan yang dilancarkan dengan mekanisme spring?",
    back: "Kedua-duanya ditolak berjauhan dalam arah bertentangan oleh daya yang sama magnitud; jika kedua-dua troli sama jisim, ia bergerak pada jarak yang sama.",
  },
  {
    id: "sci-f2-c8-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Namakan lima kesan daya ke atas objek.",
    back: "Menggerakkan objek pegun, menghentikan objek bergerak, mengubah kelajuan, mengubah arah, mengubah bentuk dan saiz.",
  },
  {
    id: "sci-f2-c8-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Bandingkan kesan daya dari arah bertentangan dan dari arah sama terhadap kelajuan objek bergerak.",
    back: "Arah bertentangan: memperlahankan objek. Arah sama: mempercepatkan objek.",
  },
  // Set 2: Daya Keapungan, Momen & Tuil
  {
    id: "sci-f2-c8-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah formula bagi daya keapungan?",
    back: "Daya keapungan = Berat sebenar − Berat ketara.",
  },
  {
    id: "sci-f2-c8-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud berat sebenar dan berat ketara?",
    back: "Berat sebenar: berat objek di udara. Berat ketara: berat objek yang direndam dalam bendalir.",
  },
  {
    id: "sci-f2-c8-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Adakah daya keapungan sama dengan berat sebenar?",
    back: "Tidak. Daya keapungan = Berat sebenar − Berat ketara, bukan sama dengan berat sebenar.",
  },
  {
    id: "sci-f2-c8-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan keadaan objek terapung dan tenggelam dari segi daya keapungan dan berat.",
    back: "Terapung: daya keapungan = berat objek. Tenggelam: daya keapungan kurang daripada berat objek.",
  },
  {
    id: "sci-f2-c8-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan ketumpatan objek yang terapung dan tenggelam berbanding cecair.",
    back: "Terapung: objek kurang tumpat daripada cecair, dan semasa terapung pegun daya apungan sama dengan berat (F = W). Tenggelam: objek lebih tumpat daripada cecair, dan daya apungan kurang daripada berat (F < W).",
  },
  {
    id: "sci-f2-c8-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Adakah objek yang kurang tumpat daripada cecair akan tenggelam?",
    back: "Tidak. Objek yang kurang tumpat akan terapung. Semasa terapung dalam keadaan pegun, daya apungan F adalah sama dengan beratnya W (F = W) — bukan lebih besar daripadanya.",
  },
  {
    id: "sci-f2-c8-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Mengapakah gabus (0.24 g cm⁻³) terapung tetapi besi (7.9 g cm⁻³) tenggelam dalam air (1.0 g cm⁻³)?",
    back: "Gabus (0.24 g cm⁻³) kurang tumpat daripada air (1.0 g cm⁻³); besi (7.9 g cm⁻³) lebih tumpat daripada air.",
  },
  {
    id: "sci-f2-c8-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Susunkan bahan berikut mengikut ketumpatan menaik: emas, air, gabus, besi.",
    back: "Gabus (0.24) < Air (1.0) < Besi (7.9) < Emas (19.3) g cm⁻³.",
  },
  {
    id: "sci-f2-c8-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah kapal kargo ditandakan dengan garis Plimsoll?",
    back: "Untuk tujuan keselamatan, kerana ketumpatan air laut berbeza mengikut suhu dan kepekatan garam di pelbagai bahagian dunia.",
  },
  {
    id: "sci-f2-c8-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud momen daya?",
    back: "Kesan putaran yang dihasilkan oleh daya yang bertindak ke atas objek pada titik tetap (pangsi/fulkrum).",
  },
  {
    id: "sci-f2-c8-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah formula bagi momen daya dan unitnya?",
    back: "Momen daya = Daya (N) × Jarak tegak dari pangsi ke daya (m); unit newton meter (N m).",
  },
  {
    id: "sci-f2-c8-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah faktor yang mempengaruhi momen daya?",
    back: "Magnitud daya yang dikenakan dan jarak tegak dari pangsi ke daya.",
  },
  {
    id: "sci-f2-c8-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Namakan tiga bahagian tuil dan fungsinya.",
    back: "Daya kuasa (effort): daya yang dikenakan. Beban (load): berat yang diangkat. Fulkrum: titik sokongan tetap.",
  },
  {
    id: "sci-f2-c8-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah prinsip momen tuil?",
    back: "Beban (N) × Jarak beban daripada fulkrum (m) = Daya kuasa (N) × Jarak daya kuasa daripada fulkrum (m).",
  },
  {
    id: "sci-f2-c8-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan tuil kelas pertama, kedua dan ketiga.",
    back: "Kelas 1: fulkrum antara beban & daya kuasa (gunting). Kelas 2: beban antara fulkrum & daya kuasa (kereta sorong). Kelas 3: daya kuasa antara fulkrum & beban (joran pancing).",
  },
  {
    id: "sci-f2-c8-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berikan contoh setiap kelas tuil.",
    back: "Kelas 1: gunting, playar, pembuka tin. Kelas 2: kereta sorong, pemecah kacang. Kelas 3: penyepit ais, joran pancing.",
  },
  {
    id: "sci-f2-c8-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Daya 50 N dikenakan pada jarak 0.2 m daripada pangsi untuk mengetatkan nat. Berapakah momen daya?",
    back: "Momen daya = 50 N × 0.2 m = 10 N m.",
  },
  {
    id: "sci-f2-c8-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Daya 10 N digunakan untuk membuka penutup tin dengan sudu sepanjang 0.15 m. Berapakah momen daya?",
    back: "Momen daya = 10 N × 0.15 m = 1.5 N m.",
  },
  {
    id: "sci-f2-c8-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Jia Yin (200 N) dan Wei Hong (300 N) di jongkang-jongket; Wei Hong 2 m daripada fulkrum. Berapa jauh Jia Yin perlu duduk?",
    back: "200 N × d = 300 N × 2 m → d = 3 m daripada fulkrum.",
  },
  {
    id: "sci-f2-c8-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Batu besar 100 kg dipindahkan dengan fulkrum; jarak batu-fulkrum 0.5 m, jarak lelaki-fulkrum 2 m, daya graviti 10 N kg⁻¹. Berapakah daya kuasa?",
    back: "Beban = 1000 N. 1000 N × 0.5 m = Daya kuasa × 2 m → Daya kuasa = 250 N.",
  },
  // Set 3: Tekanan
  {
    id: "sci-f2-c8-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah formula bagi tekanan dan unitnya?",
    back: "Tekanan = Daya (N) / Luas permukaan (m²); unit pascal (Pa), 1 Pa = 1 N m⁻².",
  },
  {
    id: "sci-f2-c8-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Daya 200 N bertindak ke atas luas 0.5 m². Berapakah tekanannya?",
    back: "P = F ÷ A = 200 N ÷ 0.5 m² = 400 Pa.",
  },
  {
    id: "sci-f2-c8-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Sebuah kotak yang beratnya 60 N terletak di atas luas 0.2 m². Berapakah tekanan yang dikenakannya?",
    back: "P = F ÷ A = 60 N ÷ 0.2 m² = 300 Pa.",
  },
  {
    id: "sci-f2-c8-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bandingkan kesan luas permukaan yang besar dan kecil terhadap tekanan.",
    back: "Luas kecil: tekanan lebih besar. Luas besar: tekanan lebih kecil (daya sama dikenakan).",
  },
  {
    id: "sci-f2-c8-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berikan contoh aplikasi konsep tekanan dalam kehidupan harian.",
    back: "Bilah kasut luncur ais dan bilah kapak yang nipis (tekanan tinggi); tayar traktor yang lebar dan tapak kaki gajah yang besar (tekanan rendah); stad pada kasut bola sepak.",
  },
  {
    id: "sci-f2-c8-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah tayar traktor dibuat besar dan lebar?",
    back: "Untuk meningkatkan luas permukaan yang bersentuhan dengan tanah, mengurangkan tekanan supaya traktor tidak terbenam dalam tanah lembut.",
  },
  {
    id: "sci-f2-c8-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah bilah kapak dan bilah kasut luncur ais dibuat nipis?",
    back: "Untuk mengurangkan luas permukaan supaya daya yang sama menghasilkan tekanan yang lebih besar, memudahkan pemotongan/luncuran.",
  },
  {
    id: "sci-f2-c8-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah gajah yang berjisim 5000 kg tidak terbenam ke dalam tanah lembut?",
    back: "Luas permukaan tapak kakinya yang besar menghasilkan tekanan yang kecil ke atas tanah (Tekanan = Daya/Luas).",
  },
  {
    id: "sci-f2-c8-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah teori kinetik gas berkaitan tekanan udara?",
    back: "Molekul udara bergerak bebas dan berlanggar dengan dinding bekas; kekerapan perlanggaran menghasilkan daya yang menolak dinding (tekanan udara).",
  },
  {
    id: "sci-f2-c8-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah dua faktor yang mempengaruhi tekanan udara/gas?",
    back: "Isi padu (semakin kecil isi padu, semakin tinggi tekanan); suhu (semakin tinggi suhu, semakin tinggi tekanan).",
  },
  {
    id: "sci-f2-c8-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Apakah maksud tekanan atmosfera dan bagaimana ia berubah dengan altitud?",
    back: "Tekanan yang dikenakan oleh atmosfera ke atas Bumi dan objek di atasnya; berkurang apabila altitud meningkat kerana semakin sedikit udara berada di atas kita.",
  },
  {
    id: "sci-f2-c8-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah telinga terasa 'berdesing' semasa mendaki gunung?",
    back: "Tekanan atmosfera berkurang dengan altitud, jadi tekanan udara di dalam telinga menjadi lebih tinggi daripada di luar sehingga tekanan menjadi seimbang.",
  },
  {
    id: "sci-f2-c8-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bagaimanakah kedalaman mempengaruhi tekanan cecair?",
    back: "Tekanan cecair berkurang apabila kedalaman berkurang, contohnya gelembung udara membesar semasa naik ke permukaan air.",
  },
  {
    id: "sci-f2-c8-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah dinding empangan direka lebih tebal di bahagian asas?",
    back: "Untuk menahan tekanan air yang lebih tinggi pada kedalaman yang lebih dalam.",
  },
  {
    id: "sci-f2-c8-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front:
      "Apakah gelembung udara yang membesar semasa naik ke permukaan air membuktikan tentang tekanan cecair?",
    back: "Membuktikan tekanan cecair berkurang apabila kedalaman berkurang (semakin dekat permukaan, tekanan semakin rendah).",
  },
  {
    id: "sci-f2-c8-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Berikan contoh aplikasi konsep tekanan udara/atmosfera dalam kehidupan harian.",
    back: "Pam sedut sinki, hemisfera Magdeburg, penyedut minuman, sifon, picagari dan penyedut hampagas.",
  },
  {
    id: "sci-f2-c8-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bagaimanakah penyedut minuman berfungsi?",
    back: "Sedutan merendahkan tekanan udara dalam penyedut; tekanan atmosfera yang lebih tinggi pada minuman menolaknya naik ke dalam penyedut.",
  },
  {
    id: "sci-f2-c8-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bagaimanakah picagari menyedut cecair?",
    back: "Menarik omboh merendahkan tekanan dalam picagari, jadi tekanan atmosfera menolak cecair masuk.",
  },
  {
    id: "sci-f2-c8-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Bagaimanakah penyedut hampagas menggunakan tekanan udara?",
    back: "Kipasnya merendahkan tekanan udara di dalam, jadi tekanan udara luar yang lebih tinggi menolak udara dan debu masuk ke dalam penyedut.",
  },
  {
    id: "sci-f2-c8-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "bm",
    front: "Mengapakah tin susu pekat dengan dua lubang membolehkan susu mengalir lebih lancar?",
    back: "Kerana tekanan udara di dalam dan di luar tin menjadi sama dengan dua lubang, berbanding satu lubang.",
  },
];
