import type { Flashcard } from "@/data/content";

export const scienceF2C8FlashcardsDLP: Flashcard[] = [
  // Deck 1: Basics (Cards 1-20)
  {
    id: "sci-f2-c8-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the meaning of force?",
    back: "A pull or a push upon an object.",
  },
  {
    id: "sci-f2-c8-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Why is force a vector quantity?",
    back: "Because force has magnitude and direction, as well as a point of application.",
  },
  {
    id: "sci-f2-c8-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the point of application of a force?",
    back: "The area where the applied force is concentrated.",
  },
  {
    id: "sci-f2-c8-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the S.I. unit of force?",
    back: "Newton (N).",
  },
  {
    id: "sci-f2-c8-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the weight of an object with a mass of 1 kg on Earth?",
    back: "10 N (an object with a mass of 100 g has a weight of 1 N).",
  },
  {
    id: "sci-f2-c8-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What instrument is used to measure force?",
    back: "Spring balance, based on the principle of spring extension.",
  },
  {
    id: "sci-f2-c8-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is gravitational force?",
    back: "The force that points towards the centre of the Earth, causing objects thrown upward to fall back to Earth.",
  },
  {
    id: "sci-f2-c8-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is frictional force?",
    back: "The force that resists movement between two surfaces in contact, acting opposite to the direction of motion.",
  },
  {
    id: "sci-f2-c8-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is normal force?",
    back: "The force produced when an object is in contact with a surface.",
  },
  {
    id: "sci-f2-c8-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the definition of weight?",
    back: "The gravitational force acting on an object.",
  },
  {
    id: "sci-f2-c8-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is buoyant force?",
    back: "The thrust force acting on an object floating on the surface of a fluid.",
  },
  {
    id: "sci-f2-c8-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is elastic force?",
    back: "The force that exists when a material is stretched or compressed, e.g. a spring.",
  },
  {
    id: "sci-f2-c8-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Name the five main types of force studied.",
    back: "Gravitational force, frictional force, normal force, elastic force, buoyant force.",
  },
  {
    id: "sci-f2-c8-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the action-reaction pair principle?",
    back: "For every action force, there exists a reaction force of the same magnitude but in the opposite direction.",
  },
  {
    id: "sci-f2-c8-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Name five effects of force on an object.",
    back: "Moving a stationary object, stopping a moving object, changing speed, changing direction, changing shape and size.",
  },
  {
    id: "sci-f2-c8-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the formula for buoyant force?",
    back: "Buoyant force = Actual weight − Apparent weight.",
  },
  {
    id: "sci-f2-c8-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the difference between actual weight and apparent weight?",
    back: "Actual weight: weight of an object in air. Apparent weight: weight of an object immersed in fluid.",
  },
  {
    id: "sci-f2-c8-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is moment of force?",
    back: "The turning effect produced by a force acting on an object at a fixed point (pivot or fulcrum).",
  },
  {
    id: "sci-f2-c8-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the formula and unit for moment of force?",
    back: "Moment of force = Force (N) × Perpendicular distance from pivot to force (m); unit newton metre (N m).",
  },
  {
    id: "sci-f2-c8-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the formula and unit for pressure?",
    back: "Pressure = Force (N) / Surface area (m²); unit pascal (Pa), 1 Pa = 1 N m⁻².",
  },

  // Deck 2: Understanding (Cards 21-40)
  {
    id: "sci-f2-c8-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Compare an object on a table and an object floating on water in terms of action-reaction pairs.",
    back: "On a table: weight balanced by normal force. Floating on water: weight balanced by buoyant force.",
  },
  {
    id: "sci-f2-c8-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What happens to two trolleys in contact launched with a spring mechanism?",
    back: "Both trolleys move the same distance but in opposite directions.",
  },
  {
    id: "sci-f2-c8-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Compare floating and submerging conditions in terms of buoyant force and weight.",
    back: "Floating: buoyant force = weight of object. Submerging: buoyant force is less than weight of object.",
  },
  {
    id: "sci-f2-c8-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Compare density of objects that float versus submerge in a liquid.",
    back: "Floating: object less dense than liquid (F > W). Submerging: object more dense than liquid (F < W).",
  },
  {
    id: "sci-f2-c8-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Based on the density table, why does cork float but iron submerge in water?",
    back: "Cork (0.24 g cm⁻³) is less dense than water (1.0 g cm⁻³); iron (7.9 g cm⁻³) is denser than water.",
  },
  {
    id: "sci-f2-c8-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What factors affect moment of force?",
    back: "The magnitude of force applied and the perpendicular distance from the pivot to the force.",
  },
  {
    id: "sci-f2-c8-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is the principle of moments for a lever?",
    back: "Load (N) × Distance of load from fulcrum (m) = Effort (N) × Distance of effort from fulcrum (m).",
  },
  {
    id: "sci-f2-c8-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Name the three parts of a lever and their functions.",
    back: "Effort: the force applied. Load: the weight being lifted. Fulcrum: the fixed support point.",
  },
  {
    id: "sci-f2-c8-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Compare first, second and third class levers.",
    back: "Class 1: fulcrum between load & effort (scissors). Class 2: load between fulcrum & effort (wheelbarrow). Class 3: effort between fulcrum & load (fishing rod).",
  },
  {
    id: "sci-f2-c8-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Give an example of each class of lever.",
    back: "Class 1: scissors, pliers, can opener. Class 2: wheelbarrow, nutcracker. Class 3: ice tongs, fishing rod.",
  },
  {
    id: "sci-f2-c8-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Compare the effect of small and large surface area on pressure.",
    back: "Small area: greater pressure. Large area: smaller pressure (same force applied).",
  },
  {
    id: "sci-f2-c8-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "How does the kinetic theory of gas relate to air pressure?",
    back: "Air molecules move freely and collide with the container walls; frequency of collision produces a force pushing against the walls (air pressure).",
  },
  {
    id: "sci-f2-c8-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What are the two factors affecting air/gas pressure?",
    back: "Volume (the smaller the volume, the higher the pressure); temperature (the higher the temperature, the higher the pressure).",
  },
  {
    id: "sci-f2-c8-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "What is atmospheric pressure and how does it change with altitude?",
    back: "The pressure exerted by the atmosphere on the Earth and objects on it; decreases as altitude increases due to weaker gravitational attraction.",
  },
  {
    id: "sci-f2-c8-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "How does depth affect liquid pressure?",
    back: "Liquid pressure decreases as depth decreases, e.g. air bubbles become larger as they rise to the water surface.",
  },
  {
    id: "sci-f2-c8-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Give examples of air/atmospheric pressure applications in daily life.",
    back: "A plunger, Magdeburg hemispheres, a drinking straw, a syphon, a syringe and a vacuum cleaner.",
  },
  {
    id: "sci-f2-c8-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Give examples of pressure concept applications in daily life.",
    back: "Thin skating blades and axe blades (high pressure); wide tractor wheels and elephant soles (low pressure); studs on football boots.",
  },
  {
    id: "sci-f2-c8-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Why does a condensed milk can with two holes let milk flow more smoothly?",
    back: "Because the air pressure inside and outside the can becomes equal with two holes, compared to a single hole.",
  },
  {
    id: "sci-f2-c8-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Why are dam walls designed thicker at the base?",
    back: "To withstand the higher water pressure at the greater depth.",
  },
  {
    id: "sci-f2-c8-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Compare the effect of force from the opposite direction versus the same direction on a moving object's speed.",
    back: "Opposite direction: slows the object down. Same direction: speeds the object up.",
  },

  // Deck 3: Exam/KBAT (Cards 41-60)
  {
    id: "sci-f2-c8-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] A force of 50 N is applied at 0.2 m from the pivot to tighten a nut. What is the moment of force?",
    back: "Moment of force = 50 N × 0.2 m = 10 N m.",
  },
  {
    id: "sci-f2-c8-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] A force of 10 N is used to open a can lid using a 0.15 m spoon. What is the moment of force?",
    back: "Moment of force = 10 N × 0.15 m = 1.5 N m.",
  },
  {
    id: "sci-f2-c8-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Jia Yin (200 N) and Wei Hong (300 N) on a see-saw; Wei Hong is 2 m from the fulcrum. How far must Jia Yin sit?",
    back: "200 N × d = 300 N × 2 m → d = 3 m from the fulcrum.",
  },
  {
    id: "sci-f2-c8-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] A 100 kg boulder is moved using a fulcrum; boulder-fulcrum distance 0.5 m, man-fulcrum distance 2 m, gravitational force 10 N kg⁻¹. What is the effort?",
    back: "Load = 1000 N. 1000 N × 0.5 m = Effort × 2 m → Effort = 250 N.",
  },
  {
    id: "sci-f2-c8-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Why doesn't an elephant weighing 5000 kg sink into the ground?",
    back: "The large surface area of its sole results in small pressure on the ground (Pressure = Force/Area).",
  },
  {
    id: "sci-f2-c8-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[Common Mistake] Is buoyant force the same as actual weight?",
    back: "No. Buoyant force = Actual weight − Apparent weight, not equal to actual weight.",
  },
  {
    id: "sci-f2-c8-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[Common Mistake] Does an object less dense than a liquid submerge?",
    back: "No. An object less dense than the liquid will float because buoyant force F > weight W.",
  },
  {
    id: "sci-f2-c8-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Why are cargo ships marked with Plimsoll lines?",
    back: "For safety purposes, because seawater density differs due to temperature and salt concentration in different parts of the world.",
  },
  {
    id: "sci-f2-c8-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Why does atmospheric pressure decrease as altitude increases?",
    back: "Weaker gravitational attraction at higher altitudes makes air less dense and able to expand more easily.",
  },
  {
    id: "sci-f2-c8-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Why does a two-hole condensed milk can flow more smoothly than a single-hole one?",
    back: "Air pressure inside and outside the can becomes equal with two holes, allowing milk to flow more smoothly.",
  },
  {
    id: "sci-f2-c8-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[Important Fact] Who is the newton (N) unit named after?",
    back: "Sir Isaac Newton, the scientist and mathematician who discovered gravitational force.",
  },
  {
    id: "sci-f2-c8-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[Exam Tip] How do you answer a moment of force calculation question for full marks?",
    back: "Write the formula Moment of force = Force × Perpendicular distance, substitute values with correct units, and state the answer's unit (N m).",
  },
  {
    id: "sci-f2-c8-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Why are dam walls designed thicker at the base?",
    back: "Because liquid pressure increases with depth, so the base must withstand higher water pressure.",
  },
  {
    id: "sci-f2-c8-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[Common Mistake] Does moment of force depend only on the magnitude of force?",
    back: "No. Moment of force depends on BOTH the magnitude of force AND the perpendicular distance from the pivot to the force.",
  },
  {
    id: "sci-f2-c8-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] What does an air bubble enlarging as it rises to the water surface prove about liquid pressure?",
    back: "It proves liquid pressure decreases as depth decreases (closer to the surface, lower the pressure).",
  },
  {
    id: "sci-f2-c8-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[Important Fact] Arrange the following by increasing density: gold, water, cork, iron.",
    back: "Cork (0.24) < Water (1.0) < Iron (7.9) < Gold (19.3) g cm⁻³.",
  },
  {
    id: "sci-f2-c8-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Why are tractor wheels made large and wide?",
    back: "To increase the surface area in contact with the ground, reducing pressure so the tractor doesn't sink into soft soil.",
  },
  {
    id: "sci-f2-c8-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[KBAT] Why are axe blades and skating blades made thin?",
    back: "To reduce surface area so the same force produces greater pressure, making cutting/gliding easier.",
  },
  {
    id: "sci-f2-c8-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "[Common Mistake] Do action and reaction forces act in the same direction?",
    back: "No. The reaction force has the same magnitude but acts in the opposite direction to the action force.",
  },
  {
    id: "sci-f2-c8-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 8",
    lang: "dlp",
    front: "Summarise Chapter 8's concept map in one sentence.",
    back: "Force (a vector with magnitude, direction, point of application) has various types and effects, including buoyant force, moment of force on levers, and pressure (gas, atmospheric, liquid).",
  },
];
