import type { QuizQuestion } from "@/data/content";

export const scienceF2C8QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c8-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "What is the meaning of force?",
    options: [
      "A pull or a push upon an object",
      "The mass of an object",
      "The volume of an object",
      "The temperature of an object",
    ],
    answerIndex: 0,
    explanation: "Force is a pull or a push upon an object.",
  },
  {
    id: "sci-f2-c8-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "What is the S.I. unit of force?",
    options: ["Joule (J)", "Newton (N)", "Pascal (Pa)", "Watt (W)"],
    answerIndex: 1,
    explanation: "The S.I. unit of force is newton (N).",
  },
  {
    id: "sci-f2-c8-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Which instrument is used to measure force?",
    options: ["Thermometer", "Spring balance", "Barometer", "Ammeter"],
    answerIndex: 1,
    explanation: "Force is measured using a spring balance, which operates based on the principle of spring extension.",
  },
  {
    id: "sci-f2-c8-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "What is the weight of an object with a mass of 1 kg on Earth?",
    options: ["1 N", "10 N", "100 N", "0.1 N"],
    answerIndex: 1,
    explanation: "An object with a mass of 100 g has a weight of 1 N; therefore, an object with a mass of 1 kg has a weight of 10 N.",
  },
  {
    id: "sci-f2-c8-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "The force that points towards the centre of the Earth, causing objects thrown upward to fall back down, is called...",
    options: ["Frictional force", "Normal force", "Gravitational force", "Elastic force"],
    answerIndex: 2,
    explanation: "Gravitational force is the force that points towards the centre of the Earth, causing all objects thrown upwards to fall back to Earth.",
  },
  {
    id: "sci-f2-c8-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "The force that resists movement between two surfaces in contact is called...",
    options: ["Frictional force", "Gravitational force", "Buoyant force", "Elastic force"],
    answerIndex: 0,
    explanation: "Frictional force resists movement between two surfaces in contact with each other, and acts in the opposite direction of motion.",
  },
  {
    id: "sci-f2-c8-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "The force produced when an object is in contact with a surface is called...",
    options: ["Normal force", "Frictional force", "Gravitational force", "Buoyant force"],
    answerIndex: 0,
    explanation: "Normal force is the force produced when an object is in contact with a surface.",
  },
  {
    id: "sci-f2-c8-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Weight is defined as...",
    options: [
      "The gravitational force acting on an object",
      "The frictional force acting on an object",
      "The mass of an object",
      "The volume of an object",
    ],
    answerIndex: 0,
    explanation: "Weight is defined as the gravitational force acting on an object.",
  },
  {
    id: "sci-f2-c8-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "The thrust force acting on an object floating on the surface of a fluid is called...",
    options: ["Normal force", "Elastic force", "Buoyant force", "Gravitational force"],
    answerIndex: 2,
    explanation: "Buoyant force is the thrust force acting on an object floating on the surface of a fluid.",
  },
  {
    id: "sci-f2-c8-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "The force that exists when a material is stretched or compressed is called...",
    options: ["Elastic force", "Gravitational force", "Normal force", "Buoyant force"],
    answerIndex: 0,
    explanation: "Elastic force exists when a material is stretched or compressed, for example a spring.",
  },
  {
    id: "sci-f2-c8-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Why is force described as a vector quantity?",
    options: [
      "Because it only has magnitude",
      "Because it has magnitude and direction",
      "Because it cannot be measured",
      "Because its value is always constant",
    ],
    answerIndex: 1,
    explanation: "Force is a vector quantity that has magnitude and direction, as well as a point of application.",
  },
  {
    id: "sci-f2-c8-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "What is meant by the point of application of a force?",
    options: [
      "The magnitude of the force",
      "The area where the applied force is concentrated",
      "The direction the force moves",
      "The unit of the force",
    ],
    answerIndex: 1,
    explanation: "The point of application is the area where the applied force is concentrated.",
  },
  {
    id: "sci-f2-c8-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "When an object remains on a table, weight (action force) is balanced by...",
    options: [
      "Buoyant force (reaction force)",
      "Normal force (reaction force)",
      "Elastic force (reaction force)",
      "Frictional force (reaction force)",
    ],
    answerIndex: 1,
    explanation: "Weight (action force) is balanced by normal force (reaction force) in the opposite direction when an object is placed on a table.",
  },
  {
    id: "sci-f2-c8-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Two trolleys in contact are launched with a spring mechanism. What happens to both trolleys?",
    options: [
      "Both move the same distance in the same direction",
      "Both move the same distance but in opposite directions",
      "Only one trolley moves",
      "Both trolleys remain stationary",
    ],
    answerIndex: 1,
    explanation: "According to the action-reaction pair principle, both trolleys move at the same distance but in opposite directions.",
  },
  {
    id: "sci-f2-c8-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "When is an object said to float in a fluid?",
    options: [
      "When the buoyant force is less than its weight",
      "When the buoyant force is enough to support its weight",
      "When the object has no weight",
      "When the object is denser than the fluid",
    ],
    answerIndex: 1,
    explanation: "An object will float if the buoyant force acting on it is enough to support its weight (buoyant force = weight of the object).",
  },
  {
    id: "sci-f2-c8-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "What is the formula for buoyant force?",
    options: [
      "Buoyant force = Actual weight + Apparent weight",
      "Buoyant force = Actual weight − Apparent weight",
      "Buoyant force = Apparent weight − Actual weight",
      "Buoyant force = Actual weight × Apparent weight",
    ],
    answerIndex: 1,
    explanation: "Buoyant force = Actual weight (in air) − Apparent weight (immersed in fluid).",
  },
  {
    id: "sci-f2-c8-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "An object more dense than a liquid will...",
    options: ["Float", "Submerge", "Remain stationary at the surface", "Change shape"],
    answerIndex: 1,
    explanation: "An object more dense than the liquid will submerge because the buoyant force F is less than the weight W.",
  },
  {
    id: "sci-f2-c8-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "What is the formula for moment of force?",
    options: [
      "Moment of force = Force × Mass",
      "Moment of force = Force × Perpendicular distance from the pivot to the force",
      "Moment of force = Force / Surface area",
      "Moment of force = Force + Distance",
    ],
    answerIndex: 1,
    explanation: "Moment of force = Force (N) × Perpendicular distance from the pivot to the force (m), with unit newton metre (N m).",
  },
  {
    id: "sci-f2-c8-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "What are the three main parts of a lever?",
    options: [
      "Effort, load, fulcrum",
      "Normal force, gravitational force, weight",
      "Magnitude, direction, point of application",
      "Volume, temperature, pressure",
    ],
    answerIndex: 0,
    explanation: "A lever is made up of three parts — effort, load, and fulcrum (fixed support point).",
  },
  {
    id: "sci-f2-c8-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "In a first class lever, the fulcrum is located between...",
    options: [
      "Load and effort",
      "Two loads",
      "Two efforts",
      "Point of application and magnitude",
    ],
    answerIndex: 0,
    explanation: "In a first class lever, the fulcrum is between load and effort, e.g. scissors, pliers, can opener.",
  },
  {
    id: "sci-f2-c8-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "A force of 50 N is applied at a distance of 0.2 m from the pivot to tighten a nut. What is the resulting moment of force?",
    options: ["5 N m", "10 N m", "25 N m", "100 N m"],
    answerIndex: 1,
    explanation: "Moment of force = 50 N × 0.2 m = 10 N m.",
  },
  {
    id: "sci-f2-c8-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Jia Yin (200 N) and Wei Hong (300 N) sit on a see-saw. Wei Hong is 2 m from the fulcrum. How far must Jia Yin sit from the fulcrum for balance?",
    options: ["1 m", "2 m", "3 m", "6 m"],
    answerIndex: 2,
    explanation: "200 N × d = 300 N × 2 m → d = 600/200 = 3 m. Jia Yin must sit 3 m from the fulcrum.",
  },
  {
    id: "sci-f2-c8-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "A man moves a 100 kg boulder using a small stone as a fulcrum. Distance boulder-fulcrum = 0.5 m, distance man-fulcrum = 2 m, gravitational force = 10 N kg⁻¹. What effort is needed?",
    options: ["100 N", "250 N", "500 N", "1000 N"],
    answerIndex: 1,
    explanation: "Load = 100 kg × 10 = 1000 N. 1000 N × 0.5 m = Effort × 2 m → Effort = 500/2 = 250 N.",
  },
  {
    id: "sci-f2-c8-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Why does an elephant weighing 5000 kg not sink into the ground?",
    options: [
      "Because it has high buoyant force",
      "Because the large surface area of its sole results in small pressure on the ground",
      "Because it has high elastic force",
      "Because it has no weight",
    ],
    answerIndex: 1,
    explanation: "Pressure = Force/Area. The large surface area of an elephant's sole results in small pressure on the ground despite its high weight.",
  },
  {
    id: "sci-f2-c8-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Based on the density table, cork (0.24 g cm⁻³) floats on water (1.0 g cm⁻³) because...",
    options: [
      "Cork is denser than water",
      "Cork is less dense than water",
      "Cork has the same weight as water",
      "Cork has no gravitational force",
    ],
    answerIndex: 1,
    explanation: "Cork floats on water because it is less dense (0.24 g cm⁻³) compared to water (1.0 g cm⁻³), making buoyant force F greater than weight W.",
  },
  {
    id: "sci-f2-c8-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Why are cargo ships marked with Plimsoll lines?",
    options: [
      "To show the ship's maximum speed",
      "For safety purposes, because the density of seawater differs due to temperature and salt concentration",
      "To show the empty mass of the ship",
      "To show the direction of the ship's movement",
    ],
    answerIndex: 1,
    explanation: "Plimsoll lines are marked for safety purposes because seawater density differs due to temperature and salt concentration in different parts of the world.",
  },
  {
    id: "sci-f2-c8-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "According to the kinetic theory of gas, air pressure results from...",
    options: [
      "The weight of air molecules pressing down",
      "The frequency of collision between air molecules and the walls of their container",
      "The low temperature of air molecules",
      "The slow movement of air molecules",
    ],
    answerIndex: 1,
    explanation: "The frequency of collision between freely-moving air molecules and the walls of their container produces a force that pushes against the walls — air pressure.",
  },
  {
    id: "sci-f2-c8-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Why does atmospheric pressure decrease as altitude increases?",
    options: [
      "Because stronger gravity makes the air denser",
      "Because weaker gravitational attraction makes the air less dense and able to expand more easily",
      "Because temperature always increases with altitude",
      "Because volume of air always decreases with altitude",
    ],
    answerIndex: 1,
    explanation: "Atmospheric pressure decreases with altitude due to weaker gravitational attraction, making air less dense and able to expand more easily.",
  },
  {
    id: "sci-f2-c8-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "A condensed milk can with two holes allows milk to flow more smoothly than one with a single hole. Why?",
    options: [
      "Because the air pressure inside the can becomes lower than outside",
      "Because the air pressure inside and outside the can becomes equal",
      "Because the milk becomes less dense",
      "Because gravitational force increases",
    ],
    answerIndex: 1,
    explanation: "With two holes, the air pressure inside and outside the can becomes equal, allowing milk to flow out more smoothly.",
  },
  {
    id: "sci-f2-c8-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "dlp",
    question: "Why are dam walls designed to be thicker at the base?",
    options: [
      "To reduce the overall weight of the dam",
      "To withstand the higher water pressure at that depth",
      "To increase the buoyant force of the dam",
      "To reduce construction costs",
    ],
    answerIndex: 1,
    explanation: "Liquid pressure increases with depth, so dam walls are designed thicker at the base to withstand the higher water pressure at that depth.",
  },
];
