import type { QuizQuestion } from "@/data/content";

export const scienceF2C8QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c8-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Apakah maksud daya?",
    options: [
      "Tarikan atau tolakan ke atas sesuatu objek",
      "Jisim sesuatu objek",
      "Isi padu sesuatu objek",
      "Suhu sesuatu objek",
    ],
    answerIndex: 0,
    explanation: "Daya ialah tarikan atau tolakan ke atas sesuatu objek.",
  },
  {
    id: "sci-f2-c8-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Apakah unit SI bagi daya?",
    options: [
      "Joule (J)",
      "Newton (N)",
      "Pascal (Pa)",
      "Watt (W)",
    ],
    answerIndex: 1,
    explanation: "Unit SI bagi daya ialah newton (N).",
  },
  {
    id: "sci-f2-c8-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Alat apakah yang digunakan untuk mengukur daya?",
    options: [
      "Termometer",
      "Barometer",
      "Neraca spring",
      "Ammeter",
    ],
    answerIndex: 2,
    explanation: "Daya diukur menggunakan neraca spring (spring balance), yang beroperasi berdasarkan prinsip pengembangan spring.",
  },
  {
    id: "sci-f2-c8-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Objek berjisim 1 kg mempunyai berat berapa di Bumi?",
    options: [
      "1 N",
      "0.1 N",
      "100 N",
      "10 N",
    ],
    answerIndex: 3,
    explanation: "Objek berjisim 100 g mempunyai berat 1 N, oleh itu objek berjisim 1 kg mempunyai berat 10 N.",
  },
  {
    id: "sci-f2-c8-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Daya yang menumpu ke arah pusat Bumi dan menyebabkan objek yang dilemparkan ke atas jatuh semula ialah...",
    options: [
      "Daya graviti",
      "Daya normal",
      "Daya geseran",
      "Daya kenyal",
    ],
    answerIndex: 0,
    explanation: "Daya graviti ialah daya yang menumpu ke arah pusat Bumi, menyebabkan semua objek yang dilemparkan ke atas jatuh semula ke Bumi.",
  },
  {
    id: "sci-f2-c8-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Daya yang merintangi pergerakan antara dua permukaan yang bersentuhan dipanggil...",
    options: [
      "Daya graviti",
      "Daya geseran",
      "Daya keapungan",
      "Daya kenyal",
    ],
    answerIndex: 1,
    explanation: "Daya geseran ialah daya yang merintangi pergerakan antara dua permukaan yang bersentuhan, dan bertindak dalam arah bertentangan dengan arah gerakan.",
  },
  {
    id: "sci-f2-c8-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Daya yang terhasil apabila sesuatu objek bersentuhan dengan permukaan dipanggil...",
    options: [
      "Daya graviti",
      "Daya geseran",
      "Daya normal",
      "Daya keapungan",
    ],
    answerIndex: 2,
    explanation: "Daya normal ialah daya yang terhasil apabila sesuatu objek bersentuhan dengan permukaan.",
  },
  {
    id: "sci-f2-c8-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Berat sesuatu objek ditakrifkan sebagai...",
    options: [
      "Isi padu sesuatu objek",
      "Daya geseran yang bertindak ke atas sesuatu objek",
      "Jisim sesuatu objek",
      "Daya graviti yang bertindak ke atas sesuatu objek",
    ],
    answerIndex: 3,
    explanation: "Berat ditakrifkan sebagai daya graviti yang bertindak ke atas sesuatu objek.",
  },
  {
    id: "sci-f2-c8-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Daya tujahan yang bertindak ke atas objek yang terapung di permukaan bendalir dipanggil...",
    options: [
      "Daya keapungan",
      "Daya kenyal",
      "Daya normal",
      "Daya graviti",
    ],
    answerIndex: 0,
    explanation: "Daya keapungan ialah daya tujahan yang bertindak ke atas objek yang terapung di permukaan bendalir.",
  },
  {
    id: "sci-f2-c8-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Daya yang wujud apabila sesuatu bahan diregangkan atau dimampatkan dipanggil...",
    options: [
      "Daya graviti",
      "Daya kenyal",
      "Daya normal",
      "Daya keapungan",
    ],
    answerIndex: 1,
    explanation: "Daya kenyal wujud apabila sesuatu bahan diregangkan atau dimampatkan, contohnya spring.",
  },
  {
    id: "sci-f2-c8-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Mengapakah daya dikatakan sebagai kuantiti vektor?",
    options: [
      "Kerana ia hanya mempunyai magnitud",
      "Kerana ia tidak boleh diukur",
      "Kerana ia mempunyai magnitud dan arah",
      "Kerana ia sentiasa tetap nilainya",
    ],
    answerIndex: 2,
    explanation: "Daya ialah kuantiti vektor yang mempunyai magnitud dan arah, serta titik aplikasi.",
  },
  {
    id: "sci-f2-c8-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Apakah maksud titik aplikasi (point of application) bagi sesuatu daya?",
    options: [
      "Magnitud daya tersebut",
      "Unit daya tersebut",
      "Arah daya tersebut bergerak",
      "Kawasan di mana daya yang dikenakan tertumpu",
    ],
    answerIndex: 3,
    explanation: "Titik aplikasi ialah kawasan di mana daya yang dikenakan tertumpu.",
  },
  {
    id: "sci-f2-c8-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Apabila objek di atas meja, berat (daya tindakan) seimbang dengan...",
    options: [
      "Daya normal (daya tindak balas)",
      "Daya keapungan (daya tindak balas)",
      "Daya kenyal (daya tindak balas)",
      "Daya geseran (daya tindak balas)",
    ],
    answerIndex: 0,
    explanation: "Berat (daya tindakan) seimbang dengan daya normal (daya tindak balas) dalam arah bertentangan apabila objek diletakkan di atas meja.",
  },
  {
    id: "sci-f2-c8-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Dua troli bersentuhan dilancarkan dengan mekanisme spring. Apakah yang berlaku kepada kedua-dua troli tersebut?",
    options: [
      "Kedua-dua bergerak pada jarak sama dalam arah sama",
      "Kedua-dua bergerak pada jarak sama dalam arah bertentangan",
      "Hanya satu troli bergerak",
      "Kedua-dua troli kekal pegun",
    ],
    answerIndex: 1,
    explanation: "Mengikut prinsip pasangan tindakan-tindak balas, kedua-dua troli akan bergerak pada jarak yang sama tetapi dalam arah bertentangan.",
  },
  {
    id: "sci-f2-c8-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Bilakah sesuatu objek dikatakan terapung dalam bendalir?",
    options: [
      "Apabila daya keapungan kurang daripada beratnya",
      "Apabila objek tidak mempunyai berat",
      "Apabila daya keapungan cukup untuk menampung beratnya",
      "Apabila objek lebih tumpat daripada bendalir",
    ],
    answerIndex: 2,
    explanation: "Sesuatu objek akan terapung jika daya keapungan yang bertindak ke atasnya cukup untuk menampung beratnya (daya keapungan = berat objek).",
  },
  {
    id: "sci-f2-c8-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Apakah formula bagi daya keapungan?",
    options: [
      "Daya keapungan = Berat sebenar + Berat ketara",
      "Daya keapungan = Berat sebenar × Berat ketara",
      "Daya keapungan = Berat ketara − Berat sebenar",
      "Daya keapungan = Berat sebenar − Berat ketara",
    ],
    answerIndex: 3,
    explanation: "Daya keapungan = Berat sebenar (di udara) − Berat ketara (direndam dalam bendalir).",
  },
  {
    id: "sci-f2-c8-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Objek yang lebih tumpat daripada cecair akan...",
    options: [
      "Tenggelam",
      "Terapung",
      "Kekal pegun di permukaan",
      "Berubah bentuk",
    ],
    answerIndex: 0,
    explanation: "Objek yang lebih tumpat daripada cecair akan tenggelam kerana daya keapungan F kurang daripada berat W.",
  },
  {
    id: "sci-f2-c8-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Apakah formula bagi momen daya?",
    options: [
      "Momen daya = Daya × Jisim",
      "Momen daya = Daya × Jarak tegak dari pangsi ke daya",
      "Momen daya = Daya / Luas permukaan",
      "Momen daya = Daya + Jarak",
    ],
    answerIndex: 1,
    explanation: "Momen daya = Daya (N) × Jarak tegak dari pangsi ke daya (m), dengan unit newton meter (N m).",
  },
  {
    id: "sci-f2-c8-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Apakah tiga bahagian utama sebuah tuil?",
    options: [
      "Magnitud, arah, titik aplikasi",
      "Daya normal, daya graviti, berat",
      "Daya kuasa, beban, fulkrum",
      "Isi padu, suhu, tekanan",
    ],
    answerIndex: 2,
    explanation: "Tuil terdiri daripada tiga bahagian — daya kuasa (effort), beban (load), dan fulkrum (titik sokongan tetap).",
  },
  {
    id: "sci-f2-c8-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Pada tuil kelas pertama, fulkrum terletak di antara...",
    options: [
      "Titik aplikasi dan magnitud",
      "Dua beban",
      "Dua daya kuasa",
      "Beban dan daya kuasa",
    ],
    answerIndex: 3,
    explanation: "Tuil kelas pertama mempunyai fulkrum terletak antara beban dan daya kuasa, contoh: gunting, playar, pembuka tin.",
  },
  {
    id: "sci-f2-c8-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Satu daya 50 N dikenakan pada jarak 0.2 m daripada pangsi untuk mengetatkan nat. Berapakah momen daya yang terhasil?",
    options: [
      "10 N m",
      "5 N m",
      "25 N m",
      "100 N m",
    ],
    answerIndex: 0,
    explanation: "Momen daya = 50 N × 0.2 m = 10 N m.",
  },
  {
    id: "sci-f2-c8-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Jia Yin (200 N) dan Wei Hong (300 N) duduk di atas jongkang-jongket. Wei Hong berada 2 m daripada fulkrum. Berapa jauhkah Jia Yin perlu duduk daripada fulkrum supaya seimbang?",
    options: [
      "1 m",
      "3 m",
      "2 m",
      "6 m",
    ],
    answerIndex: 1,
    explanation: "200 N × d = 300 N × 2 m → d = 600/200 = 3 m. Jia Yin perlu duduk 3 m daripada fulkrum.",
  },
  {
    id: "sci-f2-c8-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Seorang lelaki memindahkan batu besar berjisim 100 kg menggunakan batu kecil sebagai fulkrum. Jarak batu besar–fulkrum = 0.5 m, jarak lelaki–fulkrum = 2 m, daya graviti = 10 N kg⁻¹. Berapakah daya kuasa yang diperlukan?",
    options: [
      "100 N",
      "500 N",
      "250 N",
      "1000 N",
    ],
    answerIndex: 2,
    explanation: "Beban = 100 kg × 10 = 1000 N. 1000 N × 0.5 m = Daya kuasa × 2 m → Daya kuasa = 500/2 = 250 N.",
  },
  {
    id: "sci-f2-c8-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Mengapakah gajah seberat 5000 kg tidak tenggelam ke dalam tanah?",
    options: [
      "Kerana ia mempunyai daya keapungan yang tinggi",
      "Kerana ia tidak mempunyai berat",
      "Kerana ia mempunyai daya kenyal yang tinggi",
      "Kerana luas permukaan tapak kakinya yang besar menghasilkan tekanan yang kecil ke atas tanah",
    ],
    answerIndex: 3,
    explanation: "Tekanan = Daya/Luas. Luas permukaan tapak kaki gajah yang besar menghasilkan tekanan yang kecil ke atas tanah walaupun beratnya tinggi.",
  },
  {
    id: "sci-f2-c8-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Berdasarkan jadual ketumpatan, gabus (0.24 g cm⁻³) terapung di atas air (1.0 g cm⁻³) kerana...",
    options: [
      "Gabus kurang tumpat daripada air",
      "Gabus lebih tumpat daripada air",
      "Gabus mempunyai berat sama dengan air",
      "Gabus tidak mempunyai daya graviti",
    ],
    answerIndex: 0,
    explanation: "Gabus terapung kerana ia kurang tumpat (0.24 g cm⁻³) berbanding air (1.0 g cm⁻³). Semasa terapung pegun, daya apungan sama magnitud dengan beratnya (F = W).",
  },
  {
    id: "sci-f2-c8-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Mengapakah kapal kargo ditandakan dengan garis Plimsoll?",
    options: [
      "Untuk menunjukkan kelajuan maksimum kapal",
      "Untuk tujuan keselamatan, kerana ketumpatan air laut berbeza mengikut suhu dan kepekatan garam",
      "Untuk menunjukkan jisim kapal yang kosong",
      "Untuk menunjukkan arah pergerakan kapal",
    ],
    answerIndex: 1,
    explanation: "Garis Plimsoll ditandakan untuk tujuan keselamatan kerana ketumpatan air laut berbeza mengikut suhu dan kepekatan garam di pelbagai bahagian dunia.",
  },
  {
    id: "sci-f2-c8-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Menurut teori kinetik gas, tekanan udara terhasil daripada...",
    options: [
      "Berat molekul udara yang menekan ke bawah",
      "Suhu rendah molekul udara",
      "Kekerapan perlanggaran antara molekul udara dengan dinding bekas",
      "Pergerakan molekul udara yang perlahan",
    ],
    answerIndex: 2,
    explanation: "Kekerapan perlanggaran antara molekul udara yang bergerak bebas dengan dinding bekas menghasilkan daya yang menolak dinding, iaitu tekanan udara.",
  },
  {
    id: "sci-f2-c8-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Mengapakah tekanan atmosfera berkurang apabila altitud meningkat?",
    options: [
      "Kerana tarikan graviti yang lebih kuat menjadikan udara lebih tumpat",
      "Kerana isi padu udara sentiasa berkurang dengan altitud",
      "Kerana suhu sentiasa meningkat dengan altitud",
      "Kerana lebih sedikit udara berada di atas kita, jadi berat lajur udara yang menekan ke bawah lebih kecil",
    ],
    answerIndex: 3,
    explanation: "Semakin tinggi altitud, semakin sedikit udara yang berada di atas kita. Berat lajur udara yang menekan ke bawah menjadi lebih kecil, jadi tekanan atmosfera menjadi lebih rendah.",
  },
  {
    id: "sci-f2-c8-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Tin susu pekat dengan dua lubang membolehkan susu mengalir lebih lancar berbanding satu lubang. Mengapa?",
    options: [
      "Kerana tekanan udara di dalam dan di luar tin menjadi sama",
      "Kerana tekanan udara di dalam tin menjadi lebih rendah daripada di luar",
      "Kerana susu menjadi kurang tumpat",
      "Kerana daya graviti meningkat",
    ],
    answerIndex: 0,
    explanation: "Dengan dua lubang, tekanan udara di dalam dan di luar tin menjadi sama, membolehkan susu mengalir lebih lancar.",
  },
  {
    id: "sci-f2-c8-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 8",
    lang: "bm",
    question: "Mengapakah dinding empangan direka lebih tebal di bahagian asas?",
    options: [
      "Untuk mengurangkan berat keseluruhan empangan",
      "Untuk menahan tekanan air yang lebih tinggi pada kedalaman tersebut",
      "Untuk meningkatkan daya keapungan empangan",
      "Untuk mengurangkan kos pembinaan",
    ],
    answerIndex: 1,
    explanation: "Tekanan cecair meningkat dengan kedalaman, jadi dinding empangan direka lebih tebal di bahagian asas untuk menahan tekanan air yang lebih tinggi pada kedalaman tersebut.",
  },
];
