import type { Flashcard } from "@/data/content";

export const scienceF2C7FlashcardsDLP: Flashcard[] = [
  // Set 1: Electrostatics & Electricity
  {
    id: "sci-f2-c7-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of energy?",
    back: "The ability to do work. The SI unit of energy is the joule (J).",
  },
  {
    id: "sci-f2-c7-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Name four sources of energy.",
    back: "The sun, wind, geothermal, waves (also water, radioactive materials, biomass, fossil fuels).",
  },
  {
    id: "sci-f2-c7-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of electrostatic charge?",
    back: "A charge produced from the transfer of electrons between two objects when rubbed together.",
  },
  {
    id: "sci-f2-c7-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Compare a positively charged object with a negatively charged object.",
    back: "Positively charged: loses electrons. Negatively charged: gains electrons. Equal number of protons and electrons = neutral.",
  },
  {
    id: "sci-f2-c7-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the property of electrostatic force?",
    back: "Like charges repel each other; unlike charges attract each other.",
  },
  {
    id: "sci-f2-c7-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the function of an electroscope?",
    back: "A device to detect the presence of electric charge on an object; the gold leaf diverges if charged.",
  },
  {
    id: "sci-f2-c7-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Why does electrostatic charge build up more easily in dry weather?",
    back: "In humid air, water vapour helps charge leak away; in dry air, the charge stays on the object.",
  },
  {
    id: "sci-f2-c7-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Why does a TV screen quickly become dusty?",
    back: "Negative charges on dust are attracted to positive charges on the TV screen; an anti-static microfibre cloth can reduce this effect.",
  },
  {
    id: "sci-f2-c7-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How is lightning produced?",
    back: "Friction between clouds and air causes the clouds to become charged; lightning is produced by the attractive force between positive charges on the ground and negative charges in the clouds.",
  },
  {
    id: "sci-f2-c7-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the function of a lightning conductor?",
    back: "It provides a path for electric charge to flow into the ground, protecting buildings from being struck by lightning.",
  },
  {
    id: "sci-f2-c7-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What device is used to simulate the formation of lightning in a school laboratory?",
    back: "A Van de Graaff generator or a Wimshurst machine.",
  },
  {
    id: "sci-f2-c7-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Why is it safer to stay inside a car with a metal body during a thunderstorm?",
    back: "The metal body acts as a Faraday cage: charge from lightning flows over the outer metal surface to the ground instead of passing through the inside.",
  },
  {
    id: "sci-f2-c7-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Why is an electrostatic spark dangerous when refuelling a vehicle?",
    back: "Petrol vapour catches fire easily, so a spark from built-up charge could ignite it.",
  },
  {
    id: "sci-f2-c7-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of electric current?",
    back: "The rate of flow of electric charge through a conductor.",
  },
  {
    id: "sci-f2-c7-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the instrument and unit for measuring electric current?",
    back: "Ammeter; SI unit ampere (A).",
  },
  {
    id: "sci-f2-c7-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of voltage and its measuring instrument?",
    back: "The potential difference between two points, measured in volts (V) using a voltmeter.",
  },
  {
    id: "sci-f2-c7-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of resistance and its unit?",
    back: "The ability of a conductor to oppose the flow of electric current; unit ohm (Ω).",
  },
  {
    id: "sci-f2-c7-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "State the formula of Ohm's Law.",
    back: "V = IR, where V = voltage (V), I = current (A), R = resistance (Ω).",
  },
  {
    id: "sci-f2-c7-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "Compare the relationship between current with resistance and voltage according to Ohm's Law.",
    back: "The higher the resistance, the smaller the current. The higher the voltage, the larger the current (temperature remains constant).",
  },
  {
    id: "sci-f2-c7-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "Compare the direction of electron flow with the direction of current flow in a circuit.",
    back: "Electrons flow from the negative terminal to the positive terminal. Current flows from the positive terminal to the negative terminal.",
  },
  // Set 2: Series & Parallel Circuits
  {
    id: "sci-f2-c7-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of a series circuit?",
    back: "A circuit formed from electrical components connected one after another, current flows through a single path.",
  },
  {
    id: "sci-f2-c7-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of a parallel circuit?",
    back: "A circuit divided into several different electrical paths, each path having electrical components.",
  },
  {
    id: "sci-f2-c7-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Compare current in a series circuit and a parallel circuit.",
    back: "Series circuit: I = I₁ = I₂ (same at every point). Parallel circuit: I = I₁ + I₂ (total current).",
  },
  {
    id: "sci-f2-c7-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Compare voltage in a series circuit and a parallel circuit.",
    back: "Series circuit: V = V₁ + V₂ (total voltage). Parallel circuit: V = V₁ = V₂ (same across every resistor).",
  },
  {
    id: "sci-f2-c7-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Compare effective resistance in a series circuit and a parallel circuit.",
    back: "Series circuit: R = R₁ + R₂ (total resistance). Parallel circuit: 1/R = 1/R₁ + 1/R₂.",
  },
  {
    id: "sci-f2-c7-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Name an advantage of a series circuit.",
    back: "Every component receives the same current; controlled by the same switch; increasing voltage supplies more current.",
  },
  {
    id: "sci-f2-c7-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Name a disadvantage of a series circuit.",
    back: "One faulty appliance causes all other appliances to stop; resistance increases and current decreases when more appliances are added; cannot be switched off separately.",
  },
  {
    id: "sci-f2-c7-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Name an advantage of a parallel circuit.",
    back: "Each appliance can be switched on/off separately; adding appliances does not affect other appliances.",
  },
  {
    id: "sci-f2-c7-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Name a disadvantage of a parallel circuit.",
    back: "The voltage of each appliance cannot be adjusted because the voltage equals the source voltage.",
  },
  {
    id: "sci-f2-c7-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Why is household wiring connected in parallel?",
    back: "So that every lamp receives the same voltage from the main power supply and can be controlled separately.",
  },
  {
    id: "sci-f2-c7-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Decorative lights remain lit except one that is faulty. What type of circuit is this?",
    back: "A parallel circuit — each path is separate, so other appliances are not affected when one fails.",
  },
  {
    id: "sci-f2-c7-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "Why does adding appliances in a series circuit reduce the current, but not in a parallel circuit?",
    back: "Series circuit: total resistance increases (R = R₁ + R₂...), hence current decreases. Parallel circuit: each path is independent with equal voltage, so it is not affected.",
  },
  {
    id: "sci-f2-c7-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the function of the distribution panel in a household wiring system?",
    back: "To control the current flowing from the main power supply to the circuits in the house.",
  },
  {
    id: "sci-f2-c7-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How is an ammeter connected in a circuit, and why?",
    back: "In series with the component, so that the same current flows through the ammeter and the component.",
  },
  {
    id: "sci-f2-c7-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How is a voltmeter connected in a circuit, and why?",
    back: "In parallel across the component, because it measures the potential difference between the two ends of the component.",
  },
  {
    id: "sci-f2-c7-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Compare a fixed resistor with a variable resistor (rheostat).",
    back: "Fixed resistor: resistance cannot be adjusted. Rheostat: resistance can be adjusted.",
  },
  {
    id: "sci-f2-c7-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Why does a longer nichrome wire reduce current flow in a circuit?",
    back: "A longer wire has higher resistance; according to Ohm's Law (I = V/R), higher resistance at constant voltage reduces the current.",
  },
  {
    id: "sci-f2-c7-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "A car headlamp carries a current of 0.025 A from a 12 V accumulator. What is its resistance?",
    back: "R = V/I = 12/0.025 = 480 Ω.",
  },
  {
    id: "sci-f2-c7-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "Two 2 Ω resistors are connected in series to a 6 V supply. What is the circuit current?",
    back: "R = R₁ + R₂ = 4 Ω. I = V/R = 6/4 = 1.5 A.",
  },
  {
    id: "sci-f2-c7-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "Two 2 Ω resistors are connected in parallel to a 6 V supply. What is the total circuit current?",
    back: "1/R = 1/2 + 1/2 = 1, R = 1 Ω. I₁ = 3 A, I₂ = 3 A. Total I = 6 A.",
  },
  // Set 3: Magnetism & Electromagnets
  {
    id: "sci-f2-c7-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of a magnet and its main property?",
    back: "A material that attracts magnetic materials and has a north pole and a south pole.",
  },
  {
    id: "sci-f2-c7-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Name three magnetic materials.",
    back: "Iron, nickel and cobalt (steel is also magnetic).",
  },
  {
    id: "sci-f2-c7-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How can the north pole of a bar magnet be identified without a compass?",
    back: "Hang the magnet freely; it comes to rest with its north pole pointing towards the Earth's geographic north.",
  },
  {
    id: "sci-f2-c7-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of a magnetic field?",
    back: "The region around a magnet that has magnetic force.",
  },
  {
    id: "sci-f2-c7-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Name three characteristics of magnetic field lines.",
    back: "Start from the north pole and end at the south pole; never meet or cross; closer together in regions of stronger field.",
  },
  {
    id: "sci-f2-c7-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Does breaking a magnet into two produce only one pole per piece?",
    back: "No. Each broken piece of the magnet still has two poles (north and south).",
  },
  {
    id: "sci-f2-c7-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is a neutral point in a magnetic field?",
    back: "A point between two like poles where there is no magnetic field, because the fields from the two poles cancel out.",
  },
  {
    id: "sci-f2-c7-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of an electromagnet?",
    back: "A type of magnet that has a temporary magnetic effect when electric current flows through it.",
  },
  {
    id: "sci-f2-c7-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Compare the magnetic effect of an electromagnet with a permanent magnet.",
    back: "Electromagnet: temporary magnetic effect, only exists when current flows. Permanent magnet: the magnetic effect is permanent and always exists.",
  },
  {
    id: "sci-f2-c7-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "What are the two factors that affect the strength of an electromagnet's magnetic field?",
    back: "The magnitude of the current (greater current, stronger field) and the number of coil turns (more turns, stronger field).",
  },
  {
    id: "sci-f2-c7-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How does a soft iron core affect an electromagnet?",
    back: "It makes the magnetic field much stronger, and it is easily magnetised and demagnetised.",
  },
  {
    id: "sci-f2-c7-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "How does an experiment prove that the number of coil turns affects the strength of the magnetic field?",
    back: "By increasing the number of turns on the coil while keeping the current constant, the number of pins attracted by the iron rod increases, showing a stronger magnetic field.",
  },
  {
    id: "sci-f2-c7-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Give an example of the use of electromagnets in daily life.",
    back: "Electric bells and magnetic door locks.",
  },
  {
    id: "sci-f2-c7-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How does an electric bell use an electromagnet?",
    back: "Current magnetises the electromagnet, which pulls the iron armature so the hammer strikes the gong; the circuit then breaks and the cycle repeats.",
  },
  {
    id: "sci-f2-c7-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the function of the right-hand grip rule?",
    back: "To determine the direction of the magnetic field for current flow in a straight wire.",
  },
  {
    id: "sci-f2-c7-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "What is the meaning of a solenoid?",
    back: "A coiled wire that carries electric current to produce a magnetic field like a bar magnet.",
  },
  {
    id: "sci-f2-c7-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How is the polarity of a solenoid determined by the direction of current?",
    back: "Viewed from one end, an anticlockwise current makes that end a north pole; a clockwise current makes it a south pole.",
  },
  {
    id: "sci-f2-c7-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front:
      "A solenoid carries current in an anticlockwise direction from one end. What pole is formed?",
    back: "A north pole — anticlockwise current (viewed from that end) produces a north pole.",
  },
  {
    id: "sci-f2-c7-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "How does the magnetic field of a straight wire differ from that of a solenoid?",
    back: "Straight wire: concentric circles around the wire. Solenoid: a pattern like a bar magnet, with a north and a south pole at its ends.",
  },
  {
    id: "sci-f2-c7-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "dlp",
    front: "Does the magnetic field pattern differ when the direction of current is reversed?",
    back: "No. The magnetic field pattern (concentric circles) does not change, but the direction of the magnetic field is determined by the direction of current.",
  },
];
