import type { Flashcard } from "@/data/content";

export const scienceF2C7FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c7-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud tenaga?",
    back: "Kemampuan untuk melakukan kerja. Unit SI bagi tenaga adalah joule (J).",
  },
  {
    id: "sci-f2-c7-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Namakan empat sumber tenaga.",
    back: "Matahari, angin, geoterma, ombak (juga air, bahan radioaktif, biojisim, bahan api fosil).",
  },
  {
    id: "sci-f2-c7-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud cas elektrostatik?",
    back: "Cas yang terhasil daripada pemindahan elektron antara dua objek apabila digosok bersama.",
  },
  {
    id: "sci-f2-c7-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah sifat daya elektrostatik?",
    back: "Cas yang sama saling menolak; cas yang bertentangan saling menarik.",
  },
  {
    id: "sci-f2-c7-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah fungsi elektroskop?",
    back: "Alat untuk mengesan kewujudan cas elektrik pada sesuatu objek; daun emas mencapah jika bercas.",
  },
  {
    id: "sci-f2-c7-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bagaimanakah kilat terhasil?",
    back: "Geseran antara awan dan udara menyebabkan awan bercas; kilat terhasil akibat daya tarikan antara cas positif di bumi dan cas negatif di awan.",
  },
  {
    id: "sci-f2-c7-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah fungsi konduktor kilat?",
    back: "Menyediakan laluan bagi cas elektrik mengalir ke dalam tanah, melindungi bangunan daripada disambar kilat.",
  },
  {
    id: "sci-f2-c7-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud arus elektrik?",
    back: "Kadar aliran cas elektrik melalui konduktor.",
  },
  {
    id: "sci-f2-c7-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah alat dan unit untuk mengukur arus elektrik?",
    back: "Ammeter; unit SI ampere (A).",
  },
  {
    id: "sci-f2-c7-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud voltan dan alat pengukurannya?",
    back: "Beza keupayaan antara dua titik, diukur dalam volt (V) menggunakan voltmeter.",
  },
  {
    id: "sci-f2-c7-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud rintangan dan unitnya?",
    back: "Keupayaan konduktor untuk menghalang aliran arus elektrik; unit ohm (Ω).",
  },
  {
    id: "sci-f2-c7-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Nyatakan formula Hukum Ohm.",
    back: "V = IR, di mana V = voltan (V), I = arus (A), R = rintangan (Ω).",
    },
  {
    id: "sci-f2-c7-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud litar bersiri?",
    back: "Litar yang dibentuk daripada komponen elektrik yang disambung secara berturutan, arus mengalir melalui satu laluan tunggal.",
  },
  {
    id: "sci-f2-c7-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud litar selari?",
    back: "Litar yang dipisahkan kepada beberapa laluan litar elektrik yang berbeza, setiap laluan mempunyai komponen elektrik.",
  },
  {
    id: "sci-f2-c7-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Namakan tiga komponen elektrik dan simbolnya yang dipelajari.",
    back: "Suis, sel kering, ammeter (juga voltmeter, galvanometer, mentol, perintang, fius, perintang berubah).",
  },
  {
    id: "sci-f2-c7-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud magnet dan sifat utamanya?",
    back: "Bahan yang menarik bahan bermagnet dan mempunyai kutub utara dan selatan.",
  },
  {
    id: "sci-f2-c7-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud medan magnet?",
    back: "Kawasan sekeliling magnet yang mempunyai daya magnet.",
  },
  {
    id: "sci-f2-c7-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud elektromagnet?",
    back: "Sejenis magnet yang mempunyai kesan magnet sementara apabila arus elektrik mengalir melaluinya.",
  },
  {
    id: "sci-f2-c7-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah fungsi petua tangan kanan?",
    back: "Menentukan arah medan magnet bagi aliran arus dalam wayar lurus.",
  },
  {
    id: "sci-f2-c7-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah maksud solenoid?",
    back: "Wayar yang bergegelung yang membawa arus elektrik untuk menghasilkan medan magnet seperti magnet bar.",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c7-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan objek bercas positif dengan objek bercas negatif.",
    back: "Bercas positif: kehilangan elektron. Bercas negatif: memperoleh elektron. Bilangan proton dan elektron sama = neutral.",
  },
  {
    id: "sci-f2-c7-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan perintang tetap dengan perintang berubah (reostat).",
    back: "Perintang tetap: rintangan tidak dapat diselaraskan. Reostat: rintangan dapat diselaraskan.",
  },
  {
    id: "sci-f2-c7-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan hubungan arus dengan rintangan dan voltan mengikut Hukum Ohm.",
    back: "Semakin tinggi rintangan, semakin kecil arus. Semakin tinggi voltan, semakin besar arus (suhu kekal tidak berubah).",
  },
  {
    id: "sci-f2-c7-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan arus dalam litar bersiri dan litar selari.",
    back: "Litar bersiri: I = I₁ = I₂ (sama di setiap titik). Litar selari: I = I₁ + I₂ (jumlah arus).",
  },
  {
    id: "sci-f2-c7-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan voltan dalam litar bersiri dan litar selari.",
    back: "Litar bersiri: V = V₁ + V₂ (jumlah voltan). Litar selari: V = V₁ = V₂ (sama merentasi setiap perintang).",
  },
  {
    id: "sci-f2-c7-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan rintangan berkesan dalam litar bersiri dan litar selari.",
    back: "Litar bersiri: R = R₁ + R₂ (jumlah rintangan). Litar selari: 1/R = 1/R₁ + 1/R₂.",
  },
  {
    id: "sci-f2-c7-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Namakan kelebihan litar bersiri.",
    back: "Setiap komponen menerima arus yang sama; dikawal oleh suis yang sama; peningkatan voltan membekalkan lebih banyak arus.",
  },
  {
    id: "sci-f2-c7-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Namakan kekurangan litar bersiri.",
    back: "Satu peralatan rosak menyebabkan semua peralatan lain berhenti; rintangan meningkat dan arus berkurang apabila ditambah peralatan; tidak boleh dimatikan secara berasingan.",
  },
  {
    id: "sci-f2-c7-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Namakan kelebihan litar selari.",
    back: "Setiap peralatan boleh dihidup/dimatikan secara berasingan; penambahan peralatan tidak menjejaskan peralatan lain.",
  },
  {
    id: "sci-f2-c7-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Namakan kekurangan litar selari.",
    back: "Voltan setiap peralatan tidak boleh diselaraskan kerana voltan adalah sama dengan sumber voltan.",
  },
  {
    id: "sci-f2-c7-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Mengapakah pendawaian rumah disambung secara selari?",
    back: "Supaya setiap lampu mendapat voltan yang sama daripada bekalan kuasa utama dan boleh dikawal berasingan.",
  },
  {
    id: "sci-f2-c7-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan arah aliran elektron dengan arah aliran arus dalam litar.",
    back: "Elektron mengalir dari terminal negatif ke positif. Arus mengalir dari terminal positif ke negatif.",
  },
  {
    id: "sci-f2-c7-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah dua faktor yang mempengaruhi kekuatan medan magnet elektromagnet?",
    back: "Magnitud arus (lebih besar arus, lebih kuat medan) dan bilangan lilitan gegelung (lebih banyak lilitan, lebih kuat medan).",
  },
  {
    id: "sci-f2-c7-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan corak medan magnet wayar lurus dengan wayar bergegelung.",
    back: "Kedua-dua menghasilkan garis medan magnet berbentuk bulatan sepusat (concentric circles).",
  },
  {
    id: "sci-f2-c7-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Namakan tiga ciri garis medan magnet.",
    back: "Bermula dari kutub utara dan berakhir di kutub selatan; tidak pernah bertemu atau bersilang; lebih rapat di kawasan medan lebih kuat.",
  },
  {
    id: "sci-f2-c7-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bagaimanakah kekutuban solenoid ditentukan oleh arah arus?",
    back: "Arus dalam arah lawan jam menghasilkan kutub utara; arus mengikut arah jam menghasilkan kutub selatan.",
  },
  {
    id: "sci-f2-c7-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Bandingkan kesan magnet pada elektromagnet dengan magnet kekal.",
    back: "Elektromagnet: kesan magnet sementara, hanya wujud apabila arus mengalir. Magnet kekal: kesan magnet kekal sentiasa wujud.",
  },
  {
    id: "sci-f2-c7-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Berikan contoh penggunaan elektromagnet dalam kehidupan harian.",
    back: "Loceng elektrik dan kunci magnet pada pintu.",
  },
  {
    id: "sci-f2-c7-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Mengapakah skrin TV cepat berdebu?",
    back: "Cas negatif pada debu tertarik kepada cas positif pada skrin TV; kain mikrofiber anti-elektrostatik boleh mengurangkan kesan ini.",
  },
  {
    id: "sci-f2-c7-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah alat yang digunakan untuk simulasi pembentukan kilat di makmal sekolah?",
    back: "Penjana Van de Graaff atau mesin Wimhurst.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c7-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Lampu kereta mengalirkan arus 0.025 A pada akumulator 12 V. Berapakah rintangannya?",
    back: "R = V/I = 12/0.025 = 480 Ω.",
  },
  {
    id: "sci-f2-c7-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Dua perintang 2 Ω disambung bersiri pada bekalan 6 V. Berapakah arus litar?",
    back: "R = R₁ + R₂ = 4 Ω. I = V/R = 6/4 = 1.5 A.",
  },
  {
    id: "sci-f2-c7-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Dua perintang 2 Ω disambung selari pada bekalan 6 V. Berapakah jumlah arus litar?",
    back: "1/R = 1/2 + 1/2 = 1, R = 1 Ω. I₁ = 3 A, I₂ = 3 A. Jumlah I = 6 A.",
  },
  {
    id: "sci-f2-c7-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Lampu hiasan kekal menyala kecuali satu yang rosak. Apakah jenis litar ini?",
    back: "Litar selari — setiap laluan berasingan, jadi peralatan lain tidak terjejas apabila satu rosak.",
  },
  {
    id: "sci-f2-c7-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Mengapa menambah peralatan dalam litar bersiri mengurangkan arus, tetapi tidak dalam litar selari?",
    back: "Litar bersiri: jumlah rintangan bertambah (R = R₁ + R₂...) sebab itu arus berkurang. Litar selari: setiap laluan bebas dengan voltan sama, jadi tidak terjejas.",
  },
  {
    id: "sci-f2-c7-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah magnet yang dipatahkan kepada dua menghasilkan satu kutub setiap bahagian?",
    back: "Tidak. Setiap bahagian magnet yang dipatahkan masih mempunyai dua kutub (utara dan selatan).",
  },
  {
    id: "sci-f2-c7-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Mengapa wayar nikrom yang lebih panjang mengurangkan aliran arus dalam litar?",
    back: "Wayar yang lebih panjang mempunyai rintangan lebih tinggi; mengikut Hukum Ohm (I = V/R), rintangan tinggi pada voltan tetap mengurangkan arus.",
  },
  {
    id: "sci-f2-c7-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Satu solenoid membawa arus dalam arah lawan jam dari satu hujung. Apakah kutub yang terbentuk?",
    back: "Kutub utara — arus lawan jam (dilihat dari hujung tersebut) menghasilkan kutub utara.",
  },
  {
    id: "sci-f2-c7-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah corak medan magnet berbeza apabila arah arus ditukar?",
    back: "Tidak. Corak medan magnet (bulatan sepusat) tidak berubah, tetapi arah medan magnet ditentukan oleh arah arus.",
  },
  {
    id: "sci-f2-c7-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan 'bandingkan litar bersiri dan litar selari' dengan markah penuh?",
    back: "Nyatakan persamaan arus/voltan (I=I₁=I₂ vs V=V₁=V₂) dan rintangan berkesan (R=R₁+R₂ vs 1/R=1/R₁+1/R₂), serta satu kelebihan/kekurangan setiap satu.",
  },
  {
    id: "sci-f2-c7-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Mengapakah debu bercas negatif tertarik kepada skrin TV bercas positif?",
    back: "Kerana cas yang bertentangan saling menarik — fenomena ini ialah daya elektrostatik antara dua jenis cas berlainan.",
  },
  {
    id: "sci-f2-c7-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[Fakta Penting] Apakah dua bahan yang digunakan untuk simulasi pembentukan kilat di makmal?",
    back: "Penjana Van de Graaff dan mesin Wimhurst.",
  },
  {
    id: "sci-f2-c7-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Bagaimana konduktor kilat melindungi bangunan?",
    back: "Ia menyediakan laluan rintangan rendah untuk cas elektrik mengalir terus ke dalam tanah, mengelakkan kerosakan struktur bangunan.",
  },
  {
    id: "sci-f2-c7-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah arah aliran arus sama dengan arah aliran elektron?",
    back: "Tidak. Arus mengalir dari positif ke negatif, manakala elektron mengalir dari negatif ke positif — arah bertentangan.",
  },
  {
    id: "sci-f2-c7-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Mengapa litar selari lebih sesuai untuk pendawaian rumah berbanding litar bersiri?",
    back: "Litar selari membolehkan setiap peralatan dikawal berasingan dan satu kerosakan tidak menjejaskan peralatan lain, berbeza dengan litar bersiri.",
  },
  {
    id: "sci-f2-c7-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Bagaimana eksperimen membuktikan bilangan lilitan gegelung mempengaruhi kekuatan medan magnet?",
    back: "Dengan menambah bilangan lilitan pada gegelung sambil mengekalkan arus, bilangan pin yang ditarik oleh rod besi meningkat, menunjukkan medan magnet lebih kuat.",
  },
  {
    id: "sci-f2-c7-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Apakah fungsi panel pengagihan dalam sistem pendawaian rumah?",
    back: "Mengawal arus yang mengalir daripada bekalan kuasa utama ke litar di rumah.",
  },
  {
    id: "sci-f2-c7-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah meningkatkan bilangan peralatan dalam litar bersiri meningkatkan arus?",
    back: "Tidak. Ia meningkatkan rintangan keseluruhan dan justeru mengurangkan aliran arus, bukan meningkatkannya.",
  },
  {
    id: "sci-f2-c7-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "[KBAT] Bagaimana petua tangan kanan digunakan untuk menentukan arah medan magnet wayar lurus?",
    back: "Apabila ibu jari tangan kanan menunjukkan arah arus, jari-jari lain yang dilengkungkan menunjukkan arah medan magnet di sekeliling wayar.",
  },
  {
    id: "sci-f2-c7-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 7",
    lang: "bm",
    front: "Ringkaskan peta konsep Bab 7 dalam satu ayat.",
    back: "Bab 7 merangkumi cas elektrostatik, arus, voltan dan rintangan (Hukum Ohm), litar bersiri dan selari, serta kemagnetan dan elektromagnet.",
  },
];
