import type { QuizQuestion } from "@/data/content";

export const scienceF2C7QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c7-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What does energy mean?",
    options: [
      "The ability to do work",
      "The speed of a moving object",
      "The total mass of an object",
      "The distance between two objects",
    ],
    answerIndex: 0,
    explanation: "Energy means the ability to do work. The S.I. unit for energy is joule (J).",
  },
  {
    id: "sci-f2-c7-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "Where should an ammeter be connected to measure the current through a bulb?",
    options: [
      "In series with the bulb",
      "In parallel with the bulb",
      "Across the two ends of the cell",
      "Anywhere in the circuit",
    ],
    answerIndex: 0,
    explanation: "An ammeter is connected in series so that the same current flows through both the ammeter and the bulb.",
  },
  {
    id: "sci-f2-c7-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "An object that loses electrons becomes...",
    options: ["Positively charged", "Negatively charged", "Neutral", "Uncharged"],
    answerIndex: 0,
    explanation: "The object that loses electrons becomes positively charged; the object that gains electrons becomes negatively charged.",
  },
  {
    id: "sci-f2-c7-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is the function of an electroscope?",
    options: [
      "To detect the existence of electric charges on an object",
      "To measure electric current",
      "To measure circuit voltage",
      "To produce a magnetic field",
    ],
    answerIndex: 0,
    explanation: "An electroscope is a device used to detect the existence of electric charges on an object.",
  },
  {
    id: "sci-f2-c7-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is the function of an ammeter?",
    options: [
      "To measure electric current",
      "To measure voltage",
      "To measure resistance",
      "To measure magnetic field strength",
    ],
    answerIndex: 0,
    explanation: "Electric current is measured using an ammeter, with the S.I. unit ampere (A).",
  },
  {
    id: "sci-f2-c7-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is the unit for resistance?",
    options: ["Ohm (Ω)", "Volt (V)", "Ampere (A)", "Joule (J)"],
    answerIndex: 0,
    explanation: "The unit for resistance is ohm (Ω), which is the ability of a conductor to limit the flow of electric current.",
  },
  {
    id: "sci-f2-c7-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What does Ohm's Law state?",
    options: [
      "Electric current is directly proportional to voltage, provided temperature remains unchanged",
      "Electric current is unrelated to voltage",
      "Resistance is always constant regardless of voltage",
      "Voltage is inversely proportional to time",
    ],
    answerIndex: 0,
    explanation: "Ohm's Law states that the electric current flowing through a conductor is directly proportional to the voltage across it, provided the temperature and other physical conditions remain unchanged.",
  },
  {
    id: "sci-f2-c7-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "A circuit in which components are connected one after another in a single path is called a...",
    options: ["Parallel circuit", "Series circuit", "Open circuit", "Short circuit"],
    answerIndex: 1,
    explanation: "A series circuit is made up of electrical components connected one after another, where the current flows through a single path.",
  },
  {
    id: "sci-f2-c7-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "Where should a voltmeter be connected to measure the voltage across a bulb?",
    options: [
      "In series with the bulb",
      "In parallel with the bulb",
      "Between the switch and the cell",
      "After the bulb only",
    ],
    answerIndex: 1,
    explanation: "A voltmeter is connected in parallel across the bulb, on its own branch joining the two ends of the bulb.",
  },
  {
    id: "sci-f2-c7-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is a magnetic field?",
    options: [
      "The area around the magnet that has magnetic force",
      "The material used to make a magnet",
      "The maximum temperature of a magnet",
      "The weight of a magnet",
    ],
    answerIndex: 0,
    explanation: "A magnetic field is the area around the magnet with magnetic force.",
  },
  {
    id: "sci-f2-c7-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "During a thunderstorm, why is being inside a metal-bodied car safer?",
    options: [
      "Because the rubber tyres insulate the car from the ground",
      "Because the metal body conducts charge around the outside rather than through the space inside",
      "Because the car windows block lightning",
      "Because the car engine absorbs the electric charge",
    ],
    answerIndex: 1,
    explanation: "This is the Faraday cage concept: charge travels over the outer surface of the metal body and does not pass into the space inside. The protection comes from the metal body, not from the rubber tyres.",
  },
  {
    id: "sci-f2-c7-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is the function of a lightning conductor installed on a building?",
    options: [
      "To provide a path for electric charges to flow into the ground",
      "To produce additional electrostatic charges",
      "To increase the building's resistance",
      "To attract lightning more frequently to the building",
    ],
    answerIndex: 0,
    explanation: "A lightning conductor provides a path for electric charges to flow into the ground, protecting the building from being struck by lightning.",
  },
  {
    id: "sci-f2-c7-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is the difference between a fixed resistor and a variable resistor (rheostat)?",
    options: [
      "A fixed resistor's resistance cannot be adjusted, a rheostat's resistance can be adjusted",
      "A fixed resistor is only used in parallel circuits",
      "A rheostat cannot be used in a series circuit",
      "A fixed resistor and a rheostat are the same component",
    ],
    answerIndex: 0,
    explanation: "A fixed resistor has resistance that cannot be adjusted, whereas a variable resistor (rheostat) has resistance that can be adjusted.",
  },
  {
    id: "sci-f2-c7-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "In a series circuit, how is the total voltage across each resistor calculated?",
    options: [
      "V = V₁ + V₂ (the sum of the voltages of each resistor)",
      "V = V₁ = V₂ (the same across each resistor)",
      "V = V₁ − V₂",
      "V is unrelated to a series circuit",
    ],
    answerIndex: 0,
    explanation: "In a series circuit, the total voltage is the sum of the voltages across each resistor, V = V₁ + V₂.",
  },
  {
    id: "sci-f2-c7-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "In a parallel circuit, how is the total current calculated?",
    options: [
      "I = I₁ + I₂ (sum of the current in each path)",
      "I = I₁ = I₂ (the same in each path)",
      "I = I₁ − I₂",
      "I is always zero in a parallel circuit",
    ],
    answerIndex: 0,
    explanation: "In a parallel circuit, the total current is the sum of the currents in each path, I = I₁ + I₂, while the voltage is the same across each resistor.",
  },
  {
    id: "sci-f2-c7-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "Why is the electrical wiring system in homes connected in parallel?",
    options: [
      "So that every light gets the same voltage from the main power supply",
      "So that the same current flows through every light",
      "To reduce the cost of wiring",
      "To ensure all lights go out at the same time if one is damaged",
    ],
    answerIndex: 0,
    explanation: "Home wiring is connected in parallel so that every light gets the same voltage from the main power supply, and each appliance can be controlled separately.",
  },
  {
    id: "sci-f2-c7-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is the direction of current flow compared to electron flow in a circuit?",
    options: [
      "Current flows from positive to negative terminal; electrons flow from negative to positive terminal",
      "Current and electron flow are in the same direction",
      "Current flows from negative to positive terminal; electrons flow from positive to negative terminal",
      "Current and electron flow are unrelated to the source terminals",
    ],
    answerIndex: 0,
    explanation: "The direction of current flow is from the positive terminal to the negative terminal of the source, while electron flow is the opposite, from negative to positive.",
  },
  {
    id: "sci-f2-c7-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What two factors influence the strength of the magnetic field of an electromagnet?",
    options: [
      "The magnitude of the current and the number of turns of the coil",
      "The colour of the wire and the surrounding temperature",
      "Distance from the Earth and altitude",
      "Type of battery and size of the switch",
    ],
    answerIndex: 0,
    explanation: "The magnetic field strength of an electromagnet is influenced by the magnitude of the current flowing and the number of turns of the coil.",
  },
  {
    id: "sci-f2-c7-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What is the function of the right-hand grip rule?",
    options: [
      "To determine the direction of the magnetic field for current flow in a straight wire",
      "To measure resistance in a circuit",
      "To determine the type of charge on an electroscope",
      "To calculate total voltage in a series circuit",
    ],
    answerIndex: 0,
    explanation: "The right-hand grip rule is used to determine the direction of the magnetic field for current flow in a straight wire.",
  },
  {
    id: "sci-f2-c7-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "What happens to the strength of a magnetic field as it moves away from the centre of the conductor?",
    options: [
      "The magnetic field strength decreases",
      "The magnetic field strength increases",
      "The magnetic field strength remains the same",
      "The magnetic field strength turns into electric current",
    ],
    answerIndex: 0,
    explanation: "The strength of the magnetic field reduces as it moves away from the centre of the conductor.",
  },
  {
    id: "sci-f2-c7-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "A car light bulb conducts a current of 0.025 A when connected to a 12 V car accumulator. What is the resistance of the bulb?",
    options: ["48 Ω", "120 Ω", "480 Ω", "0.3 Ω"],
    answerIndex: 2,
    explanation: "Using R = V/I = 12/0.025 = 480 Ω.",
  },
  {
    id: "sci-f2-c7-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "Two resistors R₁ = 2 Ω and R₂ = 2 Ω are connected in series with a 6 V supply. What is the current flowing in the circuit?",
    options: ["0.75 A", "1.5 A", "3 A", "6 A"],
    answerIndex: 1,
    explanation: "Effective resistance R = R₁ + R₂ = 4 Ω. Current I = V/R = 6/4 = 1.5 A.",
  },
  {
    id: "sci-f2-c7-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "Two resistors R₁ = 2 Ω and R₂ = 2 Ω are connected in parallel with a 6 V supply. What is the total current, I, in the circuit?",
    options: ["1 A", "3 A", "6 A", "12 A"],
    answerIndex: 2,
    explanation: "1/R = 1/2 + 1/2 = 1, so R = 1 Ω. I₁ = 6/2 = 3 A, I₂ = 6/2 = 3 A. Total current I = I₁ + I₂ = 6 A.",
  },
  {
    id: "sci-f2-c7-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "A string of decorative lights remains lit except for one damaged bulb. What is the most accurate conclusion about how these lights are connected?",
    options: [
      "The bulbs are connected in a parallel circuit",
      "The bulbs are connected in a series circuit",
      "The bulbs are not connected to any circuit",
      "The bulbs use an electromagnet rather than an electric circuit",
    ],
    answerIndex: 0,
    explanation: "If other bulbs remain lit even though one is damaged, this shows a parallel circuit because each path is independent; in a series circuit, all bulbs would go out.",
  },
  {
    id: "sci-f2-c7-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "Why does adding more electrical appliances in a series circuit decrease the current flow, while in a parallel circuit it does not affect other appliances?",
    options: [
      "Because a series circuit increases total resistance (R = R₁ + R₂...), while a parallel circuit has separate paths with the same voltage across each resistor",
      "Because a parallel circuit has no resistance",
      "Because a series circuit uses a lower voltage",
      "Because both circuits function in the same way",
    ],
    answerIndex: 0,
    explanation: "In a series circuit, the total resistance increases with each new component (R = R₁ + R₂), reducing the overall current. In a parallel circuit, each path is independent with the same voltage, so adding appliances does not affect other paths.",
  },
  {
    id: "sci-f2-c7-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "The north poles of two bar magnets are brought close together. What is produced in the region between them, and why?",
    options: [
      "The strongest magnetic field, because two poles combine",
      "A neutral point, because the magnetic fields from the two poles oppose each other",
      "No change to the magnetic field pattern",
      "Magnetic field lines that cross one another",
    ],
    answerIndex: 1,
    explanation: "The magnetic fields between two like poles oppose each other, producing a point with no magnetic field at all. This is called the neutral point and is marked X.",
  },
  {
    id: "sci-f2-c7-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "The longer the nichrome wire used in the circuit, the smaller the current flow. What is the most accurate explanation for this observation?",
    options: [
      "Increasing wire length increases resistance, which decreases current according to Ohm's Law",
      "Wire length has no effect on circuit resistance",
      "Longer wire produces a higher voltage",
      "Longer wire converts direct current to alternating current",
    ],
    answerIndex: 0,
    explanation: "A longer nichrome wire has higher resistance; according to Ohm's Law (I = V/R), increasing resistance at a constant voltage decreases the current.",
  },
  {
    id: "sci-f2-c7-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "A coil of wire carries an electric current in an anti-clockwise direction when viewed from one end. What polarity is produced at that end of this solenoid?",
    options: [
      "North pole",
      "South pole",
      "No pole is formed",
      "Both north and south poles simultaneously",
    ],
    answerIndex: 0,
    explanation: "For a solenoid, current flowing in an anti-clockwise direction (when viewed from that end) produces a north pole, while a clockwise direction produces a south pole.",
  },
  {
    id: "sci-f2-c7-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question: "In the investigation into the effect of current on magnetic field strength, the number of coil turns is kept at 10. What is the role of the number of turns, and what is the responding variable?",
    options: [
      "The number of turns is the manipulated variable; the current is the responding variable",
      "The number of turns is the controlled variable; the number of pins attracted is the responding variable",
      "The number of turns is the responding variable; the current is the controlled variable",
      "Both the number of turns and the current are manipulated variables",
    ],
    answerIndex: 1,
    explanation: "The current is manipulated, the number of coil turns is kept constant at 10, and what is observed and measured as the outcome is the number of pins attracted by the iron rod.",
  },
  {
    id: "sci-f2-c7-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "dlp",
    question:
      "A student claims that a series circuit is better than a parallel circuit for home wiring because it is easier to install. What is the main disadvantage that proves this claim is unsuitable for home use?",
    options: [
      "In a series circuit, one damaged appliance causes all other appliances to stop functioning, and each appliance cannot be switched off individually",
      "A series circuit uses more wire than a parallel circuit",
      "A series circuit cannot use a switch",
      "A series circuit can only be used at night",
    ],
    answerIndex: 0,
    explanation: "The main disadvantage of a series circuit for home use is that when one appliance is damaged, all other appliances stop functioning, and each appliance cannot be switched on or off individually — the main reason parallel circuits are used in home wiring.",
  },
];
