import type { QuizQuestion } from "@/data/content";

export const scienceF2C7QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c7-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah maksud tenaga?",
    options: [
      "Kemampuan untuk melakukan kerja",
      "Kelajuan pergerakan objek",
      "Jumlah jisim sesuatu objek",
      "Jarak antara dua objek",
    ],
    answerIndex: 0,
    explanation: "Tenaga bermaksud kemampuan untuk melakukan kerja. Unit SI bagi tenaga adalah joule (J).",
  },
  {
    id: "sci-f2-c7-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah yang terhasil apabila dua objek berlainan jenis digosok bersama?",
    options: [
      "Cas elektrostatik",
      "Arus terus yang besar",
      "Medan magnet kekal",
      "Haba yang sejuk",
    ],
    answerIndex: 0,
    explanation: "Cas elektrostatik terhasil daripada pemindahan elektron antara dua objek apabila digosok bersama.",
  },
  {
    id: "sci-f2-c7-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Objek yang kehilangan elektron akan menjadi bercas...",
    options: ["Positif", "Negatif", "Neutral", "Tidak bercas"],
    answerIndex: 0,
    explanation: "Objek yang kehilangan elektron menjadi bercas positif; objek yang memperoleh elektron menjadi bercas negatif.",
  },
  {
    id: "sci-f2-c7-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah fungsi elektroskop?",
    options: [
      "Mengesan kewujudan cas elektrik pada sesuatu objek",
      "Mengukur arus elektrik",
      "Mengukur voltan litar",
      "Menghasilkan medan magnet",
    ],
    answerIndex: 0,
    explanation: "Elektroskop ialah alat yang digunakan untuk mengesan kewujudan cas elektrik pada sesuatu objek.",
  },
  {
    id: "sci-f2-c7-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah fungsi ammeter?",
    options: [
      "Mengukur arus elektrik",
      "Mengukur voltan",
      "Mengukur rintangan",
      "Mengukur kekuatan medan magnet",
    ],
    answerIndex: 0,
    explanation: "Arus elektrik diukur menggunakan ammeter, dengan unit SI ampere (A).",
  },
  {
    id: "sci-f2-c7-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah unit bagi rintangan?",
    options: ["Ohm (Ω)", "Volt (V)", "Ampere (A)", "Joule (J)"],
    answerIndex: 0,
    explanation: "Unit rintangan adalah ohm (Ω), iaitu keupayaan konduktor untuk menghalang aliran arus elektrik.",
  },
  {
    id: "sci-f2-c7-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah maksud Hukum Ohm?",
    options: [
      "Arus elektrik berkadar terus dengan voltan, dengan syarat suhu tidak berubah",
      "Arus elektrik tidak berkaitan dengan voltan",
      "Rintangan sentiasa malar tanpa mengira voltan",
      "Voltan berkadar songsang dengan masa",
    ],
    answerIndex: 0,
    explanation: "Hukum Ohm menyatakan arus elektrik yang mengalir melalui konduktor adalah berkadar terus dengan voltan, dengan syarat suhu dan keadaan fizikal yang lain kekal tidak berubah.",
  },
  {
    id: "sci-f2-c7-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Litar yang komponennya disambung secara berturutan dalam satu laluan tunggal dipanggil...",
    options: ["Litar selari", "Litar bersiri", "Litar terbuka", "Litar pintas"],
    answerIndex: 1,
    explanation: "Litar bersiri dibentuk daripada komponen elektrik yang disambung secara berturutan di mana arus mengalir melalui satu laluan tunggal.",
  },
  {
    id: "sci-f2-c7-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah sifat kutub magnet yang sama jenis?",
    options: ["Saling menolak", "Saling menarik", "Tidak memberi kesan", "Saling menetralkan"],
    answerIndex: 0,
    explanation: "Kutub yang sama saling menolak, kutub yang berbeza saling menarik.",
  },
  {
    id: "sci-f2-c7-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah maksud medan magnet?",
    options: [
      "Kawasan sekeliling magnet yang mempunyai daya magnet",
      "Bahan yang digunakan untuk membuat magnet",
      "Suhu maksimum sesuatu magnet",
      "Berat sesuatu magnet",
    ],
    answerIndex: 0,
    explanation: "Medan magnet ialah kawasan sekeliling magnet yang mempunyai daya magnet.",
  },
  {
    id: "sci-f2-c7-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Mengapakah bahagian atas awan bercas positif semasa kejadian kilat?",
    options: [
      "Geseran antara awan dan udara memisahkan cas, dengan bahagian atas kehilangan elektron",
      "Bahagian atas awan lebih sejuk daripada bahagian bawah",
      "Bumi menolak cas positif ke atas awan",
      "Awan tidak mempunyai cas pada bahagian atas",
    ],
    answerIndex: 0,
    explanation: "Geseran antara awan dan udara menyebabkan awan bercas; bahagian atas awan bercas positif, bahagian bawah bercas negatif.",
  },
  {
    id: "sci-f2-c7-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah fungsi konduktor kilat yang dipasang pada bangunan?",
    options: [
      "Menyediakan laluan bagi cas elektrik mengalir ke dalam tanah",
      "Menghasilkan cas elektrostatik tambahan",
      "Menambah rintangan bangunan",
      "Menarik kilat lebih kerap ke bangunan",
    ],
    answerIndex: 0,
    explanation: "Konduktor kilat menyediakan laluan bagi cas elektrik mengalir ke dalam tanah, melindungi bangunan daripada disambar kilat.",
  },
  {
    id: "sci-f2-c7-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah perbezaan antara perintang tetap dan perintang berubah (reostat)?",
    options: [
      "Perintang tetap mempunyai rintangan yang tidak dapat diselaraskan, reostat dapat diselaraskan",
      "Perintang tetap hanya digunakan dalam litar selari",
      "Reostat tidak boleh digunakan dalam litar bersiri",
      "Perintang tetap dan reostat adalah komponen yang sama",
    ],
    answerIndex: 0,
    explanation: "Perintang tetap mempunyai rintangan yang tidak dapat diselaraskan, manakala perintang berubah (reostat) mempunyai rintangan yang dapat diselaraskan.",
  },
  {
    id: "sci-f2-c7-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Dalam litar bersiri, bagaimanakah voltan merentasi setiap perintang dikira?",
    options: [
      "V = V₁ + V₂ (jumlah voltan setiap perintang)",
      "V = V₁ = V₂ (sama pada setiap perintang)",
      "V = V₁ − V₂",
      "V tidak berkaitan dengan litar bersiri",
    ],
    answerIndex: 0,
    explanation: "Dalam litar bersiri, voltan keseluruhan adalah jumlah voltan merentasi setiap perintang, V = V₁ + V₂.",
  },
  {
    id: "sci-f2-c7-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Dalam litar selari, bagaimanakah arus keseluruhan dikira?",
    options: [
      "I = I₁ + I₂ (jumlah arus setiap laluan)",
      "I = I₁ = I₂ (sama pada setiap laluan)",
      "I = I₁ − I₂",
      "I sentiasa sifar dalam litar selari",
    ],
    answerIndex: 0,
    explanation: "Dalam litar selari, jumlah arus adalah hasil tambah arus pada setiap laluan, I = I₁ + I₂, manakala voltan adalah sama merentasi setiap perintang.",
  },
  {
    id: "sci-f2-c7-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Mengapakah sistem pendawaian elektrik di rumah disambung secara selari?",
    options: [
      "Supaya setiap lampu mendapat voltan yang sama daripada bekalan kuasa utama",
      "Supaya arus yang sama mengalir melalui setiap lampu",
      "Untuk mengurangkan kos pendawaian",
      "Untuk memastikan semua lampu terpadam serentak jika satu rosak",
    ],
    answerIndex: 0,
    explanation: "Pendawaian rumah disambung secara selari supaya setiap lampu mendapat voltan yang sama daripada bekalan kuasa utama, dan setiap peralatan boleh dikawal berasingan.",
  },
  {
    id: "sci-f2-c7-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah arah aliran arus elektrik berbanding arah aliran elektron dalam litar?",
    options: [
      "Arah arus adalah dari terminal positif ke negatif; arah elektron adalah dari negatif ke positif",
      "Arah arus dan arah elektron adalah sama",
      "Arah arus adalah dari negatif ke positif; arah elektron adalah dari positif ke negatif",
      "Arah arus dan elektron tidak berkaitan dengan terminal sumber",
    ],
    answerIndex: 0,
    explanation: "Arah aliran arus adalah daripada terminal positif kepada terminal negatif sumber elektrik, manakala arah aliran elektron adalah sebaliknya, daripada terminal negatif kepada terminal positif.",
  },
  {
    id: "sci-f2-c7-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah dua faktor yang mempengaruhi kekuatan medan magnet bagi sebuah elektromagnet?",
    options: [
      "Magnitud arus dan bilangan lilitan gegelung",
      "Warna wayar dan suhu persekitaran",
      "Jarak dari bumi dan ketinggian tempat",
      "Jenis bateri dan saiz suis",
    ],
    answerIndex: 0,
    explanation: "Eksperimen 7.2 menunjukkan kekuatan medan magnet dipengaruhi oleh magnitud arus yang mengalir dan bilangan lilitan gegelung.",
  },
  {
    id: "sci-f2-c7-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah fungsi petua tangan kanan?",
    options: [
      "Menentukan arah medan magnet bagi aliran arus dalam wayar lurus",
      "Mengukur rintangan dalam litar",
      "Menentukan jenis cas pada elektroskop",
      "Mengira jumlah voltan dalam litar bersiri",
    ],
    answerIndex: 0,
    explanation: "Petua tangan kanan (right-hand grip rule) digunakan untuk menentukan arah medan magnet bagi aliran arus dalam wayar lurus.",
  },
  {
    id: "sci-f2-c7-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 7",
    lang: "bm",
    question: "Apakah yang berlaku kepada kekuatan medan magnet apabila bergerak jauh daripada pusat konduktor?",
    options: [
      "Kekuatan medan magnet berkurang",
      "Kekuatan medan magnet bertambah",
      "Kekuatan medan magnet kekal sama",
      "Kekuatan medan magnet bertukar menjadi arus elektrik",
    ],
    answerIndex: 0,
    explanation: "Kekuatan medan magnet berkurang apabila bergerak jauh daripada pusat konduktor.",
  },
  {
    id: "sci-f2-c7-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Lampu kereta mengalirkan arus 0.025 A apabila disambungkan kepada akumulator kereta 12 V. Berapakah rintangan lampu tersebut?",
    options: ["48 Ω", "120 Ω", "480 Ω", "0.3 Ω"],
    answerIndex: 2,
    explanation: "Menggunakan R = V/I = 12/0.025 = 480 Ω.",
  },
  {
    id: "sci-f2-c7-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Dua perintang R₁ = 2 Ω dan R₂ = 2 Ω disambung secara bersiri pada bekalan 6 V. Berapakah arus yang mengalir dalam litar?",
    options: ["0.75 A", "1.5 A", "3 A", "6 A"],
    answerIndex: 1,
    explanation: "Rintangan berkesan R = R₁ + R₂ = 4 Ω. Arus I = V/R = 6/4 = 1.5 A.",
  },
  {
    id: "sci-f2-c7-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Dua perintang R₁ = 2 Ω dan R₂ = 2 Ω disambung secara selari pada bekalan 6 V. Berapakah jumlah arus, I, dalam litar?",
    options: ["1 A", "3 A", "6 A", "12 A"],
    answerIndex: 2,
    explanation: "1/R = 1/2 + 1/2 = 1, maka R = 1 Ω. I₁ = 6/2 = 3 A, I₂ = 6/2 = 3 A. Jumlah arus I = I₁ + I₂ = 6 A.",
  },
  {
    id: "sci-f2-c7-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Satu siri lampu hiasan masih menyala kesemuanya kecuali satu lampu yang rosak. Apakah kesimpulan yang sesuai tentang susunan litar lampu ini?",
    options: [
      "Lampu disambung secara litar selari",
      "Lampu disambung secara litar bersiri",
      "Lampu tidak disambung kepada sebarang litar",
      "Lampu menggunakan elektromagnet, bukan litar elektrik",
    ],
    answerIndex: 0,
    explanation: "Jika lampu lain masih menyala walaupun satu rosak, ini menunjukkan litar selari kerana setiap laluan adalah berasingan; dalam litar bersiri, semua lampu akan terpadam.",
  },
  {
    id: "sci-f2-c7-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Mengapakah menambah lebih banyak peralatan elektrik dalam litar bersiri mengurangkan aliran arus, sedangkan dalam litar selari ia tidak menjejaskan peralatan lain?",
    options: [
      "Kerana litar bersiri meningkatkan jumlah rintangan (R = R₁ + R₂...), manakala litar selari mempunyai laluan berasingan dengan voltan sama merentasi setiap perintang",
      "Kerana litar selari tidak mempunyai rintangan",
      "Kerana litar bersiri menggunakan voltan yang lebih rendah",
      "Kerana kedua-dua litar berfungsi dengan cara yang sama",
    ],
    answerIndex: 0,
    explanation: "Dalam litar bersiri, rintangan keseluruhan bertambah dengan setiap komponen baharu (R = R₁ + R₂), mengurangkan arus keseluruhan. Dalam litar selari, setiap laluan adalah bebas dengan voltan sama, jadi penambahan peralatan tidak menjejaskan laluan lain.",
  },
  {
    id: "sci-f2-c7-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Sebatang magnet dipatahkan kepada dua bahagian. Apakah yang akan diperhatikan tentang kutub magnet pada kedua-dua bahagian tersebut?",
    options: [
      "Setiap bahagian masih mempunyai dua kutub (utara dan selatan)",
      "Setiap bahagian hanya mempunyai satu kutub sahaja",
      "Kedua-dua bahagian akan kehilangan sifat magnet",
      "Hanya satu bahagian akan mengekalkan sifat magnet",
    ],
    answerIndex: 0,
    explanation: "Magnet yang dipatahkan kepada dua bahagian masih mempunyai dua kutub pada setiap bahagian, bukan satu kutub setiap bahagian.",
  },
  {
    id: "sci-f2-c7-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Dalam Eksperimen 7.1, semakin panjang wayar nikrom yang digunakan dalam litar, semakin kecil aliran arus. Apakah penjelasan yang sesuai bagi pemerhatian ini?",
    options: [
      "Panjang wayar yang bertambah meningkatkan rintangan, sekali gus mengurangkan arus mengikut Hukum Ohm",
      "Panjang wayar tidak memberi kesan kepada rintangan litar",
      "Wayar yang lebih panjang menghasilkan voltan yang lebih tinggi",
      "Wayar yang lebih panjang menukar arus terus kepada arus ulang-alik",
    ],
    answerIndex: 0,
    explanation: "Wayar nikrom yang lebih panjang mempunyai rintangan yang lebih tinggi; mengikut Hukum Ohm (I = V/R), peningkatan rintangan dengan voltan tetap akan mengurangkan arus.",
  },
  {
    id: "sci-f2-c7-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Sebuah gegelung wayar membawa arus elektrik dalam arah lawan jam apabila dilihat dari satu hujung. Apakah kekutuban yang terhasil pada hujung tersebut bagi solenoid ini?",
    options: [
      "Kutub utara",
      "Kutub selatan",
      "Tidak terbentuk sebarang kutub",
      "Kedua-dua kutub utara dan selatan serentak",
    ],
    answerIndex: 0,
    explanation: "Bagi solenoid, arus yang mengalir dalam arah lawan jam (apabila dilihat dari hujung tersebut) menghasilkan kutub utara, manakala arah jam menghasilkan kutub selatan.",
  },
  {
    id: "sci-f2-c7-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Skrin TV menjadi cepat berdebu disebabkan tarikan elektrostatik. Berdasarkan konsep cas elektrostatik, mengapakah debu (bercas negatif) tertarik kepada skrin TV?",
    options: [
      "Kerana skrin TV bercas positif akibat geseran semasa beroperasi, dan cas bertentangan saling menarik",
      "Kerana debu dan skrin TV bercas sama, dan cas yang sama saling menarik",
      "Kerana skrin TV tidak mempunyai sebarang cas",
      "Kerana graviti menyebabkan debu melekat pada skrin",
    ],
    answerIndex: 0,
    explanation: "Skrin TV memperoleh cas positif; oleh sebab cas yang bertentangan saling menarik, debu yang bercas negatif tertarik kepadanya. Kain mikrofiber anti-elektrostatik dapat mengurangkan kesan ini.",
  },
  {
    id: "sci-f2-c7-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 7",
    lang: "bm",
    question:
      "Seorang murid mendakwa bahawa litar bersiri lebih baik daripada litar selari untuk pendawaian rumah kerana lebih mudah dipasang. Apakah kelemahan utama yang membuktikan dakwaan ini tidak sesuai untuk kegunaan rumah?",
    options: [
      "Dalam litar bersiri, satu peralatan rosak akan menyebabkan semua peralatan lain berhenti berfungsi, dan setiap peralatan tidak boleh dimatikan secara berasingan",
      "Litar bersiri menggunakan lebih banyak wayar berbanding litar selari",
      "Litar bersiri tidak boleh menggunakan suis",
      "Litar bersiri hanya boleh digunakan pada waktu malam",
    ],
    answerIndex: 0,
    explanation: "Kekurangan utama litar bersiri untuk kegunaan rumah ialah apabila satu peralatan rosak, semua peralatan lain berhenti berfungsi, dan setiap peralatan tidak boleh dihidup/dimatikan secara berasingan — sebab utama litar selari digunakan dalam pendawaian rumah.",
  },
];
