import type { QuizQuestion } from "@/data/types";

export const scienceF1C6QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f1-c6-dlp-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is an atom?",
    options: ["The basic unit of matter", "A mixture of elements", "A non-metal substance", "A positively charged particle"],
    answerIndex: 0,
    explanation: "An atom is the basic unit that makes up all matter.",
  },
  {
    id: "sci-f1-c6-dlp-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which subatomic particle is positively charged?",
    options: ["Proton", "Neutron", "Electron", "Molecule"],
    answerIndex: 0,
    explanation: "A proton is a positively charged subatomic particle.",
  },
  {
    id: "sci-f1-c6-dlp-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which subatomic particle has no charge?",
    options: ["Neutron", "Proton", "Electron", "Ion"],
    answerIndex: 0,
    explanation: "A neutron is neutral and has no charge.",
  },
  {
    id: "sci-f1-c6-dlp-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which subatomic particle is negatively charged?",
    options: ["Electron", "Proton", "Neutron", "Nucleus"],
    answerIndex: 0,
    explanation: "An electron is a negatively charged subatomic particle.",
  },
  {
    id: "sci-f1-c6-dlp-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Where are protons and neutrons found in an atom?",
    options: ["Nucleus", "Electron shells", "Outside the atom", "Only in molecules"],
    answerIndex: 0,
    explanation: "The nucleus is at the centre of the atom and contains protons and neutrons.",
  },
  {
    id: "sci-f1-c6-dlp-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Where do electrons move around the nucleus?",
    options: ["In shells", "Inside protons", "Inside neutrons", "Only inside compounds"],
    answerIndex: 0,
    explanation: "Electrons move around the nucleus in shells.",
  },
  {
    id: "sci-f1-c6-dlp-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "When is an atom neutral?",
    options: [
      "When the number of protons equals the number of electrons",
      "When the number of neutrons equals the number of electrons",
      "When there are more protons than electrons",
      "When the atom has no nucleus",
    ],
    answerIndex: 0,
    explanation: "A neutral atom has the same number of protons and electrons.",
  },
  {
    id: "sci-f1-c6-dlp-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is a molecule?",
    options: [
      "A neutral particle made of two or more atoms chemically combined",
      "Only one type of atom",
      "A physical mixture of two substances",
      "A shell around an atom",
    ],
    answerIndex: 0,
    explanation: "A molecule is a neutral particle made up of two or more atoms chemically combined.",
  },
  {
    id: "sci-f1-c6-dlp-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is an element?",
    options: [
      "A substance made of only one type of atom",
      "A substance mixed physically",
      "A substance separated by filtration",
      "A substance containing all types of atoms",
    ],
    answerIndex: 0,
    explanation: "An element is the simplest substance made up of only one type of atom.",
  },
  {
    id: "sci-f1-c6-dlp-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is a compound?",
    options: [
      "A substance formed when two or more elements combine chemically",
      "A substance mixed without reaction",
      "A substance made of one atom only",
      "A substance with no chemical bonds",
    ],
    answerIndex: 0,
    explanation: "A compound forms when two or more elements combine chemically.",
  },
  {
    id: "sci-f1-c6-dlp-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which statement is most accurate about the classification of elements in the Periodic Table?",
    options: [
      "Metals, non-metals and noble gases can be identified from their positions in the Periodic Table",
      "All elements on the left side of the Periodic Table are non-metals",
      "All elements that are gases are classified as noble gases",
      "Elements and compounds are arranged together in the Periodic Table",
    ],
    answerIndex: 0,
    explanation: "The Periodic Table arranges elements systematically and allows metals, non-metals and noble gases to be identified from their positions.",
  },
  {
    id: "sci-f1-c6-dlp-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Where are metals usually located in the Periodic Table?",
    options: ["On the left side", "On the right side", "Only in Group 18", "Outside the Periodic Table"],
    answerIndex: 0,
    explanation: "Metals are usually located on the left side of the Periodic Table.",
  },
  {
    id: "sci-f1-c6-dlp-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Where are non-metals usually located in the Periodic Table?",
    options: ["On the right side", "On the left side", "In the middle of all metals", "Inside atomic shells"],
    answerIndex: 0,
    explanation: "Non-metals are usually located on the right side of the Periodic Table.",
  },
  {
    id: "sci-f1-c6-dlp-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "Inert gases are located in which group?",
    options: ["Group 18", "Group 1", "Group 2", "Group 7"],
    answerIndex: 0,
    explanation: "Inert gases are located in Group 18.",
  },
  {
    id: "sci-f1-c6-dlp-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Easy",
    question: "A substance has a shiny surface, can be hammered into shape and conducts electricity well. How should it most likely be classified?",
    options: [
      "Non-metal",
      "Noble gas",
      "Metal",
      "Non-metal compound",
    ],
    answerIndex: 2,
    explanation: "A shiny surface, malleability and good electrical conductivity are common properties of metals.",
  },
  {
    id: "sci-f1-c6-dlp-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "A mixture of iron filings and sulfur can still be separated using a magnet before it is heated. What does this show?",
    options: [
      "The substances in a mixture retain their original properties",
      "The mixture has produced a new substance through chemical combination",
      "Mixing causes the iron to lose its magnetic properties",
      "The mixture can only be separated by chemical methods",
    ],
    answerIndex: 0,
    explanation: "In a mixture, substances are not chemically combined and retain their original properties.",
  },
  {
    id: "sci-f1-c6-dlp-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the main difference between an element and a compound?",
    options: [
      "An element consists of one type of atom, while a compound contains two or more elements chemically combined",
      "An element contains several types of atoms, while a compound consists of only one type of atom",
      "An element consists of one type of atom, while a compound is a physical mixture of different elements",
      "Both elements and compounds consist of only one type of atom",
    ],
    answerIndex: 0,
    explanation: "An element consists of one type of atom. A compound forms when different elements combine chemically.",
  },
  {
    id: "sci-f1-c6-dlp-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "What does ductility mean?",
    options: [
      "Can be pulled into wires",
      "Can float on water",
      "Can dissolve in all liquids",
      "Can change into an inert gas",
    ],
    answerIndex: 0,
    explanation: "Ductility is the ability of a material to be pulled into wires.",
  },
  {
    id: "sci-f1-c6-dlp-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "What does malleability mean?",
    options: [
      "Can be hammered or shaped without breaking",
      "Can be pulled into liquid",
      "Can produce light",
      "Can be separated only by magnet",
    ],
    answerIndex: 0,
    explanation: "Malleability is the ability of a material to be shaped or hammered without breaking.",
  },
  {
    id: "sci-f1-c6-dlp-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is a mixture?",
    options: [
      "A substance made of two or more elements or compounds mixed physically",
      "A substance formed only through chemical bonds",
      "Only one type of atom",
      "A substance separated only by electrolysis",
    ],
    answerIndex: 0,
    explanation: "A mixture is formed when substances are mixed physically without forming a new substance.",
  },
  {
    id: "sci-f1-c6-dlp-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "Which method is suitable for separating sand from water?",
    options: ["Filtration", "Distillation", "Chromatography", "Electrolysis"],
    answerIndex: 0,
    explanation: "Filtration separates insoluble solids such as sand from liquids.",
  },
  {
    id: "sci-f1-c6-dlp-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "A mixture contains iron filings and sand. What is the simplest method for separating them?",
    options: [
      "Filtration",
      "Using a magnet",
      "Distillation",
      "Flotation",
    ],
    answerIndex: 1,
    explanation: "Iron is attracted to a magnet while sand is not, so this difference in physical properties can be used for separation.",
  },
  {
    id: "sci-f1-c6-dlp-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "Why is distillation suitable for obtaining pure water from salt water?",
    options: [
      "Dissolved salt remains on filter paper during heating",
      "Water and salt have different boiling points",
      "Water and salt are separated because salt floats on the surface",
      "Salt evaporates first and its vapour condenses into pure water",
    ],
    answerIndex: 1,
    explanation: "Distillation separates substances based on differences in boiling point. Water evaporates and is then condensed back into liquid.",
  },
  {
    id: "sci-f1-c6-dlp-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "A student wants to determine whether black ink contains several different dyes. Which method is most suitable?",
    options: [
      "Filtration",
      "Flotation",
      "Chromatography",
      "Magnetic separation",
    ],
    answerIndex: 2,
    explanation: "Chromatography can separate and identify different dyes present in a mixture.",
  },
  {
    id: "sci-f1-c6-dlp-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the main difference in composition between mixtures and compounds?",
    options: [
      "Mixtures are not fixed, compounds are fixed",
      "Mixtures are fixed, compounds are not fixed",
      "Both are always not fixed",
      "Both have no composition",
    ],
    answerIndex: 0,
    explanation: "Mixtures have non-fixed composition, while compounds have fixed composition.",
  },
  {
    id: "sci-f1-c6-dlp-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Hard",
    question: "Which of the following is a chemical change?",
    options: [
      "Ice melting",
      "Salt dissolving in water",
      "Iron rusting",
      "Water freezing",
    ],
    answerIndex: 2,
    explanation: "Rusting produces a new substance, so it is a chemical change. Melting, dissolving and freezing are physical changes.",
  },
  {
    id: "sci-f1-c6-dlp-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Hard",
    question: "Why can a compound not be separated into its elements using physical methods such as filtration or a magnet?",
    options: [
      "The elements in a compound are chemically combined",
      "The elements in a compound are physically mixed but have particles of the same size",
      "The elements in a compound retain all their original properties but have the same boiling point",
      "The elements in a compound can be separated physically if the sample size is increased",
    ],
    answerIndex: 0,
    explanation: "Elements in a compound are chemically bonded, so chemical methods are required to separate them.",
  },
  {
    id: "sci-f1-c6-dlp-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Hard",
    question: "Why are metals suitable for making electrical wires?",
    options: [
      "Metals are good electrical conductors and ductile",
      "Metals are brittle and dull",
      "Metals cannot be pulled into wires",
      "Metals do not have electrons",
    ],
    answerIndex: 0,
    explanation: "Metals conduct electricity well and can be pulled into wires.",
  },
  {
    id: "sci-f1-c6-dlp-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Hard",
    question: "10 g of substance X reacts completely with 6 g of substance Y in a closed system. What is the total mass of the products formed?",
    options: [
      "4 g",
      "10 g",
      "16 g",
      "60 g",
    ],
    answerIndex: 2,
    explanation: "Mass is conserved during a chemical change. The total mass of the reactants equals the total mass of the products, which is 16 g.",
  },
  {
    id: "sci-f1-c6-dlp-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 6",
    lang: "dlp",
    difficulty: "Hard",
    question: "Iron and sulfur are heated together until a new substance forms. Why is the product classified as a compound?",
    options: [
      "Iron and sulfur are physically mixed and retain their original properties",
      "A new substance forms through chemical combination and has properties different from the original substances",
      "The product has a composition that can be varied using any ratio of iron to sulfur",
      "The product can be separated back into iron and sulfur by physical methods",
    ],
    answerIndex: 1,
    explanation: "A compound forms when elements combine chemically to form a new substance with different properties.",
  },
];
