import type { QuizQuestion } from "@/data/types";

export const scienceF1C7QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f1-c7-bm-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah peratus nitrogen dalam udara?",
    options: ["78%", "21%", "0.03%", "0.97%"],
    answerIndex: 0,
    explanation: "Nitrogen merupakan komponen terbesar udara iaitu sebanyak 78%.",
  },
  {
    id: "sci-f1-c7-bm-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah peratus oksigen dalam udara?",
    options: ["21%", "78%", "0.03%", "0.97%"],
    answerIndex: 0,
    explanation: "Oksigen membentuk kira-kira 21% daripada udara.",
  },
  {
    id: "sci-f1-c7-bm-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah peratus karbon dioksida dalam udara?",
    options: ["0.03%", "21%", "78%", "1.0%"],
    answerIndex: 0,
    explanation: "Karbon dioksida membentuk kira-kira 0.03% daripada udara.",
  },
  {
    id: "sci-f1-c7-bm-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah atmosfera?",
    options: [
      "Lapisan udara yang mengelilingi Bumi",
      "Lapisan batu di kerak Bumi",
      "Air laut di permukaan Bumi",
      "Gas oksigen sahaja",
    ],
    answerIndex: 0,
    explanation: "Atmosfera ialah lapisan udara yang mengelilingi Bumi.",
  },
  {
    id: "sci-f1-c7-bm-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah komponen utama udara?",
    options: [
      "Nitrogen, oksigen, karbon dioksida dan gas nadir",
      "Oksigen sahaja",
      "Karbon dioksida sahaja",
      "Asap dan habuk sahaja",
    ],
    answerIndex: 0,
    explanation: "Udara ialah campuran beberapa gas termasuk nitrogen, oksigen, karbon dioksida dan gas nadir.",
  },
  {
    id: "sci-f1-c7-bm-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah aras air naik dalam balang gas semasa eksperimen lilin menyala?",
    options: [
      "Oksigen digunakan semasa pembakaran",
      "Nitrogen bertukar menjadi air",
      "Karbon dioksida hilang sepenuhnya",
      "Lilin menghasilkan gas nadir",
    ],
    answerIndex: 0,
    explanation: "Lilin menggunakan oksigen untuk pembakaran, menyebabkan ruang gas berkurang dan aras air naik.",
  },
  {
    id: "sci-f1-c7-bm-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah kepentingan oksigen?",
    options: ["Untuk respirasi dan pembakaran", "Untuk membuat belon ringan sahaja", "Untuk menggantikan semua nitrogen", "Untuk menghasilkan asap"],
    answerIndex: 0,
    explanation: "Oksigen diperlukan untuk respirasi benda hidup dan proses pembakaran.",
  },
  {
    id: "sci-f1-c7-bm-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah kepentingan karbon dioksida kepada tumbuhan?",
    options: ["Digunakan dalam fotosintesis", "Digunakan untuk respirasi manusia", "Membantu api menyala", "Menjadi gas utama udara"],
    answerIndex: 0,
    explanation: "Tumbuhan menggunakan karbon dioksida semasa fotosintesis untuk membuat makanan.",
  },
  {
    id: "sci-f1-c7-bm-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Gas nadir manakah digunakan dalam belon udara kerana ringan?",
    options: ["Helium", "Neon", "Argon", "Karbon monoksida"],
    answerIndex: 0,
    explanation: "Helium ringan dan tidak mudah terbakar, maka sesuai digunakan dalam belon.",
  },
  {
    id: "sci-f1-c7-bm-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Gas nadir manakah digunakan dalam lampu papan tanda berwarna?",
    options: ["Neon", "Helium", "Nitrogen", "Oksigen"],
    answerIndex: 0,
    explanation: "Neon digunakan dalam lampu papan tanda kerana menghasilkan cahaya berwarna terang.",
  },
  {
    id: "sci-f1-c7-bm-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah pembakaran?",
    options: [
      "Tindak balas bahan api dengan oksigen yang menghasilkan haba dan cahaya",
      "Proses tumbuhan membuat makanan",
      "Proses gas menjadi cecair",
      "Proses mengasingkan campuran",
    ],
    answerIndex: 0,
    explanation: "Pembakaran berlaku apabila bahan api bertindak balas dengan oksigen dan menghasilkan haba serta cahaya.",
  },
  {
    id: "sci-f1-c7-bm-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah tiga perkara dalam segi tiga api?",
    options: ["Bahan api, haba dan oksigen", "Air, tanah dan cahaya", "Nitrogen, neon dan argon", "Asap, habuk dan jelaga"],
    answerIndex: 0,
    explanation: "Segi tiga api terdiri daripada bahan api, haba dan oksigen.",
  },
  {
    id: "sci-f1-c7-bm-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud pencemaran udara?",
    options: [
      "Kehadiran bahan pencemar dalam udara",
      "Udara yang mengandungi nitrogen",
      "Udara yang mengelilingi Bumi",
      "Proses fotosintesis",
    ],
    answerIndex: 0,
    explanation: "Pencemaran udara berlaku apabila bahan pencemar terdapat dalam udara dan menjejaskan kualitinya.",
  },
  {
    id: "sci-f1-c7-bm-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Antara berikut, yang manakah bahan pencemar udara?",
    options: ["Asap", "Oksigen", "Helium", "Nitrogen tulen"],
    answerIndex: 0,
    explanation: "Asap ialah bahan pencemar udara yang boleh menjejaskan kesihatan.",
  },
  {
    id: "sci-f1-c7-bm-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah alat yang dapat memberi amaran awal apabila terdapat asap?",
    options: ["Pengesan asap", "Termometer", "Barometer", "Penapis cerobong"],
    answerIndex: 0,
    explanation: "Pengesan asap memberi amaran awal supaya orang boleh menyelamatkan diri.",
  },
  {
    id: "sci-f1-c7-bm-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Bagaimanakah fotosintesis membantu kitar oksigen?",
    options: [
      "Menghasilkan oksigen",
      "Menggunakan oksigen untuk membakar bahan api",
      "Menghasilkan karbon monoksida",
      "Menghapuskan semua nitrogen",
    ],
    answerIndex: 0,
    explanation: "Semasa fotosintesis, tumbuhan menghasilkan oksigen yang dilepaskan ke udara.",
  },
  {
    id: "sci-f1-c7-bm-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Proses manakah menambahkan karbon dioksida ke atmosfera?",
    options: ["Respirasi, pereputan dan pembakaran", "Fotosintesis sahaja", "Penghutanan semula sahaja", "Penggunaan helium"],
    answerIndex: 0,
    explanation: "Respirasi, pereputan dan pembakaran membebaskan karbon dioksida ke atmosfera.",
  },
  {
    id: "sci-f1-c7-bm-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah cara mengekalkan keseimbangan oksigen dan karbon dioksida?",
    options: ["Penghutanan semula", "Pembalakan haram", "Pembakaran terbuka", "Meningkatkan asap kilang"],
    answerIndex: 0,
    explanation: "Penghutanan semula menambah tumbuhan yang menjalankan fotosintesis dan membantu keseimbangan gas.",
  },
  {
    id: "sci-f1-c7-bm-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kaedah memadam api secara penyejukan?",
    options: ["Menurunkan suhu bahan terbakar", "Menambah oksigen", "Menambah bahan api", "Menambah asap"],
    answerIndex: 0,
    explanation: "Kaedah penyejukan menurunkan suhu supaya api tidak terus menyala.",
  },
  {
    id: "sci-f1-c7-bm-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kaedah memadam api secara menyelimut?",
    options: ["Menghalang bekalan oksigen", "Menambah haba", "Menambah bahan api", "Menghasilkan neon"],
    answerIndex: 0,
    explanation: "Menyelimut api memutuskan bekalan oksigen, contohnya menggunakan selimut api.",
  },
  {
    id: "sci-f1-c7-bm-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah fungsi alat pemadam api karbon dioksida?",
    options: [
      "Memadam api dengan mengurangkan oksigen di sekitar api",
      "Menambah oksigen kepada api",
      "Menghasilkan air minuman",
      "Menghasilkan bahan api baharu",
    ],
    answerIndex: 0,
    explanation: "Karbon dioksida menyelimut api dan mengurangkan bekalan oksigen.",
  },
  {
    id: "sci-f1-c7-bm-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Pencemar manakah boleh menyebabkan hujan asid?",
    options: ["Sulfur dioksida", "Helium", "Neon", "Oksigen"],
    answerIndex: 0,
    explanation: "Sulfur dioksida boleh melarut dalam air hujan dan membentuk hujan asid.",
  },
  {
    id: "sci-f1-c7-bm-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kesan karbon monoksida kepada manusia?",
    options: [
      "Mengurangkan keupayaan darah membawa oksigen",
      "Membantu fotosintesis",
      "Menyuburkan tumbuhan",
      "Menyejukkan Bumi",
    ],
    answerIndex: 0,
    explanation: "Karbon monoksida berbahaya kerana mengganggu pengangkutan oksigen dalam darah.",
  },
  {
    id: "sci-f1-c7-bm-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kesan rumah hijau yang berlebihan?",
    options: ["Pemanasan global", "Penurunan suhu Bumi secara besar-besaran", "Udara menjadi 100% oksigen", "Tiada pencemaran"],
    answerIndex: 0,
    explanation: "Kesan rumah hijau yang berlebihan memerangkap lebih banyak haba dan menyebabkan pemanasan global.",
  },
  {
    id: "sci-f1-c7-bm-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Antara berikut, yang manakah langkah mengurangkan pencemaran udara?",
    options: ["Menggunakan pengangkutan awam", "Membakar sampah terbuka", "Menebang hutan secara haram", "Meningkatkan asap kilang"],
    answerIndex: 0,
    explanation: "Pengangkutan awam mengurangkan bilangan kenderaan dan pelepasan asap.",
  },
  {
    id: "sci-f1-c7-bm-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah oksigen penting untuk pembakaran?",
    options: [
      "Oksigen membolehkan bahan api terbakar dan menghasilkan haba",
      "Oksigen memadam semua api",
      "Oksigen menukar api kepada air",
      "Oksigen ialah bahan api utama",
    ],
    answerIndex: 0,
    explanation: "Pembakaran memerlukan oksigen. Tanpa oksigen, api tidak dapat terus menyala.",
  },
  {
    id: "sci-f1-c7-bm-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah karbon monoksida sangat berbahaya?",
    options: [
      "Ia menghalang darah membawa oksigen dengan berkesan",
      "Ia membantu tumbuhan membesar cepat",
      "Ia menjadikan udara lebih segar",
      "Ia ialah gas nadir yang tidak reaktif",
    ],
    answerIndex: 0,
    explanation: "Karbon monoksida boleh bergabung dengan hemoglobin dan mengurangkan bekalan oksigen kepada badan.",
  },
  {
    id: "sci-f1-c7-bm-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Bagaimanakah pembalakan haram menjejaskan kitar oksigen?",
    options: [
      "Mengurangkan pokok yang menghasilkan oksigen melalui fotosintesis",
      "Menambah bilangan pokok muda serta-merta",
      "Menghasilkan lebih banyak helium",
      "Menghalang semua respirasi",
    ],
    answerIndex: 0,
    explanation: "Kurang pokok bermaksud kurang fotosintesis dan kurang oksigen dihasilkan.",
  },
  {
    id: "sci-f1-c7-bm-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Bagaimanakah kenderaan hibrid mengurangkan pencemaran udara?",
    options: [
      "Mengurangkan penggunaan bahan api dan pelepasan asap",
      "Menghasilkan lebih banyak sulfur dioksida",
      "Meningkatkan pembakaran terbuka",
      "Menghapuskan atmosfera",
    ],
    answerIndex: 0,
    explanation: "Kenderaan hibrid menggunakan tenaga dengan lebih cekap, lalu mengurangkan pelepasan bahan pencemar.",
  },
  {
    id: "sci-f1-c7-bm-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah hujan asid merosakkan bangunan dan tumbuhan?",
    options: [
      "Sifat berasidnya menghakis bahan dan merosakkan tisu tumbuhan",
      "Ia mengandungi helium",
      "Ia meningkatkan oksigen kepada 78%",
      "Ia menukar semua tanah menjadi air",
    ],
    answerIndex: 0,
    explanation: "Hujan asid boleh menghakis bangunan dan merosakkan daun serta tanah.",
  },
];
