import type { QuizQuestion } from "@/data/types";

export const scienceF1C7QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f1-c7-dlp-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which gas is present in the largest proportion in air?",
    options: [
      "Oxygen",
      "Carbon dioxide",
      "Nitrogen",
      "Helium",
    ],
    answerIndex: 2,
    explanation: "Nitrogen is the most abundant gas in air, while oxygen is the second most abundant.",
  },
  {
    id: "sci-f1-c7-dlp-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "What percentage of air is oxygen?",
    options: ["21%", "78%", "0.03%", "0.97%"],
    answerIndex: 0,
    explanation: "Oxygen makes up about 21% of air.",
  },
  {
    id: "sci-f1-c7-dlp-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Why is air classified as a mixture?",
    options: [
      "Air consists of one type of gas with several different properties",
      "Air consists of several gases and other components physically mixed together",
      "The gases in air combine chemically to form a new substance",
      "The components of air can only be separated by chemical methods",
    ],
    answerIndex: 1,
    explanation: "Air is a mixture of gases such as nitrogen, oxygen, carbon dioxide and noble gases, together with components such as water vapour and dust.",
  },
  {
    id: "sci-f1-c7-dlp-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is the atmosphere?",
    options: [
      "The layer of air surrounding Earth",
      "The layer of rocks in Earth's crust",
      "Sea water on Earth's surface",
      "Oxygen gas only",
    ],
    answerIndex: 0,
    explanation: "The atmosphere is the layer of air surrounding Earth.",
  },
  {
    id: "sci-f1-c7-dlp-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "What are the main components of air?",
    options: [
      "Nitrogen, oxygen, carbon dioxide and noble gases",
      "Oxygen only",
      "Carbon dioxide only",
      "Smoke and dust only",
    ],
    answerIndex: 0,
    explanation: "Air is a mixture of gases including nitrogen, oxygen, carbon dioxide and noble gases.",
  },
  {
    id: "sci-f1-c7-dlp-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "What happens if one of the three conditions required for combustion is removed?",
    options: [
      "Combustion continues as long as any one condition remains",
      "Combustion stops",
      "Combustion produces the missing condition itself",
      "Combustion becomes faster because fewer conditions are needed",
    ],
    answerIndex: 1,
    explanation: "Combustion can continue only when oxygen, heat and fuel are all present.",
  },
  {
    id: "sci-f1-c7-dlp-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Why is oxygen important to most living organisms?",
    options: [
      "Oxygen is used in respiration to release energy",
      "Oxygen is used to form glucose directly in animals",
      "Oxygen is used to store light energy in all cells",
      "Oxygen is used to replace the need for food in organisms",
    ],
    answerIndex: 0,
    explanation: "Oxygen is required during cellular respiration to help release energy from glucose.",
  },
  {
    id: "sci-f1-c7-dlp-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Why is carbon dioxide important to plants?",
    options: ["It is used in photosynthesis", "It is used for human respiration", "It helps fire burn", "It is the main gas in air"],
    answerIndex: 0,
    explanation: "Plants use carbon dioxide during photosynthesis to make food.",
  },
  {
    id: "sci-f1-c7-dlp-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which noble gas is used in balloons because it is light?",
    options: ["Helium", "Neon", "Argon", "Carbon monoxide"],
    answerIndex: 0,
    explanation: "Helium is light and not easily flammable, so it is suitable for balloons.",
  },
  {
    id: "sci-f1-c7-dlp-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which noble gas is used in colourful signboard lights?",
    options: ["Neon", "Helium", "Nitrogen", "Oxygen"],
    answerIndex: 0,
    explanation: "Neon is used in signboard lights because it produces bright coloured light.",
  },
  {
    id: "sci-f1-c7-dlp-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is combustion?",
    options: [
      "A reaction between fuel and oxygen that produces heat and light",
      "The process plants use to make food",
      "The process of gas changing into liquid",
      "The process of separating mixtures",
    ],
    answerIndex: 0,
    explanation: "Combustion occurs when fuel reacts with oxygen and produces heat and light.",
  },
  {
    id: "sci-f1-c7-dlp-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which three conditions are required for combustion to occur?",
    options: [
      "Oxygen, heat and fuel",
      "Carbon dioxide, heat and fuel",
      "Nitrogen, heat and fuel",
      "Oxygen, water and fuel",
    ],
    answerIndex: 0,
    explanation: "Combustion requires oxygen, sufficient heat and a fuel.",
  },
  {
    id: "sci-f1-c7-dlp-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is meant by air pollution?",
    options: [
      "The presence of pollutants in the air that can harm living things or the environment",
      "The presence of natural gases in air even at levels that cause no harm",
      "Changes in water vapour content that only cause cloud formation",
      "The movement of air from a high-pressure area to a low-pressure area",
    ],
    answerIndex: 0,
    explanation: "Air pollution occurs when harmful pollutants are present in the atmosphere.",
  },
  {
    id: "sci-f1-c7-dlp-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which of the following is an air pollutant?",
    options: ["Smoke", "Oxygen", "Helium", "Pure nitrogen"],
    answerIndex: 0,
    explanation: "Smoke is an air pollutant that can affect health.",
  },
  {
    id: "sci-f1-c7-dlp-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which activity is most likely to contribute to the formation of haze?",
    options: [
      "Large-scale open burning",
      "The release of water vapour as clothes dry",
      "The formation of water droplets as water vapour cools",
      "The evaporation of water from a lake",
    ],
    answerIndex: 0,
    explanation: "Open burning releases smoke and suspended particles into the atmosphere, which can contribute to haze.",
  },
  {
    id: "sci-f1-c7-dlp-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "How do green plants help maintain the oxygen content of the atmosphere?",
    options: [
      "They release oxygen during respiration",
      "They release oxygen during photosynthesis",
      "They release oxygen during decomposition",
      "They release oxygen during combustion",
    ],
    answerIndex: 1,
    explanation: "Photosynthesis releases oxygen into the atmosphere and helps maintain the oxygen cycle.",
  },
  {
    id: "sci-f1-c7-dlp-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "Which processes add carbon dioxide to the atmosphere?",
    options: ["Respiration, decomposition and combustion", "Photosynthesis only", "Reforestation only", "Use of helium"],
    answerIndex: 0,
    explanation: "Respiration, decomposition and combustion release carbon dioxide into the atmosphere.",
  },
  {
    id: "sci-f1-c7-dlp-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "Which action helps maintain the balance of oxygen and carbon dioxide?",
    options: ["Reforestation", "Illegal logging", "Open burning", "Increasing factory smoke"],
    answerIndex: 0,
    explanation: "Reforestation increases plants that carry out photosynthesis and helps balance gases.",
  },
  {
    id: "sci-f1-c7-dlp-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the cooling method in fire extinguishing?",
    options: ["Lowering the temperature of burning material", "Adding oxygen", "Adding fuel", "Adding smoke"],
    answerIndex: 0,
    explanation: "Cooling lowers the temperature so the fire cannot continue burning.",
  },
  {
    id: "sci-f1-c7-dlp-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "Why can covering a small fire with a fire blanket put out the fire?",
    options: [
      "The blanket absorbs all the fuel from the burning area",
      "The blanket cuts off the oxygen supply",
      "The blanket supplies carbon dioxide by burning its fabric",
      "The blanket changes the fuel into a substance that cannot burn",
    ],
    answerIndex: 1,
    explanation: "Removing the oxygen supply removes one of the conditions required for combustion, so the fire goes out.",
  },
  {
    id: "sci-f1-c7-dlp-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the function of a carbon dioxide fire extinguisher?",
    options: [
      "It extinguishes fire by reducing oxygen around the fire",
      "It adds oxygen to the fire",
      "It produces drinking water",
      "It produces new fuel",
    ],
    answerIndex: 0,
    explanation: "Carbon dioxide smothers fire and reduces oxygen supply.",
  },
  {
    id: "sci-f1-c7-dlp-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "Which pollutant can cause acid rain?",
    options: ["Sulfur dioxide", "Helium", "Neon", "Oxygen"],
    answerIndex: 0,
    explanation: "Sulfur dioxide can dissolve in rainwater and form acid rain.",
  },
  {
    id: "sci-f1-c7-dlp-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the effect of carbon monoxide on humans?",
    options: [
      "It reduces the ability of blood to carry oxygen",
      "It helps photosynthesis",
      "It fertilises plants",
      "It cools Earth",
    ],
    answerIndex: 0,
    explanation: "Carbon monoxide is dangerous because it affects oxygen transport in blood.",
  },
  {
    id: "sci-f1-c7-dlp-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "What may happen if the amount of carbon dioxide in the atmosphere increases excessively?",
    options: [
      "The greenhouse effect becomes stronger and Earth's temperature may rise",
      "The greenhouse effect becomes weaker and Earth's temperature may fall",
      "The greenhouse effect decreases because carbon dioxide reflects all heat into space",
      "The greenhouse effect remains unchanged because only oxygen affects heat retention",
    ],
    answerIndex: 0,
    explanation: "Increased carbon dioxide can strengthen the greenhouse effect and contribute to a rise in global temperature.",
  },
  {
    id: "sci-f1-c7-dlp-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Medium",
    question: "Which action would best help reduce air pollution from vehicles?",
    options: [
      "Encourage the use of public transport",
      "Encourage each passenger to travel in a separate car",
      "Leave vehicle engines running while waiting for passengers",
      "Delay engine maintenance on vehicles that emit excessive smoke",
    ],
    answerIndex: 0,
    explanation: "Public transport can reduce the number of individual vehicles on the road and therefore reduce pollutant emissions.",
  },
  {
    id: "sci-f1-c7-dlp-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Hard",
    question: "Why is oxygen important for combustion?",
    options: [
      "Oxygen allows fuel to burn and produce heat",
      "Oxygen extinguishes all fires",
      "Oxygen changes fire into water",
      "Oxygen is the main fuel",
    ],
    answerIndex: 0,
    explanation: "Combustion needs oxygen. Without oxygen, fire cannot continue burning.",
  },
  {
    id: "sci-f1-c7-dlp-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Hard",
    question: "Why can severe haze affect human health?",
    options: [
      "Pollutants and fine particles can enter the respiratory system",
      "Haze particles enter the body only through contaminated food",
      "Fine haze particles are completely stopped in the nose and only affect the skin",
      "Haze particles only affect health when visibility falls to zero",
    ],
    answerIndex: 0,
    explanation: "Fine particles and other pollutants can enter the respiratory tract and affect the respiratory system.",
  },
  {
    id: "sci-f1-c7-dlp-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Hard",
    question: "Large-scale deforestation can increase the amount of carbon dioxide in the atmosphere. What is the best explanation?",
    options: [
      "Fewer plants are available to absorb carbon dioxide during photosynthesis",
      "Fewer plants cause all animals to stop respiring",
      "Fewer plants cause the overall rate of photosynthesis to increase",
      "Fewer plants cause the remaining plants to absorb more carbon dioxide overall",
    ],
    answerIndex: 0,
    explanation: "With fewer plants, less carbon dioxide is removed from the atmosphere through photosynthesis.",
  },
  {
    id: "sci-f1-c7-dlp-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Hard",
    question: "A residential area experiences air pollution because rubbish is regularly burned in the open. What is the most appropriate solution?",
    options: [
      "Move the rubbish burning to an open area near the houses",
      "Stop open burning and manage the waste through proper disposal or recycling",
      "Burn the rubbish at night so that the smoke is less visible",
      "Burn small piles of rubbish every day without changing the disposal method",
    ],
    answerIndex: 1,
    explanation: "Preventing open burning and using proper waste-management methods reduces smoke and pollutant emissions.",
  },
  {
    id: "sci-f1-c7-dlp-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "dlp",
    difficulty: "Hard",
    question: "Why does acid rain damage buildings and plants?",
    options: [
      "Its acidity corrodes materials and damages plant tissues",
      "It contains helium",
      "It increases oxygen to 78%",
      "It changes all soil into water",
    ],
    answerIndex: 0,
    explanation: "Acid rain can corrode buildings and damage leaves and soil.",
  },
];
