import type { QuizQuestion } from "@/data/types";

export const scienceF1C7QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f1-c7-bm-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Gas manakah terdapat dalam kuantiti paling banyak dalam udara?",
    options: [
      "Oksigen",
      "Karbon dioksida",
      "Nitrogen",
      "Helium",
    ],
    answerIndex: 2,
    explanation: "Nitrogen merupakan gas yang paling banyak dalam udara, manakala oksigen ialah gas kedua paling banyak.",
  },
  {
    id: "sci-f1-c7-bm-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah peratus oksigen dalam udara?",
    options: ["21%", "78%", "0.03%", "0.97%"],
    answerIndex: 0,
    explanation: "Oksigen membentuk kira-kira 21% daripada udara.",
  },
  {
    id: "sci-f1-c7-bm-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah udara dikategorikan sebagai campuran?",
    options: [
      "Udara terdiri daripada satu jenis gas yang mempunyai beberapa sifat berbeza",
      "Udara terdiri daripada beberapa jenis gas dan komponen lain yang bercampur secara fizikal",
      "Gas dalam udara bergabung secara kimia untuk membentuk satu bahan baharu",
      "Komponen udara hanya boleh diasingkan melalui kaedah kimia",
    ],
    answerIndex: 1,
    explanation: "Udara ialah campuran beberapa jenis gas seperti nitrogen, oksigen, karbon dioksida dan gas nadir serta komponen lain seperti wap air dan habuk.",
  },
  {
    id: "sci-f1-c7-bm-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah atmosfera?",
    options: [
      "Lapisan udara yang mengelilingi Bumi",
      "Lapisan batu di kerak Bumi",
      "Air laut di permukaan Bumi",
      "Gas oksigen sahaja",
    ],
    answerIndex: 0,
    explanation: "Atmosfera ialah lapisan udara yang mengelilingi Bumi.",
  },
  {
    id: "sci-f1-c7-bm-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah komponen utama udara?",
    options: [
      "Nitrogen, oksigen, karbon dioksida dan gas nadir",
      "Oksigen sahaja",
      "Karbon dioksida sahaja",
      "Asap dan habuk sahaja",
    ],
    answerIndex: 0,
    explanation: "Udara ialah campuran beberapa gas termasuk nitrogen, oksigen, karbon dioksida dan gas nadir.",
  },
  {
    id: "sci-f1-c7-bm-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Jika salah satu daripada tiga syarat pembakaran disingkirkan, apakah yang akan berlaku?",
    options: [
      "Pembakaran akan berterusan selagi salah satu syarat masih tersedia",
      "Pembakaran akan berhenti",
      "Pembakaran akan menghasilkan sendiri syarat yang telah disingkirkan",
      "Pembakaran akan menjadi lebih cepat kerana kurang syarat diperlukan",
    ],
    answerIndex: 1,
    explanation: "Pembakaran hanya boleh berlaku jika oksigen, haba dan bahan api semuanya tersedia.",
  },
  {
    id: "sci-f1-c7-bm-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah oksigen penting kepada kebanyakan organisma hidup?",
    options: [
      "Oksigen digunakan dalam respirasi untuk membebaskan tenaga",
      "Oksigen digunakan untuk membentuk glukosa secara langsung dalam haiwan",
      "Oksigen digunakan untuk menyimpan tenaga cahaya dalam semua sel",
      "Oksigen digunakan untuk menggantikan keperluan organisma terhadap makanan",
    ],
    answerIndex: 0,
    explanation: "Oksigen diperlukan dalam respirasi sel bagi membantu membebaskan tenaga daripada glukosa.",
  },
  {
    id: "sci-f1-c7-bm-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah kepentingan karbon dioksida kepada tumbuhan?",
    options: ["Digunakan dalam fotosintesis", "Digunakan untuk respirasi manusia", "Membantu api menyala", "Menjadi gas utama udara"],
    answerIndex: 0,
    explanation: "Tumbuhan menggunakan karbon dioksida semasa fotosintesis untuk membuat makanan.",
  },
  {
    id: "sci-f1-c7-bm-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Gas nadir manakah digunakan dalam belon udara kerana ringan?",
    options: ["Helium", "Neon", "Argon", "Karbon monoksida"],
    answerIndex: 0,
    explanation: "Helium ringan dan tidak mudah terbakar, maka sesuai digunakan dalam belon.",
  },
  {
    id: "sci-f1-c7-bm-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Gas nadir manakah digunakan dalam lampu papan tanda berwarna?",
    options: ["Neon", "Helium", "Nitrogen", "Oksigen"],
    answerIndex: 0,
    explanation: "Neon digunakan dalam lampu papan tanda kerana menghasilkan cahaya berwarna terang.",
  },
  {
    id: "sci-f1-c7-bm-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah pembakaran?",
    options: [
      "Tindak balas bahan api dengan oksigen yang menghasilkan haba dan cahaya",
      "Proses tumbuhan membuat makanan",
      "Proses gas menjadi cecair",
      "Proses mengasingkan campuran",
    ],
    answerIndex: 0,
    explanation: "Pembakaran berlaku apabila bahan api bertindak balas dengan oksigen dan menghasilkan haba serta cahaya.",
  },
  {
    id: "sci-f1-c7-bm-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah tiga syarat yang diperlukan supaya pembakaran dapat berlaku?",
    options: [
      "Oksigen, haba dan bahan api",
      "Karbon dioksida, haba dan bahan api",
      "Nitrogen, haba dan bahan api",
      "Oksigen, air dan bahan api",
    ],
    answerIndex: 0,
    explanation: "Pembakaran memerlukan oksigen, haba yang mencukupi dan bahan api.",
  },
  {
    id: "sci-f1-c7-bm-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah yang dimaksudkan dengan pencemaran udara?",
    options: [
      "Kehadiran bahan pencemar dalam udara yang boleh memudaratkan hidupan atau alam sekitar",
      "Kehadiran gas semula jadi dalam udara walaupun pada aras yang tidak memudaratkan",
      "Perubahan kandungan wap air yang menyebabkan pembentukan awan sahaja",
      "Pergerakan udara dari kawasan bertekanan tinggi ke kawasan bertekanan rendah",
    ],
    answerIndex: 0,
    explanation: "Pencemaran udara berlaku apabila bahan pencemar hadir dalam atmosfera pada tahap yang boleh menyebabkan kemudaratan.",
  },
  {
    id: "sci-f1-c7-bm-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Antara berikut, yang manakah bahan pencemar udara?",
    options: ["Asap", "Oksigen", "Helium", "Nitrogen tulen"],
    answerIndex: 0,
    explanation: "Asap ialah bahan pencemar udara yang boleh menjejaskan kesihatan.",
  },
  {
    id: "sci-f1-c7-bm-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Easy",
    question: "Aktiviti manakah paling berkemungkinan menyumbang kepada pembentukan jerebu?",
    options: [
      "Pembakaran terbuka secara meluas",
      "Pelepasan wap air semasa pakaian dikeringkan",
      "Pembentukan titisan air apabila wap air menyejuk",
      "Penyejatan air dari permukaan tasik",
    ],
    answerIndex: 0,
    explanation: "Pembakaran terbuka menghasilkan asap dan zarah terampai yang boleh menyebabkan jerebu.",
  },
  {
    id: "sci-f1-c7-bm-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Bagaimanakah tumbuhan hijau membantu mengekalkan kandungan oksigen dalam atmosfera?",
    options: [
      "Membebaskan oksigen semasa respirasi",
      "Membebaskan oksigen semasa fotosintesis",
      "Membebaskan oksigen semasa pereputan",
      "Membebaskan oksigen semasa pembakaran",
    ],
    answerIndex: 1,
    explanation: "Fotosintesis membebaskan oksigen ke atmosfera dan membantu mengekalkan keseimbangan kitar oksigen.",
  },
  {
    id: "sci-f1-c7-bm-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Proses manakah menambahkan karbon dioksida ke atmosfera?",
    options: ["Respirasi, pereputan dan pembakaran", "Fotosintesis sahaja", "Penghutanan semula sahaja", "Penggunaan helium"],
    answerIndex: 0,
    explanation: "Respirasi, pereputan dan pembakaran membebaskan karbon dioksida ke atmosfera.",
  },
  {
    id: "sci-f1-c7-bm-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah cara mengekalkan keseimbangan oksigen dan karbon dioksida?",
    options: ["Penghutanan semula", "Pembalakan haram", "Pembakaran terbuka", "Meningkatkan asap kilang"],
    answerIndex: 0,
    explanation: "Penghutanan semula menambah tumbuhan yang menjalankan fotosintesis dan membantu keseimbangan gas.",
  },
  {
    id: "sci-f1-c7-bm-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kaedah memadam api secara penyejukan?",
    options: ["Menurunkan suhu bahan terbakar", "Menambah oksigen", "Menambah bahan api", "Menambah asap"],
    answerIndex: 0,
    explanation: "Kaedah penyejukan menurunkan suhu supaya api tidak terus menyala.",
  },
  {
    id: "sci-f1-c7-bm-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah menutup api kecil dengan selimut api boleh memadamkannya?",
    options: [
      "Selimut menyerap semua bahan api daripada kawasan kebakaran",
      "Selimut menghalang bekalan oksigen kepada api",
      "Selimut membekalkan karbon dioksida melalui pembakaran fabriknya",
      "Selimut menukarkan bahan api kepada bahan yang tidak boleh terbakar",
    ],
    answerIndex: 1,
    explanation: "Apabila bekalan oksigen terputus, salah satu syarat pembakaran tidak lagi dipenuhi lalu api terpadam.",
  },
  {
    id: "sci-f1-c7-bm-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah fungsi alat pemadam api karbon dioksida?",
    options: [
      "Memadam api dengan mengurangkan oksigen di sekitar api",
      "Menambah oksigen kepada api",
      "Menghasilkan air minuman",
      "Menghasilkan bahan api baharu",
    ],
    answerIndex: 0,
    explanation: "Karbon dioksida menyelimut api dan mengurangkan bekalan oksigen.",
  },
  {
    id: "sci-f1-c7-bm-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Pencemar manakah boleh menyebabkan hujan asid?",
    options: ["Sulfur dioksida", "Helium", "Neon", "Oksigen"],
    answerIndex: 0,
    explanation: "Sulfur dioksida boleh melarut dalam air hujan dan membentuk hujan asid.",
  },
  {
    id: "sci-f1-c7-bm-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kesan karbon monoksida kepada manusia?",
    options: [
      "Mengurangkan keupayaan darah membawa oksigen",
      "Membantu fotosintesis",
      "Menyuburkan tumbuhan",
      "Menyejukkan Bumi",
    ],
    answerIndex: 0,
    explanation: "Karbon monoksida berbahaya kerana mengganggu pengangkutan oksigen dalam darah.",
  },
  {
    id: "sci-f1-c7-bm-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kesan yang boleh berlaku jika kandungan karbon dioksida dalam atmosfera meningkat secara berlebihan?",
    options: [
      "Kesan rumah hijau menjadi lebih kuat dan suhu Bumi boleh meningkat",
      "Kesan rumah hijau menjadi lebih lemah dan suhu Bumi boleh menurun",
      "Kesan rumah hijau berkurang kerana karbon dioksida memantulkan semua haba ke angkasa",
      "Kesan rumah hijau tidak berubah kerana hanya oksigen mempengaruhi pengekalan haba",
    ],
    answerIndex: 0,
    explanation: "Peningkatan karbon dioksida boleh menguatkan kesan rumah hijau dan menyumbang kepada peningkatan suhu global.",
  },
  {
    id: "sci-f1-c7-bm-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Medium",
    question: "Langkah manakah paling sesuai untuk membantu mengurangkan pencemaran udara daripada kenderaan?",
    options: [
      "Menggalakkan penggunaan pengangkutan awam",
      "Menggalakkan setiap penumpang menggunakan kereta berasingan",
      "Membiarkan enjin kenderaan hidup ketika menunggu penumpang",
      "Menangguhkan penyelenggaraan enjin yang mengeluarkan asap berlebihan",
    ],
    answerIndex: 0,
    explanation: "Penggunaan pengangkutan awam boleh mengurangkan bilangan kenderaan di jalan raya dan seterusnya mengurangkan pelepasan bahan pencemar.",
  },
  {
    id: "sci-f1-c7-bm-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah oksigen penting untuk pembakaran?",
    options: [
      "Oksigen membolehkan bahan api terbakar dan menghasilkan haba",
      "Oksigen memadam semua api",
      "Oksigen menukar api kepada air",
      "Oksigen ialah bahan api utama",
    ],
    answerIndex: 0,
    explanation: "Pembakaran memerlukan oksigen. Tanpa oksigen, api tidak dapat terus menyala.",
  },
  {
    id: "sci-f1-c7-bm-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah jerebu yang teruk boleh menjejaskan kesihatan manusia?",
    options: [
      "Zarah dan bahan pencemar dalam udara boleh memasuki sistem respirasi",
      "Zarah jerebu memasuki badan hanya melalui makanan yang tercemar",
      "Zarah halus jerebu terhenti sepenuhnya di hidung dan hanya menjejaskan kulit",
      "Zarah jerebu hanya menjejaskan kesihatan apabila jarak penglihatan menjadi sifar",
    ],
    answerIndex: 0,
    explanation: "Zarah halus dan bahan pencemar boleh memasuki salur pernafasan dan menjejaskan sistem respirasi.",
  },
  {
    id: "sci-f1-c7-bm-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Penebangan hutan secara besar-besaran boleh meningkatkan kandungan karbon dioksida di atmosfera. Apakah sebab yang paling tepat?",
    options: [
      "Lebih sedikit tumbuhan tersedia untuk menyerap karbon dioksida semasa fotosintesis",
      "Lebih sedikit tumbuhan menyebabkan semua haiwan berhenti menjalankan respirasi",
      "Lebih sedikit tumbuhan menyebabkan kadar fotosintesis keseluruhan meningkat",
      "Lebih sedikit tumbuhan menyebabkan lebih banyak karbon dioksida diserap oleh tumbuhan yang tinggal",
    ],
    answerIndex: 0,
    explanation: "Apabila bilangan tumbuhan berkurang, kurang karbon dioksida diserap melalui fotosintesis.",
  },
  {
    id: "sci-f1-c7-bm-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Sebuah kawasan perumahan mengalami pencemaran udara akibat pembakaran sampah secara terbuka. Apakah tindakan paling sesuai?",
    options: [
      "Memindahkan pembakaran sampah ke kawasan lapang berhampiran rumah",
      "Menghentikan pembakaran terbuka dan mengurus sisa melalui kaedah pelupusan atau kitar semula yang sesuai",
      "Membakar sampah pada waktu malam supaya asap kurang kelihatan",
      "Membakar sampah dalam timbunan kecil setiap hari tanpa mengubah kaedah pelupusan",
    ],
    answerIndex: 1,
    explanation: "Menghentikan pembakaran terbuka dan menggunakan kaedah pengurusan sisa yang betul dapat mengurangkan pelepasan asap dan bahan pencemar.",
  },
  {
    id: "sci-f1-c7-bm-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 7",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah hujan asid merosakkan bangunan dan tumbuhan?",
    options: [
      "Sifat berasidnya menghakis bahan dan merosakkan tisu tumbuhan",
      "Ia mengandungi helium",
      "Ia meningkatkan oksigen kepada 78%",
      "Ia menukar semua tanah menjadi air",
    ],
    answerIndex: 0,
    explanation: "Hujan asid boleh menghakis bangunan dan merosakkan daun serta tanah.",
  },
];
