// AUTO-GENERATED by scripts/generate-content-stats.ts — do not edit by hand.
// Regenerated automatically by `npm run build`. See that script for why this
// exists (keeps the admin Reports server function out of the curriculum
// registry's SSR bundle weight).
export const CONTENT_STATS = {
  totalSubjects: 6,
  totalChapters: 260,
  publishedNotes: 201,
  publishedQuizzes: 153,
  publishedFlashcards: 167,
  publishedMindmaps: 241,
  missingContent: 111,
} as const;
