// AUTO-GENERATED by scripts/generate-content-stats.ts — do not edit by hand.
// Regenerated automatically by `npm run build`. See that script for why this
// exists (keeps the admin Reports server function out of the curriculum
// registry's SSR bundle weight).
export const CONTENT_STATS = {
  totalSubjects: 6,
  totalChapters: 261,
  publishedNotes: 200,
  publishedQuizzes: 152,
  publishedFlashcards: 166,
  publishedMindmaps: 242,
  missingContent: 113,
} as const;
