import type { PairedQuizSeed } from "../paired-quiz-bank";

const q = (
  bm: string,
  dlp: string,
  correct: PairedQuizSeed["correct"],
  distractors: PairedQuizSeed["distractors"],
  bmExplanation: string,
  dlpExplanation: string,
): PairedQuizSeed => ({
  question: [bm, dlp],
  correct,
  distractors,
  explanation: [bmExplanation, dlpExplanation],
});

export const mathF2C5PairedSeeds: readonly PairedQuizSeed[] = [
  // Objective 1 — Foundation: parts of circles (7)
  q(
    "Apakah nama garis lurus dari pusat bulatan ke lilitannya?",
    "What is the line segment from the centre of a circle to its circumference called?",
    ["Jejari", "Radius"],
    [
      ["Diameter", "Diameter"],
      ["Perentas", "Chord"],
      ["Lengkok", "Arc"],
    ],
    "Jejari menghubungkan pusat dengan satu titik pada lilitan.",
    "A radius joins the centre to a point on the circumference.",
  ),
  q(
    "Garis lurus yang melalui pusat dan menghubungkan dua titik pada lilitan ialah apa?",
    "What is a line segment through the centre joining two points on the circumference?",
    ["Diameter", "Diameter"],
    [
      ["Jejari", "Radius"],
      ["Lengkok", "Arc"],
      ["Sektor", "Sector"],
    ],
    "Diameter melalui pusat dan kedua-dua hujungnya berada pada lilitan.",
    "A diameter passes through the centre and has both endpoints on the circumference.",
  ),
  q(
    "Apakah perentas bulatan?",
    "What is a chord of a circle?",
    [
      "Garis lurus yang menghubungkan dua titik pada lilitan",
      "A line segment joining two points on the circumference",
    ],
    [
      ["Garis dari pusat ke lilitan", "A line from the centre to the circumference"],
      ["Jarak mengelilingi bulatan", "The distance around the circle"],
      ["Rantau antara dua jejari sahaja", "The region between two radii only"],
    ],
    "Perentas mempunyai kedua-dua titik hujung pada lilitan.",
    "A chord has both endpoints on the circumference.",
  ),
  q(
    "Bahagian lilitan antara dua titik disebut apa?",
    "What is the part of a circumference between two points called?",
    ["Lengkok", "Arc"],
    [
      ["Perentas", "Chord"],
      ["Jejari", "Radius"],
      ["Tembereng", "Segment"],
    ],
    "Lengkok ialah sebahagian daripada lilitan bulatan.",
    "An arc is a portion of a circle's circumference.",
  ),
  q(
    "Rantau yang dibatasi oleh dua jejari dan satu lengkok dinamakan apa?",
    "What is the region bounded by two radii and an arc called?",
    ["Sektor", "Sector"],
    [
      ["Tembereng", "Segment"],
      ["Perentas", "Chord"],
      ["Diameter", "Diameter"],
    ],
    "Dua jejari bersama lengkok membatasi sebuah sektor.",
    "Two radii and an arc bound a sector.",
  ),
  q(
    "Rantau yang dibatasi oleh satu perentas dan lengkoknya disebut apa?",
    "What is the region bounded by a chord and its arc called?",
    ["Tembereng", "Segment"],
    [
      ["Sektor", "Sector"],
      ["Jejari", "Radius"],
      ["Lilitan", "Circumference"],
    ],
    "Perentas dan lengkok yang sepadan membatasi tembereng.",
    "A chord and its corresponding arc bound a segment.",
  ),
  q(
    "Antara berikut, yang manakah perentas terpanjang dalam bulatan?",
    "Which is the longest chord in a circle?",
    ["Diameter", "Diameter"],
    [
      ["Jejari", "Radius"],
      ["Lengkok minor", "Minor arc"],
      ["Perentas yang tidak melalui pusat", "A chord not through the centre"],
    ],
    "Diameter melalui pusat dan merupakan perentas terpanjang.",
    "A diameter passes through the centre and is the longest chord.",
  ),

  // Radius and diameter (4)
  q(
    "Jejari sebuah bulatan ialah 9 cm. Cari diameternya.",
    "A circle has radius 9 cm. Find its diameter.",
    "18 cm",
    ["4.5 cm", "9 cm", "27 cm"],
    "Diameter = 2 × jejari = 2(9) = 18 cm.",
    "Diameter = 2 × radius = 2(9) = 18 cm.",
  ),
  q(
    "Diameter sebuah bulatan ialah 26 mm. Berapakah jejarinya?",
    "A circle has diameter 26 mm. What is its radius?",
    "13 mm",
    ["6.5 mm", "26 mm", "52 mm"],
    "Jejari = diameter ÷ 2 = 13 mm.",
    "Radius = diameter ÷ 2 = 13 mm.",
  ),
  q(
    "Jika diameter bertambah daripada 10 cm kepada 16 cm, berapakah pertambahan jejari?",
    "If the diameter increases from 10 cm to 16 cm, by how much does the radius increase?",
    "3 cm",
    ["2 cm", "6 cm", "13 cm"],
    "Jejari berubah daripada 5 cm kepada 8 cm, jadi bertambah 3 cm.",
    "The radius changes from 5 cm to 8 cm, an increase of 3 cm.",
  ),
  q(
    "Sebuah bulatan mempunyai diameter d. Formula manakah memberi jejarinya j?",
    "A circle has diameter d. Which formula gives its radius r?",
    "j = d/2",
    ["j = 2d", "j = d²", "j = πd"],
    "Jejari ialah separuh diameter, jadi j = d/2.",
    "The radius is half the diameter, so r = d/2.",
  ),

  // Chord symmetry and properties (5)
  q(
    "Jejari OP berserenjang dengan perentas AB di P. Apakah hubungan AP dengan PB?",
    "Radius OP is perpendicular to chord AB at P. What is the relationship between AP and PB?",
    "AP = PB",
    ["AP = 2PB", "AP < PB", "AP + PB = OP"],
    "Jejari yang berserenjang dengan perentas membahagi dua sama perentas itu.",
    "A radius perpendicular to a chord bisects that chord.",
  ),
  q(
    "Dua perentas sama panjang dalam bulatan yang sama menghasilkan apa?",
    "What do two equal chords in the same circle produce?",
    ["Lengkok yang sama panjang", "Equal arcs"],
    [
      ["Jejari yang berlainan", "Different radii"],
      ["Diameter yang berlainan", "Different diameters"],
      ["Pusat yang berlainan", "Different centres"],
    ],
    "Perentas yang sama panjang menghasilkan lengkok yang sama panjang.",
    "Equal chords produce equal arcs.",
  ),
  q(
    "Dua perentas berada pada jarak yang sama dari pusat. Apakah yang boleh disimpulkan?",
    "Two chords are the same distance from the centre. What can be concluded?",
    ["Kedua-dua perentas sama panjang", "The two chords are equal in length"],
    [
      ["Kedua-duanya diameter", "Both are diameters"],
      ["Kedua-duanya berserenjang", "Both are perpendicular"],
      ["Lengkoknya sentiasa major", "Their arcs are always major"],
    ],
    "Perentas yang sama jarak dari pusat adalah sama panjang.",
    "Chords equidistant from the centre are equal in length.",
  ),
  q(
    "Pembahagi dua serenjang bagi dua perentas bertemu di mana?",
    "Where do the perpendicular bisectors of two chords meet?",
    ["Pusat bulatan", "The centre of the circle"],
    [
      ["Pada satu hujung perentas", "At an endpoint of a chord"],
      ["Di luar bulatan", "Outside the circle"],
      ["Pada lengkok major", "On the major arc"],
    ],
    "Semua pembahagi dua serenjang perentas melalui pusat bulatan.",
    "Every perpendicular bisector of a chord passes through the circle's centre.",
  ),
  q(
    "Garis melalui pusat membahagi bulatan kepada dua bahagian sepadan. Garis itu mempunyai sifat apa?",
    "A line through the centre divides a circle into two matching halves. What property does the line have?",
    ["Paksi simetri", "Axis of symmetry"],
    [
      ["Lengkok minor", "Minor arc"],
      ["Perentas terpendek", "Shortest chord"],
      ["Tangen", "Tangent"],
    ],
    "Setiap diameter ialah paksi simetri bulatan.",
    "Every diameter is an axis of symmetry of a circle.",
  ),

  // Circumference (5)
  q(
    "Cari lilitan bulatan berjejari 7 cm. Gunakan π = 22/7.",
    "Find the circumference of a circle of radius 7 cm. Use π = 22/7.",
    "44 cm",
    ["22 cm", "77 cm", "154 cm"],
    "Lilitan = 2πj = 2(22/7)(7) = 44 cm.",
    "Circumference = 2πr = 2(22/7)(7) = 44 cm.",
  ),
  q(
    "Diameter bulatan ialah 10 cm. Cari lilitannya dalam sebutan π.",
    "A circle has diameter 10 cm. Find its circumference in terms of π.",
    "10π cm",
    ["5π cm", "20π cm", "100π cm"],
    "Lilitan = πd = π(10) = 10π cm.",
    "Circumference = πd = π(10) = 10π cm.",
  ),
  q(
    "Gunakan π = 3.142 untuk mencari lilitan bulatan berjejari 5 m.",
    "Use π = 3.142 to find the circumference of a circle of radius 5 m.",
    "31.42 m",
    ["15.71 m", "25.00 m", "78.55 m"],
    "Lilitan = 2(3.142)(5) = 31.42 m.",
    "Circumference = 2(3.142)(5) = 31.42 m.",
  ),
  q(
    "Formula manakah menghitung lilitan menggunakan jejari j?",
    "Which formula calculates circumference using radius r?",
    "2πj",
    ["πj", "πj²", "2πj²"],
    "Lilitan bulatan ialah 2πj.",
    "The circumference of a circle is 2πr.",
  ),
  q(
    "Sebuah roda berdiameter 14 cm membuat satu putaran lengkap. Berapa jauh roda bergerak? Gunakan π = 22/7.",
    "A wheel of diameter 14 cm makes one complete turn. How far does it travel? Use π = 22/7.",
    "44 cm",
    ["22 cm", "88 cm", "154 cm"],
    "Jarak satu putaran ialah lilitan: πd = (22/7)(14) = 44 cm.",
    "The distance for one turn is the circumference: πd = (22/7)(14) = 44 cm.",
  ),

  // Area (5)
  q(
    "Cari luas bulatan berjejari 7 cm. Gunakan π = 22/7.",
    "Find the area of a circle of radius 7 cm. Use π = 22/7.",
    "154 cm²",
    ["44 cm²", "77 cm²", "308 cm²"],
    "Luas = πj² = (22/7)(7²) = 154 cm².",
    "Area = πr² = (22/7)(7²) = 154 cm².",
  ),
  q(
    "Sebuah bulatan mempunyai jejari 4 cm. Nyatakan luasnya dalam sebutan π.",
    "A circle has radius 4 cm. State its area in terms of π.",
    "16π cm²",
    ["4π cm²", "8π cm²", "32π cm²"],
    "Luas = π(4²) = 16π cm².",
    "Area = π(4²) = 16π cm².",
  ),
  q(
    "Diameter sebuah bulatan ialah 12 m. Cari luasnya dalam sebutan π.",
    "A circle has diameter 12 m. Find its area in terms of π.",
    "36π m²",
    ["12π m²", "24π m²", "144π m²"],
    "Jejari = 6 m. Luas = π(6²) = 36π m².",
    "Radius = 6 m. Area = π(6²) = 36π m².",
  ),
  q(
    "Apakah unit yang sesuai bagi luas bulatan berjari-jari dalam sentimeter?",
    "What is the suitable unit for the area of a circle whose radius is in centimetres?",
    "cm²",
    ["cm", "cm³", "°"],
    "Luas menggunakan unit persegi, jadi unitnya cm².",
    "Area uses square units, so its unit is cm².",
  ),
  q(
    "Jika jejari bulatan digandakan, berapa kali ganda luasnya?",
    "If a circle's radius is doubled, by what factor does its area change?",
    ["4 kali ganda", "4 times"],
    [
      ["2 kali ganda", "2 times"],
      ["6 kali ganda", "6 times"],
      ["8 kali ganda", "8 times"],
    ],
    "Luas baharu = π(2j)² = 4πj², iaitu 4 kali ganda.",
    "New area = π(2r)² = 4πr², which is 4 times as large.",
  ),

  // Simple arcs (2)
  q(
    "Cari panjang lengkok 90° bagi bulatan berjejari 14 cm. Gunakan π = 22/7.",
    "Find the length of a 90° arc in a circle of radius 14 cm. Use π = 22/7.",
    "22 cm",
    ["11 cm", "44 cm", "88 cm"],
    "Lengkok = 90/360 × 2(22/7)(14) = 22 cm.",
    "Arc length = 90/360 × 2(22/7)(14) = 22 cm.",
  ),
  q(
    "Satu semibulatan mempunyai jejari 6 cm. Berapakah panjang lengkoknya dalam sebutan π?",
    "A semicircle has radius 6 cm. What is its arc length in terms of π?",
    "6π cm",
    ["3π cm", "12π cm", "36π cm"],
    "Lengkok semibulatan ialah separuh lilitan: 1/2(2π × 6) = 6π cm.",
    "A semicircle's arc is half the circumference: 1/2(2π × 6) = 6π cm.",
  ),

  // Simple sectors (2)
  q(
    "Cari luas sektor 90° bagi bulatan berjejari 8 cm dalam sebutan π.",
    "Find the area of a 90° sector in a circle of radius 8 cm, in terms of π.",
    "16π cm²",
    ["8π cm²", "32π cm²", "64π cm²"],
    "Luas sektor = 90/360 × π(8²) = 16π cm².",
    "Sector area = 90/360 × π(8²) = 16π cm².",
  ),
  q(
    "Sektor 180° membentuk berapa bahagian daripada sebuah bulatan?",
    "What fraction of a circle is a 180° sector?",
    "1/2",
    ["1/4", "1/3", "2/3"],
    "180°/360° = 1/2.",
    "180°/360° = 1/2.",
  ),

  // Objective 2 — Practice: chord and symmetry reasoning (5)
  q(
    "OP berserenjang dengan perentas AB di P. Jika AB = 18 cm, cari AP.",
    "OP is perpendicular to chord AB at P. If AB = 18 cm, find AP.",
    "9 cm",
    ["6 cm", "18 cm", "36 cm"],
    "Jejari serenjang membahagi dua perentas, jadi AP = 18/2 = 9 cm.",
    "A perpendicular radius bisects the chord, so AP = 18/2 = 9 cm.",
  ),
  q(
    "Perentas AB dan CD sama panjang. Jarak AB dari pusat ialah 6 cm. Berapakah jarak CD dari pusat?",
    "Chords AB and CD are equal. AB is 6 cm from the centre. How far is CD from the centre?",
    "6 cm",
    ["3 cm", "12 cm", "Tidak dapat ditentukan"],
    "Perentas sama panjang adalah sama jarak dari pusat.",
    "Equal chords are equidistant from the centre.",
  ),
  q(
    "Lengkok minor PQ sama panjang dengan lengkok minor RS dalam bulatan yang sama. Bandingkan perentas PQ dan RS.",
    "Minor arcs PQ and RS are equal in the same circle. Compare chords PQ and RS.",
    "PQ = RS",
    ["PQ > RS", "PQ < RS", "PQ = 2RS"],
    "Lengkok sama panjang menghasilkan perentas yang sama panjang.",
    "Equal arcs produce equal chords.",
  ),
  q(
    "Satu garis melalui pusat O dan titik tengah M bagi perentas AB. Apakah sudut antara OM dengan AB?",
    "A line passes through centre O and midpoint M of chord AB. What is the angle between OM and AB?",
    "90°",
    ["45°", "60°", "180°"],
    "Garis dari pusat yang membahagi dua perentas adalah berserenjang dengannya.",
    "A line from the centre that bisects a chord is perpendicular to it.",
  ),
  q(
    "Mengapakah dua pembahagi dua serenjang perentas mencukupi untuk mencari pusat bulatan?",
    "Why are the perpendicular bisectors of two chords sufficient to locate a circle's centre?",
    [
      "Kedua-duanya melalui pusat dan berpotongan di satu titik",
      "Both pass through the centre and intersect at one point",
    ],
    [
      ["Kedua-duanya sentiasa menjadi diameter yang sama", "Both are always the same diameter"],
      ["Perentas mesti sama panjang", "The chords must be equal"],
      ["Titik tengah perentas berada pada lilitan", "Chord midpoints lie on the circumference"],
    ],
    "Setiap pembahagi dua serenjang melalui pusat; titik persilangannya ialah pusat.",
    "Each perpendicular bisector passes through the centre; their intersection is the centre.",
  ),

  // Centre/radius/Pythagoras (4)
  q(
    "AB ialah perentas 16 cm. OP berserenjang dengan AB di P dan OP = 6 cm. Cari jejari OA.",
    "AB is a 16 cm chord. OP is perpendicular to AB at P and OP = 6 cm. Find radius OA.",
    "10 cm",
    ["8 cm", "14 cm", "22 cm"],
    "AP = 8 cm. Dalam segi tiga bersudut tegak, OA = √(8² + 6²) = 10 cm.",
    "AP = 8 cm. In the right triangle, OA = √(8² + 6²) = 10 cm.",
  ),
  q(
    "Jejari sebuah bulatan 13 cm. Sebuah perentas berjarak 5 cm dari pusat. Cari panjang perentas itu.",
    "A circle has radius 13 cm. A chord is 5 cm from the centre. Find the chord length.",
    "24 cm",
    ["8 cm", "12 cm", "18 cm"],
    "Separuh perentas = √(13² − 5²) = 12 cm. Panjang penuh = 24 cm.",
    "Half-chord = √(13² − 5²) = 12 cm. Full length = 24 cm.",
  ),
  q(
    "Perentas 30 cm terletak 8 cm dari pusat. Berapakah jejari bulatan?",
    "A 30 cm chord is 8 cm from the centre. What is the circle's radius?",
    "17 cm",
    ["13 cm", "19 cm", "23 cm"],
    "Separuh perentas = 15 cm. Jejari = √(15² + 8²) = 17 cm.",
    "Half-chord = 15 cm. Radius = √(15² + 8²) = 17 cm.",
  ),
  q(
    "Jejari bulatan ialah 10 cm dan perentasnya 12 cm. Cari jarak perentas dari pusat.",
    "A circle has radius 10 cm and a 12 cm chord. Find the chord's distance from the centre.",
    "8 cm",
    ["4 cm", "6 cm", "16 cm"],
    "Separuh perentas = 6 cm. Jarak = √(10² − 6²) = 8 cm.",
    "Half-chord = 6 cm. Distance = √(10² − 6²) = 8 cm.",
  ),

  // Find radius/diameter from circumference or area (5)
  q(
    "Lilitan bulatan ialah 88 cm. Cari jejari. Gunakan π = 22/7.",
    "A circle's circumference is 88 cm. Find its radius. Use π = 22/7.",
    "14 cm",
    ["7 cm", "22 cm", "28 cm"],
    "j = C/(2π) = 88 ÷ (44/7) = 14 cm.",
    "r = C/(2π) = 88 ÷ (44/7) = 14 cm.",
  ),
  q(
    "Lilitan sebuah gelang ialah 31.42 cm. Cari diameternya. Gunakan π = 3.142.",
    "A ring has circumference 31.42 cm. Find its diameter. Use π = 3.142.",
    "10 cm",
    ["5 cm", "20 cm", "98.72 cm"],
    "d = C/π = 31.42/3.142 = 10 cm.",
    "d = C/π = 31.42/3.142 = 10 cm.",
  ),
  q(
    "Luas bulatan ialah 49π cm². Tentukan jejarinya.",
    "A circle has area 49π cm². Determine its radius.",
    "7 cm",
    ["3.5 cm", "14 cm", "49 cm"],
    "πj² = 49π, jadi j² = 49 dan j = 7 cm.",
    "πr² = 49π, so r² = 49 and r = 7 cm.",
  ),
  q(
    "Luas bulatan ialah 616 cm². Cari diameternya. Gunakan π = 22/7.",
    "A circle has area 616 cm². Find its diameter. Use π = 22/7.",
    "28 cm",
    ["14 cm", "22 cm", "44 cm"],
    "j² = 616 ÷ (22/7) = 196, jadi j = 14 cm dan d = 28 cm.",
    "r² = 616 ÷ (22/7) = 196, so r = 14 cm and d = 28 cm.",
  ),
  q(
    "Luas sebuah bulatan ialah 25π m². Berapakah lilitannya dalam sebutan π?",
    "A circle has area 25π m². What is its circumference in terms of π?",
    "10π m",
    ["5π m", "25π m", "50π m"],
    "Jejari = √25 = 5 m. Lilitan = 2π(5) = 10π m.",
    "Radius = √25 = 5 m. Circumference = 2π(5) = 10π m.",
  ),

  // Circumference/area applications (5)
  q(
    "Sebuah taman bulat berdiameter 28 m hendak dipagar. Cari panjang pagar. Gunakan π = 22/7.",
    "A circular garden of diameter 28 m is to be fenced. Find the fence length. Use π = 22/7.",
    "88 m",
    ["44 m", "176 m", "616 m"],
    "Panjang pagar = lilitan = πd = (22/7)(28) = 88 m.",
    "Fence length = circumference = πd = (22/7)(28) = 88 m.",
  ),
  q(
    "Sebuah alas bulat berjejari 12 cm dipotong lubang segi empat sama bersisi 6 cm di tengahnya. Cari luas bahan yang tinggal dalam sebutan π.",
    "A circular mat of radius 12 cm has a central square hole of side 6 cm cut from it. Find the remaining material area in terms of π.",
    "144π − 36 cm²",
    ["144π − 6 cm²", "72π − 36 cm²", "144π + 36 cm²"],
    "Luas bulatan = 144π cm² dan luas lubang = 36 cm². Baki = 144π − 36 cm².",
    "Circle area = 144π cm² and hole area = 36 cm². Remainder = 144π − 36 cm².",
  ),
  q(
    "Roda berdiameter 70 cm berputar 10 kali. Berapa jarak dilalui? Gunakan π = 22/7.",
    "A wheel of diameter 70 cm turns 10 times. What distance does it travel? Use π = 22/7.",
    "2200 cm",
    ["220 cm", "700 cm", "1540 cm"],
    "Satu putaran = (22/7)(70) = 220 cm. Sepuluh putaran = 2200 cm.",
    "One turn = (22/7)(70) = 220 cm. Ten turns = 2200 cm.",
  ),
  q(
    "Kos menutup bulatan berjejari 5 m ialah RM4 bagi setiap m². Nyatakan jumlah kos dalam sebutan π.",
    "Covering a circle of radius 5 m costs RM4 per m². State the total cost in terms of π.",
    "RM100π",
    ["RM20π", "RM40π", "RM400π"],
    "Luas = 25π m². Kos = 4(25π) = RM100π.",
    "Area = 25π m². Cost = 4(25π) = RM100π.",
  ),
  q(
    "Dua bulatan mempunyai jejari 3 cm dan 6 cm. Apakah nisbah luas bulatan kecil kepada besar?",
    "Two circles have radii 3 cm and 6 cm. What is the ratio of the smaller area to the larger area?",
    "1:4",
    ["1:2", "1:3", "1:8"],
    "Nisbah luas = 3²:6² = 9:36 = 1:4.",
    "Area ratio = 3²:6² = 9:36 = 1:4.",
  ),

  // Arc length (5)
  q(
    "Hujung jarum minit sepanjang 21 cm bergerak dari nombor 12 ke nombor 2. Cari jarak yang dilalui hujung jarum. Gunakan π = 22/7.",
    "The tip of a 21 cm minute hand moves from 12 to 2. Find the distance travelled by the tip. Use π = 22/7.",
    "22 cm",
    ["11 cm", "44 cm", "66 cm"],
    "Lengkok = 60/360 × 2(22/7)(21) = 22 cm.",
    "Arc length = 60/360 × 2(22/7)(21) = 22 cm.",
  ),
  q(
    "Sebuah bulatan berdiameter 20 cm mempunyai lengkok 72°. Nyatakan panjang lengkok dalam sebutan π.",
    "A circle of diameter 20 cm has a 72° arc. State its length in terms of π.",
    "4π cm",
    ["2π cm", "8π cm", "20π cm"],
    "Lengkok = 72/360 × π(20) = 4π cm.",
    "Arc length = 72/360 × π(20) = 4π cm.",
  ),
  q(
    "Lengkok major yang sepadan dengan sudut pusat 240° berada dalam bulatan berjejari 9 cm. Cari panjangnya dalam sebutan π.",
    "A major arc subtended by a 240° central angle lies in a circle of radius 9 cm. Find its length in terms of π.",
    "12π cm",
    ["6π cm", "18π cm", "24π cm"],
    "Lengkok = 240/360 × 2π(9) = 12π cm.",
    "Arc length = 240/360 × 2π(9) = 12π cm.",
  ),
  q(
    "Dua lengkok dalam bulatan yang sama mempunyai sudut pusat 45° dan 135°. Apakah nisbah panjangnya?",
    "Two arcs in the same circle have central angles 45° and 135°. What is the ratio of their lengths?",
    "1:3",
    ["1:2", "2:3", "3:4"],
    "Dalam bulatan sama, nisbah panjang lengkok = 45:135 = 1:3.",
    "In the same circle, arc-length ratio = 45:135 = 1:3.",
  ),
  q(
    "Cari perimeter sebuah sektor 90° berjejari 14 cm. Gunakan π = 22/7.",
    "Find the perimeter of a 90° sector of radius 14 cm. Use π = 22/7.",
    "50 cm",
    ["22 cm", "36 cm", "72 cm"],
    "Panjang lengkok = 22 cm. Perimeter sektor = 22 + 14 + 14 = 50 cm.",
    "Arc length = 22 cm. Sector perimeter = 22 + 14 + 14 = 50 cm.",
  ),

  // Sector area (4)
  q(
    "Sektor 120° berjejari 6 cm dicat pada kadar RM2 bagi setiap cm². Nyatakan kos mengecat dalam sebutan π.",
    "A 120° sector of radius 6 cm is painted at RM2 per cm². State the painting cost in terms of π.",
    "RM24π",
    ["RM12π", "RM36π", "RM72π"],
    "Luas sektor = 120/360 × π(6²) = 12π cm². Kos = 2(12π) = RM24π.",
    "Sector area = 120/360 × π(6²) = 12π cm². Cost = 2(12π) = RM24π.",
  ),
  q(
    "Daripada bulatan berjejari 8 cm, sektor 45° diwarnakan. Cari luas bahagian yang tidak diwarnakan dalam sebutan π.",
    "A 45° sector is coloured in a circle of radius 8 cm. Find the uncoloured area in terms of π.",
    "56π cm²",
    ["8π cm²", "32π cm²", "64π cm²"],
    "Luas bulatan = 64π dan sektor = 45/360 × 64π = 8π. Baki = 56π cm².",
    "Circle area = 64π and sector area = 45/360 × 64π = 8π. Remainder = 56π cm².",
  ),
  q(
    "Luas bulatan ialah 154 cm². Cari luas sektor 90°. Gunakan π = 22/7.",
    "A circle's area is 154 cm². Find the area of a 90° sector. Use π = 22/7.",
    "38.5 cm²",
    ["22 cm²", "44 cm²", "77 cm²"],
    "Sektor 90° ialah 1/4 bulatan: 154/4 = 38.5 cm².",
    "A 90° sector is 1/4 of the circle: 154/4 = 38.5 cm².",
  ),
  q(
    "Dua sektor dalam bulatan sama bersudut 80° dan 120°. Apakah nisbah luasnya?",
    "Two sectors in the same circle have angles 80° and 120°. What is their area ratio?",
    "2:3",
    ["1:2", "3:4", "4:5"],
    "Dalam bulatan sama, nisbah luas sektor = 80:120 = 2:3.",
    "In the same circle, sector-area ratio = 80:120 = 2:3.",
  ),

  // Compound areas (2)
  q(
    "Sebuah segi empat sama bersisi 14 cm mengandungi bulatan terterap. Cari luas di luar bulatan tetapi di dalam segi empat sama. Gunakan π = 22/7.",
    "A square of side 14 cm contains an inscribed circle. Find the area outside the circle but inside the square. Use π = 22/7.",
    "42 cm²",
    ["14 cm²", "154 cm²", "196 cm²"],
    "Luas segi empat sama = 196. Bulatan berjari-jari 7 cm berluas 154. Beza = 42 cm².",
    "Square area = 196. The radius-7 circle has area 154. Difference = 42 cm².",
  ),
  q(
    "Sebuah bentuk terdiri daripada segi empat tepat 12 cm × 7 cm dan sebuah semibulatan berdiameter 12 cm pada satu hujung. Cari luas dalam sebutan π.",
    "A shape consists of a 12 cm × 7 cm rectangle and a semicircle of diameter 12 cm at one end. Find its area in terms of π.",
    "84 + 18π cm²",
    ["84 + 36π cm²", "42 + 18π cm²", "84 + 72π cm²"],
    "Luas segi empat tepat = 84. Jejari semibulatan = 6; luasnya = 1/2π(6²) = 18π.",
    "Rectangle area = 84. Semicircle radius = 6; its area is 1/2π(6²) = 18π.",
  ),

  // Objective 3 — Challenge: chord/Pythagoras (5)
  q(
    "AB ialah perentas 24 cm dalam bulatan berpusat O. OP berserenjang dengan AB dan OP = 5 cm. Cari diameter bulatan.",
    "AB is a 24 cm chord in a circle with centre O. OP is perpendicular to AB and OP = 5 cm. Find the diameter.",
    "26 cm",
    ["13 cm", "24 cm", "34 cm"],
    "AP = 12 cm. Jejari OA = √(12² + 5²) = 13 cm, jadi diameter = 26 cm.",
    "AP = 12 cm. Radius OA = √(12² + 5²) = 13 cm, so diameter = 26 cm.",
  ),
  q(
    "Dua perentas selari panjangnya 16 cm dan 12 cm dalam bulatan berjejari 10 cm. Cari beza jarak mereka dari pusat.",
    "Two parallel chords have lengths 16 cm and 12 cm in a circle of radius 10 cm. Find the difference in their distances from the centre.",
    "2 cm",
    ["1 cm", "4 cm", "6 cm"],
    "Jarak ialah √(10² − 8²) = 6 cm dan √(10² − 6²) = 8 cm. Beza = 2 cm.",
    "The distances are √(10² − 8²) = 6 cm and √(10² − 6²) = 8 cm. Difference = 2 cm.",
  ),
  q(
    "Perentas AB panjangnya 40 cm dan jaraknya dari pusat 9 cm. Perentas CD sama panjang. Jika OM dan ON serenjang dengan AB dan CD, cari OM + ON.",
    "Chord AB is 40 cm long and 9 cm from the centre. Chord CD is equal to it. If OM and ON are perpendicular to AB and CD, find OM + ON.",
    "18 cm",
    ["9 cm", "20 cm", "40 cm"],
    "Perentas sama panjang sama jarak dari pusat, jadi OM = ON = 9 cm. Jumlah = 18 cm.",
    "Equal chords are equidistant from the centre, so OM = ON = 9 cm. Sum = 18 cm.",
  ),
  q(
    "Sebuah perentas 48 cm berada 7 cm dari pusat. Cari luas bulatan dalam sebutan π.",
    "A 48 cm chord is 7 cm from the centre. Find the circle's area in terms of π.",
    "625π cm²",
    ["49π cm²", "576π cm²", "1201π cm²"],
    "Separuh perentas = 24 cm. Jejari = √(24² + 7²) = 25 cm. Luas = 625π cm².",
    "Half-chord = 24 cm. Radius = √(24² + 7²) = 25 cm. Area = 625π cm².",
  ),
  q(
    "Dalam bulatan berjari-jari 17 cm, satu perentas berjarak 15 cm dari pusat. Perentas kedua 14 cm panjang. Perentas manakah lebih dekat kepada pusat dan berapa jaraknya?",
    "In a circle of radius 17 cm, one chord is 15 cm from the centre. A second chord is 14 cm long. Which chord is nearer the centre and what is its distance?",
    ["Perentas pertama, 15 cm", "The first chord, 15 cm"],
    [
      ["Perentas kedua, 16 cm", "The second chord, 16 cm"],
      ["Perentas pertama, 8 cm", "The first chord, 8 cm"],
      ["Perentas kedua, 14 cm", "The second chord, 14 cm"],
    ],
    "Jarak perentas kedua = √(17² − 7²) = √240 ≈ 15.49 cm. Maka perentas pertama pada 15 cm lebih dekat.",
    "The second chord's distance is √(17² − 7²) = √240 ≈ 15.49 cm. Therefore the first chord at 15 cm is nearer.",
  ),

  // Circumference ↔ radius ↔ area (5)
  q(
    "Lilitan sebuah bulatan ialah 62.84 cm. Cari luasnya. Gunakan π = 3.142.",
    "A circle has circumference 62.84 cm. Find its area. Use π = 3.142.",
    "314.2 cm²",
    ["62.84 cm²", "125.68 cm²", "628.4 cm²"],
    "Jejari = 62.84 ÷ (2 × 3.142) = 10 cm. Luas = 3.142(10²) = 314.2 cm².",
    "Radius = 62.84 ÷ (2 × 3.142) = 10 cm. Area = 3.142(10²) = 314.2 cm².",
  ),
  q(
    "Luas bulatan ialah 81π cm². Cari lilitan dalam sebutan π.",
    "A circle has area 81π cm². Find its circumference in terms of π.",
    "18π cm",
    ["9π cm", "81π cm", "162π cm"],
    "Jejari = 9 cm. Lilitan = 2π(9) = 18π cm.",
    "Radius = 9 cm. Circumference = 2π(9) = 18π cm.",
  ),
  q(
    "Dua bulatan mempunyai lilitan dalam nisbah 2:5. Apakah nisbah luasnya?",
    "Two circles have circumferences in ratio 2:5. What is their area ratio?",
    "4:25",
    ["2:5", "4:10", "8:125"],
    "Nisbah lilitan sama dengan nisbah jejari. Nisbah luas ialah kuasa dua: 2²:5² = 4:25.",
    "Circumference ratio equals radius ratio. Area ratio is its square: 2²:5² = 4:25.",
  ),
  q(
    "Jejari bulatan A ialah 3 cm lebih besar daripada B. Jika lilitan A melebihi B sebanyak 6π cm, sahkan perbezaan jejari.",
    "Circle A's radius is 3 cm larger than B's. If A's circumference exceeds B's by 6π cm, verify the radius difference.",
    "3 cm",
    ["1.5 cm", "6 cm", "9 cm"],
    "Beza lilitan = 2π(rA − rB) = 6π, jadi beza jejari = 3 cm.",
    "Circumference difference = 2π(rA − rB) = 6π, so the radius difference is 3 cm.",
  ),
  q(
    "Diameter sebuah bulatan ditambah 50%. Berapa peratus luasnya bertambah?",
    "A circle's diameter is increased by 50%. By what percentage does its area increase?",
    "125%",
    ["50%", "100%", "150%"],
    "Jejari juga menjadi 1.5 kali. Luas menjadi 1.5² = 2.25 kali, iaitu pertambahan 125%.",
    "The radius also becomes 1.5 times. Area becomes 1.5² = 2.25 times, an increase of 125%.",
  ),

  // Arc/angle/radius reverse problems (5)
  q(
    "Panjang lengkok ialah 11 cm dalam bulatan berjejari 7 cm. Cari sudut pusat. Gunakan π = 22/7.",
    "An arc is 11 cm long in a circle of radius 7 cm. Find its central angle. Use π = 22/7.",
    "90°",
    ["45°", "60°", "180°"],
    "Lilitan = 44 cm. Pecahan lengkok = 11/44 = 1/4, jadi sudut = 90°.",
    "Circumference = 44 cm. Arc fraction = 11/44 = 1/4, so angle = 90°.",
  ),
  q(
    "Lengkok 60° mempunyai panjang 8π cm. Cari jejari bulatan.",
    "A 60° arc has length 8π cm. Find the circle's radius.",
    "24 cm",
    ["8 cm", "12 cm", "48 cm"],
    "8π = 60/360 × 2πr = πr/3. Maka r = 24 cm.",
    "8π = 60/360 × 2πr = πr/3. Thus r = 24 cm.",
  ),
  q(
    "Lengkok major sebuah bulatan ialah 5 kali lengkok minornya. Cari sudut pusat lengkok minor.",
    "A circle's major arc is 5 times its minor arc. Find the minor arc's central angle.",
    "60°",
    ["30°", "72°", "120°"],
    "Jika sudut minor = x, sudut major = 5x. 6x = 360°, jadi x = 60°.",
    "If minor angle = x, major angle = 5x. Then 6x = 360°, so x = 60°.",
  ),
  q(
    "Panjang lengkok 144° ialah 20π cm. Cari diameter bulatan.",
    "A 144° arc is 20π cm long. Find the circle's diameter.",
    "50 cm",
    ["25 cm", "40 cm", "100 cm"],
    "20π = 144/360 × πd = 0.4πd. Maka d = 50 cm.",
    "20π = 144/360 × πd = 0.4πd. Thus d = 50 cm.",
  ),
  q(
    "Dua lengkok dalam bulatan sama berjumlah 360° dan panjangnya dalam nisbah 2:7. Cari sudut lengkok major.",
    "Two arcs of the same circle total 360° and their lengths are in ratio 2:7. Find the major arc's angle.",
    "280°",
    ["80°", "240°", "300°"],
    "Jumlah 9 bahagian = 360°, jadi satu bahagian 40°. Lengkok major = 7(40°) = 280°.",
    "Nine parts total 360°, so one part is 40°. Major arc = 7(40°) = 280°.",
  ),

  // Sector area/angle/radius reverse problems (5)
  q(
    "Luas sektor 90° ialah 38.5 cm². Cari jejari. Gunakan π = 22/7.",
    "A 90° sector has area 38.5 cm². Find the radius. Use π = 22/7.",
    "7 cm",
    ["3.5 cm", "11 cm", "14 cm"],
    "Luas bulatan penuh = 4(38.5) = 154 cm². Maka j² = 49 dan j = 7 cm.",
    "Full circle area = 4(38.5) = 154 cm². Thus r² = 49 and r = 7 cm.",
  ),
  q(
    "Sektor berjejari 12 cm mempunyai luas 48π cm². Cari sudut pusatnya.",
    "A sector of radius 12 cm has area 48π cm². Find its central angle.",
    "120°",
    ["60°", "90°", "240°"],
    "48π/(144π) = 1/3, jadi sudut = 1/3(360°) = 120°.",
    "48π/(144π) = 1/3, so angle = 1/3(360°) = 120°.",
  ),
  q(
    "Luas sektor major ialah tiga kali luas sektor minor. Cari sudut sektor minor.",
    "A major sector's area is three times the minor sector's area. Find the minor sector's angle.",
    "90°",
    ["45°", "120°", "270°"],
    "Sudut major:minor = 3:1. Empat bahagian = 360°, jadi minor = 90°.",
    "Major:minor angle ratio = 3:1. Four parts = 360°, so minor = 90°.",
  ),
  q(
    "Sektor 40° mempunyai luas 10π cm². Cari jejari bulatan.",
    "A 40° sector has area 10π cm². Find the circle's radius.",
    "3√10 cm",
    ["3 cm", "5√2 cm", "10 cm"],
    "10π = 40/360 × πr² = πr²/9. Maka r² = 90 dan r = 3√10 cm.",
    "10π = 40/360 × πr² = πr²/9. Thus r² = 90 and r = 3√10 cm.",
  ),
  q(
    "Sektor A dan B mempunyai luas sama. Jejari A ialah 6 cm dengan sudut 120°, manakala jejari B ialah 12 cm. Cari sudut B.",
    "Sectors A and B have equal areas. A has radius 6 cm and angle 120°, while B has radius 12 cm. Find B's angle.",
    "30°",
    ["15°", "60°", "90°"],
    "120(6²) = θ(12²). Maka θ = 120 × 36/144 = 30°.",
    "120(6²) = θ(12²). Thus θ = 120 × 36/144 = 30°.",
  ),

  // Composite/shaded-area problems (5)
  q(
    "Sebuah gelang dibentuk oleh dua bulatan sepusat berjejari 10 cm dan 6 cm. Cari luas gelang dalam sebutan π.",
    "An annulus is formed by concentric circles of radii 10 cm and 6 cm. Find its area in terms of π.",
    "64π cm²",
    ["16π cm²", "40π cm²", "136π cm²"],
    "Luas gelang = π(10² − 6²) = π(100 − 36) = 64π cm².",
    "Annulus area = π(10² − 6²) = π(100 − 36) = 64π cm².",
  ),
  q(
    "Sebuah segi empat sama bersisi 20 cm mempunyai empat suku bulatan berjejari 10 cm, satu di setiap bucu. Cari luas di luar keempat-empat suku bulatan dalam sebutan π.",
    "A square of side 20 cm has four quarter-circles of radius 10 cm, one at each corner. Find the area outside the four quarters in terms of π.",
    "400 − 100π cm²",
    ["400 − 25π cm²", "400 − 200π cm²", "100π − 400 cm²"],
    "Empat suku bulatan membentuk satu bulatan berjari-jari 10 cm. Luas baki = 400 − 100π.",
    "Four quarter-circles form one radius-10 circle. Remaining area = 400 − 100π.",
  ),
  q(
    "Sektor 90° berjejari 14 cm mengandungi segi tiga bersudut tegak yang dibentuk oleh dua jejarinya. Cari luas sektor di luar segi tiga. Gunakan π = 22/7.",
    "A 90° sector of radius 14 cm contains the right triangle formed by its two radii. Find the sector area outside the triangle. Use π = 22/7.",
    "56 cm²",
    ["42 cm²", "98 cm²", "154 cm²"],
    "Luas sektor = 154 cm². Luas segi tiga = 1/2(14)(14) = 98 cm². Beza = 56 cm².",
    "Sector area = 154 cm². Triangle area = 1/2(14)(14) = 98 cm². Difference = 56 cm².",
  ),
  q(
    "Sebuah bentuk kapsul terdiri daripada segi empat tepat 18 cm × 8 cm dan dua semibulatan berdiameter 8 cm. Cari luas dalam sebutan π.",
    "A capsule consists of an 18 cm × 8 cm rectangle and two semicircles of diameter 8 cm. Find its area in terms of π.",
    "144 + 16π cm²",
    ["144 + 8π cm²", "72 + 16π cm²", "144 + 64π cm²"],
    "Dua semibulatan membentuk bulatan berjari-jari 4 cm. Jumlah luas = 18(8) + π(4²) = 144 + 16π.",
    "Two semicircles form a radius-4 circle. Total area = 18(8) + π(4²) = 144 + 16π.",
  ),
  q(
    "Daripada bulatan berjejari 12 cm, sektor 60° dipotong. Cari luas bahagian yang tinggal dalam sebutan π.",
    "A 60° sector is cut from a circle of radius 12 cm. Find the remaining area in terms of π.",
    "120π cm²",
    ["24π cm²", "72π cm²", "144π cm²"],
    "Luas bulatan = 144π. Sektor = 60/360(144π) = 24π. Baki = 120π cm².",
    "Circle area = 144π. Sector = 60/360(144π) = 24π. Remainder = 120π cm².",
  ),

  // Real-world circle problems (5)
  q(
    "Tayar berdiameter 0.7 m bergerak 1.1 km. Anggarkan bilangan putaran lengkap. Gunakan π = 22/7.",
    "A tyre of diameter 0.7 m travels 1.1 km. Estimate the number of complete rotations. Use π = 22/7.",
    "500",
    ["50", "250", "700"],
    "Lilitan = (22/7)(0.7) = 2.2 m. Jarak 1100 m, jadi putaran = 1100/2.2 = 500.",
    "Circumference = (22/7)(0.7) = 2.2 m. Distance is 1100 m, so rotations = 1100/2.2 = 500.",
  ),
  q(
    "Sebuah trek bulat mempunyai lilitan 314.2 m. Seorang pelari melengkapkan 5 pusingan. Cari jumlah jarak.",
    "A circular track has circumference 314.2 m. A runner completes 5 laps. Find the total distance.",
    "1571 m",
    ["628.4 m", "942.6 m", "3142 m"],
    "Jumlah jarak = 5 × 314.2 = 1571 m.",
    "Total distance = 5 × 314.2 = 1571 m.",
  ),
  q(
    "Sebuah penyiram meliputi sektor 150° berjejari 6 m. Cari kawasan disiram dalam sebutan π.",
    "A sprinkler covers a 150° sector of radius 6 m. Find the watered area in terms of π.",
    "15π m²",
    ["6π m²", "21π m²", "36π m²"],
    "Luas = 150/360 × π(6²) = 15π m².",
    "Area = 150/360 × π(6²) = 15π m².",
  ),
  q(
    "Sebuah meja bulat berjejari 0.7 m memerlukan pita di tepi dan kain pada permukaan. Cari panjang pita dan luas kain. Gunakan π = 22/7.",
    "A circular table of radius 0.7 m needs trim around its edge and cloth on its top. Find the trim length and cloth area. Use π = 22/7.",
    ["4.4 m dan 1.54 m²", "4.4 m and 1.54 m²"],
    [
      ["2.2 m dan 1.54 m²", "2.2 m and 1.54 m²"],
      ["4.4 m dan 3.08 m²", "4.4 m and 3.08 m²"],
      ["1.4 m dan 4.4 m²", "1.4 m and 4.4 m²"],
    ],
    "Lilitan = 2(22/7)(0.7) = 4.4 m; luas = (22/7)(0.7²) = 1.54 m².",
    "Circumference = 2(22/7)(0.7) = 4.4 m; area = (22/7)(0.7²) = 1.54 m².",
  ),
  q(
    "Pizza berdiameter 28 cm dipotong kepada 8 sektor sama. Cari luas satu keping. Gunakan π = 22/7.",
    "A pizza of diameter 28 cm is cut into 8 equal sectors. Find the area of one slice. Use π = 22/7.",
    "77 cm²",
    ["44 cm²", "88 cm²", "154 cm²"],
    "Jejari = 14 cm. Luas pizza = 616 cm²; satu daripada 8 bahagian = 77 cm².",
    "Radius = 14 cm. Pizza area = 616 cm²; one of 8 equal parts is 77 cm².",
  ),
];
