import type { QuizQuestion } from "@/data/content";

export const scienceF2C5QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c5-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is the boiling point of pure water?",
    options: ["0°C", "50°C", "100°C", "212°C"],
    answerIndex: 2,
    explanation: "The boiling point of pure water is 100°C.",
  },
  {
    id: "sci-f2-c5-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is the density of pure water?",
    options: ["0.5 g cm⁻³", "1 g cm⁻³", "2 g cm⁻³", "10 g cm⁻³"],
    answerIndex: 1,
    explanation: "The density of pure water is 1 g cm⁻³.",
  },
  {
    id: "sci-f2-c5-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What causes surface tension in water?",
    options: ["Adhesive force", "Cohesive force between water molecules", "Gravity", "Capillary action"],
    answerIndex: 1,
    explanation: "Surface tension is a result of cohesive force between water molecules at the surface.",
  },
  {
    id: "sci-f2-c5-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is the chemical formula of water?",
    options: ["HO₂", "H₂O", "H₂O₂", "HO"],
    answerIndex: 1,
    explanation: "A water molecule is made up of two hydrogen atoms and one oxygen atom, giving the formula H₂O.",
  },
  {
    id: "sci-f2-c5-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "During electrolysis of water, which gas is produced at the anode?",
    options: ["Hydrogen", "Oxygen", "Carbon dioxide", "Nitrogen"],
    answerIndex: 1,
    explanation: "Oxygen gas is produced at the anode, while hydrogen gas is produced at the cathode.",
  },
  {
    id: "sci-f2-c5-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is a solute?",
    options: [
      "A liquid that dissolves a substance",
      "A substance that can dissolve in a liquid",
      "A mixture of solute and solvent",
      "A type of colloid",
    ],
    answerIndex: 1,
    explanation: "Solute is a substance that can dissolve in a liquid, while solvent is a liquid that dissolves a substance.",
  },
  {
    id: "sci-f2-c5-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is a saturated solution?",
    options: [
      "A solution with very little solute",
      "A solution that can still dissolve more solute",
      "A solution containing excess solute that forms a precipitate and cannot dissolve any more solute",
      "A solution made only with organic solvents",
    ],
    answerIndex: 2,
    explanation: "A saturated solution contains an excess amount of solute that forms a precipitate, and it cannot dissolve any more solute.",
  },
  {
    id: "sci-f2-c5-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What happens when light is shone through a suspension?",
    options: [
      "Light passes through easily",
      "Light is blocked because the particles are too large",
      "Light changes colour",
      "Light has no effect on suspensions",
    ],
    answerIndex: 1,
    explanation: "The size of particles in a suspension is large enough to prevent light from passing through.",
  },
  {
    id: "sci-f2-c5-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Why is water called a universal solvent?",
    options: [
      "It can dissolve only liquids",
      "It can dissolve almost all substances — solids, liquids and gases",
      "It is only used in laboratories",
      "It cannot dissolve any substance",
    ],
    answerIndex: 1,
    explanation: "Water is known as a universal solvent due to its ability to dissolve almost all substances, whether solid, liquid or gas.",
  },
  {
    id: "sci-f2-c5-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Which of the following is a water purification method?",
    options: ["Photosynthesis", "Distillation", "Respiration", "Combustion"],
    answerIndex: 1,
    explanation: "Distillation is one of the water purification methods, along with filtration, boiling and chlorination.",
  },
  {
    id: "sci-f2-c5-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What allows water to rise from the roots to the leaves of a plant through capillary action?",
    options: [
      "Cohesive force only",
      "Adhesive force only",
      "Both cohesive force (between water molecules) and adhesive force (between water and xylem walls)",
      "Gravity only",
    ],
    answerIndex: 2,
    explanation: "Capillary action occurs due to cohesive force between water molecules AND adhesive force between water molecules and the cell walls of xylem.",
  },
  {
    id: "sci-f2-c5-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is the effect of adding salt to ice and to boiling water respectively?",
    options: [
      "Lowers the melting point of ice and lowers the boiling point of water",
      "Raises the melting point of ice and raises the boiling point of water",
      "Lowers the melting point of ice and raises the boiling point of water",
      "Has no effect on either melting or boiling point",
    ],
    answerIndex: 2,
    explanation: "Salt lowers the melting point of ice and increases the boiling point of water — these are opposite effects.",
  },
  {
    id: "sci-f2-c5-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "At what temperature does evaporation of water occur?",
    options: ["Only at 100°C", "Only at 0°C", "At any temperature, at the surface of water", "Only when boiling"],
    answerIndex: 2,
    explanation: "Evaporation is the process that happens at the surface of water and occurs at ANY temperature, not only at the boiling point.",
  },
  {
    id: "sci-f2-c5-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "How does increasing humidity affect the rate of evaporation?",
    options: [
      "It increases the rate of evaporation",
      "It decreases the rate of evaporation",
      "It has no effect",
      "It only affects condensation, not evaporation",
    ],
    answerIndex: 1,
    explanation: "Humid air already contains more water vapour, so it can hold fewer additional water molecules escaping from the surface, decreasing the rate of evaporation.",
  },
  {
    id: "sci-f2-c5-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Why does fine sugar dissolve faster than sugar cubes?",
    options: [
      "Fine sugar has a smaller total surface area",
      "Fine sugar has a larger total surface area exposed to the solvent",
      "Sugar cubes contain more water",
      "There is no difference in dissolving rate",
    ],
    answerIndex: 1,
    explanation: "The smaller the size of the solute, the bigger the total surface area exposed to the solvent, allowing it to dissolve faster.",
  },
  {
    id: "sci-f2-c5-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Which of the following best describes a colloid?",
    options: [
      "A clear mixture that does not scatter light",
      "A mixture that settles and forms a precipitate like a suspension",
      "A mixture intermediate between a solution and a suspension that neither forms a clear mixture nor a precipitate",
      "A type of organic solvent",
    ],
    answerIndex: 2,
    explanation: "A colloid is intermediate between a solution and a suspension — it does not form a clear mixture (like a solution) nor does it precipitate (like a suspension).",
  },
  {
    id: "sci-f2-c5-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Which of these is an example of an emulsion colloid?",
    options: ["Shaving cream", "Milk", "Salt water", "River water"],
    answerIndex: 1,
    explanation: "Milk and mayonnaise are examples of emulsion colloids; shaving cream is an example of a foam colloid.",
  },
  {
    id: "sci-f2-c5-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Which organic solvent is commonly used as a paint thinner?",
    options: ["Alcohol", "Acetone", "Turpentine", "Ether"],
    answerIndex: 2,
    explanation: "Turpentine is commonly used as a paint thinner and paint remover.",
  },
  {
    id: "sci-f2-c5-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is the correct order of the water purification methods that remove impurities, from least to most thorough?",
    options: [
      "Distillation → Boiling → Filtration",
      "Filtration (removes suspended particles only) → Boiling/Chlorination (kills microorganisms) → Distillation (removes everything)",
      "Chlorination → Filtration → Boiling",
      "All four methods remove the exact same impurities",
    ],
    answerIndex: 1,
    explanation: "Filtration only removes suspended particles; boiling and chlorination kill microorganisms but do not remove dissolved substances; distillation removes suspended particles, dissolved substances, AND kills microorganisms, making it the most thorough.",
  },
  {
    id: "sci-f2-c5-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "What is the function of alum during the coagulation stage of water treatment?",
    options: [
      "To kill microorganisms",
      "To make mud particles stick together and sink",
      "To prevent tooth decay",
      "To increase oxygen content",
    ],
    answerIndex: 1,
    explanation: "Alum is added during coagulation so that mud particles stick together and sink to the bottom of the tank.",
  },
  {
    id: "sci-f2-c5-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "A student collects gas during electrolysis of water and finds the volume ratio of gas in cylinder K to cylinder L is 1:2, where K relights a glowing splinter. What can be concluded?",
    options: [
      "K is hydrogen (1 part) and L is oxygen (2 parts)",
      "K is oxygen (1 part) and L is hydrogen (2 parts)",
      "Both K and L are oxygen",
      "The experiment is invalid since the ratio should be 1:1",
    ],
    answerIndex: 1,
    explanation: "A glowing splinter relights in oxygen gas. Since the volume ratio of hydrogen to oxygen is 2:1, oxygen (K) would be the smaller volume (1 part) and hydrogen (L) would be the larger volume (2 parts).",
  },
  {
    id: "sci-f2-c5-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Why is dilute hydrochloric acid added to distilled water before carrying out electrolysis to find the composition of water?",
    options: [
      "To change the chemical formula of water",
      "Pure water alone does not conduct electricity well; the acid provides ions to allow current to flow",
      "To remove hydrogen from the water",
      "To increase the boiling point of water",
    ],
    answerIndex: 1,
    explanation: "Distilled water is a poor conductor of electricity on its own; adding a few drops of dilute hydrochloric acid increases the ion concentration so that current can flow through the water during electrolysis.",
  },
  {
    id: "sci-f2-c5-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Aliya found that three spatulas of salt produced a saturated solution in 50 ml of water. If she heats the solution, what would most likely happen, and why?",
    options: [
      "Nothing happens because saturated solutions cannot change",
      "More salt may dissolve, because solubility generally increases with rising temperature",
      "The salt will turn into a precipitate immediately",
      "The water will turn into a suspension",
    ],
    answerIndex: 1,
    explanation: "Since the rate (and generally the extent) of solubility increases with temperature, heating a saturated solution can allow more solute to dissolve, making it no longer saturated at the higher temperature.",
  },
  {
    id: "sci-f2-c5-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "A mixture of water and chalk powder is tested with a torchlight and filtered. The light cannot pass through, and a residue remains on the filter paper. What type of mixture is this, and why?",
    options: [
      "A solution, because chalk fully dissolves in water",
      "A colloid, because it does not settle",
      "A suspension, because the chalk particles are undissolved and large enough to block light and leave a residue",
      "An organic solvent mixture",
    ],
    answerIndex: 2,
    explanation: "Chalk powder is insoluble in water, forming a suspension. The undissolved particles are large enough to block light and will be caught as residue during filtration.",
  },
  {
    id: "sci-f2-c5-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "A farmer wants to dry his harvested fish faster using natural evaporation. Based on the four factors affecting evaporation rate, which combination of conditions would dry the fish FASTEST?",
    options: [
      "High humidity, low temperature, small surface area, still air",
      "Low humidity, high temperature, large surface area, strong air movement",
      "High humidity, high temperature, small surface area, still air",
      "Low humidity, low temperature, large surface area, still air",
    ],
    answerIndex: 1,
    explanation: "The rate of evaporation is fastest with LOW humidity, HIGH surrounding temperature, LARGE exposed surface area, and FAST air movement — all four factors working together to maximise the rate.",
  },
  {
    id: "sci-f2-c5-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Why does the Dead Sea allow people to float more easily compared to a normal sea?",
    options: [
      "The Dead Sea has lower density due to high evaporation",
      "The Dead Sea has unusually high salt content, making the water denser and increasing natural buoyancy",
      "The Dead Sea contains organic solvents that increase buoyancy",
      "The Dead Sea is colder than normal seas, which increases buoyancy",
    ],
    answerIndex: 1,
    explanation: "Because the Dead Sea is completely surrounded by land, water entering it evaporates quickly, concentrating the salt content. This unusually high salt content increases the water's density, causing natural buoyancy.",
  },
  {
    id: "sci-f2-c5-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "K, L, M and N are stages in the water purification system: K = Coagulation, L = Chlorination, M = Sedimentation, N = Filtration. What is the correct sequence?",
    options: [
      "L → K → M → N",
      "N → K → M → L",
      "K → M → N → L",
      "M → N → K → L",
    ],
    answerIndex: 2,
    explanation: "The correct sequence is Coagulation (K) → Sedimentation (M) → Filtration (N) → Chlorination (L) — particles must first clump together (coagulation), then settle (sedimentation), then be filtered (filtration), before the water is disinfected (chlorination).",
  },
  {
    id: "sci-f2-c5-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Why does Singapore use the NEWater initiative instead of relying solely on importing or harvesting natural water sources?",
    options: [
      "Because NEWater is cheaper than rainwater",
      "Because Singapore has limited natural water supply, so recycling sewage into clean water through modern technology helps meet national water needs sustainably",
      "Because NEWater removes the need for any water purification",
      "Because Singapore has no rivers at all",
    ],
    answerIndex: 1,
    explanation: "Singapore has limited natural water sources, so it uses modern technology to recycle sewage water into clean drinking and industrial water (NEWater) as a sustainable alternative source of water supply.",
  },
  {
    id: "sci-f2-c5-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "A factory illegally discharges untreated chemical waste into a river. Which law in Malaysia is most directly relevant to enforcing penalties against this action?",
    options: [
      "Environmental Quality (Scheduled Wastes) Regulations 2005 / Industrial Effluent Regulations 2009",
      "Road Transport Act",
      "Food Act",
      "Animal Welfare Act",
    ],
    answerIndex: 0,
    explanation: "Malaysia enforces laws such as the Environmental Quality (Scheduled Wastes) Regulations 2005 and the Environmental Quality (Industrial Effluent) Regulations 2009 to ensure industrial waste is treated before being discharged into rivers.",
  },
  {
    id: "sci-f2-c5-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "dlp",
    question: "Vicki tested cloudy river water using four methods: Sample A (filtered), Sample B (boiled), Sample C (distilled), Sample D (added chlorine). Which sample would become PURE water, free of suspended particles, dissolved impurities, AND microorganisms?",
    options: ["Sample A", "Sample B", "Sample C", "Sample D"],
    answerIndex: 2,
    explanation: "Distillation (Sample C) is the only method that removes suspended particles and dissolved substances, AND kills microorganisms — producing the purest water among the four methods.",
  },
];
