import type { QuizQuestion } from "@/data/content";

export const scienceF2C5QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c5-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah takat didih air tulen?",
    options: ["0°C", "50°C", "100°C", "212°C"],
    answerIndex: 2,
    explanation: "Takat didih air tulen ialah 100°C.",
  },
  {
    id: "sci-f2-c5-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah ketumpatan air tulen?",
    options: ["0.5 g cm⁻³", "1 g cm⁻³", "2 g cm⁻³", "10 g cm⁻³"],
    answerIndex: 1,
    explanation: "Ketumpatan air tulen ialah 1 g cm⁻³.",
  },
  {
    id: "sci-f2-c5-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah yang menyebabkan tegangan permukaan air?",
    options: ["Daya lekatan", "Daya lekitan antara molekul air", "Graviti", "Tindakan kapilari"],
    answerIndex: 1,
    explanation: "Tegangan permukaan terhasil daripada daya lekitan antara molekul air pada permukaan.",
  },
  {
    id: "sci-f2-c5-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah formula kimia air?",
    options: ["HO₂", "H₂O", "H₂O₂", "HO"],
    answerIndex: 1,
    explanation: "Satu molekul air terdiri daripada dua atom hidrogen dan satu atom oksigen, menghasilkan formula H₂O.",
  },
  {
    id: "sci-f2-c5-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Semasa elektrolisis air, gas manakah yang dihasilkan di anod?",
    options: ["Hidrogen", "Oksigen", "Karbon dioksida", "Nitrogen"],
    answerIndex: 1,
    explanation: "Gas oksigen dihasilkan di anod, sementara gas hidrogen dihasilkan di katod.",
  },
  {
    id: "sci-f2-c5-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah maksud zat terlarut?",
    options: [
      "Cecair yang melarutkan sesuatu bahan",
      "Bahan yang boleh larut dalam cecair",
      "Campuran zat terlarut dan pelarut",
      "Sejenis koloid",
    ],
    answerIndex: 1,
    explanation: "Zat terlarut ialah bahan yang boleh larut dalam cecair, sementara pelarut ialah cecair yang melarutkan sesuatu bahan.",
  },
  {
    id: "sci-f2-c5-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah maksud larutan tepu?",
    options: [
      "Larutan dengan zat terlarut yang sangat sedikit",
      "Larutan yang masih boleh melarutkan lebih banyak zat terlarut",
      "Larutan yang mengandungi zat terlarut berlebihan yang membentuk mendakan dan tidak boleh melarutkan lebih lagi",
      "Larutan yang hanya dibuat menggunakan pelarut organik",
    ],
    answerIndex: 2,
    explanation: "Larutan tepu mengandungi zat terlarut berlebihan yang membentuk mendakan, dan ia tidak boleh melarutkan zat terlarut lagi.",
  },
  {
    id: "sci-f2-c5-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah yang berlaku apabila cahaya disenter melalui ampaian?",
    options: [
      "Cahaya tembus dengan mudah",
      "Cahaya terhalang kerana zarah terlalu besar",
      "Cahaya bertukar warna",
      "Cahaya tidak memberi kesan kepada ampaian",
    ],
    answerIndex: 1,
    explanation: "Saiz zarah dalam ampaian cukup besar untuk menghalang cahaya daripada tembus.",
  },
  {
    id: "sci-f2-c5-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Mengapakah air dipanggil pelarut semesta?",
    options: [
      "Ia hanya boleh melarutkan cecair",
      "Ia boleh melarutkan hampir semua bahan — pepejal, cecair dan gas",
      "Ia hanya digunakan dalam makmal",
      "Ia tidak boleh melarutkan sebarang bahan",
    ],
    answerIndex: 1,
    explanation: "Air dikenali sebagai pelarut semesta kerana kemampuannya melarutkan hampir semua bahan, sama ada pepejal, cecair atau gas.",
  },
  {
    id: "sci-f2-c5-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Antara berikut, yang manakah kaedah pembersihan air?",
    options: ["Fotosintesis", "Penyulingan", "Respirasi", "Pembakaran"],
    answerIndex: 1,
    explanation: "Penyulingan ialah salah satu kaedah pembersihan air, selain penurasan, pendidihan dan pengklorinan.",
  },
  {
    id: "sci-f2-c5-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah yang membolehkan air naik daripada akar ke daun tumbuhan melalui tindakan kapilari?",
    options: [
      "Daya lekitan sahaja",
      "Daya lekatan sahaja",
      "Kedua-dua daya lekitan (antara molekul air) dan daya lekatan (antara air dan dinding xilem)",
      "Graviti sahaja",
    ],
    answerIndex: 2,
    explanation: "Tindakan kapilari berlaku disebabkan daya lekitan antara molekul air DAN daya lekatan antara molekul air dengan dinding sel xilem.",
  },
  {
    id: "sci-f2-c5-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah kesan penambahan garam ke dalam ais dan ke dalam air mendidih?",
    options: [
      "Menurunkan takat lebur ais dan menurunkan takat didih air",
      "Meningkatkan takat lebur ais dan meningkatkan takat didih air",
      "Menurunkan takat lebur ais dan meningkatkan takat didih air",
      "Tidak memberi kesan kepada takat lebur atau takat didih",
    ],
    answerIndex: 2,
    explanation: "Garam menurunkan takat lebur ais dan meningkatkan takat didih air — ini adalah kesan yang bertentangan.",
  },
  {
    id: "sci-f2-c5-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Pada suhu manakah penyejatan air berlaku?",
    options: ["Hanya pada 100°C", "Hanya pada 0°C", "Pada sebarang suhu, di permukaan air", "Hanya semasa mendidih"],
    answerIndex: 2,
    explanation: "Penyejatan ialah proses yang berlaku pada permukaan air dan berlaku pada SEBARANG suhu, bukan hanya pada takat didih.",
  },
  {
    id: "sci-f2-c5-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Bagaimanakah peningkatan kelembapan mempengaruhi kadar penyejatan?",
    options: [
      "Ia meningkatkan kadar penyejatan",
      "Ia menurunkan kadar penyejatan",
      "Ia tidak memberi kesan",
      "Ia hanya mempengaruhi kondensasi, bukan penyejatan",
    ],
    answerIndex: 1,
    explanation: "Udara lembap sudah mengandungi lebih banyak wap air, jadi ia boleh menampung lebih sedikit molekul air tambahan yang terlepas daripada permukaan, menurunkan kadar penyejatan.",
  },
  {
    id: "sci-f2-c5-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Mengapakah gula halus larut lebih cepat daripada kiub gula?",
    options: [
      "Gula halus mempunyai jumlah luas permukaan yang lebih kecil",
      "Gula halus mempunyai jumlah luas permukaan yang lebih besar terdedah kepada pelarut",
      "Kiub gula mengandungi lebih banyak air",
      "Tidak ada perbezaan dalam kadar larut",
    ],
    answerIndex: 1,
    explanation: "Semakin kecil saiz zat terlarut, semakin besar jumlah luas permukaan yang terdedah kepada pelarut, membolehkannya larut lebih cepat.",
  },
  {
    id: "sci-f2-c5-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Antara berikut, manakah yang paling tepat menerangkan koloid?",
    options: [
      "Campuran jernih yang tidak menyerakkan cahaya",
      "Campuran yang mengenap dan membentuk mendakan seperti ampaian",
      "Campuran pertengahan antara larutan dan ampaian yang tidak membentuk campuran jernih atau mendakan",
      "Sejenis pelarut organik",
    ],
    answerIndex: 2,
    explanation: "Koloid adalah pertengahan antara larutan dan ampaian — ia tidak membentuk campuran jernih (seperti larutan) mahupun mendakan (seperti ampaian).",
  },
  {
    id: "sci-f2-c5-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Antara berikut, manakah contoh koloid jenis emulsi?",
    options: ["Krim pencukur", "Susu", "Air garam", "Air sungai"],
    answerIndex: 1,
    explanation: "Susu dan mayonis adalah contoh koloid jenis emulsi; krim pencukur adalah contoh koloid jenis buih.",
  },
  {
    id: "sci-f2-c5-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Pelarut organik manakah yang biasa digunakan sebagai pelarut cat?",
    options: ["Alkohol", "Aseton", "Turpentin", "Eter"],
    answerIndex: 2,
    explanation: "Turpentin biasa digunakan sebagai pelarut cat dan penanggal cat.",
  },
  {
    id: "sci-f2-c5-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah urutan yang betul bagi kaedah pembersihan air mengikut tahap keberkesanan, daripada paling rendah kepada paling tinggi?",
    options: [
      "Penyulingan → Pendidihan → Penurasan",
      "Penurasan (hanya buang zarah terampai) → Pendidihan/Pengklorinan (bunuh mikroorganisma) → Penyulingan (buang semuanya)",
      "Pengklorinan → Penurasan → Pendidihan",
      "Kesemua empat kaedah membuang bendasing yang sama persis",
    ],
    answerIndex: 1,
    explanation: "Penurasan hanya membuang zarah terampai; pendidihan dan pengklorinan membunuh mikroorganisma tetapi tidak membuang bahan terlarut; penyulingan membuang zarah terampai, bahan terlarut, DAN membunuh mikroorganisma, menjadikannya paling menyeluruh.",
  },
  {
    id: "sci-f2-c5-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Apakah fungsi alum semasa peringkat kogulasi dalam rawatan air?",
    options: [
      "Untuk membunuh mikroorganisma",
      "Untuk melekatkan zarah lumpur bersama dan mengenapkannya",
      "Untuk mencegah kereputan gigi",
      "Untuk meningkatkan kandungan oksigen",
    ],
    answerIndex: 1,
    explanation: "Alum ditambah semasa kogulasi supaya zarah lumpur melekat bersama dan mengenap di dasar tangki.",
  },
  {
    id: "sci-f2-c5-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Seorang murid mengumpulkan gas semasa elektrolisis air dan mendapati nisbah isi padu gas di silinder K kepada silinder L ialah 1:2, di mana K menyalakan semula kayu uji berbara. Apakah yang dapat disimpulkan?",
    options: [
      "K ialah hidrogen (1 bahagian) dan L ialah oksigen (2 bahagian)",
      "K ialah oksigen (1 bahagian) dan L ialah hidrogen (2 bahagian)",
      "Kedua-dua K dan L ialah oksigen",
      "Eksperimen ini tidak sah kerana nisbah sepatutnya 1:1",
    ],
    answerIndex: 1,
    explanation: "Kayu uji berbara menyala semula dalam gas oksigen. Oleh kerana nisbah isi padu hidrogen kepada oksigen adalah 2:1, oksigen (K) ialah isi padu yang lebih kecil (1 bahagian) dan hidrogen (L) ialah isi padu yang lebih besar (2 bahagian).",
  },
  {
    id: "sci-f2-c5-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Mengapakah asid hidroklorik cair ditambah ke dalam air suling sebelum elektrolisis dijalankan untuk mengetahui komposisi air?",
    options: [
      "Untuk menukar formula kimia air",
      "Air tulen sahaja tidak mengkonduksikan elektrik dengan baik; asid ini membekalkan ion untuk membolehkan arus mengalir",
      "Untuk membuang hidrogen daripada air",
      "Untuk meningkatkan takat didih air",
    ],
    answerIndex: 1,
    explanation: "Air suling adalah konduktor elektrik yang lemah secara sendiri; penambahan beberapa titik asid hidroklorik cair meningkatkan kepekatan ion supaya arus boleh mengalir melalui air semasa elektrolisis.",
  },
  {
    id: "sci-f2-c5-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Aliya mendapati tiga sudu garam menghasilkan larutan tepu dalam 50 ml air. Jika dia memanaskan larutan itu, apakah yang paling mungkin berlaku, dan mengapa?",
    options: [
      "Tidak ada apa-apa berlaku kerana larutan tepu tidak boleh berubah",
      "Lebih banyak garam mungkin larut, kerana keterlarutan secara umum meningkat dengan peningkatan suhu",
      "Garam akan bertukar menjadi mendakan serta-merta",
      "Air akan bertukar menjadi ampaian",
    ],
    answerIndex: 1,
    explanation: "Oleh kerana kadar (dan secara umumnya tahap) keterlarutan meningkat dengan suhu, memanaskan larutan tepu boleh membolehkan lebih banyak zat terlarut larut, menjadikannya tidak tepu lagi pada suhu yang lebih tinggi.",
  },
  {
    id: "sci-f2-c5-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Satu campuran air dan serbuk kapur diuji dengan lampu suluh dan ditapis. Cahaya tidak dapat tembus, dan baki tertinggal pada kertas turas. Apakah jenis campuran ini, dan mengapa?",
    options: [
      "Larutan, kerana serbuk kapur larut sepenuhnya dalam air",
      "Koloid, kerana ia tidak mengenap",
      "Ampaian, kerana zarah kapur tidak larut dan cukup besar untuk menghalang cahaya dan meninggalkan baki",
      "Campuran pelarut organik",
    ],
    answerIndex: 2,
    explanation: "Serbuk kapur tidak larut dalam air, membentuk ampaian. Zarah yang tidak larut cukup besar untuk menghalang cahaya dan akan tertangkap sebagai baki semasa penurasan.",
  },
  {
    id: "sci-f2-c5-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Seorang petani ingin mengeringkan ikan yang dituai dengan lebih cepat menggunakan penyejatan semula jadi. Berdasarkan empat faktor yang mempengaruhi kadar penyejatan, kombinasi keadaan manakah yang akan mengeringkan ikan PALING CEPAT?",
    options: [
      "Kelembapan tinggi, suhu rendah, luas permukaan kecil, udara statik",
      "Kelembapan rendah, suhu tinggi, luas permukaan besar, pergerakan udara kuat",
      "Kelembapan tinggi, suhu tinggi, luas permukaan kecil, udara statik",
      "Kelembapan rendah, suhu rendah, luas permukaan besar, udara statik",
    ],
    answerIndex: 1,
    explanation: "Kadar penyejatan adalah paling cepat dengan kelembapan RENDAH, suhu persekitaran TINGGI, luas permukaan terdedah BESAR, dan pergerakan udara PANTAS — kesemua empat faktor bekerjasama untuk memaksimumkan kadar.",
  },
  {
    id: "sci-f2-c5-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Mengapakah Laut Mati membolehkan seseorang terapung dengan lebih mudah berbanding laut biasa?",
    options: [
      "Laut Mati mempunyai ketumpatan lebih rendah disebabkan penyejatan tinggi",
      "Laut Mati mempunyai kandungan garam yang luar biasa tinggi, menjadikan air lebih tumpat dan meningkatkan keapungan semula jadi",
      "Laut Mati mengandungi pelarut organik yang meningkatkan keapungan",
      "Laut Mati lebih sejuk berbanding laut biasa, yang meningkatkan keapungan",
    ],
    answerIndex: 1,
    explanation: "Oleh kerana Laut Mati dikepung sepenuhnya oleh tanah, air yang memasukinya sejat dengan cepat, memekatkan kandungan garam. Kandungan garam yang luar biasa tinggi ini meningkatkan ketumpatan air, menyebabkan keapungan semula jadi.",
  },
  {
    id: "sci-f2-c5-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "K, L, M dan N ialah peringkat dalam sistem pembersihan air: K = Kogulasi, L = Pengklorinan, M = Pemendapan, N = Penurasan. Apakah urutan yang betul?",
    options: [
      "L → K → M → N",
      "N → K → M → L",
      "K → M → N → L",
      "M → N → K → L",
    ],
    answerIndex: 2,
    explanation: "Urutan yang betul ialah Kogulasi (K) → Pemendapan (M) → Penurasan (N) → Pengklorinan (L) — zarah perlu melekat bersama dahulu (kogulasi), kemudian mengenap (pemendapan), kemudian ditapis (penurasan), sebelum air dinyahjangkit (pengklorinan).",
  },
  {
    id: "sci-f2-c5-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Mengapakah Singapura menggunakan inisiatif NEWater berbanding hanya bergantung kepada mengimport atau menuai sumber air semula jadi?",
    options: [
      "Kerana NEWater lebih murah berbanding air hujan",
      "Kerana Singapura mempunyai bekalan air semula jadi yang terhad, jadi mengitar semula air kumbahan menjadi air bersih melalui teknologi moden membantu memenuhi keperluan air negara secara mampan",
      "Kerana NEWater menghapuskan keperluan sebarang pembersihan air",
      "Kerana Singapura tidak mempunyai sebarang sungai",
    ],
    answerIndex: 1,
    explanation: "Singapura mempunyai sumber air semula jadi yang terhad, jadi ia menggunakan teknologi moden untuk mengitar semula air kumbahan menjadi air minuman dan air industri yang bersih (NEWater) sebagai sumber bekalan air alternatif yang mampan.",
  },
  {
    id: "sci-f2-c5-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Sebuah kilang secara haram melepaskan sisa kimia yang tidak dirawat ke dalam sungai. Undang-undang manakah di Malaysia yang paling berkaitan untuk menguatkuasakan tindakan terhadap perbuatan ini?",
    options: [
      "Peraturan Kualiti Alam Sekeliling (Buangan Terjadual) 2005 / Peraturan Efluen Industri 2009",
      "Akta Pengangkutan Jalan",
      "Akta Makanan",
      "Akta Kebajikan Haiwan",
    ],
    answerIndex: 0,
    explanation: "Malaysia menguatkuasakan undang-undang seperti Peraturan Kualiti Alam Sekeliling (Buangan Terjadual) 2005 dan Peraturan Kualiti Alam Sekeliling (Efluen Industri) 2009 untuk memastikan sisa perindustrian dirawat sebelum dilepaskan ke dalam sungai.",
  },
  {
    id: "sci-f2-c5-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 5",
    lang: "bm",
    question: "Vicki menguji air sungai yang berkabus menggunakan empat kaedah: Sampel A (ditapis), Sampel B (didih), Sampel C (disuling), Sampel D (ditambah klorin). Sampel manakah akan menjadi air TULEN, bebas daripada zarah terampai, bendasing terlarut, DAN mikroorganisma?",
    options: ["Sampel A", "Sampel B", "Sampel C", "Sampel D"],
    answerIndex: 2,
    explanation: "Penyulingan (Sampel C) adalah satu-satunya kaedah yang membuang zarah terampai dan bahan terlarut, SERTA membunuh mikroorganisma — menghasilkan air paling tulen antara keempat-empat kaedah.",
  },
];
