import type { Flashcard } from "@/data/content";

export const scienceF2C6FlashcardsBM: Flashcard[] = [
  // Set 1: Sifat Asid & Alkali
  {
    id: "sci-f2-c6-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: 'Daripada bahasa apakah perkataan "asid" berasal dan apakah maksudnya?',
    back: "Bahasa Latin, acidus, bermaksud masam.",
  },
  {
    id: "sci-f2-c6-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: 'Daripada bahasa apakah perkataan "alkali" berasal dan apakah maksudnya?',
    back: "Bahasa Arab, alqali, bermaksud abu tumbuhan.",
  },
  {
    id: "sci-f2-c6-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud asid?",
    back: "Bahan yang menunjukkan sifat berasid apabila dilarutkan dalam air, seperti rasa masam dan pH kurang daripada 7.",
  },
  {
    id: "sci-f2-c6-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud alkali?",
    back: "Bahan yang menunjukkan sifat beralkali apabila dilarutkan dalam air, seperti rasa pahit, terasa licin seperti sabun dan pH lebih daripada 7.",
  },
  {
    id: "sci-f2-c6-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berikan 2 contoh asid dalam kehidupan harian.",
    back: "Asid hidroklorik dan cuka.",
  },
  {
    id: "sci-f2-c6-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berikan 2 contoh alkali dalam kehidupan harian.",
    back: "Larutan natrium hidroksida dan air sabun.",
  },
  {
    id: "sci-f2-c6-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berikan dua contoh asid yang terdapat secara semula jadi dalam makanan.",
    back: "Asid sitrik dalam limau dan asid etanoik dalam cuka.",
  },
  {
    id: "sci-f2-c6-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud bahan berasid dan bahan beralkali?",
    back: "Bahan berasid mengandungi asid (contoh: epal, kopi); bahan beralkali mengandungi alkali (contoh: soda penaik).",
  },
  {
    id: "sci-f2-c6-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah bahan neutral? Berikan satu contoh.",
    back: "Bahan dengan pH 7 yang tidak berasid dan tidak beralkali, contohnya air tulen.",
  },
  {
    id: "sci-f2-c6-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah rasa asid dan alkali?",
    back: "Asid berasa masam; alkali berasa pahit.",
  },
  {
    id: "sci-f2-c6-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Nyatakan empat sifat asid.",
    back: "Berasa masam, mempunyai pH kurang daripada 7, menukarkan kertas litmus biru kepada merah, dan bertindak balas dengan logam reaktif seperti magnesium menghasilkan gas hidrogen.",
  },
  {
    id: "sci-f2-c6-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Nyatakan empat sifat alkali.",
    back: "Berasa pahit, terasa licin seperti sabun, mempunyai pH lebih daripada 7, dan menukarkan kertas litmus merah kepada biru.",
  },
  {
    id: "sci-f2-c6-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Bandingkan ujian rasa dengan ujian kekakisan ke atas asid dan alkali dalam ujian sifat asid dan alkali.",
    back: "Ujian rasa menggunakan jus limau (masam) dan jus peria (pahit). Ujian kekakisan menggunakan asid hidroklorik tumpat / natrium hidroksida tumpat di atas kertas turas.",
  },
  {
    id: "sci-f2-c6-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Senaraikan kelima-lima ujian sifat asid dan alkali dalam ujian sifat asid dan alkali.",
    back: "Nilai pH (kertas pH), rasa, kekakisan, kesan pada litmus biru/merah, tindak balas dengan logam.",
  },
  {
    id: "sci-f2-c6-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud 'mengakis'?",
    back: "Boleh menghakis atau memusnahkan bahan dan melecurkan kulit; asid dan alkali pekat bersifat mengakis.",
  },
  {
    id: "sci-f2-c6-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah yang perlu dilakukan segera jika asid atau alkali pekat tertumpah pada kulit?",
    back: "Bilas kawasan itu dengan banyak air paip yang mengalir dan maklumkan kepada guru.",
  },
  {
    id: "sci-f2-c6-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah asid glasial etanoik tanpa air tidak menukar warna kertas litmus biru?",
    back: "Kerana asid dan alkali hanya menunjukkan sifatnya dengan kehadiran air.",
  },
  {
    id: "sci-f2-c6-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Mengapakah natrium hidroksida pepejal tidak menukar warna kertas litmus merah, tetapi larutannya menukarkan kertas litmus merah kepada biru?",
    back: "Kerana sifat alkali hanya ditunjukkan dengan kehadiran air; tanpa air, ia tidak aktif sebagai alkali.",
  },
  {
    id: "sci-f2-c6-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah yang terhasil apabila asid bertindak balas dengan logam seperti magnesium?",
    back: 'Gas hidrogen, yang menyalakan kayu uji berbunyi "pop".',
  },
  {
    id: "sci-f2-c6-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah tindak balas asid dan alkali dengan magnesium dibandingkan?",
    back: "Asid bertindak balas dengan logam reaktif seperti magnesium menghasilkan gas hidrogen; magnesium tidak bertindak balas dengan alkali.",
  },
  // Set 2: pH, Penunjuk & Peneutralan
  {
    id: "sci-f2-c6-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud penunjuk (indikator)?",
    back: "Bahan pewarna atau campuran pewarna berbeza yang menukar warna berdasarkan bahan yang diuji, untuk menentukan sama ada bahan itu neutral, berasid atau beralkali.",
  },
  {
    id: "sci-f2-c6-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berapakah julat skala pH?",
    back: "Antara 0 hingga 14.",
  },
  {
    id: "sci-f2-c6-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Nilai pH manakah yang menunjukkan bahan neutral?",
    back: "pH 7.",
  },
  {
    id: "sci-f2-c6-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan sifat asid dan alkali dari segi nilai pH.",
    back: "Asid: pH kurang daripada 7. Alkali: pH lebih daripada 7.",
  },
  {
    id: "sci-f2-c6-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah nilai pH menunjukkan tahap keasidan atau kealkalian sesuatu larutan?",
    back: "Semakin rendah pH di bawah 7, semakin berasid larutan itu; semakin tinggi pH di atas 7, semakin beralkali larutan itu.",
  },
  {
    id: "sci-f2-c6-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Larutan A mempunyai pH 1 dan larutan B mempunyai pH 5. Larutan manakah lebih berasid?",
    back: "Larutan A, kerana pH yang lebih rendah menunjukkan darjah keasidan yang lebih tinggi.",
  },
  {
    id: "sci-f2-c6-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah kesan asid dan alkali terhadap kertas litmus biru dan merah?",
    back: "Asid menukar kertas litmus biru kepada merah. Alkali menukar kertas litmus merah kepada biru.",
  },
  {
    id: "sci-f2-c6-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah warna fenolftalein dalam asid, neutral dan alkali?",
    back: "Asid: tidak berwarna. Neutral: tidak berwarna. Alkali: merah jambu.",
  },
  {
    id: "sci-f2-c6-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah warna penunjuk semesta dalam asid, neutral dan alkali?",
    back: "Asid: merah. Neutral: hijau. Alkali: biru.",
  },
  {
    id: "sci-f2-c6-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah warna metil jingga dalam asid, neutral dan alkali?",
    back: "Asid: merah. Neutral: kuning. Alkali: kuning.",
  },
  {
    id: "sci-f2-c6-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan kelima-lima penunjuk dari segi warna dalam keadaan neutral.",
    back: "Fenolftalein: tidak berwarna. Penunjuk semesta: hijau. Metil jingga: kuning. Litmus biru: biru. Litmus merah: merah.",
  },
  {
    id: "sci-f2-c6-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Sampel air kolam diuji: litmus biru kekal biru, litmus merah kekal merah, fenolftalein tidak berwarna. Apakah sifat pH air itu?",
    back: "Neutral (pH 7) — kedua-dua jenis litmus kekal warna asal dan fenolftalein tidak menunjukkan warna merah jambu.",
  },
  {
    id: "sci-f2-c6-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah yang dipanggil tindak balas antara asid dan alkali?",
    back: "Peneutralan.",
  },
  {
    id: "sci-f2-c6-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah persamaan perkataan bagi peneutralan?",
    back: "Asid + Alkali → Garam + Air.",
  },
  {
    id: "sci-f2-c6-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah perubahan yang dialami asid dan alkali semasa peneutralan?",
    back: "Asid hilang sifat keasidannya dan alkali hilang sifat kealkaliannya.",
  },
  {
    id: "sci-f2-c6-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Bandingkan garam yang terhasil daripada asid hidroklorik dan asid sulfurik dengan alkali yang sepadan.",
    back: "Asid hidroklorik + Natrium hidroksida → Natrium klorida + Air. Asid sulfurik + Kalium hidroksida → Kalium sulfat + Air.",
  },
  {
    id: "sci-f2-c6-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Apakah yang dipanggil kaedah yang digunakan untuk menjalankan tindak balas peneutralan secara tepat?",
    back: "Pentitratan.",
  },
  {
    id: "sci-f2-c6-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah fungsi buret dan pipet dalam pentitratan asid-alkali?",
    back: "Buret diisi dengan asid hidroklorik; pipet memindahkan larutan natrium hidroksida ke dalam kelalang kon.",
  },
  {
    id: "sci-f2-c6-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Apakah penunjuk yang digunakan dalam pentitratan asid-alkali dan bagaimana takat akhir dikenal pasti?",
    back: "Fenolftalein digunakan; peneutralan selesai apabila larutan bertukar daripada merah jambu kepada tidak berwarna.",
  },
  {
    id: "sci-f2-c6-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Semasa pentitratan asid-alkali, larutan kekal merah jambu selepas sedikit asid ditambah. Apakah yang ditunjukkan?",
    back: "Jumlah asid yang ditambah masih belum cukup untuk meneutralkan kesemua alkali dalam kelalang kon.",
  },
  // Set 3: Aplikasi Peneutralan
  {
    id: "sci-f2-c6-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah kapur mati membantu tanah yang berasid?",
    back: "Kapur mati bersifat alkali; ia meneutralkan keasidan tanah supaya tumbuhan dapat tumbuh dengan baik.",
  },
  {
    id: "sci-f2-c6-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah tanah yang terlalu beralkali dapat diperbetulkan?",
    back: "Dengan menambah bahan berasid seperti kompos atau gambut untuk menurunkan pH.",
  },
  {
    id: "sci-f2-c6-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah petani perlu mengetahui pH tanah sebelum menanam?",
    back: "Setiap tanaman tumbuh dengan baik dalam julat pH tertentu, jadi tanah yang terlalu berasid atau beralkali perlu dirawat dahulu.",
  },
  {
    id: "sci-f2-c6-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah tasik yang menjadi berasid akibat hujan asid dapat dirawat?",
    back: "Dengan menambah kapur, iaitu bahan beralkali, untuk meneutralkan keasidan air.",
  },
  {
    id: "sci-f2-c6-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Bandingkan pH fabrik selepas dibasuh detergen dengan selepas digunakan pelembut fabrik.",
    back: "Selepas detergen, fabrik menjadi beralkali. Pelembut fabrik yang berasid meneutralkan fabrik tersebut.",
  },
  {
    id: "sci-f2-c6-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan pH rambut sihat dengan rambut selepas dicuci dengan syampu.",
    back: "Rambut sihat sedikit berasid; selepas dicuci dengan syampu, rambut menjadi sedikit beralkali.",
  },
  {
    id: "sci-f2-c6-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah pelembut rambut yang sedikit berasid digunakan selepas syampu?",
    back: "Untuk meneutralkan baki syampu beralkali pada rambut, menjadikan rambut licin dan sihat.",
  },
  {
    id: "sci-f2-c6-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan kesan pencuci muka beralkali dengan toner berasid pada kulit.",
    back: "Pencuci muka beralkali menjadikan kulit kering; toner berasid meneutralkan kulit selepas itu.",
  },
  {
    id: "sci-f2-c6-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah syampu 'pH seimbang' lebih lembut pada rambut?",
    back: "pHnya hampir sama dengan pH rambut dan kulit kepala yang sedikit berasid, jadi rambut tidak menjadi terlalu beralkali.",
  },
  {
    id: "sci-f2-c6-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah ubat gigi mencegah karies gigi?",
    back: "Ubat gigi mengandungi bahan beralkali yang meneutralkan asid yang dihasilkan oleh bakteria dalam mulut.",
  },
  {
    id: "sci-f2-c6-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah antasid melegakan sakit gastrik akibat asid perut berlebihan?",
    back: "Ia mengandungi alkali lemah yang meneutralkan asid hidroklorik berlebihan dalam perut.",
  },
  {
    id: "sci-f2-c6-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah antasid mengandungi alkali lemah dan bukan alkali kuat?",
    back: "Alkali kuat bersifat mengakis dan membahayakan badan; alkali lemah meneutralkan asid berlebihan dengan selamat.",
  },
  {
    id: "sci-f2-c6-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berikan satu contoh peneutralan yang berlaku dalam badan manusia.",
    back: "Hempedu dan jus pankreas yang beralkali meneutralkan makanan berasid yang memasuki duodenum dari perut.",
  },
  {
    id: "sci-f2-c6-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah sengatan lebah, yang berasid, dirawat menggunakan peneutralan?",
    back: "Alkali lemah seperti larutan soda penaik disapu untuk meneutralkan asid tersebut.",
  },
  {
    id: "sci-f2-c6-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah sisa kimia berasid daripada kilang dirawat sebelum dilepaskan ke sungai?",
    back: "Sisa kimia berasid dirawat dengan alkali sebelum dilepaskan ke dalam sungai.",
  },
  {
    id: "sci-f2-c6-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Sebuah kilang melepaskan sisa berasid ke sungai tanpa rawatan. Apakah kesannya dan penyelesaiannya?",
    back: "Mengubah pH sungai dan menjejaskan hidupan akuatik; sisa perlu dirawat dengan alkali sebelum dilepaskan.",
  },
  {
    id: "sci-f2-c6-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah baja dihasilkan menggunakan konsep asid dan alkali?",
    back: "Baja dihasilkan daripada tindak balas antara bahan berasid dan beralkali, contohnya larutan ammonia.",
  },
  {
    id: "sci-f2-c6-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front:
      "Mengapakah makanan berasid seperti jeruk tidak boleh disimpan dalam bekas besi atau aluminium?",
    back: "Asid bertindak balas dengan logam itu, menghakis bekas dan mencemarkan makanan.",
  },
  {
    id: "sci-f2-c6-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Adakah peneutralan hanya berlaku dalam makmal sahaja?",
    back: "Tidak. Peneutralan berlaku secara meluas dalam kehidupan harian, contohnya rawatan tanah, penjagaan diri dan rawatan sisa kilang.",
  },
  {
    id: "sci-f2-c6-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berikan satu aplikasi peneutralan dalam bidang pertanian, perindustrian dan kesihatan.",
    back: "Pertanian: kapur mati untuk tanah berasid. Perindustrian: merawat sisa kilang berasid dengan alkali. Kesihatan: antasid untuk sakit gastrik.",
  },
];
