import type { Flashcard } from "@/data/content";

export const scienceF2C6FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c6-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Daripada bahasa apakah perkataan \"asid\" berasal dan apakah maksudnya?",
    back: "Bahasa Latin, acidus, bermaksud masam.",
  },
  {
    id: "sci-f2-c6-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Daripada bahasa apakah perkataan \"alkali\" berasal dan apakah maksudnya?",
    back: "Bahasa Arab, alqali, bermaksud abu tumbuhan.",
  },
  {
    id: "sci-f2-c6-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berikan 2 contoh asid dalam kehidupan harian.",
    back: "Asid hidroklorik dan cuka.",
  },
  {
    id: "sci-f2-c6-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berikan 2 contoh alkali dalam kehidupan harian.",
    back: "Larutan natrium hidroksida dan air sabun.",
  },
  {
    id: "sci-f2-c6-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud bahan berasid dan bahan beralkali?",
    back: "Bahan berasid mengandungi asid (contoh: epal, kopi); bahan beralkali mengandungi alkali (contoh: soda penaik).",
  },
  {
    id: "sci-f2-c6-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud petunjuk (indikator)?",
    back: "Bahan pewarna atau campuran pewarna berbeza yang menukar warna berdasarkan bahan yang diuji, untuk menentukan sama ada bahan itu neutral, berasid atau beralkali.",
  },
  {
    id: "sci-f2-c6-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Berapakah julat skala pH?",
    back: "Antara 0 hingga 14.",
  },
  {
    id: "sci-f2-c6-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Nilai pH manakah yang menunjukkan bahan neutral?",
    back: "pH 7.",
  },
  {
    id: "sci-f2-c6-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah hubungan antara nilai pH dengan kekuatan asid dan alkali?",
    back: "Semakin rendah nilai pH, semakin kuat asid; semakin tinggi nilai pH, semakin kuat alkali.",
  },
  {
    id: "sci-f2-c6-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah rasa asid dan alkali?",
    back: "Asid berasa masam; alkali berasa pahit.",
  },
  {
    id: "sci-f2-c6-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah kesan asid dan alkali terhadap kertas litmus biru dan merah?",
    back: "Asid menukar kertas litmus biru kepada merah. Alkali menukar kertas litmus merah kepada biru.",
  },
  {
    id: "sci-f2-c6-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah warna fenolftalein dalam asid, neutral dan alkali?",
    back: "Asid: tidak berwarna. Neutral: tidak berwarna. Alkali: merah jambu.",
  },
  {
    id: "sci-f2-c6-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah warna petunjuk sejagat dalam asid, neutral dan alkali?",
    back: "Asid: merah. Neutral: hijau. Alkali: biru.",
  },
  {
    id: "sci-f2-c6-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah warna metil jingga dalam asid, neutral dan alkali?",
    back: "Asid: merah. Neutral: kuning. Alkali: kuning.",
  },
  {
    id: "sci-f2-c6-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah yang terhasil apabila asid bertindak balas dengan logam seperti magnesium?",
    back: "Gas hidrogen, yang menyalakan kayu uji berbunyi \"pop\".",
  },
  {
    id: "sci-f2-c6-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah yang dipanggil tindak balas antara asid dan alkali?",
    back: "Peneutralan.",
  },
  {
    id: "sci-f2-c6-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah persamaan perkataan bagi peneutralan?",
    back: "Asid + Alkali → Garam + Air.",
  },
  {
    id: "sci-f2-c6-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah yang dipanggil kaedah yang digunakan untuk menjalankan tindak balas peneutralan secara tepat?",
    back: "Pentitratan.",
  },
  {
    id: "sci-f2-c6-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah fungsi buret dan pipet dalam Aktiviti 6.5?",
    back: "Buret diisi dengan asid hidroklorik; pipet memindahkan larutan natrium hidroksida ke dalam kelalang kon.",
  },
  {
    id: "sci-f2-c6-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah petunjuk yang digunakan dalam Aktiviti 6.5 dan bagaimana mengetahui peneutralan selesai?",
    back: "Fenolftalein digunakan; peneutralan selesai apabila larutan bertukar daripada merah jambu kepada tidak berwarna.",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c6-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan sifat asid dan alkali dari segi nilai pH.",
    back: "Asid: pH kurang daripada 7. Alkali: pH lebih daripada 7.",
  },
  {
    id: "sci-f2-c6-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan tindak balas asid dan alkali dengan logam.",
    back: "Asid bertindak balas dengan logam untuk menghasilkan gas hidrogen. Alkali tidak bertindak balas dengan logam.",
  },
  {
    id: "sci-f2-c6-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah asid glasial etanoik tanpa air tidak menukar warna kertas litmus biru?",
    back: "Kerana asid dan alkali hanya menunjukkan sifatnya dengan kehadiran air.",
  },
  {
    id: "sci-f2-c6-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah natrium hidroksida pepejal tidak menukar warna kertas litmus merah, tetapi larutannya menukarkan kertas litmus merah kepada biru?",
    back: "Kerana sifat alkali hanya ditunjukkan dengan kehadiran air; tanpa air, ia tidak aktif sebagai alkali.",
  },
  {
    id: "sci-f2-c6-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan garam yang terhasil daripada asid hidroklorik dan asid sulfurik dengan alkali yang sepadan.",
    back: "Asid hidroklorik + Natrium hidroksida → Natrium klorida + Air. Asid sulfurik + Kalium hidroksida → Kalium sulfat + Air.",
  },
  {
    id: "sci-f2-c6-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah garam yang terhasil daripada asid nitrik dan natrium hidroksida?",
    back: "Natrium nitrat dan air (Asid nitrik + Natrium hidroksida → Natrium nitrat + Air).",
  },
  {
    id: "sci-f2-c6-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan kelima-lima petunjuk dari segi warna dalam keadaan neutral.",
    back: "Fenolftalein: tidak berwarna. Petunjuk sejagat: hijau. Metil jingga: kuning. Litmus biru: biru. Litmus merah: merah.",
  },
  {
    id: "sci-f2-c6-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah magnesium tidak bertindak balas dengan alkali dalam Aktiviti 6.1?",
    back: "Kerana alkali tidak menghasilkan tindak balas dengan logam, berbeza dengan asid yang bertindak balas menghasilkan gas hidrogen.",
  },
  {
    id: "sci-f2-c6-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah kapur terhidrat membantu tanah yang berasid?",
    back: "Kapur terhidrat bersifat alkali; ia meneutralkan keasidan tanah supaya tumbuhan dapat tumbuh dengan baik.",
  },
  {
    id: "sci-f2-c6-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan pH fabrik selepas dibasuh detergen dengan selepas digunakan pelembut fabrik.",
    back: "Selepas detergen, fabrik menjadi beralkali. Pelembut fabrik yang berasid meneutralkan fabrik tersebut.",
  },
  {
    id: "sci-f2-c6-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah sisa kimia berasid daripada kilang dirawat sebelum dilepaskan ke sungai?",
    back: "Sisa kimia berasid dirawat dengan alkali sebelum dilepaskan ke dalam sungai.",
  },
  {
    id: "sci-f2-c6-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah ubat gigi mencegah karies gigi?",
    back: "Ubat gigi mengandungi bahan beralkali yang meneutralkan asid yang dihasilkan oleh bakteria dalam mulut.",
  },
  {
    id: "sci-f2-c6-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan kesan pencuci muka beralkali dengan toner berasid pada kulit.",
    back: "Pencuci muka beralkali menjadikan kulit kering; toner berasid meneutralkan kulit selepas itu.",
  },
  {
    id: "sci-f2-c6-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan pH rambut sihat dengan rambut selepas dicuci dengan syampu.",
    back: "Rambut sihat sedikit berasid; selepas dicuci dengan syampu, rambut menjadi sedikit beralkali.",
  },
  {
    id: "sci-f2-c6-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Mengapakah pelembut rambut yang sedikit berasid digunakan selepas syampu?",
    back: "Untuk meneutralkan baki syampu beralkali pada rambut, menjadikan rambut licin dan sihat.",
  },
  {
    id: "sci-f2-c6-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Namakan dua contoh aplikasi peneutralan dalam penjagaan diri.",
    back: "Ubat gigi (meneutralkan asid bakteria) dan toner muka (meneutralkan kealkalian pencuci muka).",
  },
  {
    id: "sci-f2-c6-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Namakan dua contoh aplikasi peneutralan dalam pertanian dan perindustrian.",
    back: "Merawat tanah berasid dengan kapur terhidrat; merawat sisa kilang berasid dengan alkali sebelum dilepaskan ke sungai.",
  },
  {
    id: "sci-f2-c6-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bagaimanakah baja dihasilkan menggunakan konsep asid dan alkali?",
    back: "Baja dihasilkan daripada tindak balas antara bahan berasid dan beralkali, contohnya larutan ammonia.",
  },
  {
    id: "sci-f2-c6-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah perubahan yang dialami asid dan alkali semasa peneutralan?",
    back: "Asid hilang sifat keasidannya dan alkali hilang sifat kealkaliannya.",
  },
  {
    id: "sci-f2-c6-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Bandingkan ujian rasa dengan ujian kekakisan ke atas asid dan alkali dalam Aktiviti 6.1.",
    back: "Ujian rasa menggunakan jus limau (masam) dan jus peria (pahit). Ujian kekakisan menggunakan asid hidroklorik tumpat / natrium hidroksida tumpat di atas kertas turas.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c6-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Tanah ladang terlalu berasid sehingga tanaman tidak subur. Apakah bahan yang sesuai ditambah?",
    back: "Kapur terhidrat (slaked lime), kerana ia beralkali dan akan meneutralkan keasidan tanah.",
  },
  {
    id: "sci-f2-c6-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Dalam pentitratan Aktiviti 6.5, larutan kekal merah jambu walaupun asid telah ditambah. Apakah kesimpulannya?",
    back: "Jumlah asid yang ditambah masih belum cukup untuk meneutralkan kesemua alkali dalam kelalang kon.",
  },
  {
    id: "sci-f2-c6-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Sampel air kolam diuji: litmus biru kekal biru, litmus merah kekal merah, fenolftalein tidak berwarna. Apakah sifat pH air itu?",
    back: "Neutral (pH 7) — kedua-dua jenis litmus kekal warna asal dan fenolftalein tidak menunjukkan warna merah jambu.",
  },
  {
    id: "sci-f2-c6-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah natrium hidroksida pepejal akan menukar warna kertas litmus merah serta-merta?",
    back: "Tidak. Asid dan alkali hanya menunjukkan sifatnya dengan kehadiran air; pepejal tanpa air tidak aktif.",
  },
  {
    id: "sci-f2-c6-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah alkali bertindak balas dengan logam menghasilkan gas hidrogen seperti asid?",
    back: "Tidak. Hanya asid bertindak balas dengan logam menghasilkan gas hidrogen; alkali tidak bertindak balas dengan logam.",
  },
  {
    id: "sci-f2-c6-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan 'nyatakan petunjuk yang sesuai untuk pentitratan' dengan markah penuh?",
    back: "Nyatakan fenolftalein dan terangkan perubahan warna (merah jambu kepada tidak berwarna) sebagai tanda peneutralan lengkap.",
  },
  {
    id: "sci-f2-c6-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Mengapakah toner muka berasid digunakan selepas pencuci muka beralkali?",
    back: "Untuk meneutralkan kealkalian yang menjadikan kulit kering, mengembalikan pH semula jadi kulit.",
  },
  {
    id: "sci-f2-c6-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Sebuah kilang melepaskan sisa berasid ke sungai tanpa rawatan. Apakah kesannya dan penyelesaiannya?",
    back: "Mengubah pH sungai dan menjejaskan hidupan akuatik; sisa perlu dirawat dengan alkali sebelum dilepaskan.",
  },
  {
    id: "sci-f2-c6-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[Fakta Penting] Apakah peranan ammonia dalam pertanian?",
    back: "Larutan ammonia (alkali) digunakan dalam tindak balas dengan bahan berasid untuk menghasilkan baja.",
  },
  {
    id: "sci-f2-c6-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Mengapakah ubat gigi perlu mengandungi bahan beralkali, bukan berasid?",
    back: "Kerana bakteria dalam mulut menghasilkan asid yang menyebabkan karies gigi; bahan beralkali dalam ubat gigi meneutralkan asid tersebut.",
  },
  {
    id: "sci-f2-c6-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Senaraikan kelima-lima ujian sifat asid dan alkali dalam Aktiviti 6.1.",
    back: "Nilai pH (kertas pH), rasa, kekakisan, kesan pada litmus biru/merah, tindak balas dengan logam.",
  },
  {
    id: "sci-f2-c6-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Seorang murid mendakwa 'semua alkali bertindak balas dengan logam'. Adakah dakwaan ini tepat?",
    back: "Tidak tepat. Hanya asid bertindak balas dengan logam menghasilkan gas hidrogen; alkali tidak bertindak balas dengan logam.",
  },
  {
    id: "sci-f2-c6-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Apakah maksud peneutralan secara lengkap (termasuk perubahan kepada asid dan alkali)?",
    back: "Tindak balas antara asid dan alkali menghasilkan garam dan air; asid hilang keasidan, alkali hilang kealkalian.",
  },
  {
    id: "sci-f2-c6-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[Tip Peperiksaan] Apakah perkataan kunci yang perlu disebut bila menjawab soalan tentang pelembut fabrik?",
    back: "Pelembut fabrik berasid meneutralkan fabrik yang menjadi beralkali selepas dibasuh detergen.",
  },
  {
    id: "sci-f2-c6-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Bagaimanakah seseorang dapat membezakan asid kuat dan asid lemah menggunakan nilai pH?",
    back: "Semakin rendah nilai pH (lebih hampir kepada 0), semakin kuat asid tersebut.",
  },
  {
    id: "sci-f2-c6-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Bagaimanakah seseorang dapat membezakan alkali kuat dan alkali lemah menggunakan nilai pH?",
    back: "Semakin tinggi nilai pH (lebih hampir kepada 14), semakin kuat alkali tersebut.",
  },
  {
    id: "sci-f2-c6-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Namakan peralatan yang digunakan dalam Aktiviti 6.5 untuk pentitratan.",
    back: "Buret, pipet, kelalang kon dan fenolftalein.",
  },
  {
    id: "sci-f2-c6-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah peneutralan hanya berlaku dalam makmal sahaja?",
    back: "Tidak. Peneutralan berlaku secara meluas dalam kehidupan harian, contohnya rawatan tanah, penjagaan diri dan rawatan sisa kilang.",
  },
  {
    id: "sci-f2-c6-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "[KBAT] Mengapakah penting bagi kilang merawat sisa kimia berasid sebelum dilepaskan ke sungai, walaupun ia menambah kos pengeluaran?",
    back: "Untuk melindungi hidupan akuatik dan kualiti air sungai daripada perubahan pH yang merosakkan ekosistem.",
  },
  {
    id: "sci-f2-c6-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 6",
    lang: "bm",
    front: "Ringkaskan Bab 6 dalam satu ayat.",
    back: "Asid dan alkali mempunyai sifat berbeza yang diukur melalui skala pH dan petunjuk, serta bertindak balas semasa peneutralan untuk menghasilkan garam dan air dengan pelbagai aplikasi dalam kehidupan harian.",
  },
];
