import type { QuizQuestion } from "@/data/content";

export const scienceF2C6QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c6-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Daripada bahasa apakah perkataan \"asid\" berasal, dan apakah maksudnya?",
    options: [
      "Bahasa Latin, bermaksud masam",
      "Bahasa Arab, bermaksud abu tumbuhan",
      "Bahasa Greek, bermaksud pahit",
      "Bahasa Latin, bermaksud kakisan",
    ],
    answerIndex: 0,
    explanation: "Perkataan \"asid\" berasal daripada perkataan Latin acidus yang bermaksud masam.",
  },
  {
    id: "sci-f2-c6-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Daripada bahasa apakah perkataan \"alkali\" berasal, dan apakah maksudnya?",
    options: [
      "Bahasa Latin, bermaksud masam",
      "Bahasa Arab, bermaksud abu tumbuhan",
      "Bahasa Greek, bermaksud pahit",
      "Bahasa Sanskrit, bermaksud kelikatan",
    ],
    answerIndex: 1,
    explanation: "Perkataan \"alkali\" berasal daripada perkataan Arab alqali yang bermaksud abu tumbuhan.",
  },
  {
    id: "sci-f2-c6-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Berapakah julat nilai skala pH?",
    options: ["0 hingga 7", "0 hingga 14", "1 hingga 10", "7 hingga 14"],
    answerIndex: 1,
    explanation: "Skala pH digunakan untuk menunjukkan kekuatan asid atau alkali dan mempunyai julat antara 0 hingga 14.",
  },
  {
    id: "sci-f2-c6-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Nilai pH manakah yang menunjukkan bahan bersifat neutral?",
    options: ["pH 0", "pH 7", "pH 14", "pH 10"],
    answerIndex: 1,
    explanation: "pH 7 menunjukkan bahan tersebut neutral, bukan asid mahupun alkali.",
  },
  {
    id: "sci-f2-c6-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah warna kertas litmus biru selepas ditambah asid?",
    options: ["Kekal biru", "Bertukar kepada merah", "Bertukar kepada hijau", "Bertukar kepada kuning"],
    answerIndex: 1,
    explanation: "Asid menukar warna kertas litmus biru kepada merah.",
  },
  {
    id: "sci-f2-c6-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah warna kertas litmus merah selepas ditambah alkali?",
    options: ["Kekal merah", "Bertukar kepada biru", "Bertukar kepada kuning", "Bertukar kepada tidak berwarna"],
    answerIndex: 1,
    explanation: "Alkali menukar warna kertas litmus merah kepada biru.",
  },
  {
    id: "sci-f2-c6-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah rasa asid?",
    options: ["Masam", "Pahit", "Tawar", "Manis"],
    answerIndex: 0,
    explanation: "Asid berasa masam, contohnya jus limau.",
  },
  {
    id: "sci-f2-c6-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah rasa alkali?",
    options: ["Masam", "Pahit", "Masin", "Tawar"],
    answerIndex: 1,
    explanation: "Alkali berasa pahit, contohnya jus peria.",
  },
  {
    id: "sci-f2-c6-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah maksud petunjuk (indikator)?",
    options: [
      "Bahan yang mengukur suhu sesuatu larutan",
      "Bahan pewarna atau campuran pewarna yang menukar warna berdasarkan bahan yang diuji",
      "Bahan yang menambah kekakisan asid",
      "Alat untuk mengukur isipadu cecair",
    ],
    answerIndex: 1,
    explanation: "Petunjuk ialah bahan pewarna atau campuran pewarna berbeza yang menukar warna berdasarkan bahan yang diuji, untuk menentukan sama ada bahan itu neutral, berasid atau beralkali.",
  },
  {
    id: "sci-f2-c6-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah hasil tindak balas antara asid dengan alkali?",
    options: ["Gas dan air", "Garam dan air", "Logam dan air", "Garam dan gas"],
    answerIndex: 1,
    explanation: "Persamaan perkataan bagi peneutralan ialah Asid + Alkali → Garam + Air.",
  },
  {
    id: "sci-f2-c6-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Mengapakah asid glasial etanoik (tanpa air) tidak menukar warna kertas litmus biru?",
    options: [
      "Kerana ia bukan asid sebenar",
      "Kerana asid dan alkali hanya menunjukkan sifatnya dengan kehadiran air",
      "Kerana kertas litmus biru telah rosak",
      "Kerana ia terlalu cair",
    ],
    answerIndex: 1,
    explanation: "Asid dan alkali hanya menunjukkan sifatnya dengan kehadiran air; tanpa air, asid glasial etanoik tidak menukar warna kertas litmus biru.",
  },
  {
    id: "sci-f2-c6-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah perubahan warna fenolftalein apabila diuji dengan alkali?",
    options: ["Tidak berwarna kepada merah jambu", "Merah jambu kepada tidak berwarna", "Merah kepada biru", "Kuning kepada merah"],
    answerIndex: 0,
    explanation: "Fenolftalein tidak berwarna dalam keadaan neutral atau berasid, tetapi bertukar kepada merah jambu dalam keadaan beralkali.",
  },
  {
    id: "sci-f2-c6-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah warna petunjuk sejagat dalam larutan neutral?",
    options: ["Merah", "Hijau", "Biru", "Kuning"],
    answerIndex: 1,
    explanation: "Mengikut jadual perubahan warna petunjuk, petunjuk sejagat berwarna hijau dalam keadaan neutral, merah dalam asid, dan biru dalam alkali.",
  },
  {
    id: "sci-f2-c6-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah warna metil jingga dalam keadaan neutral dan beralkali?",
    options: ["Merah", "Kuning", "Biru", "Hijau"],
    answerIndex: 1,
    explanation: "Metil jingga berwarna merah dalam asid, tetapi kuning dalam keadaan neutral mahupun beralkali.",
  },
  {
    id: "sci-f2-c6-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Dalam Aktiviti 6.1, apakah gas yang terhasil apabila riben magnesium bertindak balas dengan asid hidroklorik cair?",
    options: ["Gas oksigen", "Gas karbon dioksida", "Gas hidrogen", "Gas nitrogen"],
    answerIndex: 2,
    explanation: "Riben magnesium bertindak balas dengan asid hidroklorik cair menghasilkan gas hidrogen, yang menyalakan kayu uji berbunyi \"pop\".",
  },
  {
    id: "sci-f2-c6-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah yang berlaku apabila riben magnesium dimasukkan ke dalam larutan alkali dalam Aktiviti 6.1?",
    options: [
      "Menghasilkan gas hidrogen dengan cepat",
      "Menghasilkan gas oksigen",
      "Magnesium tidak bertindak balas dengan alkali",
      "Magnesium melarut sepenuhnya",
    ],
    answerIndex: 2,
    explanation: "Magnesium tidak bertindak balas dengan alkali dalam aktiviti ini, berbeza dengan tindak balasnya dengan asid.",
  },
  {
    id: "sci-f2-c6-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah garam yang terhasil daripada tindak balas antara asid hidroklorik dan natrium hidroksida?",
    options: ["Natrium nitrat", "Kalium sulfat", "Natrium klorida", "Magnesium klorida"],
    answerIndex: 2,
    explanation: "Asid hidroklorik + Natrium hidroksida → Natrium klorida + Air.",
  },
  {
    id: "sci-f2-c6-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Apakah garam yang terhasil daripada tindak balas antara asid sulfurik dan kalium hidroksida?",
    options: ["Kalium sulfat", "Natrium klorida", "Kalium nitrat", "Natrium sulfat"],
    answerIndex: 0,
    explanation: "Asid sulfurik + Kalium hidroksida → Kalium sulfat + Air.",
  },
  {
    id: "sci-f2-c6-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Dalam Aktiviti 6.5, apakah peranan buret?",
    options: [
      "Memindahkan larutan natrium hidroksida ke dalam kelalang kon",
      "Diisi dengan asid hidroklorik untuk pentitratan",
      "Mengukur suhu larutan",
      "Sebagai petunjuk warna",
    ],
    answerIndex: 1,
    explanation: "Dalam Aktiviti 6.5, buret diisi dengan asid hidroklorik, manakala pipet digunakan untuk memindahkan larutan natrium hidroksida ke dalam kelalang kon.",
  },
  {
    id: "sci-f2-c6-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Bagaimanakah seseorang mengetahui bahawa peneutralan telah selesai dalam Aktiviti 6.5?",
    options: [
      "Larutan menjadi keruh",
      "Larutan bertukar daripada merah jambu kepada tidak berwarna",
      "Larutan mengeluarkan buih",
      "Larutan bertukar kepada biru",
    ],
    answerIndex: 1,
    explanation: "Dengan menggunakan fenolftalein sebagai petunjuk, peneutralan selesai apabila larutan bertukar daripada merah jambu kepada tidak berwarna.",
  },
  {
    id: "sci-f2-c6-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Tanah di sebuah ladang didapati terlalu berasid sehingga tanaman tidak subur. Apakah bahan yang sesuai ditambah dan mengapa?",
    options: [
      "Cuka, kerana ia akan meningkatkan keasidan tanah",
      "Kapur terhidrat, kerana ia beralkali dan akan meneutralkan keasidan tanah",
      "Asid sulfurik, kerana ia akan mengakis tanah",
      "Air suling, kerana ia tidak memberi sebarang kesan",
    ],
    answerIndex: 1,
    explanation: "Tanah berasid boleh dirawat dengan menambah kapur terhidrat yang beralkali supaya tumbuhan dapat tumbuh dengan baik melalui proses peneutralan.",
  },
  {
    id: "sci-f2-c6-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Mengapakah pelembut fabrik yang bersifat berasid digunakan selepas fabrik dibasuh dengan detergen?",
    options: [
      "Untuk menjadikan fabrik lebih berwarna",
      "Untuk meningkatkan kealkalian fabrik",
      "Untuk meneutralkan fabrik yang menjadi beralkali selepas dibasuh dengan detergen",
      "Untuk membersihkan kotoran berat",
    ],
    answerIndex: 2,
    explanation: "Pelembut fabrik bersifat berasid dan mengurangkan paras pH fabrik yang menjadi beralkali setelah dibasuh dengan detergen, iaitu satu bentuk peneutralan.",
  },
  {
    id: "sci-f2-c6-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Sebuah kilang melepaskan sisa kimia berasid terus ke dalam sungai tanpa rawatan. Apakah kesan jangka panjang dan bagaimana ia boleh dicegah?",
    options: [
      "Tidak memberi kesan kepada hidupan akuatik; tiada rawatan diperlukan",
      "Menjejaskan hidupan akuatik akibat perubahan pH air; sisa perlu dirawat dengan alkali sebelum dilepaskan",
      "Air sungai akan menjadi beralkali secara semula jadi tanpa rawatan",
      "Hanya menjejaskan warna air sungai, bukan hidupan",
    ],
    answerIndex: 1,
    explanation: "Sisa kimia berasid daripada kilang perlu dirawat dengan alkali sebelum dilepaskan ke dalam sungai untuk mengelakkan kesan buruk terhadap hidupan akuatik akibat perubahan pH.",
  },
  {
    id: "sci-f2-c6-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Bagaimanakah ubat gigi membantu mencegah karies gigi dari segi konsep peneutralan?",
    options: [
      "Ubat gigi berasid dan menambah lagi keasidan dalam mulut",
      "Ubat gigi mengandungi bahan beralkali yang meneutralkan asid yang dihasilkan oleh bakteria dalam mulut",
      "Ubat gigi tidak mempunyai kaitan dengan pH mulut",
      "Ubat gigi hanya membersihkan secara fizikal tanpa tindak balas kimia",
    ],
    answerIndex: 1,
    explanation: "Ubat gigi mengandungi bahan beralkali yang dapat meneutralkan asid yang dihasilkan oleh bakteria dalam mulut, sekali gus mencegah karies gigi.",
  },
  {
    id: "sci-f2-c6-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Seorang pelajar menggunakan pencuci muka beralkali setiap hari sehingga kulit mukanya menjadi kering. Apakah penyelesaian yang sesuai mengikut konsep peneutralan?",
    options: [
      "Menggunakan lebih banyak pencuci muka beralkali",
      "Menggunakan toner berasid untuk meneutralkan kealkalian pada kulit",
      "Tidak membasuh muka sama sekali",
      "Menggunakan air suling sahaja tanpa sebarang produk",
    ],
    answerIndex: 1,
    explanation: "Pencuci muka yang beralkali menjadikan kulit muka kering, oleh itu toner berasid digunakan untuk meneutralkan kulit.",
  },
  {
    id: "sci-f2-c6-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Mengapakah pelembut rambut yang sedikit berasid digunakan selepas mencuci rambut dengan syampu?",
    options: [
      "Syampu menjadikan rambut sedikit beralkali; pelembut rambut berasid meneutralkan baki syampu agar rambut licin dan sihat",
      "Untuk menjadikan rambut lebih beralkali",
      "Syampu tidak memberi sebarang kesan kepada pH rambut",
      "Pelembut rambut hanya berfungsi sebagai pewarna",
    ],
    answerIndex: 0,
    explanation: "Rambut yang sihat sedikit berasid, tetapi syampu menjadikan rambut sedikit beralkali; pelembut rambut yang sedikit berasid meneutralkan baki syampu pada rambut.",
  },
  {
    id: "sci-f2-c6-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Dalam satu eksperimen pentitratan menggunakan kaedah Aktiviti 6.5, larutan dalam kelalang kon kekal merah jambu walaupun lebih banyak asid hidroklorik telah ditambah daripada buret. Apakah kesimpulan yang sesuai bagi pemerhatian ini?",
    options: [
      "Peneutralan telah selesai sepenuhnya",
      "Jumlah asid yang ditambah masih belum cukup untuk meneutralkan kesemua alkali dalam kelalang kon",
      "Fenolftalein telah rosak",
      "Larutan dalam kelalang kon adalah berasid",
    ],
    answerIndex: 1,
    explanation: "Larutan kekal merah jambu (warna fenolftalein dalam keadaan beralkali) bermakna alkali masih berlebihan; peneutralan baru selesai apabila warna bertukar kepada tidak berwarna.",
  },
  {
    id: "sci-f2-c6-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Mengapakah natrium hidroksida pepejal tidak menukar warna kertas litmus merah, tetapi larutan natrium hidroksida menukarkannya kepada biru?",
    options: [
      "Kerana natrium hidroksida pepejal bukan alkali",
      "Kerana asid dan alkali hanya menunjukkan sifatnya dengan kehadiran air",
      "Kerana kertas litmus merah rosak apabila terkena pepejal",
      "Kerana natrium hidroksida pepejal lebih lemah daripada larutannya",
    ],
    answerIndex: 1,
    explanation: "Asid dan alkali hanya menunjukkan sifatnya dengan kehadiran air; natrium hidroksida pepejal (tanpa air) tidak menukar warna litmus merah, tetapi dengan air ia menukarkannya kepada biru.",
  },
  {
    id: "sci-f2-c6-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Seorang petani menggunakan larutan ammonia untuk menghasilkan baja bagi tanamannya. Apakah konsep sains yang mendasari proses ini?",
    options: [
      "Larutan ammonia adalah asid yang mengakis tanah",
      "Baja dihasilkan daripada tindak balas antara bahan berasid dan beralkali, dengan ammonia sebagai bahan alkali",
      "Larutan ammonia tidak berkaitan dengan asid atau alkali",
      "Baja dihasilkan tanpa melibatkan sebarang tindak balas kimia",
    ],
    answerIndex: 1,
    explanation: "Baja dihasilkan daripada tindak balas antara bahan berasid dan beralkali; larutan ammonia (alkali) digunakan dalam penghasilan baja untuk sektor pertanian.",
  },
  {
    id: "sci-f2-c6-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "bm",
    question: "Berdasarkan jadual perubahan warna petunjuk, sebatang sampel air kolam diuji dengan kertas litmus biru (kekal biru), kertas litmus merah (kekal merah), dan fenolftalein (tidak berwarna). Apakah sifat pH air kolam itu?",
    options: ["Berasid", "Beralkali", "Neutral", "Tidak dapat ditentukan"],
    answerIndex: 2,
    explanation: "Kertas litmus biru dan merah yang kekal warna asal serta fenolftalein yang kekal tidak berwarna menunjukkan bahan tersebut adalah neutral (pH 7).",
  },
];
