import type { QuizQuestion } from "@/data/content";

export const scienceF2C6QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c6-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "From which language does the word \"acid\" originate, and what does it mean?",
    options: [
      "Latin, meaning sour",
      "Arabic, meaning ashes of plants",
      "Greek, meaning bitter",
      "Latin, meaning corrosive",
    ],
    answerIndex: 0,
    explanation: "The word \"acid\" comes from the Latin word acidus, which means sour.",
  },
  {
    id: "sci-f2-c6-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "From which language does the word \"alkali\" originate, and what does it mean?",
    options: [
      "Latin, meaning sour",
      "Arabic, meaning ashes of plants",
      "Greek, meaning bitter",
      "Sanskrit, meaning viscosity",
    ],
    answerIndex: 1,
    explanation: "The word \"alkali\" comes from the Arabic word alqali, which means ashes of plants.",
  },
  {
    id: "sci-f2-c6-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What is the range of the pH scale?",
    options: ["0 to 7", "0 to 14", "1 to 10", "7 to 14"],
    answerIndex: 1,
    explanation: "The pH scale is used to show the strength of acids or alkalis, with a range of 0 to 14.",
  },
  {
    id: "sci-f2-c6-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "Which pH value indicates a neutral substance?",
    options: ["pH 0", "pH 7", "pH 14", "pH 10"],
    answerIndex: 1,
    explanation: "pH 7 indicates that a substance is neutral, neither acidic nor alkaline.",
  },
  {
    id: "sci-f2-c6-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What colour does blue litmus paper turn when an acid is added?",
    options: ["Stays blue", "Turns red", "Turns green", "Turns yellow"],
    answerIndex: 1,
    explanation: "An acid turns blue litmus paper red.",
  },
  {
    id: "sci-f2-c6-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What colour does red litmus paper turn when an alkali is added?",
    options: ["Stays red", "Turns blue", "Turns yellow", "Turns colourless"],
    answerIndex: 1,
    explanation: "An alkali turns red litmus paper blue.",
  },
  {
    id: "sci-f2-c6-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What is the taste of an acid?",
    options: ["Sour", "Bitter", "Bland", "Sweet"],
    answerIndex: 0,
    explanation: "Acids taste sour, for example lime juice.",
  },
  {
    id: "sci-f2-c6-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What is the taste of an alkali?",
    options: ["Sour", "Bitter", "Salty", "Bland"],
    answerIndex: 1,
    explanation: "Alkalis taste bitter, for example bitter gourd juice.",
  },
  {
    id: "sci-f2-c6-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What is the meaning of an indicator?",
    options: [
      "A substance that measures the temperature of a solution",
      "A colouring or mixture of colourings that changes colour based on the substance tested",
      "A substance that increases the corrosiveness of an acid",
      "An instrument used to measure the volume of a liquid",
    ],
    answerIndex: 1,
    explanation: "An indicator is a colouring or mixture of different colourings that changes colour based on the substance tested, used to determine if a substance is neutral, acidic or alkaline.",
  },
  {
    id: "sci-f2-c6-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What is produced from the reaction between an acid and an alkali?",
    options: ["Gas and water", "Salt and water", "Metal and water", "Salt and gas"],
    answerIndex: 1,
    explanation: "The word equation for neutralisation is Acid + Alkali → Salt + Water.",
  },
  {
    id: "sci-f2-c6-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "Why does glacial ethanoic acid (without water) not change the colour of blue litmus paper?",
    options: [
      "Because it is not a true acid",
      "Because acids and alkalis only show their properties in the presence of water",
      "Because the blue litmus paper is damaged",
      "Because it is too dilute",
    ],
    answerIndex: 1,
    explanation: "Acids and alkalis show their properties only in the presence of water; without water, glacial ethanoic acid does not change the colour of blue litmus paper.",
  },
  {
    id: "sci-f2-c6-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What colour change occurs to phenolphthalein when tested with an alkali?",
    options: ["Colourless to pink", "Pink to colourless", "Red to blue", "Yellow to red"],
    answerIndex: 0,
    explanation: "Phenolphthalein is colourless in neutral and acidic conditions, but turns pink in alkaline conditions.",
  },
  {
    id: "sci-f2-c6-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What colour is universal indicator in a neutral solution?",
    options: ["Red", "Green", "Blue", "Yellow"],
    answerIndex: 1,
    explanation: "According to the colour change table, universal indicator is green in neutral conditions, red in acids, and blue in alkalis.",
  },
  {
    id: "sci-f2-c6-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What colour is methyl orange in neutral and alkaline conditions?",
    options: ["Red", "Yellow", "Blue", "Green"],
    answerIndex: 1,
    explanation: "Methyl orange is red in acid, but yellow in both neutral and alkaline conditions.",
  },
  {
    id: "sci-f2-c6-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "In Activity 6.1, what gas is produced when magnesium ribbon reacts with dilute hydrochloric acid?",
    options: ["Oxygen gas", "Carbon dioxide gas", "Hydrogen gas", "Nitrogen gas"],
    answerIndex: 2,
    explanation: "Magnesium ribbon reacts with dilute hydrochloric acid to produce hydrogen gas, which gives a \"pop\" sound with a lighted wooden splinter.",
  },
  {
    id: "sci-f2-c6-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What happens when magnesium ribbon is placed in an alkaline solution in Activity 6.1?",
    options: [
      "It quickly produces hydrogen gas",
      "It produces oxygen gas",
      "Magnesium does not react with the alkali",
      "Magnesium dissolves completely",
    ],
    answerIndex: 2,
    explanation: "Magnesium does not react with alkali in this activity, unlike its reaction with acid.",
  },
  {
    id: "sci-f2-c6-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What salt is produced from the reaction between hydrochloric acid and sodium hydroxide?",
    options: ["Sodium nitrate", "Potassium sulphate", "Sodium chloride", "Magnesium chloride"],
    answerIndex: 2,
    explanation: "Hydrochloric acid + Sodium hydroxide → Sodium chloride + Water.",
  },
  {
    id: "sci-f2-c6-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "What salt is produced from the reaction between sulphuric acid and potassium hydroxide?",
    options: ["Potassium sulphate", "Sodium chloride", "Potassium nitrate", "Sodium sulphate"],
    answerIndex: 0,
    explanation: "Sulphuric acid + Potassium hydroxide → Potassium sulphate + Water.",
  },
  {
    id: "sci-f2-c6-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "In Activity 6.5, what is the role of the burette?",
    options: [
      "Transferring sodium hydroxide solution into the conical flask",
      "Filled with hydrochloric acid for titration",
      "Measuring the temperature of the solution",
      "Acting as a colour indicator",
    ],
    answerIndex: 1,
    explanation: "In Activity 6.5, the burette is filled with hydrochloric acid, while the pipette is used to transfer sodium hydroxide solution into the conical flask.",
  },
  {
    id: "sci-f2-c6-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "How would one know that neutralisation is complete in Activity 6.5?",
    options: [
      "The solution becomes cloudy",
      "The solution changes from pink to colourless",
      "The solution produces bubbles",
      "The solution turns blue",
    ],
    answerIndex: 1,
    explanation: "Using phenolphthalein as the indicator, neutralisation is complete when the solution changes from pink to colourless.",
  },
  {
    id: "sci-f2-c6-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "The soil on a farm is found to be too acidic for crops to grow well. What substance should be added and why?",
    options: [
      "Vinegar, because it will increase the soil's acidity",
      "Slaked lime, because it is alkaline and will neutralise the soil's acidity",
      "Sulphuric acid, because it will corrode the soil",
      "Distilled water, because it has no effect",
    ],
    answerIndex: 1,
    explanation: "Acidic soil can be treated by adding slaked lime, which is alkaline, so that plants can grow well through the process of neutralisation.",
  },
  {
    id: "sci-f2-c6-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "Why is an acidic fabric softener used after fabrics are washed with detergent?",
    options: [
      "To make the fabric more colourful",
      "To increase the alkalinity of the fabric",
      "To neutralise the fabric, which becomes alkaline after being washed with detergent",
      "To remove heavy stains",
    ],
    answerIndex: 2,
    explanation: "Fabric softeners are acidic and reduce the pH level of fabrics, which become alkaline after being washed with detergents — a form of neutralisation.",
  },
  {
    id: "sci-f2-c6-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "A factory discharges acidic chemical waste directly into a river without treatment. What is the long-term effect and how can it be prevented?",
    options: [
      "No effect on aquatic life; no treatment is needed",
      "It harms aquatic life due to changes in water pH; the waste must be treated with alkalis before discharge",
      "The river water will naturally become alkaline without treatment",
      "It only affects the colour of the river water, not living organisms",
    ],
    answerIndex: 1,
    explanation: "Acidic waste substances from factories must be treated with alkalis before being discharged into the river to prevent harmful effects on aquatic life caused by pH changes.",
  },
  {
    id: "sci-f2-c6-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "How does toothpaste help prevent dental caries based on the concept of neutralisation?",
    options: [
      "Toothpaste is acidic and adds to the acidity in the mouth",
      "Toothpaste contains an alkaline substance that neutralises the acid produced by bacteria in the mouth",
      "Toothpaste has no relation to the pH of the mouth",
      "Toothpaste only cleans physically without any chemical reaction",
    ],
    answerIndex: 1,
    explanation: "Toothpaste contains an alkaline substance that can neutralise the acid produced by bacteria in the mouth, thereby preventing dental caries.",
  },
  {
    id: "sci-f2-c6-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "A student uses an alkaline face cleanser daily until their facial skin becomes dry. What is the appropriate solution based on the concept of neutralisation?",
    options: [
      "Use more alkaline face cleanser",
      "Use an acidic toner to neutralise the alkalinity on the skin",
      "Stop washing the face altogether",
      "Use only distilled water without any product",
    ],
    answerIndex: 1,
    explanation: "Alkaline face cleansers make the facial skin dry, so acidic toners are used to neutralise the skin.",
  },
  {
    id: "sci-f2-c6-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "Why is a mildly acidic hair conditioner used after washing hair with shampoo?",
    options: [
      "Shampoo makes hair slightly alkaline; acidic conditioner neutralises the shampoo residue so hair becomes smooth and healthy",
      "To make the hair more alkaline",
      "Shampoo has no effect on the pH of hair",
      "Hair conditioner only functions as a colouring agent",
    ],
    answerIndex: 0,
    explanation: "Healthy hair is slightly acidic, but shampoo makes hair slightly alkaline; a mildly acidic hair conditioner neutralises the shampoo residue on hair.",
  },
  {
    id: "sci-f2-c6-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "In a titration experiment using the method from Activity 6.5, the solution in the conical flask remains pink even after more hydrochloric acid has been added from the burette. What is the most accurate conclusion?",
    options: [
      "Neutralisation is fully complete",
      "The amount of acid added is still insufficient to neutralise all the alkali in the conical flask",
      "The phenolphthalein has gone bad",
      "The solution in the conical flask is acidic",
    ],
    answerIndex: 1,
    explanation: "The solution remaining pink (phenolphthalein's colour in alkaline conditions) means alkali is still in excess; neutralisation is only complete when the colour changes to colourless.",
  },
  {
    id: "sci-f2-c6-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "Why does solid sodium hydroxide not change the colour of red litmus paper, but sodium hydroxide solution turns it blue?",
    options: [
      "Because solid sodium hydroxide is not an alkali",
      "Because acids and alkalis only show their properties in the presence of water",
      "Because the red litmus paper is damaged by the solid",
      "Because solid sodium hydroxide is weaker than its solution",
    ],
    answerIndex: 1,
    explanation: "Acids and alkalis show their properties only in the presence of water; solid sodium hydroxide (without water) does not change red litmus paper, but with water it turns it blue.",
  },
  {
    id: "sci-f2-c6-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "A farmer uses ammonia solution to produce fertiliser for crops. What scientific concept underlies this process?",
    options: [
      "Ammonia solution is an acid that corrodes the soil",
      "Fertilisers are produced from the reaction between acidic and alkaline substances, with ammonia as the alkaline substance",
      "Ammonia solution has no relation to acids or alkalis",
      "Fertilisers are produced without any chemical reaction",
    ],
    answerIndex: 1,
    explanation: "Fertilisers are produced from the reaction between acidic and alkaline substances; ammonia solution (an alkali) is used in fertiliser production for the agricultural sector.",
  },
  {
    id: "sci-f2-c6-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 6",
    lang: "dlp",
    question: "Based on the indicator colour change table, a pond water sample is tested with blue litmus paper (stays blue), red litmus paper (stays red), and phenolphthalein (colourless). What is the pH nature of the pond water?",
    options: ["Acidic", "Alkaline", "Neutral", "Cannot be determined"],
    answerIndex: 2,
    explanation: "Blue and red litmus paper remaining unchanged, along with phenolphthalein remaining colourless, indicates the substance is neutral (pH 7).",
  },
];
