import type { MathGeometryVisual } from "@/features/quiz/visuals/mathGeometryVisual";
import {
  cuboid,
  views,
  triangularPrism,
  steppedPrism,
  planeNormal,
  layout,
  cylinder,
  inclinedTriangle,
  inclinedRod,
  overlappingVertices,
} from "../quiz-solids";
const normal = planeNormal(),
  positions = layout(),
  tube = cylinder(),
  prism = triangularPrism(),
  step = steppedPrism();
export const MATH_F3_C7_QUIZ_VISUALS: Partial<
  Record<number, MathGeometryVisual>
> = {
  3: normal,
  4: normal,
  5: cuboid("?", "?", "?"),
  6: cuboid("?", "?", "?"),
  10: positions,
  11: positions,
  12: normal,
  16: views("4 cm", "3 cm", "2 cm"),
  17: views("?", "?", "?"),
  18: normal,
  19: views("8 cm", "5 cm", "3 cm"),
  20: views("12 cm", "8 cm", "5 cm"),
  21: cuboid("?", "?", "?", true),
  22: normal,
  24: tube,
  25: tube,
  28: prism,
  29: positions,
  30: positions,
  34: views("8 cm", "5 cm", "3 cm"),
  36: step,
  37: cuboid("7 cm", "4 cm", "3 cm"),
  38: cuboid("7 cm", "4 cm", "3 cm"),
  39: prism,
  40: overlappingVertices(),
  41: inclinedTriangle(),
  43: inclinedRod(),
  44: prism,
  45: step,
  46: prism,
  48: views("4 cm", "2.5 cm", "1.5 cm"),
  49: overlappingVertices(),
  50: views("w", "d", "h"),
};
