import type { StructuredNotes } from "@/data/types";

export const sejarahF3C1Notes: StructuredNotes = {
  chapterSummary: "Bab ini menerangkan kestabilan dan kemakmuran negara kita sebelum kedatangan kuasa Barat, faktor kedatangan kuasa Barat, persaingan mendapatkan tanah jajahan dan strategi kuasa Barat menguasai negara kita.",
  quickRevision: ["1.1 Kestabilan dan Kemakmuran Negara Kita: Negara kita mempunyai sistem pemerintahan beraja dan pentadbiran mantap sebelum kedatangan Barat.","Tarikh penting 1.1: 1759: Batu Uban dibuka oleh orang Melayu dari Sumatera","1.2 Faktor Kedatangan Kuasa Barat ke Negara Kita: Pada tahun 1600, Syarikat Hindia Timur Inggeris ditubuhkan di England.","Tarikh penting 1.2: 1600: SHTI ditubuhkan","1.3 Persaingan Kuasa Barat untuk Mendapatkan Tanah Jajahan: Kuasa Barat bersaing untuk mendapatkan tanah jajahan bagi bahan mentah, pasaran dan kedudukan strategik.","Tarikh penting 1.3: 1843: serangan penduduk tempatan ke atas kapal British di Sabah","1.4 Perbezaan Strategi Kuasa Barat untuk Menguasai Negara Kita: Kuasa Barat menggunakan strategi perjanjian, pakatan, manipulasi, ugutan, serangan fizikal dan pajakan.","Tarikh penting 1.4: 1786: British menduduki Pulau Pinang"],
  keyTerms: ["kestabilan","kemakmuran","sistem beraja","perundangan","hubungan luar","ekonomi tradisional","rempah-ratus","SHTI","VOC","Revolusi Perindustrian","Terusan Suez","kapal wap","telegraf","imperialisme","tanah jajahan","persaingan kuasa Barat","bahan mentah","pasaran","perjanjian","pakatan","manipulasi","ugutan","serangan fizikal","pajakan"],
  keyExamFacts: ["Negara kita mempunyai sistem pemerintahan beraja dan pentadbiran mantap sebelum kedatangan Barat.","Pentadbiran negeri diketuai raja atau sultan, dibantu pembesar jajahan atau daerah dan penghulu atau penggawa pada peringkat kampung.","Perundangan terdiri daripada undang-undang tidak bertulis seperti adat dan undang-undang bertulis seperti Hukum Kanun Melaka, Hukum Kanun Pahang dan Undang-Undang 99 Perak.","Pada tahun 1600, Syarikat Hindia Timur Inggeris ditubuhkan di England.","Pada tahun 1602, Syarikat Hindia Timur Belanda ditubuhkan.","Pada tahun 1664, Perancis menubuhkan Syarikat Hindia Timur Perancis.","Kuasa Barat bersaing untuk mendapatkan tanah jajahan bagi bahan mentah, pasaran dan kedudukan strategik.","British, Belanda, Perancis, Sepanyol, Jerman dan Amerika Syarikat terlibat dalam persaingan imperialisme.","Kawasan di Alam Melayu penting kerana kedudukan strategik dan kekayaan hasil bumi.","Kuasa Barat menggunakan strategi perjanjian, pakatan, manipulasi, ugutan, serangan fizikal dan pajakan.","British menggunakan perjanjian untuk mendapatkan Pulau Pinang, Singapura dan Melaka.","Belanda dan British memeterai Perjanjian London 1824 untuk menyelesaikan pertikaian di Alam Melayu."],
  sections: [
    {
      title: "Bab Overview",
      subsections: [
        { title: "Sinopsis", content: "Bab ini menerangkan kestabilan dan kemakmuran negara kita sebelum kedatangan kuasa Barat, faktor kedatangan kuasa Barat, persaingan mendapatkan tanah jajahan dan strategi kuasa Barat menguasai negara kita." },
        { title: "Apa yang akan dipelajari", bulletPoints: ["1.1 Kestabilan dan Kemakmuran Negara Kita","1.2 Faktor Kedatangan Kuasa Barat ke Negara Kita","1.3 Persaingan Kuasa Barat untuk Mendapatkan Tanah Jajahan","1.4 Perbezaan Strategi Kuasa Barat untuk Menguasai Negara Kita"] },
        { title: "Fokus UASA", bulletPoints: ["Kenal pasti kronologi, tokoh, tempat, perjanjian dan kesan.","Bezakan sebab, strategi dan kesan peluasan kuasa Barat.","Gunakan kata kunci seperti kedaulatan, pentadbiran, ekonomi, penentangan dan pemodenan."] },
      ],
    },
    {
      title: "1.1 Kestabilan dan Kemakmuran Negara Kita",
      subsections: [
        { title: "Ringkasan", content: "Kestabilan dan Kemakmuran Negara Kita menerangkan negara kita mempunyai sistem pemerintahan beraja dan pentadbiran mantap sebelum kedatangan barat. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Negara kita mempunyai sistem pemerintahan beraja dan pentadbiran mantap sebelum kedatangan Barat.","Pentadbiran negeri diketuai raja atau sultan, dibantu pembesar jajahan atau daerah dan penghulu atau penggawa pada peringkat kampung.","Perundangan terdiri daripada undang-undang tidak bertulis seperti adat dan undang-undang bertulis seperti Hukum Kanun Melaka, Hukum Kanun Pahang dan Undang-Undang 99 Perak.","Kemakmuran disokong hasil bumi, hasil alam, perdagangan, pelabuhan, sistem mata wang, percukaian, timbang sukat dan kegiatan intelektual."] },
        { title: "Kata kunci", bulletPoints: ["kestabilan","kemakmuran","sistem beraja","perundangan","hubungan luar","ekonomi tradisional"] },
        { title: "Tokoh penting", bulletPoints: ["Raja atau Sultan","Pembesar","Penghulu","Penggawa","Ibu Soko"] },
        { title: "Tarikh penting", bulletPoints: ["1759: Batu Uban dibuka oleh orang Melayu dari Sumatera"] },
        { title: "Tempat penting", bulletPoints: ["Negeri-negeri Melayu","Sarawak","Sabah","Pelabuhan Johor","Kedah","Klang","Melaka","Batu Uban"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Adat Perpatih; Hukum Kanun Melaka; Hukum Kanun Pahang; Undang-Undang 99 Perak"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Kebijaksanaan pemerintah","Muafakat pemerintah dan rakyat","Kedudukan pelabuhan strategik","Kekayaan hasil bumi dan hasil alam"] },
        { title: "Kesan", bulletPoints: ["Pentadbiran stabil","Hubungan luar berkembang","Ekonomi makmur","Bahasa Melayu dan tulisan Jawi berkembang"] },
        { title: "Kepentingan", bulletPoints: ["Membuktikan negara kita sudah mempunyai tamadun, pentadbiran dan ekonomi tersusun sebelum campur tangan Barat."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Kestabilan politik memudahkan kemakmuran ekonomi; kemakmuran pula menarik minat kuasa Barat."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta pelabuhan dan muara sungai menunjukkan perdagangan berkembang kerana lokasi strategik di laluan timur dan barat.","Sebelum abad ke-16: sistem beraja, adat, pelabuhan dan pendidikan tempatan sudah berkembang."] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "1.2 Faktor Kedatangan Kuasa Barat ke Negara Kita",
      subsections: [
        { title: "Ringkasan", content: "Faktor Kedatangan Kuasa Barat ke Negara Kita menerangkan pada tahun 1600, syarikat hindia timur inggeris ditubuhkan di england. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Pada tahun 1600, Syarikat Hindia Timur Inggeris ditubuhkan di England.","Pada tahun 1602, Syarikat Hindia Timur Belanda ditubuhkan.","Pada tahun 1664, Perancis menubuhkan Syarikat Hindia Timur Perancis.","Kedatangan Barat dipengaruhi keperluan barangan mewah, pusat pengumpulan barang, pelabuhan persinggahan, penyebaran agama Kristian, Revolusi Perindustrian, perkembangan industri kereta, kesuburan tanah, industri mengetin, Terusan Suez, kapal wap, persaingan kuasa Barat dan telegraf."] },
        { title: "Kata kunci", bulletPoints: ["rempah-ratus","SHTI","VOC","Revolusi Perindustrian","Terusan Suez","kapal wap","telegraf"] },
        { title: "Tokoh penting", bulletPoints: ["Ferdinand de Lesseps"] },
        { title: "Tarikh penting", bulletPoints: ["1600: SHTI ditubuhkan","1602: Syarikat Hindia Timur Belanda ditubuhkan","1664: Syarikat Hindia Timur Perancis ditubuhkan","1859: Terusan Suez mula dibangunkan","1870-an: Jerman dan Perancis menjadi negara perindustrian"] },
        { title: "Tempat penting", bulletPoints: ["Kepulauan Melayu","China","India","Canton","Pelabuhan Said","Suez","Tanjung Harapan"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","SHTI; VOC"]] } },
        { title: "Sebab", bulletPoints: ["Permintaan rempah, emas, perak, sutera dan tembikar","Keperluan bahan mentah dan pasaran","Perkembangan pengangkutan dan komunikasi","Persaingan mendapatkan tanah jajahan"] },
        { title: "Kesan", bulletPoints: ["Alam Melayu menjadi sasaran kuasa Barat","Perdagangan bertambah","Tanah jajahan dicari untuk bahan mentah dan pasaran"] },
        { title: "Kepentingan", bulletPoints: ["Menjelaskan sebab kuasa Barat sanggup datang jauh dan bersaing untuk menguasai Alam Melayu."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Revolusi Perindustrian meningkatkan keperluan bahan mentah; kemajuan kapal wap dan Terusan Suez mempercepat penguasaan Barat."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta laluan Portugis, Sepanyol, Belanda dan Inggeris menunjukkan Alam Melayu terletak di laluan perdagangan antarabangsa.","Abad ke-16: Portugis dan Sepanyol","Abad ke-17 hingga ke-18: Belanda, British dan Perancis","Abad ke-19 hingga ke-20: bahan mentah dan pasaran industri menjadi tumpuan"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "1.3 Persaingan Kuasa Barat untuk Mendapatkan Tanah Jajahan",
      subsections: [
        { title: "Ringkasan", content: "Persaingan Kuasa Barat untuk Mendapatkan Tanah Jajahan menerangkan kuasa barat bersaing untuk mendapatkan tanah jajahan bagi bahan mentah, pasaran dan kedudukan strategik. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Kuasa Barat bersaing untuk mendapatkan tanah jajahan bagi bahan mentah, pasaran dan kedudukan strategik.","British, Belanda, Perancis, Sepanyol, Jerman dan Amerika Syarikat terlibat dalam persaingan imperialisme.","Kawasan di Alam Melayu penting kerana kedudukan strategik dan kekayaan hasil bumi.","Kuasa Barat menganggap keluasan tanah jajahan melambangkan kekuatan dan sanjungan."] },
        { title: "Kata kunci", bulletPoints: ["imperialisme","tanah jajahan","persaingan kuasa Barat","bahan mentah","pasaran"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Brunei","Sultan Sulu"] },
        { title: "Tarikh penting", bulletPoints: ["1843: serangan penduduk tempatan ke atas kapal British di Sabah"] },
        { title: "Tempat penting", bulletPoints: ["Alam Melayu","Sabah","Sarawak","Kepulauan Melayu","Filipina"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Keperluan bahan mentah","Kepentingan laluan perdagangan","Persaingan kuasa imperialis","Prestij tanah jajahan"] },
        { title: "Kesan", bulletPoints: ["Peluasan kuasa Barat semakin agresif","Negeri tempatan berhadapan ancaman kedaulatan","Kuasa Barat mula menggunakan pelbagai strategi"] },
        { title: "Kepentingan", bulletPoints: ["Murid perlu memahami persaingan kuasa Barat sebagai faktor luaran yang menggugat kedaulatan negara."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Persaingan Barat membawa kepada strategi penguasaan seperti perjanjian, manipulasi dan ugutan."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Kedudukan Alam Melayu di antara India dan China menjadikannya rebutan kuasa Barat.","Abad ke-19: persaingan imperialisme semakin ketara selepas perkembangan industri Barat."] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "1.4 Perbezaan Strategi Kuasa Barat untuk Menguasai Negara Kita",
      subsections: [
        { title: "Ringkasan", content: "Perbezaan Strategi Kuasa Barat untuk Menguasai Negara Kita menerangkan kuasa barat menggunakan strategi perjanjian, pakatan, manipulasi, ugutan, serangan fizikal dan pajakan. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Kuasa Barat menggunakan strategi perjanjian, pakatan, manipulasi, ugutan, serangan fizikal dan pajakan.","British menggunakan perjanjian untuk mendapatkan Pulau Pinang, Singapura dan Melaka.","Belanda dan British memeterai Perjanjian London 1824 untuk menyelesaikan pertikaian di Alam Melayu.","Strategi pajakan dan perjanjian turut digunakan di Sabah dan Sarawak."] },
        { title: "Kata kunci", bulletPoints: ["perjanjian","pakatan","manipulasi","ugutan","serangan fizikal","pajakan"] },
        { title: "Tokoh penting", bulletPoints: ["Francis Light","Stamford Raffles","John Crawfurd","James Brooke"] },
        { title: "Tarikh penting", bulletPoints: ["1786: British menduduki Pulau Pinang","1819: perjanjian awal Singapura","1824: Perjanjian London","1824: Perjanjian British di Singapura"] },
        { title: "Tempat penting", bulletPoints: ["Pulau Pinang","Singapura","Melaka","Naning","Sarawak","Sabah"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian London 1824; Perjanjian 6 Februari 1819; Perjanjian 2 Ogos 1824"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["British mahukan petempatan strategik","Belanda mahu melindungi kepentingan di Alam Melayu","Pemerintah tempatan menghadapi tekanan politik dan keselamatan"] },
        { title: "Kesan", bulletPoints: ["Kedaulatan tempatan terjejas","British menguasai petempatan strategik","Naning dianggap sebahagian Melaka oleh British selepas Perjanjian London"] },
        { title: "Kepentingan", bulletPoints: ["Menunjukkan perlunya berwaspada terhadap anasir luar dan strategi kuasa asing."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Strategi penguasaan Barat menjadi asas kepada pembentukan Negeri-negeri Selat dan campur tangan seterusnya."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta Naning dan Melaka menerangkan bagaimana Perjanjian London digunakan British untuk menuntut Naning sebagai sebahagian Melaka.","1786 Pulau Pinang","1819 Singapura","1824 Perjanjian London dan pengukuhan British di Singapura"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "Rumusan Bab",
      subsections: [
        { title: "Imbas Kembali", bulletPoints: ["1.1: kestabilan, kemakmuran, sistem beraja, perundangan","1.2: rempah-ratus, SHTI, VOC, Revolusi Perindustrian","1.3: imperialisme, tanah jajahan, persaingan kuasa Barat, bahan mentah","1.4: perjanjian, pakatan, manipulasi, ugutan"] },
        { title: "Kata Kunci Peperiksaan", bulletPoints: ["kestabilan","kemakmuran","sistem beraja","perundangan","hubungan luar","ekonomi tradisional","rempah-ratus","SHTI","VOC","Revolusi Perindustrian","Terusan Suez","kapal wap","telegraf","imperialisme","tanah jajahan","persaingan kuasa Barat","bahan mentah","pasaran","perjanjian","pakatan","manipulasi","ugutan","serangan fizikal","pajakan"] },
      ],
    }
  ],
};
