import type { QuizQuestion } from "@/data/types";

export const scienceF1C3QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f1-c3-bm-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud homeostasis?",
    options: [
      "Penghasilan tenaga oleh badan",
      "Pengekalan persekitaran dalaman badan yang stabil",
      "Proses pembiakan organisma",
      "Pergerakan badan terhadap rangsangan",
    ],
    answerIndex: 1,
    explanation: "Homeostasis ialah proses mengekalkan persekitaran dalaman badan supaya seimbang dan stabil.",
  },
  {
    id: "sci-f1-c3-bm-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah homeostasis penting kepada organisma?",
    options: [
      "Supaya organisma tidak perlu makan",
      "Supaya proses hidup berjalan dengan lancar",
      "Supaya badan sentiasa menjadi lebih besar",
      "Supaya tumbuhan tidak memerlukan cahaya",
    ],
    answerIndex: 1,
    explanation: "Homeostasis menyediakan keadaan optimum supaya proses hidup dan metabolisme sel dapat berlaku dengan baik.",
  },
  {
    id: "sci-f1-c3-bm-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah contoh persekitaran dalaman badan?",
    options: ["Warna pakaian", "Suhu badan dan kandungan air", "Jenis makanan di kantin", "Saiz kasut"],
    answerIndex: 1,
    explanation: "Persekitaran dalaman termasuk keadaan dalam badan seperti suhu badan dan kandungan air.",
  },
  {
    id: "sci-f1-c3-bm-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud keadaan stabil dan seimbang dalam homeostasis?",
    options: [
      "Keadaan badan berubah tanpa kawalan",
      "Keadaan dalaman badan dikekalkan dalam julat normal",
      "Organisma berhenti bergerak",
      "Badan tidak menghasilkan haba",
    ],
    answerIndex: 1,
    explanation: "Keadaan stabil bermaksud keadaan dalaman badan dikawal supaya kekal dalam julat yang sesuai.",
  },
  {
    id: "sci-f1-c3-bm-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Organ manakah bertindak sebagai pusat kawalan dalam homeostasis manusia?",
    options: ["Perut", "Otak", "Paru-paru", "Kulit"],
    answerIndex: 1,
    explanation: "Otak bertindak sebagai pusat kawalan yang mengesan perubahan dan menghantar arahan pembetulan.",
  },
  {
    id: "sci-f1-c3-bm-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah suhu badan normal manusia?",
    options: ["27°C", "32°C", "37°C", "45°C"],
    answerIndex: 2,
    explanation: "Suhu badan normal manusia adalah kira-kira 37°C.",
  },
  {
    id: "sci-f1-c3-bm-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah yang berlaku kepada salur darah kulit dalam persekitaran panas?",
    options: ["Salur darah mengembang", "Salur darah mengecut", "Salur darah tertutup", "Salur darah menjadi keras"],
    answerIndex: 0,
    explanation: "Dalam persekitaran panas, salur darah mengembang supaya lebih banyak haba dapat dibebaskan.",
  },
  {
    id: "sci-f1-c3-bm-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah fungsi peluh dalam persekitaran panas?",
    options: [
      "Meningkatkan suhu badan",
      "Menyejukkan badan apabila peluh mengewap",
      "Menghasilkan air kencing",
      "Menutup stoma",
    ],
    answerIndex: 1,
    explanation: "Peluh mengewap dari kulit dan membantu membebaskan haba daripada badan.",
  },
  {
    id: "sci-f1-c3-bm-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah keadaan bulu roma manusia dalam persekitaran panas?",
    options: ["Bulu roma menegak", "Bulu roma condong pada kulit", "Bulu roma menjadi lebih panjang", "Bulu roma menghasilkan peluh"],
    answerIndex: 1,
    explanation: "Dalam persekitaran panas, bulu roma condong pada kulit untuk mengurangkan perangkap haba.",
  },
  {
    id: "sci-f1-c3-bm-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah yang berlaku kepada salur darah kulit dalam persekitaran sejuk?",
    options: ["Salur darah mengembang", "Salur darah mengecut", "Salur darah pecah", "Salur darah menghasilkan peluh"],
    answerIndex: 1,
    explanation: "Dalam persekitaran sejuk, salur darah mengecut untuk mengurangkan kehilangan haba.",
  },
  {
    id: "sci-f1-c3-bm-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah manusia menggigil dalam persekitaran sejuk?",
    options: ["Untuk menjana haba", "Untuk menghasilkan lebih air kencing", "Untuk menutup stoma", "Untuk mengurangkan metabolisme"],
    answerIndex: 0,
    explanation: "Menggigil melibatkan pengecutan otot yang cepat untuk menghasilkan haba.",
  },
  {
    id: "sci-f1-c3-bm-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Organ manakah mengawal kandungan air dengan menghasilkan air kencing?",
    options: ["Ginjal", "Jantung", "Peparu", "Usus kecil"],
    answerIndex: 0,
    explanation: "Ginjal mengawal kandungan air badan dengan menghasilkan lebih atau kurang air kencing.",
  },
  {
    id: "sci-f1-c3-bm-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah yang berlaku apabila kandungan air dalam badan tinggi?",
    options: ["Ginjal menghasilkan lebih banyak air kencing", "Ginjal menghasilkan kurang air kencing", "Badan mula menggigil", "Stoma tertutup"],
    answerIndex: 0,
    explanation: "Apabila kandungan air tinggi, ginjal menghasilkan lebih banyak air kencing untuk membuang air berlebihan.",
  },
  {
    id: "sci-f1-c3-bm-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah transpirasi?",
    options: [
      "Kehilangan wap air daripada tumbuhan melalui stoma",
      "Penghasilan makanan oleh akar",
      "Pernafasan haiwan melalui spirakel",
      "Penghasilan peluh oleh kulit",
    ],
    answerIndex: 0,
    explanation: "Transpirasi ialah kehilangan air dalam bentuk wap air daripada tumbuhan, terutamanya melalui stoma.",
  },
  {
    id: "sci-f1-c3-bm-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah fungsi sel pengawal?",
    options: ["Mengawal pembukaan dan penutupan stoma", "Menghasilkan peluh", "Menghasilkan air kencing", "Mengawal bulu roma manusia"],
    answerIndex: 0,
    explanation: "Sel pengawal mengawal sama ada stoma terbuka atau tertutup.",
  },
  {
    id: "sci-f1-c3-bm-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah mekanisme pembetulan dalam homeostasis?",
    options: [
      "Tindak balas yang mengembalikan keadaan badan kepada normal",
      "Proses yang menjadikan badan lebih panas sahaja",
      "Proses menghasilkan makanan dalam daun",
      "Perubahan yang tidak dapat dikawal oleh badan",
    ],
    answerIndex: 0,
    explanation: "Mekanisme pembetulan ialah tindak balas badan untuk mengembalikan keadaan dalaman kepada julat normal.",
  },
  {
    id: "sci-f1-c3-bm-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Antara berikut, yang manakah tindak balas lengkap badan dalam persekitaran panas?",
    options: [
      "Menggigil, salur darah mengecut, bulu roma menegak",
      "Berpeluh, salur darah mengembang, bulu roma condong pada kulit",
      "Kurang peluh, salur darah mengecut, metabolisme meningkat",
      "Dahaga, ginjal hasilkan kurang air kencing, bulu roma menegak",
    ],
    answerIndex: 1,
    explanation: "Dalam cuaca panas, badan berpeluh, salur darah mengembang dan bulu roma condong pada kulit untuk membebaskan haba.",
  },
  {
    id: "sci-f1-c3-bm-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Antara berikut, yang manakah tindak balas badan dalam persekitaran sejuk?",
    options: [
      "Salur darah mengembang dan banyak peluh dihasilkan",
      "Bulu roma condong pada kulit dan metabolisme menurun",
      "Salur darah mengecut, bulu roma menegak dan menggigil",
      "Stoma terbuka dan transpirasi meningkat",
    ],
    answerIndex: 2,
    explanation: "Dalam cuaca sejuk, badan mengurangkan kehilangan haba melalui pengecutan salur darah, bulu roma menegak dan menggigil.",
  },
  {
    id: "sci-f1-c3-bm-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah hubungan antara metabolisme dan suhu sejuk dalam manusia?",
    options: [
      "Metabolisme meningkat untuk menghasilkan lebih haba",
      "Metabolisme berhenti sepenuhnya",
      "Metabolisme menurun untuk menyejukkan badan",
      "Metabolisme hanya berlaku dalam tumbuhan",
    ],
    answerIndex: 0,
    explanation: "Dalam keadaan sejuk, metabolisme meningkat supaya badan dapat menghasilkan lebih banyak haba.",
  },
  {
    id: "sci-f1-c3-bm-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah yang berlaku apabila kandungan air badan rendah selepas banyak berpeluh?",
    options: [
      "Ginjal menghasilkan lebih banyak air kencing",
      "Ginjal menghasilkan kurang air kencing dan badan berasa dahaga",
      "Salur darah mengembang untuk membuang air",
      "Stoma terbuka pada kulit manusia",
    ],
    answerIndex: 1,
    explanation: "Apabila air badan rendah, ginjal menghasilkan kurang air kencing dan rasa dahaga mendorong kita minum air.",
  },
  {
    id: "sci-f1-c3-bm-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Bagaimanakah kucing menyejukkan badannya dalam cuaca panas?",
    options: ["Menjilat bulu", "Menutup spirakel", "Menghasilkan air kencing", "Menutup stoma"],
    answerIndex: 0,
    explanation: "Kucing menjilat bulu; air liur yang mengewap membantu menyejukkan badan.",
  },
  {
    id: "sci-f1-c3-bm-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Bagaimanakah anjing mengurangkan haba badan?",
    options: ["Menjelirkan lidah dan tercungap-cungap", "Menutup stoma", "Menghasilkan lendir", "Menegakkan bulu roma sahaja"],
    answerIndex: 0,
    explanation: "Anjing menjelirkan lidah dan tercungap-cungap supaya penyejatan dapat menyejukkan badan.",
  },
  {
    id: "sci-f1-c3-bm-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah siput menghasilkan lendir dan mencari tempat lembap?",
    options: ["Untuk mengelakkan kehilangan air berlebihan", "Untuk meningkatkan suhu badan", "Untuk menghasilkan peluh", "Untuk menutup salur darah"],
    answerIndex: 0,
    explanation: "Lendir dan tempat lembap membantu siput mengekalkan air badan dan mengelakkan kekeringan.",
  },
  {
    id: "sci-f1-c3-bm-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah fungsi lapisan lilin dan spirakel pada lebah?",
    options: [
      "Mengurangkan kehilangan air",
      "Menghasilkan lebih banyak peluh",
      "Mengawal pembukaan stoma",
      "Meningkatkan air kencing",
    ],
    answerIndex: 0,
    explanation: "Lapisan lilin dan penutupan spirakel membantu lebah mengurangkan kehilangan air.",
  },
  {
    id: "sci-f1-c3-bm-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah yang berlaku kepada stoma pada waktu siang?",
    options: [
      "Stoma terbuka untuk pertukaran gas dan transpirasi",
      "Stoma sentiasa tertutup sepanjang hari",
      "Stoma menghasilkan air kencing",
      "Stoma menyebabkan manusia berpeluh",
    ],
    answerIndex: 0,
    explanation: "Pada waktu siang, stoma biasanya terbuka untuk pertukaran gas dan transpirasi.",
  },
  {
    id: "sci-f1-c3-bm-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Hard",
    question: "Seorang murid bermain bola di bawah matahari dan banyak berpeluh. Apakah tindak balas homeostasis yang paling sesuai?",
    options: [
      "Ginjal menghasilkan kurang air kencing dan murid berasa dahaga",
      "Ginjal menghasilkan lebih banyak air kencing dan murid tidak perlu minum",
      "Bulu roma menegak untuk memerangkap haba",
      "Stoma pada kulit tertutup untuk mengurangkan air",
    ],
    answerIndex: 0,
    explanation: "Selepas banyak berpeluh, kandungan air badan menurun, jadi ginjal menghasilkan kurang air kencing dan rasa dahaga berlaku.",
  },
  {
    id: "sci-f1-c3-bm-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah stoma tumbuhan tertutup semasa cuaca terlalu panas?",
    options: [
      "Untuk mengurangkan kehilangan air dan mengelakkan layu",
      "Untuk meningkatkan kehilangan air sebanyak mungkin",
      "Untuk menghentikan semua proses hidup tumbuhan",
      "Untuk menghasilkan lebih banyak mineral",
    ],
    answerIndex: 0,
    explanation: "Dalam cuaca terlalu panas, stoma tertutup untuk mengurangkan kehilangan air supaya tumbuhan tidak mudah layu.",
  },
  {
    id: "sci-f1-c3-bm-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Hard",
    question: "Seekor cicak berada di tempat yang sejuk dan menjadi kurang aktif. Apakah penerangan yang paling sesuai?",
    options: [
      "Metabolisme cicak menurun kerana cicak ialah haiwan berdarah sejuk",
      "Cicak menghasilkan peluh yang banyak",
      "Ginjal cicak menghasilkan lebih banyak air kencing",
      "Stoma cicak tertutup untuk menjimatkan air",
    ],
    answerIndex: 0,
    explanation: "Cicak ialah haiwan berdarah sejuk; apabila suhu persekitaran rendah, metabolisme dan aktiviti badannya menurun.",
  },
  {
    id: "sci-f1-c3-bm-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Hard",
    question: "Jika salur darah tidak mengembang dalam cuaca panas, apakah kesan yang mungkin berlaku?",
    options: [
      "Badan sukar membebaskan haba dan suhu badan boleh meningkat",
      "Badan menghasilkan kurang haba dengan serta-merta",
      "Ginjal berhenti berfungsi sepenuhnya",
      "Tumbuhan kehilangan semua stomanya",
    ],
    answerIndex: 0,
    explanation: "Pengembangan salur darah membantu membebaskan haba. Jika tidak berlaku, badan lebih sukar menyejukkan diri.",
  },
  {
    id: "sci-f1-c3-bm-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "bm",
    difficulty: "Hard",
    question: "Pilih pasangan organisma dan tindak balas homeostasis yang betul.",
    options: [
      "Anjing - menutup stoma semasa panas",
      "Lebah - menutup spirakel untuk mengurangkan kehilangan air",
      "Manusia - menghasilkan lendir pada kulit untuk kekal lembap",
      "Tumbuhan - menggigil untuk menjana haba",
    ],
    answerIndex: 1,
    explanation: "Lebah boleh menutup spirakel dan mempunyai lapisan lilin untuk mengurangkan kehilangan air.",
  },
];
