import type { QuizQuestion } from "@/data/types";

export const scienceF1C3QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f1-c3-dlp-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is homeostasis?",
    options: [
      "Production of energy by the body",
      "Maintenance of a stable internal environment",
      "Reproduction process of organisms",
      "Body movement towards stimuli",
    ],
    answerIndex: 1,
    explanation: "Homeostasis is the process of maintaining a balanced and stable internal environment.",
  },
  {
    id: "sci-f1-c3-dlp-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "Why is homeostasis important to living organisms?",
    options: [
      "It ensures that internal conditions change with every change in the external environment",
      "It provides suitable internal conditions for cells to carry out metabolic processes efficiently",
      "It keeps body temperature the same as environmental temperature so that cells do not need to produce heat",
      "It prevents all internal changes, including those needed during physical activity",
    ],
    answerIndex: 1,
    explanation: "Homeostasis maintains suitable internal conditions so that cells, enzymes and metabolic processes can function efficiently.",
  },
  {
    id: "sci-f1-c3-dlp-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which is an example of the body's internal environment?",
    options: ["Clothing colour", "Body temperature and water content", "The weather outside", "Shoe size"],
    answerIndex: 1,
    explanation: "The internal environment includes conditions inside the body such as temperature and water content.",
  },
  {
    id: "sci-f1-c3-dlp-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What does a stable and balanced condition mean in homeostasis?",
    options: [
      "The body changes without control",
      "Internal conditions are kept within a normal range",
      "The organism stops moving",
      "The body does not produce heat",
    ],
    answerIndex: 1,
    explanation: "A stable condition means the internal environment is controlled within a suitable normal range.",
  },
  {
    id: "sci-f1-c3-dlp-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which organ acts as the control centre in human homeostasis?",
    options: ["Stomach", "Brain", "Lungs", "Skin"],
    answerIndex: 1,
    explanation: "The brain acts as a control centre that detects changes and sends corrective instructions.",
  },
  {
    id: "sci-f1-c3-dlp-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is the normal human body temperature?",
    options: ["27°C", "32°C", "37°C", "45°C"],
    answerIndex: 2,
    explanation: "The normal human body temperature is about 37°C.",
  },
  {
    id: "sci-f1-c3-dlp-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What happens to blood vessels in the skin in a hot environment?",
    options: ["They dilate", "They constrict", "They close completely", "They become hard"],
    answerIndex: 0,
    explanation: "In a hot environment, blood vessels dilate so more heat can be released.",
  },
  {
    id: "sci-f1-c3-dlp-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is the function of sweating in a hot environment?",
    options: [
      "To increase body temperature",
      "To cool the body when sweat evaporates",
      "To produce urine",
      "To close stomata",
    ],
    answerIndex: 1,
    explanation: "Sweat evaporates from the skin and helps remove heat from the body.",
  },
  {
    id: "sci-f1-c3-dlp-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What happens to fine hairs on human skin in a hot environment?",
    options: ["They stand erect", "They lie flat", "They become longer", "They produce sweat"],
    answerIndex: 1,
    explanation: "In a hot environment, fine hairs lie flat to reduce heat trapping.",
  },
  {
    id: "sci-f1-c3-dlp-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What happens to blood vessels in the skin in a cold environment?",
    options: ["They dilate", "They constrict", "They burst", "They produce sweat"],
    answerIndex: 1,
    explanation: "In a cold environment, blood vessels constrict to reduce heat loss.",
  },
  {
    id: "sci-f1-c3-dlp-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "Why does a person shiver when exposed to a very cold environment?",
    options: [
      "Muscle contraction and relaxation reduce heat production",
      "Muscle contraction and relaxation trap a layer of air at the skin",
      "Muscle contraction and relaxation help to produce heat",
      "Muscle contraction and relaxation increase heat loss through the skin",
    ],
    answerIndex: 2,
    explanation: "Rapid contraction and relaxation of skeletal muscles during shivering produce heat and help return body temperature towards the normal range.",
  },
  {
    id: "sci-f1-c3-dlp-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which organ regulates water content by producing urine?",
    options: ["Kidney", "Heart", "Lung", "Small intestine"],
    answerIndex: 0,
    explanation: "Kidneys regulate body water content by producing more or less urine.",
  },
  {
    id: "sci-f1-c3-dlp-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "After a person drinks a large amount of water, what usually happens?",
    options: [
      "Less water is removed through urine so that body water content continues to increase",
      "More excess water is removed through urine",
      "All excess water is stored in the body without any change in urine production",
      "Excess water is removed mainly through sweat even when the body is not overheated",
    ],
    answerIndex: 1,
    explanation: "The body regulates its water content to maintain balance. When there is excess water, more water is removed through urine.",
  },
  {
    id: "sci-f1-c3-dlp-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is transpiration?",
    options: [
      "Loss of water vapour from plants through stomata",
      "Production of food by roots",
      "Breathing through spiracles in animals",
      "Production of sweat by skin",
    ],
    answerIndex: 0,
    explanation: "Transpiration is the loss of water vapour from plants, mainly through stomata.",
  },
  {
    id: "sci-f1-c3-dlp-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is the function of guard cells?",
    options: ["Control the opening and closing of stomata", "Produce sweat", "Produce urine", "Control human fine hairs"],
    answerIndex: 0,
    explanation: "Guard cells control whether stomata are open or closed.",
  },
  {
    id: "sci-f1-c3-dlp-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is a corrective mechanism in homeostasis?",
    options: [
      "A response that returns body conditions to normal",
      "A process that only makes the body hotter",
      "A process that produces food in leaves",
      "A change that cannot be controlled by the body",
    ],
    answerIndex: 0,
    explanation: "A corrective mechanism is a body response that returns internal conditions to the normal range.",
  },
  {
    id: "sci-f1-c3-dlp-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "A student is standing on a field during a hot afternoon. Which body response helps to lower the student's body temperature?",
    options: [
      "Blood vessels constrict and the student shivers",
      "Sweating increases and blood vessels dilate",
      "Sweating decreases and body hairs stand upright",
      "Blood vessels constrict and body hairs stand upright",
    ],
    answerIndex: 1,
    explanation: "Sweat evaporates from the skin and removes heat, while dilation of blood vessels increases heat loss through the skin.",
  },
  {
    id: "sci-f1-c3-dlp-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "Which is the correct body response in a cold environment?",
    options: [
      "Blood vessels dilate and more sweat is produced",
      "Fine hairs lie flat and metabolism decreases",
      "Blood vessels constrict, fine hairs stand erect and shivering occurs",
      "Stomata open and transpiration increases",
    ],
    answerIndex: 2,
    explanation: "In cold conditions, the body reduces heat loss through blood vessel constriction, erect fine hairs and shivering.",
  },
  {
    id: "sci-f1-c3-dlp-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the link between metabolism and cold conditions in humans?",
    options: [
      "Metabolism increases to produce more heat",
      "Metabolism stops completely",
      "Metabolism decreases to cool the body",
      "Metabolism only happens in plants",
    ],
    answerIndex: 0,
    explanation: "In cold conditions, metabolism increases so the body can produce more heat.",
  },
  {
    id: "sci-f1-c3-dlp-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "What happens when body water content is low after heavy sweating?",
    options: [
      "Kidneys produce more urine",
      "Kidneys produce less urine and thirst is triggered",
      "Blood vessels dilate to remove water",
      "Stomata open on human skin",
    ],
    answerIndex: 1,
    explanation: "When body water is low, kidneys produce less urine and thirst encourages us to drink water.",
  },
  {
    id: "sci-f1-c3-dlp-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "How does a cat cool its body in hot weather?",
    options: ["It licks its fur", "It closes spiracles", "It produces urine", "It closes stomata"],
    answerIndex: 0,
    explanation: "A cat licks its fur; evaporation of saliva helps cool the body.",
  },
  {
    id: "sci-f1-c3-dlp-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "A dog pants and sticks out its tongue on a hot day. What is the purpose of this response?",
    options: [
      "To increase heat loss from the body",
      "To increase heat production through muscle contraction",
      "To reduce heat loss by trapping air",
      "To reduce heat loss by slowing down water evaporation",
    ],
    answerIndex: 0,
    explanation: "Panting increases heat loss and helps the dog regulate its body temperature.",
  },
  {
    id: "sci-f1-c3-dlp-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "Why do snails produce mucus and move to damp places?",
    options: ["To avoid excessive water loss", "To increase body temperature", "To produce sweat", "To close blood vessels"],
    answerIndex: 0,
    explanation: "Mucus and damp places help snails keep body moisture and prevent drying out.",
  },
  {
    id: "sci-f1-c3-dlp-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the function of the waxy layer and spiracles in bees?",
    options: ["Reduce water loss", "Produce more sweat", "Control stomata opening", "Increase urine production"],
    answerIndex: 0,
    explanation: "The waxy layer and closing of spiracles help bees reduce water loss.",
  },
  {
    id: "sci-f1-c3-dlp-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "What happens to stomata during the day?",
    options: [
      "Stomata open for gas exchange and transpiration",
      "Stomata stay closed all day",
      "Stomata produce urine",
      "Stomata cause humans to sweat",
    ],
    answerIndex: 0,
    explanation: "During the day, stomata usually open for gas exchange and transpiration.",
  },
  {
    id: "sci-f1-c3-dlp-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "A student's pulse rate increases after jogging. What is the best explanation for this change?",
    options: [
      "Body cells require more oxygen and nutrients during physical activity",
      "Body cells require less oxygen because muscles obtain energy from body heat",
      "The heart needs to reduce the nutrient supply so that body temperature does not rise",
      "The heart needs to reduce blood flow to the muscles to conserve energy",
    ],
    answerIndex: 0,
    explanation: "During physical activity, muscle cells require more energy. The heart beats faster to increase the supply of oxygen and other substances needed by the cells.",
  },
  {
    id: "sci-f1-c3-dlp-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Medium",
    question: "During very hot weather, the stomata of a plant may close. Why is this response important?",
    options: [
      "To increase water loss through transpiration",
      "To reduce water loss through transpiration",
      "To increase carbon dioxide intake for photosynthesis",
      "To increase heat loss through water evaporation",
    ],
    answerIndex: 1,
    explanation: "Closing the stomata reduces the loss of water vapour through transpiration when environmental conditions are very hot.",
  },
  {
    id: "sci-f1-c3-dlp-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Hard",
    question: "A lizard is in a cold place and becomes less active. What is the best explanation?",
    options: [
      "Its metabolism decreases because it is a cold-blooded animal",
      "It produces a lot of sweat",
      "Its kidneys produce more urine",
      "Its stomata close to save water",
    ],
    answerIndex: 0,
    explanation: "A lizard is cold-blooded; when the surrounding temperature is low, its metabolism and activity decrease.",
  },
  {
    id: "sci-f1-c3-dlp-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Hard",
    question: "If blood vessels do not dilate in hot weather, what may happen?",
    options: [
      "The body has difficulty releasing heat and body temperature may rise",
      "The body immediately produces less heat",
      "Kidneys stop working completely",
      "Plants lose all their stomata",
    ],
    answerIndex: 0,
    explanation: "Blood vessel dilation helps release heat. Without it, the body has more difficulty cooling down.",
  },
  {
    id: "sci-f1-c3-dlp-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 3",
    lang: "dlp",
    difficulty: "Hard",
    question: "Choose the correct organism and homeostatic response pair.",
    options: [
      "Dog - closes stomata during hot weather",
      "Bee - closes spiracles to reduce water loss",
      "Human - produces mucus on the skin to stay moist",
      "Plant - shivers to generate heat",
    ],
    answerIndex: 1,
    explanation: "Bees can close their spiracles and have a waxy layer to reduce water loss.",
  },
];
