import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c5-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 5",
    lang: "bm",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C5QuizzesBM: QuizQuestion[] = buildQuiz([
  ["Easy", "Apakah hipotenus dalam segi tiga bersudut tegak?", ["Sisi terpanjang, bertentangan sudut 90°", "Sisi terpendek", "Sisi bersebelahan sudut tirus", "Sisi mendatar sahaja"], 0],
  ["Easy", "Apakah formula sin θ?", ["Sisi bertentangan / hipotenus", "Sisi bersebelahan / hipotenus", "Sisi bertentangan / sisi bersebelahan", "Hipotenus / sisi bertentangan"], 0],
  ["Easy", "Apakah formula kos θ?", ["Sisi bersebelahan / hipotenus", "Sisi bertentangan / hipotenus", "Sisi bertentangan / sisi bersebelahan", "Hipotenus / sisi bersebelahan"], 0],
  ["Easy", "Apakah formula tan θ?", ["Sisi bertentangan / sisi bersebelahan", "Sisi bersebelahan / hipotenus", "Sisi bertentangan / hipotenus", "Hipotenus / sisi bertentangan"], 0],
  ["Easy", "Apakah formula tan θ dalam sebutan sin dan kos?", ["tan θ = sin θ / kos θ", "tan θ = kos θ / sin θ", "tan θ = sin θ x kos θ", "tan θ = sin θ + kos θ"], 0],
  ["Easy", "Apakah nilai sin 30°?", ["1/2", "√3/2", "1", "1/√2"], 0],
  ["Easy", "Apakah nilai kos 60°?", ["1/2", "√3/2", "1", "0"], 0],
  ["Easy", "Apakah nilai tan 45°?", ["1", "0", "√3", "1/√3"], 0],
  ["Easy", "Apakah nilai sin 45°?", ["1/√2", "1/2", "√3/2", "1"], 0],
  ["Easy", "Apakah nilai tan 30°?", ["1/√3", "√3", "1", "1/2"], 0],
  ["Easy", "Apakah nilai tan 60°?", ["√3", "1/√3", "1", "√3/2"], 0],
  ["Easy", "1° bersamaan berapa minit?", ["60 minit", "100 minit", "30 minit", "1 minit"], 0],
  ["Easy", "Tukar 43° 30' kepada darjah.", ["43.5°", "43.3°", "44°", "43.03°"], 0],
  ["Easy", "Apa yang terjadi pada sin θ apabila sudut θ bertambah dari 0° ke 90°?", ["Bertambah ke 1", "Berkurang ke 0", "Tetap sama", "Berkurang ke -1"], 0],
  ["Easy", "Apa yang terjadi pada kos θ apabila sudut θ bertambah dari 0° ke 90°?", ["Berkurang ke 0", "Bertambah ke 1", "Tetap sama", "Bertambah tanpa had"], 0],
  ["Easy", "Apa yang terjadi pada tan θ apabila sudut θ menghampiri 90°?", ["Bertambah ke infiniti", "Berkurang ke 0", "Tetap 1", "Menjadi negatif"], 0],
  ["Easy", "PQR bersudut tegak, PQ=15cm, QR=8cm. Hitung PR.", ["17 cm", "23 cm", "7 cm", "13 cm"], 0],
  ["Easy", "Daripada soalan di atas, hitung sin∠PRQ.", ["15/17", "8/17", "8/15", "17/15"], 0],
  ["Easy", "Jika sin θ=0.6 dan kos θ=0.8, hitung tan θ.", ["0.75", "1.33", "0.48", "1.4"], 0],
  ["Easy", "Apakah mod kalkulator yang betul untuk kira trigonometri darjah?", ["Mod Deg (darjah)", "Mod Rad (radian)", "Mod Grad", "Tidak penting"], 0],

  ["Medium", "Segi tiga PQR, PR=20cm, sin∠QPR=3/5. Hitung panjang QR.", ["12 cm", "16 cm", "20 cm", "8 cm"], 0],
  ["Medium", "Daripada soalan di atas, hitung PQ menggunakan Pythagoras.", ["16 cm (√(20²-12²))", "12 cm", "24 cm", "8 cm"], 0],
  ["Medium", "Daripada soalan di atas, hitung kos∠QPR.", ["4/5", "3/5", "3/4", "4/3"], 0],
  ["Medium", "Jika sin θ=3/8 dan tan θ=3/√55, hitung kos θ.", ["√55/8", "8/√55", "3/√55", "√55/3"], 0],
  ["Medium", "Hitung sin45°+kos45° tanpa kalkulator.", ["√2", "1", "2", "1/√2"], 0],
  ["Medium", "Hitung 3kos30°-2sin60°.", ["√3/2", "√3", "3√3/2", "0"], 0],
  ["Medium", "Hitung 2tan45°-2kos60°.", ["1", "2", "0", "1.5"], 0],
  ["Medium", "Hitung (2sin60°)(4kos30°)-4tan60°.", ["6-4√3", "6+4√3", "2-4√3", "4√3-6"], 0],
  ["Medium", "Tukar 30.2° kepada darjah dan minit.", ["30° 12'", "30° 20'", "30° 2'", "30° 30'"], 0],
  ["Medium", "Jika sin x=0.8377, hitung x.", ["56.9° atau 56° 54'", "33.1°", "60°", "45°"], 0],
  ["Medium", "Jika kos x=0.7021, hitung x.", ["45.4° atau 45° 24'", "44.6°", "30°", "60°"], 0],
  ["Medium", "Tangga PQR bersandar dinding 50°, tinggi QR=2.5m. Hitung panjang tangga PR.", ["3.26 m", "1.91 m", "2.5 m", "3.91 m"], 0],
  ["Medium", "Kuboid ABCDEFGH: BC=8cm, CH=5cm, HE=4cm. FG=EH. Hitung panjang CG.", ["√89 cm (≈9.43cm)", "13 cm", "√41 cm", "9 cm"], 0],
  ["Medium", "Daripada soalan di atas, hitung tan∠FCG.", ["4/√89", "√89/4", "5/4", "4/5"], 0],
  ["Medium", "Daripada soalan di atas, hitung ∠FCG.", ["22.98° atau 22°59'", "30°", "45°", "60°"], 0],
  ["Medium", "Tangga lipat segi tiga sama kaki PQR, T titik tengah PR, ∠PQR=38°, PR=1.4m. Hitung PQ.", ["Guna sin19°=0.7/PQ, PQ≈2.15m", "PQ=1.4m", "PQ=0.7m", "PQ=2.8m"], 0],
  ["Medium", "Aisyah lihat tiang lampu sudut dongak 55°, jarak mata-hujung tiang 145m. Hitung jarak mengufuk d.", ["d=145kos55°≈83.1m", "d=145sin55°≈118.8m", "d=145tan55°≈207m", "d=145m"], 0],
  ["Medium", "Kapal dilihat dari rumah api sudut tunduk 41°, jarak mengufuk 200m. Hitung tinggi rumah api h.", ["h=200tan41°≈173.9m", "h=200sin41°≈131.2m", "h=200kos41°≈151m", "h=200m"], 0],
  ["Medium", "PRS dengan PQR garis lurus, kos60°=0.5, PQ=10cm sudut QPS=30°. Hitung QR.", ["QR=5cm (kos60°=QR/10)", "QR=10cm", "QR=8.66cm", "QR=2.5cm"], 0],
  ["Medium", "Daripada soalan di atas, jika SR=√75cm dan PR=15cm, hitung PS.", ["PS≈17.32cm (√(75+225))", "PS=15cm", "PS=20cm", "PS=10cm"], 0],

  ["Hard", "Kuboid PQRSTUVW, PQ=12cm, QR=7cm. Hitung tan∠PQS (∠PQS dalam segi empat sama PSTU).", ["12/7 (anggaran, bergantung konfigurasi tepat)", "7/12", "1", "12/√193"], 0],
  ["Hard", "Daripada soalan di atas, hitung panjang QS (pepenjuru tapak) jika PQRS segi empat sama dengan PQ=12, QR=7.", ["QS=√(12²+7²)=√193≈13.89cm", "QS=19cm", "QS=12cm", "QS=7cm"], 0],
  ["Hard", "Heksagon sekata PQRSTU bersisi 6cm. Hitung ∠PTS (anggaran menggunakan sifat heksagon sekata).", ["30° (anggaran berdasarkan simetri heksagon)", "60°", "90°", "120°"], 0],
  ["Hard", "Daripada heksagon sekata bersisi 6cm, hitung panjang pepenjuru pendek PS (anggaran).", ["6√3 cm (anggaran pepenjuru pendek heksagon sekata)", "12 cm", "6 cm", "9 cm"], 0],
  ["Hard", "Segi empat tepat ABCD, AB=8cm, BC=16cm (2xAB), N titik tengah BC. Hitung BN.", ["8 cm (separuh BC)", "16 cm", "4 cm", "12 cm"], 0],
  ["Hard", "Daripada soalan di atas, jika MD=(1/4)AD dan AD=16cm, hitung AM.", ["12 cm (16-4)", "4 cm", "8 cm", "16 cm"], 0],
  ["Hard", "Hitung 8sin60°-3tan60° tanpa kalkulator.", ["4√3-3√3=√3 (8(√3/2)-3√3)", "5√3", "√3/2", "0"], 0],
  ["Hard", "Hitung (tan30°)(2kos30°)+6sin30°.", ["1+3=4 ((1/√3)(2)(√3/2)+6(1/2)=1+3)", "4√3", "1", "6"], 0],
  ["Hard", "Hitung (8kos45°)(sin60°)+(8sin45°)(kos30°).", ["4√6+4√6/√2 (anggaran pengiraan surd kompleks)", "16", "8√2", "4√3"], 0],
  ["Hard", "PRS dengan QR=RS=18cm, tan θ=3/4. Hitung panjang PQ jika θ=∠QPR.", ["PQ=24cm (18÷tan θ jika θ sudut yang sesuai; bergantung konfigurasi tepat rajah)", "PQ=18cm", "PQ=13.5cm", "PQ=30cm"], 0],
  ["Hard", "ABC bersudut tegak, AB=21cm, sin θ=3/5. Hitung panjang AC.", ["AC bergantung kedudukan θ; jika θ bertentangan AC, AC=AB x (sinθ/kosθ) atau guna nisbah sepadan", "AC=15.75cm", "AC=35cm", "AC=12.6cm"], 0],
  ["Hard", "Daripada soalan di atas, hitung nilai ∠BAC dalam darjah terdekat jika sin θ=3/5.", ["∠BAC=37° (sin⁻¹0.6≈36.87°, bundar ke 37°)", "53°", "30°", "60°"], 0],
  ["Hard", "Pintu gelangsar membentuk segi tiga, gunakan trigonometri untuk anggar sudut bukaan jika nisbah sisi 3:4:5.", ["θ=sin⁻¹(3/5)≈36.87° atau θ=kos⁻¹(4/5)≈36.87°", "θ=45°", "θ=60°", "θ=30°"], 0],
  ["Hard", "DPF garis lurus dalam DEF bersudut tegak, PE=5cm, x dan θ tidak diketahui secara langsung. Apakah strategi penyelesaian yang betul?", ["Kenal pasti segi tiga bersudut tegak kecil yang melibatkan PE dan sisi diketahui, gunakan Pythagoras dan nisbah trig berurutan", "Terus guna teorem sinus", "Terus guna teorem kosinus", "Anggap semua sudut 45°"], 0],
  ["Hard", "Mengapa nisbah trigonometri bagi sudut yang sama kekal sama walaupun saiz segi tiga berbeza?", ["Segi tiga adalah serupa (sudut sama, sisi berkadaran)", "Kerana hipotenus sentiasa sama panjang", "Kerana sudut 90° berubah", "Kebetulan sahaja"], 0],
]);
