import type { QuizQuestion } from "@/data/types";

export const scienceF1C5QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f1-c5-dlp-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is matter?",
    options: [
      "A substance that has mass and occupies space",
      "A substance without mass",
      "A form of light",
      "A type of sound",
    ],
    answerIndex: 0,
    explanation: "Matter is any substance that has mass and occupies space.",
  },
  {
    id: "sci-f1-c5-dlp-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Why is the air inside a balloon classified as matter?",
    options: [
      "Air has volume but no mass",
      "Air has a fixed shape and a fixed volume",
      "Air has mass and occupies space",
      "Air has mass but does not occupy space",
    ],
    answerIndex: 2,
    explanation: "Matter is anything that has mass and occupies space. Air has both of these properties.",
  },
  {
    id: "sci-f1-c5-dlp-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which of the following is non-matter?",
    options: ["Sound", "Rock", "Air", "Book"],
    answerIndex: 0,
    explanation: "Sound is non-matter because it has no mass and does not occupy space.",
  },
  {
    id: "sci-f1-c5-dlp-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is mass?",
    options: [
      "The quantity of matter in an object",
      "The space occupied by an object",
      "The temperature of an object",
      "The speed of an object",
    ],
    answerIndex: 0,
    explanation: "Mass is the quantity of matter in an object.",
  },
  {
    id: "sci-f1-c5-dlp-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "What does occupying space mean?",
    options: [
      "Having volume",
      "Cannot be seen",
      "Having no weight",
      "Producing light",
    ],
    answerIndex: 0,
    explanation: "An object that occupies space has volume.",
  },
  {
    id: "sci-f1-c5-dlp-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which of the following is a physical property of matter?",
    options: ["Melting point", "Flammability", "Rusting", "Decomposition"],
    answerIndex: 0,
    explanation: "Melting point is a physical property because it can be identified without forming a new substance.",
  },
  {
    id: "sci-f1-c5-dlp-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which of the following is a chemical property of matter?",
    options: ["Flammability", "Boiling point", "Density", "Solubility"],
    answerIndex: 0,
    explanation: "Flammability is a chemical property because burning changes a substance into new substances.",
  },
  {
    id: "sci-f1-c5-dlp-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which state of matter has a fixed shape and fixed volume?",
    options: ["Solid", "Liquid", "Gas", "Vapour"],
    answerIndex: 0,
    explanation: "A solid has a fixed shape and a fixed volume.",
  },
  {
    id: "sci-f1-c5-dlp-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which statement best describes the particles in a solid?",
    options: [
      "The particles are far apart and move freely in all directions",
      "The particles are closely packed but do not move at all",
      "The particles are closely packed and vibrate about fixed positions",
      "The particles are closely packed and move freely past one another",
    ],
    answerIndex: 2,
    explanation: "Particles in a solid are closely packed and vibrate about fixed positions.",
  },
  {
    id: "sci-f1-c5-dlp-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Which state of matter takes the shape of its container but has a fixed volume?",
    options: ["Liquid", "Solid", "Gas", "Light"],
    answerIndex: 0,
    explanation: "A liquid takes the shape of its container but has a fixed volume.",
  },
  {
    id: "sci-f1-c5-dlp-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "Why can gases be compressed more easily than solids and liquids?",
    options: [
      "There are large spaces between gas particles",
      "Gas particles are more closely packed than liquid particles",
      "Each gas particle becomes smaller when pressure is applied",
      "Each gas particle loses mass when pressure is applied",
    ],
    answerIndex: 0,
    explanation: "The large spaces between gas particles allow the particles to be pushed closer together when pressure is applied.",
  },
  {
    id: "sci-f1-c5-dlp-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is diffusion?",
    options: [
      "Movement of particles from high concentration to low concentration",
      "Change of solid into liquid",
      "An object sinking in water",
      "Production of a new substance",
    ],
    answerIndex: 0,
    explanation: "Diffusion occurs when particles move from an area of high concentration to an area of low concentration.",
  },
  {
    id: "sci-f1-c5-dlp-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "In which state of matter does diffusion happen the fastest?",
    options: ["Gas", "Liquid", "Solid", "Ice"],
    answerIndex: 0,
    explanation: "Diffusion is fastest in gases because gas particles move freely and rapidly.",
  },
  {
    id: "sci-f1-c5-dlp-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is the process of changing solid into liquid?",
    options: ["Melting", "Freezing", "Condensation", "Sublimation"],
    answerIndex: 0,
    explanation: "Melting is the process in which a solid changes into a liquid.",
  },
  {
    id: "sci-f1-c5-dlp-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Easy",
    question: "What is the formula for density?",
    options: ["Density = Mass / Volume", "Density = Volume / Mass", "Density = Mass x Temperature", "Density = Force / Area"],
    answerIndex: 0,
    explanation: "Density is calculated by dividing mass by volume.",
  },
  {
    id: "sci-f1-c5-dlp-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "Two substances have the same colour but different boiling points. Which property is most suitable for distinguishing between them?",
    options: [
      "Colour of the substances",
      "Boiling point",
      "Shape of the container",
      "Amount of substance",
    ],
    answerIndex: 1,
    explanation: "Boiling point is a physical property that can be used to identify and classify substances.",
  },
  {
    id: "sci-f1-c5-dlp-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "Why does gas take the shape and volume of its container?",
    options: [
      "Gas particles are far apart and move freely",
      "Gas particles are closely packed and fixed",
      "Gas has no particles",
      "Gas always becomes solid",
    ],
    answerIndex: 0,
    explanation: "Gas particles are far apart and move freely, so gas fills the whole container.",
  },
  {
    id: "sci-f1-c5-dlp-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "What happens to the particles of a solid when it is heated until it melts?",
    options: [
      "The particles release heat and vibrate more slowly about fixed positions",
      "The particles absorb heat, move more actively and eventually move past one another",
      "The particles absorb heat, become more closely packed and remain in fixed positions",
      "The particles release heat and become more orderly in their arrangement",
    ],
    answerIndex: 1,
    explanation: "As the solid is heated, its particles absorb heat energy and move more actively until the fixed arrangement of the solid can no longer be maintained.",
  },
  {
    id: "sci-f1-c5-dlp-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "What is the change from liquid to gas at boiling point called?",
    options: ["Boiling", "Freezing", "Condensation", "Melting"],
    answerIndex: 0,
    explanation: "Boiling occurs when a liquid changes into gas at its boiling point.",
  },
  {
    id: "sci-f1-c5-dlp-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "Water vapour forms water droplets on the outside of a cold glass. What happens to the water vapour particles?",
    options: [
      "They absorb heat, move faster and become further apart",
      "They release heat, move faster and become further apart",
      "They release heat, move more slowly and become closer together",
      "They absorb heat, move more slowly and become closer together",
    ],
    answerIndex: 2,
    explanation: "During condensation, a gas releases heat. Its particles lose kinetic energy, move more slowly and become closer together to form a liquid.",
  },
  {
    id: "sci-f1-c5-dlp-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "Which process absorbs heat?",
    options: ["Melting", "Freezing", "Condensation", "Gas to solid"],
    answerIndex: 0,
    explanation: "Melting absorbs heat to change a solid into a liquid.",
  },
  {
    id: "sci-f1-c5-dlp-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "Ice is melting at its melting point. Although heat continues to be supplied, its temperature remains constant for a period of time. Why?",
    options: [
      "The heat energy is used to overcome the forces of attraction between particles during the change of state",
      "The heat energy is used to increase the mass of each particle in the ice",
      "The heat energy is used to increase particle temperature without changing the arrangement",
      "The heat energy is no longer absorbed while any ice remains",
    ],
    answerIndex: 0,
    explanation: "During a change of state, the absorbed heat energy is used to overcome forces of attraction between particles rather than increase the temperature.",
  },
  {
    id: "sci-f1-c5-dlp-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "100 g of water is completely frozen into ice without any substance entering or leaving the container. What is the mass of the ice?",
    options: [
      "Less than 100 g",
      "More than 100 g",
      "0 g",
      "100 g",
    ],
    answerIndex: 3,
    explanation: "Mass remains unchanged during a physical change as long as no matter enters or leaves the system.",
  },
  {
    id: "sci-f1-c5-dlp-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "An object has a mass of 20 g and a volume of 10 cm3. What is its density?",
    options: ["2 g/cm3", "10 g/cm3", "20 g/cm3", "200 g/cm3"],
    answerIndex: 0,
    explanation: "Density = 20 g / 10 cm3 = 2 g/cm3.",
  },
  {
    id: "sci-f1-c5-dlp-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Medium",
    question: "Wet clothes become dry when they are left outside. Which process changes the water in the clothes into water vapour?",
    options: [
      "Condensation",
      "Evaporation",
      "Freezing",
      "Sublimation",
    ],
    answerIndex: 1,
    explanation: "Evaporation is the change of a liquid into a gas from the surface of the liquid.",
  },
  {
    id: "sci-f1-c5-dlp-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Hard",
    question: "Why does gas diffuse faster than solid?",
    options: [
      "Gas particles are far apart and move more freely",
      "Gas particles are arranged closely",
      "Gas has a fixed volume",
      "Solids do not have particles",
    ],
    answerIndex: 0,
    explanation: "Gas particles are far apart and move quickly, so diffusion occurs faster.",
  },
  {
    id: "sci-f1-c5-dlp-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Hard",
    question: "Why does ice float on water?",
    options: [
      "Ice is less dense than water",
      "Ice is denser than water",
      "Ice has no mass",
      "Water is non-matter",
    ],
    answerIndex: 0,
    explanation: "An object floats if it is less dense than the liquid. Ice is less dense than water.",
  },
  {
    id: "sci-f1-c5-dlp-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Hard",
    question: "If heat continues to be supplied to a liquid, what is the best prediction about its particles?",
    options: [
      "Particles move faster and may change into gas",
      "Particles become closer and fixed",
      "Particles disappear completely",
      "Particles change into sound",
    ],
    answerIndex: 0,
    explanation: "Heat increases particle kinetic energy. A liquid may change into gas through boiling or evaporation.",
  },
  {
    id: "sci-f1-c5-dlp-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Hard",
    question: "Ali wants to test whether a material burns easily. What type of property is being tested?",
    options: ["Chemical property", "Physical property", "Volume", "Mass only"],
    answerIndex: 0,
    explanation: "Flammability is a chemical property because burning produces new substances.",
  },
  {
    id: "sci-f1-c5-dlp-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "dlp",
    difficulty: "Hard",
    question: "An object sinks in water. What is the most suitable conclusion?",
    options: [
      "The object is denser than water",
      "The object is less dense than water",
      "The object is non-matter",
      "The object has no volume",
    ],
    answerIndex: 0,
    explanation: "An object that is denser than a liquid will sink.",
  },
];
