import type { QuizQuestion } from "@/data/types";

export const scienceF1C5QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f1-c5-bm-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud jirim?",
    options: [
      "Bahan yang mempunyai jisim dan memenuhi ruang",
      "Bahan yang tidak mempunyai jisim",
      "Tenaga yang boleh dilihat",
      "Cahaya dan bunyi",
    ],
    answerIndex: 0,
    explanation: "Jirim ialah bahan yang mempunyai jisim dan memenuhi ruang.",
  },
  {
    id: "sci-f1-c5-bm-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah udara di dalam belon dikategorikan sebagai jirim?",
    options: [
      "Udara mempunyai isi padu tetapi tidak mempunyai jisim",
      "Udara mempunyai bentuk dan isi padu yang tetap",
      "Udara mempunyai jisim dan memenuhi ruang",
      "Udara mempunyai jisim tetapi tidak memenuhi ruang",
    ],
    answerIndex: 2,
    explanation: "Jirim ialah sesuatu yang mempunyai jisim dan memenuhi ruang. Udara memenuhi kedua-dua ciri tersebut.",
  },
  {
    id: "sci-f1-c5-bm-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Antara berikut, yang manakah bukan jirim?",
    options: ["Bunyi", "Batu", "Udara", "Buku"],
    answerIndex: 0,
    explanation: "Bunyi bukan jirim kerana tidak mempunyai jisim dan tidak memenuhi ruang.",
  },
  {
    id: "sci-f1-c5-bm-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud jisim?",
    options: [
      "Kuantiti jirim dalam sesuatu objek",
      "Ruang yang dipenuhi objek",
      "Suhu sesuatu objek",
      "Kelajuan pergerakan objek",
    ],
    answerIndex: 0,
    explanation: "Jisim ialah kuantiti jirim dalam sesuatu objek.",
  },
  {
    id: "sci-f1-c5-bm-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud memenuhi ruang?",
    options: [
      "Mempunyai isi padu",
      "Tidak boleh dilihat",
      "Tidak mempunyai berat",
      "Menghasilkan cahaya",
    ],
    answerIndex: 0,
    explanation: "Objek yang memenuhi ruang mempunyai isi padu.",
  },
  {
    id: "sci-f1-c5-bm-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Antara berikut, yang manakah sifat fizik jirim?",
    options: ["Takat lebur", "Kebolehbakaran", "Pengaratan", "Penguraian"],
    answerIndex: 0,
    explanation: "Takat lebur ialah sifat fizik kerana boleh dikenal pasti tanpa menghasilkan bahan baharu.",
  },
  {
    id: "sci-f1-c5-bm-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Antara berikut, yang manakah sifat kimia jirim?",
    options: ["Kebolehbakaran", "Takat didih", "Ketumpatan", "Keterlarutan"],
    answerIndex: 0,
    explanation: "Kebolehbakaran ialah sifat kimia kerana bahan boleh berubah kepada bahan baharu apabila terbakar.",
  },
  {
    id: "sci-f1-c5-bm-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah keadaan jirim yang mempunyai bentuk tetap dan isi padu tetap?",
    options: ["Pepejal", "Cecair", "Gas", "Wap"],
    answerIndex: 0,
    explanation: "Pepejal mempunyai bentuk tetap dan isi padu tetap.",
  },
  {
    id: "sci-f1-c5-bm-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Pernyataan manakah paling tepat menerangkan zarah dalam pepejal?",
    options: [
      "Zarah berjauhan dan bergerak bebas ke semua arah",
      "Zarah tersusun rapat tetapi langsung tidak bergerak",
      "Zarah tersusun rapat dan bergetar pada kedudukan tetap",
      "Zarah tersusun rapat dan bergerak bebas antara satu sama lain",
    ],
    answerIndex: 2,
    explanation: "Zarah pepejal sangat rapat dan hanya bergetar pada kedudukan tetap.",
  },
  {
    id: "sci-f1-c5-bm-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah keadaan jirim yang mengikut bentuk bekas tetapi mempunyai isi padu tetap?",
    options: ["Cecair", "Pepejal", "Gas", "Cahaya"],
    answerIndex: 0,
    explanation: "Cecair mengikut bentuk bekas tetapi isi padunya tetap.",
  },
  {
    id: "sci-f1-c5-bm-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah gas lebih mudah dimampatkan berbanding pepejal dan cecair?",
    options: [
      "Terdapat ruang yang besar antara zarah gas",
      "Zarah gas tersusun lebih rapat daripada zarah cecair",
      "Saiz setiap zarah gas mengecil apabila tekanan dikenakan",
      "Jisim setiap zarah gas berkurang apabila tekanan dikenakan",
    ],
    answerIndex: 0,
    explanation: "Ruang yang besar antara zarah gas membolehkan zarah-zarahnya dirapatkan apabila tekanan dikenakan.",
  },
  {
    id: "sci-f1-c5-bm-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud resapan?",
    options: [
      "Pergerakan zarah dari kawasan berkepekatan tinggi ke rendah",
      "Perubahan pepejal kepada cecair",
      "Objek tenggelam dalam air",
      "Penghasilan bahan baharu",
    ],
    answerIndex: 0,
    explanation: "Resapan berlaku apabila zarah bergerak dari kawasan berkepekatan tinggi ke kawasan berkepekatan rendah.",
  },
  {
    id: "sci-f1-c5-bm-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Dalam keadaan jirim manakah resapan berlaku paling cepat?",
    options: ["Gas", "Cecair", "Pepejal", "Ais"],
    answerIndex: 0,
    explanation: "Resapan paling cepat dalam gas kerana zarah gas bergerak bebas dan laju.",
  },
  {
    id: "sci-f1-c5-bm-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah proses perubahan pepejal kepada cecair?",
    options: ["Peleburan", "Pembekuan", "Kondensasi", "Pemejalwapan"],
    answerIndex: 0,
    explanation: "Peleburan ialah proses pepejal berubah menjadi cecair.",
  },
  {
    id: "sci-f1-c5-bm-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah rumus ketumpatan?",
    options: ["Ketumpatan = Jisim / Isi padu", "Ketumpatan = Isi padu / Jisim", "Ketumpatan = Jisim x Suhu", "Ketumpatan = Daya / Luas"],
    answerIndex: 0,
    explanation: "Ketumpatan dikira dengan membahagikan jisim dengan isi padu.",
  },
  {
    id: "sci-f1-c5-bm-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Dua bahan mempunyai warna yang sama tetapi takat didih yang berbeza. Sifat manakah paling sesuai digunakan untuk membezakan kedua-dua bahan tersebut?",
    options: [
      "Warna bahan",
      "Takat didih",
      "Bentuk bekas",
      "Kuantiti bahan",
    ],
    answerIndex: 1,
    explanation: "Takat didih ialah sifat fizik yang boleh digunakan untuk mengenal pasti dan mengelaskan bahan.",
  },
  {
    id: "sci-f1-c5-bm-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah gas mengikut bentuk dan isi padu bekas?",
    options: [
      "Zarah gas berjauhan dan bergerak bebas",
      "Zarah gas tersusun rapat dan tetap",
      "Gas tidak mempunyai zarah",
      "Gas sentiasa menjadi pepejal",
    ],
    answerIndex: 0,
    explanation: "Zarah gas berjauhan dan bergerak bebas, jadi gas memenuhi seluruh bekas.",
  },
  {
    id: "sci-f1-c5-bm-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah yang berlaku kepada zarah pepejal apabila pepejal dipanaskan sehingga melebur?",
    options: [
      "Zarah membebaskan haba lalu bergetar semakin perlahan pada kedudukan tetap",
      "Zarah menyerap haba, bergerak lebih aktif dan akhirnya dapat bergerak antara satu sama lain",
      "Zarah menyerap haba lalu menjadi semakin rapat dan kekal pada kedudukan tetap",
      "Zarah membebaskan haba lalu susunannya menjadi semakin teratur",
    ],
    answerIndex: 1,
    explanation: "Semasa pemanasan, zarah menyerap tenaga haba. Pergerakannya meningkat sehingga susunan tetap pepejal tidak lagi dapat dikekalkan.",
  },
  {
    id: "sci-f1-c5-bm-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Perubahan cecair kepada gas pada takat didih dikenali sebagai apa?",
    options: ["Pendidihan", "Pembekuan", "Kondensasi", "Peleburan"],
    answerIndex: 0,
    explanation: "Pendidihan berlaku apabila cecair berubah menjadi gas pada takat didih.",
  },
  {
    id: "sci-f1-c5-bm-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Wap air membentuk titisan air pada permukaan luar gelas yang sejuk. Apakah yang berlaku kepada zarah wap air?",
    options: [
      "Zarah menyerap haba, bergerak lebih cepat dan menjadi lebih berjauhan",
      "Zarah membebaskan haba, bergerak lebih cepat dan menjadi lebih berjauhan",
      "Zarah membebaskan haba, bergerak lebih perlahan dan menjadi lebih rapat",
      "Zarah menyerap haba, bergerak lebih perlahan dan menjadi lebih rapat",
    ],
    answerIndex: 2,
    explanation: "Semasa kondensasi, gas membebaskan haba. Zarah kehilangan tenaga kinetik, bergerak lebih perlahan dan menjadi lebih rapat untuk membentuk cecair.",
  },
  {
    id: "sci-f1-c5-bm-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Antara proses berikut, yang manakah menyerap haba?",
    options: ["Peleburan", "Pembekuan", "Kondensasi", "Gas kepada pepejal"],
    answerIndex: 0,
    explanation: "Peleburan menyerap haba untuk menukar pepejal kepada cecair.",
  },
  {
    id: "sci-f1-c5-bm-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Ais sedang melebur pada takat leburnya. Walaupun haba terus dibekalkan, suhu ais dan air kekal sama untuk suatu tempoh. Mengapakah hal ini berlaku?",
    options: [
      "Tenaga haba digunakan untuk mengatasi daya tarikan antara zarah semasa perubahan keadaan",
      "Tenaga haba digunakan untuk menambahkan jisim setiap zarah ais",
      "Tenaga haba digunakan untuk meningkatkan suhu zarah tanpa mengubah susunannya",
      "Tenaga haba tidak lagi diserap selagi masih terdapat ais",
    ],
    answerIndex: 0,
    explanation: "Semasa perubahan keadaan, tenaga haba digunakan untuk mengatasi daya tarikan antara zarah, bukannya meningkatkan suhu.",
  },
  {
    id: "sci-f1-c5-bm-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "100 g air dibekukan sepenuhnya menjadi ais tanpa kehilangan bahan daripada bekas. Apakah jisim ais yang terbentuk?",
    options: [
      "Kurang daripada 100 g",
      "Lebih daripada 100 g",
      "0 g",
      "100 g",
    ],
    answerIndex: 3,
    explanation: "Jisim kekal tidak berubah semasa perubahan fizik jika tiada bahan masuk atau keluar daripada sistem.",
  },
  {
    id: "sci-f1-c5-bm-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Sebuah objek berjisim 20 g mempunyai isi padu 10 cm3. Berapakah ketumpatannya?",
    options: ["2 g/cm3", "10 g/cm3", "20 g/cm3", "200 g/cm3"],
    answerIndex: 0,
    explanation: "Ketumpatan = 20 g / 10 cm3 = 2 g/cm3.",
  },
  {
    id: "sci-f1-c5-bm-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Medium",
    question: "Pakaian basah menjadi kering apabila dijemur. Proses manakah yang menyebabkan air pada pakaian berubah menjadi wap air?",
    options: [
      "Kondensasi",
      "Penyejatan",
      "Pembekuan",
      "Pemejalwapan",
    ],
    answerIndex: 1,
    explanation: "Penyejatan ialah perubahan cecair kepada gas yang berlaku pada permukaan cecair.",
  },
  {
    id: "sci-f1-c5-bm-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah gas meresap lebih cepat berbanding pepejal?",
    options: [
      "Zarah gas berjauhan dan bergerak lebih bebas",
      "Zarah gas tersusun rapat",
      "Gas mempunyai isi padu tetap",
      "Pepejal tidak mempunyai zarah",
    ],
    answerIndex: 0,
    explanation: "Zarah gas berjauhan dan bergerak laju, jadi resapan berlaku lebih cepat.",
  },
  {
    id: "sci-f1-c5-bm-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah ais terapung di atas air?",
    options: [
      "Ais kurang tumpat daripada air",
      "Ais lebih tumpat daripada air",
      "Ais tidak mempunyai jisim",
      "Air bukan jirim",
    ],
    answerIndex: 0,
    explanation: "Objek kurang tumpat daripada cecair akan terapung. Ais kurang tumpat daripada air.",
  },
  {
    id: "sci-f1-c5-bm-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Hard",
    question: "Jika haba terus dibekalkan kepada cecair, apakah ramalan terbaik tentang zarahnya?",
    options: [
      "Zarah bergerak lebih laju dan boleh berubah menjadi gas",
      "Zarah menjadi lebih rapat dan tetap",
      "Zarah hilang sepenuhnya",
      "Zarah bertukar menjadi bunyi",
    ],
    answerIndex: 0,
    explanation: "Haba meningkatkan tenaga kinetik zarah. Cecair boleh berubah menjadi gas melalui pendidihan atau penyejatan.",
  },
  {
    id: "sci-f1-c5-bm-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Hard",
    question: "Ali mahu menguji sama ada sesuatu bahan mudah terbakar. Apakah jenis sifat yang diuji?",
    options: ["Sifat kimia", "Sifat fizik", "Isi padu", "Jisim sahaja"],
    answerIndex: 0,
    explanation: "Kebolehbakaran ialah sifat kimia kerana pembakaran menghasilkan bahan baharu.",
  },
  {
    id: "sci-f1-c5-bm-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 5",
    lang: "bm",
    difficulty: "Hard",
    question: "Sebuah objek tenggelam dalam air. Apakah kesimpulan paling sesuai?",
    options: [
      "Objek itu lebih tumpat daripada air",
      "Objek itu kurang tumpat daripada air",
      "Objek itu bukan jirim",
      "Objek itu tidak mempunyai isi padu",
    ],
    answerIndex: 0,
    explanation: "Objek yang lebih tumpat daripada cecair akan tenggelam.",
  },
];
