import type { Flashcard } from "@/data/content";

export const scienceF2C3FlashcardsDLP: Flashcard[] = [
  // Deck 1: Basics (Cards 1-20)
  {
    id: "sci-f2-c3-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What are the 7 main classes of food?",
    back: "Carbohydrate, protein, fat, vitamin, mineral, fibre and water.",
  },
  {
    id: "sci-f2-c3-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the main function of carbohydrate?",
    back: "Supplies energy; it is the staple food for humans.",
  },
  {
    id: "sci-f2-c3-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Name three examples of carbohydrate.",
    back: "Starch (stored in plants), glycogen (stored in animals), cellulose (forms plant cell walls).",
  },
  {
    id: "sci-f2-c3-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the basic unit of protein after digestion?",
    back: "Amino acid.",
  },
  {
    id: "sci-f2-c3-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is Kwashiorkor?",
    back: "A disease caused by protein deficiency, generally occurring in children aged 1-3 years.",
  },
  {
    id: "sci-f2-c3-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Fat is formed from what?",
    back: "Glycerol and fatty acid.",
  },
  {
    id: "sci-f2-c3-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the function of vitamins in the body?",
    back: "Vitamins do not supply energy, but are needed in small quantities to maintain good health.",
  },
  {
    id: "sci-f2-c3-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is fibre?",
    back: "A substance that cannot be broken down by the digestive system, comprising cellulose; stimulates peristalsis and prevents constipation.",
  },
  {
    id: "sci-f2-c3-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the function of minerals in the body?",
    back: "Minerals do not supply energy, but are needed in small quantities to regulate body processes.",
  },
  {
    id: "sci-f2-c3-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the function of water in the body?",
    back: "Acts as a chemical solvent and transport medium for nutrients/oxygen; removes waste from cells; regulates body temperature.",
  },
  {
    id: "sci-f2-c3-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is a balanced diet?",
    back: "A diet that contains all the food classes in the right quantities required by the body.",
  },
  {
    id: "sci-f2-c3-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is digestion?",
    back: "The process of breaking down large/complex food particles into small/simple molecules that can be absorbed by the body.",
  },
  {
    id: "sci-f2-c3-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is a villus?",
    back: "A fine projection on the small intestine wall that increases surface area for absorption of digested food.",
  },
  {
    id: "sci-f2-c3-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is defecation?",
    back: "The process of eliminating faeces (undigested food waste) from the body through the anus.",
  },
  {
    id: "sci-f2-c3-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is assimilation?",
    back: "The process of distributing the end products of digestion for use by the cells of the body.",
  },
  {
    id: "sci-f2-c3-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Name the 4 food tests learned in this chapter.",
    back: "Iodine test, Benedict's test, Millon's test, alcohol-emulsion test.",
  },
  {
    id: "sci-f2-c3-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Which test is used to detect starch?",
    back: "The iodine test.",
  },
  {
    id: "sci-f2-c3-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Which test is used to detect glucose/reducing sugars?",
    back: "Benedict's test.",
  },
  {
    id: "sci-f2-c3-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Which test is used to detect protein?",
    back: "Millon's test.",
  },
  {
    id: "sci-f2-c3-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Which test is used to detect fat?",
    back: "The alcohol-emulsion test.",
  },

  // Deck 2: Understanding (Cards 21-40)
  {
    id: "sci-f2-c3-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the difference between physical and chemical digestion?",
    back: "Physical digestion: happens in the mouth only through chewing, no enzymes. Chemical digestion: happens in the mouth, stomach, duodenum and intestine, involves enzymes.",
  },
  {
    id: "sci-f2-c3-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the difference between water-soluble and fat-soluble vitamins?",
    back: "Water-soluble: Vitamin B and C. Fat-soluble: Vitamin A, D, E and K.",
  },
  {
    id: "sci-f2-c3-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the role of the mouth in digestion?",
    back: "Food is chewed by teeth, softened by saliva; salivary amylase breaks down starch into maltose.",
  },
  {
    id: "sci-f2-c3-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the role of the oesophagus in digestion?",
    back: "Food (bolus) is pushed into the stomach through peristalsis at the oesophagus wall.",
  },
  {
    id: "sci-f2-c3-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the role of the stomach in digestion?",
    back: "Secretes protease and hydrochloric acid; HCl activates protease and kills bacteria; protein is digested into polypeptides; food becomes chyme.",
  },
  {
    id: "sci-f2-c3-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the role of the duodenum in digestion?",
    back: "Bile (from the liver, stored in the gall bladder) emulsifies fat and neutralises acid; the pancreas secretes amylase, protease and lipase.",
  },
  {
    id: "sci-f2-c3-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the role of the small intestine in digestion?",
    back: "Secretes maltase (maltose→glucose) and protease (dipeptide→amino acid); also the main site of absorption through villi.",
  },
  {
    id: "sci-f2-c3-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the role of the large intestine in digestion?",
    back: "Receives undigested food; water and mineral reabsorption happens here.",
  },
  {
    id: "sci-f2-c3-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the role of the rectum and anus?",
    back: "The rectum temporarily stores faeces; the anus excretes faeces from the body.",
  },
  {
    id: "sci-f2-c3-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Which enzyme is secreted by the salivary glands and pancreas, and what does it do?",
    back: "Amylase; digests starch into maltose.",
  },
  {
    id: "sci-f2-c3-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Compare the action of protease in the stomach, pancreas and small intestine.",
    back: "Stomach: protein→polypeptide. Pancreas: polypeptide→dipeptide. Small intestine: dipeptide→amino acid.",
  },
  {
    id: "sci-f2-c3-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the action of pancreatic lipase?",
    back: "Digests fat into fatty acids and glycerol.",
  },
  {
    id: "sci-f2-c3-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Why is bile NOT an enzyme?",
    back: "Bile only emulsifies fat into small droplets and neutralises chyme acid; it does not break the chemical bonds of fat like an enzyme does.",
  },
  {
    id: "sci-f2-c3-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What food group is at the base of the Malaysian Food Pyramid, and how many servings daily?",
    back: "Rice, noodles, bread, grains and potatoes; 4-8 servings daily.",
  },
  {
    id: "sci-f2-c3-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "How many servings of vegetables and fruits are recommended daily?",
    back: "Vegetables: 3 servings daily. Fruits: 2 servings daily.",
  },
  {
    id: "sci-f2-c3-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What food group is at the tip of the Malaysian Food Pyramid?",
    back: "Fat, oil, sugar and salt — eaten sparingly (smallest quantity).",
  },
  {
    id: "sci-f2-c3-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "List the 6 factors that influence a person's calorific requirement.",
    back: "State of health, climate, work, gender, body size, age.",
  },
  {
    id: "sci-f2-c3-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Why do farmers/labourers need more energy than office workers?",
    back: "Because they carry out heavy work that requires more energy.",
  },
  {
    id: "sci-f2-c3-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Why do children need more carbohydrate and protein than adults?",
    back: "Because they are growing (need protein for growth) and are more active (need carbohydrate for energy).",
  },
  {
    id: "sci-f2-c3-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the lacteal and what is its function?",
    back: "A structure within each villus that absorbs digested fat and transfers it into the lymphatic system, then into the blood circulatory system.",
  },

  // Deck 3: Exam (Cards 41-60)
  {
    id: "sci-f2-c3-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the formula for BMI?",
    back: "BMI = Mass (kg) ÷ [Height (m) × Height (m)].",
  },
  {
    id: "sci-f2-c3-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the energy value of fat (kJ/g and kcal/g)?",
    back: "37 kJ/g, 9 kcal/g.",
  },
  {
    id: "sci-f2-c3-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the energy value of protein and carbohydrate (kJ/g and kcal/g)?",
    back: "Both are 17 kJ/g, 4 kcal/g.",
  },
  {
    id: "sci-f2-c3-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the conversion relationship between calorie and joule?",
    back: "1 calorie (cal) = 4.2 joule (J); 1 kilocalorie (kcal) = 4.2 kilojoule (kJ).",
  },
  {
    id: "sci-f2-c3-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "How many times more energy does fat supply compared to carbohydrate per gram?",
    back: "Roughly 2 times (37 kJ/g compared to 17 kJ/g).",
  },
  {
    id: "sci-f2-c3-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What percentage of Malaysians have high cholesterol according to NHMS 2016?",
    back: "47%.",
  },
  {
    id: "sci-f2-c3-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What percentage of Malaysians are overweight according to NHMS 2016?",
    back: "40%.",
  },
  {
    id: "sci-f2-c3-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What percentage of Malaysians have obesity and diabetes according to NHMS 2016?",
    back: "Obesity: 17%. Diabetes: 17.5%.",
  },
  {
    id: "sci-f2-c3-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What percentage of Malaysian adults eat enough fruits and vegetables?",
    back: "Only 6%, which prompted the Ministry of Health's Eat Fruits and Vegetables Campaign.",
  },
  {
    id: "sci-f2-c3-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Arrange the complete protein digestion chain from substrate to final product.",
    back: "Protein → (stomach protease) → Polypeptide → (pancreatic protease) → Dipeptide → (small intestine protease) → Amino acid.",
  },
  {
    id: "sci-f2-c3-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What is the positive result of Benedict's test, and what does a brick-red colour mean?",
    back: "Colour changes from blue to green/yellow/brick-red precipitate; a brick-red precipitate indicates a HIGH concentration of reducing sugar.",
  },
  {
    id: "sci-f2-c3-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Why must ethanol be kept away from fire during the alcohol-emulsion test?",
    back: "Because ethanol is a flammable chemical.",
  },
  {
    id: "sci-f2-c3-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "How are glucose, amino acid and fatty acid/glycerol used after assimilation?",
    back: "Glucose→energy (respiration); Amino acid→new cell components; Fatty acid+glycerol→fat (heat insulator, protects organs).",
  },
  {
    id: "sci-f2-c3-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Why is the thin villus wall (one-cell thick) important?",
    back: "It shortens the diffusion distance and increases the RATE of nutrient absorption into the blood.",
  },
  {
    id: "sci-f2-c3-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Which three body systems work together to ensure digested food molecules reach body cells?",
    back: "The digestive system, blood circulatory system, and respiratory system.",
  },
  {
    id: "sci-f2-c3-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What happens to water and minerals as food passes through the large intestine?",
    back: "Water and minerals are reabsorbed into the bloodstream, turning the remaining undigested food into solid faeces.",
  },
  {
    id: "sci-f2-c3-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Give one example of a healthy lifestyle practice to reduce diet-related disease risk.",
    back: "Eat less sugar, salt, oil and fat; exercise regularly; do not smoke.",
  },
  {
    id: "sci-f2-c3-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "What other nutrition-related issue (besides obesity) is briefly mentioned in this chapter?",
    back: "Malnutrition (a general deficiency of nutrients) can also affect a person's health.",
  },
  {
    id: "sci-f2-c3-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "Why does a person with a larger body frame need bigger food portions?",
    back: "Because a larger body requires more energy to function, hence requiring bigger food portions.",
  },
  {
    id: "sci-f2-c3-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 3",
    lang: "dlp",
    front: "If hydrochloric acid in the stomach decreases drastically, what are two main effects on digestion?",
    back: "Stomach protease cannot be properly activated (protein digestion is impaired), and bacteria in food cannot be effectively killed.",
  },
];
