import type { QuizQuestion } from "@/data/content";

export const scienceF2C3QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c3-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "How many main classes of food are there?",
    options: ["5", "6", "7", "8"],
    answerIndex: 2,
    explanation: "Food is divided into 7 main classes: carbohydrate, protein, fat, vitamin, mineral, fibre and water.",
  },
  {
    id: "sci-f2-c3-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the basic unit produced when protein is digested?",
    options: ["Glucose", "Amino acid", "Fatty acid", "Glycerol"],
    answerIndex: 1,
    explanation: "Protein is digested to its basic unit: amino acid.",
  },
  {
    id: "sci-f2-c3-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "The protein deficiency disease that generally occurs in children aged 1-3 years is called...",
    options: ["Scurvy", "Rickets", "Kwashiorkor", "Goiter"],
    answerIndex: 2,
    explanation: "Kwashiorkor is caused by protein deficiency and generally occurs in children aged 1-3 years.",
  },
  {
    id: "sci-f2-c3-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Fat is formed from a combination of...",
    options: ["Glucose and amino acid", "Glycerol and fatty acid", "Starch and cellulose", "Amino acid and glycogen"],
    answerIndex: 1,
    explanation: "Fat is formed from glycerol and fatty acid.",
  },
  {
    id: "sci-f2-c3-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Which vitamins belong to the fat-soluble group?",
    options: ["B and C", "A, D, E and K", "Only C", "Only B"],
    answerIndex: 1,
    explanation: "Vitamins are classified as water-soluble (B and C) and fat-soluble (A, D, E and K).",
  },
  {
    id: "sci-f2-c3-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Deficiency of Vitamin C causes...",
    options: ["Beri-beri", "Scurvy", "Rickets", "Anaemia"],
    answerIndex: 1,
    explanation: "Deficiency of Vitamin C causes Scurvy (bleeding gums).",
  },
  {
    id: "sci-f2-c3-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the main function of fibre in the body?",
    options: [
      "Supplies energy to the body",
      "Stimulates peristalsis and prevents constipation",
      "Forms haemoglobin in the blood",
      "Transports fat-soluble vitamins",
    ],
    answerIndex: 1,
    explanation: "Fibre is important to stimulate peristalsis, easing food movement and preventing constipation.",
  },
  {
    id: "sci-f2-c3-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Which mineral is important for building haemoglobin in the blood?",
    options: ["Calcium", "Iron", "Iodine", "Phosphorus"],
    answerIndex: 1,
    explanation: "Iron builds haemoglobin in blood; its deficiency causes Anaemia.",
  },
  {
    id: "sci-f2-c3-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Deficiency of iodine causes...",
    options: ["Goiter", "Scurvy", "Kwashiorkor", "Beri-beri"],
    answerIndex: 0,
    explanation: "Iodine helps thyroid gland function; its deficiency causes Goiter.",
  },
  {
    id: "sci-f2-c3-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the minimum recommended amount of water to drink daily?",
    options: ["1 litre", "2 litres", "4 litres", "0.5 litre"],
    answerIndex: 1,
    explanation: "The recommendation is to drink at least 2 litres of water a day.",
  },
  {
    id: "sci-f2-c3-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the positive result of the iodine test?",
    options: ["Colour changes to blue-black", "Brick-red precipitate", "Cloudy white emulsion", "Colour changes to green"],
    answerIndex: 0,
    explanation: "The iodine test detects starch — a positive result is a colour change to blue-black.",
  },
  {
    id: "sci-f2-c3-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Which test is used to detect protein, and what is its positive result?",
    options: [
      "Benedict's test; green colour",
      "Millon's test; brick-red precipitate/colour",
      "Iodine test; blue-black",
      "Alcohol-emulsion test; white emulsion",
    ],
    answerIndex: 1,
    explanation: "Millon's test detects protein — the positive result is a brick-red precipitate/colour after heating.",
  },
  {
    id: "sci-f2-c3-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Why are Benedict's and Millon's tests heated in a water bath instead of a direct flame?",
    options: [
      "To prevent starch from exploding",
      "Because ethanol used in another test is flammable, and for safe/even heating",
      "Because iodine cannot be exposed to light",
      "To save experiment time",
    ],
    answerIndex: 1,
    explanation: "Heating in a water bath is safer and more even; ethanol (used in the fat test) is flammable, so safety precautions must be taken in the lab.",
  },
  {
    id: "sci-f2-c3-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Which food group is at the base (largest section) of the Malaysian Food Pyramid?",
    options: [
      "Fat, oil, sugar and salt",
      "Milk and dairy products",
      "Rice, noodles, bread, grains and potatoes",
      "Fish, chicken, meat and nuts",
    ],
    answerIndex: 2,
    explanation: "Rice, noodles, bread, grains and potatoes are at the base of the pyramid with 4-8 servings daily — the largest group.",
  },
  {
    id: "sci-f2-c3-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the energy value of fat in kJ/g?",
    options: ["17 kJ/g", "37 kJ/g", "9 kJ/g", "4 kJ/g"],
    answerIndex: 1,
    explanation: "Fat supplies 37 kJ/g (9 kcal/g), roughly twice the energy value of carbohydrate/protein (17 kJ/g each).",
  },
  {
    id: "sci-f2-c3-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the formula to calculate Body Mass Index (BMI)?",
    options: [
      "BMI = Mass (kg) × Height (m)",
      "BMI = Mass (kg) ÷ [Height (m) × Height (m)]",
      "BMI = Height (m) ÷ Mass (kg)",
      "BMI = Mass (kg) ÷ Height (m)",
    ],
    answerIndex: 1,
    explanation: "BMI = Mass (kg) ÷ [Height (m) × Height (m)] — used to evaluate a person's body mass status.",
  },
  {
    id: "sci-f2-c3-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Which organ follows the oesophagus in the digestive tract?",
    options: ["Duodenum", "Small intestine", "Stomach", "Large intestine"],
    answerIndex: 2,
    explanation: "Digestive tract order: Mouth → Oesophagus → Stomach → Duodenum → Small intestine → Large intestine → Rectum → Anus.",
  },
  {
    id: "sci-f2-c3-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the name of the semi-liquid food formed in the stomach?",
    options: ["Bolus", "Chyme", "Villus", "Faeces"],
    answerIndex: 1,
    explanation: "In the stomach, food mixes with protease and hydrochloric acid and becomes semi-liquid called chyme.",
  },
  {
    id: "sci-f2-c3-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Which enzyme digests maltose into glucose?",
    options: ["Amylase", "Protease", "Maltase", "Lipase"],
    answerIndex: 2,
    explanation: "Maltase, secreted by the small intestine, digests maltose into glucose.",
  },
  {
    id: "sci-f2-c3-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the role of villi in the small intestine?",
    options: [
      "Produce bile to emulsify fat",
      "Increase surface area for absorption of digested food",
      "Kill bacteria in food",
      "Store faeces before defecation",
    ],
    answerIndex: 1,
    explanation: "Villi are fine projections on the small intestine wall that increase surface area for absorption of digested food.",
  },
  {
    id: "sci-f2-c3-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "A farm labourer working in a hot climate needs more of which food classes, and why?",
    options: [
      "Vitamins only, because heavy work requires more vitamins for energy",
      "Carbohydrate for energy due to heavy work, and water to replace water lost through sweat",
      "Minerals only, because minerals supply high energy",
      "Fibre only, to prevent constipation from heavy work",
    ],
    answerIndex: 1,
    explanation: "Labourers need more energy due to heavy work (carbohydrate) and more water to replace water lost through sweat due to the hot climate.",
  },
  {
    id: "sci-f2-c3-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "If a person's pancreas fails to function, which digestive process is MOST affected?",
    options: [
      "Starch digestion in the mouth by salivary amylase only",
      "Digestion of protein, starch and fat in the duodenum by pancreatic amylase, protease and lipase",
      "Water absorption in the large intestine",
      "Muscle contraction of the oesophagus during peristalsis",
    ],
    answerIndex: 1,
    explanation: "The pancreas produces pancreatic juice containing amylase, protease and lipase — its failure affects digestion of starch, polypeptides and fat in the duodenum.",
  },
  {
    id: "sci-f2-c3-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Based on calorific values, which supplies MORE energy: 10g of fat or 10g of carbohydrate?",
    options: [
      "10g of carbohydrate, because carbohydrate is a staple food",
      "Both supply the same amount, because both supply energy",
      "10g of fat, because fat supplies roughly 2× the energy of carbohydrate per gram",
      "Cannot be determined without protein information",
    ],
    answerIndex: 2,
    explanation: "Fat supplies 37 kJ/g compared to carbohydrate's 17 kJ/g, so 10g of fat (370 kJ) supplies more energy than 10g of carbohydrate (170 kJ).",
  },
  {
    id: "sci-f2-c3-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Why is bile NOT classified as an enzyme even though it helps with fat digestion?",
    options: [
      "Because bile only emulsifies fat (breaks it into small droplets) and neutralises acid, rather than breaking the chemical bonds of fat",
      "Because bile is produced by the pancreas, not the liver",
      "Because bile only acts on carbohydrate",
      "Because bile is not secreted into the duodenum",
    ],
    answerIndex: 0,
    explanation: "Bile only emulsifies fat into small droplets and neutralises chyme acid; the actual chemical digestion of fat (breaking chemical bonds) is carried out by the enzyme lipase.",
  },
  {
    id: "sci-f2-c3-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Why is digested fat absorbed through the lacteal and lymphatic system, unlike glucose and amino acids?",
    options: [
      "Because fat is larger in size and does not dissolve directly in blood, so it requires a pathway through the lymphatic system before entering blood circulation",
      "Because fat is not absorbed by the body at all",
      "Because fat is digested directly in the mouth",
      "Because fat is only absorbed by the large intestine",
    ],
    answerIndex: 0,
    explanation: "Digested fat (reformed fatty acids and glycerol) is absorbed by the lacteal within villi and transferred to the lymphatic system first before entering the blood circulatory system, unlike glucose/amino acids which are absorbed directly into blood capillaries.",
  },
  {
    id: "sci-f2-c3-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Based on the NHMS 2016 statistics, what is the MOST accurate conclusion about Malaysians' eating habits?",
    options: [
      "The majority of Malaysians practise very healthy and balanced eating",
      "The high percentages of diet-related health problems (47% high cholesterol, 40% overweight) show improper diet/lifestyle among Malaysians",
      "Only diabetes is significant among Malaysians",
      "There is no connection between these statistics and eating habits",
    ],
    answerIndex: 1,
    explanation: "High percentages (47% high cholesterol, 40% overweight, 17% obesity, 30% high blood pressure, 17.5% diabetes) show improper diet/lifestyle among Malaysians.",
  },
  {
    id: "sci-f2-c3-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "Arrange the CORRECT substrate→product order for protein digestion from the mouth to the small intestine.",
    options: [
      "Protein → Amino acid → Polypeptide → Dipeptide",
      "Protein → Polypeptide → Dipeptide → Amino acid",
      "Polypeptide → Protein → Amino acid → Dipeptide",
      "Amino acid → Dipeptide → Polypeptide → Protein",
    ],
    answerIndex: 1,
    explanation: "Stomach protease digests protein → polypeptide; pancreatic protease digests polypeptide → dipeptide; small intestine protease digests dipeptide → amino acid.",
  },
  {
    id: "sci-f2-c3-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "A growing child needs a greater quantity of two specific food classes compared to an adult. What are these two food classes?",
    options: [
      "Vitamin and mineral",
      "Carbohydrate (energy) and protein (growth)",
      "Fat and water",
      "Fibre and mineral",
    ],
    answerIndex: 1,
    explanation: "Children and teenagers need more carbohydrate for energy and protein for growth since they are growing and more active.",
  },
  {
    id: "sci-f2-c3-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "What is the main difference between 'absorption' in the small intestine and 'reabsorption' in the large intestine?",
    options: [
      "There is no difference, both are the same process",
      "Absorption in the small intestine involves nutrients (glucose, amino acids, fatty acids) through villi; reabsorption in the large intestine only involves water and minerals",
      "Reabsorption in the large intestine involves all nutrients, while the small intestine only absorbs water",
      "Both processes occur in the rectum",
    ],
    answerIndex: 1,
    explanation: "Absorption in the small intestine (via villi) involves the end products of digestion; reabsorption in the large intestine only involves water and minerals, leaving the remaining material to form solid faeces.",
  },
  {
    id: "sci-f2-c3-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "dlp",
    question: "How do the digestive system, blood circulatory system and respiratory system work together after food is digested?",
    options: [
      "The digestive system breaks food into small molecules absorbed via villi, the blood circulatory system transports them to body cells, and the respiratory system supplies oxygen for cellular respiration using that glucose",
      "These three systems are not related to each other",
      "The respiratory system digests food directly without the digestive system",
      "The blood circulatory system completely replaces the digestive system's function",
    ],
    answerIndex: 0,
    explanation: "The digestive system breaks down food into small molecules absorbed into villi; the blood circulatory system transports these nutrients to cells; the respiratory system supplies the oxygen needed for cellular respiration using the assimilated glucose.",
  },
];
