import type { QuizQuestion } from "@/data/content";

export const scienceF2C3QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c3-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Berapakah jumlah kelas makanan utama?",
    options: ["5", "6", "7", "8"],
    answerIndex: 2,
    explanation: "Makanan terbahagi kepada 7 kelas utama: karbohidrat, protein, lemak, vitamin, mineral, pelawas dan air.",
  },
  {
    id: "sci-f2-c3-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah unit asas yang dihasilkan apabila protein dicernakan?",
    options: ["Glukosa", "Asid amino", "Asid lemak", "Gliserol"],
    answerIndex: 1,
    explanation: "Protein dicernakan kepada unit asasnya iaitu asid amino.",
  },
  {
    id: "sci-f2-c3-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Penyakit kekurangan protein yang biasa berlaku pada kanak-kanak berumur 1-3 tahun dipanggil...",
    options: ["Skurvi", "Riket", "Kwashiorkor", "Goiter"],
    answerIndex: 2,
    explanation: "Kwashiorkor disebabkan oleh kekurangan protein, biasanya berlaku pada kanak-kanak berumur 1-3 tahun.",
  },
  {
    id: "sci-f2-c3-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Lemak terbentuk daripada gabungan...",
    options: ["Glukosa dan asid amino", "Gliserol dan asid lemak", "Kanji dan selulosa", "Asid amino dan glikogen"],
    answerIndex: 1,
    explanation: "Lemak terbentuk daripada gliserol dan asid lemak.",
  },
  {
    id: "sci-f2-c3-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Vitamin manakah tergolong dalam kumpulan larut lemak?",
    options: ["B dan C", "A, D, E dan K", "Hanya C", "Hanya B"],
    answerIndex: 1,
    explanation: "Vitamin dikelaskan sebagai larut air (B dan C) dan larut lemak (A, D, E dan K).",
  },
  {
    id: "sci-f2-c3-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Kekurangan Vitamin C menyebabkan penyakit...",
    options: ["Beri-beri", "Skurvi", "Riket", "Anemia"],
    answerIndex: 1,
    explanation: "Kekurangan Vitamin C menyebabkan Skurvi (gum berdarah).",
  },
  {
    id: "sci-f2-c3-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah fungsi utama pelawas (fiber) dalam badan?",
    options: [
      "Membekalkan tenaga kepada badan",
      "Merangsang peristalsis dan mencegah sembelit",
      "Membentuk hemoglobin dalam darah",
      "Mengangkut vitamin larut lemak",
    ],
    answerIndex: 1,
    explanation: "Pelawas penting untuk merangsang peristalsis, memudahkan gerakan makanan dan mencegah sembelit.",
  },
  {
    id: "sci-f2-c3-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Mineral manakah penting untuk membina hemoglobin dalam darah?",
    options: ["Kalsium", "Ferum", "Iodin", "Fosforus"],
    answerIndex: 1,
    explanation: "Ferum penting untuk membina hemoglobin dalam darah; kekurangannya menyebabkan Anemia.",
  },
  {
    id: "sci-f2-c3-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Kekurangan iodin menyebabkan penyakit...",
    options: ["Goiter", "Skurvi", "Kwashiorkor", "Beri-beri"],
    answerIndex: 0,
    explanation: "Iodin membantu fungsi kelenjar tiroid; kekurangannya menyebabkan Goiter.",
  },
  {
    id: "sci-f2-c3-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Berapakah cadangan minimum air yang perlu diminum sehari?",
    options: ["1 liter", "2 liter", "4 liter", "0.5 liter"],
    answerIndex: 1,
    explanation: "Cadangan adalah minum sekurang-kurangnya 2 liter air sehari.",
  },
  {
    id: "sci-f2-c3-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah keputusan positif bagi ujian iodin?",
    options: ["Warna bertukar hitam-kebiruan", "Mendakan merah bata", "Emulsi putih berkabus", "Warna bertukar hijau"],
    answerIndex: 0,
    explanation: "Ujian iodin digunakan untuk mengesan kanji — keputusan positif ialah warna bertukar hitam-kebiruan.",
  },
  {
    id: "sci-f2-c3-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Ujian manakah digunakan untuk mengesan kehadiran protein, dan apakah keputusan positifnya?",
    options: [
      "Ujian Benedict; warna hijau",
      "Ujian Millon; mendakan/warna merah bata",
      "Ujian iodin; hitam-kebiruan",
      "Ujian emulsi alkohol; emulsi putih",
    ],
    answerIndex: 1,
    explanation: "Ujian Millon mengesan protein — keputusan positif ialah mendakan/warna merah bata selepas dipanaskan.",
  },
  {
    id: "sci-f2-c3-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Mengapakah ujian Benedict dan Millon perlu dipanaskan dalam mandi air, bukan nyalaan api terus?",
    options: [
      "Untuk mengelakkan letupan kanji",
      "Kerana etanol yang digunakan dalam ujian lain mudah terbakar dan untuk pemanasan yang selamat/sekata",
      "Kerana iodin tidak boleh terkena cahaya",
      "Untuk menjimatkan masa eksperimen",
    ],
    answerIndex: 1,
    explanation: "Pemanasan dalam mandi air adalah lebih selamat dan sekata; etanol (digunakan dalam ujian lemak) mudah terbakar, jadi langkah berjaga-jaga perlu diambil di dalam makmal.",
  },
  {
    id: "sci-f2-c3-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Kumpulan makanan manakah terletak di tapak (bahagian terbesar) piramid makanan Malaysia?",
    options: [
      "Lemak, minyak, gula dan garam",
      "Susu dan produk tenusu",
      "Nasi, mi, roti, bijirin dan ubi-ubian",
      "Ikan, ayam, daging dan kekacang",
    ],
    answerIndex: 2,
    explanation: "Nasi, mi, roti, bijirin dan ubi-ubian terletak di tapak piramid dengan cadangan 4-8 sajian sehari — kumpulan terbesar.",
  },
  {
    id: "sci-f2-c3-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Berapakah nilai tenaga lemak dalam unit kJ/g?",
    options: ["17 kJ/g", "37 kJ/g", "9 kJ/g", "4 kJ/g"],
    answerIndex: 1,
    explanation: "Lemak membekalkan 37 kJ/g (9 kkal/g), kira-kira dua kali ganda nilai tenaga karbohidrat/protein (17 kJ/g masing-masing).",
  },
  {
    id: "sci-f2-c3-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah formula untuk mengira Indeks Jisim Badan (BMI)?",
    options: [
      "BMI = Jisim (kg) × Ketinggian (m)",
      "BMI = Jisim (kg) ÷ [Ketinggian (m) × Ketinggian (m)]",
      "BMI = Ketinggian (m) ÷ Jisim (kg)",
      "BMI = Jisim (kg) ÷ Ketinggian (m)",
    ],
    answerIndex: 1,
    explanation: "BMI = Jisim (kg) ÷ [Ketinggian (m) × Ketinggian (m)] — digunakan untuk menilai status jisim badan.",
  },
  {
    id: "sci-f2-c3-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah organ yang menyusuli esofagus dalam saluran pencernaan?",
    options: ["Duodenum", "Usus kecil", "Perut", "Usus besar"],
    answerIndex: 2,
    explanation: "Urutan saluran pencernaan: Mulut → Esofagus → Perut → Duodenum → Usus kecil → Usus besar → Rektum → Anus.",
  },
  {
    id: "sci-f2-c3-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah nama makanan separa cecair yang terbentuk di dalam perut?",
    options: ["Bolus", "Kimus", "Vilus", "Najis"],
    answerIndex: 1,
    explanation: "Di dalam perut, makanan bercampur dengan protease dan asid hidroklorik dan menjadi separa cecair dipanggil kimus.",
  },
  {
    id: "sci-f2-c3-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Enzim manakah mencerna maltosa kepada glukosa?",
    options: ["Amilase", "Protease", "Maltase", "Lipase"],
    answerIndex: 2,
    explanation: "Maltase, yang dirembeskan oleh usus kecil, mencerna maltosa kepada glukosa.",
  },
  {
    id: "sci-f2-c3-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah peranan vilus dalam usus kecil?",
    options: [
      "Menghasilkan hempedu untuk mengemulsikan lemak",
      "Meningkatkan luas permukaan untuk penyerapan makanan terhadam",
      "Membunuh bakteria dalam makanan",
      "Menyimpan najis sebelum disahtinjakan",
    ],
    answerIndex: 1,
    explanation: "Vilus ialah unjuran halus pada dinding usus kecil yang meningkatkan luas permukaan untuk penyerapan makanan terhadam.",
  },
  {
    id: "sci-f2-c3-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Seorang buruh ladang yang bekerja di kawasan beriklim panas memerlukan lebih banyak pengambilan kelas makanan manakah, dan mengapa?",
    options: [
      "Vitamin sahaja, kerana kerja berat memerlukan lebih vitamin untuk tenaga",
      "Karbohidrat untuk tenaga akibat kerja berat, dan air untuk menggantikan air yang hilang melalui peluh",
      "Mineral sahaja, kerana mineral membekalkan tenaga yang tinggi",
      "Pelawas sahaja, untuk mengelakkan sembelit akibat kerja berat",
    ],
    answerIndex: 1,
    explanation: "Buruh memerlukan lebih banyak tenaga akibat kerja berat (karbohidrat) dan lebih banyak air untuk menggantikan kehilangan air melalui peluh akibat cuaca panas.",
  },
  {
    id: "sci-f2-c3-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Jika pankreas seseorang gagal berfungsi, proses pencernaan manakah PALING terjejas?",
    options: [
      "Pencernaan kanji di mulut oleh amilase saliva sahaja",
      "Pencernaan protein, kanji dan lemak di duodenum oleh amilase, protease dan lipase pankreas",
      "Penyerapan air di usus besar",
      "Pengecutan otot esofagus semasa peristalsis",
    ],
    answerIndex: 1,
    explanation: "Pankreas menghasilkan jus pankreas yang mengandungi amilase, protease dan lipase — kegagalannya menjejaskan pencernaan kanji, polipeptida dan lemak di duodenum.",
  },
  {
    id: "sci-f2-c3-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Berdasarkan nilai tenaga makanan, hidangan manakah membekalkan tenaga yang LEBIH BANYAK: 10g lemak atau 10g karbohidrat?",
    options: [
      "10g karbohidrat, kerana karbohidrat ialah makanan ruji",
      "Sama banyak, kerana kedua-duanya membekalkan tenaga",
      "10g lemak, kerana lemak membekalkan kira-kira 2× tenaga berbanding karbohidrat bagi setiap gram",
      "Tidak dapat ditentukan tanpa maklumat protein",
    ],
    answerIndex: 2,
    explanation: "Lemak membekalkan 37 kJ/g berbanding karbohidrat 17 kJ/g, maka 10g lemak (370 kJ) membekalkan lebih tenaga berbanding 10g karbohidrat (170 kJ).",
  },
  {
    id: "sci-f2-c3-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Mengapakah hempedu BUKAN dikategorikan sebagai enzim walaupun ia membantu pencernaan lemak?",
    options: [
      "Kerana hempedu hanya mengemulsikan lemak (memecah kepada titisan kecil) dan meneutralkan asid, bukan memecahkan ikatan kimia lemak",
      "Kerana hempedu dihasilkan oleh pankreas, bukan hati",
      "Kerana hempedu hanya bertindak pada karbohidrat",
      "Kerana hempedu tidak dirembeskan ke dalam duodenum",
    ],
    answerIndex: 0,
    explanation: "Hempedu hanya mengemulsikan lemak kepada titisan kecil dan meneutralkan asid kimus secara fizikal/kimia ringkas; pencernaan kimia sebenar lemak (memecah ikatan kimia) dilakukan oleh enzim lipase.",
  },
  {
    id: "sci-f2-c3-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Mengapakah lemak terhadam diserap melalui lakteal dan sistem limfa, berbeza daripada glukosa dan asid amino?",
    options: [
      "Kerana lemak bersaiz lebih besar dan tidak larut dalam darah secara terus, jadi memerlukan laluan melalui sistem limfa sebelum memasuki peredaran darah",
      "Kerana lemak tidak diserap sama sekali oleh badan",
      "Kerana lemak dicerna terus di dalam mulut",
      "Kerana lemak hanya diserap oleh usus besar",
    ],
    answerIndex: 0,
    explanation: "Lemak terhadam (asid lemak dan gliserol bergabung semula) diserap oleh lakteal dalam vilus dan dipindahkan ke sistem limfa terlebih dahulu sebelum memasuki sistem peredaran darah, berbeza daripada glukosa/asid amino yang diserap terus ke kapilari darah.",
  },
  {
    id: "sci-f2-c3-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Berdasarkan statistik NHMS 2016, apakah kesimpulan yang PALING tepat tentang tabiat pemakanan rakyat Malaysia?",
    options: [
      "Majoriti rakyat Malaysia mengamalkan pemakanan yang sangat sihat dan seimbang",
      "Peratusan tinggi masalah kesihatan berkaitan pemakanan (kolesterol tinggi 47%, berat badan berlebihan 40%) menunjukkan amalan pemakanan/gaya hidup yang tidak sihat",
      "Hanya masalah diabetes yang signifikan dalam kalangan rakyat Malaysia",
      "Tiada kaitan antara statistik tersebut dengan amalan pemakanan",
    ],
    answerIndex: 1,
    explanation: "Peratusan tinggi (kolesterol tinggi 47%, berat badan berlebihan 40%, obesiti 17%, darah tinggi 30%, diabetes 17.5%) menunjukkan amalan pemakanan dan gaya hidup yang tidak sihat dalam kalangan rakyat Malaysia.",
  },
  {
    id: "sci-f2-c3-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Susunkan mengikut urutan substrat→produk yang BETUL bagi pencernaan protein dari mulut hingga usus kecil.",
    options: [
      "Protein → Asid amino → Polipeptida → Dipeptida",
      "Protein → Polipeptida → Dipeptida → Asid amino",
      "Polipeptida → Protein → Asid amino → Dipeptida",
      "Asid amino → Dipeptida → Polipeptida → Protein",
    ],
    answerIndex: 1,
    explanation: "Protease perut mencerna protein → polipeptida; protease pankreas mencerna polipeptida → dipeptida; protease usus kecil mencerna dipeptida → asid amino.",
  },
  {
    id: "sci-f2-c3-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Seorang kanak-kanak yang sedang membesar memerlukan kuantiti lebih besar bagi dua kelas makanan tertentu berbanding orang dewasa. Apakah dua kelas makanan tersebut?",
    options: [
      "Vitamin dan mineral",
      "Karbohidrat (tenaga) dan protein (pertumbuhan)",
      "Lemak dan air",
      "Pelawas dan mineral",
    ],
    answerIndex: 1,
    explanation: "Kanak-kanak dan remaja memerlukan lebih banyak karbohidrat untuk tenaga dan protein untuk pertumbuhan kerana mereka sedang membesar dan lebih aktif.",
  },
  {
    id: "sci-f2-c3-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Apakah perbezaan utama antara 'penyerapan' di usus kecil dan 'penyerapan semula' di usus besar?",
    options: [
      "Tidak ada perbezaan, kedua-duanya proses yang sama",
      "Penyerapan di usus kecil melibatkan nutrien (glukosa, asid amino, asid lemak) melalui vilus; penyerapan semula di usus besar hanya melibatkan air dan mineral",
      "Penyerapan semula di usus besar melibatkan semua nutrien, manakala usus kecil hanya menyerap air",
      "Kedua-dua proses berlaku di rektum",
    ],
    answerIndex: 1,
    explanation: "Penyerapan di usus kecil (melalui vilus) melibatkan nutrien hasil pencernaan; penyerapan semula di usus besar hanya melibatkan air dan mineral, menjadikan baki makanan menjadi najis pejal.",
  },
  {
    id: "sci-f2-c3-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 3",
    lang: "bm",
    question: "Bagaimanakah sistem pencernaan, sistem peredaran darah dan sistem pernafasan bekerjasama selepas makanan dicerna?",
    options: [
      "Sistem pencernaan memecahkan makanan kepada molekul kecil yang diserap melalui vilus, sistem peredaran darah mengangkutnya ke sel-sel badan, dan sistem pernafasan membekalkan oksigen untuk respirasi sel menggunakan glukosa tersebut",
      "Ketiga-tiga sistem ini tidak berkaitan antara satu sama lain",
      "Sistem pernafasan mencerna makanan terus tanpa bantuan sistem pencernaan",
      "Sistem peredaran darah menggantikan fungsi sistem pencernaan sepenuhnya",
    ],
    answerIndex: 0,
    explanation: "Sistem pencernaan memecah makanan kepada molekul kecil yang diserap ke dalam vilus; sistem peredaran darah mengangkut nutrien ini ke sel-sel; sistem pernafasan membekalkan oksigen yang diperlukan untuk respirasi sel menggunakan glukosa yang diasimilasikan.",
  },
];
