import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c3-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 3",
    lang: "dlp",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C3QuizzesDLP: QuizQuestion[] = buildQuiz([
  ["Easy", "What is the formula for simple interest?", ["I = Prt", "I = P + rt", "I = P/rt", "I = Pr + t"], 0],
  ["Easy", "What does P mean in I=Prt?", ["Principal", "Percentage", "Profit", "Periodic payment"], 0],
  ["Easy", "What does r mean in I=Prt?", ["Interest rate", "Risk", "Return", "Rebate"], 0],
  ["Easy", "What does t mean in I=Prt?", ["Term in years", "Total transactions", "Date", "Tax"], 0],
  ["Easy", "Encik Zainal saves RM4 000 at 2% per year. Find the interest after 1 year.", ["RM80", "RM800", "RM8", "RM40"], 0],
  ["Easy", "Which type of savings has a higher interest rate but a fixed term?", ["Fixed deposit account", "Current account", "Regular savings account", "Digital wallet"], 0],
  ["Easy", "Which type of investment returns dividends and capital gains?", ["Shares", "Savings account", "Current account", "Emergency fund"], 0],
  ["Easy", "What is the formula for the maturity value with compound interest?", ["MV = P(1+r/n)^(nt)", "MV = Prt", "MV = P + rt", "MV = Pr/nt"], 0],
  ["Easy", "What does n mean in MV=P(1+r/n)^(nt)?", ["Compounding frequency per year", "Number of investors", "Nominal value", "Net value"], 0],
  ["Easy", "What is the ROI formula?", ["(Total return/cost of investment) x100%", "Total return - cost", "Cost/total return", "Total return + cost"], 0],
  ["Easy", "What are the three factors to consider before investing?", ["Risk, return, liquidity", "Price, colour, brand", "Location, size, colour", "Date, time, place"], 0],
  ["Easy", "What does liquidity mean?", ["The ability to convert an investment into cash quickly", "Total interest", "Rate of return", "Investment risk"], 0],
  ["Easy", "What does credit mean?", ["An agreement to borrow money/goods to be repaid later", "Savings money", "Share investment", "Compound interest"], 0],
  ["Easy", "How many days is the typical interest-free period for a credit card?", ["20 days", "10 days", "30 days", "5 days"], 0],
  ["Easy", "What percentage is the typical minimum credit card payment?", ["5% of the final balance or RM50", "50% of the balance", "10% of the balance", "1% of the balance"], 0],
  ["Easy", "What is the formula for flat-rate loan repayment?", ["A = P + Prt", "A = P x rt", "A = P - rt", "A = Prt"], 0],
  ["Easy", "What is the formula for the monthly instalment?", ["A / number of months", "A x number of months", "A - number of months", "A + number of months"], 0],
  ["Easy", "What is an advantage of a credit card?", ["Cash rebates and reward points", "Free interest forever", "No charges at all", "No spending limit"], 0],
  ["Easy", "What is a disadvantage of a credit card?", ["Finance charges and risk of overspending", "No drawbacks", "Always low interest", "Cannot be used online"], 0],
  ["Easy", "What is the dollar-cost averaging strategy?", ["Investing a fixed amount periodically regardless of market conditions", "Investing only in a lump sum", "Not investing at all", "Investing only when prices are high"], 0],

  ["Medium", "Encik Badrul saves RM5 000 at 3% per year, 2 years. Find the total interest.", ["RM300", "RM150", "RM600", "RM450"], 0],
  ["Medium", "Cik Wong saves RM10 000 at 4% per year. Find the interest after 6 months.", ["RM200", "RM400", "RM100", "RM800"], 0],
  ["Medium", "RM10 000 at 5% per year, compounded monthly (n=12), 1 year. Find the maturity value.", ["RM10 511.62", "RM10 500.00", "RM10 050.00", "RM11 000.00"], 0],
  ["Medium", "Compare n=4 and n=12 for the same rate and term: which gives a higher maturity value?", ["n=12 (more frequent compounding)", "n=4", "Same value", "Cannot be determined"], 0],
  ["Medium", "Encik Osman saves RM20 000 under the wadiah principle, receives RM20 500 after 1 year. Find the percentage of hibah.", ["2.5%", "5%", "25%", "0.25%"], 0],
  ["Medium", "Encik Yusuf: ROI = 76% obtained from a total return of RM456 000 and a cost of RM600 000. Verify this calculation.", ["Correct: (456000/600000)x100=76%", "Incorrect, should be 65%", "Incorrect, should be 84%", "Incorrect, should be 60%"], 0],
  ["Medium", "Puan Linda invests RM20 000 in a lump sum at RM2.00/unit. How many units does she get?", ["10 000 units", "20 000 units", "5 000 units", "2 000 units"], 0],
  ["Medium", "Puan Esther invests RM20 000 using dollar-cost averaging, obtaining 10 626 units. Find the average cost per unit.", ["RM1.88", "RM2.00", "RM1.50", "RM2.50"], 0],
  ["Medium", "Between Puan Linda and Puan Esther, who is the wiser investor?", ["Puan Esther (lower average cost)", "Puan Linda (more units at once)", "Both equally wise", "Cannot be determined"], 0],
  ["Medium", "Encik Azlan borrows RM10 000 at 4% flat rate, 7 years. Find the total repayment A.", ["RM12 800", "RM10 400", "RM14 000", "RM11 600"], 0],
  ["Medium", "From the previous question, find the monthly instalment (84 months).", ["RM152.38", "RM142.86", "RM166.67", "RM120.00"], 0],
  ["Medium", "Encik Harith borrows RM10 000 at 6% reducing balance, instalment RM150. Find the first month's interest.", ["RM50.00", "RM60.00", "RM45.00", "RM100.00"], 0],
  ["Medium", "After month 1 (balance RM9 900), find the second month's interest at 6% reducing balance.", ["RM49.50", "RM50.00", "RM48.00", "RM51.00"], 0],
  ["Medium", "What is Encik Harith's loan balance after the first instalment (loan RM10000+interest RM50, instalment RM150)?", ["RM9 900", "RM9 850", "RM10 050", "RM9 950"], 0],
  ["Medium", "Cik Kayal borrows RM X at 5% flat rate, 8 years, monthly instalment RM218.75. Find the total repayment A.", ["RM218.75 x 96 = RM21 000", "RM218.75 x 84 = RM18 375", "RM218.75 x 8 = RM1 750", "RM218.75 x 60 = RM13 125"], 0],
  ["Medium", "From the previous question, if A = P + Prt with r=0.05, t=8, find P.", ["P = A/(1+0.4) = 21000/1.4 = RM15 000", "P = RM21 000", "P = RM10 500", "P = RM7 500"], 0],
  ["Medium", "Encik Murugan borrows RM16 000, repays over 5 years, monthly instalment RM320. Find the total repayment.", ["RM19 200 (320x60)", "RM16 000", "RM17 600", "RM20 000"], 0],
  ["Medium", "From the previous question, find the total interest.", ["RM3 200 (19200-16000)", "RM1 600", "RM4 800", "RM2 000"], 0],
  ["Medium", "From the previous question, find the annual flat interest rate using I=Prt.", ["4% (3200=16000x r x5, r=0.04)", "5%", "3%", "6%"], 0],
  ["Medium", "Encik Vincent earns RM2 800/month, other expenses RM1 500. Bank A: 9 years 4.5%; Bank B: 6 years 5%, needs guarantor. Which bank suits him if he has no guarantor?", ["Bank A (no guarantor needed)", "Bank B (lower rate, shorter term)", "Both equally suitable", "He cannot borrow"], 0],

  ["Hard", "Encik Yusuf buys a shop for RM600 000, pays 10%, sells for RM1 300 000. Outstanding loan RM486 000, instalments paid RM450 000, legal fees RM15 000, stamp duty RM15 000, commission RM18 000, accumulated rent RM200 000. Find the capital gain.", ["RM256 000", "RM700 000", "RM814 000", "RM200 000"], 0],
  ["Hard", "From the previous question, find the total return (rent + capital gain).", ["RM456 000", "RM256 000", "RM700 000", "RM600 000"], 0],
  ["Hard", "Encik Zainal owns 6 000 RM1 shares, dividend 6%, bonus 1 share per 2 units held. Find the total dividend.", ["RM360 (6000x1x0.06)", "RM600", "RM3 600", "RM60"], 0],
  ["Hard", "From the previous question, find the total bonus shares received.", ["3 000 units (6000/2)", "6 000 units", "1 500 units", "12 000 units"], 0],
  ["Hard", "From the previous question, find the total shares held after the bonus.", ["9 000 units (6000+3000)", "6 000 units", "3 000 units", "12 000 units"], 0],
  ["Hard", "Encik Kishendran saves RM5 000 at 4%, compounded every 3 months (n=4), 3 years. Find the accumulated interest (MV-P).", ["Approximately RM633 (MV≈5633, interest≈633)", "RM600", "RM500", "RM700"], 0],
  ["Hard", "Encik Oswald borrows RM15 000 at 5% flat rate, 5 years. Find the total interest paid.", ["RM3 750 (15000x0.05x5)", "RM750", "RM7 500", "RM1 500"], 0],
  ["Hard", "From the previous question, find the total repayment A and the monthly instalment (60 months).", ["A=RM18 750, instalment=RM312.50", "A=RM15 000, instalment=RM250", "A=RM18 750, instalment=RM375", "A=RM20 000, instalment=RM333.33"], 0],
  ["Hard", "Encik Syed buys an aircon for RM3 200, pays RM2 000 cash, the remaining RM1 200 is paid via credit card within the interest-free period. How much interest is charged if paid in full within that period?", ["RM0 (no interest within the interest-free period)", "RM120", "RM12", "RM1 200"], 0],
  ["Hard", "Cik Chin buys a bag from Company L Singapore for SGD250+SGD50 shipping=SGD300, with a 1% overseas transaction surcharge on her credit card. Find the surcharge in SGD.", ["SGD3.00 (300x0.01)", "SGD30.00", "SGD0.30", "SGD300"], 0],
  ["Hard", "From the previous question, Company V Malaysia offers RM799 with free shipping. If SGD1=RM3.30 and Company L's total cost (SGD303) is converted to RM, which is cheaper?", ["Depends on calculation: SGD303x3.30=RM999.90, so Company V (RM799) is cheaper", "Company L is cheaper", "Same price", "Cannot be compared"], 0],
  ["Hard", "What is the mistake in this statement: 'Reducing balance interest is calculated using the original principal every month'?", ["Reducing balance interest should be recalculated based on the current balance each month, not the original principal", "This statement is correct", "It should use simple interest instead", "It should use ROI instead"], 0],
  ["Hard", "Why does compound interest yield a higher return than simple interest for the same P, r, t?", ["Compound interest is calculated on the principal AND previously accumulated interest", "The compound interest rate is automatically higher", "The compound interest term is longer", "Compound interest is not taxed"], 0],
  ["Hard", "Encik Hussein buys a house for RM300 000, pays a 10% deposit=RM30 000, sells for RM600 000 after 20 years, loan settled RM475 000, accumulated rent RM60 000. Estimate the total return assuming no other costs.", ["Capital gain=600000-475000-30000=95000; total return=60000+95000=155000", "Total return=600000", "Total return=300000", "Total return=60000"], 0],
  ["Hard", "From the previous question, find the ROI based on the initial cost of RM300 000.", ["ROI=(155000/300000)x100%≈51.7%", "ROI=200%", "ROI=20%", "ROI=100%"], 0],
]);
