import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c3-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 3",
    lang: "bm",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C3QuizzesBM: QuizQuestion[] = buildQuiz([
  ["Easy", "Apakah formula faedah mudah?", ["I = Prt", "I = P + rt", "I = P/rt", "I = Pr + t"], 0],
  ["Easy", "Apakah maksud P dalam I=Prt?", ["Prinsipal", "Peratus", "Pulangan", "Pinjaman bulanan"], 0],
  ["Easy", "Apakah maksud r dalam I=Prt?", ["Kadar faedah", "Risiko", "Pulangan", "Rebat"], 0],
  ["Easy", "Apakah maksud t dalam I=Prt?", ["Tempoh dalam tahun", "Jumlah transaksi", "Tarikh", "Tabungan"], 0],
  ["Easy", "Encik Zainal simpan RM4 000, kadar 2% setahun. Hitung faedah selepas 1 tahun.", ["RM80", "RM800", "RM8", "RM40"], 0],
  ["Easy", "Apakah jenis simpanan dengan faedah lebih tinggi tetapi tempoh terhad?", ["Akaun simpanan tetap", "Akaun semasa", "Akaun simpanan biasa", "Dompet digital"], 0],
  ["Easy", "Apakah jenis pelaburan dengan pulangan dividen dan keuntungan modal?", ["Saham", "Akaun simpanan", "Akaun semasa", "Tabung kecemasan"], 0],
  ["Easy", "Apakah formula nilai matang faedah kompaun?", ["MV = P(1+r/n)^(nt)", "MV = Prt", "MV = P + rt", "MV = Pr/nt"], 0],
  ["Easy", "Apakah maksud n dalam MV=P(1+r/n)^(nt)?", ["Kekerapan pengkompaunan setahun", "Nombor pelabur", "Nilai nominal", "Nilai bersih"], 0],
  ["Easy", "Apakah formula ROI?", ["(Jumlah pulangan/kos pelaburan) x100%", "Jumlah pulangan - kos", "Kos/jumlah pulangan", "Jumlah pulangan + kos"], 0],
  ["Easy", "Apakah tiga faktor sebelum melabur?", ["Risiko, pulangan, kecairan", "Harga, warna, jenama", "Lokasi, saiz, warna", "Tarikh, masa, tempat"], 0],
  ["Easy", "Apakah maksud kecairan?", ["Keupayaan menukar pelaburan kepada tunai dengan segera", "Jumlah faedah", "Kadar pulangan", "Risiko pelaburan"], 0],
  ["Easy", "Apakah maksud kredit?", ["Perjanjian meminjam wang/barang untuk dibayar kemudian", "Wang simpanan", "Pelaburan saham", "Faedah kompaun"], 0],
  ["Easy", "Berapa hari biasanya tempoh tanpa faedah kad kredit?", ["20 hari", "10 hari", "30 hari", "5 hari"], 0],
  ["Easy", "Berapa peratus biasanya bayaran minimum kad kredit?", ["5% daripada baki akhir atau RM50", "50% daripada baki", "10% daripada baki", "1% daripada baki"], 0],
  ["Easy", "Apakah formula bayaran balik pinjaman faedah sama rata?", ["A = P + Prt", "A = P x rt", "A = P - rt", "A = Prt"], 0],
  ["Easy", "Apakah formula ansuran bulanan?", ["A / bilangan bulan", "A x bilangan bulan", "A - bilangan bulan", "A + bilangan bulan"], 0],
  ["Easy", "Apakah kelebihan kad kredit?", ["Rebat tunai dan mata ganjaran", "Faedah percuma selamanya", "Tiada caj sama sekali", "Tiada had perbelanjaan"], 0],
  ["Easy", "Apakah kekurangan kad kredit?", ["Caj faedah dan risiko berbelanja lebih", "Tiada kelemahan", "Faedah sentiasa rendah", "Tidak boleh digunakan dalam talian"], 0],
  ["Easy", "Apakah strategi pemurataan kos?", ["Melabur amaun tetap secara berkala tanpa kira keadaan pasaran", "Melabur sekali gus sahaja", "Tidak melabur sama sekali", "Melabur hanya semasa harga tinggi"], 0],

  ["Medium", "Encik Badrul simpan RM5 000, kadar 3% setahun, 2 tahun. Hitung jumlah faedah.", ["RM300", "RM150", "RM600", "RM450"], 0],
  ["Medium", "Cik Wong simpan RM10 000, kadar 4% setahun. Hitung faedah selepas 6 bulan.", ["RM200", "RM400", "RM100", "RM800"], 0],
  ["Medium", "RM10 000 pada 5% setahun, dikompaun bulanan (n=12), 1 tahun. Hitung nilai matang.", ["RM10 511.62", "RM10 500.00", "RM10 050.00", "RM11 000.00"], 0],
  ["Medium", "Bandingkan n=4 dan n=12 untuk kadar dan tempoh sama: yang manakah nilai matang lebih tinggi?", ["n=12 (lebih kerap pengkompaunan)", "n=4", "Sama sahaja", "Tidak boleh ditentukan"], 0],
  ["Medium", "Encik Osman simpan RM20 000 prinsip wadiah, terima RM20 500 selepas 1 tahun. Hitung peratus hibah.", ["2.5%", "5%", "25%", "0.25%"], 0],
  ["Medium", "Encik Yusuf: ROI = 76% diperoleh daripada jumlah pulangan RM456 000 dan kos RM600 000. Sahkan pengiraan ini betul.", ["Betul: (456000/600000)x100=76%", "Salah, sepatutnya 65%", "Salah, sepatutnya 84%", "Salah, sepatutnya 60%"], 0],
  ["Medium", "Puan Linda labur RM20 000 sekaligus pada RM2.00/unit. Berapa unit diperoleh?", ["10 000 unit", "20 000 unit", "5 000 unit", "2 000 unit"], 0],
  ["Medium", "Puan Esther labur RM20 000 secara pemurataan, memperoleh 10 626 unit. Hitung kos purata seunit.", ["RM1.88", "RM2.00", "RM1.50", "RM2.50"], 0],
  ["Medium", "Antara Puan Linda dan Puan Esther, siapa pelabur lebih bijak?", ["Puan Esther (kos purata lebih rendah)", "Puan Linda (lebih ramai unit serentak)", "Kedua sama bijak", "Tidak dapat ditentukan"], 0],
  ["Medium", "Encik Azlan pinjam RM10 000, kadar 4% sama rata, 7 tahun. Hitung jumlah bayaran balik A.", ["RM12 800", "RM10 400", "RM14 000", "RM11 600"], 0],
  ["Medium", "Daripada soalan sebelumnya, hitung ansuran bulanan (84 bulan).", ["RM152.38", "RM142.86", "RM166.67", "RM120.00"], 0],
  ["Medium", "Encik Harith pinjam RM10 000, kadar 6% atas baki, ansuran RM150. Hitung faedah bulan pertama.", ["RM50.00", "RM60.00", "RM45.00", "RM100.00"], 0],
  ["Medium", "Selepas bulan pertama (baki RM9 900), hitung faedah bulan kedua pada 6% atas baki.", ["RM49.50", "RM50.00", "RM48.00", "RM51.00"], 0],
  ["Medium", "Apakah baki pinjaman selepas ansuran bulan pertama Encik Harith (pinjaman RM10000+faedah RM50, ansuran RM150)?", ["RM9 900", "RM9 850", "RM10 050", "RM9 950"], 0],
  ["Medium", "Cik Kayal pinjam RM X pada 5% sama rata, 8 tahun, ansuran bulanan RM218.75. Hitung jumlah bayaran balik A.", ["RM218.75 x 96 = RM21 000", "RM218.75 x 84 = RM18 375", "RM218.75 x 8 = RM1 750", "RM218.75 x 60 = RM13 125"], 0],
  ["Medium", "Daripada soalan sebelumnya, jika A = P + Prt dengan r=0.05, t=8, hitung P.", ["P = A/(1+0.4) = 21000/1.4 = RM15 000", "P = RM21 000", "P = RM10 500", "P = RM7 500"], 0],
  ["Medium", "Encik Murugan pinjam RM16 000, bayar balik 5 tahun, ansuran bulanan RM320. Hitung jumlah bayaran balik.", ["RM19 200 (320x60)", "RM16 000", "RM17 600", "RM20 000"], 0],
  ["Medium", "Daripada soalan sebelumnya, hitung jumlah faedah keseluruhan.", ["RM3 200 (19200-16000)", "RM1 600", "RM4 800", "RM2 000"], 0],
  ["Medium", "Daripada soalan sebelumnya, hitung kadar faedah setahun (sama rata) menggunakan I=Prt.", ["4% (3200=16000x r x5, r=0.04)", "5%", "3%", "6%"], 0],
  ["Medium", "Encik Vincent gaji RM2 800 sebulan, perbelanjaan lain RM1 500. Bank A: 9 tahun 4.5%; Bank B: 6 tahun 5%, perlu penjamin. Bank manakah lebih sesuai jika tiada penjamin?", ["Bank A (tidak perlu penjamin)", "Bank B (kadar lebih rendah tempoh)", "Kedua sama", "Tidak boleh dipinjam"], 0],

  ["Hard", "Encik Yusuf beli kedai RM600 000, bayar 10%, jual RM1 300 000. Pinjaman berbaki RM486 000, ansuran dilunaskan RM450 000, kos guaman RM15 000, duti setem RM15 000, komisen RM18 000, sewa terkumpul RM200 000. Hitung keuntungan modal.", ["RM256 000", "RM700 000", "RM814 000", "RM200 000"], 0],
  ["Hard", "Daripada soalan sebelumnya, hitung jumlah pulangan keseluruhan (sewa + keuntungan modal).", ["RM456 000", "RM256 000", "RM700 000", "RM600 000"], 0],
  ["Hard", "Encik Zainal punya 6 000 unit syer RM1, dividen 6%, bonus 1 syer per 2 unit dipegang. Hitung jumlah dividen.", ["RM360 (6000x1x0.06)", "RM600", "RM3 600", "RM60"], 0],
  ["Hard", "Daripada soalan sebelumnya, hitung jumlah unit syer bonus diterima.", ["3 000 unit (6000/2)", "6 000 unit", "1 500 unit", "12 000 unit"], 0],
  ["Hard", "Daripada soalan sebelumnya, hitung jumlah unit syer dipegang selepas bonus.", ["9 000 unit (6000+3000)", "6 000 unit", "3 000 unit", "12 000 unit"], 0],
  ["Hard", "Encik Kishendran simpan RM5 000, kadar 4%, dikompaun 3 bulan sekali (n=4), 3 tahun. Hitung faedah terkumpul (MV-P).", ["Anggaran RM633 (MV≈5633, faedah≈633)", "RM600", "RM500", "RM700"], 0],
  ["Hard", "Encik Oswald pinjam RM15 000, kadar 5% sama rata, 5 tahun. Hitung jumlah faedah dibayar.", ["RM3 750 (15000x0.05x5)", "RM750", "RM7 500", "RM1 500"], 0],
  ["Hard", "Daripada soalan sebelumnya, hitung jumlah bayaran balik A dan ansuran bulanan (60 bulan).", ["A=RM18 750, ansuran=RM312.50", "A=RM15 000, ansuran=RM250", "A=RM18 750, ansuran=RM375", "A=RM20 000, ansuran=RM333.33"], 0],
  ["Hard", "Encik Syed beli aircond RM3 200, bayar tunai RM2 000, kekurangan RM1 200 dibayar kad kredit dalam tempoh tanpa faedah. Berapa faedah dikenakan jika dibayar penuh dalam tempoh tersebut?", ["RM0 (tiada faedah dalam tempoh tanpa faedah)", "RM120", "RM12", "RM1 200"], 0],
  ["Hard", "Cik Chin beli beg dari Syarikat L Singapura SGD250+SGD50 penghantaran=SGD300, kad kredit kena caj tambahan 1% transaksi luar negara. Hitung caj tambahan dalam SGD.", ["SGD3.00 (300x0.01)", "SGD30.00", "SGD0.30", "SGD300"], 0],
  ["Hard", "Daripada soalan sebelumnya, Syarikat V Malaysia tawar RM799 percuma penghantaran. Jika SGD1=RM3.30 dan jumlah kos Syarikat L (SGD303) ditukar ke RM, mana lebih murah?", ["Bergantung kiraan: SGD303x3.30=RM999.90, jadi Syarikat V (RM799) lebih murah", "Syarikat L lebih murah", "Sama harga", "Tidak dapat dibandingkan"], 0],
  ["Hard", "Apakah kesilapan dalam pernyataan: 'Faedah atas baki dikira menggunakan prinsipal asal setiap bulan'?", ["Sepatutnya faedah atas baki dikira semula berdasarkan baki terkini setiap bulan, bukan prinsipal asal", "Pernyataan ini betul", "Sepatutnya guna faedah mudah", "Sepatutnya guna ROI"], 0],
  ["Hard", "Mengapa faedah kompaun memberikan pulangan lebih tinggi berbanding faedah mudah untuk P, r, t yang sama?", ["Faedah kompaun dikira atas prinsipal DAN faedah terkumpul sebelumnya", "Kadar faedah kompaun automatik lebih tinggi", "Tempoh faedah kompaun lebih lama", "Faedah kompaun tidak dikenakan cukai"], 0],
  ["Hard", "Encik Hussein beli rumah RM300 000, bayar pendahuluan 10%=RM30 000, jual RM600 000 selepas 20 tahun, pinjaman dilunaskan RM475 000, sewa terkumpul RM60 000. Anggarkan jumlah pulangan jika tiada kos lain.", ["Keuntungan modal=600000-475000-30000=95000; jumlah pulangan=60000+95000=155000", "Jumlah pulangan=600000", "Jumlah pulangan=300000", "Jumlah pulangan=60000"], 0],
  ["Hard", "Daripada soalan sebelumnya, hitung ROI berdasarkan kos awal RM300 000.", ["ROI=(155000/300000)x100%≈51.7%", "ROI=200%", "ROI=20%", "ROI=100%"], 0],
]);
