import type { Difficulty, QuizQuestion } from "@/data/content";

import { MATH_F3_C3_QUIZ_VISUALS } from "./quiz-visuals";
import { MATH_F3_C3_QUIZ_EXPLANATIONS } from "./quiz-explanations";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c3-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 3",
    lang: "bm",
    question,
    options,
    answerIndex,
    mathNotation: "indices",
    visual: MATH_F3_C3_QUIZ_VISUALS[index + 1],
    explanation: MATH_F3_C3_QUIZ_EXPLANATIONS[index + 1].bm,
  }));
}

export const mathF3C3QuizzesBM: QuizQuestion[] = buildQuiz([
  ["Easy", "Apakah formula faedah mudah?", ["I = Prt", "I = P + rt", "I = P/rt", "I = Pr + t"], 0],
  ["Easy", "Apakah maksud P dalam I=Prt?", ["Prinsipal", "Peratus", "Pulangan", "Pinjaman bulanan"], 0],
  ["Easy", "Apakah maksud r dalam I = Prt, apabila t dalam tahun?", ["Kadar faedah tahunan dalam perpuluhan", "Risiko", "Pulangan", "Rebat"], 0],
  ["Easy", "Apakah maksud t dalam I=Prt?", ["Tempoh dalam tahun", "Jumlah transaksi", "Tarikh", "Tabungan"], 0],
  ["Easy", "Encik Zainal menyimpan RM4 000 pada kadar faedah mudah 2% setahun. Hitung faedah selepas 1 tahun.", ["RM80", "RM800", "RM8", "RM40"], 0],
  ["Easy", "Dalam perbandingan akaun bank, akaun manakah biasanya menawarkan kadar faedah lebih tinggi dengan tempoh simpanan ditetapkan?", ["Akaun simpanan tetap", "Akaun semasa", "Akaun simpanan biasa", "Dompet digital"], 0],
  ["Easy", "Apakah jenis pelaburan dengan pulangan dividen dan keuntungan modal?", ["Saham", "Akaun simpanan", "Akaun semasa", "Tabung kecemasan"], 0],
  ["Easy", "Apakah formula nilai matang faedah kompaun?", ["MV = P(1+r/n)^(nt)", "MV = Prt", "MV = P + rt", "MV = Pr/nt"], 0],
  ["Easy", "Apakah maksud n dalam MV=P(1+r/n)^(nt)?", ["Kekerapan pengkompaunan setahun", "Nombor pelabur", "Nilai nominal", "Nilai bersih"], 0],
  ["Easy", "Apakah formula ROI?", ["(Jumlah pulangan/kos pelaburan) × 100%", "Jumlah pulangan - kos", "Kos/jumlah pulangan", "Jumlah pulangan + kos"], 0],
  ["Easy", "Apakah tiga faktor sebelum melabur?", ["Risiko, pulangan, kecairan", "Harga, warna, jenama", "Lokasi, saiz, warna", "Tarikh, masa, tempat"], 0],
  ["Easy", "Apakah maksud kecairan?", ["Keupayaan menukar pelaburan kepada tunai dengan segera", "Jumlah faedah", "Kadar pulangan", "Risiko pelaburan"], 0],
  ["Easy", "Apakah maksud kredit?", ["Perjanjian meminjam wang/barang untuk dibayar kemudian", "Wang simpanan", "Pelaburan saham", "Faedah kompaun"], 0],
  ["Easy", "Kad kredit dalam soalan ini memberikan tempoh tanpa faedah 20 hari dari tarikh penyata. Selepas 7 hari, berapa hari lagi sehingga tamat tempoh itu?", ["13 hari", "20 hari", "27 hari", "7 hari"], 0],
  ["Easy", "Kad kredit menetapkan bayaran minimum sebagai 5% daripada baki penyata atau RM50, yang mana lebih tinggi. Jika baki ialah RM800, hitung bayaran minimum.", ["RM50", "RM40", "RM80", "RM800"], 0],
  ["Easy", "Apakah formula bayaran balik pinjaman faedah sama rata?", ["A = P + Prt", "A = P × rt", "A = P - rt", "A = Prt"], 0],
  ["Easy", "Apakah formula ansuran bulanan?", ["A / bilangan bulan", "A × bilangan bulan", "A - bilangan bulan", "A + bilangan bulan"], 0],
  ["Easy", "Yang manakah boleh menjadi kelebihan kad kredit dengan program ganjaran?", ["Rebat tunai dan mata ganjaran", "Faedah percuma selamanya", "Tiada caj sama sekali", "Tiada had perbelanjaan"], 0],
  ["Easy", "Apakah kekurangan kad kredit?", ["Caj faedah dan risiko berbelanja lebih", "Tiada kelemahan", "Faedah sentiasa rendah", "Tidak boleh digunakan dalam talian"], 0],
  ["Easy", "Apakah strategi pemurataan kos?", ["Melabur amaun tetap secara berkala tanpa kira keadaan pasaran", "Melabur sekali gus sahaja", "Tidak melabur sama sekali", "Melabur hanya semasa harga tinggi"], 0],
  ["Medium", "Encik Badrul menyimpan RM5 000 pada kadar faedah mudah 3% setahun selama 2 tahun. Hitung jumlah faedah.", ["RM300", "RM150", "RM600", "RM450"], 0],
  ["Medium", "Cik Wong menyimpan RM10 000 pada kadar faedah mudah 4% setahun. Hitung faedah selepas 6 bulan.", ["RM200", "RM400", "RM100", "RM800"], 0],
  ["Medium", "RM10 000 disimpan pada kadar 5% setahun, dikompaun bulanan (n = 12), selama 1 tahun. Hitung nilai matang kepada sen terdekat.", ["RM10 511.62", "RM10 500.00", "RM10 050.00", "RM11 000.00"], 0],
  ["Medium", "Dua simpanan masing-masing RM10 000 pada kadar tahunan nominal 5% selama 1 tahun, tanpa pengeluaran atau caj. Simpanan A dikompaun suku tahunan (n = 4), B bulanan (n = 12). Yang manakah nilai matang lebih tinggi?", ["Simpanan B", "Simpanan A", "Nilai sama", "Tidak boleh ditentukan"], 0],
  ["Medium", "Encik Osman simpan RM20 000 prinsip wadiah, terima RM20 500 selepas 1 tahun. Hitung peratus hibah.", ["2.5%", "5%", "25%", "0.25%"], 0],
  ["Medium", "Jumlah pulangan pelaburan Encik Yusuf ialah RM456 000 dan kos pelaburan RM600 000. Hitung ROI.", ["76%", "65%", "84%", "60%"], 0],
  ["Medium", "Puan Linda labur RM20 000 sekali gus pada RM2.00/unit. Berapa unit diperoleh?", ["10 000 unit", "20 000 unit", "5 000 unit", "2 000 unit"], 0],
  ["Medium", "Puan Esther melabur RM20 000 melalui strategi pemurataan kos dan memperoleh 10 626 unit. Hitung kos purata seunit kepada sen terdekat.", ["RM1.88", "RM2.00", "RM1.50", "RM2.50"], 0],
  ["Medium", "Puan Linda membayar RM20 000 untuk 10 000 unit, manakala Puan Esther membayar RM20 000 untuk 10 626 unit pelaburan yang sama. Siapakah memperoleh kos purata seunit lebih rendah?", ["Puan Esther", "Puan Linda", "Kos purata sama", "Tidak dapat ditentukan"], 0],
  ["Medium", "Encik Azlan pinjam RM10 000, kadar 4% sama rata, 7 tahun. Hitung jumlah bayaran balik A.", ["RM12 800", "RM10 400", "RM14 000", "RM11 600"], 0],
  ["Medium", "Jumlah bayaran balik pinjaman Encik Azlan ialah RM12 800, dibayar dalam 84 ansuran bulanan sama. Hitung ansuran bulanan kepada sen terdekat.", ["RM152.38", "RM142.86", "RM166.67", "RM120.00"], 0],
  ["Medium", "Encik Harith meminjam RM10 000 pada kadar faedah tahunan 6% atas baki berkurangan, dengan ansuran RM150 pada akhir bulan. Gunakan kadar bulanan 6% ÷ 12. Hitung faedah bulan pertama.", ["RM50.00", "RM60.00", "RM45.00", "RM100.00"], 0],
  ["Medium", "Baki pinjaman Encik Harith pada awal bulan kedua ialah RM9 900. Kadar faedah tahunan atas baki berkurangan ialah 6%. Gunakan kadar bulanan 6% ÷ 12. Hitung faedah bulan kedua.", ["RM49.50", "RM50.00", "RM48.00", "RM51.00"], 0],
  ["Medium", "Baki awal pinjaman Encik Harith ialah RM10 000. Faedah bulan pertama RM50 ditambah sebelum ansuran RM150 dibayar. Hitung baki selepas ansuran itu.", ["RM9 900", "RM9 850", "RM10 050", "RM9 950"], 0],
  ["Medium", "Cik Kayal pinjam RM X pada 5% sama rata, 8 tahun, ansuran bulanan RM218.75. Hitung jumlah bayaran balik A.", ["RM21 000", "RM18 375", "RM1 750", "RM13 125"], 0],
  ["Medium", "Cik Kayal membayar balik RM21 000 untuk pinjaman pada kadar faedah sama rata 5% setahun selama 8 tahun. Jika A = P + Prt, hitung prinsipal P.", ["RM15 000", "RM21 000", "RM10 500", "RM7 500"], 0],
  ["Medium", "Encik Murugan pinjam RM16 000, bayar balik 5 tahun, ansuran bulanan RM320. Hitung jumlah bayaran balik.", ["RM19 200", "RM16 000", "RM17 600", "RM20 000"], 0],
  ["Medium", "Encik Murugan meminjam RM16 000 dan membayar balik RM19 200 keseluruhannya. Hitung jumlah faedah.", ["RM3 200", "RM1 600", "RM4 800", "RM2 000"], 0],
  ["Medium", "Encik Murugan meminjam RM16 000 selama 5 tahun dan membayar jumlah faedah RM3 200. Hitung kadar faedah sama rata setahun menggunakan I = Prt.", ["4%", "5%", "3%", "6%"], 0],
  ["Medium", "Encik Vincent tiada penjamin. Bank A menawarkan pinjaman 9 tahun pada 4.5% tanpa penjamin; Bank B menawarkan 6 tahun pada 5% dan mewajibkan penjamin. Berdasarkan keperluan penjamin sahaja, bank manakah memenuhi syaratnya?", ["Bank A", "Bank B", "Kedua-dua bank", "Tiada bank"], 0],
  ["Hard", "Encik Yusuf membeli kedai RM600 000 dengan pendahuluan 10%, kemudian menjualnya RM1 300 000. Baki pinjaman yang diselesaikan RM486 000; ansuran terdahulu RM450 000; kos guaman RM15 000; duti setem RM15 000; komisen RM18 000. Hitung keuntungan modal bersih selepas menolak semua kos tersebut termasuk pendahuluan.", ["RM256 000", "RM700 000", "RM814 000", "RM200 000"], 0],
  ["Hard", "Encik Yusuf memperoleh keuntungan modal bersih RM256 000 dan sewa terkumpul RM200 000. Hitung jumlah pulangan.", ["RM456 000", "RM256 000", "RM700 000", "RM600 000"], 0],
  ["Hard", "Encik Zainal memegang 6 000 unit syer pada nilai RM1 seunit. Dividen 6% dikira atas nilai syer asal sebelum bonus. Hitung jumlah dividen.", ["RM360", "RM600", "RM3 600", "RM60"], 0],
  ["Hard", "Encik Zainal memegang 6 000 unit syer dan menerima 1 syer bonus bagi setiap 2 unit dipegang. Hitung bilangan syer bonus.", ["3 000 unit", "6 000 unit", "1 500 unit", "12 000 unit"], 0],
  ["Hard", "Encik Zainal memegang 6 000 unit syer dan menerima 3 000 unit syer bonus. Hitung jumlah syer selepas bonus.", ["9 000 unit", "6 000 unit", "3 000 unit", "12 000 unit"], 0],
  ["Hard", "Encik Kishendran menyimpan RM5 000 pada kadar 4% setahun, dikompaun setiap 3 bulan (n = 4), selama 3 tahun. Hitung faedah terkumpul (MV − P) kepada sen terdekat.", ["RM634.13", "RM600.00", "RM500.00", "RM700.00"], 0],
  ["Hard", "Encik Oswald pinjam RM15 000, kadar 5% sama rata, 5 tahun. Hitung jumlah faedah dibayar.", ["RM3 750", "RM750", "RM7 500", "RM1 500"], 0],
  ["Hard", "Encik Oswald meminjam RM15 000 pada kadar faedah sama rata 5% setahun selama 5 tahun. Hitung jumlah bayaran balik A dan ansuran bulanan bagi 60 bulan.", ["A = RM18 750; ansuran RM312.50", "A = RM15 000; ansuran RM250.00", "A = RM18 750; ansuran RM375.00", "A = RM20 000; ansuran RM333.33"], 0],
  ["Hard", "Encik Syed membeli penyaman udara RM3 200, membayar tunai RM2 000 dan baki RM1 200 menggunakan kad kredit. Kad itu memberikan tempoh tanpa faedah untuk pembelian ini jika baki penyata dibayar penuh tepat pada masanya. Semua syarat dipenuhi. Hitung faedah dikenakan.", ["RM0", "RM120", "RM12", "RM1 200"], 0],
  ["Hard", "Cik Chin beli beg dari Syarikat L Singapura SGD250+SGD50 penghantaran=SGD300, kad kredit kena caj tambahan 1% transaksi luar negara. Hitung caj tambahan dalam SGD.", ["SGD3.00", "SGD30.00", "SGD0.30", "SGD300.00"], 0],
  ["Hard", "Syarikat L menawarkan beg pada jumlah harga SGD303 termasuk penghantaran dan caj kad. Syarikat V menawarkan beg sama pada RM799 termasuk penghantaran. Gunakan SGD1 = RM3.30 dan abaikan caj lain. Yang manakah lebih murah?", ["Syarikat V", "Syarikat L", "Harga sama", "Tidak dapat dibandingkan"], 0],
  ["Hard", "Apakah kesilapan dalam pernyataan: 'Faedah atas baki dikira menggunakan prinsipal asal setiap bulan'?", ["Sepatutnya faedah atas baki dikira semula berdasarkan baki terkini setiap bulan, bukan prinsipal asal", "Pernyataan ini betul", "Sepatutnya guna faedah mudah", "Sepatutnya guna ROI"], 0],
  ["Hard", "Dua simpanan mempunyai prinsipal dan kadar faedah tahunan positif yang sama. Faedah kompaun dikreditkan setiap tahun selama 2 tahun tanpa pengeluaran atau caj. Mengapa pulangannya lebih tinggi daripada faedah mudah bagi tempoh sama?", ["Faedah kompaun dikira atas prinsipal DAN faedah terkumpul sebelumnya", "Kadar faedah kompaun automatik lebih tinggi", "Tempoh faedah kompaun lebih lama", "Faedah kompaun tidak dikenakan cukai"], 0],
  ["Hard", "Encik Hussein membeli rumah RM300 000 dengan pendahuluan RM30 000 dan menjualnya RM600 000 selepas 20 tahun. Jumlah bayaran pinjaman kepada bank sepanjang tempoh itu ialah RM475 000 dan sewa terkumpul RM60 000. Pinjaman selesai sepenuhnya. Abaikan kos lain. Hitung jumlah pulangan bersih.", ["RM155 000", "RM600 000", "RM300 000", "RM60 000"], 0],
  ["Hard", "Encik Hussein memperoleh jumlah pulangan bersih RM155 000. Gunakan kos pelaburan awal RM300 000 sebagai penyebut. Hitung ROI kepada 1 tempat perpuluhan.", ["51.7%", "200.0%", "20.0%", "100.0%"], 0],
]);
