import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c1-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 1",
    lang: "bm",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C1QuizzesBM: QuizQuestion[] = buildQuiz([
  ["Easy", "Dalam an, apakah nama bagi a?", ["Asas", "Indeks", "Kuasa", "Faktor"], 0],
  ["Easy", "Dalam an, apakah nama bagi n?", ["Indeks atau kuasa", "Asas", "Punca", "Pekali"], 0],
  ["Easy", "Tukar 5 x 5 x 5 x 5 x 5 x 5 kepada bentuk indeks.", ["5^6", "6^5", "5^5", "6^6"], 0],
  ["Easy", "Tukar (-2) x (-2) x (-2) kepada bentuk indeks.", ["(-2)^3", "-2^3", "(-2)^2", "2^3"], 0],
  ["Easy", "Apakah nilai 4^3?", ["64", "12", "48", "16"], 0],
  ["Easy", "Apakah hukum bagi am x an?", ["a^(m+n)", "a^(m-n)", "a^(mn)", "a^(m/n)"], 0],
  ["Easy", "Apakah hukum bagi am ÷ an?", ["a^(m-n)", "a^(m+n)", "a^(mn)", "a^(n-m)"], 0],
  ["Easy", "Apakah hukum bagi (am)n?", ["a^(mn)", "a^(m+n)", "a^(m-n)", "a^(m/n)"], 0],
  ["Easy", "Apakah nilai a0 jika a ≠ 0?", ["1", "0", "a", "Tidak ditakrifkan"], 0],
  ["Easy", "Apakah bentuk lain bagi a-n?", ["1/an", "-an", "an", "-1/an"], 0],
  ["Easy", "Ringkaskan 7^2 x 7^3.", ["7^5", "7^6", "14^5", "7^1"], 0],
  ["Easy", "Ringkaskan 4^5 ÷ 4^2.", ["4^3", "4^7", "4^10", "4^2"], 0],
  ["Easy", "Ringkaskan (3^4)^2.", ["3^8", "3^6", "3^4", "3^2"], 0],
  ["Easy", "Apakah maksud a1/n?", ["Punca kuasa ke-n bagi a", "a didarab n", "a kuasa n", "a ditolak n"], 0],
  ["Easy", "Apakah punca kuasa tiga bagi 8?", ["2", "3", "4", "8"], 0],
  ["Easy", "Ringkaskan 2k^2 x 4k^3.", ["8k^5", "6k^5", "8k^6", "6k^6"], 0],
  ["Easy", "Permudahkan m^7 ÷ m^2 ÷ m^4.", ["m", "m^13", "m^9", "m^5"], 0],
  ["Easy", "Tukar 81 kepada bentuk indeks berasaskan 3.", ["3^4", "3^3", "3^5", "3^2"], 0],
  ["Easy", "Apakah nilai 2^(-2)?", ["1/4", "-4", "4", "-1/4"], 0],
  ["Easy", "Apakah punca kuasa empat bagi 81?", ["3", "9", "4", "27"], 0],

  ["Medium", "Ringkaskan m^3 x n^2 x m^4 x n^5.", ["m^7 n^7", "m^7 n^12", "m^12 n^7", "m^9 n^9"], 0],
  ["Medium", "Ringkaskan 25x^2y^3 ÷ 5xy.", ["5xy^2", "5x^2y^2", "5xy^3", "20xy^2"], 0],
  ["Medium", "Ringkaskan (p^2 q^3 r)^4.", ["p^8 q^12 r^4", "p^6 q^7 r^5", "p^8 q^12 r^1", "p^2 q^3 r^4"], 0],
  ["Medium", "Ringkaskan (5m^4 n^3)^2.", ["25m^8n^6", "10m^8n^6", "25m^6n^5", "25m^4n^3"], 0],
  ["Medium", "Ringkaskan (0.2)^2 x (0.2)^4 x (0.2)^5.", ["(0.2)^11", "(0.2)^9", "(0.2)^10", "(0.2)^20"], 0],
  ["Medium", "Tukar a^(-2) kepada bentuk positif.", ["1/a^2", "-1/a^2", "1/a^(-2)", "a^2"], 0],
  ["Medium", "Tukar (2/5)^(-10) kepada bentuk indeks positif.", ["(5/2)^10", "(2/5)^10", "(5/2)^(-10)", "-(2/5)^10"], 0],
  ["Medium", "Nilaikan 2^3 ÷ 2^5.", ["1/4", "4", "1/8", "8"], 0],
  ["Medium", "Tukar 8^(1/3) kepada bentuk punca kuasa dan nilaikan.", ["Punca kuasa tiga 8 = 2", "Punca kuasa dua 8", "8 kuasa 3", "1/8"], 0],
  ["Medium", "Tukar 81^(3/4) kepada bentuk punca kuasa dan nilaikan.", ["(punca kuasa empat 81)^3 = 27", "81^3", "9^3", "3^4"], 0],
  ["Medium", "Permudahkan m^(1/2) x n^(3/4).", ["m^(1/2) n^(3/4)", "m n", "mn^(1/2)", "(mn)^(1/2)"], 0],
  ["Medium", "Apakah nilai 5^4?", ["625", "20", "125", "256"], 0],
  ["Medium", "Apakah nilai (-7)^3?", ["-343", "343", "-21", "21"], 0],
  ["Medium", "Apakah nilai (2/4)^2 dalam bentuk termudah?", ["1/4", "1/2", "4/16", "2/4"], 0],
  ["Medium", "Permudahkan (-3x)^3 x (2x^3y^-4)^2.", ["-108x^9y^-8", "108x^9y^8", "-108x^6y^-8", "108x^5y^-8"], 0],
  ["Medium", "Selesaikan 3^x x 9^(x+5) ÷ 3^4 = 1 bagi nilai x.", ["x = -2", "x = 2", "x = -6", "x = 0"], 0],
  ["Medium", "Permudahkan h^3 x h^10.", ["h^13", "h^30", "h^7", "h^3"], 0],
  ["Medium", "Bandingkan (4^2)^3 dengan (4^3)^2.", ["Kedua-duanya sama dengan 4^6", "(4^2)^3 lebih besar", "(4^3)^2 lebih besar", "Tidak boleh dibandingkan"], 0],
  ["Medium", "Permudahkan -25h^4 ÷ 5h^2 ÷ h.", ["-5h^1 = -5h", "-5h^2", "5h", "-5h^7"], 0],
  ["Medium", "Tukar 2m^(-3) kepada bentuk positif.", ["2/m^3", "-2/m^3", "1/2m^3", "2m^3"], 0],

  ["Hard", "Selesaikan persamaan serentak 25^m x 5^n = 5^8 dan 2^m x 2^(-n) = 2 untuk m dan n.", ["m=3, n=2", "m=2, n=3", "m=4, n=0", "m=1, n=6"], 0],
  ["Hard", "Jika 16(4^x) = 16^y dan 3(9^x) = 27^y, hitung nilai x dan y.", ["x=2, y=2.4 (selesaikan serentak)", "x=1, y=1", "x=4, y=4", "x=0, y=0"], 0],
  ["Hard", "Permudahkan (cube root of c^2 d^3 e) x c^(-1)d^2e^(-1), ungkapkan sebagai indeks pecahan.", ["c^(-1/3) d^(7/3) e^(-2/3)", "c^(1/3) d^(3) e", "c d e", "c^2 d^3 e"], 0],
  ["Hard", "Permudahkan (square root of (m n)) x (mn^3)^(1/2) ÷ (m^(-1) square root of n^3).", ["Gunakan hukum indeks pecahan; jawapan dalam bentuk m dan n berindeks pecahan", "mn", "m^2n^2", "1"], 1],
  ["Hard", "Tukarkan 81^(3/4) kepada bentuk (a^m)^(1/n) dan (a^(1/n))^m, kemudian nilaikan.", ["(81^3)^(1/4) = (81^(1/4))^3 = 27", "81^4", "81^(1/3)", "3"], 0],
  ["Hard", "Jika 3^x x 9^(x+5) ÷ 3^4 = 1, apakah langkah pertama yang betul?", ["Tukar 9 kepada 3^2 supaya semua asas sama", "Tukar 3 kepada 9", "Darab terus tanpa menukar asas", "Abaikan 3^4"], 0],
  ["Hard", "Permudahkan (square root 25x^3yz^2) x 4x^2z, ungkapkan dalam bentuk indeks pecahan.", ["20x^(7/2) y^(1/2) z^3", "20x^3yz^3", "100x^5yz^3", "5x^(7/2)yz^3"], 0],
  ["Hard", "Salin dan lengkapkan: 5^6 = 5^? x 5^5. Apakah nilai ?", ["1", "11", "30", "6"], 0],
  ["Hard", "Salin dan lengkapkan: 5^12 ÷ 5^? = 5^2. Apakah nilai ?", ["10", "14", "6", "24"], 0],
  ["Hard", "Apakah nilai bagi (5^?)^3 jika hasilnya 5^9?", ["3", "6", "12", "27"], 0],
  ["Hard", "Jika a-n = 1/an dibuktikan menggunakan hukum pembahagian, apakah persamaan permulaan yang sesuai?", ["a^0 ÷ a^n = a^(0-n) = a^(-n), dan a^0 ÷ a^n = 1/a^n", "a^n x a^0", "a^n ÷ a^0", "a^n + a^0"], 0],
  ["Hard", "Apakah hubungan antara n-th root of a dengan a^(1/n) yang membolehkan pembuktian a^0=1?", ["a^(n/n) = a^1 dan juga (n-th root of a)^n = a, jadi a^(1/n) ialah n-th root of a", "Tiada hubungan", "a^(1/n) = a^n", "a^(1/n) = 1/a^n"], 0],
  ["Hard", "Lengkapkan rajah: 5^9 = 5^? x 5^5; (1/5)^? = 5^(-3); 5^? = 1/5^3 menggunakan hukum indeks yang sesuai.", ["? = 4 untuk yang pertama; ? = 3 dan -3 untuk yang lain mengikut hukum negatif", "Semua ? = 0", "Semua ? = 9", "Tidak boleh diselesaikan"], 0],
  ["Hard", "Chong mendapat 16(4^x) = 16^y dan Navin mendapat 3(9^x) = 27^y. Apakah asas sepunya yang perlu digunakan untuk setiap persamaan?", ["Asas 2 untuk persamaan pertama, asas 3 untuk persamaan kedua", "Asas 10 untuk kedua-duanya", "Asas 5 untuk kedua-duanya", "Tidak perlu asas sepunya"], 0],
  ["Hard", "Permudahkan (m^(-1) square root of n^3) sebagai penyebut dalam ungkapan pecahan indeks, apakah bentuk indeks bagi penyebut itu?", ["m^(-1) n^(3/2)", "m n^3", "m^(-1) n^3", "m n^(3/2)"], 0],
  ["Hard", "Dalam projek Segi Tiga Pascal yang dikaitkan dengan bab ini, hukum indeks manakah yang membantu mempercepatkan pengiraan kuasa besar?", ["Hukum kuasa bagi kuasa, (am)n = amn", "Hukum tambah sahaja", "Hukum tolak sahaja", "Tiada kaitan"], 0],
  ["Hard", "Mengapa 0^0 tidak ditakrifkan dalam hukum indeks sifar?", ["Kerana pembuktian a^0=1 menggunakan pembahagian a^n/a^n yang tidak sah apabila a=0", "Kerana 0 ialah nombor genap", "Kerana 0 tiada asas", "Kerana 0 sentiasa negatif"], 0],
  ["Hard", "Apakah kesilapan dalam langkah ini: '(-2)^3 = -2 x 3 = -6'?", ["Sepatutnya (-2) x (-2) x (-2) = -8, bukan pendaraban dengan indeks", "Jawapan -6 adalah betul", "Sepatutnya 2 x 3", "Tiada kesilapan"], 0],
]);
