import type { Difficulty, QuizQuestion } from "@/data/content";
import { MATH_F3_C1_QUIZ_VISUALS } from "./quiz-visuals";
import { MATH_F3_C1_EXPLANATIONS } from "./quiz-explanations";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c1-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 1",
    lang: "dlp",
    question,
    options,
    answerIndex,
    mathNotation: "indices",
    visual: MATH_F3_C1_QUIZ_VISUALS[index + 1],
    explanation: MATH_F3_C1_EXPLANATIONS[index + 1]["dlp"],
  }));
}

export const mathF3C1QuizzesDLP: QuizQuestion[] = buildQuiz([
  ["Easy", "In a^n, what is a called?", ["Base", "Index", "Power", "Factor"], 0],
  ["Easy", "In a^n, what is n called?", ["Index or power", "Base", "Root", "Coefficient"], 0],
  ["Easy", "Write 5 × 5 × 5 × 5 × 5 × 5 in index form.", ["5^6", "6^5", "5^5", "6^6"], 0],
  ["Easy", "Write (-2) × (-2) × (-2) in index form.", ["(-2)^3", "-2^2", "(-2)^2", "2^3"], 0],
  ["Easy", "What is the value of 4^3?", ["64", "12", "48", "16"], 0],
  ["Easy", "What is the law for a^m × a^n?", ["a^(m+n)", "a^(m-n)", "a^(mn)", "a^(m/n)"], 0],
  ["Easy", "What is the law for a^m ÷ a^n? (a ≠ 0).", ["a^(m-n)", "a^(m+n)", "a^(mn)", "a^(n-m)"], 0],
  ["Easy", "What is the law for (a^m)^n?", ["a^(mn)", "a^(m+n)", "a^(m-n)", "a^(m/n)"], 0],
  ["Easy", "What is the value of a^0 if a ≠ 0?", ["1", "0", "a", "Undefined"], 0],
  ["Easy", "What is another form of a^(-n), a ≠ 0?", ["1/(a^n)", "-a^n", "a^n", "-1/(a^n)"], 0],
  ["Easy", "Simplify 7^2 × 7^3.", ["7^5", "7^6", "14^5", "7^1"], 0],
  ["Easy", "Simplify 4^5 ÷ 4^2.", ["4^3", "4^7", "4^10", "4^2"], 0],
  ["Easy", "Simplify (3^4)^2.", ["3^8", "3^6", "3^4", "3^2"], 0],
  ["Easy", "What does a^(1/n) mean, where a > 0 and n is a positive integer, n ≥ 2?", ["The nth root of a", "a multiplied by n", "a raised to n", "a minus n"], 0],
  ["Easy", "What is the cube root of 8?", ["2", "3", "4", "8"], 0],
  ["Easy", "Simplify 2k^2 × 4k^3.", ["8k^5", "6k^5", "8k^6", "6k^6"], 0],
  ["Easy", "Simplify m^7 ÷ m^2 ÷ m^4 (m ≠ 0).", ["m", "m^13", "m^9", "m^5"], 0],
  ["Easy", "Write 81 in index form with base 3.", ["3^4", "3^3", "3^5", "3^2"], 0],
  ["Easy", "What is the value of 2^(-2)?", ["1/4", "-4", "4", "-1/4"], 0],
  ["Easy", "What is the fourth root of 81?", ["3", "9", "4", "27"], 0],

  ["Medium", "Simplify m^3 × n^2 × m^4 × n^5.", ["m^7 n^7", "m^7 n^12", "m^12 n^7", "m^9 n^9"], 0],
  ["Medium", "Simplify 25x^2y^3 ÷ 5xy (x, y ≠ 0).", ["5xy^2", "5x^2y^2", "5xy^3", "20xy^2"], 0],
  ["Medium", "Simplify (p^2 q^3 r)^4.", ["p^8 q^12 r^4", "p^6 q^7 r^5", "p^8 q^12 r^1", "p^2 q^3 r^4"], 0],
  ["Medium", "Simplify (5m^4 n^3)^2.", ["25m^8n^6", "10m^8n^6", "25m^6n^5", "25m^4n^3"], 0],
  ["Medium", "Simplify (0.2)^2 × (0.2)^4 × (0.2)^5.", ["(0.2)^11", "(0.2)^9", "(0.2)^10", "(0.2)^20"], 0],
  ["Medium", "Express a^(-2) with a positive index (a ≠ 0).", ["1/(a^2)", "-1/(a^2)", "1/(a^(-2))", "a^2"], 0],
  ["Medium", "Express (2/5)^(-10) with a positive index.", ["(5/2)^10", "(2/5)^10", "(5/2)^(-10)", "-(2/5)^10"], 0],
  ["Medium", "Evaluate 2^3 ÷ 2^5.", ["1/4", "4", "1/8", "8"], 0],
  ["Medium", "Convert 8^(1/3) to root form and evaluate.", ["Cube root of 8 = 2", "Square root of 8", "8 to the power 3", "1/8"], 0],
  ["Medium", "Convert 81^(3/4) to root form and evaluate.", ["(fourth root of 81)^3 = 27", "81^3", "9^3", "3^4"], 0],
  ["Medium", "Simplify m^(1/2) × n^(3/4) (m, n > 0).", ["m^(1/2) n^(3/4)", "m n", "mn^(1/2)", "(mn)^(1/2)"], 0],
  ["Medium", "What is the value of 5^4?", ["625", "20", "125", "256"], 0],
  ["Medium", "What is the value of (-7)^3?", ["-343", "343", "-21", "21"], 0],
  ["Medium", "What is (2/4)^2 in simplest form?", ["1/4", "1/2", "4/16", "2/4"], 0],
  ["Medium", "Simplify (-3x)^3 × (2x^3y^(-4))^2 (y ≠ 0).", ["-108x^9y^(-8)", "108x^9y^8", "-108x^6y^(-8)", "108x^5y^(-8)"], 0],
  ["Medium", "Solve 3^x × 9^(x+5) ÷ 3^4 = 1 for x.", ["x = -2", "x = 2", "x = -6", "x = 0"], 0],
  ["Medium", "Simplify h^3 × h^10.", ["h^13", "h^30", "h^7", "h^3"], 0],
  ["Medium", "Compare (4^2)^3 with (4^3)^2.", ["Both equal 4^6", "(4^2)^3 is bigger", "(4^3)^2 is bigger", "Cannot be compared"], 0],
  ["Medium", "Simplify -25h^4 ÷ 5h^2 ÷ h (h ≠ 0).", ["-5h^1 = -5h", "-5h^2", "5h", "-5h^7"], 0],
  ["Medium", "Express 2m^(-3) with a positive index (m ≠ 0).", ["2/(m^3)", "-2/(m^3)", "1/(2m^3)", "2m^3"], 0],

  ["Hard", "Solve the simultaneous equations 25^m × 5^n = 5^8 and 2^m × 2^(-n) = 2 for m and n.", ["m=3, n=2", "m=2, n=3", "m=4, n=0", "m=1, n=6"], 0],
  ["Hard", "If 16(4^x) = 16^y and 3(9^x) = 27^y, find × and y.", ["x = 4, y = 3", "x=1, y=1", "x=4, y=4", "x=0, y=0"], 0],
  ["Hard", "Simplify (c^2d^3e)^(1/3) × c^(-1)d^2e^(-1) using fractional indices, where c, d, e > 0.", ["c^(-1/3) d^3 e^(-2/3)", "c^(1/3) d^(3) e", "c d e", "c^2 d^3 e"], 0],
  ["Hard", "Simplify √(mn) × (mn^3)^(1/2) ÷ (m^(-1)√(n^3)), where m, n > 0.", ["m^2 n^(1/2)", "mn", "m^2n^2", "1"], 0],
  ["Hard", "Convert 81^(3/4) to (a^m)^(1/n) and (a^(1/n))^m forms, then evaluate.", ["(81^3)^(1/4) = (81^(1/4))^3 = 27", "81^4", "81^(1/3)", "3"], 0],
  ["Hard", "If 3^x × 9^(x+5) ÷ 3^4 = 1, what is the correct first step?", ["Convert 9 to 3^2 so all bases are equal", "Convert 3 to 9", "Multiply directly without converting bases", "Ignore 3^4"], 0],
  ["Hard", "Simplify √(25x^3yz^2) × 4x^2z using fractional indices, where x, y, z > 0.", ["20x^(7/2) y^(1/2) z^2", "20x^3yz^3", "100x^5yz^3", "5x^(7/2)yz^3"], 0],
  ["Hard", "Complete: 5^6 = 5^? × 5^5. Find ?.", ["1", "11", "30", "6"], 0],
  ["Hard", "Complete: 5^12 ÷ 5^? = 5^2. Find ?.", ["10", "14", "6", "24"], 0],
  ["Hard", "Find the value of ? in (5^?)^3 = 5^9.", ["3", "6", "12", "27"], 0],
  ["Hard", "To prove a^(-n) = 1/(a^n) using the division law, what is the correct starting equation? (a ≠ 0).", ["a^0 ÷ a^n = a^(0-n) = a^(-n), and a^0 ÷ a^n = 1/a^n", "a^n × a^0", "a^n ÷ a^0", "a^n + a^0"], 0],
  ["Hard", "What is the relationship between the nth root of a and a^(1/n), where a > 0 and n is a positive integer, n ≥ 2?", ["(a^(1/n))^n = a, so a^(1/n) is the nth root of a", "There is no relationship", "a^(1/n) = a^n", "a^(1/n) = 1/a^n"], 0],
  ["Hard", "Complete the diagram: 5^9 = 5^p × 5^5; (1/5)^q = 5^(-3); 5^r = 1/(5^3). Find p, q and r.", ["p = 4, q = 3, r = -3", "p = 4, q = -3, r = 3", "p = 14, q = 3, r = -3", "p = 4, q = 3, r = 3"], 0],
  ["Hard", "Chong obtained 16(4^x) = 16^y and Navin obtained 3(9^x) = 27^y. What common base should be used for each equation?", ["Base 2 for the first equation, base 3 for the second", "Base 10 for both", "Base 5 for both", "No common base is needed"], 0],
  ["Hard", "What is the index form of the denominator m^(-1)√(n^3), where m ≠ 0 and n > 0?", ["m^(-1) n^(3/2)", "m n^3", "m^(-1) n^3", "m n^(3/2)"], 0],
  ["Hard", "Which index law is used to simplify (a^m)^n?", ["The power of a power law, (a^m)^n = a^(mn)", "The addition law only", "The subtraction law only", "No connection"], 0],
  ["Hard", "Why is 0^0 undefined under the zero index law?", ["Because proving a^0=1 uses a^n/a^n which is invalid when a=0", "Because 0 is an even number", "Because 0 has no base", "Because 0 is always negative"], 0],
  ["Hard", "What is the mistake in this step: '(-2)^3 = -2 × 3 = -6'?", ["It should be (-2) × (-2) × (-2) = -8, not multiplication by the index", "The answer -6 is correct", "It should be 2 × 3", "There is no mistake"], 0],
]);
