import type { StructuredNotes } from "@/data/types";

export const sejarahF3C7Notes: StructuredNotes = {
  chapterSummary: "Bab ini menghuraikan matlamat dan bentuk penentangan masyarakat tempatan, kesan sistem pentadbiran Barat terhadap kuasa dan kehidupan tempatan, peristiwa penentangan serta kesannya.",
  quickRevision: ["7.1 Matlamat dan Bentuk Penentangan Masyarakat Tempatan: Penentangan bertujuan mempertahankan hak, kuasa, maruah, adat dan kedaulatan tempatan.","Tarikh penting 7.1: 1831-1832: Perang Naning","7.2 Sistem Pentadbiran Barat Memberikan Kesan Terhadap Kuasa Pemerintahan dan Kehidupan Masyarakat Tempatan: Sistem pentadbiran Barat menjejaskan kuasa sultan dan pembesar.","Tarikh penting 7.2: 1874: Sistem Residen bermula di Perak selepas Perjanjian Pangkor","7.3 Penentangan Masyarakat Tempatan Terhadap Kuasa Barat: Dol Said menentang British di Naning kerana isu cukai dan kedaulatan Naning.","Tarikh penting 7.3: 1831-1832: Perang Naning","7.4 Kesan Penentangan Masyarakat Tempatan: British mengalami kerugian 100,000 Pound Sterling dalam Perang Naning.","Tarikh penting 7.4: 1905: Kolej Melayu Kuala Kangsar ditubuhkan"],
  keyTerms: ["penentangan","kedaulatan","hak tempatan","adat","kuasa pembesar","Sistem Residen","cukai","undang-undang Barat","adat tempatan","Dol Said","Rentap","Dato' Maharaja Lela","Dato' Bahaman","Mat Salleh","Tok Janggut","Haji Abdul Rahman Limbong","kerugian perang","Majlis Mesyuarat Negeri","MCKK","MCS","MAS","pemantapan kuasa Barat"],
  keyExamFacts: ["Penentangan bertujuan mempertahankan hak, kuasa, maruah, adat dan kedaulatan tempatan.","Bentuk penentangan termasuk penentangan bersenjata, mencabar perjanjian, menggunakan undang-undang dan serangan terhadap pusat pentadbiran Barat.","Tokoh tempatan menentang kerana pentadbiran Barat menggugat kuasa tradisional dan kehidupan masyarakat.","Sistem pentadbiran Barat menjejaskan kuasa sultan dan pembesar.","Residen British mentadbir hasil negeri dan nasihatnya mesti dipatuhi kecuali agama Islam dan adat Melayu.","Pungutan cukai tradisional digantikan dengan cukai Barat.","Dol Said menentang British di Naning kerana isu cukai dan kedaulatan Naning.","Rentap menentang Brooke di Sarawak dan mempertahankan Bukit Sadok sehingga serangan ketiga Brooke pada tahun 1861.","Dato' Maharaja Lela dan pembesar Perak menentang J.W.W. Birch di Pasir Salak.","British mengalami kerugian 100,000 Pound Sterling dalam Perang Naning.","British membelanjakan 400,000 Pound Sterling dalam Perang Perak.","British mengalami kerugian 7000 Pound Sterling dalam Perang Pahang."],
  sections: [
    {
      title: "Bab Overview",
      subsections: [
        { title: "Sinopsis", content: "Bab ini menghuraikan matlamat dan bentuk penentangan masyarakat tempatan, kesan sistem pentadbiran Barat terhadap kuasa dan kehidupan tempatan, peristiwa penentangan serta kesannya." },
        { title: "Apa yang akan dipelajari", bulletPoints: ["7.1 Matlamat dan Bentuk Penentangan Masyarakat Tempatan","7.2 Sistem Pentadbiran Barat Memberikan Kesan Terhadap Kuasa Pemerintahan dan Kehidupan Masyarakat Tempatan","7.3 Penentangan Masyarakat Tempatan Terhadap Kuasa Barat","7.4 Kesan Penentangan Masyarakat Tempatan"] },
        { title: "Fokus UASA", bulletPoints: ["Kenal pasti kronologi, tokoh, tempat, perjanjian dan kesan.","Bezakan sebab, strategi dan kesan peluasan kuasa Barat.","Gunakan kata kunci seperti kedaulatan, pentadbiran, ekonomi, penentangan dan pemodenan."] },
      ],
    },
    {
      title: "7.1 Matlamat dan Bentuk Penentangan Masyarakat Tempatan",
      subsections: [
        { title: "Ringkasan", content: "Matlamat dan Bentuk Penentangan Masyarakat Tempatan menerangkan penentangan bertujuan mempertahankan hak, kuasa, maruah, adat dan kedaulatan tempatan. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Penentangan bertujuan mempertahankan hak, kuasa, maruah, adat dan kedaulatan tempatan.","Bentuk penentangan termasuk penentangan bersenjata, mencabar perjanjian, menggunakan undang-undang dan serangan terhadap pusat pentadbiran Barat.","Tokoh tempatan menentang kerana pentadbiran Barat menggugat kuasa tradisional dan kehidupan masyarakat.","Penentangan berlaku di Naning, Sarawak, Sabah, Perak, Pahang, Kelantan dan Terengganu."] },
        { title: "Kata kunci", bulletPoints: ["penentangan","kedaulatan","hak tempatan","adat","kuasa pembesar"] },
        { title: "Tokoh penting", bulletPoints: ["Dol Said","Rentap","Sharif Masahor","Dato' Maharaja Lela","Yamtuan Antah","Dato' Bahaman","Mat Salleh","Tok Janggut","Haji Abdul Rahman Limbong"] },
        { title: "Tarikh penting", bulletPoints: ["1831-1832: Perang Naning","1875: pembunuhan J.W.W. Birch","1895-1897: penentangan Mat Salleh","1915: penentangan Tok Janggut","1928: gerakan Haji Abdul Rahman Limbong"] },
        { title: "Tempat penting", bulletPoints: ["Naning","Bukit Sadok","Pasir Salak","Pahang","Tambunan","Kelantan","Terengganu"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Pangkor 1874"],["Undang-undang","Undang-undang Barat; peraturan cukai Barat"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Cukai membebankan","Kuasa pembesar terhakis","Adat tempatan diganggu","Tanah dan hasil dikawal Barat"] },
        { title: "Kesan", bulletPoints: ["Kebangkitan tempatan berlaku","British menggunakan kekuatan tentera dan undang-undang","Tokoh tempatan dihukum atau dibuang negeri"] },
        { title: "Kepentingan", bulletPoints: ["Membuktikan masyarakat tempatan mempertahankan maruah dan kedaulatan."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Matlamat penentangan berkait dengan kesan pentadbiran Barat dalam subtopik 7.2."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta lokasi penentangan menunjukkan kebangkitan berlaku di pelbagai negeri dan wilayah.","1831 Naning","1875 Perak","1890-an Pahang/Sabah","1915 Kelantan","1928 Terengganu"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "7.2 Sistem Pentadbiran Barat Memberikan Kesan Terhadap Kuasa Pemerintahan dan Kehidupan Masyarakat Tempatan",
      subsections: [
        { title: "Ringkasan", content: "Sistem Pentadbiran Barat Memberikan Kesan Terhadap Kuasa Pemerintahan dan Kehidupan Masyarakat Tempatan menerangkan sistem pentadbiran barat menjejaskan kuasa sultan dan pembesar. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Sistem pentadbiran Barat menjejaskan kuasa sultan dan pembesar.","Residen British mentadbir hasil negeri dan nasihatnya mesti dipatuhi kecuali agama Islam dan adat Melayu.","Pungutan cukai tradisional digantikan dengan cukai Barat.","Undang-undang tradisional terjejas apabila undang-undang Barat diperkenalkan.","SBUB memperkenalkan pelbagai jenis cukai yang membebankan rakyat."] },
        { title: "Kata kunci", bulletPoints: ["Sistem Residen","cukai","undang-undang Barat","kuasa pembesar","adat tempatan"] },
        { title: "Tokoh penting", bulletPoints: ["J.W.W. Birch","Sultan Abdullah","Pembesar Melayu","Pegawai SBUB"] },
        { title: "Tarikh penting", bulletPoints: ["1874: Sistem Residen bermula di Perak selepas Perjanjian Pangkor"] },
        { title: "Tempat penting", bulletPoints: ["Perak","Naning","Sabah","Pahang","Terengganu","Kelantan"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Pangkor 1874"],["Undang-undang","Undang-undang Barat; peraturan cukai; peraturan tanah"],["Organisasi / pentadbiran","Sistem Residen"]] } },
        { title: "Sebab", bulletPoints: ["British mahu menguasai hasil negeri","Sistem pentadbiran Barat menggantikan amalan tradisional","Cukai baharu diperkenalkan"] },
        { title: "Kesan", bulletPoints: ["Pembesar kehilangan sumber pendapatan","Rakyat terbeban","Kemarahan masyarakat tempatan meningkat"] },
        { title: "Kepentingan", bulletPoints: ["Menjelaskan punca langsung penentangan masyarakat tempatan."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Kesan pentadbiran Barat membawa kepada peristiwa penentangan dalam 7.3."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Rajah perbandingan pentadbiran tradisional dan pentadbiran Barat membantu murid melihat kuasa yang hilang.","Selepas campur tangan Barat: kuasa tempatan semakin terhakis"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "7.3 Penentangan Masyarakat Tempatan Terhadap Kuasa Barat",
      subsections: [
        { title: "Ringkasan", content: "Penentangan Masyarakat Tempatan Terhadap Kuasa Barat menerangkan dol said menentang british di naning kerana isu cukai dan kedaulatan naning. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Dol Said menentang British di Naning kerana isu cukai dan kedaulatan Naning.","Rentap menentang Brooke di Sarawak dan mempertahankan Bukit Sadok sehingga serangan ketiga Brooke pada tahun 1861.","Dato' Maharaja Lela dan pembesar Perak menentang J.W.W. Birch di Pasir Salak.","Dato' Bahaman menentang British di Pahang.","Mat Salleh menentang SBUB di Sabah.","Tok Janggut menentang British di Kelantan pada tahun 1915.","Haji Abdul Rahman Limbong menentang peraturan tanah British di Terengganu."] },
        { title: "Kata kunci", bulletPoints: ["Dol Said","Rentap","Dato' Maharaja Lela","Dato' Bahaman","Mat Salleh","Tok Janggut","Haji Abdul Rahman Limbong"] },
        { title: "Tokoh penting", bulletPoints: ["Dol Said","Rentap","Sharif Masahor","Dato' Maharaja Lela","Dato' Sagor","Sultan Abdullah","Dato' Bahaman","Mat Salleh","Tok Janggut","Haji Abdul Rahman Limbong"] },
        { title: "Tarikh penting", bulletPoints: ["1831-1832: Perang Naning","1861: Brooke menawan Bukit Sadok","1875: J.W.W. Birch dibunuh","1915: Tok Janggut menentang British","1928: penentangan di Terengganu"] },
        { title: "Tempat penting", bulletPoints: ["Naning","Bukit Sadok","Kuching","Pasir Salak","Belanja","Pahang","Tambunan","Kelantan","Terengganu"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Pangkor 1874"],["Undang-undang","Peraturan tanah British; peraturan cukai SBUB"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Cukai","hilang kuasa","campur tangan adat","peraturan tanah","penindasan pentadbiran Barat"] },
        { title: "Kesan", bulletPoints: ["British menggunakan tentera dan tipu muslihat","Tokoh tempatan dihukum","British memperkukuh kuasa selepas penentangan dipatahkan"] },
        { title: "Kepentingan", bulletPoints: ["Tokoh penentangan menjadi lambang keberanian mempertahankan tanah air."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Setiap penentangan mempunyai sebab tempatan tetapi berpunca daripada peluasan kuasa Barat."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta lokasi penentangan menghubungkan tokoh dengan kawasan perjuangan masing-masing.","1831 Naning","1861 Bukit Sadok","1875 Pasir Salak","1915 Kelantan","1928 Terengganu"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "7.4 Kesan Penentangan Masyarakat Tempatan",
      subsections: [
        { title: "Ringkasan", content: "Kesan Penentangan Masyarakat Tempatan menerangkan british mengalami kerugian 100,000 pound sterling dalam perang naning. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["British mengalami kerugian 100,000 Pound Sterling dalam Perang Naning.","British membelanjakan 400,000 Pound Sterling dalam Perang Perak.","British mengalami kerugian 7000 Pound Sterling dalam Perang Pahang.","British lebih berhati-hati melantik Residen yang memahami adat resam tempatan.","British menubuhkan Majlis Mesyuarat Negeri dan memantapkan skim penempatan pegawai.","Kolej Melayu Kuala Kangsar ditubuhkan pada tahun 1905.","British memberikan peluang kepada aristokrat Melayu menyertai MCS dan menubuhkan MAS."] },
        { title: "Kata kunci", bulletPoints: ["kerugian perang","Majlis Mesyuarat Negeri","MCKK","MCS","MAS","pemantapan kuasa Barat"] },
        { title: "Tokoh penting", bulletPoints: ["Residen British","Aristokrat Melayu","Pegawai British"] },
        { title: "Tarikh penting", bulletPoints: ["1905: Kolej Melayu Kuala Kangsar ditubuhkan"] },
        { title: "Tempat penting", bulletPoints: ["Naning","Perak","Pahang","Kuala Kangsar","Sarawak","Sabah"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Perintah atau Peraturan Sultan dalam Majlis Mesyuarat"],["Organisasi / pentadbiran","Majlis Mesyuarat Negeri"]] } },
        { title: "Sebab", bulletPoints: ["Penentangan tempatan menyukarkan pentadbiran British","British mahu mengelakkan kebangkitan berulang"] },
        { title: "Kesan", bulletPoints: ["British lebih berhati-hati","MMN ditubuhkan","Pentadbiran pegawai disusun semula","Kuasa Barat tetap diperkukuh"] },
        { title: "Kepentingan", bulletPoints: ["Menunjukkan penentangan memberi kesan walaupun akhirnya British memantapkan kuasa."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Kesan penentangan membuka ruang kepada peranan raja dan pembesar menangani cabaran Barat dalam Bab 8."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Rajah kesan membandingkan kesan kepada British dan masyarakat tempatan.","Selepas penentangan: British menyusun semula pentadbiran dan memperkukuh kawalan"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "Rumusan Bab",
      subsections: [
        { title: "Imbas Kembali", bulletPoints: ["7.1: penentangan, kedaulatan, hak tempatan, adat","7.2: Sistem Residen, cukai, undang-undang Barat, kuasa pembesar","7.3: Dol Said, Rentap, Dato' Maharaja Lela, Dato' Bahaman","7.4: kerugian perang, Majlis Mesyuarat Negeri, MCKK, MCS"] },
        { title: "Kata Kunci Peperiksaan", bulletPoints: ["penentangan","kedaulatan","hak tempatan","adat","kuasa pembesar","Sistem Residen","cukai","undang-undang Barat","adat tempatan","Dol Said","Rentap","Dato' Maharaja Lela","Dato' Bahaman","Mat Salleh","Tok Janggut","Haji Abdul Rahman Limbong","kerugian perang","Majlis Mesyuarat Negeri","MCKK","MCS","MAS","pemantapan kuasa Barat"] },
      ],
    }
  ],
};
