import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f2-c1-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 2",
    difficulty,
    chapter: "Chapter 1",
    lang: "dlp",
    question,
    options,
    answerIndex,
  }));
}

export const mathF2C1QuizzesDLP: QuizQuestion[] = buildQuiz([
  ["Easy", "What is the meaning of a pattern?", ["A list of numbers or objects arranged based on a rule", "A number that always decreases", "A shape with no arrangement", "The final answer of a calculation"], 0],
  ["Easy", "Which operations can form a number pattern?", ["Addition, subtraction, multiplication or division", "Draw, colour, measure or copy", "Round, fold, cut or paste", "Name, title, unit or sentence"], 0],
  ["Easy", "Even numbers are numbers that can be divided exactly by which number?", ["2", "3", "5", "10"], 0],
  ["Easy", "Odd numbers are numbers that", ["Cannot be divided exactly by 2", "Are always greater than 10", "Are negative numbers only", "Always have decimals"], 0],
  ["Easy", "The pattern for -10, -4, 2, 8, ... is", ["Add 6", "Subtract 6", "Multiply by 6", "Divide by 6"], 0],
  ["Easy", "The pattern for 17, 7, -3, -13, ... is", ["Subtract 10", "Add 10", "Multiply by 10", "Divide by 10"], 0],
  ["Easy", "The pattern for 2, 6, 18, 54, ... is", ["Multiply by 3", "Add 3", "Subtract 3", "Divide by 3"], 0],
  ["Easy", "The pattern for 81, 27, 9, 3, ... is", ["Divide by 3", "Multiply by 3", "Add 3", "Subtract 3"], 0],
  ["Easy", "The pattern for -2.3, -2.6, -2.9, -3.2, ... is", ["Subtract 0.3", "Add 0.3", "Multiply by 0.3", "Divide by 0.3"], 0],
  ["Easy", "Pascal's Triangle starts with the number", ["1", "0", "2", "3"], 0],
  ["Easy", "Each row of Pascal's Triangle starts and ends with", ["1", "0", "2", "10"], 0],
  ["Easy", "A middle number in Pascal's Triangle is obtained by", ["Adding the two numbers above it", "Subtracting two numbers below it", "Multiplying the end numbers", "Dividing numbers from the previous row"], 0],
  ["Easy", "The row after 1, 3, 3, 1 in Pascal's Triangle is", ["1, 4, 6, 4, 1", "1, 3, 6, 3, 1", "1, 4, 4, 4, 1", "1, 6, 4, 6, 1"], 0],
  ["Easy", "The Fibonacci Numbers in the notes start with", ["0, 1, 1", "1, 2, 3", "2, 4, 6", "1, 3, 5"], 0],
  ["Easy", "The rule for Fibonacci Numbers is", ["Add the previous two terms", "Add 2 each time", "Multiply by 2 each time", "Subtract the previous term"], 0],
  ["Easy", "In the Fibonacci sequence 0, 1, 1, 2, 3, 5, the next term is", ["8", "6", "7", "10"], 0],
  ["Easy", "What is the meaning of a sequence?", ["A set of numbers or objects arranged according to a certain pattern", "Any single number", "A list without arrangement", "The answer to one operation"], 0],
  ["Easy", "A set of numbers is a sequence when it", ["Follows a certain pattern", "Contains large numbers only", "Starts with zero only", "Has no negative signs"], 0],
  ["Easy", "The pattern of a sequence is", ["The rule linking one term to the next", "The name of the last number", "The sum of all terms", "A graph shape only"], 0],
  ["Easy", "A number sequence consists of", ["Numbers", "Letters only", "Colours only", "Time units only"], 0],
  ["Easy", "The triangular numbers in the notes begin with", ["1, 3, 6, 10", "2, 4, 6, 8", "1, 4, 9, 16", "0, 1, 1, 2"], 0],
  ["Easy", "A sequence pattern can be described using", ["Numbers, words and algebraic expressions", "Colours, sizes and shapes only", "Titles, labels and units only", "Time, distance and temperature only"], 0],
  ["Easy", "An algebraic expression involves", ["Numbers, variables or mathematical entities", "Pictures only", "Physical objects only", "Sentences without numbers"], 0],
  ["Easy", "The n-th term is written as", ["Tn", "nTn", "T + n", "n only"], 0],
  ["Easy", "T1 means", ["The first term", "The last term", "The sum of terms", "The number pattern"], 0],
  ["Easy", "T2 means", ["The second term", "The first term", "Two times all terms", "Two patterns"], 0],
  ["Easy", "For 4, 8, 12, 16, ..., T3 is", ["12", "4", "8", "16"], 0],
  ["Easy", "For 4, 8, 12, 16, ..., T4 is", ["16", "12", "8", "4"], 0],
  ["Easy", "The first step in solving a sequence problem is to", ["Understand the problem", "Write the final answer first", "Ignore the unit", "Change all numbers into fractions"], 0],
  ["Easy", "The time interval formula in the notes is", ["Interval = total time / number of equal parts", "Interval = total time x number of parts", "Interval = first time + last time", "Interval = term / even number"], 0],

  ["Medium", "Complete the sequence: 7, 13, __, 25, __, 37, ...", ["19, 31", "18, 30", "20, 32", "21, 33"], 0],
  ["Medium", "Complete the sequence: 88, __, 64, 52, __, 28, ...", ["76, 40", "72, 36", "80, 44", "74, 42"], 0],
  ["Medium", "Complete the sequence: 96, 92, 88, __, 80, __, ...", ["84, 76", "86, 78", "82, 74", "85, 77"], 0],
  ["Medium", "If the pattern is multiply by 3 and starts with 7, the three terms after 7 are", ["21, 63, 189", "10, 13, 16", "14, 21, 28", "4, 1, -2"], 0],
  ["Medium", "If the pattern is divide by 5 and starts with 400, the correct sequence is", ["400, 80, 16, 3.2", "400, 395, 390, 385", "400, 2000, 10000, 50000", "400, 405, 410, 415"], 0],
  ["Medium", "Complete: 1, 0.3, __, 0.027, 0.0081, ...", ["0.09", "0.9", "0.03", "0.003"], 0],
  ["Medium", "Complete the Fibonacci Numbers: 0, 1, 1, 2, 3, __, 8", ["5", "4", "6", "7"], 0],
  ["Medium", "Complete the Fibonacci-type sequence: 1, 3, __, __, 11, ...", ["4, 7", "5, 8", "3, 6", "2, 9"], 0],
  ["Medium", "In Pascal's Triangle, the number between 3 and 3 in the lower row is", ["6", "3", "9", "1"], 0],
  ["Medium", "State the pattern for 1, 3/2, 2, 5/2, ...", ["Add 1/2", "Add 1", "Multiply by 3/2", "Subtract 1/2"], 0],
  ["Medium", "From 7, 12, 17, 22, 27, ..., 67, the odd-number pattern is", ["Add 10", "Add 5", "Subtract 10", "Multiply by 10"], 0],
  ["Medium", "For 2, 10, 18, ..., the 5th term is", ["34", "26", "42", "30"], 0],
  ["Medium", "For 65, 60, 55, 50, ..., 40 is the", ["6th term", "5th term", "7th term", "8th term"], 0],
  ["Medium", "For 42, 49, 56, 63, 70, ..., the pattern is", ["Add 7", "Subtract 7", "Multiply by 7", "Divide by 7"], 0],
  ["Medium", "If T1=42 and the pattern is add 7, T6 is", ["77", "70", "84", "63"], 0],
  ["Medium", "The algebraic expression for 1, 9, 17, 25, ... based on n = 0 is", ["1 + 8n", "8 + n", "8n", "9 + 8n"], 0],
  ["Medium", "In the expression 1 + 8n, the value of n for the first term is", ["0", "1", "2", "8"], 0],
  ["Medium", "If n = 3 in 1 + 8n, the term value is", ["25", "17", "33", "9"], 0],
  ["Medium", "The word description for 1, 9, 17, 25, ... is", ["Add 8 to the previous number", "Subtract 8 from the previous number", "Multiply the previous number by 8", "Divide the previous number by 8"], 0],
  ["Medium", "The number form for the pattern 1, 9, 17, 25, ... is", ["+8, +8, +8", "-8, -8, -8", "x8, x8, x8", "divide 8, divide 8, divide 8"], 0],
  ["Medium", "The set -10, -6, -2, 2, 6, ... is a sequence because", ["Its pattern is add 4", "Its pattern is subtract 4", "It has no pattern", "All numbers are positive"], 0],
  ["Medium", "Complete: 21.3, 13.3, 5.3, __, -10.7, ...", ["-2.7", "-3.7", "2.7", "0.7"], 0],
  ["Medium", "If a sequence decreases by subtracting 12, the term after 52 is", ["40", "64", "44", "28"], 0],
  ["Medium", "If the blank before 0.3 is in a multiply-by-0.3 sequence, its value is", ["1", "0.09", "0.6", "3"], 0],
  ["Medium", "The row of Pascal's Triangle after 1, 4, 6, 4, 1 begins with", ["1", "4", "6", "5"], 0],
  ["Medium", "The Fibonacci number after 8 and 13 is", ["21", "18", "20", "23"], 0],
  ["Medium", "For the sequence 4, 8, 12, 16, ..., T1 to T4 show", ["Term positions", "The sum of all terms", "The number of patterns", "Pascal row numbers"], 0],
  ["Medium", "When a rule is given in words, students should", ["Apply the rule directly and carefully", "Change the rule freely", "Ignore the first term", "Round all answers"], 0],
  ["Medium", "For division patterns, a reverse check can be done by", ["Multiplying", "Subtracting", "Adding", "Rounding"], 0],
  ["Medium", "If a question asks 'which term', a suitable strategy is to", ["Continue the sequence until the required value appears", "Answer with the first value only", "Change all numbers to 0", "Use Pascal's Triangle"], 0],

  ["Hard", "An automatic fish feeder feeds fish 4 times a day. If T1 is 7:35 a.m., T3 is", ["7:35 p.m.", "1:35 p.m.", "7:35 a.m.", "1:35 a.m."], 0],
  ["Hard", "In the fish feeder problem with 4 feeds a day, each time interval is", ["6 hours", "4 hours", "8 hours", "12 hours"], 0],
  ["Hard", "If a bus leaves every 6 hours starting at 7:35 a.m., the fourth departure time is", ["1:35 a.m.", "7:35 p.m.", "1:35 p.m.", "7:35 a.m."], 0],
  ["Hard", "The sequence 1, 9, 17, 25, ... uses n = 0. The value when n = 5 is", ["41", "33", "49", "40"], 0],
  ["Hard", "If a = 1 and d = 8 in a + dn, the term when n = 4 is", ["33", "25", "41", "32"], 0],
  ["Hard", "A sequence starts at 5 and increases by 8 each time. The expression based on n = 0 is", ["5 + 8n", "8 + 5n", "5n + 8", "13n"], 0],
  ["Hard", "For 5 + 8n where n = 0, 1, 2, ..., the first three terms are", ["5, 13, 21", "8, 13, 18", "5, 10, 15", "13, 21, 29"], 0],
  ["Hard", "If T1 = 2 and the pattern is add 8, T7 is", ["50", "42", "58", "48"], 0],
  ["Hard", "If 65, 60, 55, ... continues, the term with value 35 is T", ["7", "6", "8", "9"], 0],
  ["Hard", "Complete this Fibonacci-type sequence: 2, 5, 7, 12, __, __", ["19, 31", "17, 29", "20, 32", "18, 30"], 0],
  ["Hard", "If two consecutive Fibonacci terms are 13 and 21, the next term is", ["34", "33", "35", "31"], 0],
  ["Hard", "A blank comes after 0.027 in a multiply-by-0.3 sequence. Its value is", ["0.0081", "0.081", "0.0027", "0.00081"], 0],
  ["Hard", "If a divide-by-5 sequence has 16 followed by 3.2, the term before 16 is", ["80", "20", "32", "11"], 0],
  ["Hard", "In Pascal's Triangle, the row after 1, 4, 6, 4, 1 is", ["1, 5, 10, 10, 5, 1", "1, 5, 9, 9, 5, 1", "1, 4, 10, 10, 4, 1", "1, 6, 10, 10, 6, 1"], 0],
  ["Hard", "The number 10 in the row 1, 5, 10, 10, 5, 1 is obtained from", ["4 + 6", "5 + 5", "1 + 9", "10 + 0"], 0],
  ["Hard", "Which statement describes a mistake in Fibonacci Numbers?", ["Adding only one previous term", "Adding the previous two terms", "Using the two terms before the blank", "Checking each term after the first two terms"], 0],
  ["Hard", "What is the correct conclusion for -10, -6, -2, 2, 6, ...?", ["It is a sequence because the pattern is add 4", "It is not a sequence because it has negative numbers", "It is a sequence because all numbers are odd", "It is not a sequence because it starts with -10"], 0],
  ["Hard", "If 88, 76, 64, 52, ... continues for two more terms, the answer is", ["40, 28", "44, 36", "48, 44", "36, 20"], 0],
  ["Hard", "If an object pattern has 2, 4, 6 dots, the fifth object has", ["10 dots", "8 dots", "12 dots", "6 dots"], 0],
  ["Hard", "For 7, 12, 17, 22, ..., the odd numbers from the list form the pattern", ["7, 17, 27, 37, ...", "7, 12, 17, 22, ...", "12, 22, 32, 42, ...", "17, 22, 27, 32, ..."], 0],
  ["Hard", "If the odd-number pattern continues from 7 to 67, the number of terms is", ["7", "6", "8", "10"], 0],
  ["Hard", "A sequence starts at 42 and adds 7. The term with value 70 is", ["T5", "T4", "T6", "T7"], 0],
  ["Hard", "If the first time is 7:35 a.m. and the interval is 6 hours, the second and third times are", ["1:35 p.m. and 7:35 p.m.", "1:35 a.m. and 7:35 a.m.", "12:35 p.m. and 6:35 p.m.", "2:35 p.m. and 8:35 p.m."], 0],
  ["Hard", "In sequence problem solving, what information must be identified?", ["The first term, pattern and required term", "The colour of the question and page title", "The number of letters in the question", "The variable name only"], 0],
  ["Hard", "If the add-8 pattern is written as 1 + 8n, why does n start with 0?", ["So that the first term is 1", "So that the first term is 8", "So that all terms are negative", "So that the pattern becomes divide by 8"], 0],
  ["Hard", "What is the mistake if n = 1 is used in 1 + 8n for the first term?", ["The first term becomes 9, not 1", "The first term becomes 0", "The pattern becomes Fibonacci", "The Pascal row changes"], 0],
  ["Hard", "If a question asks for the pattern in numbers, words and algebraic expression, the most complete answer is", ["+8; add 8; 1 + 8n", "+8 only", "Add 8 only", "1 + 8n only"], 0],
  ["Hard", "To determine T5 for 2, 10, 18, ..., the correct step is to", ["List 2, 10, 18, 26, 34", "Add 5 to 2", "Multiply 2 by 5", "Take the fifth number as 5"], 0],
  ["Hard", "The sequence 400, 80, 16, 3.2, ... involves decimals because", ["Division by 5 continues after 16", "The pattern changes to add 5", "The number 3.2 is rounded to 3", "The sequence stops after 16"], 0],
  ["Hard", "What is an important note for time problems in sequences?", ["Use correct a.m. and p.m. notation", "Ignore time units", "Always answer in seconds", "Change all times to even numbers"], 0],
]);
