import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f2-c1-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 2",
    difficulty,
    chapter: "Chapter 1",
    lang: "bm",
    question,
    options,
    answerIndex,
  }));
}

export const mathF2C1QuizzesBM: QuizQuestion[] = buildQuiz([
  ["Easy", "Apakah maksud corak?", ["Senarai nombor atau objek yang disusun berdasarkan peraturan", "Nombor yang sentiasa menurun", "Bentuk yang tidak mempunyai susunan", "Jawapan akhir bagi pengiraan"], 0],
  ["Easy", "Operasi manakah boleh membentuk corak nombor?", ["Tambah, tolak, darab atau bahagi", "Lukis, warna, ukur atau salin", "Bundar, lipat, potong atau tampal", "Nama, tajuk, unit atau ayat"], 0],
  ["Easy", "Nombor genap ialah nombor yang boleh dibahagi tepat dengan nombor berapa?", ["2", "3", "5", "10"], 0],
  ["Easy", "Nombor ganjil ialah nombor yang bagaimana?", ["Tidak boleh dibahagi tepat dengan 2", "Sentiasa lebih besar daripada 10", "Hanya nombor negatif", "Sentiasa mempunyai perpuluhan"], 0],
  ["Easy", "Corak bagi -10, -4, 2, 8, ... ialah", ["Tambah 6", "Tolak 6", "Darab 6", "Bahagi 6"], 0],
  ["Easy", "Corak bagi 17, 7, -3, -13, ... ialah", ["Tolak 10", "Tambah 10", "Darab 10", "Bahagi 10"], 0],
  ["Easy", "Corak bagi 2, 6, 18, 54, ... ialah", ["Darab 3", "Tambah 3", "Tolak 3", "Bahagi 3"], 0],
  ["Easy", "Corak bagi 81, 27, 9, 3, ... ialah", ["Bahagi 3", "Darab 3", "Tambah 3", "Tolak 3"], 0],
  ["Easy", "Corak bagi -2.3, -2.6, -2.9, -3.2, ... ialah", ["Tolak 0.3", "Tambah 0.3", "Darab 0.3", "Bahagi 0.3"], 0],
  ["Easy", "Segi Tiga Pascal bermula dengan nombor", ["1", "0", "2", "3"], 0],
  ["Easy", "Setiap baris Segi Tiga Pascal bermula dan berakhir dengan", ["1", "0", "2", "10"], 0],
  ["Easy", "Nombor tengah dalam Segi Tiga Pascal diperoleh dengan", ["Menambah dua nombor di atasnya", "Menolak dua nombor di bawahnya", "Mendarab nombor hujung", "Membahagi nombor baris sebelumnya"], 0],
  ["Easy", "Baris selepas 1, 3, 3, 1 dalam Segi Tiga Pascal ialah", ["1, 4, 6, 4, 1", "1, 3, 6, 3, 1", "1, 4, 4, 4, 1", "1, 6, 4, 6, 1"], 0],
  ["Easy", "Nombor Fibonacci dalam nota bermula dengan", ["0, 1, 1", "1, 2, 3", "2, 4, 6", "1, 3, 5"], 0],
  ["Easy", "Peraturan Nombor Fibonacci ialah", ["Tambah dua sebutan sebelumnya", "Tambah 2 setiap kali", "Darab 2 setiap kali", "Tolak sebutan sebelumnya"], 0],
  ["Easy", "Dalam jujukan Fibonacci 0, 1, 1, 2, 3, 5, sebutan seterusnya ialah", ["8", "6", "7", "10"], 0],
  ["Easy", "Apakah maksud jujukan?", ["Set nombor atau objek yang disusun mengikut corak tertentu", "Sebarang nombor tunggal", "Senarai tanpa susunan", "Jawapan bagi satu operasi"], 0],
  ["Easy", "Set nombor ialah jujukan apabila set itu", ["Mengikut suatu corak tertentu", "Mengandungi nombor besar sahaja", "Bermula dengan sifar sahaja", "Tidak mempunyai tanda negatif"], 0],
  ["Easy", "Corak suatu jujukan ialah", ["Peraturan yang menghubungkan satu sebutan dengan sebutan seterusnya", "Nama bagi nombor terakhir", "Jumlah semua sebutan", "Bentuk graf sahaja"], 0],
  ["Easy", "Jujukan nombor terdiri daripada", ["Nombor", "Huruf sahaja", "Warna sahaja", "Unit masa sahaja"], 0],
  ["Easy", "Nombor segi tiga dalam nota bermula dengan", ["1, 3, 6, 10", "2, 4, 6, 8", "1, 4, 9, 16", "0, 1, 1, 2"], 0],
  ["Easy", "Corak jujukan boleh dihuraikan menggunakan", ["Nombor, perkataan dan ungkapan algebra", "Warna, saiz dan bentuk sahaja", "Tajuk, label dan unit sahaja", "Masa, jarak dan suhu sahaja"], 0],
  ["Easy", "Ungkapan algebra melibatkan", ["Nombor, pemboleh ubah atau entiti matematik", "Gambar sahaja", "Objek fizikal sahaja", "Ayat tanpa nombor"], 0],
  ["Easy", "Sebutan ke-n ditulis sebagai", ["Tn", "nTn", "T + n", "n sahaja"], 0],
  ["Easy", "T1 bermaksud", ["Sebutan pertama", "Sebutan terakhir", "Jumlah sebutan", "Corak nombor"], 0],
  ["Easy", "T2 bermaksud", ["Sebutan kedua", "Sebutan pertama", "Dua kali semua sebutan", "Dua corak"], 0],
  ["Easy", "Bagi 4, 8, 12, 16, ..., T3 ialah", ["12", "4", "8", "16"], 0],
  ["Easy", "Bagi 4, 8, 12, 16, ..., T4 ialah", ["16", "12", "8", "4"], 0],
  ["Easy", "Langkah pertama menyelesaikan masalah jujukan ialah", ["Fahami masalah", "Tulis jawapan akhir dahulu", "Abaikan unit", "Tukar semua nombor kepada pecahan"], 0],
  ["Easy", "Formula selang masa dalam nota ialah", ["Selang = jumlah masa / bilangan bahagian yang sama", "Selang = jumlah masa x bilangan bahagian", "Selang = masa pertama + masa akhir", "Selang = sebutan / nombor genap"], 0],

  ["Medium", "Lengkapkan jujukan: 7, 13, __, 25, __, 37, ...", ["19, 31", "18, 30", "20, 32", "21, 33"], 0],
  ["Medium", "Lengkapkan jujukan: 88, __, 64, 52, __, 28, ...", ["76, 40", "72, 36", "80, 44", "74, 42"], 0],
  ["Medium", "Lengkapkan jujukan: 96, 92, 88, __, 80, __, ...", ["84, 76", "86, 78", "82, 74", "85, 77"], 0],
  ["Medium", "Jika corak ialah darab 3 dan bermula dengan 7, tiga sebutan selepas 7 ialah", ["21, 63, 189", "10, 13, 16", "14, 21, 28", "4, 1, -2"], 0],
  ["Medium", "Jika corak ialah bahagi 5 dan bermula dengan 400, jujukan yang betul ialah", ["400, 80, 16, 3.2", "400, 395, 390, 385", "400, 2000, 10000, 50000", "400, 405, 410, 415"], 0],
  ["Medium", "Lengkapkan: 1, 0.3, __, 0.027, 0.0081, ...", ["0.09", "0.9", "0.03", "0.003"], 0],
  ["Medium", "Lengkapkan Nombor Fibonacci: 0, 1, 1, 2, 3, __, 8", ["5", "4", "6", "7"], 0],
  ["Medium", "Lengkapkan jujukan jenis Fibonacci: 1, 3, __, __, 11, ...", ["4, 7", "5, 8", "3, 6", "2, 9"], 0],
  ["Medium", "Dalam Segi Tiga Pascal, nombor di antara 3 dan 3 pada baris bawah ialah", ["6", "3", "9", "1"], 0],
  ["Medium", "Nyatakan corak bagi 1, 3/2, 2, 5/2, ...", ["Tambah 1/2", "Tambah 1", "Darab 3/2", "Tolak 1/2"], 0],
  ["Medium", "Daripada 7, 12, 17, 22, 27, ..., 67, corak nombor ganjil ialah", ["Tambah 10", "Tambah 5", "Tolak 10", "Darab 10"], 0],
  ["Medium", "Bagi 2, 10, 18, ..., sebutan ke-5 ialah", ["34", "26", "42", "30"], 0],
  ["Medium", "Bagi 65, 60, 55, 50, ..., 40 ialah sebutan ke-", ["6", "5", "7", "8"], 0],
  ["Medium", "Bagi 42, 49, 56, 63, 70, ..., coraknya ialah", ["Tambah 7", "Tolak 7", "Darab 7", "Bahagi 7"], 0],
  ["Medium", "Jika T1=42 dan corak tambah 7, T6 ialah", ["77", "70", "84", "63"], 0],
  ["Medium", "Ungkapan algebra bagi 1, 9, 17, 25, ... berdasarkan n = 0 ialah", ["1 + 8n", "8 + n", "8n", "9 + 8n"], 0],
  ["Medium", "Dalam ungkapan 1 + 8n, nilai n untuk sebutan pertama ialah", ["0", "1", "2", "8"], 0],
  ["Medium", "Jika n = 3 dalam 1 + 8n, nilai sebutan ialah", ["25", "17", "33", "9"], 0],
  ["Medium", "Huraian perkataan bagi corak 1, 9, 17, 25, ... ialah", ["Tambah 8 kepada nombor sebelumnya", "Tolak 8 daripada nombor sebelumnya", "Darab nombor sebelumnya dengan 8", "Bahagi nombor sebelumnya dengan 8"], 0],
  ["Medium", "Bentuk nombor bagi corak 1, 9, 17, 25, ... ialah", ["+8, +8, +8", "-8, -8, -8", "x8, x8, x8", "bahagi 8, bahagi 8, bahagi 8"], 0],
  ["Medium", "Set -10, -6, -2, 2, 6, ... ialah jujukan kerana", ["Coraknya tambah 4", "Coraknya tolak 4", "Tiada corak", "Semua nombor positif"], 0],
  ["Medium", "Lengkapkan: 21.3, 13.3, 5.3, __, -10.7, ...", ["-2.7", "-3.7", "2.7", "0.7"], 0],
  ["Medium", "Jika jujukan menurun dengan menolak 12, sebutan selepas 52 ialah", ["40", "64", "44", "28"], 0],
  ["Medium", "Jika tempat kosong sebelum 0.3 dalam jujukan darab 0.3, nilainya ialah", ["1", "0.09", "0.6", "3"], 0],
  ["Medium", "Baris Segi Tiga Pascal selepas 1, 4, 6, 4, 1 bermula dengan", ["1", "4", "6", "5"], 0],
  ["Medium", "Nombor Fibonacci selepas 8 dan 13 ialah", ["21", "18", "20", "23"], 0],
  ["Medium", "Bagi jujukan 4, 8, 12, 16, ..., T1 hingga T4 menunjukkan", ["Kedudukan sebutan", "Jumlah semua sebutan", "Bilangan corak", "Nombor baris Pascal"], 0],
  ["Medium", "Apabila peraturan diberi dalam perkataan, murid perlu", ["Menggunakan peraturan itu secara terus dan teliti", "Menukar peraturan sesuka hati", "Abaikan sebutan pertama", "Bundarkan semua jawapan"], 0],
  ["Medium", "Untuk corak pembahagian, semakan songsang boleh dibuat dengan", ["Mendarab", "Menolak", "Menambah", "Membundar"], 0],
  ["Medium", "Jika soalan meminta 'sebutan yang ke berapa', strategi yang sesuai ialah", ["Teruskan jujukan sehingga nilai itu muncul", "Jawab dengan nilai pertama sahaja", "Tukar semua nombor kepada 0", "Gunakan Segi Tiga Pascal"], 0],

  ["Hard", "Sebuah alat memberi makanan ikan 4 kali sehari. Jika T1 ialah 7:35 a.m., T3 ialah", ["7:35 p.m.", "1:35 p.m.", "7:35 a.m.", "1:35 a.m."], 0],
  ["Hard", "Dalam masalah alat memberi makanan 4 kali sehari, selang masa setiap pemberian ialah", ["6 jam", "4 jam", "8 jam", "12 jam"], 0],
  ["Hard", "Jika bas bertolak setiap 6 jam bermula 7:35 a.m., masa bertolak keempat ialah", ["1:35 a.m.", "7:35 p.m.", "1:35 p.m.", "7:35 a.m."], 0],
  ["Hard", "Jujukan 1, 9, 17, 25, ... digunakan dengan n = 0. Nilai bagi n = 5 ialah", ["41", "33", "49", "40"], 0],
  ["Hard", "Jika a = 1 dan d = 8 dalam a + dn, sebutan apabila n = 4 ialah", ["33", "25", "41", "32"], 0],
  ["Hard", "Satu jujukan bermula 5 dan bertambah 8 setiap kali. Ungkapan berdasarkan n = 0 ialah", ["5 + 8n", "8 + 5n", "5n + 8", "13n"], 0],
  ["Hard", "Bagi 5 + 8n dengan n = 0, 1, 2, ..., tiga sebutan pertama ialah", ["5, 13, 21", "8, 13, 18", "5, 10, 15", "13, 21, 29"], 0],
  ["Hard", "Jika T1 = 2 dan corak tambah 8, T7 ialah", ["50", "42", "58", "48"], 0],
  ["Hard", "Jika 65, 60, 55, ... diteruskan, sebutan bernilai 35 ialah T", ["7", "6", "8", "9"], 0],
  ["Hard", "Lengkapkan jujukan Fibonacci jenis ini: 2, 5, 7, 12, __, __", ["19, 31", "17, 29", "20, 32", "18, 30"], 0],
  ["Hard", "Jika dua sebutan berturutan Fibonacci ialah 13 dan 21, sebutan seterusnya ialah", ["34", "33", "35", "31"], 0],
  ["Hard", "Satu tempat kosong berada selepas 0.027 dalam jujukan darab 0.3. Nilainya ialah", ["0.0081", "0.081", "0.0027", "0.00081"], 0],
  ["Hard", "Jika jujukan bahagi 5 mempunyai sebutan 16 diikuti 3.2, sebutan sebelum 16 ialah", ["80", "20", "32", "11"], 0],
  ["Hard", "Dalam Segi Tiga Pascal, baris selepas 1, 4, 6, 4, 1 ialah", ["1, 5, 10, 10, 5, 1", "1, 5, 9, 9, 5, 1", "1, 4, 10, 10, 4, 1", "1, 6, 10, 10, 6, 1"], 0],
  ["Hard", "Nombor 10 dalam baris 1, 5, 10, 10, 5, 1 diperoleh daripada", ["4 + 6", "5 + 5", "1 + 9", "10 + 0"], 0],
  ["Hard", "Antara berikut, yang manakah menerangkan kesilapan dalam Nombor Fibonacci?", ["Menambah satu sebutan sebelumnya sahaja", "Menambah dua sebutan sebelumnya", "Menggunakan dua sebutan sebelum tempat kosong", "Menyemak setiap sebutan selepas dua sebutan pertama"], 0],
  ["Hard", "Apakah kesimpulan tepat bagi -10, -6, -2, 2, 6, ...?", ["Set ini jujukan kerana coraknya tambah 4", "Set ini bukan jujukan kerana ada nombor negatif", "Set ini jujukan kerana semua nombor ganjil", "Set ini bukan jujukan kerana bermula dengan -10"], 0],
  ["Hard", "Jika jujukan 88, 76, 64, 52, ... diteruskan dua sebutan lagi, jawapannya ialah", ["40, 28", "44, 36", "48, 44", "36, 20"], 0],
  ["Hard", "Jika corak objek mempunyai 2, 4, 6 titik, objek kelima mempunyai", ["10 titik", "8 titik", "12 titik", "6 titik"], 0],
  ["Hard", "Bagi 7, 12, 17, 22, ..., nombor ganjil daripada senarai itu membentuk corak", ["7, 17, 27, 37, ...", "7, 12, 17, 22, ...", "12, 22, 32, 42, ...", "17, 22, 27, 32, ..."], 0],
  ["Hard", "Jika corak nombor ganjil tersebut diteruskan daripada 7 hingga 67, bilangan sebutannya ialah", ["7", "6", "8", "10"], 0],
  ["Hard", "Satu jujukan bermula 42 dan tambah 7. Sebutan yang bernilai 70 ialah", ["T5", "T4", "T6", "T7"], 0],
  ["Hard", "Jika masa pertama ialah 7:35 a.m. dan selang 6 jam, masa kedua dan ketiga ialah", ["1:35 p.m. dan 7:35 p.m.", "1:35 a.m. dan 7:35 a.m.", "12:35 p.m. dan 6:35 p.m.", "2:35 p.m. dan 8:35 p.m."], 0],
  ["Hard", "Dalam penyelesaian masalah jujukan, apakah maklumat yang mesti dikenal pasti?", ["Sebutan pertama, corak dan sebutan yang dikehendaki", "Warna soalan dan tajuk halaman", "Bilangan huruf dalam soalan", "Nama pemboleh ubah sahaja"], 0],
  ["Hard", "Jika corak tambah 8 ditulis sebagai 1 + 8n, mengapa n bermula dengan 0?", ["Supaya sebutan pertama ialah 1", "Supaya sebutan pertama ialah 8", "Supaya semua sebutan menjadi negatif", "Supaya corak menjadi bahagi 8"], 0],
  ["Hard", "Apakah kesilapan apabila menggunakan n = 1 dalam 1 + 8n untuk sebutan pertama?", ["Sebutan pertama menjadi 9, bukan 1", "Sebutan pertama menjadi 0", "Corak menjadi Fibonacci", "Baris Pascal berubah"], 0],
  ["Hard", "Jika soalan meminta corak dalam nombor, perkataan dan ungkapan algebra, jawapan paling lengkap ialah", ["+8; tambah 8; 1 + 8n", "+8 sahaja", "Tambah 8 sahaja", "1 + 8n sahaja"], 0],
  ["Hard", "Untuk menentukan T5 bagi 2, 10, 18, ..., langkah yang betul ialah", ["Senaraikan 2, 10, 18, 26, 34", "Tambah 5 kepada 2", "Darab 2 dengan 5", "Ambil nombor kelima sebagai 5"], 0],
  ["Hard", "Jujukan 400, 80, 16, 3.2, ... melibatkan nombor perpuluhan kerana", ["Pembahagian 5 diteruskan selepas 16", "Corak berubah kepada tambah 5", "Nombor 3.2 dibundarkan kepada 3", "Jujukan berhenti selepas 16"], 0],
  ["Hard", "Apakah nota penting bagi masalah masa dalam jujukan?", ["Gunakan notasi a.m. dan p.m. yang betul", "Abaikan unit masa", "Sentiasa jawab dalam saat", "Tukar semua masa kepada nombor genap"], 0],
]);
