import type { QuizQuestion } from "@/data/content";

export const mathF2C1FoundationQuizzesBM: QuizQuestion[] = [
  {
    id: "math-f2-c1-bm-f1",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah maksud pola dalam Matematik?",
    options: [
      "Senarai nombor secara rawak",
      "Aturan atau corak tertentu bagi nombor atau objek",
      "Nombor yang sentiasa genap",
      "Operasi yang hanya melibatkan darab",
    ],
    answerIndex: 1,
    explanation: "Pola ialah aturan atau corak tertentu dalam senarai nombor atau objek.",
  },
  {
    id: "math-f2-c1-bm-f2",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n5, 9, 13, 17, …",
    options: ["19", "20", "21", "22"],
    answerIndex: 2,
    explanation: "Setiap sebutan bertambah 4. Maka, 17 + 4 = 21.",
  },
  {
    id: "math-f2-c1-bm-f3",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah pola bagi jujukan\r\n18, 15, 12, 9, …?",
    options: ["Tambah 3", "Tolak 3", "Darab 3", "Bahagi 3"],
    answerIndex: 1,
    explanation: "Setiap sebutan diperoleh dengan menolak 3 daripada sebutan sebelumnya.",
  },
  {
    id: "math-f2-c1-bm-f4",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n3, 6, 12, 24, …",
    options: ["30", "36", "42", "48"],
    answerIndex: 3,
    explanation: "Setiap nombor didarab dengan 2. Oleh itu, 24 × 2 = 48.",
  },
  {
    id: "math-f2-c1-bm-f5",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n160, 80, 40, 20, …",
    options: ["5", "10", "15", "18"],
    answerIndex: 1,
    explanation: "Setiap sebutan dibahagi dengan 2. Maka, 20 ÷ 2 = 10.",
  },
  {
    id: "math-f2-c1-bm-f6",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Yang manakah nombor genap?",
    options: ["17", "29", "34", "45"],
    answerIndex: 2,
    explanation: "34 boleh dibahagi tepat dengan 2.",
  },
  {
    id: "math-f2-c1-bm-f7",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Yang manakah nombor ganjil?",
    options: ["28", "42", "56", "63"],
    answerIndex: 3,
    explanation: "63 tidak boleh dibahagi tepat dengan 2.",
  },
  {
    id: "math-f2-c1-bm-f8",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan Nombor Fibonacci seterusnya:\r\n0, 1, 1, 2, 3, 5, …",
    options: ["6", "7", "8", "10"],
    answerIndex: 2,
    explanation: "Sebutan seterusnya ialah hasil tambah dua sebutan sebelumnya. 3 + 5 = 8.",
  },
  {
    id: "math-f2-c1-bm-f9",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Dalam jujukan Fibonacci, apakah nombor selepas 8 dan 13?",
    options: ["18", "19", "20", "21"],
    answerIndex: 3,
    explanation: "8 + 13 = 21.",
  },
  {
    id: "math-f2-c1-bm-f10",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Setiap baris dalam Segi Tiga Pascal bermula dan berakhir dengan nombor apa?",
    options: ["0", "1", "2", "3"],
    answerIndex: 1,
    explanation: "Setiap baris Segi Tiga Pascal bermula dan berakhir dengan nombor 1.",
  },
  {
    id: "math-f2-c1-bm-f11",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah baris seterusnya selepas\r\n1, 3, 3, 1\r\ndalam Segi Tiga Pascal?",
    options: ["1, 4, 6, 4, 1", "1, 4, 4, 4, 1", "1, 3, 6, 3, 1", "1, 5, 6, 5, 1"],
    answerIndex: 0,
    explanation: "Nombor bersebelahan ditambah: 1+3=4, 3+3=6 dan 3+1=4.",
  },
  {
    id: "math-f2-c1-bm-f12",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah maksud jujukan?",
    options: [
      "Senarai nombor tanpa aturan",
      "Susunan nombor atau objek yang mengikut suatu pola",
      "Senarai nombor ganjil sahaja",
      "Senarai nombor bulat sahaja",
    ],
    answerIndex: 1,
    explanation: "Jujukan ialah susunan nombor atau objek yang mengikut suatu pola.",
  },
  {
    id: "math-f2-c1-bm-f13",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan nombor yang hilang:\r\n7, 12, 17, __, 27",
    options: ["20", "21", "22", "23"],
    answerIndex: 2,
    explanation: "Polanya ialah tambah 5. Maka, 17 + 5 = 22.",
  },
  {
    id: "math-f2-c1-bm-f14",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan nombor yang hilang:\r\n45, 39, __, 27, 21",
    options: ["30", "31", "32", "33"],
    answerIndex: 3,
    explanation: "Polanya ialah tolak 6. Maka, 39 − 6 = 33.",
  },
  {
    id: "math-f2-c1-bm-f15",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n2, 10, 50, 250, …",
    options: ["500", "750", "1 000", "1 250"],
    answerIndex: 3,
    explanation: "Setiap sebutan didarab dengan 5. Maka, 250 × 5 = 1 250.",
  },
  {
    id: "math-f2-c1-bm-f16",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n729, 243, 81, 27, …",
    options: ["3", "6", "9", "12"],
    answerIndex: 2,
    explanation: "Setiap sebutan dibahagi dengan 3. Maka, 27 ÷ 3 = 9.",
  },
  {
    id: "math-f2-c1-bm-f17",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagi jujukan\r\n6, 12, 18, 24, …\r\napakah nilai T₃?",
    options: ["6", "12", "18", "24"],
    answerIndex: 2,
    explanation: "T₃ ialah sebutan ketiga, iaitu 18.",
  },
  {
    id: "math-f2-c1-bm-f18",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagi jujukan\r\n9, 14, 19, 24, …\r\napakah nilai T₄?",
    options: ["19", "20", "23", "24"],
    answerIndex: 3,
    explanation: "Sebutan keempat ialah 24.",
  },
  {
    id: "math-f2-c1-bm-f19",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Simbol manakah mewakili sebutan kelima?",
    options: ["T₁", "T₅", "Tₙ", "5T"],
    answerIndex: 1,
    explanation: "T₅ ialah sebutan kelima.",
  },
  {
    id: "math-f2-c1-bm-f20",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Jujukan\r\n4, 8, 12, 16, …\r\nboleh ditulis sebagai ungkapan yang mana bagi n = 1, 2, 3, …?",
    options: ["2n", "3n", "4n", "4 + n"],
    answerIndex: 2,
    explanation: "4n menghasilkan 4, 8, 12, 16, … apabila n = 1, 2, 3, 4, … .",
  },
  {
    id: "math-f2-c1-bm-f21",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jujukan manakah dihasilkan oleh 5n bagi n = 1, 2, 3, …?",
    options: ["1, 5, 10, 15, …", "5, 10, 15, 20, …", "5, 6, 7, 8, …", "0, 5, 10, 15, …"],
    answerIndex: 1,
    explanation: "5(1)=5, 5(2)=10, 5(3)=15 dan seterusnya.",
  },
  {
    id: "math-f2-c1-bm-f22",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Pernyataan manakah menerangkan jujukan\r\n12, 19, 26, 33, …?",
    options: ["Tambah 5", "Tambah 6", "Tambah 7", "Tambah 8"],
    answerIndex: 2,
    explanation: "Beza antara setiap sebutan ialah 7.",
  },
  {
    id: "math-f2-c1-bm-f23",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Pernyataan manakah menerangkan jujukan\r\n100, 50, 25, 12.5, …?",
    options: [
      "Bahagi nombor sebelumnya dengan 2",
      "Tolak 50",
      "Darab nombor sebelumnya dengan 2",
      "Bahagi nombor sebelumnya dengan 5",
    ],
    answerIndex: 0,
    explanation: "Setiap sebutan ialah separuh daripada sebutan sebelumnya.",
  },
  {
    id: "math-f2-c1-bm-f24",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Yang manakah mempunyai pola penambahan tetap?",
    options: ["2, 5, 8, 11, …", "2, 4, 8, 16, …", "1, 1, 2, 3, 5, …", "20, 10, 5, 2.5, …"],
    answerIndex: 0,
    explanation: "Setiap sebutan bertambah 3.",
  },
  {
    id: "math-f2-c1-bm-f25",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n−8, −3, 2, 7, …",
    options: ["10", "11", "12", "13"],
    answerIndex: 2,
    explanation: "Setiap sebutan bertambah 5. Maka, 7 + 5 = 12.",
  },
  {
    id: "math-f2-c1-bm-f26",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n4.5, 4.0, 3.5, 3.0, …",
    options: ["1.5", "2.0", "2.5", "3.5"],
    answerIndex: 2,
    explanation: "Setiap sebutan berkurang 0.5.",
  },
  {
    id: "math-f2-c1-bm-f27",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah T₁ bagi jujukan\r\n−6, −2, 2, 6, …?",
    options: ["−6", "−2", "2", "6"],
    answerIndex: 0,
    explanation: "T₁ ialah sebutan pertama, iaitu −6.",
  },
  {
    id: "math-f2-c1-bm-f28",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Lengkapkan jujukan Fibonacci:\r\n1, 1, 2, 3, 5, __, 13",
    options: ["6", "7", "8", "10"],
    answerIndex: 2,
    explanation: "3 + 5 = 8 dan 5 + 8 = 13.",
  },
  {
    id: "math-f2-c1-bm-f29",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah operasi bagi jujukan\r\n30, 27, 24, 21, …?",
    options: ["+3", "−3", "×3", "÷3"],
    answerIndex: 1,
    explanation: "Setiap sebutan berkurang 3.",
  },
  {
    id: "math-f2-c1-bm-f30",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Suatu corak mempunyai 2 petak pada Corak 1, 5 petak pada Corak 2 dan 8 petak pada Corak 3. Berapakah bilangan petak pada Corak 4?",
    options: ["9", "10", "11", "12"],
    answerIndex: 2,
    explanation: "Bilangan petak bertambah 3 setiap kali: 2, 5, 8, 11.",
  },
];

export const mathF2C1PracticeQuizzesBM: QuizQuestion[] = [
  {
    id: "math-f2-c1-bm-p1",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan dua sebutan seterusnya:\r\n14, 22, 30, 38, …",
    options: ["44, 50", "46, 54", "46, 52", "48, 56"],
    answerIndex: 1,
    explanation: "Tambah 8 setiap kali.",
  },
  {
    id: "math-f2-c1-bm-p2",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Lengkapkan jujukan:\r\n71, 62, __, 44, __",
    options: ["54, 35", "53, 35", "53, 36", "52, 34"],
    answerIndex: 1,
    explanation: "Tolak 9 setiap kali: 71, 62, 53, 44, 35.",
  },
  {
    id: "math-f2-c1-bm-p3",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n1.5, 4.5, 13.5, 40.5, …",
    options: ["81", "94.5", "121.5", "162"],
    answerIndex: 2,
    explanation: "Setiap sebutan didarab dengan 3.",
  },
  {
    id: "math-f2-c1-bm-p4",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Lengkapkan jujukan:\r\n320, 160, 80, __, 20",
    options: ["30", "40", "50", "60"],
    answerIndex: 1,
    explanation: "Setiap sebutan dibahagi dengan 2.",
  },
  {
    id: "math-f2-c1-bm-p5",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Suatu jujukan bermula dengan −12 dan bertambah 7 setiap kali. Apakah T₅?",
    options: ["9", "16", "23", "28"],
    answerIndex: 1,
    explanation: "Jujukannya ialah −12, −5, 2, 9, 16.",
  },
  {
    id: "math-f2-c1-bm-p6",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Suatu jujukan bermula dengan 64 dan berkurang 6 setiap kali. Apakah T₆?",
    options: ["28", "30", "34", "40"],
    answerIndex: 2,
    explanation: "Jujukannya ialah 64, 58, 52, 46, 40, 34.",
  },
  {
    id: "math-f2-c1-bm-p7",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagi jujukan\r\n3, 11, 19, 27, …\r\n43 ialah sebutan yang keberapa?",
    options: ["T₅", "T₆", "T₇", "T₈"],
    answerIndex: 1,
    explanation: "Jujukan diteruskan dengan 35, 43. Maka, 43 ialah T₆.",
  },
  {
    id: "math-f2-c1-bm-p8",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagi jujukan\r\n82, 75, 68, 61, …\r\n47 ialah sebutan yang keberapa?",
    options: ["T₅", "T₆", "T₇", "T₈"],
    answerIndex: 1,
    explanation: "T₅ = 54 dan T₆ = 47.",
  },
  {
    id: "math-f2-c1-bm-p9",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Ungkapan manakah mewakili\r\n6, 11, 16, 21, …\r\nbagi n = 1, 2, 3, …?",
    options: ["5n", "5n + 1", "6n − 1", "6n"],
    answerIndex: 1,
    explanation: "5(1)+1=6, 5(2)+1=11 dan 5(3)+1=16.",
  },
  {
    id: "math-f2-c1-bm-p10",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Ungkapan manakah mewakili\r\n−2, 2, 6, 10, …?",
    options: ["4n − 6", "4n − 2", "6n − 8", "2n − 4"],
    answerIndex: 0,
    explanation: "4(1)−6=−2, 4(2)−6=2 dan seterusnya.",
  },
  {
    id: "math-f2-c1-bm-p11",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jika Tₙ = 3n + 2, apakah T₇?",
    options: ["21", "23", "25", "27"],
    answerIndex: 1,
    explanation: "T₇ = 3(7)+2 = 23.",
  },
  {
    id: "math-f2-c1-bm-p12",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jika Tₙ = 20 − 2n, apakah T₆?",
    options: ["6", "8", "10", "12"],
    answerIndex: 1,
    explanation: "T₆ = 20 − 12 = 8.",
  },
  {
    id: "math-f2-c1-bm-p13",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan dua Nombor Fibonacci seterusnya:\r\n5, 8, 13, 21, …",
    options: ["29, 42", "32, 53", "34, 55", "34, 56"],
    answerIndex: 2,
    explanation: "13+21=34 dan 21+34=55.",
  },
  {
    id: "math-f2-c1-bm-p14",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Suatu jujukan jenis Fibonacci bermula dengan\r\n2, 3, 5, 8, … .\r\nApakah sebutan keenam?",
    options: ["11", "12", "13", "21"],
    answerIndex: 3,
    explanation: "Jujukannya ialah 2, 3, 5, 8, 13, 21.",
  },
  {
    id: "math-f2-c1-bm-p15",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah nombor di tengah bagi baris\r\n1, 4, 6, 4, 1\r\ndalam Segi Tiga Pascal?",
    options: ["4", "5", "6", "8"],
    answerIndex: 2,
    explanation: "Nombor di tengah ialah 6.",
  },
  {
    id: "math-f2-c1-bm-p16",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Baris seterusnya selepas\r\n1, 5, 10, 10, 5, 1\r\nialah:",
    options: [
      "1, 6, 15, 20, 15, 6, 1",
      "1, 6, 16, 20, 16, 6, 1",
      "1, 5, 15, 20, 15, 5, 1",
      "1, 7, 15, 20, 15, 7, 1",
    ],
    answerIndex: 0,
    explanation: "Dua nombor bersebelahan pada baris sebelumnya ditambah.",
  },
  {
    id: "math-f2-c1-bm-p17",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Daripada senarai\r\n13, 18, 23, 28, 33, 38, 43,\r\napakah jujukan nombor ganjil?",
    options: ["13, 23, 33, 43", "13, 18, 23, 28", "18, 28, 38", "23, 33, 43"],
    answerIndex: 0,
    explanation: "Nombor ganjil ialah 13, 23, 33 dan 43.",
  },
  {
    id: "math-f2-c1-bm-p18",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagi nombor genap dalam senarai\r\n13, 18, 23, 28, 33, 38, 43,\r\napakah polanya?",
    options: ["+5", "+10", "+15", "+20"],
    answerIndex: 1,
    explanation: "Jujukan nombor genap ialah 18, 28, 38.",
  },
  {
    id: "math-f2-c1-bm-p19",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n1/2, 1, 3/2, 2, …",
    options: ["2¼", "2½", "3", "3½"],
    answerIndex: 1,
    explanation: "Tambah 1/2 setiap kali.",
  },
  {
    id: "math-f2-c1-bm-p20",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n3.2, 1.6, 0.8, 0.4, …",
    options: ["0.1", "0.2", "0.3", "0.35"],
    answerIndex: 1,
    explanation: "Setiap sebutan dibahagi dengan 2.",
  },
  {
    id: "math-f2-c1-bm-p21",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jujukan manakah mempunyai pola “darab nombor sebelumnya dengan 4”?",
    options: ["2, 6, 10, 14, …", "2, 8, 32, 128, …", "4, 8, 12, 16, …", "128, 32, 8, 2, …"],
    answerIndex: 1,
    explanation: "Setiap sebutan ialah empat kali sebutan sebelumnya.",
  },
  {
    id: "math-f2-c1-bm-p22",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jujukan manakah mempunyai pola “bahagi nombor sebelumnya dengan 3”?",
    options: [
      "243, 81, 27, 9, …",
      "243, 240, 237, 234, …",
      "3, 9, 27, 81, …",
      "243, 121.5, 60.75, …",
    ],
    answerIndex: 0,
    explanation: "243 ÷ 3 = 81 dan seterusnya.",
  },
  {
    id: "math-f2-c1-bm-p23",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Suatu corak jubin mempunyai 5 jubin pada Corak 1, 9 pada Corak 2 dan 13 pada Corak 3. Berapakah bilangan jubin pada Corak 7?",
    options: ["25", "27", "29", "31"],
    answerIndex: 2,
    explanation: "Tambah 4 setiap kali: 5, 9, 13, 17, 21, 25, 29.",
  },
  {
    id: "math-f2-c1-bm-p24",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Sebuah dewan mempunyai 12 kerusi pada Baris 1. Setiap baris seterusnya mempunyai 3 kerusi lebih banyak. Berapakah bilangan kerusi pada Baris 5?",
    options: ["21", "24", "27", "30"],
    answerIndex: 1,
    explanation: "Bilangannya ialah 12, 15, 18, 21, 24.",
  },
  {
    id: "math-f2-c1-bm-p25",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Bas bertolak setiap 20 minit. Bas pertama bertolak pada pukul 8:10 pagi. Pukul berapakah bas keempat bertolak?",
    options: ["8:50 pagi", "9:00 pagi", "9:10 pagi", "9:30 pagi"],
    answerIndex: 2,
    explanation: "8:10, 8:30, 8:50, 9:10.",
  },
  {
    id: "math-f2-c1-bm-p26",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Sebuah mesin mengeluarkan makanan 6 kali secara sama jarak dalam tempoh 24 jam. Berapakah selang masa antara setiap pemberian?",
    options: ["2 jam", "3 jam", "4 jam", "6 jam"],
    answerIndex: 2,
    explanation: "24 ÷ 6 = 4 jam.",
  },
  {
    id: "math-f2-c1-bm-p27",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Pemberian pertama berlaku pada pukul 6:15 pagi dan makanan diberikan setiap 4 jam. Pukul berapakah pemberian ketiga?",
    options: ["10:15 pagi", "12:15 tengah hari", "2:15 petang", "4:15 petang"],
    answerIndex: 2,
    explanation: "6:15 pagi, 10:15 pagi, 2:15 petang.",
  },
  {
    id: "math-f2-c1-bm-p28",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jujukan\r\n4, 7, 10, 13, …\r\ndiwakili oleh Tₙ = 3n + 1. Apakah T₅?",
    options: ["15", "16", "17", "18"],
    answerIndex: 1,
    explanation: "3(5)+1 = 16.",
  },
  {
    id: "math-f2-c1-bm-p29",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jika Tₙ = 5n + 1 dan Tₙ = 31, apakah nilai n?",
    options: ["5", "6", "7", "8"],
    answerIndex: 1,
    explanation: "5n+1=31, maka 5n=30 dan n=6.",
  },
  {
    id: "math-f2-c1-bm-p30",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Pernyataan manakah betul bagi\r\n7, 14, 21, 28, …?",
    options: [
      "Pola +7 dan Tₙ = 7n",
      "Pola ×7 dan Tₙ = 7+n",
      "Pola +14 dan Tₙ = 14n",
      "Pola −7 dan Tₙ = 7n−7",
    ],
    answerIndex: 0,
    explanation: "Jujukan bertambah 7 dan setiap sebutan ialah gandaan 7.",
  },
];

export const mathF2C1ChallengeQuizzesBM: QuizQuestion[] = [
  {
    id: "math-f2-c1-bm-c1",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan dua sebutan seterusnya:\r\n3, 8, 15, 24, 35, …",
    options: ["46, 59", "47, 61", "48, 63", "49, 64"],
    answerIndex: 2,
    explanation: "Bezanya ialah +5, +7, +9, +11. Seterusnya +13 dan +15.",
  },
  {
    id: "math-f2-c1-bm-c2",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan dua sebutan seterusnya:\r\n7, 5, 8, 4, 9, 3, …",
    options: ["10, 2", "9, 1", "11, 2", "10, 1"],
    answerIndex: 0,
    explanation: "Polanya ialah −2, +3, −4, +5, −6, maka seterusnya +7 dan −8.",
  },
  {
    id: "math-f2-c1-bm-c3",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan dua sebutan seterusnya:\r\n2, 4, 5, 10, 12, 24, 27, …",
    options: ["48, 51", "54, 58", "54, 60", "56, 60"],
    answerIndex: 1,
    explanation: "Polanya berselang-seli ×2, +1, ×2, +2, ×2, +3. Seterusnya ×2 dan +4.",
  },
  {
    id: "math-f2-c1-bm-c4",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n1, 4, 9, 18, 35, …",
    options: ["66", "67", "68", "70"],
    answerIndex: 2,
    explanation: "Operasi ialah ×2+2, ×2+1, ×2+0, ×2−1. Seterusnya ×2−2.",
  },
  {
    id: "math-f2-c1-bm-c5",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n2, 5, 11, 23, 47, …",
    options: ["71", "94", "95", "96"],
    answerIndex: 2,
    explanation: "Darab 2 kemudian tambah 1.",
  },
  {
    id: "math-f2-c1-bm-c6",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n100, 96, 88, 76, 60, …",
    options: ["36", "40", "42", "44"],
    answerIndex: 1,
    explanation: "Tolak 4, 8, 12, 16. Seterusnya tolak 20.",
  },
  {
    id: "math-f2-c1-bm-c7",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n4, 7, 15, 31, 63, …",
    options: ["95", "111", "126", "127"],
    answerIndex: 3,
    explanation: "Daripada 7, polanya ialah darab 2 dan tambah 1.",
  },
  {
    id: "math-f2-c1-bm-c8",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tentukan sebutan seterusnya:\r\n1, 3, 6, 10, 15, 21, …",
    options: ["26", "27", "28", "30"],
    answerIndex: 2,
    explanation: "Tambahan ialah +2, +3, +4, +5, +6. Seterusnya +7.",
  },
  {
    id: "math-f2-c1-bm-c9",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Ungkapan manakah mewakili\r\n11, 18, 25, 32, …?",
    options: ["7n + 4", "7n + 11", "11n − 4", "4n + 7"],
    answerIndex: 0,
    explanation: "7(1)+4=11, 7(2)+4=18 dan seterusnya.",
  },
  {
    id: "math-f2-c1-bm-c10",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Ungkapan manakah mewakili\r\n18, 14, 10, 6, …?",
    options: ["22 − 4n", "18 − 4n", "20 − 2n", "4n + 14"],
    answerIndex: 0,
    explanation: "22−4(1)=18, 22−4(2)=14 dan seterusnya.",
  },
  {
    id: "math-f2-c1-bm-c11",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jika Tₙ = 6n − 5, apakah T₁₂?",
    options: ["62", "65", "67", "72"],
    answerIndex: 2,
    explanation: "T₁₂ = 72−5 = 67.",
  },
  {
    id: "math-f2-c1-bm-c12",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagi Tₙ = 4n + 3, nombor 39 ialah sebutan yang keberapa?",
    options: ["T₈", "T₉", "T₁₀", "T₁₁"],
    answerIndex: 1,
    explanation: "4n+3=39, maka n=9.",
  },
  {
    id: "math-f2-c1-bm-c13",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Empat sebutan pertama ialah\r\n13, 9, 5, 1, … .\r\nApakah T₁₀?",
    options: ["−19", "−21", "−23", "−25"],
    answerIndex: 2,
    explanation: "Tolak 4 setiap kali. T₁₀ = 13 + 9(−4) = −23.",
  },
  {
    id: "math-f2-c1-bm-c14",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Sebutan pertama ialah −7 dan setiap sebutan bertambah 6. Nombor 35 ialah sebutan yang keberapa?",
    options: ["T₆", "T₇", "T₈", "T₉"],
    answerIndex: 2,
    explanation: "−7, −1, 5, 11, 17, 23, 29, 35.",
  },
  {
    id: "math-f2-c1-bm-c15",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Suatu corak mempunyai 4 objek pada Corak 1, 9 pada Corak 2 dan 14 pada Corak 3. Ungkapan manakah memberikan bilangan objek pada Corak ke-n?",
    options: ["4n + 5", "5n − 1", "5n + 4", "9n − 5"],
    answerIndex: 1,
    explanation: "5(1)−1=4, 5(2)−1=9 dan 5(3)−1=14.",
  },
  {
    id: "math-f2-c1-bm-c16",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Jika Tₙ = 5n − 1, berapakah bilangan objek pada Corak 20?",
    options: ["95", "96", "99", "101"],
    answerIndex: 2,
    explanation: "5(20)−1 = 99.",
  },
  {
    id: "math-f2-c1-bm-c17",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Seorang murid mengatakan sebutan seterusnya bagi\r\n0, 1, 1, 2, 3, 5, 8, …\r\nialah 12. Pernyataan manakah betul?",
    options: [
      "Betul kerana 8 + 4 = 12",
      "Betul kerana setiap sebutan bertambah 4",
      "Salah; sebutan seterusnya ialah 13",
      "Salah; sebutan seterusnya ialah 16",
    ],
    answerIndex: 2,
    explanation: "Dalam jujukan Fibonacci, 5 + 8 = 13.",
  },
  {
    id: "math-f2-c1-bm-c18",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Dalam baris Segi Tiga Pascal\r\n1, 6, 15, 20, 15, 6, 1,\r\nberapakah hasil tambah dua nombor yang berada tepat di sebelah 20?",
    options: ["21", "24", "30", "35"],
    answerIndex: 2,
    explanation: "15 + 15 = 30.",
  },
  {
    id: "math-f2-c1-bm-c19",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Dalam Segi Tiga Pascal, jika sebahagian dua baris berturutan ialah:\r\n\r\n... 5, 10, 10, 5 ...\r\n... ?, 15, 20, 15, ? ...\r\n\r\nApakah nombor pada kedua-dua tempat bertanda soal?",
    options: ["5", "6", "10", "15"],
    answerIndex: 1,
    explanation: "Baris lengkap ialah 1, 6, 15, 20, 15, 6, 1.",
  },
  {
    id: "math-f2-c1-bm-c20",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Suatu jujukan jenis Fibonacci bermula dengan\r\n4, 7, 11, 18, 29, … .\r\nApakah T₇?",
    options: ["47", "58", "76", "105"],
    answerIndex: 2,
    explanation: "T₆=47 dan T₇=29+47=76.",
  },
  {
    id: "math-f2-c1-bm-c21",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Lima buah bas bertolak pada selang masa yang sama. Bas A bertolak pada 7:40 pagi, Bas B pada 8:05 pagi dan Bas C pada 8:30 pagi. Pukul berapakah Bas E bertolak?",
    options: ["8:55 pagi", "9:10 pagi", "9:20 pagi", "9:30 pagi"],
    answerIndex: 2,
    explanation: "Selangnya 25 minit. Bas D = 8:55 pagi dan Bas E = 9:20 pagi.",
  },
  {
    id: "math-f2-c1-bm-c22",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Sebuah van ulang-alik bertolak setiap 35 minit bermula pada 9:15 pagi. Pukul berapakah van kelima bertolak?",
    options: ["11:15 pagi", "11:25 pagi", "11:35 pagi", "11:45 pagi"],
    answerIndex: 2,
    explanation: "Empat selang masa berlaku selepas perjalanan pertama: 4×35=140 minit.",
  },
  {
    id: "math-f2-c1-bm-c23",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Sebuah mesin memberi makanan ikan 8 kali dalam tempoh 24 jam pada selang masa yang sama. Jika pemberian pertama pada 5:30 pagi, pukul berapakah pemberian keempat?",
    options: ["11:30 pagi", "2:30 petang", "5:30 petang", "8:30 malam"],
    answerIndex: 1,
    explanation: "Selang masa ialah 24÷8=3 jam.",
  },
  {
    id: "math-f2-c1-bm-c24",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Sebuah dewan mempunyai 18 kerusi pada Baris 1. Setiap baris seterusnya mempunyai 4 kerusi tambahan. Berapakah bilangan kerusi pada Baris 12?",
    options: ["58", "60", "62", "66"],
    answerIndex: 2,
    explanation: "T₁₂ = 18 + 11(4) = 62.",
  },
  {
    id: "math-f2-c1-bm-c25",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Suatu corak dinding menggunakan 7 jubin pada Corak 1 dan bertambah 6 jubin bagi setiap corak seterusnya. Corak yang manakah menggunakan tepat 121 jubin?",
    options: ["Corak 18", "Corak 19", "Corak 20", "Corak 21"],
    answerIndex: 2,
    explanation: "7 + (n−1)6 = 121. Maka n = 20.",
  },
  {
    id: "math-f2-c1-bm-c26",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Jujukan bermula dengan\r\n−5, 2, 9, 16, … .\r\nSeorang murid mengatakan T₁₅ = 93. Adakah murid itu betul?",
    options: [
      "Ya, kerana T₁₅ = −5 + 14(7) = 93",
      "Ya, kerana 15×7 = 105",
      "Tidak, kerana T₁₅ = 100",
      "Tidak, kerana T₁₅ = 86",
    ],
    answerIndex: 0,
    explanation: "Dari T₁ ke T₁₅ terdapat 14 penambahan sebanyak 7.",
  },
  {
    id: "math-f2-c1-bm-c27",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Jujukan A ialah\r\n4, 9, 14, 19, …\r\ndan Jujukan B ialah\r\n7, 12, 17, 22, … .\r\nPernyataan manakah betul?",
    options: [
      "Jujukan A meningkat lebih cepat",
      "Jujukan B meningkat lebih cepat",
      "Kedua-duanya bertambah dengan nilai yang sama",
      "Kedua-duanya bermula dengan nombor yang sama",
    ],
    answerIndex: 2,
    explanation: "Kedua-dua jujukan bertambah 5 setiap kali.",
  },
  {
    id: "math-f2-c1-bm-c28",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Nombor manakah terdapat dalam KEDUA-DUA jujukan berikut?\r\n\r\nJujukan A: 2, 8, 14, 20, 26, …\r\nJujukan B: 5, 12, 19, 26, 33, …",
    options: ["14", "19", "20", "26"],
    answerIndex: 3,
    explanation: "26 terdapat dalam kedua-dua jujukan.",
  },
  {
    id: "math-f2-c1-bm-c29",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Suatu jujukan diberikan oleh Tₙ = 8n − 3. Satu lagi jujukan diberikan oleh Sₙ = 5n + 9. Pada nilai n yang manakah kedua-dua sebutan adalah sama?",
    options: ["3", "4", "5", "6"],
    answerIndex: 1,
    explanation: "8n−3 = 5n+9. Maka 3n=12 dan n=4.",
  },
  {
    id: "math-f2-c1-bm-c30",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Jujukan pertama ialah\r\n10, 16, 22, 28, … .\r\nJujukan kedua ialah\r\n4, 13, 22, 31, … .\r\nPada kedudukan sebutan yang manakah kedua-dua jujukan pertama kali mempunyai nilai yang sama?",
    options: ["T₁", "T₂", "T₃", "T₄"],
    answerIndex: 2,
    explanation: "Kedua-dua jujukan mempunyai nilai 22 pada sebutan ketiga.",
  },
];

export const mathF2C1QuizzesBM: QuizQuestion[] = [
  ...mathF2C1FoundationQuizzesBM,
  ...mathF2C1PracticeQuizzesBM,
  ...mathF2C1ChallengeQuizzesBM,
];
