import type { Difficulty, QuizQuestion } from "@/data/content";
import { buildForm3MathQuizSets } from "../quiz-sets";
import { MATH_F3_C8_QUIZ_VISUALS } from "./quiz-visuals";
import { MATH_F3_C8_QUIZ_EXPLANATIONS } from "./quiz-explanations";
type QuizSeed = [Difficulty, string, [string, string, string, string], number];
function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c8-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty,
    question,
    options,
    answerIndex,
    mathNotation: "indices",
    visual: MATH_F3_C8_QUIZ_VISUALS[index + 1],
    explanation: MATH_F3_C8_QUIZ_EXPLANATIONS[index + 1].bm,
  }));
}
export const mathF3C8QuestionBankBM: QuizQuestion[] = buildQuiz([
  [
    "Easy",
    "Apakah maksud lokus?",
    [
      "Surihan/lintasan satu set titik yang memenuhi syarat tertentu",
      "Satu titik tetap sahaja",
      "Sebarang garis lurus",
      "Luas sesuatu bentuk",
    ],
    0,
  ],
  [
    "Easy",
    "Satu titik pada sayap kipas, bukan pada paksi, berputar satu pusingan penuh tentang paksi tetap. Apakah bentuk lokusnya?",
    ["Bulatan", "Garis lurus", "Segi tiga", "Segi empat"],
    0,
  ],
  [
    "Easy",
    "Roket bergerak menegak ke atas tanpa perubahan arah. Apakah bentuk lintasan satu titik pada roket?",
    ["Garis lurus", "Bulatan", "Lengkok", "Sfera"],
    0,
  ],
  [
    "Easy",
    "Dalam satu satah, apakah lokus titik pada jarak tetap r daripada O, dengan r > 0?",
    [
      "Bulatan berpusat O dan berjejari r",
      "Garis lurus melalui O",
      "Pembahagi dua sama sudut",
      "Sepasang garis selari",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah lokus titik berjarak sama dari dua titik tetap?",
    [
      "Pembahagi dua sama serenjang",
      "Bulatan",
      "Garis selari",
      "Pembahagi dua sudut",
    ],
    0,
  ],
  [
    "Easy",
    "Dalam seluruh satah, apakah lokus titik pada jarak tetap positif daripada satu garis lurus tanpa had?",
    [
      "Sepasang garis selari, satu pada setiap sisi",
      "Satu bulatan",
      "Satu garis sahaja",
      "Pembahagi dua sama sudut",
    ],
    0,
  ],
  [
    "Easy",
    "Titik P bergerak dengan jarak serenjang yang sama dari dua garis selari AB dan CD (d₁ = d₂). Apakah lokus P?",
    [
      "Satu garis lurus selari di tengah-tengah",
      "Bulatan",
      "Pembahagi dua sudut",
      "Lengkok",
    ],
    0,
  ],
  [
    "Easy",
    "Dalam seluruh satah, apakah lokus titik yang sama jarak dari dua garis lurus bersilang?",
    [
      "Kedua-dua pembahagi dua sama sudut",
      "Satu pembahagi dua sama serenjang",
      "Satu bulatan",
      "Sepasang garis selari",
    ],
    0,
  ],
  [
    "Easy",
    "Bina lokus P berjarak 3cm dari titik O. Apakah bentuknya?",
    [
      "Bulatan jejari 3cm berpusat O",
      "Garis lurus 3cm",
      "Segi tiga",
      "Pembahagi dua sudut",
    ],
    0,
  ],
  [
    "Easy",
    "Segi empat tepat diputar 360° tentang salah satu sisinya sebagai paksi tetap. Apakah pepejal yang terhasil?",
    ["Silinder tegak", "Sfera", "Kon", "Kubus"],
    0,
  ],
  [
    "Easy",
    "Separuh bulatan diputar 360° tentang diameternya sebagai paksi tetap. Apakah pepejal yang terhasil?",
    ["Sfera", "Silinder", "Kon", "Piramid"],
    0,
  ],
  [
    "Easy",
    "Lokus P ialah bulatan berpusat O dan berjejari 4 cm. Titik Q berjarak 3 cm dari O. Di manakah Q berbanding bulatan lokus itu?",
    [
      "Di dalam bulatan",
      "Pada lilitan bulatan",
      "Di luar bulatan",
      "Di pusat bulatan",
    ],
    0,
  ],
  [
    "Easy",
    "Pembahagi dua sama serenjang bagi segmen AB melalui titik M pada AB. Jika AB = 10 cm, berapakah AM?",
    ["5 cm", "10 cm", "20 cm", "2.5 cm"],
    0,
  ],
  [
    "Easy",
    "Apakah lokus bagi titik pada bandul yang berayun?",
    ["Lengkok", "Garis lurus", "Bulatan penuh", "Sfera"],
    0,
  ],
  [
    "Easy",
    "Dalam seluruh satah, berapakah bilangan garis dalam lokus titik pada jarak tetap r > 0 daripada satu garis lurus?",
    ["2", "1", "3", "4"],
    0,
  ],
  [
    "Easy",
    "Apakah nama garis yang membahagi dua sama sudut antara dua garis bersilang?",
    [
      "Pembahagi dua sudut (angle bisector)",
      "Pembahagi dua serenjang",
      "Garis normal",
      "Garis tangen",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah nama garis yang berserenjang dengan satu segmen dan melalui titik tengahnya?",
    [
      "Pembahagi dua sama serenjang",
      "Pembahagi dua sudut",
      "Garis tangen",
      "Garis normal",
    ],
    0,
  ],
  [
    "Easy",
    "T berjarak 1.5cm dari garis lurus tanpa had CD. Apakah lokus T?",
    [
      "Sepasang garis selari CD, jarak 1.5cm",
      "Bulatan jejari 1.5cm",
      "Satu garis sahaja",
      "Pembahagi dua sudut",
    ],
    0,
  ],
  [
    "Easy",
    "A(−2,0) dan B(2,0) ialah dua titik tetap. Titik manakah berada pada lokus titik yang sama jarak dari A dan B?",
    ["(0, 3)", "(1, 3)", "(−1, 3)", "(2, 3)"],
    0,
  ],
  [
    "Easy",
    "O ialah asalan. Titik manakah berada pada jarak 5 unit dari O?",
    ["(3, 4)", "(3, 3)", "(0, 4)", "(6, 0)"],
    0,
  ],
  [
    "Medium",
    "X berjarak sama dari titik P dan R (segi tiga sama sisi PQR). Apakah lokus X?",
    [
      "Pembahagi dua sama serenjang PR",
      "Bulatan berpusat P",
      "Garis selari PR",
      "Pembahagi dua sudut P",
    ],
    0,
  ],
  [
    "Medium",
    "Lukis lokus X bergerak 3 unit dari garis lurus tanpa had AB. Apakah hasilnya?",
    [
      "Sepasang garis selari AB, berjarak 3 unit",
      "Satu bulatan jejari 3 unit",
      "Satu garis sahaja",
      "Pembahagi dua sudut",
    ],
    0,
  ],
  [
    "Medium",
    "ABCD ialah segi empat tepat. X terhad di dalam atau pada sempadan ABCD dan sama jarak dari garis AB dan DC. Apakah lokus X?",
    [
      "Segmen yang menghubungkan titik tengah AD dan BC",
      "Bulatan berpusat A",
      "Pepenjuru AC",
      "Keseluruhan garis AB",
    ],
    0,
  ],
  [
    "Medium",
    "X terletak di bahagian dalam ∠QPN dan sama jarak dari garis PQ dan PN. Apakah lokus X dalam sudut itu?",
    [
      "Bahagian pembahagi dua sama ∠QPN di dalam sudut",
      "Pembahagi dua sama serenjang PQ",
      "Bulatan berpusat P",
      "Garis selari PQ",
    ],
    0,
  ],
  [
    "Medium",
    "ABCD ialah segi empat sama. Y terhad kepada ABCD, termasuk sempadan, dan sama jarak dari garis AB dan AD. Apakah lokus Y?",
    ["Pepenjuru AC", "Pepenjuru BD", "Sisi AB", "Bulatan berpusat A"],
    0,
  ],
  [
    "Medium",
    "ABCD ialah segi empat sama: A(0,0), B(8,0), C(8,8), D(0,8). X berada dalam atau pada sempadan ABCD, berjarak 5 unit dari A dan sama jarak dari garis AB dan CD. Berapakah kedudukan X yang mungkin?",
    ["1", "2", "3", "4"],
    0,
  ],
  [
    "Medium",
    "Garis MN, titik P berjarak sama dari M dan N. Bagaimana bina lokus P?",
    [
      "Lukis pembahagi dua sama serenjang MN",
      "Lukis bulatan jejari MN",
      "Lukis garis selari MN",
      "Lukis pembahagi dua sudut M",
    ],
    0,
  ],
  [
    "Medium",
    "Garis lurus melalui O(0,0), P(−2,−2) dan Q(4,4). Persamaan manakah menerangkan garis itu?",
    ["y = x", "y = −x", "y = 2", "x = 2"],
    0,
  ],
  [
    "Medium",
    "Garis melalui (0,0), (−2,−2) dan (4,4) ialah y = x. Hitung sudut tirus antara garis itu dengan paksi-x positif.",
    ["45°", "90°", "60°", "30°"],
    0,
  ],
  [
    "Medium",
    "Dalam seluruh satah Cartes, Faruk sama jarak dari paksi-x dan paksi-y serta kurang daripada 5 unit dari O. Apakah lokus yang memenuhi kedua-dua syarat?",
    [
      "Bahagian kedua-dua garis y = x dan y = −x di dalam bulatan jejari 5, tanpa titik pada bulatan",
      "Bulatan jejari 5 sahaja",
      "Garis y = x sahaja tanpa had jarak",
      "Paksi-x sahaja",
    ],
    0,
  ],
  [
    "Medium",
    "Segi empat sama ABCD, P bergerak sama jarak dari A dan D. Apakah lokus P?",
    [
      "Pembahagi dua sama serenjang AD",
      "Bulatan berpusat A",
      "Pembahagi dua sudut A",
      "Garis selari AD",
    ],
    0,
  ],
  [
    "Medium",
    "Q terhad kepada segi empat sama ABCD, termasuk sempadan, dan sama jarak dari B dan D. Apakah lokus Q?",
    ["Pepenjuru AC", "Pepenjuru BD", "Bulatan berpusat B", "Sisi AB"],
    0,
  ],
  [
    "Medium",
    "R bergerak 4 unit dari garis lurus tanpa had yang melalui BC. Apakah lokus R?",
    [
      "Sepasang garis selari BC, jarak 4 unit",
      "Bulatan jejari 4 unit",
      "Pembahagi dua sudut BC",
      "Satu garis sahaja",
    ],
    0,
  ],
  [
    "Medium",
    "S terhad kepada segi empat sama ABCD, termasuk sempadan, dan sama jarak dari garis AB dan BC. Apakah lokus S?",
    ["Pepenjuru BD", "Pepenjuru AC", "Bulatan berpusat B", "Sisi BC"],
    0,
  ],
  [
    "Medium",
    "PQ ialah segmen sepanjang 5 cm. X berjarak 3 cm dari P. Huraikan lokus X.",
    [
      "Bulatan jejari 3cm berpusat P",
      "Garis lurus 3cm dari P",
      "Pembahagi dua serenjang PQ",
      "Bulatan jejari 5cm berpusat P",
    ],
    0,
  ],
  [
    "Medium",
    "PQ ialah segmen sepanjang 5 cm. Y bergerak pada jarak tetap 4 cm dari Q. Huraikan lokus Y.",
    [
      "Bulatan jejari 4cm berpusat Q",
      "Garis lurus 4cm dari Q",
      "Pembahagi dua serenjang PQ",
      "Bulatan jejari 5cm berpusat Q",
    ],
    0,
  ],
  [
    "Medium",
    "C dan D berada pada satu garis lurus tanpa had, dengan CD = 6 cm. Dalam seluruh satah, T berjarak 1.5 cm secara serenjang dari garis itu. Berapakah garis dalam lokus T?",
    ["2", "1", "3", "4"],
    0,
  ],
  [
    "Medium",
    "Kawasan ABCD ialah segi empat sama: A(0,0), B(8,0), C(8,8), D(0,8). Titik X terhad kepada kawasan termasuk sempadan, berjarak 5 unit dari D dan 3 unit dari garis BC. Berapakah kedudukan X yang mungkin?",
    ["1", "0", "2", "4"],
    0,
  ],
  [
    "Medium",
    "Empat segi empat sama bersisi 2 cm membentuk satu segi empat sama 4 cm × 4 cm. M ialah pusatnya. X terhad kepada segi empat sama itu, termasuk sempadan, dan berjarak 2 cm dari M. Apakah lokus X?",
    [
      "Bulatan berpusat M dan berjejari 2 cm",
      "Garis lurus melalui M",
      "Pembahagi dua sama serenjang satu sisi",
      "Pepenjuru segi empat sama",
    ],
    0,
  ],
  [
    "Medium",
    "PRTV ialah segi empat sama dengan bucu mengikut urutan. Y terhad kepada kawasan termasuk sempadan dan sama jarak dari garis PR dan PV. Apakah lokus Y?",
    ["Pepenjuru PT", "Pepenjuru RV", "Sisi PR", "Bulatan berpusat P"],
    0,
  ],
  [
    "Hard",
    "E(2,4), F(4,2), G(4,6) dan H(6,4) ialah empat kedudukan yang diberi. Faruk mesti sama jarak dari kedua-dua paksi dan kurang daripada 5 unit dari O. Kedudukan manakah memenuhi kedua-dua syarat?",
    ["Tiada satu pun daripada E, F, G dan H", "E atau F", "G", "H"],
    0,
  ],
  [
    "Hard",
    "E(3,3), F(−3,3), G(−4,−4) dan H(2,−2) semuanya sama jarak dari kedua-dua paksi. Titik manakah TIDAK berada kurang daripada 5 unit dari O?",
    ["G", "E", "F", "H"],
    0,
  ],
  [
    "Hard",
    "ABCD ialah segi empat sama: A(0,0), B(8,0), C(8,8), D(0,8). X terhad kepada kawasan termasuk sempadan, berjarak 7 unit dari A dan sama jarak dari garis AB dan CD. Cari koordinat X.",
    ["(√33, 4)", "(−√33, 4)", "(4, √33)", "(√33, 8)"],
    0,
  ],
  [
    "Hard",
    "Dalam seluruh satah, X berjarak 5 unit dari O dan 3 unit secara serenjang dari paksi-x. Berapakah kedudukan X yang mungkin?",
    ["4", "2", "1", "0"],
    0,
  ],
  [
    "Hard",
    "A(−3,0) dan B(3,0) ialah titik tetap. X sama jarak dari A dan B, berjarak 5 unit dari A dan berada di atas paksi-x. Cari X.",
    ["(0, 4)", "(0, −4)", "(4, 0)", "(3, 4)"],
    0,
  ],
  [
    "Hard",
    "P(0,0) dan Q(6,0) ialah titik tetap. X berjarak 5 unit dari kedua-duanya dan berada di atas paksi-x. Koordinat manakah memenuhi semua syarat?",
    ["(3, 4)", "(3, −4)", "(4, 3)", "(0, 5)"],
    0,
  ],
  [
    "Hard",
    "X berjarak 5 unit dari O, 2 unit secara serenjang dari paksi-y dan berada di atas paksi-x. Berapakah kedudukan X yang mungkin?",
    ["2", "4", "1", "0"],
    0,
  ],
  [
    "Hard",
    "ABCD ialah segi empat sama bersisi 6 unit dengan A(0,0), B(6,0), C(6,6), D(0,6). X terhad kepada kawasan, berjarak 5 unit dari A dan sama jarak dari garis AB dan AD. Cari koordinat X, betul kepada 2 tempat perpuluhan.",
    ["(3.54, 3.54)", "(5.00, 5.00)", "(2.50, 2.50)", "(−3.54, −3.54)"],
    0,
  ],
  [
    "Hard",
    "Segi empat tepat berukuran 3 cm × 5 cm diputar 360° tentang sisi 5 cm sebagai paksi. Berapakah isi padu pepejal yang terhasil, dalam sebutan π?",
    ["45π cm³", "15π cm³", "18π cm³", "90π cm³"],
    0,
  ],
  [
    "Hard",
    "X sama jarak dari garis y = 0 dan y = 6, serta berjarak 5 unit dari O. Jika x > 0, cari koordinat X.",
    ["(4, 3)", "(−4, 3)", "(3, 4)", "(4, −3)"],
    0,
  ],
]);
export const mathF3C8QuizzesBM: QuizQuestion[] = buildForm3MathQuizSets(
  8,
  mathF3C8QuestionBankBM,
);
