import type { Difficulty, QuizQuestion } from "@/data/content";
import { buildForm3MathQuizSets } from "../quiz-sets";
import { MATH_F3_C8_QUIZ_VISUALS } from "./quiz-visuals";
import { MATH_F3_C8_QUIZ_EXPLANATIONS } from "./quiz-explanations";
type QuizSeed = [Difficulty, string, [string, string, string, string], number];
function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c8-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    chapter: "Chapter 8",
    lang: "dlp",
    difficulty,
    question,
    options,
    answerIndex,
    mathNotation: "indices",
    visual: MATH_F3_C8_QUIZ_VISUALS[index + 1],
    explanation: MATH_F3_C8_QUIZ_EXPLANATIONS[index + 1].dlp,
  }));
}
export const mathF3C8QuestionBankDLP: QuizQuestion[] = buildQuiz([
  [
    "Easy",
    "What does locus mean?",
    [
      "A path/trace of a set of points satisfying certain conditions",
      "A single fixed point only",
      "Any straight line",
      "The area of a shape",
    ],
    0,
  ],
  [
    "Easy",
    "A point on a fan blade, away from the axis, makes one full rotation about a fixed axis. What shape is its locus?",
    ["Circle", "Straight line", "Triangle", "Rectangle"],
    0,
  ],
  [
    "Easy",
    "A rocket moves vertically upwards without changing direction. What shape is the path of a point on the rocket?",
    ["Straight line", "Circle", "Arc", "Sphere"],
    0,
  ],
  [
    "Easy",
    "In a plane, what is the locus of points at fixed distance r from O, where r > 0?",
    [
      "A circle with centre O and radius r",
      "A straight line through O",
      "An angle bisector",
      "A pair of parallel lines",
    ],
    0,
  ],
  [
    "Easy",
    "What is the locus of a point equidistant from two fixed points?",
    ["Perpendicular bisector", "A circle", "Parallel lines", "Angle bisector"],
    0,
  ],
  [
    "Easy",
    "Over the whole plane, what is the locus of points at a fixed positive distance from an infinite straight line?",
    [
      "A pair of parallel lines, one on each side",
      "A circle",
      "Only one line",
      "An angle bisector",
    ],
    0,
  ],
  [
    "Easy",
    "Point P moves so its perpendicular distances from parallel lines AB and CD are equal (d₁ = d₂). What is its locus?",
    [
      "A straight line parallel midway between them",
      "A circle",
      "An angle bisector",
      "An arc",
    ],
    0,
  ],
  [
    "Easy",
    "Over the whole plane, what is the locus of points equidistant from two intersecting straight lines?",
    [
      "Both angle bisectors",
      "One perpendicular bisector",
      "A circle",
      "A pair of parallel lines",
    ],
    0,
  ],
  [
    "Easy",
    "Construct the locus of P at 3cm from point O. What shape is it?",
    [
      "A circle of radius 3cm centred at O",
      "A straight line of 3cm",
      "A triangle",
      "An angle bisector",
    ],
    0,
  ],
  [
    "Easy",
    "A rectangle is rotated through 360° about one of its sides as a fixed axis. Which solid is produced?",
    ["Right cylinder", "Sphere", "Cone", "Cube"],
    0,
  ],
  [
    "Easy",
    "A semicircle is rotated through 360° about its diameter as a fixed axis. Which solid is produced?",
    ["Sphere", "Cylinder", "Cone", "Pyramid"],
    0,
  ],
  [
    "Easy",
    "The locus of P is a circle with centre O and radius 4 cm. Point Q is 3 cm from O. Where is Q relative to that circle?",
    [
      "Inside the circle",
      "On the circumference",
      "Outside the circle",
      "At the centre",
    ],
    0,
  ],
  [
    "Easy",
    "The perpendicular bisector of segment AB passes through M on AB. If AB = 10 cm, what is AM?",
    ["5 cm", "10 cm", "20 cm", "2.5 cm"],
    0,
  ],
  [
    "Easy",
    "What is the locus of a point on a swinging pendulum?",
    ["Arc", "Straight line", "Full circle", "Sphere"],
    0,
  ],
  [
    "Easy",
    "Over the whole plane, how many lines form the locus of points at fixed distance r > 0 from a straight line?",
    ["2", "1", "3", "4"],
    0,
  ],
  [
    "Easy",
    "What is the name of the line bisecting the angle between two intersecting lines?",
    ["Angle bisector", "Perpendicular bisector", "Normal line", "Tangent line"],
    0,
  ],
  [
    "Easy",
    "What is the name of the line perpendicular to a segment and passing through its midpoint?",
    ["Perpendicular bisector", "Angle bisector", "Tangent line", "Normal line"],
    0,
  ],
  [
    "Easy",
    "T is 1.5cm from infinite line CD. What is the locus of T?",
    [
      "A pair of lines parallel to CD, 1.5cm away",
      "A circle of radius 1.5cm",
      "Just one line",
      "An angle bisector",
    ],
    0,
  ],
  [
    "Easy",
    "A(−2,0) and B(2,0) are fixed points. Which point lies on the locus equidistant from A and B?",
    ["(0, 3)", "(1, 3)", "(−1, 3)", "(2, 3)"],
    0,
  ],
  [
    "Easy",
    "O is the origin. Which point is 5 units from O?",
    ["(3, 4)", "(3, 3)", "(0, 4)", "(6, 0)"],
    0,
  ],
  [
    "Medium",
    "X is equidistant from points P and R (equilateral triangle PQR). What is the locus of X?",
    [
      "The perpendicular bisector of PR",
      "A circle centred at P",
      "A line parallel to PR",
      "The angle bisector at P",
    ],
    0,
  ],
  [
    "Medium",
    "Draw the locus of X moving 3 units from infinite line AB. What is the result?",
    [
      "A pair of lines parallel to AB, 3 units away",
      "A single circle of radius 3 units",
      "Just one line",
      "An angle bisector",
    ],
    0,
  ],
  [
    "Medium",
    "ABCD is a rectangle. X is restricted to its interior or boundary and is equidistant from lines AB and DC. What is its locus?",
    [
      "The segment joining the midpoints of AD and BC",
      "A circle centred at A",
      "Diagonal AC",
      "The whole line AB",
    ],
    0,
  ],
  [
    "Medium",
    "X lies inside ∠QPN and is equidistant from lines PQ and PN. What is its locus within that angle?",
    [
      "The portion of the internal bisector of ∠QPN inside the angle",
      "The perpendicular bisector of PQ",
      "A circle centred at P",
      "A line parallel to PQ",
    ],
    0,
  ],
  [
    "Medium",
    "ABCD is a square. Y is restricted to ABCD, including its boundary, and is equidistant from lines AB and AD. What is its locus?",
    ["Diagonal AC", "Diagonal BD", "Side AB", "A circle centred at A"],
    0,
  ],
  [
    "Medium",
    "ABCD is a square: A(0,0), B(8,0), C(8,8), D(0,8). X is inside or on its boundary, 5 units from A and equidistant from lines AB and CD. How many positions are possible?",
    ["1", "2", "3", "4"],
    0,
  ],
  [
    "Medium",
    "Line MN, point P is equidistant from M and N. How do you construct the locus of P?",
    [
      "Draw the perpendicular bisector of MN",
      "Draw a circle of radius MN",
      "Draw a line parallel to MN",
      "Draw the angle bisector at M",
    ],
    0,
  ],
  [
    "Medium",
    "A straight line passes through O(0,0), P(−2,−2) and Q(4,4). Which equation describes it?",
    ["y = x", "y = −x", "y = 2", "x = 2"],
    0,
  ],
  [
    "Medium",
    "The line through (0,0), (−2,−2) and (4,4) is y = x. Find its acute angle with the positive x-axis.",
    ["45°", "90°", "60°", "30°"],
    0,
  ],
  [
    "Medium",
    "Over the whole Cartesian plane, Faruk is equidistant from the x- and y-axes and less than 5 units from O. Which locus satisfies both conditions?",
    [
      "The portions of both y = x and y = −x inside the radius-5 circle, excluding points on the circle",
      "Only the radius-5 circle",
      "Only y = x, with no distance limit",
      "Only the x-axis",
    ],
    0,
  ],
  [
    "Medium",
    "Square ABCD, P moves equidistant from A and D. What is the locus of P?",
    [
      "The perpendicular bisector of AD",
      "A circle centred at A",
      "The angle bisector at A",
      "A line parallel to AD",
    ],
    0,
  ],
  [
    "Medium",
    "Q is restricted to square ABCD, including its boundary, and is equidistant from B and D. What is its locus?",
    ["Diagonal AC", "Diagonal BD", "A circle centred at B", "Side AB"],
    0,
  ],
  [
    "Medium",
    "R moves 4 units from infinite straight line through BC. What is the locus of R?",
    [
      "A pair of lines parallel to BC, 4 units away",
      "A circle of radius 4 units",
      "The angle bisector at BC",
      "Just one line",
    ],
    0,
  ],
  [
    "Medium",
    "S is restricted to square ABCD, including its boundary, and is equidistant from lines AB and BC. What is its locus?",
    ["Diagonal BD", "Diagonal AC", "A circle centred at B", "Side BC"],
    0,
  ],
  [
    "Medium",
    "PQ is a line segment of length 5 cm. X is 3 cm from P. Describe its locus.",
    [
      "A circle of radius 3cm centred at P",
      "A straight line 3cm from P",
      "The perpendicular bisector of PQ",
      "A circle of radius 5cm centred at P",
    ],
    0,
  ],
  [
    "Medium",
    "PQ is a line segment of length 5 cm. Y moves at a fixed distance of 4 cm from Q. Describe the locus of Y.",
    [
      "A circle of radius 4cm centred at Q",
      "A straight line 4cm from Q",
      "The perpendicular bisector of PQ",
      "A circle of radius 5cm centred at Q",
    ],
    0,
  ],
  [
    "Medium",
    "C and D lie on an infinite straight line, with CD = 6 cm. Over the whole plane, T is at perpendicular distance 1.5 cm from the line. How many lines form its locus?",
    ["2", "1", "3", "4"],
    0,
  ],
  [
    "Medium",
    "Region ABCD is a square: A(0,0), B(8,0), C(8,8), D(0,8). X is restricted to the region including its boundary, 5 units from D and 3 units from line BC. How many positions are possible?",
    ["1", "0", "2", "4"],
    0,
  ],
  [
    "Medium",
    "Four squares of side 2 cm form a 4 cm × 4 cm square. M is its centre. X is restricted to the square, including its boundary, and is 2 cm from M. What is its locus?",
    [
      "A circle with centre M and radius 2 cm",
      "A straight line through M",
      "The perpendicular bisector of one side",
      "A diagonal of the square",
    ],
    0,
  ],
  [
    "Medium",
    "PRTV is a square with vertices in order. Y is restricted to the region including its boundary and is equidistant from lines PR and PV. What is its locus?",
    ["Diagonal PT", "Diagonal RV", "Side PR", "A circle centred at P"],
    0,
  ],
  [
    "Hard",
    "E(2,4), F(4,2), G(4,6) and H(6,4) are four given positions. Faruk must be equidistant from both axes and less than 5 units from O. Which position satisfies both conditions?",
    ["None of E, F, G or H", "E or F", "G", "H"],
    0,
  ],
  [
    "Hard",
    "E(3,3), F(−3,3), G(−4,−4) and H(2,−2) are all equidistant from both axes. Which point is NOT less than 5 units from O?",
    ["G", "E", "F", "H"],
    0,
  ],
  [
    "Hard",
    "ABCD is a square: A(0,0), B(8,0), C(8,8), D(0,8). X is restricted to the region including its boundary, 7 units from A and equidistant from lines AB and CD. Find X’s coordinates.",
    ["(√33, 4)", "(−√33, 4)", "(4, √33)", "(√33, 8)"],
    0,
  ],
  [
    "Hard",
    "Over the whole plane, X is 5 units from O and at perpendicular distance 3 units from the x-axis. How many positions are possible?",
    ["4", "2", "1", "0"],
    0,
  ],
  [
    "Hard",
    "A(−3,0) and B(3,0) are fixed points. X is equidistant from A and B, 5 units from A and above the x-axis. Find X.",
    ["(0, 4)", "(0, −4)", "(4, 0)", "(3, 4)"],
    0,
  ],
  [
    "Hard",
    "P(0,0) and Q(6,0) are fixed points. X is 5 units from both and above the x-axis. Which coordinates satisfy all conditions?",
    ["(3, 4)", "(3, −4)", "(4, 3)", "(0, 5)"],
    0,
  ],
  [
    "Hard",
    "X is 5 units from O, at perpendicular distance 2 units from the y-axis and above the x-axis. How many positions are possible?",
    ["2", "4", "1", "0"],
    0,
  ],
  [
    "Hard",
    "ABCD is a square of side 6 units with A(0,0), B(6,0), C(6,6), D(0,6). X is restricted to the region, 5 units from A and equidistant from lines AB and AD. Find X, correct to 2 decimal places.",
    ["(3.54, 3.54)", "(5.00, 5.00)", "(2.50, 2.50)", "(−3.54, −3.54)"],
    0,
  ],
  [
    "Hard",
    "A 3 cm × 5 cm rectangle is rotated through 360° about its 5 cm side as the axis. What is the volume of the resulting solid, in terms of π?",
    ["45π cm³", "15π cm³", "18π cm³", "90π cm³"],
    0,
  ],
  [
    "Hard",
    "X is equidistant from lines y = 0 and y = 6, and 5 units from O. If x > 0, find X’s coordinates.",
    ["(4, 3)", "(−4, 3)", "(3, 4)", "(4, −3)"],
    0,
  ],
]);
export const mathF3C8QuizzesDLP: QuizQuestion[] = buildForm3MathQuizSets(
  8,
  mathF3C8QuestionBankDLP,
);
