type Bilingual = { bm: string; dlp: string };
type Fact = { term: Bilingual; statement: Bilingual };
type Subtopic = { number: string; title: Bilingual; introduction: Bilingual; facts: Fact[] };

export type ScienceF3ChapterSource = {
  chapter: number;
  title: Bilingual;
  mission: Bilingual;
  whyItMatters: Bilingual;
  objectives: Bilingual[];
  summary: Bilingual;
  subtopics: Subtopic[];
};

const bi = (bm: string, dlp: string): Bilingual => ({ bm, dlp });
const fact = (termBM: string, statementBM: string, termDLP: string, statementDLP: string): Fact => ({
  term: bi(termBM, termDLP),
  statement: bi(statementBM, statementDLP),
});

export const scienceF3Chapters: ScienceF3ChapterSource[] = [
  {
    chapter: 1,
    title: bi("Rangsangan dan Gerak Balas", "Stimuli and Responses"),
    mission: bi("Apabila cahaya terang mengenai mata, bunyi deringan telefon dikesan oleh telinga, atau tangan tersentuh objek panas, badan mengesan rangsangan lalu menghasilkan gerak balas yang sesuai.", "When bright light reaches the eye, a phone ring is detected by the ear, or a hand touches a hot object, the body detects the stimulus and produces a suitable response."),
    whyItMatters: bi("Memahami koordinasi saraf, organ deria, had deria, tropisme dan penyesuaian haiwan membantu kita melindungi diri, menjaga kesihatan pancaindera dan menerangkan kesinambungan hidup.", "Understanding nervous coordination, sense organs, sensory limits, tropisms and animal adaptations helps us protect ourselves, care for our senses and explain survival."),
    objectives: [bi("Menerangkan sistem saraf manusia dan aliran impuls.", "Explain the human nervous system and the flow of nerve impulses."), bi("Menghubungkaitkan organ deria dengan rangsangan, mekanisme dan gerak balas.", "Relate sense organs to stimuli, mechanisms and responses."), bi("Menerangkan gerak balas tumbuhan, had deria dan kepentingan gerak balas haiwan.", "Explain plant responses, sensory limits and the importance of animal responses.")],
    summary: bi("Bab ini menghubungkan sistem saraf, organ deria dan reseptor dengan tindakan terkawal serta luar kawal, mekanisme penglihatan dan pendengaran, had serta kecacatan deria, tropisme dan gerak balas nastik tumbuhan, dan penyesuaian deria haiwan.", "This chapter links the nervous system, sense organs and receptors with voluntary and involuntary actions, vision and hearing mechanisms, sensory limits and defects, plant tropisms and nastic responses, and animal sensory adaptations."),
    subtopics: [
      { number: "1.1", title: bi("Sistem Saraf Manusia", "Human Nervous System"), introduction: bi("Sistem saraf mengesan perubahan dan menyelaras gerak balas badan.", "The nervous system detects changes and coordinates body responses."), facts: [
        fact("Sistem saraf pusat", "Sistem saraf pusat terdiri daripada otak dan saraf tunjang.", "Central nervous system", "The central nervous system consists of the brain and spinal cord."),
        fact("Sistem saraf periferi", "Sistem saraf periferi terdiri daripada saraf kranium dan saraf spina yang menghubungkan sistem saraf pusat dengan bahagian badan.", "Peripheral nervous system", "The peripheral nervous system consists of cranial and spinal nerves that connect the central nervous system to body parts."),
        fact("Neuron", "Neuron ialah unit asas sistem saraf yang membawa impuls saraf.", "Neuron", "A neuron is the basic unit of the nervous system that carries nerve impulses."),
        fact("Rangsangan", "Rangsangan ialah perubahan dalam persekitaran yang dapat dikesan oleh badan.", "Stimulus", "A stimulus is a change in the environment that can be detected by the body."),
        fact("Gerak balas", "Gerak balas ialah tindakan yang dilakukan sebagai tindak balas terhadap rangsangan.", "Response", "A response is an action carried out in response to a stimulus."),
        fact("Afektor", "Afektor atau reseptor mengesan rangsangan.", "Afferent receptor", "An affector or receptor detects stimuli."),
        fact("Efektor", "Efektor ialah otot atau kelenjar yang menghasilkan gerak balas.", "Effector", "An effector is a muscle or gland that produces a response."),
        fact("Impuls saraf", "Impuls saraf dihantar dari afektor ke sistem saraf pusat dan seterusnya ke efektor.", "Nerve impulse", "A nerve impulse is transmitted from the receptor to the central nervous system and then to the effector."),
        fact("Tindakan terkawal", "Tindakan terkawal dilakukan mengikut kehendak dan dikawal oleh otak.", "Voluntary action", "A voluntary action is performed consciously and controlled by the brain."),
        fact("Tindakan luar kawal", "Tindakan luar kawal berlaku secara automatik tanpa kehendak sedar.", "Involuntary action", "An involuntary action occurs automatically without conscious control."),
        fact("Medula oblongata", "Medula oblongata mengawal tindakan luar kawal seperti denyutan jantung dan pernafasan.", "Medulla oblongata", "The medulla oblongata controls involuntary actions such as heartbeat and breathing."),
      ]},
      { number: "1.2", title: bi("Rangsangan dan Gerak Balas dalam Manusia", "Stimuli and Responses in Humans"), introduction: bi("Reseptor dalam organ deria mengesan rangsangan tertentu.", "Receptors in sense organs detect specific stimuli."), facts: [
        fact("Reseptor cahaya", "Fotoreseptor pada retina mengesan cahaya.", "Light receptor", "Photoreceptors in the retina detect light."),
        fact("Mata", "Mata ialah organ deria penglihatan.", "Eye", "The eye is the organ of vision."),
        fact("Kornea", "Kornea membiaskan dan memfokuskan cahaya ke retina.", "Cornea", "The cornea refracts and focuses light onto the retina."),
        fact("Iris", "Iris mengawal saiz pupil dan kuantiti cahaya yang memasuki mata.", "Iris", "The iris controls pupil size and the amount of light entering the eye."),
        fact("Pupil", "Pupil ialah bukaan di tengah iris yang mengawal kuantiti cahaya masuk ke dalam mata.", "Pupil", "The pupil is the opening in the centre of the iris that controls the amount of light entering the eye."),
        fact("Kanta mata", "Kanta mata memfokuskan cahaya ke retina.", "Lens", "The lens focuses light onto the retina."),
        fact("Akomodasi mata", "Ketebalan kanta mata berubah untuk memfokuskan objek dekat atau jauh pada retina.", "Eye accommodation", "The thickness of the eye lens changes to focus near or distant objects on the retina."),
        fact("Retina", "Retina mengandungi fotoreseptor yang menghasilkan impuls saraf.", "Retina", "The retina contains photoreceptors that produce nerve impulses."),
        fact("Saraf optik", "Saraf optik membawa impuls saraf dari retina ke otak.", "Optic nerve", "The optic nerve carries nerve impulses from the retina to the brain."),
        fact("Koklea", "Koklea menukarkan getaran bunyi kepada impuls saraf.", "Cochlea", "The cochlea converts sound vibrations into nerve impulses."),
        fact("Salur separuh bulat", "Salur separuh bulat membantu mengawal keseimbangan badan.", "Semicircular canals", "The semicircular canals help control body balance."),
        fact("Hidung", "Hidung mengesan bau, iaitu bahan kimia dalam udara.", "Nose", "The nose detects smell, which is a chemical substance in the air."),
        fact("Lidah", "Lidah mengesan lima rasa asas: manis, masin, masam, pahit dan umami.", "Tongue", "The tongue detects five basic tastes: sweet, salty, sour, bitter and umami."),
        fact("Kulit", "Kulit mengesan sentuhan, haba, sejuk, sakit dan tekanan.", "Skin", "The skin detects touch, heat, cold, pain and pressure."),
        fact("Kepekaan kulit", "Kepekaan kulit bergantung pada bilangan reseptor dan ketebalan epidermis.", "Skin sensitivity", "Skin sensitivity depends on the number of receptors and the thickness of the epidermis."),
        fact("Mekanisme penglihatan", "Cahaya bergerak melalui kornea, gelemair, kanta mata dan gelemaca sebelum sampai ke retina.", "Vision mechanism", "Light passes through the cornea, aqueous humour, lens and vitreous humour before reaching the retina."),
        fact("Mekanisme pendengaran", "Bunyi bergerak melalui cuping telinga, salur telinga, gegendang telinga, osikel, jendela bujur dan koklea.", "Hearing mechanism", "Sound travels through the pinna, ear canal, eardrum, ossicles, oval window and cochlea."),
      ]},
      { number: "1.3", title: bi("Rangsangan dan Gerak Balas dalam Tumbuhan", "Stimuli and Responses in Plants"), introduction: bi("Tumbuhan bergerak balas terhadap rangsangan melalui tropisme dan gerak balas nastik.", "Plants respond to stimuli through tropisms and nastic responses."), facts: [
        fact("Fototropisme", "Fototropisme ialah gerak balas pertumbuhan terhadap cahaya; pucuk menunjukkan fototropisme positif.", "Phototropism", "Phototropism is a growth response to light; shoots show positive phototropism."),
        fact("Geotropisme", "Geotropisme ialah gerak balas pertumbuhan terhadap graviti; akar menunjukkan geotropisme positif.", "Geotropism", "Geotropism is a growth response to gravity; roots show positive geotropism."),
        fact("Hidrotropisme", "Hidrotropisme ialah gerak balas pertumbuhan akar ke arah air.", "Hydrotropism", "Hydrotropism is the growth response of roots towards water."),
        fact("Tigmotropisme", "Tigmotropisme ialah gerak balas pertumbuhan terhadap sentuhan, seperti sulur paut melilit sokongan.", "Thigmotropism", "Thigmotropism is a growth response to touch, such as tendrils coiling around a support."),
        fact("Gerak balas nastik", "Gerak balas nastik tidak bergantung pada arah rangsangan, seperti daun semalu menguncup apabila disentuh.", "Nastic response", "A nastic response does not depend on stimulus direction, such as Mimosa leaves folding when touched."),
        fact("Tropisme positif", "Bahagian tumbuhan yang tumbuh ke arah rangsangan menunjukkan tropisme positif.", "Positive tropism", "The plant part growing towards the stimulus shows positive tropism."),
        fact("Tropisme negatif", "Bahagian tumbuhan yang tumbuh menjauhi rangsangan menunjukkan tropisme negatif.", "Negative tropism", "The plant part growing away from the stimulus shows negative tropism."),
        fact("Akar", "Akar menunjukkan geotropisme positif dan hidrotropisme positif.", "Root", "Roots show positive geotropism and positive hydrotropism."),
        fact("Pucuk", "Pucuk menunjukkan fototropisme positif dan geotropisme negatif.", "Shoot", "Shoots show positive phototropism and negative geotropism."),
        fact("Sulur paut", "Sulur paut dan batang melilit objek menunjukkan tigmotropisme positif.", "Tendril", "Tendrils and climbing stems wrapping around objects show positive thigmotropism."),
        fact("Pokok semalu", "Pokok semalu menguncupkan daun apabila disentuh sebagai pertahanan.", "Mimosa", "Mimosa folds its leaves when touched as a defence."),
      ]},
      { number: "1.4", title: bi("Kepentingan Gerak Balas dalam Haiwan", "Importance of Responses in Animals"), introduction: bi("Kepekaan deria membantu haiwan mencari makanan, pasangan dan mengelakkan bahaya.", "Sensory sensitivity helps animals find food and mates and avoid danger."), facts: [
        fact("Penglihatan stereoskopik", "Haiwan pemangsa mempunyai medan penglihatan bertindih yang membolehkan jarak dianggar dengan tepat.", "Stereoscopic vision", "Predators have overlapping visual fields that allow accurate distance estimation."),
        fact("Penglihatan monokular", "Haiwan mangsa mempunyai medan penglihatan luas untuk mengesan pemangsa dari pelbagai arah.", "Monocular vision", "Prey animals have a wide field of vision to detect predators from many directions."),
        fact("Pendengaran stereofonik", "Penggunaan kedua-dua belah telinga membantu haiwan menentukan arah bunyi.", "Stereophonic hearing", "Using both ears helps an animal determine the direction of sound."),
        fact("Julat frekuensi", "Haiwan yang berlainan dapat mendengar julat frekuensi bunyi yang berlainan.", "Frequency range", "Different animals can hear different ranges of sound frequencies."),
        fact("Gabungan organ deria", "Sesetengah haiwan meningkatkan kepekaan dengan bilangan reseptor yang banyak atau gabungan beberapa organ deria.", "Combination of sense organs", "Some animals increase sensitivity through many receptors or a combination of several sense organs."),
        fact("Medan penglihatan stereoskopik", "Dua mata di hadapan kepala menghasilkan penglihatan tiga dimensi.", "Stereoscopic visual field", "Two eyes at the front of the head produce three-dimensional vision."),
        fact("Medan penglihatan monokular", "Mata di sisi kepala menghasilkan medan penglihatan yang luas.", "Monocular visual field", "Eyes at the side of the head produce a wide field of view."),
        fact("Pendengaran manusia", "Frekuensi bunyi yang dapat dikesan oleh telinga manusia terhad kepada julat 20 Hz hingga 20 000 Hz.", "Human hearing", "The sound frequency detectable by the human ear is limited to 20 Hz to 20 000 Hz."),
      ]},
    ],
  },
  {
    chapter: 2,
    title: bi("Respirasi", "Respiration"),
    mission: bi("Setiap sedutan membekalkan oksigen untuk respirasi sel, manakala hembusan menyingkirkan karbon dioksida.", "Each inhalation supplies oxygen for cellular respiration, while exhalation removes carbon dioxide."),
    whyItMatters: bi("Bab ini menerangkan bagaimana badan memperoleh oksigen, bagaimana pencemaran merosakkan sistem respirasi dan bagaimana organisma lain bertukar gas.", "This chapter explains how the body obtains oxygen, how pollution harms the respiratory system and how other organisms exchange gases."),
    objectives: [bi("Menerangkan struktur dan mekanisme sistem respirasi manusia.", "Explain the structure and mechanism of the human respiratory system."), bi("Menerangkan pertukaran serta pengangkutan gas.", "Explain gas exchange and transport."), bi("Membandingkan adaptasi respirasi haiwan dan pertukaran gas tumbuhan.", "Compare respiratory adaptations in animals and gas exchange in plants.")],
    summary: bi("Respirasi melibatkan pengudaraan, pertukaran gas pada permukaan yang lembap, nipis dan luas, pengangkutan oksigen serta respirasi sel; kesihatan sistem ini dipengaruhi bahan pencemar.", "Respiration involves ventilation, gas exchange across moist, thin and large surfaces, oxygen transport and cellular respiration; the system's health is affected by pollutants."),
    subtopics: [
      { number: "2.1", title: bi("Sistem Respirasi", "Respiratory System"), introduction: bi("Udara bergerak melalui salur respirasi hingga ke alveolus.", "Air moves through the respiratory tract to the alveoli."), facts: [
        fact("Laluan udara", "Udara melalui lubang hidung, rongga hidung, farinks, larinks, trakea, bronkus dan bronkiol sebelum sampai ke alveolus.", "Air pathway", "Air passes through the nostrils, nasal cavity, pharynx, larynx, trachea, bronchi and bronchioles before reaching the alveoli."),
        fact("Epiglotis", "Epiglotis menutup trakea semasa menelan supaya makanan tidak memasuki salur pernafasan.", "Epiglottis", "The epiglottis closes the trachea during swallowing so food does not enter the respiratory tract."),
        fact("Tarik nafas", "Semasa menarik nafas, otot interkostal mengecut, sangkar rusuk bergerak ke atas dan ke luar, dan diafragma mengecut serta mendatar.", "Inhalation", "During inhalation, intercostal muscles contract, the rib cage moves upwards and outwards, and the diaphragm contracts and flattens."),
        fact("Hembus nafas", "Semasa menghembus nafas, otot interkostal mengendur, sangkar rusuk bergerak ke bawah dan ke dalam, dan diafragma melengkung ke atas.", "Exhalation", "During exhalation, intercostal muscles relax, the rib cage moves downwards and inwards, and the diaphragm curves upwards."),
      ]},
      { number: "2.2", title: bi("Pergerakan dan Pertukaran Gas", "Movement and Exchange of Gases"), introduction: bi("Gas meresap mengikut perbezaan kepekatan antara alveolus, darah dan sel.", "Gases diffuse down concentration differences between alveoli, blood and cells."), facts: [
        fact("Alveolus", "Alveolus mempunyai dinding nipis, permukaan lembap, luas permukaan besar dan jaringan kapilari yang banyak.", "Alveolus", "An alveolus has a thin wall, moist surface, large surface area and a rich capillary network."),
        fact("Resapan oksigen", "Oksigen meresap dari alveolus ke dalam kapilari darah.", "Oxygen diffusion", "Oxygen diffuses from the alveolus into the blood capillary."),
        fact("Oksihemoglobin", "Oksigen bergabung dengan hemoglobin dalam sel darah merah untuk membentuk oksihemoglobin.", "Oxyhaemoglobin", "Oxygen combines with haemoglobin in red blood cells to form oxyhaemoglobin."),
        fact("Respirasi sel", "Respirasi sel menggunakan oksigen dan glukosa untuk menghasilkan tenaga, karbon dioksida dan air.", "Cellular respiration", "Cellular respiration uses oxygen and glucose to produce energy, carbon dioxide and water."),
      ]},
      { number: "2.3", title: bi("Kesihatan Sistem Respirasi", "Health of the Respiratory System"), introduction: bi("Bahan pencemar udara boleh merosakkan salur respirasi dan peparu.", "Air pollutants can damage the respiratory tract and lungs."), facts: [
        fact("Tar rokok", "Tar dalam asap rokok merosakkan sel salur respirasi dan boleh menyebabkan kanser peparu.", "Cigarette tar", "Tar in cigarette smoke damages respiratory tract cells and can cause lung cancer."),
        fact("Karbon monoksida", "Karbon monoksida bersaing dengan oksigen untuk bergabung dengan hemoglobin.", "Carbon monoxide", "Carbon monoxide competes with oxygen to combine with haemoglobin."),
        fact("Penyakit respirasi", "Asma, bronkitis, emfisema dan kanser peparu ialah penyakit sistem respirasi.", "Respiratory diseases", "Asthma, bronchitis, emphysema and lung cancer are diseases of the respiratory system."),
        fact("Bahan pencemar", "Debu, jerebu, sulfur dioksida, nitrogen dioksida, debunga dan asap rokok memudaratkan sistem respirasi.", "Pollutants", "Dust, haze, sulphur dioxide, nitrogen dioxide, pollen and cigarette smoke harm the respiratory system."),
      ]},
      { number: "2.4", title: bi("Adaptasi Sistem Respirasi", "Adaptations in Respiratory Systems"), introduction: bi("Permukaan respirasi berbeza mengikut habitat tetapi cekap untuk pertukaran gas.", "Respiratory surfaces differ by habitat but are efficient for gas exchange."), facts: [
        fact("Trakea serangga", "Sistem trakea serangga membawa udara terus ke tisu melalui trakeol.", "Insect tracheal system", "The insect tracheal system carries air directly to tissues through tracheoles."),
        fact("Insang ikan", "Filamen dan lamela insang menyediakan luas permukaan besar untuk pertukaran gas dalam air.", "Fish gills", "Gill filaments and lamellae provide a large surface area for gas exchange in water."),
        fact("Kulit amfibia", "Kulit luar amfibia yang nipis dan lembap membolehkan pertukaran gas berlaku.", "Amphibian skin", "The thin, moist outer skin of amphibians allows gas exchange."),
        fact("Ciri permukaan respirasi", "Permukaan respirasi yang cekap adalah nipis, lembap, luas dan mempunyai bekalan darah yang baik.", "Respiratory surface features", "An efficient respiratory surface is thin, moist, large and has a good blood supply."),
      ]},
      { number: "2.5", title: bi("Pertukaran Gas dalam Tumbuhan", "Gas Exchange in Plants"), introduction: bi("Stoma mengawal pertukaran gas antara daun dengan atmosfera.", "Stomata control gas exchange between leaves and the atmosphere."), facts: [
        fact("Stoma", "Stoma ialah liang pada epidermis daun yang membenarkan pertukaran gas.", "Stoma", "A stoma is a pore in the leaf epidermis that allows gas exchange."),
        fact("Sel pengawal", "Sel pengawal mengawal pembukaan dan penutupan stoma.", "Guard cells", "Guard cells control the opening and closing of stomata."),
        fact("Stoma waktu siang", "Stoma lazimnya terbuka pada waktu siang untuk membolehkan karbon dioksida masuk bagi fotosintesis.", "Stomata during daytime", "Stomata are usually open during the day to allow carbon dioxide to enter for photosynthesis."),
        fact("Persekitaran tidak tercemar", "Persekitaran tidak tercemar membantu menjamin pertumbuhan dan kemandirian tumbuhan.", "Unpolluted environment", "An unpolluted environment helps ensure plant growth and survival."),
      ]},
    ],
  },
  {
    chapter: 3,
    title: bi("Pengangkutan", "Transportation"),
    mission: bi("Sel memerlukan oksigen dan nutrien serta perlu menyingkirkan bahan kumuh; sistem pengangkutan melakukan tugas ini secara berterusan.", "Cells need oxygen and nutrients and must remove waste; transport systems perform this task continuously."),
    whyItMatters: bi("Memahami darah, jantung, salur darah dan tisu vaskular menerangkan cara manusia, haiwan dan tumbuhan terus hidup.", "Understanding blood, the heart, blood vessels and vascular tissues explains how humans, animals and plants stay alive."),
    objectives: [bi("Menerangkan sistem pengangkutan organisma.", "Explain transport systems in organisms."), bi("Menerangkan peredaran darah dan komponen darah manusia.", "Explain blood circulation and components of human blood."), bi("Membandingkan pengangkutan haiwan dengan tumbuhan.", "Compare transport in animals and plants.")],
    summary: bi("Haiwan mempunyai sistem peredaran yang melibatkan jantung, darah dan salur darah, manakala tumbuhan menggunakan xilem dan floem untuk mengangkut air, garam mineral dan sukrosa.", "Animals have circulatory systems involving the heart, blood and blood vessels, while plants use xylem and phloem to transport water, mineral salts and sucrose."),
    subtopics: [
      { number: "3.1", title: bi("Sistem Pengangkutan dalam Organisma", "Transport Systems in Organisms"), introduction: bi("Organisma kompleks memerlukan sistem khas untuk mengangkut bahan.", "Complex organisms require specialised systems to transport substances."), facts: [
        fact("Keperluan pengangkutan", "Sistem pengangkutan membawa oksigen dan nutrien ke sel serta menyingkirkan karbon dioksida dan bahan kumuh.", "Need for transport", "Transport systems carry oxygen and nutrients to cells and remove carbon dioxide and waste."),
        fact("Organisma ringkas", "Organisma unisel bertukar bahan secara resapan melalui permukaan badan.", "Simple organisms", "Unicellular organisms exchange substances by diffusion across the body surface."),
        fact("Organisma kompleks", "Organisma multisel yang besar memerlukan sistem pengangkutan kerana nisbah luas permukaan kepada isi padu lebih kecil.", "Complex organisms", "Large multicellular organisms need transport systems because their surface-area-to-volume ratio is smaller."),
        fact("Bahan terlarut", "Air, nutrien dan bahan terlarut diangkut untuk memenuhi keperluan sel organisma.", "Dissolved substances", "Water, nutrients and dissolved substances are transported to meet the needs of organism cells."),
      ]},
      { number: "3.2", title: bi("Sistem Peredaran Darah", "Blood Circulatory System"), introduction: bi("Jantung mengepam darah melalui arteri, kapilari dan vena.", "The heart pumps blood through arteries, capillaries and veins."), facts: [
        fact("Jantung", "Jantung manusia mempunyai empat ruang: dua atrium dan dua ventrikel.", "Heart", "The human heart has four chambers: two atria and two ventricles."),
        fact("Arteri", "Arteri membawa darah keluar dari jantung pada tekanan tinggi dan mempunyai dinding tebal serta berotot.", "Artery", "An artery carries blood away from the heart at high pressure and has a thick, muscular wall."),
        fact("Vena", "Vena membawa darah kembali ke jantung dan mempunyai injap untuk mencegah aliran balik.", "Vein", "A vein carries blood back to the heart and has valves to prevent backflow."),
        fact("Kapilari", "Kapilari berdinding setebal satu sel untuk memudahkan pertukaran bahan dengan sel badan.", "Capillary", "A capillary has a wall one cell thick to facilitate exchange with body cells."),
      ]},
      { number: "3.3", title: bi("Darah Manusia", "Human Blood"), introduction: bi("Darah terdiri daripada plasma, sel darah merah, sel darah putih dan platlet.", "Blood consists of plasma, red blood cells, white blood cells and platelets."), facts: [
        fact("Plasma", "Plasma mengangkut bahan terlarut seperti nutrien, hormon, karbon dioksida dan bahan kumuh.", "Plasma", "Plasma transports dissolved substances such as nutrients, hormones, carbon dioxide and waste."),
        fact("Sel darah merah", "Sel darah merah mengandungi hemoglobin untuk mengangkut oksigen.", "Red blood cell", "Red blood cells contain haemoglobin to transport oxygen."),
        fact("Sel darah putih", "Sel darah putih melindungi badan daripada patogen.", "White blood cell", "White blood cells protect the body from pathogens."),
        fact("Platlet", "Platlet membantu pembekuan darah pada luka.", "Platelet", "Platelets help blood clot at a wound."),
      ]},
      { number: "3.4", title: bi("Pengangkutan dalam Tumbuhan", "Transport in Plants"), introduction: bi("Tisu xilem dan floem membentuk sistem pengangkutan tumbuhan.", "Xylem and phloem tissues form the plant transport system."), facts: [
        fact("Xilem", "Xilem mengangkut air dan garam mineral terlarut dari akar ke bahagian lain tumbuhan.", "Xylem", "Xylem transports water and dissolved mineral salts from roots to other parts of the plant."),
        fact("Floem", "Floem mengangkut sukrosa dari daun ke seluruh bahagian tumbuhan.", "Phloem", "Phloem transports sucrose from leaves to all parts of the plant."),
        fact("Transpirasi", "Transpirasi ialah kehilangan air dalam bentuk wap dari permukaan tumbuhan, terutamanya melalui stoma.", "Transpiration", "Transpiration is the loss of water as vapour from plant surfaces, mainly through stomata."),
        fact("Faktor transpirasi", "Keamatan cahaya, suhu, kelembapan udara dan pergerakan udara mempengaruhi kadar transpirasi.", "Transpiration factors", "Light intensity, temperature, air humidity and air movement affect the rate of transpiration."),
      ]},
      { number: "3.5", title: bi("Perbandingan Sistem Pengangkutan", "Comparison of Transport Systems"), introduction: bi("Kedua-dua sistem mengangkut bahan tetapi mempunyai struktur berbeza.", "Both systems transport substances but have different structures."), facts: [
        fact("Persamaan sistem", "Sistem haiwan dan tumbuhan ialah sistem pengangkutan dalam organisma kompleks yang membawa air, nutrien dan bahan terlarut.", "System similarity", "Animal and plant systems are transport systems in complex organisms that carry water, nutrients and dissolved substances."),
        fact("Salur haiwan", "Arteri, kapilari dan vena bersambung membentuk salur berterusan.", "Animal vessels", "Arteries, capillaries and veins connect to form continuous vessels."),
        fact("Salur tumbuhan", "Xilem dan floem ialah dua salur berasingan yang tidak bersambung.", "Plant vessels", "Xylem and phloem are two separate vessels that are not connected."),
        fact("Pam dan injap", "Sistem haiwan bertiub dengan jantung dan injap, manakala sistem tumbuhan tidak mempunyai pam atau injap.", "Pump and valves", "The animal system is tubular with a heart and valves, whereas the plant system has no pump or valves."),
      ]},
    ],
  },
  {
    chapter: 4,
    title: bi("Kereaktifan Logam", "Reactivity of Metals"),
    mission: bi("Logam dalam telefon, bangunan dan kenderaan berasal daripada mineral yang perlu dipisahkan dan diproses.", "Metals in phones, buildings and vehicles come from minerals that must be separated and processed."),
    whyItMatters: bi("Siri kereaktifan membantu meramal tindak balas logam dan memilih kaedah pengekstrakan yang sesuai sambil menilai kesan perlombongan.", "The reactivity series helps predict metal reactions and select suitable extraction methods while evaluating mining impacts."),
    objectives: [bi("Menerangkan kepelbagaian mineral.", "Explain the diversity of minerals."), bi("Membina dan menggunakan siri kereaktifan logam.", "Construct and use the reactivity series of metals."), bi("Menerangkan pengekstrakan logam dan kesannya.", "Explain metal extraction and its impacts.")],
    summary: bi("Mineral terdiri daripada unsur atau sebatian; kereaktifan logam terhadap oksigen membentuk siri kereaktifan yang menentukan sama ada karbon boleh menurunkan oksida logam semasa pengekstrakan.", "Minerals consist of elements or compounds; metal reactivity towards oxygen forms a reactivity series that determines whether carbon can reduce a metal oxide during extraction."),
    subtopics: [
      { number: "4.1", title: bi("Kepelbagaian Mineral", "Diversity of Minerals"), introduction: bi("Kerak Bumi mengandungi mineral unsur dan mineral sebatian.", "Earth's crust contains elemental and compound minerals."), facts: [
        fact("Mineral", "Mineral ialah unsur atau sebatian pepejal yang wujud secara semula jadi dengan struktur hablur tertentu.", "Mineral", "A mineral is a naturally occurring solid element or compound with a definite crystal structure."),
        fact("Mineral unsur", "Emas, perak dan grafit ialah contoh mineral unsur.", "Elemental mineral", "Gold, silver and graphite are examples of elemental minerals."),
        fact("Mineral sebatian", "Bauksit, hematit, galena dan kasiterit ialah bijih yang mengandungi sebatian logam.", "Compound mineral", "Bauxite, haematite, galena and cassiterite are ores containing metal compounds."),
        fact("Kegunaan mineral", "Mineral digunakan untuk meneutralkan tanah berasid, membuat kaca, membina tapak bangunan dan menghasilkan barang harian.", "Uses of minerals", "Minerals are used to neutralise acidic soil, make glass, build foundations and produce everyday items."),
        fact("Batu kapur", "Batu kapur mengandungi kalsium karbonat dan mempunyai pelbagai kegunaan dalam pembinaan serta industri.", "Limestone", "Limestone contains calcium carbonate and has various uses in construction and industry."),
        fact("Bauksit", "Bauksit ialah bijih aluminium.", "Bauxite", "Bauxite is an ore of aluminium."),
      ]},
      { number: "4.2", title: bi("Siri Kereaktifan Logam", "Reactivity Series of Metals"), introduction: bi("Kecergasan tindak balas logam dengan oksigen digunakan untuk menyusun logam.", "The vigour of metal reactions with oxygen is used to arrange metals."), facts: [
        fact("Siri kereaktifan", "Logam disusun daripada paling reaktif kepada paling kurang reaktif berdasarkan tindak balasnya.", "Reactivity series", "Metals are arranged from most reactive to least reactive based on their reactions."),
        fact("Tindak balas oksigen", "Logam yang lebih reaktif bertindak balas dengan oksigen secara lebih cergas.", "Reaction with oxygen", "A more reactive metal reacts more vigorously with oxygen."),
        fact("Karbon dalam siri", "Kedudukan karbon digunakan untuk menentukan logam yang boleh diekstrak daripada oksidanya melalui penurunan oleh karbon.", "Carbon in the series", "The position of carbon determines which metals can be extracted from their oxides by carbon reduction."),
        fact("Oksida logam", "Tindak balas logam dengan oksigen menghasilkan oksida logam.", "Metal oxide", "The reaction of a metal with oxygen produces a metal oxide."),
        fact("Magnesium", "Magnesium terbakar dengan cahaya putih terang apabila dipanaskan dalam oksigen.", "Magnesium", "Magnesium burns with a bright white light when heated in oxygen."),
        fact("Kereaktifan rendah", "Logam yang kurang reaktif menunjukkan tindak balas yang kurang cergas terhadap oksigen.", "Low reactivity", "Less reactive metals show less vigorous reactions with oxygen."),
        fact("Ramalan tindak balas", "Kedudukan dalam siri kereaktifan membolehkan perbandingan dan ramalan kecergasan tindak balas logam.", "Predicting reactions", "Position in the reactivity series allows comparison and prediction of reaction vigour."),
      ]},
      { number: "4.3", title: bi("Pengekstrakan Logam daripada Bijih", "Extraction of Metals from Ores"), introduction: bi("Kaedah pengekstrakan bergantung pada kedudukan logam relatif kepada karbon.", "The extraction method depends on the metal's position relative to carbon."), facts: [
        fact("Penurunan oleh karbon", "Oksida logam yang kurang reaktif daripada karbon boleh diturunkan oleh karbon.", "Reduction by carbon", "Metal oxides less reactive than carbon can be reduced by carbon."),
        fact("Relau bagas", "Besi diekstrak daripada hematit dalam relau bagas menggunakan karbon sebagai agen penurunan.", "Blast furnace", "Iron is extracted from haematite in a blast furnace using carbon as a reducing agent."),
        fact("Bijih besi", "Hematit ialah bijih ferum yang digunakan dalam pengekstrakan besi.", "Iron ore", "Haematite is an iron ore used in iron extraction."),
        fact("Logam sangat reaktif", "Logam yang lebih reaktif daripada karbon tidak boleh diekstrak daripada oksidanya menggunakan karbon.", "Highly reactive metals", "Metals more reactive than carbon cannot be extracted from their oxides using carbon."),
        fact("Perlombongan", "Perlombongan yang tidak dirancang dengan baik memberi kesan buruk kepada hidupan dan alam sekitar.", "Mining", "Poorly planned mining has harmful effects on living things and the environment."),
        fact("Pemulihan kawasan", "Idea kreatif dan inovatif diperlukan untuk mengurangkan kesan perlombongan serta memulihkan kawasan.", "Site rehabilitation", "Creative and innovative ideas are needed to reduce mining impacts and rehabilitate sites."),
        fact("Agen penurunan", "Agen penurunan menyingkirkan oksigen daripada oksida logam.", "Reducing agent", "A reducing agent removes oxygen from a metal oxide."),
      ]},
    ],
  },
  {
    chapter: 5,
    title: bi("Termokimia", "Thermochemistry"),
    mission: bi("Pek panas, pek sejuk, pembakaran dan fotosintesis semuanya melibatkan perubahan haba.", "Hot packs, cold packs, combustion and photosynthesis all involve heat changes."),
    whyItMatters: bi("Mengenal pasti tindak balas eksotermik dan endotermik membantu memilih proses yang sesuai dalam kehidupan harian.", "Identifying exothermic and endothermic reactions helps us choose suitable processes in daily life."),
    objectives: [bi("Mendefinisikan termokimia.", "Define thermochemistry."), bi("Membezakan tindak balas eksotermik dan endotermik.", "Differentiate exothermic and endothermic reactions."), bi("Mengaplikasikan perubahan haba dalam penyelesaian masalah.", "Apply heat changes in problem solving.")],
    summary: bi("Termokimia mengkaji perubahan haba semasa tindak balas kimia; tindak balas eksotermik membebaskan haba dan menaikkan suhu persekitaran, manakala tindak balas endotermik menyerap haba dan menurunkannya.", "Thermochemistry studies heat changes during chemical reactions; exothermic reactions release heat and raise the surroundings' temperature, while endothermic reactions absorb heat and lower it."),
    subtopics: [
      { number: "5.1", title: bi("Tindak Balas Endotermik dan Eksotermik", "Endothermic and Exothermic Reactions"), introduction: bi("Perubahan suhu menunjukkan arah pemindahan haba antara sistem tindak balas dengan persekitaran.", "Temperature change indicates the direction of heat transfer between a reaction system and its surroundings."), facts: [
        fact("Termokimia", "Termokimia ialah kajian tentang perubahan haba semasa tindak balas kimia.", "Thermochemistry", "Thermochemistry is the study of heat changes during chemical reactions."),
        fact("Tindak balas eksotermik", "Tindak balas eksotermik membebaskan haba ke persekitaran.", "Exothermic reaction", "An exothermic reaction releases heat to the surroundings."),
        fact("Suhu eksotermik", "Suhu persekitaran meningkat semasa tindak balas eksotermik.", "Exothermic temperature", "The temperature of the surroundings increases during an exothermic reaction."),
        fact("Pembakaran", "Pembakaran kertas ialah contoh tindak balas eksotermik.", "Combustion", "Burning paper is an example of an exothermic reaction."),
        fact("Respirasi", "Respirasi ialah proses eksotermik yang membebaskan tenaga.", "Respiration", "Respiration is an exothermic process that releases energy."),
        fact("Peneutralan", "Peneutralan asid dengan alkali ialah tindak balas eksotermik.", "Neutralisation", "Neutralisation of an acid with an alkali is an exothermic reaction."),
        fact("Letupan", "Letupan bom ialah contoh proses eksotermik yang membebaskan banyak haba.", "Explosion", "A bomb explosion is an example of an exothermic process that releases much heat."),
        fact("Tindak balas endotermik", "Tindak balas endotermik menyerap haba daripada persekitaran.", "Endothermic reaction", "An endothermic reaction absorbs heat from the surroundings."),
        fact("Suhu endotermik", "Suhu persekitaran menurun semasa tindak balas endotermik.", "Endothermic temperature", "The temperature of the surroundings decreases during an endothermic reaction."),
        fact("Fotosintesis", "Fotosintesis ialah proses endotermik yang menyerap tenaga cahaya.", "Photosynthesis", "Photosynthesis is an endothermic process that absorbs light energy."),
        fact("Membuat kek", "Proses membuat kek memerlukan penyerapan haba dan bersifat endotermik.", "Baking a cake", "Baking a cake requires heat absorption and is endothermic."),
        fact("Pengekstrakan besi", "Pengekstrakan besi daripada bijih besi disenaraikan sebagai proses endotermik.", "Iron extraction", "Extraction of iron from iron ore is listed as an endothermic process."),
        fact("Garam ammonium", "Melarutkan garam ammonium dalam air menyerap haba dan menurunkan suhu.", "Ammonium salt", "Dissolving an ammonium salt in water absorbs heat and lowers the temperature."),
        fact("Pek panas", "Bahan yang menjalani proses eksotermik sesuai digunakan dalam pek panas.", "Hot pack", "A substance undergoing an exothermic process is suitable for a hot pack."),
        fact("Pek sejuk", "Bahan yang menjalani proses endotermik sesuai digunakan dalam pek sejuk.", "Cold pack", "A substance undergoing an endothermic process is suitable for a cold pack."),
        fact("Kekejangan otot", "Bahan eksotermik sesuai untuk menghasilkan haba bagi melegakan kekejangan otot.", "Muscle cramp", "An exothermic substance is suitable for producing heat to relieve muscle cramps."),
        fact("Arah haba eksotermik", "Dalam tindak balas eksotermik, haba mengalir dari sistem ke persekitaran.", "Exothermic heat direction", "In an exothermic reaction, heat flows from the system to the surroundings."),
        fact("Arah haba endotermik", "Dalam tindak balas endotermik, haba mengalir dari persekitaran ke sistem.", "Endothermic heat direction", "In an endothermic reaction, heat flows from the surroundings to the system."),
        fact("Aktiviti cergas", "Suhu badan meningkat semasa aktiviti fizikal cergas kerana kadar respirasi meningkat dan lebih banyak haba dibebaskan.", "Vigorous activity", "Body temperature rises during vigorous activity because respiration rate increases and more heat is released."),
        fact("Perubahan haba", "Kenaikan atau penurunan suhu digunakan sebagai bukti perubahan haba dalam tindak balas.", "Heat change", "A rise or fall in temperature is used as evidence of heat change in a reaction."),
      ]},
    ],
  },
  {
    chapter: 6,
    title: bi("Elektrik dan Kemagnetan", "Electricity and Magnetism"),
    mission: bi("Tenaga elektrik dijana jauh dari rumah, dinaikkan voltannya untuk dihantar dan diturunkan semula sebelum digunakan dengan selamat.", "Electrical energy is generated far from homes, stepped up for transmission and stepped down again before safe use."),
    whyItMatters: bi("Bab ini membantu kita memahami penjanaan, transformer, grid, keselamatan pendawaian dan kos penggunaan elektrik.", "This chapter helps us understand generation, transformers, the grid, wiring safety and electricity cost."),
    objectives: [bi("Menerangkan penjanaan tenaga elektrik.", "Explain electrical energy generation."), bi("Menerangkan transformer dan sistem penghantaran.", "Explain transformers and the transmission system."), bi("Mengira penggunaan serta kos elektrik.", "Calculate electricity consumption and cost.")],
    summary: bi("Arus aruhan dijana apabila gegelung memotong garis medan magnet; transformer mengubah voltan arus ulang-alik, grid menghantar tenaga dan penggunaan elektrik ditentukan oleh kuasa serta masa.", "Induced current is generated when a coil cuts magnetic field lines; transformers change alternating-current voltage, the grid transmits energy and electricity use is determined by power and time."),
    subtopics: [
      { number: "6.1", title: bi("Penjanaan Tenaga Elektrik", "Generation of Electrical Energy"), introduction: bi("Penjana menukarkan tenaga mekanik kepada tenaga elektrik melalui aruhan elektromagnet.", "A generator converts mechanical energy to electrical energy through electromagnetic induction."), facts: [
        fact("Arus aruhan", "Arus aruhan terhasil apabila gegelung dawai memotong garis medan magnet.", "Induced current", "An induced current is produced when a wire coil cuts magnetic field lines."),
        fact("Penjana", "Penjana tenaga elektrik menukarkan tenaga mekanik kepada tenaga elektrik.", "Generator", "An electrical generator converts mechanical energy into electrical energy."),
        fact("Arus ulang-alik", "Penjana di stesen jana kuasa menghasilkan arus ulang-alik yang arah dan magnitudnya berubah.", "Alternating current", "Generators at power stations produce alternating current whose direction and magnitude change."),
        fact("Arus terus", "Sel kering dan sel suria menghasilkan arus terus yang mengalir dalam satu arah.", "Direct current", "Dry cells and solar cells produce direct current that flows in one direction."),
        fact("Sumber boleh baharu", "Hidro, ombak, solar, pasang surut, angin, biojisim dan geoterma ialah sumber tenaga boleh baharu.", "Renewable sources", "Hydroelectric, wave, solar, tidal, wind, biomass and geothermal energy are renewable sources."),
        fact("Sumber tidak boleh baharu", "Tenaga nuklear, arang batu, gas asli dan petroleum ialah sumber tenaga tidak boleh baharu.", "Non-renewable sources", "Nuclear energy, coal, natural gas and petroleum are non-renewable energy sources."),
      ]},
      { number: "6.2", title: bi("Transformer", "Transformer"), introduction: bi("Transformer berfungsi dengan arus ulang-alik untuk menaikkan atau menurunkan voltan.", "A transformer works with alternating current to step voltage up or down."), facts: [
        fact("Transformer injak naik", "Transformer injak naik mempunyai lebih banyak lilitan pada gegelung sekunder dan menaikkan voltan.", "Step-up transformer", "A step-up transformer has more turns in the secondary coil and increases voltage."),
        fact("Transformer injak turun", "Transformer injak turun mempunyai lebih sedikit lilitan pada gegelung sekunder dan menurunkan voltan.", "Step-down transformer", "A step-down transformer has fewer turns in the secondary coil and decreases voltage."),
        fact("Nisbah transformer", "Bagi transformer unggul, Vp/Vs = Np/Ns.", "Transformer ratio", "For an ideal transformer, Vp/Vs = Np/Ns."),
        fact("Arus ulang-alik transformer", "Transformer tidak berfungsi dengan bekalan arus terus yang tetap kerana medan magnet tidak berubah.", "Transformer alternating current", "A transformer does not operate with a steady direct-current supply because the magnetic field does not change."),
      ]},
      { number: "6.3", title: bi("Penghantaran dan Pengagihan", "Transmission and Distribution"), introduction: bi("Voltan tinggi mengurangkan kehilangan tenaga semasa penghantaran jarak jauh.", "High voltage reduces energy loss during long-distance transmission."), facts: [
        fact("Rangkaian Grid Nasional", "Rangkaian Grid Nasional menghantar tenaga elektrik pada voltan tinggi ke seluruh negara.", "National Grid Network", "The National Grid Network transmits electrical energy at high voltage throughout the country."),
        fact("Urutan penghantaran", "Tenaga bergerak dari stesen jana kuasa ke transformer injak naik, grid, transformer injak turun dan pencawang sebelum pengguna.", "Transmission sequence", "Energy moves from a power station to a step-up transformer, grid, step-down transformer and substations before users."),
        fact("Wayar hidup", "Wayar hidup membawa arus ke peralatan elektrik.", "Live wire", "The live wire carries current to an electrical appliance."),
        fact("Wayar neutral", "Wayar neutral mengembalikan arus ke bekalan.", "Neutral wire", "The neutral wire returns current to the supply."),
        fact("Wayar bumi", "Wayar bumi mengalirkan arus bocor ke Bumi untuk mengurangkan risiko renjatan elektrik.", "Earth wire", "The earth wire carries leakage current to Earth to reduce electric shock risk."),
        fact("Fius", "Fius melebur dan memutuskan litar apabila arus melebihi nilai selamat.", "Fuse", "A fuse melts and breaks the circuit when current exceeds a safe value."),
        fact("Litar pintas", "Litar pintas berlaku apabila wayar hidup bersentuhan terus dengan wayar neutral dan menghasilkan arus besar.", "Short circuit", "A short circuit occurs when live and neutral wires make direct contact, producing a large current."),
      ]},
      { number: "6.4", title: bi("Kos Penggunaan Elektrik", "Cost of Electricity Consumption"), introduction: bi("Tenaga digunakan bergantung pada kuasa peralatan dan tempoh penggunaan.", "Energy consumed depends on appliance power and duration of use."), facts: [
        fact("Tenaga elektrik", "Tenaga elektrik dalam kilowatt-jam dikira dengan kuasa dalam kilowatt didarab masa dalam jam.", "Electrical energy", "Electrical energy in kilowatt-hours equals power in kilowatts multiplied by time in hours."),
        fact("Kilowatt-jam", "Satu kilowatt-jam ialah tenaga yang digunakan oleh peralatan 1 kW selama satu jam.", "Kilowatt-hour", "One kilowatt-hour is the energy used by a 1 kW appliance for one hour."),
        fact("Kos elektrik", "Kos penggunaan elektrik dikira daripada bilangan unit kWh dan kadar tarif.", "Electricity cost", "Electricity cost is calculated from the number of kWh units and tariff rate."),
      ]},
    ],
  },
  {
    chapter: 7,
    title: bi("Tenaga dan Kuasa", "Energy and Power"),
    mission: bi("Mengangkat beg, memecut basikal dan meregangkan spring melibatkan kerja serta perubahan tenaga.", "Lifting a bag, accelerating a bicycle and stretching a spring involve work and energy changes."),
    whyItMatters: bi("Rumus kerja, kuasa dan tenaga membolehkan kita menerangkan serta mengira prestasi sistem harian.", "The equations for work, power and energy allow us to explain and calculate the performance of everyday systems."),
    objectives: [bi("Mengira kerja dan kuasa.", "Calculate work and power."), bi("Mengira tenaga keupayaan dan kinetik.", "Calculate potential and kinetic energy."), bi("Mengaplikasikan Prinsip Keabadian Tenaga.", "Apply the Principle of Conservation of Energy.")],
    summary: bi("Kerja memindahkan tenaga apabila daya menghasilkan sesaran; kuasa ialah kadar melakukan kerja, dan tenaga keupayaan serta kinetik saling berubah tanpa memusnahkan jumlah tenaga sistem tertutup.", "Work transfers energy when a force causes displacement; power is the rate of doing work, and potential and kinetic energy transform without destroying the total energy of a closed system."),
    subtopics: [
      { number: "7.1", title: bi("Kerja, Tenaga dan Kuasa", "Work, Energy and Power"), introduction: bi("Kerja dilakukan apabila daya menggerakkan objek dalam arah daya.", "Work is done when a force moves an object in the direction of the force."), facts: [
        fact("Kerja", "Kerja ialah hasil darab daya dengan sesaran dalam arah daya: W = Fs.", "Work", "Work is the product of force and displacement in the force direction: W = Fs."),
        fact("Joule", "Satu joule ialah kerja yang dilakukan apabila daya 1 N menggerakkan objek sejauh 1 m dalam arah daya.", "Joule", "One joule is the work done when a force of 1 N moves an object 1 m in the force direction."),
        fact("Tiada kerja", "Tiada kerja dilakukan jika tiada sesaran dalam arah daya.", "No work", "No work is done if there is no displacement in the direction of the force."),
        fact("Tenaga", "Tenaga ialah keupayaan untuk melakukan kerja dan unit S.I.-nya ialah joule.", "Energy", "Energy is the ability to do work and its SI unit is the joule."),
        fact("Kuasa", "Kuasa ialah kadar melakukan kerja: P = W/t.", "Power", "Power is the rate of doing work: P = W/t."),
        fact("Watt", "Satu watt ialah kuasa apabila kerja 1 J dilakukan dalam masa 1 s.", "Watt", "One watt is the power when 1 J of work is done in 1 s."),
        fact("Kuasa tinggi", "Bagi kerja yang sama, masa yang lebih singkat menghasilkan kuasa yang lebih tinggi.", "High power", "For the same work, a shorter time produces greater power."),
      ]},
      { number: "7.2", title: bi("Tenaga Keupayaan dan Kinetik", "Potential and Kinetic Energy"), introduction: bi("Kedudukan, regangan dan gerakan menyimpan bentuk tenaga yang berbeza.", "Position, deformation and motion store different forms of energy."), facts: [
        fact("Tenaga keupayaan graviti", "Tenaga keupayaan graviti ialah E = mgh.", "Gravitational potential energy", "Gravitational potential energy is E = mgh."),
        fact("Jisim dan ketinggian", "Tenaga keupayaan graviti meningkat apabila jisim atau ketinggian meningkat.", "Mass and height", "Gravitational potential energy increases when mass or height increases."),
        fact("Tenaga keupayaan kenyal", "Tenaga keupayaan kenyal bagi spring ialah E = 1/2 Fx.", "Elastic potential energy", "The elastic potential energy of a spring is E = 1/2 Fx."),
        fact("Daya spring", "Daya yang lebih besar atau pemanjangan yang lebih besar meningkatkan tenaga keupayaan kenyal.", "Spring force", "A greater force or extension increases elastic potential energy."),
        fact("Tenaga kinetik", "Tenaga kinetik objek bergerak ialah E = 1/2 mv².", "Kinetic energy", "The kinetic energy of a moving object is E = 1/2 mv²."),
        fact("Kesan laju", "Tenaga kinetik berkadar dengan kuasa dua laju.", "Effect of speed", "Kinetic energy is proportional to the square of speed."),
        fact("Objek pegun", "Objek pegun mempunyai tenaga kinetik sifar.", "Stationary object", "A stationary object has zero kinetic energy."),
      ]},
      { number: "7.3", title: bi("Prinsip Keabadian Tenaga", "Principle of Conservation of Energy"), introduction: bi("Tenaga berubah bentuk tetapi jumlahnya kekal dalam sistem tertutup.", "Energy changes form but its total remains constant in a closed system."), facts: [
        fact("Keabadian tenaga", "Tenaga tidak boleh dicipta atau dimusnahkan tetapi boleh berubah daripada satu bentuk kepada bentuk lain.", "Conservation of energy", "Energy cannot be created or destroyed but can change from one form to another."),
        fact("Sistem tertutup", "Jumlah tenaga dalam sistem tertutup adalah tetap.", "Closed system", "The total energy in a closed system remains constant."),
        fact("Objek jatuh", "Apabila objek jatuh, tenaga keupayaan graviti berkurang sementara tenaga kinetik meningkat.", "Falling object", "As an object falls, gravitational potential energy decreases while kinetic energy increases."),
        fact("Ayunan", "Dalam ayunan, tenaga berubah berulang kali antara tenaga keupayaan dan tenaga kinetik.", "Oscillation", "During oscillation, energy repeatedly changes between potential and kinetic energy."),
        fact("Jumlah tenaga mekanik", "Tanpa kehilangan tenaga, jumlah tenaga keupayaan dan tenaga kinetik adalah malar.", "Total mechanical energy", "Without energy loss, the sum of potential and kinetic energy remains constant."),
        fact("Perubahan bentuk", "Peralatan harian menukarkan tenaga daripada satu bentuk kepada bentuk lain semasa melakukan kerja.", "Energy transformation", "Everyday devices convert energy from one form to another while doing work."),
      ]},
    ],
  },
  {
    chapter: 8,
    title: bi("Keradioaktifan", "Radioactivity"),
    mission: bi("Sinaran digunakan untuk diagnosis, rawatan, industri dan pentarikhan, tetapi pendedahan mesti dikawal.", "Radiation is used in diagnosis, treatment, industry and dating, but exposure must be controlled."),
    whyItMatters: bi("Memahami nukleus, sinaran mengion dan langkah keselamatan membolehkan teknologi radioaktif digunakan secara bertanggungjawab.", "Understanding nuclei, ionising radiation and safety measures allows radioactive technology to be used responsibly."),
    objectives: [bi("Menghuraikan sejarah penemuan keradioaktifan.", "Describe the history of radioactivity discoveries."), bi("Menerangkan atom, nukleus dan sinaran.", "Explain atoms, nuclei and radiation."), bi("Menerangkan kegunaan dan keselamatan sinaran radioaktif.", "Explain uses and safety of radioactive radiation.")],
    summary: bi("Keradioaktifan ialah pereputan spontan nukleus tidak stabil yang memancarkan sinaran; sinaran mengion mempunyai pelbagai kegunaan tetapi memerlukan penyimpanan, perlindungan, pemantauan dan pelupusan yang selamat.", "Radioactivity is the spontaneous decay of unstable nuclei that emit radiation; ionising radiation has many uses but requires safe storage, shielding, monitoring and disposal."),
    subtopics: [
      { number: "8.1", title: bi("Sejarah Penemuan Keradioaktifan", "History of the Discovery of Radioactivity"), introduction: bi("Penemuan sinaran-X dan keradioaktifan berlaku pada akhir abad ke-19.", "X-rays and radioactivity were discovered at the end of the nineteenth century."), facts: [
        fact("Wilhelm Roentgen", "Wilhelm Roentgen menemukan sinar-X pada tahun 1895.", "Wilhelm Roentgen", "Wilhelm Roentgen discovered X-rays in 1895."),
        fact("Henri Becquerel", "Henri Becquerel menemukan keradioaktifan pada tahun 1896.", "Henri Becquerel", "Henri Becquerel discovered radioactivity in 1896."),
        fact("Marie dan Pierre Curie", "Marie dan Pierre Curie mengesan keradioaktifan melalui kesan pengionannya pada tahun 1897.", "Marie and Pierre Curie", "Marie and Pierre Curie detected radioactivity through its ionising effect in 1897."),
        fact("Keradioaktifan", "Keradioaktifan ialah proses pereputan spontan nukleus tidak stabil dengan memancarkan sinaran radioaktif.", "Radioactivity", "Radioactivity is the spontaneous decay of an unstable nucleus with the emission of radioactive radiation."),
        fact("Bahan radioaktif", "Karbon-14, radon-222, torium-234 dan uranium-238 ialah contoh bahan radioaktif.", "Radioactive substances", "Carbon-14, radon-222, thorium-234 and uranium-238 are examples of radioactive substances."),
      ]},
      { number: "8.2", title: bi("Atom dan Nukleus", "Atom and Nucleus"), introduction: bi("Struktur nukleus menentukan identiti dan kestabilan atom.", "Nuclear structure determines an atom's identity and stability."), facts: [
        fact("Proton", "Proton bercas positif dan terletak di dalam nukleus.", "Proton", "A proton is positively charged and located in the nucleus."),
        fact("Neutron", "Neutron tidak bercas dan terletak di dalam nukleus.", "Neutron", "A neutron has no charge and is located in the nucleus."),
        fact("Elektron", "Elektron bercas negatif dan bergerak mengelilingi nukleus.", "Electron", "An electron is negatively charged and moves around the nucleus."),
        fact("Nombor proton", "Nombor proton ialah bilangan proton dalam nukleus atom.", "Proton number", "The proton number is the number of protons in an atomic nucleus."),
        fact("Nombor nukleon", "Nombor nukleon ialah jumlah proton dan neutron dalam nukleus.", "Nucleon number", "The nucleon number is the total number of protons and neutrons in a nucleus."),
      ]},
      { number: "8.3", title: bi("Sinaran Mengion dan Tidak Mengion", "Ionising and Non-ionising Radiation"), introduction: bi("Sinaran mengion mempunyai tenaga yang cukup untuk menghasilkan ion.", "Ionising radiation has enough energy to produce ions."), facts: [
        fact("Sinaran mengion", "Sinar alfa, beta, gama dan sinar-X ialah sinaran mengion.", "Ionising radiation", "Alpha, beta and gamma radiation and X-rays are ionising radiation."),
        fact("Pengionan", "Pengionan menghasilkan ion positif dan ion negatif.", "Ionisation", "Ionisation produces positive and negative ions."),
        fact("Sumber semula jadi", "Sinaran kosmik dan sinaran latar belakang ialah sumber sinaran semula jadi.", "Natural sources", "Cosmic radiation and background radiation are natural radiation sources."),
        fact("Sumber buatan", "Ujian nuklear dan unsur radioaktif buatan ialah sumber sinaran buatan manusia.", "Artificial sources", "Nuclear tests and artificial radioactive elements are human-made radiation sources."),
        fact("Becquerel", "Becquerel, Bq, ialah unit S.I. bagi aktiviti keradioaktifan.", "Becquerel", "The becquerel, Bq, is the SI unit of radioactive activity."),
      ]},
      { number: "8.4", title: bi("Kegunaan Sinaran Radioaktif", "Uses of Radioactive Radiation"), introduction: bi("Kegunaan sinaran perlu diseimbangkan dengan perlindungan daripada kesan berbahaya.", "Radiation uses must be balanced with protection from harmful effects."), facts: [
        fact("Bidang kegunaan", "Sinaran radioaktif digunakan dalam pertanian, pertahanan, perubatan, arkeologi, geokronologi, industri dan pengawetan makanan.", "Fields of use", "Radioactive radiation is used in agriculture, defence, medicine, archaeology, geochronology, industry and food preservation."),
        fact("Penyimpanan", "Sumber radioaktif perlu disimpan di tempat khas yang selamat.", "Storage", "Radioactive sources must be stored in a special safe place."),
        fact("Perisai plumbum", "Kepingan plumbum digunakan untuk menghadang sinaran mengion.", "Lead shielding", "Lead sheets are used to block ionising radiation."),
        fact("Tangan robotik", "Tangan robotik digunakan untuk mengendalikan sumber radioaktif dari jarak selamat.", "Robotic hand", "A robotic hand is used to handle radioactive sources from a safe distance."),
        fact("Lencana sinaran", "Lencana sinaran dipakai untuk memantau dos sinaran yang diterima pekerja.", "Radiation badge", "A radiation badge is worn to monitor the radiation dose received by a worker."),
      ]},
    ],
  },
  {
    chapter: 9,
    title: bi("Cuaca Angkasa Lepas", "Space Weather"),
    mission: bi("Aktiviti Matahari boleh menghasilkan aurora yang indah tetapi juga mengganggu satelit, navigasi, telekomunikasi dan talian kuasa.", "Solar activity can produce beautiful auroras but also disrupt satellites, navigation, telecommunications and power lines."),
    whyItMatters: bi("Cuaca angkasa menunjukkan hubungan Matahari-Bumi dan peranan magnetosfera dalam melindungi hidupan serta teknologi.", "Space weather shows the Sun-Earth relationship and the magnetosphere's role in protecting life and technology."),
    objectives: [bi("Menerangkan struktur dan fenomena Matahari.", "Explain the Sun's structure and phenomena."), bi("Menghubungkaitkan aktiviti Matahari dengan kesan di Bumi.", "Relate solar activity to effects on Earth."), bi("Menerangkan cuaca angkasa dan magnetosfera.", "Explain space weather and the magnetosphere.")],
    summary: bi("Aktiviti pada fotosfera, kromosfera dan korona menghasilkan fenomena serta angin suria; interaksinya dengan medan magnet Bumi membentuk magnetosfera yang mengurangkan kesan zarah bercas.", "Activity in the photosphere, chromosphere and corona produces phenomena and solar wind; its interaction with Earth's magnetic field forms the magnetosphere, which reduces the effects of charged particles."),
    subtopics: [
      { number: "9.1", title: bi("Aktiviti Matahari yang Memberi Kesan kepada Bumi", "Solar Activities that Affect Earth"), introduction: bi("Matahari mempunyai lapisan dan fenomena yang berubah mengikut aktivitinya.", "The Sun has layers and phenomena that vary with its activity."), facts: [
        fact("Struktur Matahari", "Struktur Matahari terdiri daripada teras, zon radiasi, zon perolakan, fotosfera, kromosfera dan korona.", "Structure of the Sun", "The Sun consists of the core, radiation zone, convection zone, photosphere, chromosphere and corona."),
        fact("Teras", "Teras ialah bahagian Matahari tempat tenaga dijana.", "Core", "The core is the part of the Sun where energy is generated."),
        fact("Fotosfera", "Fotosfera ialah permukaan Matahari yang dapat dilihat dari Bumi.", "Photosphere", "The photosphere is the visible surface of the Sun."),
        fact("Granul", "Granul ialah corak berbutir pada fotosfera akibat arus perolakan.", "Granules", "Granules are grainy patterns on the photosphere caused by convection currents."),
        fact("Tompok Matahari", "Tompok Matahari kelihatan gelap kerana suhunya lebih rendah daripada kawasan sekeliling.", "Sunspots", "Sunspots appear dark because their temperature is lower than the surrounding regions."),
        fact("Kitaran suria", "Bilangan tompok Matahari berubah mengikut kitaran suria.", "Solar cycle", "The number of sunspots changes according to the solar cycle."),
        fact("Semarak suria", "Semarak suria ialah gelungan gas panas yang besar dari permukaan Matahari.", "Solar prominence", "A solar prominence is a large loop of hot gas from the Sun's surface."),
        fact("Nyalaan suria", "Nyalaan suria ialah letusan tenaga yang kuat di permukaan Matahari.", "Solar flare", "A solar flare is a powerful burst of energy at the Sun's surface."),
        fact("Lentingan jisim korona", "Lentingan jisim korona membebaskan sejumlah besar zarah bercas dari korona.", "Coronal mass ejection", "A coronal mass ejection releases a large amount of charged particles from the corona."),
        fact("Angin suria", "Angin suria ialah aliran zarah bercas yang bergerak keluar dari Matahari.", "Solar wind", "Solar wind is a stream of charged particles moving outward from the Sun."),
      ]},
      { number: "9.2", title: bi("Cuaca Angkasa", "Space Weather"), introduction: bi("Perubahan aktiviti Matahari dan angin suria menentukan keadaan ruang berhampiran Bumi.", "Changes in solar activity and solar wind determine conditions in near-Earth space."), facts: [
        fact("Cuaca angkasa", "Cuaca angkasa merujuk keadaan di angkasa yang dipengaruhi aktiviti Matahari dan angin suria.", "Space weather", "Space weather refers to conditions in space influenced by solar activity and solar wind."),
        fact("Magnetosfera", "Magnetosfera ialah kawasan di sekeliling Bumi yang dipengaruhi medan magnet Bumi.", "Magnetosphere", "The magnetosphere is the region around Earth influenced by Earth's magnetic field."),
        fact("Pembentukan magnetosfera", "Magnetosfera terbentuk daripada interaksi medan magnet dalam angin suria dengan medan magnet Bumi.", "Formation of the magnetosphere", "The magnetosphere forms through interaction between the magnetic field carried by solar wind and Earth's magnetic field."),
        fact("Bentuk magnetosfera", "Bentuk magnetosfera berubah apabila bilangan dan tenaga zarah angin suria berubah.", "Shape of the magnetosphere", "The magnetosphere's shape changes when the number and energy of solar-wind particles change."),
        fact("Sekatan biologi", "Magnetosfera bertindak sebagai sekatan biologi yang melindungi hidupan daripada kesan buruk angin suria.", "Biological shield", "The magnetosphere acts as a biological shield protecting life from harmful solar-wind effects."),
        fact("Zarah bercas", "Magnetosfera menghalang banyak elektron, proton dan zarah alfa dalam angin suria daripada sampai ke Bumi.", "Charged particles", "The magnetosphere prevents many electrons, protons and alpha particles in solar wind from reaching Earth."),
        fact("Tekanan angin suria", "Magnetosfera mengurangkan tekanan angin suria terhadap atmosfera Bumi.", "Solar-wind pressure", "The magnetosphere reduces solar-wind pressure on Earth's atmosphere."),
        fact("Aurora", "Interaksi zarah bercas dengan atmosfera Bumi boleh menghasilkan aurora.", "Aurora", "Interaction of charged particles with Earth's atmosphere can produce auroras."),
        fact("Gangguan teknologi", "Zarah bercas yang berlebihan boleh mengganggu telekomunikasi, sistem navigasi dan talian kuasa elektrik.", "Technology disruption", "Excess charged particles can disrupt telecommunications, navigation systems and electrical power lines."),
        fact("Hubungan tompok Matahari", "Peningkatan bilangan tompok Matahari berkait dengan peningkatan lentingan jisim korona dan angin suria.", "Sunspot relationship", "An increase in sunspot number is related to increased coronal mass ejections and solar wind."),
      ]},
    ],
  },
  {
    chapter: 10,
    title: bi("Penerokaan Angkasa Lepas", "Space Exploration"),
    mission: bi("Daripada memerhati langit hingga menghantar satelit dan kuar, manusia membina model serta teknologi untuk memahami angkasa.", "From observing the sky to sending satellites and probes, humans build models and technologies to understand space."),
    whyItMatters: bi("Penerokaan angkasa menyokong komunikasi, cuaca, penderiaan jauh, pertanian, geologi, pengurusan bencana dan pertahanan.", "Space exploration supports communication, weather, remote sensing, agriculture, geology, disaster management and defence."),
    objectives: [bi("Membandingkan perkembangan model astronomi.", "Compare the development of astronomical models."), bi("Menerangkan teknologi penerokaan angkasa.", "Explain space exploration technologies."), bi("Menerangkan aplikasi penderiaan jauh.", "Explain applications of remote sensing.")],
    summary: bi("Model Sistem Suria berkembang daripada geosentrik Ptolemy kepada heliosentrik Copernicus dan orbit elips Kepler; roket, satelit, kuar dan penderiaan jauh meluaskan penerokaan serta aplikasi di Bumi.", "Solar System models developed from Ptolemy's geocentric model to Copernicus's heliocentric model and Kepler's elliptical orbits; rockets, satellites, probes and remote sensing expand exploration and Earth applications."),
    subtopics: [
      { number: "10.1", title: bi("Perkembangan dalam Astronomi", "Developments in Astronomy"), introduction: bi("Model astronomi berubah apabila pemerhatian dan bukti baharu diperoleh.", "Astronomical models changed as new observations and evidence became available."), facts: [
        fact("Model Ptolemy", "Ptolemy membina model geosentrik dengan Bumi sebagai pusat Sistem Suria.", "Ptolemy's model", "Ptolemy developed a geocentric model with Earth at the centre of the Solar System."),
        fact("Orbit Ptolemy", "Dalam model Ptolemy, Matahari dan planet lain dianggap bergerak dalam orbit membulat mengelilingi Bumi.", "Ptolemaic orbits", "In Ptolemy's model, the Sun and other planets were considered to move in circular orbits around Earth."),
        fact("Model Copernicus", "Copernicus mengemukakan model heliosentrik dengan Matahari sebagai pusat Sistem Suria.", "Copernicus's model", "Copernicus proposed a heliocentric model with the Sun at the centre of the Solar System."),
        fact("Orbit Copernicus", "Copernicus menganggap Bumi dan planet lain bergerak dalam orbit membulat mengelilingi Matahari.", "Copernican orbits", "Copernicus considered Earth and other planets to move in circular orbits around the Sun."),
        fact("Model Kepler", "Kepler mengekalkan Matahari sebagai pusat tetapi menerangkan orbit planet sebagai elips.", "Kepler's model", "Kepler retained the Sun at the centre but described planetary orbits as ellipses."),
        fact("Model Sistem Suria", "Model digunakan untuk menggambarkan susunan dan pergerakan jasad dalam Sistem Suria.", "Solar System model", "A model is used to represent the arrangement and motion of bodies in the Solar System."),
        fact("Perkembangan bukti", "Perkembangan astronomi menunjukkan bahawa model saintifik boleh berubah berdasarkan bukti baharu.", "Development of evidence", "The development of astronomy shows that scientific models can change based on new evidence."),
        fact("Geosentrik", "Geosentrik bermaksud Bumi dianggap berada di pusat sistem.", "Geocentric", "Geocentric means Earth is considered to be at the centre of the system."),
        fact("Heliosentrik", "Heliosentrik bermaksud Matahari dianggap berada di pusat Sistem Suria.", "Heliocentric", "Heliocentric means the Sun is considered to be at the centre of the Solar System."),
        fact("Orbit elips", "Orbit elips menerangkan laluan planet yang tidak berbentuk bulatan sempurna.", "Elliptical orbit", "An elliptical orbit describes a planetary path that is not a perfect circle."),
      ]},
      { number: "10.2", title: bi("Teknologi Penerokaan Angkasa", "Technology in Space Exploration"), introduction: bi("Teknologi berbeza menjalankan fungsi penghantaran, pemerhatian dan pengumpulan data.", "Different technologies perform launch, observation and data-collection functions."), facts: [
        fact("Roket", "Roket digunakan untuk menghantar kapal angkasa, satelit dan kuar angkasa ke angkasa lepas.", "Rocket", "Rockets are used to launch spacecraft, satellites and space probes into space."),
        fact("Satelit", "Satelit mengumpul maklumat cuaca angkasa, keadaan angkasa dan data penderiaan jauh serta menyokong telekomunikasi dan pertahanan.", "Satellite", "Satellites collect space-weather, space-condition and remote-sensing data and support telecommunications and defence."),
        fact("Kuar angkasa", "Kuar angkasa mengumpul dan menghantar maklumat tentang jasad angkasa yang jauh.", "Space probe", "A space probe collects and transmits information about distant space bodies."),
        fact("Kapal angkasa", "Kapal angkasa membawa manusia atau peralatan untuk menjalankan misi di angkasa.", "Spacecraft", "A spacecraft carries people or equipment to conduct missions in space."),
        fact("Penderiaan jauh", "Penderiaan jauh mengumpul maklumat tentang permukaan Bumi tanpa sentuhan langsung.", "Remote sensing", "Remote sensing collects information about Earth's surface without direct contact."),
        fact("Pertanian", "Penderiaan jauh digunakan dalam pertanian untuk memerhati kawasan tanaman.", "Agriculture", "Remote sensing is used in agriculture to observe crop areas."),
        fact("Geologi", "Penderiaan jauh membantu kajian geologi dan sumber permukaan Bumi.", "Geology", "Remote sensing supports geological studies and investigation of Earth's surface resources."),
        fact("Pengurusan bencana", "Data penderiaan jauh membantu memantau dan mengurus bencana.", "Disaster management", "Remote-sensing data helps monitor and manage disasters."),
        fact("Telekomunikasi", "Satelit membolehkan penghantaran maklumat telekomunikasi merentasi jarak jauh.", "Telecommunications", "Satellites enable telecommunication information to be transmitted over long distances."),
        fact("Pertahanan", "Teknologi satelit dan penderiaan jauh mempunyai aplikasi dalam pertahanan.", "Defence", "Satellite and remote-sensing technologies have applications in defence."),
      ]},
    ],
  },
];
