import type { PairedQuizSeed } from "../paired-quiz-bank";

const q = (
  bm: string,
  dlp: string,
  correct: PairedQuizSeed["correct"],
  distractors: PairedQuizSeed["distractors"],
  bmExplanation: string,
  dlpExplanation: string,
): PairedQuizSeed => ({
  question: [bm, dlp],
  correct,
  distractors,
  explanation: [bmExplanation, dlpExplanation],
});

export const mathF2C4PairedSeeds: readonly PairedQuizSeed[] = [
  // Objective 1 — Foundation: names and recognition (5)
  q(
    "Apakah nama poligon yang mempunyai 5 sisi?",
    "What is the name of a polygon with 5 sides?",
    ["Pentagon", "Pentagon"],
    [
      ["Segi tiga", "Triangle"],
      ["Heksagon", "Hexagon"],
      ["Oktagon", "Octagon"],
    ],
    "Poligon bersisi 5 dinamakan pentagon.",
    "A 5-sided polygon is called a pentagon.",
  ),
  q(
    "Sebuah heptagon mempunyai berapa bucu?",
    "How many vertices does a heptagon have?",
    "7",
    ["6", "8", "9"],
    "Bilangan bucu poligon sama dengan bilangan sisinya; heptagon mempunyai 7.",
    "A polygon has the same number of vertices as sides; a heptagon has 7.",
  ),
  q(
    "Poligon manakah mempunyai 10 sisi?",
    "Which polygon has 10 sides?",
    ["Dekagon", "Decagon"],
    [
      ["Nonagon", "Nonagon"],
      ["Oktagon", "Octagon"],
      ["Dodekagon", "Dodecagon"],
    ],
    "Dekagon ialah poligon yang mempunyai 10 sisi.",
    "A decagon is a polygon with 10 sides.",
  ),
  q(
    "Bentuk tertutup yang terdiri daripada tiga atau lebih garis lurus disebut apa?",
    "What is a closed shape made of three or more straight line segments called?",
    ["Poligon", "Polygon"],
    [
      ["Bulatan", "Circle"],
      ["Lengkok", "Arc"],
      ["Garis selari", "Parallel lines"],
    ],
    "Poligon ialah bentuk tertutup yang dibina daripada garis lurus.",
    "A polygon is a closed shape formed by straight line segments.",
  ),
  q(
    "Sebuah nonagon mempunyai berapa sisi dan bucu?",
    "How many sides and vertices does a nonagon have?",
    ["9 sisi dan 9 bucu", "9 sides and 9 vertices"],
    [
      ["8 sisi dan 9 bucu", "8 sides and 9 vertices"],
      ["9 sisi dan 10 bucu", "9 sides and 10 vertices"],
      ["10 sisi dan 10 bucu", "10 sides and 10 vertices"],
    ],
    "Nonagon mempunyai 9 sisi dan setiap pertemuan sisi membentuk 9 bucu.",
    "A nonagon has 9 sides and their junctions form 9 vertices.",
  ),

  // Regular versus irregular and properties (5)
  q(
    "Antara berikut, yang manakah menerangkan poligon sekata?",
    "Which statement describes a regular polygon?",
    ["Semua sisi dan semua sudut pedalaman sama", "All sides and all interior angles are equal"],
    [
      ["Hanya semua sisinya sama", "Only all its sides are equal"],
      ["Hanya semua sudutnya sama", "Only all its angles are equal"],
      ["Mempunyai sekurang-kurangnya dua sisi melengkung", "It has at least two curved sides"],
    ],
    "Poligon sekata mesti mempunyai semua sisi dan semua sudut pedalaman yang sama.",
    "A regular polygon must have all sides and all interior angles equal.",
  ),
  q(
    "Sebuah segi empat mempunyai empat sisi sama tetapi sudutnya bukan semua sama. Apakah jenisnya?",
    "A quadrilateral has four equal sides but its angles are not all equal. What type is it?",
    ["Poligon tidak sekata", "Irregular polygon"],
    [
      ["Poligon sekata", "Regular polygon"],
      ["Bukan poligon", "Not a polygon"],
      ["Segi tiga sekata", "Regular triangle"],
    ],
    "Kesamaan sisi sahaja tidak mencukupi; sudut juga mesti sama untuk menjadi sekata.",
    "Equal sides alone are insufficient; the angles must also be equal for it to be regular.",
  ),
  q(
    "Yang manakah semestinya benar bagi segi tiga sama sisi?",
    "Which is always true for an equilateral triangle?",
    ["Ia poligon sekata", "It is a regular polygon"],
    [
      ["Ia tidak mempunyai paksi simetri", "It has no axes of symmetry"],
      ["Satu sudutnya berbeza", "One of its angles is different"],
      ["Ia mempunyai empat bucu", "It has four vertices"],
    ],
    "Semua sisi dan sudut segi tiga sama sisi adalah sama, jadi ia sekata.",
    "All sides and angles of an equilateral triangle are equal, so it is regular.",
  ),
  q(
    "Mengapakah sebuah segi empat tepat yang bukan segi empat sama tidak sekata?",
    "Why is a rectangle that is not a square irregular?",
    ["Tidak semua sisinya sama panjang", "Not all its sides are equal in length"],
    [
      ["Sudutnya tidak sama", "Its angles are unequal"],
      ["Ia mempunyai garis melengkung", "It has a curved line"],
      ["Ia tidak tertutup", "It is not closed"],
    ],
    "Semua sudutnya sama, tetapi dua pasang sisinya berlainan panjang.",
    "All its angles are equal, but its two pairs of sides have different lengths.",
  ),
  q(
    "Sebuah heksagon mempunyai enam sisi sama tetapi satu sudut berbeza. Apakah kesimpulan yang betul?",
    "A hexagon has six equal sides but one angle is different. What is the correct conclusion?",
    ["Heksagon itu tidak sekata", "The hexagon is irregular"],
    [
      ["Heksagon itu sekata", "The hexagon is regular"],
      ["Bentuk itu ialah pentagon", "The shape is a pentagon"],
      ["Bentuk itu bukan poligon", "The shape is not a polygon"],
    ],
    "Poligon sekata memerlukan semua sisi dan semua sudut sama; satu sudut berbeza menjadikannya tidak sekata.",
    "A regular polygon requires all sides and all angles equal; one different angle makes it irregular.",
  ),

  // Symmetry (4)
  q(
    "Berapakah bilangan paksi simetri bagi pentagon sekata?",
    "How many axes of symmetry does a regular pentagon have?",
    "5",
    ["3", "4", "10"],
    "Poligon sekata bersisi n mempunyai n paksi simetri; n = 5.",
    "A regular n-gon has n axes of symmetry; here n = 5.",
  ),
  q(
    "Sebuah poligon sekata mempunyai 8 paksi simetri. Berapakah bilangan sisinya?",
    "A regular polygon has 8 axes of symmetry. How many sides does it have?",
    "8",
    ["4", "6", "16"],
    "Bilangan paksi simetri poligon sekata sama dengan bilangan sisinya.",
    "The number of symmetry axes of a regular polygon equals its number of sides.",
  ),
  q(
    "Paksi simetri bagi poligon membahagikan bentuk itu kepada apa?",
    "What does an axis of symmetry divide a polygon into?",
    ["Dua bahagian yang sepadan tepat", "Two exactly matching halves"],
    [
      ["Dua bahagian yang sentiasa berlainan luas", "Two parts that always have different areas"],
      ["Tiga bahagian sama", "Three equal parts"],
      ["Sudut pedalaman dan peluaran", "An interior and an exterior angle"],
    ],
    "Apabila dilipat pada paksi simetri, kedua-dua bahagian bertindih tepat.",
    "When folded along an axis of symmetry, the two halves match exactly.",
  ),
  q(
    "Berapakah paksi simetri bagi segi tiga sama sisi?",
    "How many axes of symmetry does an equilateral triangle have?",
    "3",
    ["1", "2", "6"],
    "Setiap bucu boleh dihubungkan ke titik tengah sisi bertentangan untuk membentuk satu paksi; jumlahnya 3.",
    "Each vertex can join the midpoint of the opposite side to form an axis; there are 3.",
  ),

  // Triangles and interior sums (5)
  q(
    "Berapa segi tiga terhasil apabila satu bucu pentagon disambungkan kepada semua bucu tidak bersebelahan?",
    "How many triangles are formed when one vertex of a pentagon is joined to all non-adjacent vertices?",
    "3",
    ["2", "4", "5"],
    "Bilangan segi tiga ialah n − 2 = 5 − 2 = 3.",
    "The number of triangles is n − 2 = 5 − 2 = 3.",
  ),
  q(
    "Apakah rumus jumlah sudut pedalaman poligon bersisi n?",
    "What is the formula for the sum of interior angles of an n-sided polygon?",
    "(n − 2) × 180°",
    ["n × 180°", "(n + 2) × 180°", "360°/n"],
    "Poligon boleh dibahagi kepada n − 2 segi tiga, setiap satunya berjumlah 180°.",
    "A polygon can be divided into n − 2 triangles, each with angle sum 180°.",
  ),
  q(
    "Hitung jumlah sudut pedalaman heksagon.",
    "Calculate the sum of the interior angles of a hexagon.",
    "720°",
    ["540°", "900°", "1080°"],
    "(6 − 2) × 180° = 720°.",
    "(6 − 2) × 180° = 720°.",
  ),
  q(
    "Jumlah sudut pedalaman sebuah segi empat ialah berapa?",
    "What is the sum of the interior angles of a quadrilateral?",
    "360°",
    ["180°", "270°", "540°"],
    "(4 − 2) × 180° = 360°.",
    "(4 − 2) × 180° = 360°.",
  ),
  q(
    "Sebuah poligon dibahagi kepada 6 segi tiga dari satu bucu. Berapakah jumlah sudut pedalamannya?",
    "A polygon is divided into 6 triangles from one vertex. What is its interior-angle sum?",
    "1080°",
    ["720°", "900°", "1260°"],
    "Enam segi tiga memberi jumlah 6 × 180° = 1080°.",
    "Six triangles give a total of 6 × 180° = 1080°.",
  ),

  // Regular interior angles (5)
  q(
    "Setiap sudut pedalaman segi tiga sama sisi ialah berapa?",
    "What is each interior angle of an equilateral triangle?",
    "60°",
    ["45°", "90°", "120°"],
    "Jumlah 180° dibahagi sama rata kepada 3 sudut: 60°.",
    "The sum 180° is divided equally among 3 angles: 60°.",
  ),
  q(
    "Cari sudut pedalaman sebuah segi empat sama.",
    "Find an interior angle of a square.",
    "90°",
    ["60°", "120°", "135°"],
    "Jumlah sudut pedalaman 360° dibahagi 4, iaitu 90°.",
    "The interior-angle sum 360° divided by 4 is 90°.",
  ),
  q(
    "Sebuah heksagon sekata mempunyai jumlah sudut pedalaman 720°. Berapakah satu sudut pedalamannya?",
    "A regular hexagon has an interior-angle sum of 720°. What is one interior angle?",
    "120°",
    ["60°", "90°", "144°"],
    "Semua 6 sudut sama: 720° ÷ 6 = 120°.",
    "All 6 angles are equal: 720° ÷ 6 = 120°.",
  ),
  q(
    "Berapakah satu sudut pedalaman pentagon sekata?",
    "What is one interior angle of a regular pentagon?",
    "108°",
    ["72°", "90°", "120°"],
    "Jumlahnya (5 − 2) × 180° = 540°; 540° ÷ 5 = 108°.",
    "Its sum is (5 − 2) × 180° = 540°; 540° ÷ 5 = 108°.",
  ),
  q(
    "Setiap sudut peluaran sebuah oktagon sekata ialah 45°. Cari sudut pedalamannya.",
    "Each exterior angle of a regular octagon is 45°. Find its interior angle.",
    "135°",
    ["45°", "90°", "315°"],
    "Sudut pedalaman + sudut peluaran = 180°, jadi 180° − 45° = 135°.",
    "Interior angle + exterior angle = 180°, so 180° − 45° = 135°.",
  ),

  // Exterior angles (4)
  q(
    "Berapakah jumlah sudut peluaran bagi mana-mana poligon cembung?",
    "What is the sum of the exterior angles of any convex polygon?",
    "360°",
    ["180°", "540°", "Bergantung pada bilangan sisi"],
    "Satu sudut peluaran pada setiap bucu sentiasa berjumlah 360°.",
    "One exterior angle at each vertex always sums to 360°.",
  ),
  q(
    "Cari satu sudut peluaran bagi pentagon sekata.",
    "Find one exterior angle of a regular pentagon.",
    "72°",
    ["36°", "90°", "108°"],
    "360° ÷ 5 = 72°.",
    "360° ÷ 5 = 72°.",
  ),
  q(
    "Sebuah poligon sekata mempunyai 12 sisi. Berapakah sudut peluarannya?",
    "A regular polygon has 12 sides. What is its exterior angle?",
    "30°",
    ["15°", "60°", "150°"],
    "Sudut peluaran = 360° ÷ 12 = 30°.",
    "Exterior angle = 360° ÷ 12 = 30°.",
  ),
  q(
    "Sudut pedalaman poligon sekata ialah 150°. Berapakah sudut peluarannya?",
    "A regular polygon has an interior angle of 150°. What is its exterior angle?",
    "30°",
    ["10°", "150°", "210°"],
    "Kedua-duanya berjumlah 180°: 180° − 150° = 30°.",
    "They sum to 180°: 180° − 150° = 30°.",
  ),

  // Simple missing angles (2)
  q(
    "Tiga sudut sebuah segi empat ialah 80°, 95° dan 105°. Cari sudut keempat.",
    "Three angles of a quadrilateral are 80°, 95° and 105°. Find the fourth angle.",
    "80°",
    ["70°", "90°", "100°"],
    "Sudut keempat = 360° − (80° + 95° + 105°) = 80°.",
    "Fourth angle = 360° − (80° + 95° + 105°) = 80°.",
  ),
  q(
    "Dua sudut sebuah segi tiga ialah 48° dan 67°. Cari sudut ketiga.",
    "Two angles of a triangle are 48° and 67°. Find the third angle.",
    "65°",
    ["55°", "75°", "115°"],
    "Sudut ketiga = 180° − 48° − 67° = 65°.",
    "Third angle = 180° − 48° − 67° = 65°.",
  ),

  // Objective 2 — Practice: number of sides from angles (5)
  q(
    "Sebuah poligon sekata mempunyai sudut peluaran 40°. Berapakah bilangan sisinya?",
    "A regular polygon has an exterior angle of 40°. How many sides does it have?",
    "9",
    ["8", "10", "14"],
    "n = 360° ÷ 40° = 9.",
    "n = 360° ÷ 40° = 9.",
  ),
  q(
    "Sudut pedalaman sebuah poligon sekata ialah 156°. Tentukan bilangan sisinya.",
    "A regular polygon has an interior angle of 156°. Determine its number of sides.",
    "15",
    ["12", "18", "24"],
    "Sudut peluaran = 180° − 156° = 24°; n = 360° ÷ 24° = 15.",
    "Exterior angle = 180° − 156° = 24°; n = 360° ÷ 24° = 15.",
  ),
  q(
    "Jumlah sudut pedalaman sebuah poligon ialah 1260°. Berapakah bilangan sisinya?",
    "A polygon has an interior-angle sum of 1260°. How many sides does it have?",
    "9",
    ["7", "8", "11"],
    "(n − 2)180° = 1260°, jadi n − 2 = 7 dan n = 9.",
    "(n − 2)180° = 1260°, so n − 2 = 7 and n = 9.",
  ),
  q(
    "Dari satu bucu, sebuah poligon boleh dibahagi kepada 8 segi tiga. Berapa sisinya?",
    "From one vertex, a polygon can be divided into 8 triangles. How many sides does it have?",
    "10",
    ["6", "8", "12"],
    "n − 2 = 8, maka n = 10.",
    "n − 2 = 8, so n = 10.",
  ),
  q(
    "Satu sudut peluaran poligon sekata ialah satu perlima sudut pedalamannya. Cari bilangan sisi.",
    "A regular polygon's exterior angle is one fifth of its interior angle. Find the number of sides.",
    "12",
    ["6", "10", "15"],
    "Jika peluaran = x, pedalaman = 5x. Maka 6x = 180°, x = 30° dan n = 360°/30° = 12.",
    "Let exterior = x and interior = 5x. Then 6x = 180°, x = 30°, and n = 360°/30° = 12.",
  ),

  // Interior/exterior relationship (6)
  q(
    "Sudut peluaran sebuah poligon sekata ialah 24°. Cari sudut pedalamannya.",
    "A regular polygon has an exterior angle of 24°. Find its interior angle.",
    "156°",
    ["144°", "166°", "336°"],
    "Sudut pedalaman = 180° − 24° = 156°.",
    "Interior angle = 180° − 24° = 156°.",
  ),
  q(
    "Jika sudut pedalaman ialah (3x + 20)° dan sudut peluarannya (x + 40)°, cari x.",
    "If an interior angle is (3x + 20)° and its exterior angle is (x + 40)°, find x.",
    "30",
    ["20", "35", "40"],
    "(3x + 20) + (x + 40) = 180. Jadi 4x = 120 dan x = 30.",
    "(3x + 20) + (x + 40) = 180. Thus 4x = 120 and x = 30.",
  ),
  q(
    "Sudut pedalaman sebuah poligon sekata ialah tiga kali sudut peluarannya. Cari kedua-dua sudut.",
    "A regular polygon's interior angle is three times its exterior angle. Find both angles.",
    ["135° dan 45°", "135° and 45°"],
    [
      ["120° dan 60°", "120° and 60°"],
      ["150° dan 50°", "150° and 50°"],
      ["90° dan 30°", "90° and 30°"],
    ],
    "3x + x = 180°, maka x = 45°. Sudut pedalaman = 135°.",
    "3x + x = 180°, so x = 45°. The interior angle is 135°.",
  ),
  q(
    "Sebuah poligon sekata bersisi 20. Cari beza antara sudut pedalaman dengan sudut peluaran.",
    "A regular polygon has 20 sides. Find the difference between its interior and exterior angles.",
    "144°",
    ["126°", "162°", "180°"],
    "Sudut peluaran = 360°/20 = 18° dan pedalaman = 162°. Beza = 144°.",
    "Exterior angle = 360°/20 = 18° and interior angle = 162°. Difference = 144°.",
  ),
  q(
    "Sudut peluaran poligon sekata bertambah daripada 30° kepada 45°. Bagaimanakah sudut pedalamannya berubah?",
    "A regular polygon's exterior angle increases from 30° to 45°. How does its interior angle change?",
    ["Berkurang 15°", "It decreases by 15°"],
    [
      ["Bertambah 15°", "It increases by 15°"],
      ["Berkurang 30°", "It decreases by 30°"],
      ["Tidak berubah", "It does not change"],
    ],
    "Sudut pedalaman berubah daripada 150° kepada 135°, iaitu berkurang 15°.",
    "The interior angle changes from 150° to 135°, a decrease of 15°.",
  ),
  q(
    "Sudut pedalaman poligon sekata A ialah 140°, manakala B ialah 150°. Poligon manakah mempunyai lebih banyak sisi?",
    "Regular polygon A has interior angle 140°, while B has 150°. Which polygon has more sides?",
    ["Poligon B", "Polygon B"],
    [
      ["Poligon A", "Polygon A"],
      ["Kedua-duanya sama", "Both have the same number"],
      ["Tidak dapat ditentukan", "Cannot be determined"],
    ],
    "B mempunyai sudut peluaran lebih kecil, 30° berbanding 40°, jadi B mempunyai lebih banyak sisi.",
    "B has the smaller exterior angle, 30° versus 40°, so B has more sides.",
  ),

  // Sums (5)
  q(
    "Cari jumlah sudut pedalaman sebuah poligon bersisi 11.",
    "Find the interior-angle sum of an 11-sided polygon.",
    "1620°",
    ["1440°", "1800°", "1980°"],
    "(11 − 2) × 180° = 1620°.",
    "(11 − 2) × 180° = 1620°.",
  ),
  q(
    "Jumlah tujuh sudut peluaran berturutan sebuah poligon ialah 280°. Jika semua sudut peluaran lain berjumlah 80°, apakah jumlah keseluruhan?",
    "Seven consecutive exterior angles of a polygon total 280°. If all remaining exterior angles total 80°, what is the overall sum?",
    "360°",
    ["200°", "280°", "440°"],
    "280° + 80° = 360°, selaras dengan jumlah sudut peluaran poligon.",
    "280° + 80° = 360°, consistent with a polygon's exterior-angle sum.",
  ),
  q(
    "Sebuah poligon mempunyai 14 sisi. Berapa segi tiga terbentuk dari satu bucu dan apakah jumlah sudut pedalamannya?",
    "A polygon has 14 sides. How many triangles form from one vertex and what is its interior-angle sum?",
    ["12 segi tiga, 2160°", "12 triangles, 2160°"],
    [
      ["14 segi tiga, 2520°", "14 triangles, 2520°"],
      ["12 segi tiga, 2520°", "12 triangles, 2520°"],
      ["16 segi tiga, 2880°", "16 triangles, 2880°"],
    ],
    "n − 2 = 12 segi tiga; jumlah = 12 × 180° = 2160°.",
    "n − 2 = 12 triangles; sum = 12 × 180° = 2160°.",
  ),
  q(
    "Jumlah sudut pedalaman poligon A ialah 900° dan poligon B ialah 1440°. Berapakah beza bilangan sisi?",
    "Polygon A has interior-angle sum 900° and polygon B has 1440°. What is the difference in their numbers of sides?",
    "3",
    ["2", "4", "5"],
    "A: n = 900/180 + 2 = 7. B: n = 1440/180 + 2 = 10. Beza = 3.",
    "A: n = 900/180 + 2 = 7. B: n = 1440/180 + 2 = 10. Difference = 3.",
  ),
  q(
    "Sebuah poligon sekata mempunyai 18 sisi. Cari jumlah semua sudut pedalaman dan jumlah semua sudut peluaran.",
    "A regular polygon has 18 sides. Find the sums of all interior and exterior angles.",
    ["2880° dan 360°", "2880° and 360°"],
    [
      ["3240° dan 360°", "3240° and 360°"],
      ["2880° dan 180°", "2880° and 180°"],
      ["3240° dan 180°", "3240° and 180°"],
    ],
    "Jumlah pedalaman = (18 − 2)180° = 2880°; jumlah peluaran = 360°.",
    "Interior sum = (18 − 2)180° = 2880°; exterior sum = 360°.",
  ),

  // Multi-angle missing values (5)
  q(
    "Sudut sebuah pentagon ialah 100°, 110°, 120°, 90° dan x°. Cari x.",
    "A pentagon's angles are 100°, 110°, 120°, 90° and x°. Find x.",
    "120°",
    ["100°", "110°", "140°"],
    "Jumlah pentagon = 540°. Maka x = 540° − 420° = 120°.",
    "A pentagon's sum is 540°. Thus x = 540° − 420° = 120°.",
  ),
  q(
    "Sudut sebuah heksagon ialah 110°, 125°, 130°, 115°, x° dan x°. Cari x.",
    "A hexagon's angles are 110°, 125°, 130°, 115°, x° and x°. Find x.",
    "120°",
    ["100°", "110°", "130°"],
    "Jumlah tetap = 480°. Jadi 2x = 720° − 480° = 240° dan x = 120°.",
    "The fixed angles total 480°. So 2x = 720° − 480° = 240° and x = 120°.",
  ),
  q(
    "Empat sudut peluaran sebuah pentagon ialah 65°, 80°, 70° dan 75°. Cari sudut peluaran kelima.",
    "Four exterior angles of a pentagon are 65°, 80°, 70° and 75°. Find the fifth exterior angle.",
    "70°",
    ["60°", "80°", "90°"],
    "Sudut kelima = 360° − (65° + 80° + 70° + 75°) = 70°.",
    "Fifth angle = 360° − (65° + 80° + 70° + 75°) = 70°.",
  ),
  q(
    "Sudut sebuah segi empat ialah x°, (x + 10)°, (x + 20)° dan (x + 30)°. Cari x.",
    "A quadrilateral's angles are x°, (x + 10)°, (x + 20)° and (x + 30)°. Find x.",
    "75°",
    ["60°", "70°", "90°"],
    "4x + 60° = 360°, maka 4x = 300° dan x = 75°.",
    "4x + 60° = 360°, so 4x = 300° and x = 75°.",
  ),
  q(
    "Tiga sudut peluaran sebuah heksagon ialah 50° setiap satu. Tiga yang lain sama besar. Cari setiap sudut yang lain.",
    "Three exterior angles of a hexagon are 50° each. The other three are equal. Find each remaining angle.",
    "70°",
    ["50°", "60°", "90°"],
    "Baki = 360° − 150° = 210°. Setiap satu = 210°/3 = 70°.",
    "Remainder = 360° − 150° = 210°. Each is 210°/3 = 70°.",
  ),

  // Symmetry/property applications (4)
  q(
    "Sebuah logo berbentuk poligon sekata mempunyai 12 paksi simetri. Apakah sudut putaran terkecil yang memetakannya pada diri sendiri?",
    "A regular-polygon logo has 12 axes of symmetry. What is its smallest rotational angle onto itself?",
    "30°",
    ["15°", "60°", "150°"],
    "Poligon itu mempunyai 12 sisi; sudut putaran terkecil = 360°/12 = 30°.",
    "It has 12 sides; the smallest rotational angle is 360°/12 = 30°.",
  ),
  q(
    "Dua poligon sekata mempunyai 6 dan 9 paksi simetri. Berapakah jumlah bilangan sisinya?",
    "Two regular polygons have 6 and 9 axes of symmetry. What is their total number of sides?",
    "15",
    ["3", "12", "54"],
    "Bilangan sisi masing-masing ialah 6 dan 9, jadi jumlahnya 15.",
    "Their numbers of sides are 6 and 9, so the total is 15.",
  ),
  q(
    "Sebuah bentuk mempunyai 5 sisi sama dan tepat 5 paksi simetri. Apakah bentuk itu?",
    "A shape has 5 equal sides and exactly 5 axes of symmetry. What is it?",
    ["Pentagon sekata", "Regular pentagon"],
    [
      ["Pentagon tidak sekata", "Irregular pentagon"],
      ["Heksagon sekata", "Regular hexagon"],
      ["Segi empat sama", "Square"],
    ],
    "Pentagon sekata mempunyai 5 sisi sama, 5 sudut sama dan 5 paksi simetri.",
    "A regular pentagon has 5 equal sides, 5 equal angles and 5 axes of symmetry.",
  ),
  q(
    "Sebuah jubin heksagon mempunyai hanya 2 paksi simetri. Mengapakah ia bukan heksagon sekata?",
    "A hexagonal tile has only 2 axes of symmetry. Why is it not a regular hexagon?",
    [
      "Heksagon sekata sepatutnya mempunyai 6 paksi simetri",
      "A regular hexagon should have 6 axes of symmetry",
    ],
    [
      ["Semua heksagon tiada simetri", "All hexagons have no symmetry"],
      ["Poligon sekata mesti mempunyai 12 paksi", "A regular polygon must have 12 axes"],
      ["Bilangan paksi mesti dua kali bilangan sisi", "The axes must be twice the number of sides"],
    ],
    "Poligon sekata bersisi 6 mempunyai 6 paksi simetri, bukan 2.",
    "A regular 6-sided polygon has 6 axes of symmetry, not 2.",
  ),

  // Contextual applications (5)
  q(
    "Meja bulat dihias dengan corak poligon sekata yang sudut peluarannya 60°. Apakah poligon itu?",
    "A table is decorated with a regular-polygon pattern whose exterior angle is 60°. What is the polygon?",
    ["Heksagon sekata", "Regular hexagon"],
    [
      ["Pentagon sekata", "Regular pentagon"],
      ["Oktagon sekata", "Regular octagon"],
      ["Dekagon sekata", "Regular decagon"],
    ],
    "n = 360°/60° = 6, jadi poligon itu heksagon sekata.",
    "n = 360°/60° = 6, so it is a regular hexagon.",
  ),
  q(
    "Sebuah laluan berbentuk poligon sekata mempunyai sudut pedalaman 144° pada setiap penjuru. Berapa penjuru laluan itu?",
    "A regular-polygon path has an interior angle of 144° at each corner. How many corners does it have?",
    "10",
    ["8", "9", "12"],
    "Sudut peluaran = 36°; n = 360°/36° = 10.",
    "Exterior angle = 36°; n = 360°/36° = 10.",
  ),
  q(
    "Robot berpusing melalui sudut peluaran yang sama di setiap bucu dan kembali ke arah asal selepas 8 pusingan. Berapa darjah setiap pusingan?",
    "A robot turns through equal exterior angles at each vertex and faces its original direction after 8 turns. How many degrees is each turn?",
    "45°",
    ["22.5°", "80°", "135°"],
    "Satu pusingan penuh ialah 360°; 360°/8 = 45°.",
    "One full turn is 360°; 360°/8 = 45°.",
  ),
  q(
    "Sebuah bingkai pentagon tidak sekata mempunyai empat sudut 95°, 105°, 120° dan 130°. Cari sudut terakhir.",
    "An irregular pentagonal frame has four angles of 95°, 105°, 120° and 130°. Find the last angle.",
    "90°",
    ["80°", "100°", "110°"],
    "Jumlah pentagon = 540°. Sudut terakhir = 540° − 450° = 90°.",
    "A pentagon's sum is 540°. Last angle = 540° − 450° = 90°.",
  ),
  q(
    "Dua papan tanda ialah poligon sekata. Satu mempunyai sudut peluaran 72° dan satu lagi 45°. Berapakah beza bilangan sisi?",
    "Two signs are regular polygons. One has exterior angle 72° and the other 45°. What is the difference in their numbers of sides?",
    "3",
    ["2", "5", "8"],
    "Bilangan sisi ialah 360/72 = 5 dan 360/45 = 8. Beza = 3.",
    "The side counts are 360/72 = 5 and 360/45 = 8. Difference = 3.",
  ),

  // Objective 3 — Challenge: multi-step unknown angles (8)
  q(
    "Sudut pedalaman poligon sekata ialah (5x + 10)° dan sudut peluarannya (x + 2)°. Cari bilangan sisi.",
    "A regular polygon has interior angle (5x + 10)° and exterior angle (x + 2)°. Find its number of sides.",
    "12",
    ["9", "10", "15"],
    "6x + 12 = 180, jadi x = 28. Sudut peluaran = 30°, maka n = 360/30 = 12.",
    "6x + 12 = 180, so x = 28. Exterior angle = 30°, hence n = 360/30 = 12.",
  ),
  q(
    "Sudut sebuah pentagon ialah x°, (x + 10)°, (2x − 20)°, 110° dan 120°. Cari sudut terbesar.",
    "A pentagon's angles are x°, (x + 10)°, (2x − 20)°, 110° and 120°. Find the largest angle.",
    "140°",
    ["120°", "130°", "150°"],
    "4x + 220 = 540, jadi x = 80. Sudut-sudut berubah ialah 80°, 90° dan 140°; terbesar ialah 140°.",
    "4x + 220 = 540, so x = 80. The variable angles are 80°, 90° and 140°; the largest is 140°.",
  ),
  q(
    "Lima sudut sebuah heksagon ialah 100°, 110°, 120°, 130° dan 140°. Sudut keenam dibahagi dua oleh satu garis. Cari setiap bahagian.",
    "Five angles of a hexagon are 100°, 110°, 120°, 130° and 140°. The sixth angle is bisected. Find each half.",
    "60°",
    ["50°", "70°", "120°"],
    "Sudut keenam = 720° − 600° = 120°. Setiap bahagian = 60°.",
    "Sixth angle = 720° − 600° = 120°. Each half is 60°.",
  ),
  q(
    "Sudut peluaran sebuah poligon ialah 35°, 45°, 55°, 65°, 75° dan x°. Cari sudut pedalaman yang sepadan dengan x.",
    "A polygon's exterior angles are 35°, 45°, 55°, 65°, 75° and x°. Find the interior angle corresponding to x.",
    "95°",
    ["75°", "85°", "105°"],
    "x = 360° − 275° = 85°. Sudut pedalaman = 180° − 85° = 95°.",
    "x = 360° − 275° = 85°. The interior angle is 180° − 85° = 95°.",
  ),
  q(
    "Tiga sudut sebuah pentagon sama dengan 110°. Dua sudut lain ialah x° dan (x + 30)°. Cari x.",
    "Three angles of a pentagon are each 110°. The other two are x° and (x + 30)°. Find x.",
    "90°",
    ["75°", "105°", "120°"],
    "330 + x + x + 30 = 540. Jadi 2x = 180 dan x = 90°.",
    "330 + x + x + 30 = 540. Thus 2x = 180 and x = 90°.",
  ),
  q(
    "Sudut pedalaman poligon sekata A ialah 15° lebih besar daripada poligon sekata B. Sudut peluaran B ialah 45°. Cari bilangan sisi A.",
    "Regular polygon A's interior angle is 15° larger than regular polygon B's. B's exterior angle is 45°. Find A's number of sides.",
    "12",
    ["8", "10", "15"],
    "Pedalaman B = 135°, jadi pedalaman A = 150° dan peluarannya 30°. Maka n = 12.",
    "B's interior angle is 135°, so A's is 150° and its exterior is 30°. Thus n = 12.",
  ),
  q(
    "Jumlah sudut pedalaman poligon ialah 5 kali jumlah sudut peluarannya. Berapa sisi poligon itu?",
    "A polygon's interior-angle sum is 5 times its exterior-angle sum. How many sides does it have?",
    "12",
    ["7", "10", "14"],
    "Jumlah pedalaman = 5(360°) = 1800°. (n − 2)180° = 1800°, jadi n = 12.",
    "Interior sum = 5(360°) = 1800°. (n − 2)180° = 1800°, so n = 12.",
  ),
  q(
    "Sudut pedalaman sebuah poligon sekata ialah dua kali sudut pedalaman segi tiga sama sisi. Berapa paksi simetrinya?",
    "A regular polygon's interior angle is twice that of an equilateral triangle. How many axes of symmetry does it have?",
    "6",
    ["4", "5", "8"],
    "Sudutnya 2(60°) = 120°, jadi peluaran 60° dan n = 360/60 = 6. Paksi simetri = 6.",
    "Its angle is 2(60°) = 120°, so exterior is 60° and n = 360/60 = 6. It has 6 axes.",
  ),

  // Determine polygon from partial information (6)
  q(
    "Sebuah poligon sekata mempunyai sudut pedalaman dan peluaran dalam nisbah 7:2. Kenal pasti poligon itu.",
    "A regular polygon has interior-to-exterior angle ratio 7:2. Identify the polygon.",
    ["Nonagon sekata", "Regular nonagon"],
    [
      ["Heptagon sekata", "Regular heptagon"],
      ["Oktagon sekata", "Regular octagon"],
      ["Dekagon sekata", "Regular decagon"],
    ],
    "9 bahagian = 180°, jadi sudut peluaran = 40°. n = 360/40 = 9, iaitu nonagon.",
    "9 parts = 180°, so exterior angle = 40°. n = 360/40 = 9, a nonagon.",
  ),
  q(
    "Jumlah sudut pedalaman sebuah poligon ialah 2340°. Apakah nama poligon itu?",
    "A polygon's interior-angle sum is 2340°. What is the polygon called?",
    ["Pentadekagon", "Pentadecagon"],
    [
      ["Dodekagon", "Dodecagon"],
      ["Tetradekagon", "Tetradecagon"],
      ["Heksadekagon", "Hexadecagon"],
    ],
    "(n − 2)180 = 2340 memberi n − 2 = 13 dan n = 15, iaitu pentadekagon.",
    "(n − 2)180 = 2340 gives n − 2 = 13 and n = 15, a pentadecagon.",
  ),
  q(
    "Sebuah poligon sekata mempunyai dua kali bilangan paksi simetri sebuah segi empat sama. Apakah poligon itu?",
    "A regular polygon has twice as many axes of symmetry as a square. What is it?",
    ["Oktagon sekata", "Regular octagon"],
    [
      ["Heksagon sekata", "Regular hexagon"],
      ["Dekagon sekata", "Regular decagon"],
      ["Dodekagon sekata", "Regular dodecagon"],
    ],
    "Segi empat sama mempunyai 4 paksi; dua kali 4 ialah 8, jadi oktagon sekata.",
    "A square has 4 axes; twice 4 is 8, so it is a regular octagon.",
  ),
  q(
    "Sebuah poligon sekata boleh dibahagi kepada 13 segi tiga dari satu bucu. Apakah sudut peluarannya?",
    "A regular polygon can be divided into 13 triangles from one vertex. What is its exterior angle?",
    "24°",
    ["12°", "26°", "30°"],
    "n − 2 = 13, jadi n = 15. Sudut peluaran = 360°/15 = 24°.",
    "n − 2 = 13, so n = 15. Exterior angle = 360°/15 = 24°.",
  ),
  q(
    "Sudut peluaran poligon sekata ialah 12°. Berapa segi tiga terbentuk dari satu bucu?",
    "A regular polygon's exterior angle is 12°. How many triangles form from one vertex?",
    "28",
    ["12", "18", "30"],
    "n = 360°/12° = 30. Bilangan segi tiga = n − 2 = 28.",
    "n = 360°/12° = 30. The number of triangles is n − 2 = 28.",
  ),
  q(
    "Satu sudut pedalaman poligon sekata ialah 165°. Adakah poligon itu wujud dengan bilangan sisi bulat?",
    "A regular polygon has an interior angle of 165°. Does it exist with a whole number of sides?",
    ["Ya, mempunyai 24 sisi", "Yes, it has 24 sides"],
    [
      ["Ya, mempunyai 12 sisi", "Yes, it has 12 sides"],
      ["Ya, mempunyai 15 sisi", "Yes, it has 15 sides"],
      ["Tidak, kerana 165° mustahil", "No, because 165° is impossible"],
    ],
    "Sudut peluaran = 15° dan 360°/15° = 24, suatu nombor bulat.",
    "Exterior angle = 15° and 360°/15° = 24, a whole number.",
  ),

  // Combined regular-polygon geometry (5)
  q(
    "Sebuah segi tiga sama sisi dan heksagon sekata berkongsi satu bucu. Berapakah beza sudut pedalaman mereka?",
    "An equilateral triangle and a regular hexagon share a vertex. What is the difference between their interior angles?",
    "60°",
    ["30°", "90°", "180°"],
    "Sudutnya 60° dan 120°; beza = 60°.",
    "Their angles are 60° and 120°; the difference is 60°.",
  ),
  q(
    "Tiga heksagon sekata bertemu pada satu titik. Adakah terdapat ruang di sekeliling titik itu?",
    "Three regular hexagons meet at one point. Is there a gap around the point?",
    ["Tidak, kerana 3 × 120° = 360°", "No, because 3 × 120° = 360°"],
    [
      ["Ya, ruang 60°", "Yes, a 60° gap"],
      ["Ya, ruang 120°", "Yes, a 120° gap"],
      ["Tidak, kerana setiap sudut 60°", "No, because each angle is 60°"],
    ],
    "Tiga sudut pedalaman 120° memenuhi 360° tepat.",
    "Three 120° interior angles fill 360° exactly.",
  ),
  q(
    "Sebuah segi empat sama dan dua oktagon sekata bertemu pada satu titik. Tentukan jumlah sudutnya.",
    "A square and two regular octagons meet at one point. Determine their angle sum.",
    "360°",
    ["315°", "405°", "450°"],
    "Sudut segi empat sama 90° dan oktagon 135°. Jumlah = 90° + 2(135°) = 360°.",
    "A square angle is 90° and an octagon angle is 135°. Sum = 90° + 2(135°) = 360°.",
  ),
  q(
    "Dua poligon sekata mempunyai sudut peluaran 30° dan 20°. Berapakah nisbah bilangan sisi pertama kepada kedua?",
    "Two regular polygons have exterior angles 30° and 20°. What is the ratio of the first side count to the second?",
    "2:3",
    ["3:2", "1:2", "3:4"],
    "Bilangan sisi ialah 12 dan 18. Nisbah 12:18 = 2:3.",
    "The side counts are 12 and 18. The ratio 12:18 = 2:3.",
  ),
  q(
    "Sudut pedalaman poligon sekata P ialah 108° dan Q ialah 135°. Cari jumlah paksi simetri kedua-duanya.",
    "Regular polygon P has interior angle 108° and Q has 135°. Find their total axes of symmetry.",
    "13",
    ["8", "10", "15"],
    "P ialah pentagon (5 paksi) dan Q ialah oktagon (8 paksi); jumlah = 13.",
    "P is a pentagon (5 axes) and Q an octagon (8 axes); total = 13.",
  ),

  // Diagram-style reasoning in text (5)
  q(
    "ABCDE ialah pentagon. Sudut luar di A, B, C dan D masing-masing 50°, 60°, 70° dan 80°. Cari sudut pedalaman di E.",
    "ABCDE is a pentagon. Exterior angles at A, B, C and D are 50°, 60°, 70° and 80°. Find the interior angle at E.",
    "80°",
    ["60°", "100°", "120°"],
    "Sudut luar E = 360° − 260° = 100°. Sudut dalam E = 180° − 100° = 80°.",
    "Exterior angle E = 360° − 260° = 100°. Interior angle E = 180° − 100° = 80°.",
  ),
  q(
    "PQRST ialah pentagon. Garis di Q dilanjutkan membentuk sudut peluaran 65°. Cari sudut pedalaman Q.",
    "PQRST is a pentagon. A side at Q is extended to form an exterior angle of 65°. Find the interior angle at Q.",
    "115°",
    ["65°", "125°", "295°"],
    "Sudut bersebelahan pada garis lurus berjumlah 180°: 180° − 65° = 115°.",
    "Adjacent angles on a straight line sum to 180°: 180° − 65° = 115°.",
  ),
  q(
    "Dalam heksagon ABCDEF, sudut A hingga E berjumlah 590°. Cari sudut F.",
    "In hexagon ABCDEF, angles A through E total 590°. Find angle F.",
    "130°",
    ["110°", "120°", "140°"],
    "Jumlah heksagon = 720°. Maka F = 720° − 590° = 130°.",
    "A hexagon's sum is 720°. Thus F = 720° − 590° = 130°.",
  ),
  q(
    "Dalam poligon sekata ABCDEFGH, pepenjuru dari A membahagi poligon kepada berapa segi tiga, dan berapa jumlah sudutnya?",
    "In regular polygon ABCDEFGH, diagonals from A divide it into how many triangles, and what is the angle sum?",
    ["6 segi tiga, 1080°", "6 triangles, 1080°"],
    [
      ["5 segi tiga, 900°", "5 triangles, 900°"],
      ["8 segi tiga, 1440°", "8 triangles, 1440°"],
      ["6 segi tiga, 720°", "6 triangles, 720°"],
    ],
    "Oktagon memberi 8 − 2 = 6 segi tiga dan jumlah 6 × 180° = 1080°.",
    "An octagon gives 8 − 2 = 6 triangles and sum 6 × 180° = 1080°.",
  ),
  q(
    "Poligon ABCD mempunyai sudut A = 2x°, B = (x + 20)°, C = 100° dan D = 90°. Cari sudut A.",
    "Quadrilateral ABCD has A = 2x°, B = (x + 20)°, C = 100° and D = 90°. Find angle A.",
    "100°",
    ["50°", "80°", "120°"],
    "2x + x + 20 + 100 + 90 = 360, jadi 3x = 150 dan x = 50. A = 100°.",
    "2x + x + 20 + 100 + 90 = 360, so 3x = 150 and x = 50. A = 100°.",
  ),

  // Real-world / KBAT (6)
  q(
    "Seorang pereka mahu jubin poligon sekata tunggal memenuhi lantai tanpa ruang. Antara sudut 108°, 120°, 135° dan 150°, yang manakah boleh bertemu tepat di satu titik menggunakan tiga jubin?",
    "A designer wants one type of regular polygon tile to fill a floor without gaps. Which angle among 108°, 120°, 135° and 150° can meet exactly at a point using three tiles?",
    "120°",
    ["108°", "135°", "150°"],
    "Tiga jubin mesti berjumlah 360°. Hanya 3 × 120° = 360°.",
    "Three tiles must total 360°. Only 3 × 120° = 360°.",
  ),
  q(
    "Sebuah roda berbentuk poligon sekata berputar 24° ketika bergolek dari satu sisi ke sisi seterusnya. Berapa sisi roda itu?",
    "A regular-polygon wheel turns 24° as it rolls from one side to the next. How many sides does it have?",
    "15",
    ["12", "18", "24"],
    "Putaran setiap sisi ialah sudut peluaran. n = 360°/24° = 15.",
    "The turn per side is the exterior angle. n = 360°/24° = 15.",
  ),
  q(
    "Sebuah astaka berbentuk poligon sekata mempunyai 18 tiang, satu di setiap bucu. Cari sudut pedalaman antara dua sisi bersebelahan.",
    "A regular-polygon pavilion has 18 pillars, one at each vertex. Find the interior angle between adjacent sides.",
    "160°",
    ["20°", "150°", "170°"],
    "Sudut peluaran = 360°/18 = 20°. Sudut pedalaman = 160°.",
    "Exterior angle = 360°/18 = 20°. Interior angle = 160°.",
  ),
  q(
    "Dua laluan poligon sekata mempunyai sudut peluaran yang nisbahnya 3:2. Jika laluan pertama mempunyai 8 sisi, berapa sisi laluan kedua?",
    "Two regular-polygon paths have exterior angles in ratio 3:2. If the first has 8 sides, how many sides does the second have?",
    "12",
    ["6", "10", "16"],
    "Sudut pertama = 45°. Sudut kedua = 30°. Maka sisinya = 360°/30° = 12.",
    "First exterior angle = 45°. The second is 30°. Thus its side count is 360°/30° = 12.",
  ),
  q(
    "Sebuah corak menggunakan dua segi tiga sama sisi dan dua poligon sekata yang sama pada satu titik. Apakah poligon sekata itu jika tiada ruang?",
    "A pattern uses two equilateral triangles and two identical regular polygons at a point. What are the regular polygons if there is no gap?",
    ["Heksagon sekata", "Regular hexagons"],
    [
      ["Segi empat sama", "Squares"],
      ["Pentagon sekata", "Regular pentagons"],
      ["Oktagon sekata", "Regular octagons"],
    ],
    "Baki sudut = 360° − 2(60°) = 240°. Setiap poligon mempunyai sudut 120°, iaitu heksagon sekata.",
    "Remaining angle = 360° − 2(60°) = 240°. Each polygon has angle 120°, so they are regular hexagons.",
  ),
  q(
    "Seorang murid mendakwa poligon sekata boleh mempunyai sudut peluaran 28°. Nilai dakwaan itu.",
    "A student claims a regular polygon can have an exterior angle of 28°. Assess the claim.",
    ["Salah, kerana 360 ÷ 28 bukan nombor bulat", "False, because 360 ÷ 28 is not a whole number"],
    [
      ["Betul, kerana 28° kurang daripada 180°", "True, because 28° is less than 180°"],
      ["Betul, kerana jumlah pedalaman ialah 360°", "True, because the interior sum is 360°"],
      [
        "Salah, kerana sudut peluaran mesti melebihi 30°",
        "False, because an exterior angle must exceed 30°",
      ],
    ],
    "Bilangan sisi mesti 360°/28° = 12.857…, bukan nombor bulat; maka tidak mungkin.",
    "The side count would be 360°/28° = 12.857…, not a whole number; therefore it is impossible.",
  ),
];
