import type { StructuredNotes } from "@/data/types";

export const sejarahF3C6Notes: StructuredNotes = {
  chapterSummary: "Bab ini menerangkan pengenalan ekonomi moden oleh kuasa Barat, pentadbiran Barat berkaitan ekonomi serta kesan ekonomi dan sosial akibat perkembangan ekonomi kolonial.",
  quickRevision: ["6.1 Pengenalan Ekonomi Moden oleh Kuasa Barat di Negara Kita: Kuasa Barat memperkenalkan ekonomi moden berasaskan modal besar, teknologi dan eksport.","Tarikh penting 6.1: Abad ke-19: ekonomi moden berkembang","6.2 Pentadbiran Barat Berkaitan dengan Ekonomi: Pentadbiran Barat menggubal dasar tanah, buruh dan kewangan untuk menyokong ekonomi kolonial.","Tarikh penting 6.2: 1913: Akta Tanah Simpanan Melayu diperkenalkan","6.3 Kesan Ekonomi Akibat Pentadbiran Barat di Negara Kita: British membina landasan kereta api untuk menghubungkan kawasan lombong dengan pelabuhan.","Tarikh penting 6.3: 1885-1896: fasa pertama kereta api","6.4 Kesan Sosial Akibat Perkembangan Ekonomi di Negara Kita: Perkembangan ekonomi membawa kepada kemunculan bandar baharu.","Tarikh penting 6.4: Awal abad ke-20: bandar dan perkhidmatan sosial berkembang"],
  keyTerms: ["ekonomi moden","modal","eksport","getah","bijih timah","petroleum","tanah","buruh","cukai","Akta Tanah Simpanan Melayu","ekonomi kolonial","kereta api","jalan raya","pelabuhan","telegraf","telefon","pos","bandar","masyarakat majmuk","pendidikan vernakular","kesihatan","telekomunikasi"],
  keyExamFacts: ["Kuasa Barat memperkenalkan ekonomi moden berasaskan modal besar, teknologi dan eksport.","Tanaman komersial seperti getah, tebu, tembakau dan padi berorientasikan eksport berkembang.","Bijih timah, bijih besi, emas, petroleum dan arang batu menjadi hasil penting.","Pentadbiran Barat menggubal dasar tanah, buruh dan kewangan untuk menyokong ekonomi kolonial.","Akta Tanah Simpanan Melayu diperkenalkan bagi melindungi tanah orang Melayu.","Sistem cukai dan peraturan tanah mengubah hubungan masyarakat dengan tanah.","British membina landasan kereta api untuk menghubungkan kawasan lombong dengan pelabuhan.","Fasa kereta api 1885-1896 menghubungkan lombong dengan pelabuhan.","Fasa 1897-1909 menghubungkan utara dan selatan Tanah Melayu selepas NNMB dibentuk.","Perkembangan ekonomi membawa kepada kemunculan bandar baharu.","Kemasukan buruh luar membentuk masyarakat majmuk.","Pendidikan vernakular, sekolah Melayu dan sekolah agama berkembang mengikut komuniti."],
  sections: [
    {
      title: "Bab Overview",
      subsections: [
        { title: "Sinopsis", content: "Bab ini menerangkan pengenalan ekonomi moden oleh kuasa Barat, pentadbiran Barat berkaitan ekonomi serta kesan ekonomi dan sosial akibat perkembangan ekonomi kolonial." },
        { title: "Apa yang akan dipelajari", bulletPoints: ["6.1 Pengenalan Ekonomi Moden oleh Kuasa Barat di Negara Kita","6.2 Pentadbiran Barat Berkaitan dengan Ekonomi","6.3 Kesan Ekonomi Akibat Pentadbiran Barat di Negara Kita","6.4 Kesan Sosial Akibat Perkembangan Ekonomi di Negara Kita"] },
        { title: "Fokus UASA", bulletPoints: ["Kenal pasti kronologi, tokoh, tempat, perjanjian dan kesan.","Bezakan sebab, strategi dan kesan peluasan kuasa Barat.","Gunakan kata kunci seperti kedaulatan, pentadbiran, ekonomi, penentangan dan pemodenan."] },
      ],
    },
    {
      title: "6.1 Pengenalan Ekonomi Moden oleh Kuasa Barat di Negara Kita",
      subsections: [
        { title: "Ringkasan", content: "Pengenalan Ekonomi Moden oleh Kuasa Barat di Negara Kita menerangkan kuasa barat memperkenalkan ekonomi moden berasaskan modal besar, teknologi dan eksport. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Kuasa Barat memperkenalkan ekonomi moden berasaskan modal besar, teknologi dan eksport.","Tanaman komersial seperti getah, tebu, tembakau dan padi berorientasikan eksport berkembang.","Bijih timah, bijih besi, emas, petroleum dan arang batu menjadi hasil penting.","SBUB melakukan pelaburan dalam tanaman getah di Sabah seperti Bongaya dan Sungai Labuk."] },
        { title: "Kata kunci", bulletPoints: ["ekonomi moden","modal","eksport","getah","bijih timah","petroleum"] },
        { title: "Tokoh penting", bulletPoints: ["Pelabur Barat","SBUB","Pentadbir British"] },
        { title: "Tarikh penting", bulletPoints: ["Abad ke-19: ekonomi moden berkembang","Selepas 1840: permintaan bijih timah meningkat"] },
        { title: "Tempat penting", bulletPoints: ["Negeri-negeri Melayu","Sarawak","Sabah","Bongaya","Sungai Labuk"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Permintaan bahan mentah dunia","Revolusi Perindustrian","Modal Barat","Kesuburan tanah dan kekayaan hasil bumi"] },
        { title: "Kesan", bulletPoints: ["Pertanian komersial berkembang","Perlombongan diperluas","Buruh luar dibawa masuk","Ekonomi tradisional berubah"] },
        { title: "Kepentingan", bulletPoints: ["Menerangkan asas perubahan ekonomi negara akibat pentadbiran Barat."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Ekonomi moden membawa kepada pembinaan infrastruktur dan perubahan sosial."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta kawasan getah dan lombong menunjukkan tumpuan ekonomi eksport.","Abad ke-19 hingga awal abad ke-20: ekonomi eksport berkembang pesat"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "6.2 Pentadbiran Barat Berkaitan dengan Ekonomi",
      subsections: [
        { title: "Ringkasan", content: "Pentadbiran Barat Berkaitan dengan Ekonomi menerangkan pentadbiran barat menggubal dasar tanah, buruh dan kewangan untuk menyokong ekonomi kolonial. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Pentadbiran Barat menggubal dasar tanah, buruh dan kewangan untuk menyokong ekonomi kolonial.","Akta Tanah Simpanan Melayu diperkenalkan bagi melindungi tanah orang Melayu.","Sistem cukai dan peraturan tanah mengubah hubungan masyarakat dengan tanah.","Kemasukan buruh luar diurus untuk memenuhi keperluan lombong dan ladang."] },
        { title: "Kata kunci", bulletPoints: ["tanah","buruh","cukai","Akta Tanah Simpanan Melayu","ekonomi kolonial"] },
        { title: "Tokoh penting", bulletPoints: ["Pentadbir British","Pemodal Eropah","Buruh Cina","Buruh India"] },
        { title: "Tarikh penting", bulletPoints: ["1913: Akta Tanah Simpanan Melayu diperkenalkan"] },
        { title: "Tempat penting", bulletPoints: ["Tanah Melayu","Sarawak","Sabah","kawasan lombong","ladang getah"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Akta Tanah Simpanan Melayu; peraturan tanah; peraturan buruh"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Keperluan mengawal tanah dan tenaga kerja","Perkembangan lombong dan ladang","Kepentingan hasil eksport"] },
        { title: "Kesan", bulletPoints: ["Tanah dikategorikan mengikut kepentingan ekonomi","Buruh luar meningkat","Masyarakat tempatan semakin terikat dengan sistem pentadbiran Barat"] },
        { title: "Kepentingan", bulletPoints: ["Menunjukkan ekonomi kolonial dikawal melalui undang-undang dan pentadbiran."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Dasar ekonomi Barat membawa kepada kesan sosial seperti kemunculan bandar dan masyarakat majmuk."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Rajah dasar tanah dan buruh menerangkan bagaimana pentadbiran Barat menyokong ekonomi eksport.","Awal abad ke-20: dasar tanah dan buruh kolonial diperkukuh"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "6.3 Kesan Ekonomi Akibat Pentadbiran Barat di Negara Kita",
      subsections: [
        { title: "Ringkasan", content: "Kesan Ekonomi Akibat Pentadbiran Barat di Negara Kita menerangkan british membina landasan kereta api untuk menghubungkan kawasan lombong dengan pelabuhan. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["British membina landasan kereta api untuk menghubungkan kawasan lombong dengan pelabuhan.","Fasa kereta api 1885-1896 menghubungkan lombong dengan pelabuhan.","Fasa 1897-1909 menghubungkan utara dan selatan Tanah Melayu selepas NNMB dibentuk.","Fasa 1910-1931 menghubungkan seluruh Tanah Melayu selepas pengaruh British meluas ke NNMTB.","Jalan raya, pelabuhan, lapangan terbang awam dan telekomunikasi seperti telegraf, telefon dan pos berkembang."] },
        { title: "Kata kunci", bulletPoints: ["kereta api","jalan raya","pelabuhan","telegraf","telefon","pos"] },
        { title: "Tokoh penting", bulletPoints: ["Pentadbir British","Pengusaha lombong","Pengusaha ladang"] },
        { title: "Tarikh penting", bulletPoints: ["1885-1896: fasa pertama kereta api","1897-1909: fasa kedua","1910-1931: fasa ketiga"] },
        { title: "Tempat penting", bulletPoints: ["Port Weld","Taiping","Kuala Lumpur","Port Swettenham","Gemas","Padang Besar","Kota Bharu"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Keperluan mengangkut bijih timah dan getah","Pertumbuhan ekonomi eksport","Keperluan menghubungkan kawasan pengeluaran dengan pelabuhan"] },
        { title: "Kesan", bulletPoints: ["Pengangkutan moden berkembang","Bandar dan pelabuhan maju","Eksport bahan mentah lebih cepat","Telekomunikasi memudahkan pentadbiran"] },
        { title: "Kepentingan", bulletPoints: ["Infrastruktur moden ialah kesan langsung ekonomi kolonial."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Pengangkutan dan telekomunikasi mempercepat eksploitasi ekonomi serta perubahan sosial."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta landasan kereta api menunjukkan hubungan kawasan lombong, ladang dan pelabuhan.","1885-1896","1897-1909","1910-1931"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "6.4 Kesan Sosial Akibat Perkembangan Ekonomi di Negara Kita",
      subsections: [
        { title: "Ringkasan", content: "Kesan Sosial Akibat Perkembangan Ekonomi di Negara Kita menerangkan perkembangan ekonomi membawa kepada kemunculan bandar baharu. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Perkembangan ekonomi membawa kepada kemunculan bandar baharu.","Kemasukan buruh luar membentuk masyarakat majmuk.","Pendidikan vernakular, sekolah Melayu dan sekolah agama berkembang mengikut komuniti.","Perkhidmatan kesihatan, hospital, sistem pos, telegraf dan telefon diperkenalkan.","SBUB membuka sekolah Melayu di Papar."] },
        { title: "Kata kunci", bulletPoints: ["bandar","masyarakat majmuk","pendidikan vernakular","kesihatan","telekomunikasi"] },
        { title: "Tokoh penting", bulletPoints: ["Pentadbir British","Masyarakat Melayu","Masyarakat Cina","Masyarakat India","SBUB"] },
        { title: "Tarikh penting", bulletPoints: ["Awal abad ke-20: bandar dan perkhidmatan sosial berkembang"] },
        { title: "Tempat penting", bulletPoints: ["Kuala Lumpur","Ipoh","Taiping","Papar","Sarawak","Sabah"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Perkembangan lombong dan ladang","Kemasukan buruh luar","Pembinaan infrastruktur","Keperluan pentadbiran kolonial"] },
        { title: "Kesan", bulletPoints: ["Bandar berkembang","Masyarakat majmuk terbentuk","Pendidikan terpisah mengikut kaum","Perkhidmatan sosial moden diperkenalkan"] },
        { title: "Kepentingan", bulletPoints: ["Menjelaskan asal usul perubahan sosial moden di negara kita."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Kesan sosial berpunca daripada keperluan ekonomi Barat, bukan semata-mata kebajikan masyarakat tempatan."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta bandar baharu menunjukkan kawasan yang berkembang akibat perlombongan, ladang dan pelabuhan.","Akhir abad ke-19 hingga awal abad ke-20: perubahan sosial semakin jelas"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "Rumusan Bab",
      subsections: [
        { title: "Imbas Kembali", bulletPoints: ["6.1: ekonomi moden, modal, eksport, getah","6.2: tanah, buruh, cukai, Akta Tanah Simpanan Melayu","6.3: kereta api, jalan raya, pelabuhan, telegraf","6.4: bandar, masyarakat majmuk, pendidikan vernakular, kesihatan"] },
        { title: "Kata Kunci Peperiksaan", bulletPoints: ["ekonomi moden","modal","eksport","getah","bijih timah","petroleum","tanah","buruh","cukai","Akta Tanah Simpanan Melayu","ekonomi kolonial","kereta api","jalan raya","pelabuhan","telegraf","telefon","pos","bandar","masyarakat majmuk","pendidikan vernakular","kesihatan","telekomunikasi"] },
      ],
    }
  ],
};
