import type { QuizQuestion } from "@/data/content";

export const mathF2C2FoundationQuizzesDLP: QuizQuestion[] = [
  {
    id: "DLP-F1",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "What does the expansion of an algebraic expression mean?",
    options: [
      "Writing an expression as a product of factors",
      "Multiplying a term by the expression inside brackets and simplifying",
      "Dividing every term by a variable",
      "Substituting a number for a variable",
    ],
    answerIndex: 1,
    explanation:
      "Expansion multiplies the term outside the brackets by every term inside before simplifying.",
  },
  {
    id: "DLP-F2",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand 3(x + 4).",
    options: ["3x + 4", "3x + 7", "3x + 12", "12x"],
    answerIndex: 2,
    explanation: "Expand each set of brackets and combine like terms to obtain 3x + 12.",
  },
  {
    id: "DLP-F3",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand −2(a − 5).",
    options: ["−2a − 10", "−2a + 10", "2a − 10", "2a + 10"],
    answerIndex: 1,
    explanation: "Expand each set of brackets and combine like terms to obtain −2a + 10.",
  },
  {
    id: "DLP-F4",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand 4m(2m + 3).",
    options: ["8m² + 12m", "8m² + 3", "6m² + 12m", "8m + 12"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain 8m² + 12m.",
  },
  {
    id: "DLP-F5",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (x + 2)(x + 3).",
    options: ["x² + 6", "x² + 5x + 6", "x² + 6x + 5", "x² + x + 6"],
    answerIndex: 1,
    explanation: "Expand each set of brackets and combine like terms to obtain x² + 5x + 6.",
  },
  {
    id: "DLP-F6",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (y − 4)(y + 2).",
    options: ["y² − 2y − 8", "y² + 2y − 8", "y² − 6y + 8", "y² − 8"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain y² − 2y − 8.",
  },
  {
    id: "DLP-F7",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (a + 5)².",
    options: ["a² + 25", "a² + 5a + 25", "a² + 10a + 25", "a² + 10a + 10"],
    answerIndex: 2,
    explanation: "Expand each set of brackets and combine like terms to obtain a² + 10a + 25.",
  },
  {
    id: "DLP-F8",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (p − 3)².",
    options: ["p² − 9", "p² − 6p + 9", "p² − 3p + 9", "p² + 6p + 9"],
    answerIndex: 1,
    explanation: "Expand each set of brackets and combine like terms to obtain p² − 6p + 9.",
  },
  {
    id: "DLP-F9",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (m + 7)(m − 7).",
    options: ["m² − 14m + 49", "m² + 49", "m² − 49", "m² + 14m − 49"],
    answerIndex: 2,
    explanation: "Expand each set of brackets and combine like terms to obtain m² − 49.",
  },
  {
    id: "DLP-F10",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 2(3x − 1) + 4(x + 2).",
    options: ["10x + 6", "10x − 6", "7x + 8", "8x + 6"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain 10x + 6.",
  },
  {
    id: "DLP-F11",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorisation is:",
    options: [
      "the same process as expansion",
      "the inverse process of expansion",
      "a process unrelated to expansion",
      "a process for numbers only",
    ],
    answerIndex: 1,
    explanation:
      "Factorisation is the inverse of expansion because it rewrites an expression as a product of factors.",
  },
  {
    id: "DLP-F12",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Find the HCF of 12x and 18x².",
    options: ["2x", "3x", "6x", "6x²"],
    answerIndex: 2,
    explanation:
      "Take the greatest numerical factor and the lowest common variable powers. The HCF is 6x.",
  },
  {
    id: "DLP-F13",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 8a + 12.",
    options: ["2(4a + 6)", "4(2a + 3)", "8(a + 12)", "4(a + 3)"],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is 4(2a + 3).",
  },
  {
    id: "DLP-F14",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise completely 15m² − 20m.",
    options: ["5m(3m − 4)", "5(3m² − 4m)", "m(15m − 20)", "10m(m − 2)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is 5m(3m − 4).",
  },
  {
    id: "DLP-F15",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise x² + 7x + 12.",
    options: ["(x + 2)(x + 6)", "(x + 3)(x + 4)", "(x − 3)(x − 4)", "(x + 1)(x + 12)"],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x + 3)(x + 4).",
  },
  {
    id: "DLP-F16",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise x² − 9x + 20.",
    options: ["(x − 4)(x − 5)", "(x + 4)(x + 5)", "(x − 2)(x − 10)", "(x + 2)(x − 10)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x − 4)(x − 5).",
  },
  {
    id: "DLP-F17",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise x² − 25.",
    options: ["(x − 5)²", "(x + 5)²", "(x − 5)(x + 5)", "x(x − 25)"],
    answerIndex: 2,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x − 5)(x + 5).",
  },
  {
    id: "DLP-F18",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise x² + 10x + 25.",
    options: ["(x + 5)²", "(x − 5)²", "(x + 25)(x + 1)", "x(x + 10) + 25"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x + 5)².",
  },
  {
    id: "DLP-F19",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise completely 4y² − 36.",
    options: ["4(y − 9)(y + 9)", "4(y − 3)(y + 3)", "2(y − 6)(y + 6)", "(2y − 6)²"],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is 4(y − 3)(y + 3).",
  },
  {
    id: "DLP-F20",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 2x² + 7x + 3.",
    options: ["(2x + 1)(x + 3)", "(2x + 3)(x + 1)", "(x + 1)(x + 6)", "(2x − 1)(x − 3)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (2x + 1)(x + 3).",
  },
  {
    id: "DLP-F21",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "In the algebraic fraction (x + 3)/5, what is the numerator?",
    options: ["5", "x", "x + 3", "3"],
    answerIndex: 2,
    explanation: "The numerator is the expression above the fraction bar, x + 3.",
  },
  {
    id: "DLP-F22",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "In 3/(4y), what is the denominator?",
    options: ["3", "4", "y", "4y"],
    answerIndex: 3,
    explanation: "The denominator is the expression below the fraction bar, 4y.",
  },
  {
    id: "DLP-F23",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 6x/9.",
    options: ["2x/3", "3x/2", "2x/9", "x/3"],
    answerIndex: 0,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 2x/3.",
  },
  {
    id: "DLP-F24",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify a/5 + 2a/5.",
    options: ["2a/10", "3a/5", "3a/10", "a/5"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 3a/5.",
  },
  {
    id: "DLP-F25",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 7b/8 − 3b/8.",
    options: ["b/2", "b/4", "5b/8", "4b"],
    answerIndex: 0,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is b/2.",
  },
  {
    id: "DLP-F26",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 1/x + 2/x, where x ≠ 0.",
    options: ["2/x", "3/x", "3/(2x)", "1/(3x)"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 3/x.",
  },
  {
    id: "DLP-F27",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 3/(2m) + 1/(2m), where m ≠ 0.",
    options: ["1/m", "2/m", "4/m", "2/(3m)"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 2/m.",
  },
  {
    id: "DLP-F28",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (x/3)(6/x), where x ≠ 0.",
    options: ["1", "2", "3", "6"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 2.",
  },
  {
    id: "DLP-F29",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (8a/5) ÷ (4a/15), where a ≠ 0.",
    options: ["3", "4", "6", "8"],
    answerIndex: 2,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 6.",
  },
  {
    id: "DLP-F30",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (x² − 9)/(x − 3), where x ≠ 3.",
    options: ["x − 3", "x + 3", "x² + 3", "1"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is x + 3.",
  },
];

export const mathF2C2PracticeQuizzesDLP: QuizQuestion[] = [
  {
    id: "DLP-P1",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 5(2x − 3) − 2(x + 4).",
    options: ["8x − 23", "8x − 7", "12x − 23", "12x − 7"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain 8x − 23.",
  },
  {
    id: "DLP-P2",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (2a + 3)(a − 4).",
    options: ["2a² − 5a − 12", "2a² + 5a − 12", "2a² − 8a + 3", "2a² − a − 12"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain 2a² − 5a − 12.",
  },
  {
    id: "DLP-P3",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (3m − 2)².",
    options: ["9m² − 4", "9m² − 6m + 4", "9m² − 12m + 4", "6m² − 12m + 4"],
    answerIndex: 2,
    explanation: "Expand each set of brackets and combine like terms to obtain 9m² − 12m + 4.",
  },
  {
    id: "DLP-P4",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Expand (4p + 1)(4p − 1).",
    options: ["16p² − 1", "16p² + 1", "8p² − 1", "16p² − 8p + 1"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain 16p² − 1.",
  },
  {
    id: "DLP-P5",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (x + 5)(x − 2) + (x − 1)(x + 2).",
    options: ["2x² + 4x − 12", "2x² + 2x − 8", "x² + 4x − 12", "2x² + 6x − 10"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain 2x² + 4x − 12.",
  },
  {
    id: "DLP-P6",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "A rectangle has length (3x + 2) cm and width (x + 4) cm. What is its area?",
    options: ["3x² + 8", "3x² + 14x + 8", "3x² + 12x + 8", "4x² + 14x + 8"],
    answerIndex: 1,
    explanation: "Expand each set of brackets and combine like terms to obtain 3x² + 14x + 8.",
  },
  {
    id: "DLP-P7",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "A square has side length (2y − 3) cm. What is its area?",
    options: ["4y² − 9", "4y² − 6y + 9", "4y² − 12y + 9", "2y² − 12y + 9"],
    answerIndex: 2,
    explanation: "Expand each set of brackets and combine like terms to obtain 4y² − 12y + 9.",
  },
  {
    id: "DLP-P8",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 3a(a + 2) − a(a − 5).",
    options: ["2a² + a", "2a² + 11a", "4a² + 11a", "2a² − 11a"],
    answerIndex: 1,
    explanation: "Expand each set of brackets and combine like terms to obtain 2a² + 11a.",
  },
  {
    id: "DLP-P9",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify −2x(3x − 4) + 5x(x + 1).",
    options: ["−x² + 13x", "x² + 13x", "−x² + 3x", "11x² + 13x"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain −x² + 13x.",
  },
  {
    id: "DLP-P10",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (2m + 5)(m + 3) − (m + 1)(m + 2).",
    options: ["m² + 8m + 13", "m² + 7m + 13", "3m² + 8m + 17", "m² + 8m + 17"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain m² + 8m + 13.",
  },
  {
    id: "DLP-P11",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Find the HCF of 18x²y and 24xy².",
    options: ["3xy", "6xy", "6x²y²", "12xy"],
    answerIndex: 1,
    explanation:
      "Take the greatest numerical factor and the lowest common variable powers. The HCF is 6xy.",
  },
  {
    id: "DLP-P12",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise completely 14a²b − 21ab².",
    options: ["7ab(2a − 3b)", "7ab(2a + 3b)", "7a(2ab − 3b²)", "ab(14a − 21b)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is 7ab(2a − 3b).",
  },
  {
    id: "DLP-P13",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 3x² + 12x.",
    options: ["3x(x + 4)", "3(x² + 4x)", "x(3x + 12)", "3x(x + 12)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is 3x(x + 4).",
  },
  {
    id: "DLP-P14",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise x² + 11x + 30.",
    options: ["(x + 3)(x + 10)", "(x + 5)(x + 6)", "(x − 5)(x − 6)", "(x + 2)(x + 15)"],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x + 5)(x + 6).",
  },
  {
    id: "DLP-P15",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise x² − 2x − 35.",
    options: ["(x − 5)(x + 7)", "(x − 7)(x + 5)", "(x + 7)(x + 5)", "(x − 7)(x − 5)"],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x − 7)(x + 5).",
  },
  {
    id: "DLP-P16",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 2x² + 9x + 4.",
    options: ["(2x + 1)(x + 4)", "(2x + 4)(x + 1)", "(x + 2)(x + 4)", "(2x − 1)(x − 4)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (2x + 1)(x + 4).",
  },
  {
    id: "DLP-P17",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 3m² − 13m + 4.",
    options: ["(3m + 1)(m − 4)", "(3m − 1)(m − 4)", "(3m − 4)(m − 1)", "(m − 3)(m − 4)"],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (3m − 1)(m − 4).",
  },
  {
    id: "DLP-P18",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 9a² − 24a + 16.",
    options: ["(3a − 4)²", "(3a + 4)²", "(9a − 4)(a − 4)", "(3a − 8)(3a − 2)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (3a − 4)².",
  },
  {
    id: "DLP-P19",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 25p² − 49q².",
    options: ["(5p − 7q)²", "(5p + 7q)²", "(5p − 7q)(5p + 7q)", "(25p − 49q)(p + q)"],
    answerIndex: 2,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (5p − 7q)(5p + 7q).",
  },
  {
    id: "DLP-P20",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise ax + ay + bx + by.",
    options: ["(a + b)(x + y)", "(a + x)(b + y)", "ab(x + y)", "xy(a + b)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (a + b)(x + y).",
  },
  {
    id: "DLP-P21",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 3x/4 + x/6.",
    options: ["5x/10", "11x/12", "4x/10", "7x/12"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 11x/12.",
  },
  {
    id: "DLP-P22",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 5a/6 − a/4.",
    options: ["7a/12", "a/2", "4a/12", "9a/12"],
    answerIndex: 0,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 7a/12.",
  },
  {
    id: "DLP-P23",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 2/m + 3/(2m), where m ≠ 0.",
    options: ["5/(2m)", "7/(2m)", "5/m", "7/m"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 7/(2m).",
  },
  {
    id: "DLP-P24",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify x/3 + y/6.",
    options: ["(x + y)/9", "(2x + y)/6", "(x + 2y)/6", "(2x + 2y)/6"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is (2x + y)/6.",
  },
  {
    id: "DLP-P25",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 5/(2a) − 1/(3a), where a ≠ 0.",
    options: ["4/(5a)", "13/(6a)", "14/(6a)", "3/a"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 13/(6a).",
  },
  {
    id: "DLP-P26",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (3x/4)(8/(9x)), where x ≠ 0.",
    options: ["1/3", "2/3", "3/2", "2"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 2/3.",
  },
  {
    id: "DLP-P27",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (5a/6) ÷ (10a/9), where a ≠ 0.",
    options: ["2/3", "3/4", "4/3", "5/6"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 3/4.",
  },
  {
    id: "DLP-P28",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (x² − 16)/(x − 4), where x ≠ 4.",
    options: ["x − 4", "x + 4", "x² + 4", "4"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is x + 4.",
  },
  {
    id: "DLP-P29",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (a² − 9)/(a + 3), where a ≠ −3.",
    options: ["a + 3", "a − 3", "a² − 3", "1"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is a − 3.",
  },
  {
    id: "DLP-P30",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (x² + 5x + 6)/(x + 2), where x ≠ −2.",
    options: ["x + 2", "x + 3", "x + 5", "x + 6"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is x + 3.",
  },
];

export const mathF2C2ChallengeQuizzesDLP: QuizQuestion[] = [
  {
    id: "DLP-C1",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 2(x − 3)² − (x + 1)(x − 1).",
    options: ["x² − 12x + 19", "x² − 6x + 19", "3x² − 12x + 17", "x² − 12x + 17"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain x² − 12x + 19.",
  },
  {
    id: "DLP-C2",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (2a − 3)(a + 4) + (a − 2)².",
    options: ["3a² + a − 8", "3a² − a − 8", "2a² + a − 8", "3a² + 9a − 8"],
    answerIndex: 0,
    explanation: "Expand each set of brackets and combine like terms to obtain 3a² + a − 8.",
  },
  {
    id: "DLP-C3",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "A rectangle has length (3x + 2) cm and width (x − 1) cm. What is its perimeter?",
    options: ["4x + 1", "6x + 2", "8x + 2", "8x − 2"],
    answerIndex: 2,
    explanation: "Expand each set of brackets and combine like terms to obtain 8x + 2.",
  },
  {
    id: "DLP-C4",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "A square region has side length (x + 5) m. A square of side x m is removed from its centre. What is the remaining area?",
    options: ["5x + 25", "10x + 25", "x² + 10x + 25", "25"],
    answerIndex: 1,
    explanation: "Expand each set of brackets and combine like terms to obtain 10x + 25.",
  },
  {
    id: "DLP-C5",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise completely 6x² − 15x.",
    options: ["3x(2x − 5)", "3(2x² − 5x)", "x(6x − 15)", "6x(x − 5)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is 3x(2x − 5).",
  },
  {
    id: "DLP-C6",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise x² + x − 20.",
    options: ["(x + 5)(x − 4)", "(x − 5)(x + 4)", "(x + 10)(x − 2)", "(x − 10)(x + 2)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x + 5)(x − 4).",
  },
  {
    id: "DLP-C7",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 6x² + x − 2.",
    options: ["(3x + 2)(2x − 1)", "(3x − 2)(2x + 1)", "(6x − 1)(x + 2)", "(2x + 2)(3x − 1)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (3x + 2)(2x − 1).",
  },
  {
    id: "DLP-C8",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise −2x² + 7x − 3.",
    options: ["(−2x + 1)(x − 3)", "(−2x − 1)(x + 3)", "(2x − 1)(x − 3)", "(−x + 1)(2x − 3)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (−2x + 1)(x − 3).",
  },
  {
    id: "DLP-C9",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 4a² − 12ab + 9b².",
    options: ["(2a − 3b)²", "(2a + 3b)²", "(4a − 3b)(a − 3b)", "(2a − 9b)(2a − b)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (2a − 3b)².",
  },
  {
    id: "DLP-C10",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 49m² − 81n².",
    options: ["(7m − 9n)²", "(7m − 9n)(7m + 9n)", "(49m − 81n)(m + n)", "(7m + 9n)²"],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (7m − 9n)(7m + 9n).",
  },
  {
    id: "DLP-C11",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Factorise 2ax + 2ay − 3bx − 3by.",
    options: ["(2a − 3b)(x + y)", "(2a + 3b)(x − y)", "(2a − 3b)(x − y)", "(a − b)(2x + 3y)"],
    answerIndex: 0,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (2a − 3b)(x + y).",
  },
  {
    id: "DLP-C12",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "The area of a rectangle is x² + 7x + 10. Which pair could represent its length and width?",
    options: [
      "(x + 1) and (x + 10)",
      "(x + 2) and (x + 5)",
      "(x − 2) and (x − 5)",
      "x and (x + 7)",
    ],
    answerIndex: 1,
    explanation:
      "Extract the common factor or find the appropriate factor pair. The complete factorisation is (x + 2) and (x + 5).",
  },
  {
    id: "DLP-C13",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (2x² − 7x + 3)/(x − 3), where x ≠ 3.",
    options: ["2x + 1", "2x − 1", "x − 3", "2x − 3"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 2x − 1.",
  },
  {
    id: "DLP-C14",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (x² − 9)/(x² − 6x + 9), where x ≠ 3.",
    options: ["(x − 3)/(x + 3)", "(x + 3)/(x − 3)", "x + 3", "1"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is (x + 3)/(x − 3).",
  },
  {
    id: "DLP-C15",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (a² − 4a + 4)/(a² − 4), where a ≠ ±2.",
    options: ["(a + 2)/(a − 2)", "(a − 2)/(a + 2)", "a − 2", "a + 2"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is (a − 2)/(a + 2).",
  },
  {
    id: "DLP-C16",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 2x/3 + (x − 1)/6.",
    options: ["(3x − 1)/6", "(5x − 1)/6", "(5x + 1)/6", "(4x − 1)/6"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is (5x − 1)/6.",
  },
  {
    id: "DLP-C17",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (3a + 1)/4 − (a − 2)/6.",
    options: ["(7a + 7)/12", "(7a − 7)/12", "(5a + 5)/12", "(11a − 1)/12"],
    answerIndex: 0,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is (7a + 7)/12.",
  },
  {
    id: "DLP-C18",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify x/(x + 1) + 2x/(x + 1), where x ≠ −1.",
    options: ["2x/(x + 1)", "3x/(x + 1)", "3x/(2x + 2)", "3/(x + 1)"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 3x/(x + 1).",
  },
  {
    id: "DLP-C19",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify [(x² − 9)/(x + 3)] × [2/(x − 3)], where x ≠ −3, 3.",
    options: ["1", "2", "x − 3", "x + 3"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 2.",
  },
  {
    id: "DLP-C20",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify [(a² − 25)/(a + 5)] ÷ [(a − 5)/3], where a ≠ −5, 5.",
    options: ["1", "2", "3", "a − 5"],
    answerIndex: 2,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 3.",
  },
  {
    id: "DLP-C21",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (3x² + 12x)/(3x), where x ≠ 0.",
    options: ["x + 3", "3x + 4", "x + 4", "3x + 12"],
    answerIndex: 2,
    explanation: "Factorise 3x² + 12x as 3x(x + 4), then cancel the factor 3x to obtain x + 4.",
  },
  {
    id: "DLP-C22",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify 2/x + 1/(2x) − 3/(4x), where x ≠ 0.",
    options: ["5/(4x)", "6/(4x)", "7/(4x)", "9/(4x)"],
    answerIndex: 2,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 7/(4x).",
  },
  {
    id: "DLP-C23",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (a/3)(9/a²), where a ≠ 0.",
    options: ["3a", "3/a", "9/a", "1/(3a)"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 3/a.",
  },
  {
    id: "DLP-C24",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify (4x² − 9)/(2x + 3), where 2x + 3 ≠ 0.",
    options: ["2x + 3", "2x − 3", "4x − 3", "x − 3"],
    answerIndex: 1,
    explanation:
      "Use a common denominator or factorise first, then cancel only permissible common factors. The lowest term is 2x − 3.",
  },
  {
    id: "DLP-C25",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "The area of a rectangle is x² + 6x + 8 and its width is (x + 2). What is its length?",
    options: ["x + 4", "x + 1", "x + 6", "x + 8"],
    answerIndex: 0,
    explanation: "x² + 6x + 8 = (x + 2)(x + 4). Since the width is x + 2, the length is x + 4.",
  },
  {
    id: "DLP-C26",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "One item costs RM(x + 2), while another costs RM(2x − 1). What is the total cost of three of the first item and two of the second?",
    options: ["RM(5x + 1)", "RM(7x + 4)", "RM(7x + 8)", "RM(6x + 4)"],
    answerIndex: 1,
    explanation: "Expand each set of brackets and combine like terms to obtain RM(7x + 4).",
  },
  {
    id: "DLP-C27",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "Amir is x years old. His sister is (x + 3) years old, and his father is twice his sister's age. What is their total age?",
    options: ["3x + 6", "4x + 6", "4x + 9", "5x + 9"],
    answerIndex: 2,
    explanation: "Expand each set of brackets and combine like terms to obtain 4x + 9.",
  },
  {
    id: "DLP-C28",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "A student writes (a + b)² = a² + b². Which is the correct expansion?",
    options: ["a² + 2ab + b²", "a² − 2ab + b²", "2a² + 2b²", "a² + ab + b²"],
    answerIndex: 0,
    explanation: "A squared binomial includes the middle term 2ab: (a + b)² = a² + 2ab + b².",
  },
  {
    id: "DLP-C29",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "The expression x² − 7x + 12 is factorised before substituting x = 5. What is its value?",
    options: ["0", "2", "4", "6"],
    answerIndex: 1,
    explanation: "x² − 7x + 12 = (x − 3)(x − 4). At x = 5, its value is 2 × 1 = 2.",
  },
  {
    id: "DLP-C30",
    subjectId: "math",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Simplify:\n\n(x² − 4x + 4)/(x − 2) + (x² − 9)/(x + 3),\n\nwhere x ≠ 2, −3.",
    options: ["2x − 5", "2x + 5", "x − 5", "2x − 1"],
    answerIndex: 0,
    explanation: "Factorise the numerators and cancel common factors: (x − 2) + (x − 3) = 2x − 5.",
  },
];

export const mathF2C2QuizzesDLP: QuizQuestion[] = [
  ...mathF2C2FoundationQuizzesDLP,
  ...mathF2C2PracticeQuizzesDLP,
  ...mathF2C2ChallengeQuizzesDLP,
];
