import type { Difficulty, QuizQuestion } from "@/data/content";
import { buildForm3MathQuizSets } from "../quiz-sets";
import { MATH_F3_C9_QUIZ_VISUALS } from "./quiz-visuals";
import { MATH_F3_C9_QUIZ_EXPLANATIONS } from "./quiz-explanations";
type QuizSeed = [Difficulty, string, [string, string, string, string], number];
function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c9-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    chapter: "Chapter 9",
    lang: "bm",
    difficulty,
    question,
    options,
    answerIndex,
    mathNotation: "indices",
    visual: MATH_F3_C9_QUIZ_VISUALS[index + 1],
    explanation: MATH_F3_C9_QUIZ_EXPLANATIONS[index + 1].bm,
  }));
}
export const mathF3C9QuestionBankBM: QuizQuestion[] = buildQuiz([
  [
    "Easy",
    "Dalam y=mx+c, apakah m?",
    ["Kecerunan", "Pintasan-y", "Pintasan-x", "Pemalar"],
    0,
  ],
  [
    "Easy",
    "Dalam y=mx+c, apakah c?",
    ["Pintasan-y", "Kecerunan", "Pintasan-x", "Sudut"],
    0,
  ],
  ["Easy", "Tentukan kecerunan bagi y=2x+9.", ["2", "9", "-2", "1/2"], 0],
  ["Easy", "Tentukan pintasan-y bagi y=2x+9.", ["9", "2", "0", "-9"], 0],
  [
    "Easy",
    "Dalam x/a+y/b=1, apakah a? Diberi a ≠ 0 dan b ≠ 0.",
    ["Pintasan-x", "Pintasan-y", "Kecerunan", "Pemalar"],
    0,
  ],
  [
    "Easy",
    "Dalam x/a+y/b=1, apakah b? Diberi a ≠ 0 dan b ≠ 0.",
    ["Pintasan-y", "Pintasan-x", "Kecerunan", "Pemalar"],
    0,
  ],
  ["Easy", "Apakah kecerunan garis y=6?", ["0", "6", "Tak tertakrif", "1"], 0],
  ["Easy", "Apakah kecerunan garis x=2?", ["Tak tertakrif", "0", "2", "1"], 0],
  [
    "Easy",
    "Garis y=h selari dengan paksi apa? Diberi h ≠ 0.",
    ["Paksi-x", "Paksi-y", "Kedua-duanya", "Tiada"],
    0,
  ],
  [
    "Easy",
    "Garis x=h selari dengan paksi apa? Diberi h ≠ 0.",
    ["Paksi-y", "Paksi-x", "Kedua-duanya", "Tiada"],
    0,
  ],
  [
    "Easy",
    "Dua garis lurus berbeza yang bukan mencancang adalah selari apabila syarat manakah dipenuhi?",
    [
      "Kecerunan sama",
      "Pintasan-y sama sahaja",
      "Pintasan-x sama sahaja",
      "Kecerunan berbeza",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah formula kecerunan dua titik (x₁,y₁) dan (x₂,y₂)? Diberi x₁ ≠ x₂.",
    [
      "(y₂-y₁)/(x₂-x₁)",
      "(x₂-x₁)/(y₂-y₁)",
      "(y₂+y₁)/(x₂+x₁)",
      "(y₂ − y₁) × (x₂ − x₁)",
    ],
    0,
  ],
  ["Easy", "3y=-2x+12. Apakah kecerunan?", ["-2/3", "2/3", "-3/2", "3/2"], 0],
  ["Easy", "3y=-2x+12. Apakah pintasan-y?", ["4", "12", "3", "-2"], 0],
  [
    "Easy",
    "Titik manakah terletak pada garis y = 3x + 2?",
    ["(1, 5)", "(1, 8)", "(2, 5)", "(3, 8)"],
    0,
  ],
  [
    "Easy",
    "Titik (k,8) terletak pada garis y = 3x + 2. Cari k.",
    ["2", "3", "6", "8"],
    0,
  ],
  [
    "Easy",
    "Cari titik persilangan garis y = x + 1 dan y = 3.",
    ["(2, 3)", "(3, 2)", "(1, 3)", "(2, 2)"],
    0,
  ],
  [
    "Easy",
    "Cari titik persilangan garis y = 2x dan x = 3.",
    ["(3, 6)", "(6, 3)", "(3, 3)", "(6, 6)"],
    0,
  ],
  [
    "Easy",
    "Cari pintasan-x bagi garis y = −2x + 5.",
    ["5/2", "−5/2", "5", "2"],
    0,
  ],
  [
    "Easy",
    "Cari kecerunan garis melalui P(1,2) dan Q(3,6).",
    ["2", "1/2", "4", "−2"],
    0,
  ],
  [
    "Medium",
    "Tukar 2x+3y=12 kepada bentuk x/a+y/b=1.",
    ["x/6 + y/4 = 1", "x/4 + y/6 = 1", "x/12 + y/12 = 1", "x/2 + y/3 = 1"],
    0,
  ],
  [
    "Medium",
    "Tukar 2x+3y=12 kepada y=mx+c.",
    ["y = (−2/3)x + 4", "y = (2/3)x + 4", "y = (−3/2)x + 6", "y = 2x + 12"],
    0,
  ],
  [
    "Medium",
    "Tukar x/6+y/3=1 kepada bentuk ax+by=c.",
    ["x + 2y = 6", "x + y = 9", "2x + y = 6", "x - 2y = 6"],
    0,
  ],
  [
    "Medium",
    "Tentukan kecerunan garis lurus 3x-4y=24.",
    ["3/4", "-3/4", "4/3", "-4/3"],
    0,
  ],
  [
    "Medium",
    "Titik (−4,k) terletak pada garis 3x − 2y = 12. Cari k.",
    ["−12", "12", "−6", "−16"],
    0,
  ],
  [
    "Medium",
    "Titik (k,−2) terletak pada garis x/3 + y/2 = 1. Cari k.",
    ["6", "−6", "3", "−3"],
    0,
  ],
  [
    "Medium",
    "Apakah kecerunan garis yang selari dengan 6x − 2y = 9?",
    ["3", "−3", "2", "−2"],
    0,
  ],
  [
    "Medium",
    "Dua garis mempunyai persamaan y = 3x + 8 dan 6y = 3x − 9. Pilih pasangan kecerunan dalam urutan itu.",
    ["(3, 1/2)", "(3, 2)", "(8, −9)", "(1/3, 1/2)"],
    0,
  ],
  [
    "Medium",
    "4x+3y=18 selari dengan 2x+hy=20. Cari h.",
    ["h = 3/2", "h = 2/3", "h = 3", "h = 1/2"],
    0,
  ],
  [
    "Medium",
    "Cari persamaan garis kecerunan 1/2 melalui P(6,8).",
    ["y = (1/2)x + 5", "y = (1/2)x + 8", "y = 2x + 5", "y = (1/2)x - 5"],
    0,
  ],
  [
    "Medium",
    "Cari persamaan garis melalui P(-1,5) dan Q(2,-7).",
    ["y = -4x + 1", "y = 4x + 1", "y = -4x - 1", "y = (−1/4)x + 1"],
    0,
  ],
  [
    "Medium",
    "Cari persamaan garis selari y=-2x+6 melalui P(5,4).",
    ["y = -2x + 14", "y = -2x + 6", "y = 2x + 14", "y = -2x - 14"],
    0,
  ],
  [
    "Medium",
    "Cari persamaan garis selari paksi-x melalui A(2,4) dan M(0,4).",
    ["y = 4", "x = 4", "y = 2x + 4", "x = 2"],
    0,
  ],
  [
    "Medium",
    "Cari persamaan garis selari paksi-y melalui A(2,4) dan N(2,0).",
    ["x = 2", "y = 2", "y = 4x", "x = 4"],
    0,
  ],
  [
    "Medium",
    "Cari titik persilangan 2x+y=5 dan x+2y=1.",
    ["(3, -1)", "(-1, 3)", "(1, 3)", "(3, 1)"],
    0,
  ],
  [
    "Medium",
    "Tentukan nilai k bagi pasangan garis selari y=-3x+4 dan y+kx=14.",
    ["k = 3", "k = -3", "k = 4", "k = 14"],
    0,
  ],
  [
    "Medium",
    "Tentukan nilai k bagi pasangan garis selari kx+2y=7 dan 6x+2y=15.",
    ["k = 6", "k = 7", "k = 2", "k = 15"],
    0,
  ],
  [
    "Medium",
    "3x+5y=15. Apakah pintasan-x (h)?",
    ["h = 5", "h = 3", "h = 15", "h = 1/5"],
    0,
  ],
  [
    "Medium",
    "Garis mempunyai persamaan 3x + 5y = 15. Cari pintasan-y, k.",
    ["k = 3", "k = 5", "k = 15", "k = 1/3"],
    0,
  ],
  [
    "Medium",
    "Daripada 3x+5y=15, jika titik (2,q) pada garis, cari q.",
    ["q = 9/5", "q = 5/9", "q = 3", "q = -9/5"],
    0,
  ],
  [
    "Hard",
    "Tukar y=-2x+8 kepada bentuk ax+by=c.",
    ["2x + y = 8", "-2x + y = 8", "2x - y = 8", "x + 2y = 8"],
    0,
  ],
  [
    "Hard",
    "Tukar y=3x+6 kepada bentuk x/a+y/b=1.",
    [
      "x/(-2) + y/6 = 1",
      "x/2 + y/6 = 1",
      "x/6 + y/2 = 1",
      "x/(-2) + y/(-6) = 1",
    ],
    0,
  ],
  [
    "Hard",
    "Garis lurus PQ: y=(1/3)x+2. Cari persamaan garis selari PQ melalui A(2,4).",
    ["y = (1/3)x + 10/3", "y = (1/3)x + 2", "y = 3x + 4", "y = (1/3)x - 10/3"],
    0,
  ],
  [
    "Hard",
    "Garis PQ mempunyai persamaan y = (1/3)x + 2. Cari persamaan garis selari PQ melalui asalan (0,0).",
    ["y = (1/3)x", "y = (1/3)x + 2", "x = 0", "y = 0"],
    0,
  ],
  [
    "Hard",
    "Cari titik persilangan y = x + 2 dan 2x + 3y = 6.",
    ["(0, 2)", "(2, 4)", "(−2, 0)", "(1, 3)"],
    0,
  ],
  [
    "Hard",
    "Garis 3y = −6x + 3 selari dengan kx + 2y = 10. Cari k.",
    ["4", "−4", "2", "−2"],
    0,
  ],
  [
    "Hard",
    "Cari titik persilangan garis 2x + 3y = 3 dan 2x + 6y = 12.",
    ["(−3, 3)", "(3, −3)", "(3, 3)", "(−3, −3)"],
    0,
  ],
  [
    "Hard",
    "Garis kx − 4y = 5 selari dengan y = (3/2)x + 1. Cari k.",
    ["6", "−6", "3/2", "−3/2"],
    0,
  ],
  [
    "Hard",
    "8y = 5x + 1 selari dengan kx − 3y = 8. Cari k.",
    ["15/8", "−15/8", "5/8", "−5/8"],
    0,
  ],
  [
    "Hard",
    "Dalam satah koordinat berunit meter, rumah P(0,0) dan Q(800,0) berada pada jalan lurus y = 0. Klinik sama jarak dari P dan Q, berjarak 600 m dari jalan dan berada di sebelah y > 0. Cari koordinat klinik.",
    ["(400, 600)", "(400, −600)", "(600, 400)", "(800, 600)"],
    0,
  ],
  [
    "Hard",
    "Garis ay = 6x − 9 mempunyai pintasan-y −3. Cari kecerunan garis itu.",
    ["2", "−2", "3", "−3"],
    0,
  ],
  [
    "Hard",
    "Garis y = 2x + c dan 3x + y = 11 bersilang pada (3,k). Cari c.",
    ["−4", "4", "2", "−2"],
    0,
  ],
  [
    "Hard",
    "Koordinat manakah memenuhi KEDUA-DUA persamaan 2x − y = 7 dan x + y = 5?",
    ["(4, 1)", "(1, 4)", "(3, 2)", "(2, 3)"],
    0,
  ],
]);
export const mathF3C9QuizzesBM: QuizQuestion[] = buildForm3MathQuizSets(
  9,
  mathF3C9QuestionBankBM,
);
