import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c9-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 9",
    lang: "dlp",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C9QuizzesDLP: QuizQuestion[] = buildQuiz([
  ["Easy", "In y=mx+c, what is m?", ["Gradient", "y-intercept", "x-intercept", "Constant"], 0],
  ["Easy", "In y=mx+c, what is c?", ["y-intercept", "Gradient", "x-intercept", "Angle"], 0],
  ["Easy", "Find the gradient of y=2x+9.", ["2", "9", "-2", "1/2"], 0],
  ["Easy", "Find the y-intercept of y=2x+9.", ["9", "2", "0", "-9"], 0],
  ["Easy", "In x/a+y/b=1, what is a?", ["x-intercept", "y-intercept", "Gradient", "Constant"], 0],
  ["Easy", "In x/a+y/b=1, what is b?", ["y-intercept", "x-intercept", "Gradient", "Constant"], 0],
  ["Easy", "What is the gradient of line y=6?", ["0", "6", "Undefined", "1"], 0],
  ["Easy", "What is the gradient of line x=2?", ["Undefined", "0", "2", "1"], 0],
  ["Easy", "Line y=h is parallel to which axis?", ["x-axis", "y-axis", "Both", "Neither"], 0],
  ["Easy", "Line x=h is parallel to which axis?", ["y-axis", "x-axis", "Both", "Neither"], 0],
  ["Easy", "Two straight lines are parallel if?", ["Equal gradients", "Equal y-intercepts", "Equal x-intercepts", "Equal lengths"], 0],
  ["Easy", "What is the gradient formula for two points (x1,y1) and (x2,y2)?", ["(y2-y1)/(x2-x1)", "(x2-x1)/(y2-y1)", "(y2+y1)/(x2+x1)", "(y2-y1)x(x2-x1)"], 0],
  ["Easy", "3y=-2x+12. What is the gradient?", ["-2/3", "2/3", "-3/2", "3/2"], 0],
  ["Easy", "3y=-2x+12. What is the y-intercept?", ["4", "12", "3", "-2"], 0],
  ["Easy", "How do you check if P(2,8) lies on y=3x+2?", ["Substitute x=2, check if y=8 makes both sides equal", "Just draw the graph", "Just estimate", "It cannot be checked"], 0],
  ["Easy", "P(2,8), y=3x+2. Does P lie on this line?", ["Yes (3(2)+2=8)", "No", "Cannot be determined", "Only if x=0"], 0],
  ["Easy", "What are the two methods to find the intersection of two lines?", ["Graphing and simultaneous equations", "Calculator only", "Estimation only", "Geometry only"], 0],
  ["Easy", "What are the two simultaneous equation methods?", ["Substitution and elimination", "Addition and subtraction only", "Multiplication and division only", "Drawing and measuring"], 0],
  ["Easy", "What must the coefficient of y be in y=mx+c?", ["+1", "-1", "0", "Any value"], 0],
  ["Easy", "Who is referred to as the father of Greek geometry in this chapter?", ["Euclid", "Pythagoras", "Archimedes", "Thales"], 0],

  ["Medium", "Convert 2x+3y=12 to the form x/a+y/b=1.", ["x/6 + y/4 = 1", "x/4 + y/6 = 1", "x/12 + y/12 = 1", "x/2 + y/3 = 1"], 0],
  ["Medium", "Convert 2x+3y=12 to y=mx+c.", ["y = -2/3x + 4", "y = 2/3x + 4", "y = -3/2x + 6", "y = 2x + 12"], 0],
  ["Medium", "Convert x/6+y/3=1 to the form ax+by=c.", ["x + 2y = 6", "x + y = 9", "2x + y = 6", "x - 2y = 6"], 0],
  ["Medium", "Find the gradient of straight line 3x-4y=24.", ["3/4", "-3/4", "4/3", "-4/3"], 0],
  ["Medium", "P(-4,2). Does it lie on the line 3x-2y=12?", ["No (3(-4)-2(2)=-16≠12)", "Yes", "Cannot be determined", "Only if y=0"], 0],
  ["Medium", "P(6,-2). Does it lie on the line x/3+y/2=1?", ["Yes (6/3-2/2=2-1=1)", "No", "Cannot be determined", "Only if x=0"], 0],
  ["Medium", "Is y=3x+5 parallel to 6x-2y=9?", ["Yes (equal gradient=3)", "No", "Cannot be determined", "Only if c is equal"], 0],
  ["Medium", "Is y=3x+8 parallel to 6y=3x-9?", ["No (gradient 3 vs 1/2)", "Yes", "Cannot be determined", "Only if x=0"], 0],
  ["Medium", "4x+3y=18 is parallel to 2x+hy=20. Find h.", ["h = 3/2", "h = 2/3", "h = 3", "h = 1/2"], 0],
  ["Medium", "Find the equation of a line with gradient 1/2 through P(6,8).", ["y = (1/2)x + 5", "y = (1/2)x + 8", "y = 2x + 5", "y = (1/2)x - 5"], 0],
  ["Medium", "Find the equation of a line through P(-1,5) and Q(2,-7).", ["y = -4x + 1", "y = 4x + 1", "y = -4x - 1", "y = -1/4x + 1"], 0],
  ["Medium", "Find the equation of a line parallel to y=-2x+6 through P(5,4).", ["y = -2x + 14", "y = -2x + 6", "y = 2x + 14", "y = -2x - 14"], 0],
  ["Medium", "Find the equation of a line parallel to the x-axis through A(2,4) and M(0,4).", ["y = 4", "x = 4", "y = 2x + 4", "x = 2"], 0],
  ["Medium", "Find the equation of a line parallel to the y-axis through A(2,4) and N(2,0).", ["x = 2", "y = 2", "y = 4x", "x = 4"], 0],
  ["Medium", "Find the intersection of 2x+y=5 and x+2y=1.", ["(3, -1)", "(-1, 3)", "(1, 3)", "(3, 1)"], 0],
  ["Medium", "Find the value of k for the parallel lines y=-3x+4 and y+kx=14.", ["k = 3", "k = -3", "k = 4", "k = 14"], 0],
  ["Medium", "Find the value of k for the parallel lines kx+2y=7 and 6x+2y=15.", ["k = 6", "k = 7", "k = 2", "k = 15"], 0],
  ["Medium", "3x+5y=15. What is the x-intercept (h)?", ["h = 5", "h = 3", "h = 15", "h = 1/5"], 0],
  ["Medium", "From the above, what is the y-intercept (k)?", ["k = 3", "k = 5", "k = 15", "k = 1/3"], 0],
  ["Medium", "From 3x+5y=15, if point (2,q) is on the line, find q.", ["q = 9/5", "q = 5/9", "q = 3", "q = -9/5"], 0],

  ["Hard", "Convert y=-2x+8 to the form ax+by=c.", ["2x + y = 8", "-2x + y = 8", "2x - y = 8", "x + 2y = 8"], 0],
  ["Hard", "Convert y=3x+6 to the form x/a+y/b=1.", ["x/(-2) + y/6 = 1", "x/2 + y/6 = 1", "x/6 + y/2 = 1", "x/(-2) + y/(-6) = 1"], 0],
  ["Hard", "Line PQ: y=(1/3)x+2. Find the equation of a line parallel to PQ through A(2,4).", ["y = (1/3)x + 10/3", "y = (1/3)x + 2", "y = 3x + 4", "y = (1/3)x - 10/3"], 0],
  ["Hard", "From the above, find the equation of a line parallel to PQ through the origin (0,0).", ["y = (1/3)x", "y = (1/3)x + 2", "x = 0", "y = 0"], 0],
  ["Hard", "Find the intersection of y=x+2 and 2x+3y=6.", ["x=0, y=2 (substitute: 2x+3(x+2)=6, 5x=0, x=0)", "x=2, y=4", "x=-2, y=0", "x=1, y=3"], 0],
  ["Hard", "Two lines 3y=-6x+3 and y+2x=14. Are they parallel?", ["Yes (gradient -2 and -2)", "No", "Cannot be determined", "Only if c is equal"], 0],
  ["Hard", "Two lines 2x+3y=3 and 2x+6y=12. Are they parallel?", ["No (gradient -2/3 vs -1/3)", "Yes", "Cannot be determined", "Only if divided first"], 0],
  ["Hard", "Two lines y=2x+1 and 8x-4y=5. Are they parallel?", ["Yes (gradient 2 and 2)", "No", "Cannot be determined", "Only if divided by 4"], 0],
  ["Hard", "8y=5x+1 is parallel to kx-3y=8. Find k.", ["k = -15/8 (gradient 5/8 = k/3, k=15/8; check the sign)", "k = 15/8", "k = 5/8", "k = -5/8"], 0],
  ["Hard", "A clinic is built equidistant from house P and Q, and 600m from road AB. What locus/line type is relevant for finding the clinic's location?", ["The perpendicular bisector of PQ intersecting a line parallel to AB at 600m", "Only a circle centred at P", "Only a line parallel to AB", "Only an angle bisector"], 0],
  ["Hard", "Why must the coefficient of y be converted to +1 before reading m and c?", ["Because the formula y=mx+c requires the y coefficient to be 1 for direct comparison", "Not important, any coefficient works", "Only for visual convenience", "Only applies to even numbers"], 0],
  ["Hard", "What is the best strategy for solving two simultaneous equations whose x coefficients differ but are easy to match?", ["Elimination method: multiply one/both equations to match coefficients, then subtract/add", "Substitution method only", "Graphing only", "Estimate the answer"], 0],
  ["Hard", "How do you verify the intersection point answer is correct?", ["Substitute the coordinates back into both original equations and confirm both are satisfied", "Only check one equation", "No need to check", "Compare with a classmate's answer"], 0],
]);
