import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c9-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 9",
    lang: "bm",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C9QuizzesBM: QuizQuestion[] = buildQuiz([
  ["Easy", "Dalam y=mx+c, apakah m?", ["Kecerunan", "Pintasan-y", "Pintasan-x", "Pemalar"], 0],
  ["Easy", "Dalam y=mx+c, apakah c?", ["Pintasan-y", "Kecerunan", "Pintasan-x", "Sudut"], 0],
  ["Easy", "Tentukan kecerunan bagi y=2x+9.", ["2", "9", "-2", "1/2"], 0],
  ["Easy", "Tentukan pintasan-y bagi y=2x+9.", ["9", "2", "0", "-9"], 0],
  ["Easy", "Dalam x/a+y/b=1, apakah a?", ["Pintasan-x", "Pintasan-y", "Kecerunan", "Pemalar"], 0],
  ["Easy", "Dalam x/a+y/b=1, apakah b?", ["Pintasan-y", "Pintasan-x", "Kecerunan", "Pemalar"], 0],
  ["Easy", "Apakah kecerunan garis y=6?", ["0", "6", "Tak tertakrif", "1"], 0],
  ["Easy", "Apakah kecerunan garis x=2?", ["Tak tertakrif", "0", "2", "1"], 0],
  ["Easy", "Garis y=h selari dengan paksi apa?", ["Paksi-x", "Paksi-y", "Kedua-duanya", "Tiada"], 0],
  ["Easy", "Garis x=h selari dengan paksi apa?", ["Paksi-y", "Paksi-x", "Kedua-duanya", "Tiada"], 0],
  ["Easy", "Dua garis lurus selari jika?", ["Kecerunan sama", "Pintasan-y sama", "Pintasan-x sama", "Panjang sama"], 0],
  ["Easy", "Apakah formula kecerunan dua titik (x1,y1) dan (x2,y2)?", ["(y2-y1)/(x2-x1)", "(x2-x1)/(y2-y1)", "(y2+y1)/(x2+x1)", "(y2-y1)x(x2-x1)"], 0],
  ["Easy", "3y=-2x+12. Apakah kecerunan?", ["-2/3", "2/3", "-3/2", "3/2"], 0],
  ["Easy", "3y=-2x+12. Apakah pintasan-y?", ["4", "12", "3", "-2"], 0],
  ["Easy", "Bagaimana semak titik P(2,8) terletak pada y=3x+2?", ["Gantikan x=2, semak jika y=8 hasilkan kesamaan", "Lukis graf sahaja", "Anggar sahaja", "Tidak boleh disemak"], 0],
  ["Easy", "P(2,8), y=3x+2. Adakah P pada garis ini?", ["Ya (3(2)+2=8)", "Tidak", "Tidak dapat ditentukan", "Hanya jika x=0"], 0],
  ["Easy", "Apakah dua kaedah mencari titik persilangan dua garis?", ["Graf dan persamaan serentak", "Hanya kalkulator", "Hanya anggaran", "Hanya geometri"], 0],
  ["Easy", "Apakah dua kaedah persamaan serentak?", ["Penggantian dan penghapusan", "Tambah dan tolak sahaja", "Darab dan bahagi sahaja", "Lukis dan ukur"], 0],
  ["Easy", "Apakah pekali y yang mesti dalam y=mx+c?", ["+1", "-1", "0", "Sebarang nilai"], 0],
  ["Easy", "Siapakah bapa geometri Yunani disebut dalam bab ini?", ["Euclid", "Pythagoras", "Archimedes", "Thales"], 0],

  ["Medium", "Tukar 2x+3y=12 kepada bentuk x/a+y/b=1.", ["x/6 + y/4 = 1", "x/4 + y/6 = 1", "x/12 + y/12 = 1", "x/2 + y/3 = 1"], 0],
  ["Medium", "Tukar 2x+3y=12 kepada y=mx+c.", ["y = -2/3x + 4", "y = 2/3x + 4", "y = -3/2x + 6", "y = 2x + 12"], 0],
  ["Medium", "Tukar x/6+y/3=1 kepada bentuk ax+by=c.", ["x + 2y = 6", "x + y = 9", "2x + y = 6", "x - 2y = 6"], 0],
  ["Medium", "Tentukan kecerunan garis lurus 3x-4y=24.", ["3/4", "-3/4", "4/3", "-4/3"], 0],
  ["Medium", "P(-4,2). Adakah pada garis 3x-2y=12?", ["Tidak (3(-4)-2(2)=-16≠12)", "Ya", "Tidak dapat ditentukan", "Hanya jika y=0"], 0],
  ["Medium", "P(6,-2). Adakah pada garis x/3+y/2=1?", ["Ya (6/3-2/2=2-1=1)", "Tidak", "Tidak dapat ditentukan", "Hanya jika x=0"], 0],
  ["Medium", "Adakah y=3x+5 selari dengan 6x-2y=9?", ["Ya (kecerunan sama=3)", "Tidak", "Tidak dapat ditentukan", "Hanya jika c sama"], 0],
  ["Medium", "Adakah y=3x+8 selari dengan 6y=3x-9?", ["Tidak (kecerunan 3 vs 1/2)", "Ya", "Tidak dapat ditentukan", "Hanya jika x=0"], 0],
  ["Medium", "4x+3y=18 selari dengan 2x+hy=20. Cari h.", ["h = 3/2", "h = 2/3", "h = 3", "h = 1/2"], 0],
  ["Medium", "Cari persamaan garis kecerunan 1/2 melalui P(6,8).", ["y = (1/2)x + 5", "y = (1/2)x + 8", "y = 2x + 5", "y = (1/2)x - 5"], 0],
  ["Medium", "Cari persamaan garis melalui P(-1,5) dan Q(2,-7).", ["y = -4x + 1", "y = 4x + 1", "y = -4x - 1", "y = -1/4x + 1"], 0],
  ["Medium", "Cari persamaan garis selari y=-2x+6 melalui P(5,4).", ["y = -2x + 14", "y = -2x + 6", "y = 2x + 14", "y = -2x - 14"], 0],
  ["Medium", "Cari persamaan garis selari paksi-x melalui A(2,4) dan M(0,4).", ["y = 4", "x = 4", "y = 2x + 4", "x = 2"], 0],
  ["Medium", "Cari persamaan garis selari paksi-y melalui A(2,4) dan N(2,0).", ["x = 2", "y = 2", "y = 4x", "x = 4"], 0],
  ["Medium", "Cari titik persilangan 2x+y=5 dan x+2y=1.", ["(3, -1)", "(-1, 3)", "(1, 3)", "(3, 1)"], 0],
  ["Medium", "Tentukan nilai k bagi pasangan garis selari y=-3x+4 dan y+kx=14.", ["k = 3", "k = -3", "k = 4", "k = 14"], 0],
  ["Medium", "Tentukan nilai k bagi pasangan garis selari kx+2y=7 dan 6x+2y=15.", ["k = 6", "k = 7", "k = 2", "k = 15"], 0],
  ["Medium", "3x+5y=15. Apakah pintasan-x (h)?", ["h = 5", "h = 3", "h = 15", "h = 1/5"], 0],
  ["Medium", "Daripada soalan di atas, apakah pintasan-y (k)?", ["k = 3", "k = 5", "k = 15", "k = 1/3"], 0],
  ["Medium", "Daripada 3x+5y=15, jika titik (2,q) pada garis, cari q.", ["q = 9/5", "q = 5/9", "q = 3", "q = -9/5"], 0],

  ["Hard", "Tukar y=-2x+8 kepada bentuk ax+by=c.", ["2x + y = 8", "-2x + y = 8", "2x - y = 8", "x + 2y = 8"], 0],
  ["Hard", "Tukar y=3x+6 kepada bentuk x/a+y/b=1.", ["x/(-2) + y/6 = 1", "x/2 + y/6 = 1", "x/6 + y/2 = 1", "x/(-2) + y/(-6) = 1"], 0],
  ["Hard", "Garis lurus PQ: y=(1/3)x+2. Cari persamaan garis selari PQ melalui A(2,4).", ["y = (1/3)x + 10/3", "y = (1/3)x + 2", "y = 3x + 4", "y = (1/3)x - 10/3"], 0],
  ["Hard", "Daripada soalan di atas, cari persamaan garis selari PQ melalui asalan (0,0).", ["y = (1/3)x", "y = (1/3)x + 2", "x = 0", "y = 0"], 0],
  ["Hard", "Cari titik persilangan y=x+2 dan 2x+3y=6.", ["x=0, y=2 (gantikan: 2x+3(x+2)=6, 5x=0, x=0)", "x=2, y=4", "x=-2, y=0", "x=1, y=3"], 0],
  ["Hard", "Dua garis 3y=-6x+3 dan y+2x=14. Adakah selari?", ["Ya (kecerunan -2 dan -2)", "Tidak", "Tidak dapat ditentukan", "Hanya jika c sama"], 0],
  ["Hard", "Dua garis 2x+3y=3 dan 2x+6y=12. Adakah selari?", ["Tidak (kecerunan -2/3 vs -1/3)", "Ya", "Tidak dapat ditentukan", "Hanya jika dibahagi dahulu"], 0],
  ["Hard", "Dua garis y=2x+1 dan 8x-4y=5. Adakah selari?", ["Ya (kecerunan 2 dan 2)", "Tidak", "Tidak dapat ditentukan", "Hanya jika dibahagi 4"], 0],
  ["Hard", "8y=5x+1 selari dengan kx-3y=8. Cari k.", ["k = -15/8 (kecerunan 5/8 = k/3, k=15/8; perhatikan tanda)", "k = 15/8", "k = 5/8", "k = -5/8"], 0],
  ["Hard", "Klinik dibina berjarak sama dari rumah P dan Q, serta 600m dari jalan AB. Apakah jenis lokus/garis yang relevan untuk cari kedudukan klinik?", ["Pembahagi dua sama serenjang PQ bersilang dengan garis selari AB pada 600m", "Hanya bulatan pusat P", "Hanya garis selari AB", "Hanya pembahagi dua sudut"], 0],
  ["Hard", "Mengapa pekali y mesti ditukar kepada +1 sebelum baca m dan c?", ["Kerana formula y=mx+c memerlukan pekali y bernilai 1 untuk bandingan terus", "Tidak penting, sebarang pekali boleh", "Hanya untuk kemudahan visual", "Hanya berlaku untuk nombor genap"], 0],
  ["Hard", "Apakah strategi terbaik menyelesaikan dua persamaan serentak dengan pekali x berbeza tetapi mudah disamakan?", ["Kaedah penghapusan: darab salah satu/kedua persamaan untuk samakan pekali, kemudian tolak/tambah", "Kaedah penggantian sahaja", "Lukis graf sahaja", "Anggar jawapan"], 0],
  ["Hard", "Bagaimana sahkan jawapan titik persilangan adalah betul?", ["Gantikan semula koordinat ke kedua-dua persamaan asal dan pastikan kedua memenuhi", "Hanya semak satu persamaan", "Tidak perlu semak", "Bandingkan dengan jawapan rakan"], 0],
]);
