import type { Difficulty, QuizQuestion } from "@/data/content";
import { buildForm3MathQuizSets } from "../quiz-sets";
import { MATH_F3_C9_QUIZ_VISUALS } from "./quiz-visuals";
import { MATH_F3_C9_QUIZ_EXPLANATIONS } from "./quiz-explanations";
type QuizSeed = [Difficulty, string, [string, string, string, string], number];
function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c9-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    chapter: "Chapter 9",
    lang: "dlp",
    difficulty,
    question,
    options,
    answerIndex,
    mathNotation: "indices",
    visual: MATH_F3_C9_QUIZ_VISUALS[index + 1],
    explanation: MATH_F3_C9_QUIZ_EXPLANATIONS[index + 1].dlp,
  }));
}
export const mathF3C9QuestionBankDLP: QuizQuestion[] = buildQuiz([
  [
    "Easy",
    "In y=mx+c, what is m?",
    ["Gradient", "y-intercept", "x-intercept", "Constant"],
    0,
  ],
  [
    "Easy",
    "In y=mx+c, what is c?",
    ["y-intercept", "Gradient", "x-intercept", "Angle"],
    0,
  ],
  ["Easy", "Find the gradient of y=2x+9.", ["2", "9", "-2", "1/2"], 0],
  ["Easy", "Find the y-intercept of y=2x+9.", ["9", "2", "0", "-9"], 0],
  [
    "Easy",
    "In x/a+y/b=1, what is a? Given a ≠ 0 and b ≠ 0.",
    ["x-intercept", "y-intercept", "Gradient", "Constant"],
    0,
  ],
  [
    "Easy",
    "In x/a+y/b=1, what is b? Given a ≠ 0 and b ≠ 0.",
    ["y-intercept", "x-intercept", "Gradient", "Constant"],
    0,
  ],
  [
    "Easy",
    "What is the gradient of line y=6?",
    ["0", "6", "Undefined", "1"],
    0,
  ],
  [
    "Easy",
    "What is the gradient of line x=2?",
    ["Undefined", "0", "2", "1"],
    0,
  ],
  [
    "Easy",
    "Line y=h is parallel to which axis? Given h ≠ 0.",
    ["x-axis", "y-axis", "Both", "Neither"],
    0,
  ],
  [
    "Easy",
    "Line x=h is parallel to which axis? Given h ≠ 0.",
    ["y-axis", "x-axis", "Both", "Neither"],
    0,
  ],
  [
    "Easy",
    "Which condition makes two distinct non-vertical straight lines parallel?",
    [
      "Equal gradients",
      "Only equal y-intercepts",
      "Only equal x-intercepts",
      "Different gradients",
    ],
    0,
  ],
  [
    "Easy",
    "What is the gradient formula for two points (x₁,y₁) and (x₂,y₂)? Given x₁ ≠ x₂.",
    [
      "(y₂-y₁)/(x₂-x₁)",
      "(x₂-x₁)/(y₂-y₁)",
      "(y₂+y₁)/(x₂+x₁)",
      "(y₂ − y₁) × (x₂ − x₁)",
    ],
    0,
  ],
  [
    "Easy",
    "3y=-2x+12. What is the gradient?",
    ["-2/3", "2/3", "-3/2", "3/2"],
    0,
  ],
  ["Easy", "3y=-2x+12. What is the y-intercept?", ["4", "12", "3", "-2"], 0],
  [
    "Easy",
    "Which point lies on the line y = 3x + 2?",
    ["(1, 5)", "(1, 8)", "(2, 5)", "(3, 8)"],
    0,
  ],
  [
    "Easy",
    "Point (k,8) lies on the line y = 3x + 2. Find k.",
    ["2", "3", "6", "8"],
    0,
  ],
  [
    "Easy",
    "Find the intersection of the lines y = x + 1 and y = 3.",
    ["(2, 3)", "(3, 2)", "(1, 3)", "(2, 2)"],
    0,
  ],
  [
    "Easy",
    "Find the intersection of the lines y = 2x and x = 3.",
    ["(3, 6)", "(6, 3)", "(3, 3)", "(6, 6)"],
    0,
  ],
  [
    "Easy",
    "Find the x-intercept of the line y = −2x + 5.",
    ["5/2", "−5/2", "5", "2"],
    0,
  ],
  [
    "Easy",
    "Find the gradient of the line through P(1,2) and Q(3,6).",
    ["2", "1/2", "4", "−2"],
    0,
  ],
  [
    "Medium",
    "Convert 2x+3y=12 to the form x/a+y/b=1.",
    ["x/6 + y/4 = 1", "x/4 + y/6 = 1", "x/12 + y/12 = 1", "x/2 + y/3 = 1"],
    0,
  ],
  [
    "Medium",
    "Convert 2x+3y=12 to y=mx+c.",
    ["y = (−2/3)x + 4", "y = (2/3)x + 4", "y = (−3/2)x + 6", "y = 2x + 12"],
    0,
  ],
  [
    "Medium",
    "Convert x/6+y/3=1 to the form ax+by=c.",
    ["x + 2y = 6", "x + y = 9", "2x + y = 6", "x - 2y = 6"],
    0,
  ],
  [
    "Medium",
    "Find the gradient of straight line 3x-4y=24.",
    ["3/4", "-3/4", "4/3", "-4/3"],
    0,
  ],
  [
    "Medium",
    "Point (−4,k) lies on the line 3x − 2y = 12. Find k.",
    ["−12", "12", "−6", "−16"],
    0,
  ],
  [
    "Medium",
    "Point (k,−2) lies on the line x/3 + y/2 = 1. Find k.",
    ["6", "−6", "3", "−3"],
    0,
  ],
  [
    "Medium",
    "What is the gradient of a line parallel to 6x − 2y = 9?",
    ["3", "−3", "2", "−2"],
    0,
  ],
  [
    "Medium",
    "Two lines have equations y = 3x + 8 and 6y = 3x − 9. Choose their gradients in that order.",
    ["(3, 1/2)", "(3, 2)", "(8, −9)", "(1/3, 1/2)"],
    0,
  ],
  [
    "Medium",
    "4x+3y=18 is parallel to 2x+hy=20. Find h.",
    ["h = 3/2", "h = 2/3", "h = 3", "h = 1/2"],
    0,
  ],
  [
    "Medium",
    "Find the equation of a line with gradient 1/2 through P(6,8).",
    ["y = (1/2)x + 5", "y = (1/2)x + 8", "y = 2x + 5", "y = (1/2)x - 5"],
    0,
  ],
  [
    "Medium",
    "Find the equation of a line through P(-1,5) and Q(2,-7).",
    ["y = -4x + 1", "y = 4x + 1", "y = -4x - 1", "y = (−1/4)x + 1"],
    0,
  ],
  [
    "Medium",
    "Find the equation of a line parallel to y=-2x+6 through P(5,4).",
    ["y = -2x + 14", "y = -2x + 6", "y = 2x + 14", "y = -2x - 14"],
    0,
  ],
  [
    "Medium",
    "Find the equation of a line parallel to the x-axis through A(2,4) and M(0,4).",
    ["y = 4", "x = 4", "y = 2x + 4", "x = 2"],
    0,
  ],
  [
    "Medium",
    "Find the equation of a line parallel to the y-axis through A(2,4) and N(2,0).",
    ["x = 2", "y = 2", "y = 4x", "x = 4"],
    0,
  ],
  [
    "Medium",
    "Find the intersection of 2x+y=5 and x+2y=1.",
    ["(3, -1)", "(-1, 3)", "(1, 3)", "(3, 1)"],
    0,
  ],
  [
    "Medium",
    "Find the value of k for the parallel lines y=-3x+4 and y+kx=14.",
    ["k = 3", "k = -3", "k = 4", "k = 14"],
    0,
  ],
  [
    "Medium",
    "Find the value of k for the parallel lines kx+2y=7 and 6x+2y=15.",
    ["k = 6", "k = 7", "k = 2", "k = 15"],
    0,
  ],
  [
    "Medium",
    "3x+5y=15. What is the x-intercept (h)?",
    ["h = 5", "h = 3", "h = 15", "h = 1/5"],
    0,
  ],
  [
    "Medium",
    "A line has equation 3x + 5y = 15. Find its y-intercept, k.",
    ["k = 3", "k = 5", "k = 15", "k = 1/3"],
    0,
  ],
  [
    "Medium",
    "From 3x+5y=15, if point (2,q) is on the line, find q.",
    ["q = 9/5", "q = 5/9", "q = 3", "q = -9/5"],
    0,
  ],
  [
    "Hard",
    "Convert y=-2x+8 to the form ax+by=c.",
    ["2x + y = 8", "-2x + y = 8", "2x - y = 8", "x + 2y = 8"],
    0,
  ],
  [
    "Hard",
    "Convert y=3x+6 to the form x/a+y/b=1.",
    [
      "x/(-2) + y/6 = 1",
      "x/2 + y/6 = 1",
      "x/6 + y/2 = 1",
      "x/(-2) + y/(-6) = 1",
    ],
    0,
  ],
  [
    "Hard",
    "Line PQ: y=(1/3)x+2. Find the equation of a line parallel to PQ through A(2,4).",
    ["y = (1/3)x + 10/3", "y = (1/3)x + 2", "y = 3x + 4", "y = (1/3)x - 10/3"],
    0,
  ],
  [
    "Hard",
    "Line PQ has equation y = (1/3)x + 2. Find the equation of a line parallel to PQ through the origin (0,0).",
    ["y = (1/3)x", "y = (1/3)x + 2", "x = 0", "y = 0"],
    0,
  ],
  [
    "Hard",
    "Find the intersection of y = x + 2 and 2x + 3y = 6.",
    ["(0, 2)", "(2, 4)", "(−2, 0)", "(1, 3)"],
    0,
  ],
  [
    "Hard",
    "The line 3y = −6x + 3 is parallel to kx + 2y = 10. Find k.",
    ["4", "−4", "2", "−2"],
    0,
  ],
  [
    "Hard",
    "Find the intersection of the lines 2x + 3y = 3 and 2x + 6y = 12.",
    ["(−3, 3)", "(3, −3)", "(3, 3)", "(−3, −3)"],
    0,
  ],
  [
    "Hard",
    "The line kx − 4y = 5 is parallel to y = (3/2)x + 1. Find k.",
    ["6", "−6", "3/2", "−3/2"],
    0,
  ],
  [
    "Hard",
    "8y = 5x + 1 is parallel to kx − 3y = 8. Find k.",
    ["15/8", "−15/8", "5/8", "−5/8"],
    0,
  ],
  [
    "Hard",
    "On a coordinate plane measured in metres, houses P(0,0) and Q(800,0) lie on road y = 0. A clinic is equidistant from P and Q, 600 m from the road and on the side y > 0. Find its coordinates.",
    ["(400, 600)", "(400, −600)", "(600, 400)", "(800, 600)"],
    0,
  ],
  [
    "Hard",
    "The line ay = 6x − 9 has y-intercept −3. Find its gradient.",
    ["2", "−2", "3", "−3"],
    0,
  ],
  [
    "Hard",
    "The lines y = 2x + c and 3x + y = 11 intersect at (3,k). Find c.",
    ["−4", "4", "2", "−2"],
    0,
  ],
  [
    "Hard",
    "Which coordinates satisfy BOTH equations 2x − y = 7 and x + y = 5?",
    ["(4, 1)", "(1, 4)", "(3, 2)", "(2, 3)"],
    0,
  ],
]);
export const mathF3C9QuizzesDLP: QuizQuestion[] = buildForm3MathQuizSets(
  9,
  mathF3C9QuestionBankDLP,
);
