import type { Flashcard } from "@/data/content";

export const scienceF2C2FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c2-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud ekosistem?",
    back: "Beberapa komuniti yang hidup bersama dalam satu habitat dan berinteraksi sesama sendiri, termasuk komponen bukan hidup seperti air, udara dan tanah.",
  },
  {
    id: "sci-f2-c2-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud habitat?",
    back: "Persekitaran semula jadi atau tempat tinggal sesuatu organisma.",
  },
  {
    id: "sci-f2-c2-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud spesies?",
    back: "Sekumpulan organisma yang mempunyai ciri sepunya dan boleh membiak untuk menghasilkan anak.",
  },
  {
    id: "sci-f2-c2-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud populasi?",
    back: "Sekumpulan organisma daripada spesies yang sama yang hidup dalam habitat yang sama.",
  },
  {
    id: "sci-f2-c2-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud komuniti?",
    back: "Beberapa populasi organisma berlainan yang hidup bersama dalam satu habitat dan mempunyai interaksi sesama sendiri.",
  },
  {
    id: "sci-f2-c2-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud pengeluar?",
    back: "Organisma yang menghasilkan makanannya sendiri melalui fotosintesis. Kebanyakan tumbuhan ialah pengeluar.",
  },
  {
    id: "sci-f2-c2-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud pengguna primer?",
    back: "Organisma yang memakan organisma lain; herbivor dan omnivor yang memakan pengeluar, contoh: ulat.",
  },
  {
    id: "sci-f2-c2-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud pengguna sekunder?",
    back: "Omnivor dan karnivor yang memakan pengguna primer.",
  },
  {
    id: "sci-f2-c2-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud pengguna tertier?",
    back: "Karnivor sekunder yang memakan pengguna sekunder; biasanya bersaiz lebih besar.",
  },
  {
    id: "sci-f2-c2-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud pengurai? Berikan contoh.",
    back: "Organisma yang memecahkan haiwan/tumbuhan mati kepada bahan/nutrien yang lebih ringkas (saprofitisme). Contoh: cendawan, kulapuk, bakteria E. coli.",
  },
  {
    id: "sci-f2-c2-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud rantai makanan?",
    back: "Menunjukkan hubungan pemakanan antara organisma secara linear (satu arah).",
  },
  {
    id: "sci-f2-c2-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud siratan makanan?",
    back: "Gabungan beberapa rantai makanan yang saling berkait.",
  },
  {
    id: "sci-f2-c2-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Namakan tiga kitar nutrien utama.",
    back: "Kitar air, kitar karbon, kitar oksigen.",
  },
  {
    id: "sci-f2-c2-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud mutualisme?",
    back: "Interaksi simbiosis yang memberi manfaat kepada KEDUA-DUA organisma.",
  },
  {
    id: "sci-f2-c2-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud komensalisme?",
    back: "Interaksi yang memberi manfaat kepada SATU organisma sahaja, tanpa merugikan atau memanfaatkan organisma lain.",
  },
  {
    id: "sci-f2-c2-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud parasitisme?",
    back: "Interaksi yang memberi manfaat kepada SATU organisma (parasit) dan MERUGIKAN organisma lain (perumah).",
  },
  {
    id: "sci-f2-c2-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud mangsa-pemangsa?",
    back: "Melibatkan satu organisma (pemangsa) memakan organisma lain (mangsa).",
  },
  {
    id: "sci-f2-c2-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud persaingan?",
    back: "Berlaku apabila organisma bersaing untuk bekalan keperluan asas terhad seperti cahaya, ruang, air, makanan dan pasangan.",
  },
  {
    id: "sci-f2-c2-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud kawalan biologi?",
    back: "Kaedah menggunakan pemangsa, parasit atau patogen semula jadi untuk mengurangkan bilangan perosak di sesuatu kawasan.",
  },
  {
    id: "sci-f2-c2-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud aliran tenaga dalam ekosistem?",
    back: "Pemindahan tenaga daripada satu organisma kepada organisma lain melalui rantai/siratan makanan; sebahagian tenaga hilang sebagai haba pada setiap peringkat.",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c2-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan pengguna primer dengan pengguna sekunder.",
    back: "Pengguna primer: herbivor/omnivor yang memakan pengeluar. Pengguna sekunder: omnivor/karnivor yang memakan pengguna primer.",
  },
  {
    id: "sci-f2-c2-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan pengguna sekunder dengan pengguna tertier.",
    back: "Pengguna sekunder: omnivor/karnivor (karnivor primer) yang memakan pengguna primer. Pengguna tertier: karnivor sekunder yang memakan pengguna sekunder, biasanya lebih besar.",
  },
  {
    id: "sci-f2-c2-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan mutualisme, komensalisme dan parasitisme.",
    back: "Mutualisme: kedua-dua untung. Komensalisme: satu untung, satu tidak terjejas. Parasitisme: satu untung (parasit), satu rugi (perumah).",
  },
  {
    id: "sci-f2-c2-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan mangsa-pemangsa dengan persaingan.",
    back: "Mangsa-pemangsa: pemakanan antara dua organisma berlainan. Persaingan: organisma bersaing untuk keperluan asas terhad (boleh sesama/antara spesies).",
  },
  {
    id: "sci-f2-c2-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan peranan tumbuhan dalam kitar air dengan kitar karbon/oksigen.",
    back: "Kitar air: akar menyerap air, daun melepaskan air melalui transpirasi. Kitar karbon/oksigen: daun menjalankan fotosintesis (menyerap CO2, melepaskan O2).",
  },
  {
    id: "sci-f2-c2-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan peranan respirasi dengan fotosintesis dalam kitar oksigen.",
    back: "Respirasi: menggunakan oksigen, melepaskan karbon dioksida. Fotosintesis: menyerap karbon dioksida, melepaskan oksigen.",
  },
  {
    id: "sci-f2-c2-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan rantai makanan dengan siratan makanan.",
    back: "Rantai makanan: laluan linear tunggal. Siratan makanan: gabungan beberapa rantai makanan yang saling berkait.",
  },
  {
    id: "sci-f2-c2-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan spesies, populasi, komuniti dan ekosistem dari segi skop.",
    back: "Spesies (organisma berkongsi ciri) → Populasi (satu spesies, satu habitat) → Komuniti (banyak populasi) → Ekosistem (komuniti + komponen bukan hidup).",
  },
  {
    id: "sci-f2-c2-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan contoh mutualisme: anemon laut & ikan badut dengan mynah & kerbau.",
    back: "Anemon laut & ikan badut: anemon melindungi & beri makanan, ikan badut membersihkan & beri nutrien. Mynah & kerbau: mynah makan kutu kerbau, kerbau jadi bebas kutu.",
  },
  {
    id: "sci-f2-c2-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan contoh komensalisme: ikan remora & jerung dengan paku pakis sarang burung.",
    back: "Ikan remora & jerung: remora makan sisa makanan jerung, jerung tidak terjejas. Paku pakis sarang burung: tumbuh di dahan pokok untuk dapatkan cahaya, pokok tidak terjejas.",
  },
  {
    id: "sci-f2-c2-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan kebaikan dan kelemahan kawalan biologi.",
    back: "Kebaikan: mesra alam, murah, tidak jejas kesihatan manusia. Kelemahan: lambat berkesan, boleh ganggu keseimbangan ekosistem (spesies baharu diperkenalkan).",
  },
  {
    id: "sci-f2-c2-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan kesan pembalakan hutan dengan kesan perindustrian.",
    back: "Pembalakan: kepupusan spesies, hakisan tanah, kesan rumah hijau. Perindustrian: pencemaran udara/air/tanah, hujan asid, kesan rumah hijau.",
  },
  {
    id: "sci-f2-c2-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan kesan pertanian dengan kesan pelupusan sisa.",
    back: "Pertanian: pencemaran air (racun/baja berlebihan), kehilangan mineral tanah. Pelupusan sisa: pencemaran air/tanah, bau busuk, banjir kilat.",
  },
  {
    id: "sci-f2-c2-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan faktor penyakit dengan faktor sumber makanan dalam mempengaruhi saiz populasi.",
    back: "Penyakit: contoh selesema burung, virus mozek tembakau, menurunkan populasi secara terus. Sumber makanan: contoh panda & buluh, jika sumber berkurang populasi terancam pupus.",
  },
  {
    id: "sci-f2-c2-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan faktor pemangsa dengan faktor cuaca dalam mempengaruhi saiz populasi.",
    back: "Pemangsa: contoh zebra & singa, populasi mangsa berkurang dengan kehadiran pemangsa. Cuaca: kemarau menyebabkan tanah kering & kebakaran hutan, populasi tumbuhan/haiwan berkurang.",
  },
  {
    id: "sci-f2-c2-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan kesan penghijrahan dengan kesan bekalan air terhad terhadap ekosistem.",
    back: "Penghijrahan: contoh burung kuntul kerbau di Kuala Gula, mengurangkan populasi serangga. Bekalan air terhad: kemarau panjang mengurangkan populasi padi (pengeluar), menjejaskan siratan makanan.",
  },
  {
    id: "sci-f2-c2-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan in situ konservasi (Bab 1) dengan langkah pemuliharaan ekosistem (Bab 2).",
    back: "Bab 1 in situ: memelihara spesies dalam habitat asal. Bab 2: penguatkuasaan undang-undang, kesedaran awam, 5R dan kawalan biologi untuk mengekalkan keseimbangan ekosistem secara umum.",
  },
  {
    id: "sci-f2-c2-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan kelima-lima prinsip 5R.",
    back: "Refuse (tolak guna bahan tak boleh kitar semula), Reduce (kurangkan penggunaan), Reuse (guna semula), Recycle (kitar semula), Repurpose (guna untuk tujuan lain).",
  },
  {
    id: "sci-f2-c2-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan ekosistem semula jadi dengan ekosistem buatan manusia.",
    back: "Kedua-duanya boleh seimbang. Ekosistem semula jadi: hutan, kolam. Ekosistem buatan manusia: contoh akuarium — organisma & komponen bukan hidup masih berinteraksi secara harmoni.",
  },
  {
    id: "sci-f2-c2-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bandingkan konsep piramid tenaga dengan aliran tenaga linear dalam rantai makanan.",
    back: "Aliran tenaga linear: tenaga berpindah dari pengeluar ke pengguna secara berurutan. Piramid tenaga: gambaran visual bahawa jumlah tenaga berkurang pada setiap peringkat trofik yang lebih tinggi.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c2-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[KBAT] Musang (pengguna tertier) dalam siratan makanan mati akibat penyakit. Apakah kesan kepada burung (pengguna sekunder) dan siput (pengguna primer)?",
    back: "Populasi burung mungkin meningkat (kurang pemangsa); populasi siput mungkin berkurang akibat lebih ramai burung memakannya.",
  },
  {
    id: "sci-f2-c2-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[KBAT] Petani ingin kawal tikus tanpa racun kimia. Kaedah paling sesuai?",
    back: "Memelihara burung hantu sebagai kawalan biologi — mesra alam dan tidak menjejaskan kesihatan manusia, walaupun mengambil masa lebih lama.",
  },
  {
    id: "sci-f2-c2-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Namakan 5 contoh kawalan biologi yang digunakan dalam pertanian Malaysia.",
    back: "Burung hantu (tikus), guppy (larva nyamuk), Bacillus thuringiensis (kumbang badak), kumbang kepik (afid), itik (siput/serangga di sawah padi).",
  },
  {
    id: "sci-f2-c2-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Bila dan di mana burung kuntul kerbau (Bubulcus ibis) berhijrah?",
    back: "Ke Kuala Gula, Perak, dari September hingga April setiap tahun.",
  },
  {
    id: "sci-f2-c2-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[Fakta Penting] Apakah yang terjadi di selatan Rusia pada tahun 2015?",
    back: "Kawanan belalang memusnahkan ladang jagung seluas 800 hektar dalam masa beberapa jam.",
  },
  {
    id: "sci-f2-c2-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[Fakta Penting] Apakah program PERHILITAN di Taman Tasik Perdana pada tahun 2010?",
    back: "Program pensterilan monyet jantan (kemudian dibebaskan semula) untuk mengawal populasi monyet sebagai alternatif menyelesaikan konflik manusia-monyet.",
  },
  {
    id: "sci-f2-c2-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah tenaga dikitar semula seperti nutrien?",
    back: "Tidak. Tenaga mengalir satu hala dan hilang sebagai haba/najis pada setiap peringkat trofik; hanya nutrien yang dikitar semula.",
  },
  {
    id: "sci-f2-c2-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah komensalisme sama dengan mutualisme kecil?",
    back: "Tidak. Dalam komensalisme, organisma kedua TIDAK menerima sebarang manfaat — ia hanya tidak terjejas, berbeza dengan mutualisme di mana kedua-dua untung.",
  },
  {
    id: "sci-f2-c2-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah persaingan hanya berlaku antara spesies berlainan?",
    back: "Tidak. Persaingan boleh berlaku sesama spesies (contoh: persaingan mendapatkan pasangan) mahupun antara spesies berlainan untuk keperluan asas terhad.",
  },
  {
    id: "sci-f2-c2-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[KBAT] Sawah padi alami kemarau panjang. Apakah kesan kepada siratan makanan?",
    back: "Populasi pengeluar (padi) berkurang akibat kekurangan air, menyebabkan keseluruhan siratan makanan yang bergantung kepadanya turut terjejas.",
  },
  {
    id: "sci-f2-c2-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Mengapa panda terancam apabila hutan buluh ditebang?",
    back: "Panda bergantung kepada buluh sebagai sumber makanan utama; penebangan hutan memusnahkan sumber makanan dan habitatnya.",
  },
  {
    id: "sci-f2-c2-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Mengapa populasi burung gagak di Malaysia meningkat?",
    back: "Disebabkan oleh sumber makanan yang banyak, iaitu sisa makanan manusia.",
  },
  {
    id: "sci-f2-c2-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan 'nyatakan DUA langkah menjimatkan air' dengan markah penuh?",
    back: "Nyatakan langkah spesifik: menyimpan air hujan untuk kegunaan harian, dan menanam semula pokok untuk mengekalkan kitar air.",
  },
  {
    id: "sci-f2-c2-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Namakan 4 jenis aktiviti manusia dan kesan utamanya terhadap alam sekitar.",
    back: "Pembalakan (kepupusan spesies, hakisan tanah), perindustrian (pencemaran, hujan asid), pertanian (pencemaran air, kehilangan mineral), pelupusan sisa (pencemaran, banjir kilat).",
  },
  {
    id: "sci-f2-c2-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah peranan Jabatan Perhutanan dalam penguatkuasaan undang-undang alam sekitar?",
    back: "Menjalankan rondaan di kawasan hutan, menggunakan helikopter, dan mengadakan sekatan jalan raya untuk memantau lori pembawa balak.",
  },
  {
    id: "sci-f2-c2-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[KBAT] Mengapa pembalakan tidak terkawal menjejaskan kitar air dan kitar karbon?",
    back: "Kehilangan pokok mengurangkan transpirasi dan penyerapan karbon dioksida melalui fotosintesis, sekali gus mengganggu kedua-dua kitar tersebut.",
  },
  {
    id: "sci-f2-c2-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah maksud ahli ekologi?",
    back: "Seseorang yang mengkaji ekosistem.",
  },
  {
    id: "sci-f2-c2-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "[KBAT] Mengapa kawalan biologi dianggap mempunyai risiko ekologi walaupun mesra alam?",
    back: "Kerana ia memperkenalkan spesies baharu ke dalam ekosistem, yang berpotensi mengganggu keseimbangan ekosistem sedia ada.",
  },
  {
    id: "sci-f2-c2-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Apakah hipotesis yang diuji dalam Eksperimen 2.1 mengenai kutu kayu (woodlice)?",
    back: "Kutu kayu berkumpul di kawasan bersuhu sederhana, gelap dan lembap — menunjukkan suhu, cahaya dan kelembapan mempengaruhi taburan organisma.",
  },
  {
    id: "sci-f2-c2-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "bm",
    front: "Ringkaskan peta konsep Bab 2 dalam satu ayat.",
    back: "Ekosistem merangkumi hierarki spesies-populasi-komuniti, aliran tenaga melalui pengeluar/pengguna/pengurai, kitar nutrien, jenis interaksi (simbiosis, mangsa-pemangsa, persaingan), faktor saiz populasi, dan peranan manusia mengekalkan keseimbangan alam.",
  },
];
