import type { Flashcard } from "@/data/content";

export const scienceF2C2FlashcardsDLP: Flashcard[] = [
  // Set 1: Ecosystem Components & Energy Flow
  {
    id: "sci-f2-c2-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is the meaning of an ecosystem?",
    back: "A few communities that live together in one habitat and interact with one another, including non-living components such as water, air and soil.",
  },
  {
    id: "sci-f2-c2-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a habitat?",
    back: "The natural surroundings or home of an organism.",
  },
  {
    id: "sci-f2-c2-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a species?",
    back: "A group of organisms that have common characteristics and can reproduce to produce offspring.",
  },
  {
    id: "sci-f2-c2-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a population?",
    back: "A group of organisms of the same species that live in the same habitat.",
  },
  {
    id: "sci-f2-c2-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a community?",
    back: "A few populations of different organisms that live together in one habitat and have mutual interaction with one another.",
  },
  {
    id: "sci-f2-c2-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare species, population, community and ecosystem in terms of scope.",
    back: "Species (organisms sharing characteristics) → Population (one species, one habitat) → Community (many populations) → Ecosystem (community + non-living components).",
  },
  {
    id: "sci-f2-c2-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a producer?",
    back: "An organism that produces its own food through photosynthesis. Most plants are producers.",
  },
  {
    id: "sci-f2-c2-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a primary consumer?",
    back: "An organism that eats another organism; herbivores and omnivores that eat producers, e.g. caterpillar.",
  },
  {
    id: "sci-f2-c2-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a secondary consumer?",
    back: "An omnivore and carnivore that eats the primary consumer.",
  },
  {
    id: "sci-f2-c2-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a tertiary consumer?",
    back: "A secondary carnivore that eats a secondary consumer; usually bigger in size.",
  },
  {
    id: "sci-f2-c2-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare primary consumer with secondary consumer.",
    back: "Primary consumer: herbivore/omnivore that eats the producer. Secondary consumer: omnivore/carnivore that eats the primary consumer.",
  },
  {
    id: "sci-f2-c2-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare secondary consumer with tertiary consumer.",
    back: "Secondary consumer: omnivore/carnivore (primary carnivore) that eats the primary consumer. Tertiary consumer: secondary carnivore that eats the secondary consumer, usually bigger.",
  },
  {
    id: "sci-f2-c2-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a decomposer? Give an example.",
    back: "An organism that breaks down dead plants and animals into simpler nutrients (saprophytism). Examples: mushrooms, mould and bacteria.",
  },
  {
    id: "sci-f2-c2-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is the original source of energy in an ecosystem?",
    back: "The Sun. Producers convert light energy into chemical energy through photosynthesis.",
  },
  {
    id: "sci-f2-c2-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a food chain?",
    back: "Shows the feeding relationship between organisms in a linear (one-direction) path.",
  },
  {
    id: "sci-f2-c2-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is a food web?",
    back: "The interconnection of a few food chains.",
  },
  {
    id: "sci-f2-c2-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare a food chain with a food web.",
    back: "Food chain: a single linear path. Food web: the interconnection of several food chains.",
  },
  {
    id: "sci-f2-c2-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is energy flow in an ecosystem?",
    back: "The transfer of energy from one organism to another through food chains/webs; some energy is lost as heat at each level.",
  },
  {
    id: "sci-f2-c2-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Is energy recycled like nutrients?",
    back: "No. Energy flows one way: at every level it is lost as heat through respiration and movement, and in consumers also through faeces (undigested food). Producers have no faecal loss. Only nutrients are recycled.",
  },
  {
    id: "sci-f2-c2-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front:
      "A fox (tertiary consumer) in a food web dies of disease. What is the effect on the bird (secondary consumer) and snail (primary consumer)?",
    back: "Bird population may increase (fewer predators); snail population may decrease as more birds feed on them.",
  },
  // Set 2: Nutrient Cycles & Interactions
  {
    id: "sci-f2-c2-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Name the three main nutrient cycles.",
    back: "Water cycle, carbon cycle, oxygen cycle.",
  },
  {
    id: "sci-f2-c2-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Describe the water cycle.",
    back: "Water evaporates, condenses into clouds, falls as rain and returns to rivers and seas; plants also release water vapour through transpiration.",
  },
  {
    id: "sci-f2-c2-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "How is carbon dioxide returned to the atmosphere in the carbon cycle?",
    back: "Through respiration by living things, decomposition of dead organisms and burning of fuels.",
  },
  {
    id: "sci-f2-c2-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is the role of decomposers in the nutrient cycle?",
    back: "They break down dead organisms and return nutrients to the soil to be used again by plants.",
  },
  {
    id: "sci-f2-c2-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the role of plants in the water cycle versus the carbon/oxygen cycle.",
    back: "Water cycle: roots absorb water, leaves release water via transpiration. Carbon/oxygen cycle: leaves carry out photosynthesis (absorb CO2, release O2).",
  },
  {
    id: "sci-f2-c2-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the role of respiration with photosynthesis in the oxygen cycle.",
    back: "Respiration: uses oxygen, releases carbon dioxide. Photosynthesis: absorbs carbon dioxide, releases oxygen.",
  },
  {
    id: "sci-f2-c2-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Why does unrestricted logging disrupt the water cycle and carbon cycle?",
    back: "Loss of trees reduces transpiration and carbon dioxide absorption through photosynthesis, disrupting both cycles.",
  },
  {
    id: "sci-f2-c2-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is symbiosis?",
    back: "A close interaction between two organisms of different species that live together.",
  },
  {
    id: "sci-f2-c2-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is mutualism?",
    back: "A symbiotic interaction that benefits BOTH organisms.",
  },
  {
    id: "sci-f2-c2-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is commensalism?",
    back: "An interaction that benefits ONLY ONE organism, without harming or benefiting the other.",
  },
  {
    id: "sci-f2-c2-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is parasitism?",
    back: "An interaction that benefits ONE organism (the parasite) and HARMS the other (the host).",
  },
  {
    id: "sci-f2-c2-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare mutualism, commensalism and parasitism.",
    back: "Mutualism: both benefit. Commensalism: one benefits, one unaffected. Parasitism: one benefits (parasite), one harmed (host).",
  },
  {
    id: "sci-f2-c2-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the mutualism examples: sea anemone & clown fish versus mynah & buffalo.",
    back: "Sea anemone & clown fish: anemone protects & feeds, clown fish cleans & provides nutrients. Mynah & buffalo: mynah eats buffalo's ticks, buffalo becomes free of ticks.",
  },
  {
    id: "sci-f2-c2-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the commensalism examples: remora & shark versus bird's nest fern.",
    back: "Remora & shark: remora eats shark's food scraps, shark unaffected. Bird's nest fern: grows on tree branches to get sunlight, tree unaffected.",
  },
  {
    id: "sci-f2-c2-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Is commensalism the same as a small mutualism?",
    back: "No. In commensalism, the second organism receives NO benefit at all — it is simply unaffected, unlike mutualism where both organisms benefit.",
  },
  {
    id: "sci-f2-c2-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Give an example of parasitism.",
    back: "A tapeworm in the human intestine: the tapeworm benefits while the human host is harmed.",
  },
  {
    id: "sci-f2-c2-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is prey-predator interaction?",
    back: "Involves one organism (predator) that eats another organism (prey).",
  },
  {
    id: "sci-f2-c2-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is competition?",
    back: "Happens when organisms compete for a limited supply of basic needs such as light, space, water, food and mates.",
  },
  {
    id: "sci-f2-c2-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare prey-predator with competition.",
    back: "Prey-predator: feeding between two different organisms. Competition: organisms competing for limited basic needs (can be within/between species).",
  },
  {
    id: "sci-f2-c2-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Does competition only occur between different species?",
    back: "No. Competition can occur within the same species (e.g. competition for a mate) as well as between different species for limited basic needs.",
  },
  // Set 3: Population Factors & Human Roles
  {
    id: "sci-f2-c2-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Name four factors that affect the size of a population.",
    back: "Disease, food supply, predators and weather (also migration and water supply).",
  },
  {
    id: "sci-f2-c2-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the disease factor with the food source factor in influencing population size.",
    back: "Disease: e.g. avian flu, tobacco mosaic virus, directly decreases population. Food source: e.g. panda & bamboo, if source decreases population is threatened with extinction.",
  },
  {
    id: "sci-f2-c2-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the predator factor with the weather factor in influencing population size.",
    back: "Predator: e.g. zebra & lion, prey population decreases with presence of predators. Weather: drought causes dry soil & forest fires, plant/animal populations decrease.",
  },
  {
    id: "sci-f2-c2-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the effect of migration with limited water supply on an ecosystem.",
    back: "Migration: e.g. cattle egret in Kuala Gula, reduces insect population. Limited water supply: long drought reduces paddy (producer) population, affecting the food web.",
  },
  {
    id: "sci-f2-c2-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "A paddy field experiences a long drought. What is the effect on the food web?",
    back: "The producer (paddy) population decreases due to lack of water, causing the entire food web depending on it to be affected.",
  },
  {
    id: "sci-f2-c2-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Why is the panda population threatened when bamboo forests are cleared?",
    back: "Pandas depend on bamboo as their primary food source; clearing forests destroys their food source and habitat.",
  },
  {
    id: "sci-f2-c2-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Why has the crow population in Malaysia increased?",
    back: "Due to an abundance of food scraps from humans.",
  },
  {
    id: "sci-f2-c2-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Which three physical factors affect where woodlice live?",
    back: "Temperature, light and humidity — woodlice gather in places of medium temperature that are dark and damp.",
  },
  {
    id: "sci-f2-c2-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the effects of forest logging with industrialisation.",
    back: "Logging: species extinction, soil erosion, greenhouse effect. Industrialisation: air/water/soil pollution, acid rain, greenhouse effect.",
  },
  {
    id: "sci-f2-c2-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the effects of agriculture with waste disposal.",
    back: "Agriculture: water pollution (overuse of pesticides/fertilisers), soil mineral loss. Waste disposal: water/soil pollution, foul odour, flash floods.",
  },
  {
    id: "sci-f2-c2-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Name 4 types of human activities and their main effects on the environment.",
    back: "Logging (species extinction, soil erosion), industrialisation (pollution, acid rain), agriculture (water pollution, soil mineral loss), waste disposal (pollution, flash floods).",
  },
  {
    id: "sci-f2-c2-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is biological control?",
    back: "A method using natural predators, parasites or pathogens to reduce the number of pests in an area.",
  },
  {
    id: "sci-f2-c2-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare the advantages and weaknesses of biological control.",
    back: "Advantages: eco-friendly, cheaper, doesn't affect human health. Weaknesses: slow effect, may disrupt ecosystem balance (new species introduced).",
  },
  {
    id: "sci-f2-c2-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front:
      "A farmer wants to control rats without chemical pesticides. What is the most appropriate method?",
    back: "Keeping owls as biological control — environmentally friendly and does not affect human health, although it takes longer to be effective.",
  },
  {
    id: "sci-f2-c2-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Name 5 examples of biological control used in Malaysian agriculture.",
    back: "Owls (rats), guppies (mosquito larvae), Bacillus thuringiensis (rhinoceros beetle), ladybird beetles (aphids), ducks (snails/insects in paddy fields).",
  },
  {
    id: "sci-f2-c2-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front:
      "Why is biological control considered to have an ecological risk despite being eco-friendly?",
    back: "Because it introduces a new species into the ecosystem, which can potentially disrupt the existing ecosystem balance.",
  },
  {
    id: "sci-f2-c2-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What are the five principles of the 5R?",
    back: "Refuse (refuse non-recyclable materials), Reduce (reduce usage), Reuse (reuse materials), Recycle (recycle materials), Repurpose (use materials for other purposes).",
  },
  {
    id: "sci-f2-c2-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Give two ways humans can help keep an ecosystem balanced.",
    back: "Replanting trees (reforestation) and managing waste properly to reduce pollution.",
  },
  {
    id: "sci-f2-c2-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "Compare a natural ecosystem with a man-made ecosystem.",
    back: "Both can be balanced. Natural ecosystem: forest, pond. Man-made ecosystem: e.g. aquarium — organisms and non-living components still interact harmoniously.",
  },
  {
    id: "sci-f2-c2-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 2",
    lang: "dlp",
    front: "What is the role of the Forestry Department in environmental law enforcement?",
    back: "Conducting patrols in forest areas, using helicopters, and setting up roadblocks to monitor timber-carrying lorries.",
  },
];
