import type { QuizQuestion } from "@/data/content";

export const scienceF2C2QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c2-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "What is the meaning of an ecosystem?",
    options: [
      "A group of organisms from the same species",
      "A few communities that live together in one habitat and interact with one another, including non-living components",
      "A type of plant that produces its own food",
      "An area inhabited only by poikilothermic animals",
    ],
    answerIndex: 1,
    explanation:
      "An ecosystem is a few communities that live together in one habitat and interact with one another, including non-living components such as water, air and soil.",
  },
  {
    id: "sci-f2-c2-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "An organism that produces its own food through photosynthesis is called a...",
    options: ["Primary consumer", "Decomposer", "Producer", "Secondary consumer"],
    answerIndex: 2,
    explanation: "A producer is an organism that produces its own food through photosynthesis. Most plants are producers.",
  },
  {
    id: "sci-f2-c2-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "What is the role of decomposers in an ecosystem?",
    options: [
      "Producing their own food through photosynthesis",
      "Breaking down dead animals and plants into simpler materials/nutrients",
      "Hunting primary consumers for food",
      "Competing for light and water",
    ],
    answerIndex: 1,
    explanation: "Decomposers break down dead animals and plants into simpler materials or nutrients, e.g. mushrooms and E. coli bacteria.",
  },
  {
    id: "sci-f2-c2-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "What is the difference between a food chain and a food web?",
    options: [
      "Food chain = a linear path; food web = the interconnection of several food chains",
      "Food chain is only for animals; food web is only for plants",
      "Both are the same thing",
      "A food web only involves producers",
    ],
    answerIndex: 0,
    explanation: "A food chain shows feeding relationships in a linear path, while a food web is the interconnection of several food chains.",
  },
  {
    id: "sci-f2-c2-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "The three main nutrient cycles learned in this chapter are...",
    options: [
      "Water cycle, carbon cycle, oxygen cycle",
      "Hydrogen cycle, nitrogen cycle, phosphorus cycle",
      "Heat cycle, light cycle, sound cycle",
      "Soil cycle, rock cycle, metal cycle",
    ],
    answerIndex: 0,
    explanation: "The three main nutrient cycles are the water cycle, carbon cycle and oxygen cycle.",
  },
  {
    id: "sci-f2-c2-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "A group of organisms from the same species that live in the same habitat is called a...",
    options: ["Community", "Ecosystem", "Population", "Habitat"],
    answerIndex: 2,
    explanation: "A population is a group of organisms of the same species that live in the same habitat.",
  },
  {
    id: "sci-f2-c2-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "An interaction that benefits both organisms is called...",
    options: ["Parasitism", "Commensalism", "Mutualism", "Competition"],
    answerIndex: 2,
    explanation: "Mutualism is a symbiotic interaction that benefits both organisms involved.",
  },
  {
    id: "sci-f2-c2-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "A tapeworm that lives in the human intestine and absorbs nutrients is an example of...",
    options: ["Mutualism", "Commensalism", "Parasitism", "Prey-predator"],
    answerIndex: 2,
    explanation: "The tapeworm (parasite) lives in the human intestine (host) and absorbs nutrients — this is an example of parasitism.",
  },
  {
    id: "sci-f2-c2-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "Which pair consists of one living component and one non-living component in a pond ecosystem?",
    options: ["Fish and snails", "Water and soil", "Sunlight and air", "Fish and water"],
    answerIndex: 3,
    explanation:
      "Fish are living components, while water is a non-living component of a pond ecosystem.",
  },
  {
    id: "sci-f2-c2-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Which of the following is NOT one of the 5R?",
    options: ["Reduce", "Reuse", "Replace", "Repurpose"],
    answerIndex: 2,
    explanation: "The 5R are Refuse, Reduce, Reuse, Recycle and Repurpose — 'Replace' is not part of the 5R.",
  },
  {
    id: "sci-f2-c2-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "Given the food chain: Paddy plant → Grasshopper → Sparrow → Owl. What is the trophic level of the sparrow?",
    options: ["Producer", "Primary consumer", "Secondary consumer", "Tertiary consumer"],
    answerIndex: 2,
    explanation: "The sparrow eats the grasshopper (primary consumer), so the sparrow is the secondary consumer in this food chain.",
  },
  {
    id: "sci-f2-c2-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Why is energy NOT recycled in an ecosystem, unlike nutrients?",
    options: [
      "Because energy is lost as heat through respiration and movement at every level, and through faeces in consumers",
      "Because energy is permanently stored in the producer's body",
      "Because only decomposers need energy",
      "Because energy only exists at the tertiary consumer level",
    ],
    answerIndex: 0,
    explanation:
      "At every trophic level energy is lost as heat through respiration and movement. Consumers lose extra energy in undigested food (faeces); producers do not, because they make their own food. That is why energy flows in one direction and is not recycled like nutrients.",
  },
  {
    id: "sci-f2-c2-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "What is the role of plant roots in the water cycle?",
    options: [
      "Releasing carbon dioxide into the atmosphere",
      "Absorbing water from the soil and holding the soil tightly to prevent erosion",
      "Carrying out respiration to produce oxygen",
      "Breaking down organic matter into nutrients",
    ],
    answerIndex: 1,
    explanation: "Plant roots absorb water from the soil and hold the soil tightly, slowing down underground water flow and preventing soil erosion.",
  },
  {
    id: "sci-f2-c2-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "How are respiration and decomposition related to the oxygen cycle?",
    options: [
      "Both processes produce oxygen",
      "Both processes use oxygen and release carbon dioxide",
      "Neither process involves oxygen at all",
      "Only respiration uses oxygen, decomposition does not",
    ],
    answerIndex: 1,
    explanation: "Respiration (by animals and plants) and decomposition (by bacteria and fungi) both use oxygen and release carbon dioxide.",
  },
  {
    id: "sci-f2-c2-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "A remora fish that latches onto a shark and gets food scraps without affecting the shark is an example of...",
    options: ["Mutualism", "Commensalism", "Parasitism", "Competition"],
    answerIndex: 1,
    explanation: "The remora fish (commensal) benefits (gets food) without affecting the shark (host) — this is an example of commensalism.",
  },
  {
    id: "sci-f2-c2-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "A pond contains populations of fish, snails, tadpoles and water hyacinths living together. Together, these populations form a...",
    options: ["organism", "population", "community", "habitat"],
    answerIndex: 2,
    explanation:
      "Several populations of different species living together in the same habitat form a community.",
  },
  {
    id: "sci-f2-c2-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "Why is the panda population threatened when bamboo forests are cleared?",
    options: [
      "Because pandas need bamboo as their primary food source and habitat",
      "Because pandas can only live in cold climates",
      "Because pandas compete with lions for food",
      "Because clearing forests increases water supply for pandas",
    ],
    answerIndex: 0,
    explanation: "Pandas depend on bamboo as their primary food source; clearing forests destroys their food source and habitat, threatening the panda population.",
  },
  {
    id: "sci-f2-c2-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "When cattle egrets migrate into an area, populations of insects such as grasshoppers, crickets and flies may decrease. Why?",
    options: [
      "The egrets produce substances that kill the insects",
      "The egrets feed on the insects",
      "The insects stop reproducing when the birds arrive",
      "The egrets reduce the amount of water in the habitat",
    ],
    answerIndex: 1,
    explanation:
      "Migration can alter population sizes in an ecosystem. Cattle egrets feed on insects, so insect populations may decrease when the number of egrets increases.",
  },
  {
    id: "sci-f2-c2-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "What is the main effect of industrialisation on the environment according to the table in this chapter?",
    options: [
      "Extinction of flora and fauna species only",
      "Pollution of air, water and soil; acid rain; greenhouse effect",
      "Increase in soil fertility",
      "Increase in clean water supply",
    ],
    answerIndex: 1,
    explanation: "Industrialisation causes pollution of air, water and soil, acid rain, and the greenhouse effect.",
  },
  {
    id: "sci-f2-c2-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 2",
    lang: "dlp",
    question: "What is one weakness of biological control as a method of pest control?",
    options: [
      "It directly affects human health",
      "It takes a long time before any effect is seen, and it might disrupt the balance of the ecosystem",
      "It is more expensive than chemical pesticides",
      "It can only be used in urban areas",
    ],
    answerIndex: 1,
    explanation: "Biological control takes a long time before any effect is seen, and the balance of the ecosystem might be disrupted because a new species is introduced.",
  },
  {
    id: "sci-f2-c2-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "In a food web, the fox population (tertiary consumer) dies due to disease. What is the most likely effect on the bird population (secondary consumer) and the snail population (primary consumer)?",
    options: [
      "Both bird and snail populations remain unchanged",
      "The bird population may increase (fewer predators), and the snail population may decrease as more birds feed on them",
      "Both bird and snail populations will become extinct simultaneously",
      "The snail population will increase drastically with no effect on the bird population",
    ],
    answerIndex: 1,
    explanation: "Without the fox as a predator, the bird population could increase; the increase in birds feeding on snails could then cause the snail population to decrease — this demonstrates the chain of effects within a food web.",
  },
  {
    id: "sci-f2-c2-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "A farmer wants to control the rat population in a palm oil plantation without using chemical pesticides. Which method is most appropriate and why?",
    options: [
      "Use chemical rat poison because it works faster",
      "Keep owls as a natural predator of rats, because it is environmentally friendly and does not affect human health even though it takes longer",
      "Burn the plantation area to kill the rats",
      "Plant more oil palm fruit to distract the rats",
    ],
    answerIndex: 1,
    explanation: "Keeping owls as biological control is the most appropriate method because it is environmentally friendly and does not affect human health, even though the effect takes longer than chemical pesticides.",
  },
  {
    id: "sci-f2-c2-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "A paddy field experiences a long drought season. How does this affect the food web in that area?",
    options: [
      "There is no effect because paddy does not need water",
      "The producer (paddy) population decreases due to lack of water, causing the entire food web that depends on it to be affected",
      "The tertiary consumer population will increase drastically",
      "The carbon cycle will stop immediately",
    ],
    answerIndex: 1,
    explanation: "Paddy requires a lot of water; a long drought season causes the producer (paddy) population to decrease, affecting the entire food web that depends on paddy as a basic energy source.",
  },
  {
    id: "sci-f2-c2-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "A farming area draws river water excessively for irrigation all year round. How does this disrupt the water cycle and the ecosystem there?",
    options: [
      "There is no effect because water always returns through rainfall at the same rate",
      "River and groundwater stores fall, so less water is available for plants and animals and the water cycle is disrupted",
      "The oxygen content of the atmosphere rises sharply",
      "The rate of photosynthesis increases because the soil becomes drier",
    ],
    answerIndex: 1,
    explanation:
      "Excessive use of water for agricultural and domestic purposes is one of the three main disruptions to the nutrient cycle. Over-extraction lowers river and groundwater stores, reducing the resources available to living things and disrupting the water cycle. Solutions include conserving water and harvesting rainwater.",
  },
  {
    id: "sci-f2-c2-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "Why can unrestricted forest logging disrupt the nutrient cycle and not just biodiversity?",
    options: [
      "Because logging has no effect on the nutrient cycle",
      "Because the loss of trees reduces transpiration and carbon dioxide absorption through photosynthesis, disrupting the water cycle and carbon cycle",
      "Because logging only affects the oxygen cycle, not the water or carbon cycle",
      "Because logging increases the rate of photosynthesis drastically",
    ],
    answerIndex: 1,
    explanation: "Unrestricted logging reduces the number of trees carrying out transpiration and photosynthesis (absorbing carbon dioxide), thereby disrupting the water cycle and carbon cycle in the ecosystem.",
  },
  {
    id: "sci-f2-c2-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "The grasshopper population in an agricultural ecosystem increases sharply. What is the most likely effect?",
    options: [
      "Plant populations increase because more animals are present",
      "Producer populations may decrease and the ecosystem balance may be disturbed",
      "All predators immediately become extinct",
      "The water cycle completely stops",
    ],
    answerIndex: 1,
    explanation:
      "A sharp increase in herbivores such as grasshoppers increases feeding on plants. Producer populations may decrease, affecting other populations in the food web.",
  },
  {
    id: "sci-f2-c2-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "An ecologist found that avian flu had spread in a poultry-rearing area. What factor influencing population size is illustrated in this situation?",
    options: ["Source of food", "Change of weather", "Disease", "Presence of predators"],
    answerIndex: 2,
    explanation: "Avian flu is an example of disease causing a decrease in animal (poultry) population — one of the main factors influencing population size.",
  },
  {
    id: "sci-f2-c2-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "If the number of decomposers in an ecosystem decreases greatly, what is the most likely result?",
    options: [
      "Dead matter accumulates and fewer nutrients are returned to the soil",
      "All consumers begin producing their own food",
      "Photosynthesis stops because there are no predators",
      "All non-living components disappear",
    ],
    answerIndex: 0,
    explanation:
      "Decomposers break down dead organisms and waste and return nutrients to the environment. Fewer decomposers can therefore disrupt nutrient cycling.",
  },
  {
    id: "sci-f2-c2-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "In a vegetable-garden food web: cabbage is eaten by caterpillars, snails and grasshoppers; caterpillars, snails and grasshoppers are eaten by birds; grasshoppers are also eaten by frogs; and birds and frogs are eaten by a snake. How many complete food chains can be built from this web?",
    options: ["Two", "Three", "Four", "Six"],
    answerIndex: 2,
    explanation:
      "Four chains: cabbage → caterpillar → bird → snake; cabbage → snail → bird → snake; cabbage → grasshopper → bird → snake; cabbage → grasshopper → frog → snake. Each chain starts with the producer and ends with the tertiary consumer — that is how a food web is interpreted.",
  },
  {
    id: "sci-f2-c2-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 2",
    lang: "dlp",
    question:
      "A student claims that 'competition only occurs between organisms of different species'. Is this claim accurate?",
    options: [
      "Accurate, because organisms of the same species never compete",
      "Not accurate, because competition can occur within the same species (e.g. competition for a mate) as well as between different species for limited basic needs",
      "Accurate, because only predators and prey can compete",
      "Not accurate, because competition only occurs to get water",
    ],
    answerIndex: 1,
    explanation: "Competition occurs when organisms in a habitat compete for limited basic needs such as light, space, water, food and mates — this can occur within the same species (e.g. competition for a mate) or between different species.",
  },
];
