import type { StructuredNotes } from "@/data/types";

export const sejarahF3C8Notes: StructuredNotes = {
  chapterSummary: "Bab ini menerangkan reaksi pemerintah negeri Melayu utara dan Johor terhadap tindakan Barat, tindakan raja Melayu, usaha pembesar dalam pemodenan negeri dan keberkesanan peranan pemerintah tempatan.",
  quickRevision: ["8.1 Reaksi Pemerintah Negeri-negeri Melayu Utara dan Johor Terhadap Tindakan Barat: Perjanjian Bangkok 1909 menimbulkan reaksi pemerintah negeri Melayu utara.","Tarikh penting 8.1: 1909: Perjanjian Bangkok","8.2 Tindakan Raja Melayu Menangani Cabaran Barat: Raja-raja Melayu menggunakan Durbar untuk menyuarakan bantahan terhadap pemusatan kuasa British.","Tarikh penting 8.2: 1903: Durbar Kuala Lumpur","8.3 Usaha Pembesar Melayu dalam Pemodenan Negeri: Pembesar Melayu memainkan peranan dalam pemodenan negeri melalui pentadbiran, pendidikan, ekonomi dan undang-undang.","Tarikh penting 8.3: 1895: Undang-Undang Tubuh Kerajaan Johor","8.4 Keberkesanan Peranan Pemerintah Tempatan dalam Menangani Cabaran Barat: Pemerintah tempatan berjaya melambatkan campur tangan British melalui diplomasi, undang-undang dan pemodenan.","Tarikh penting 8.4: 1895: Undang-Undang Tubuh Kerajaan Johor"],
  keyTerms: ["reaksi pemerintah","Perjanjian Bangkok 1909","negeri Melayu utara","Johor","kedaulatan","Durbar","diplomasi","Raja-raja Melayu","Penasihat British","ejen British","pemodenan negeri","pembesar Melayu","Majlis Mesyuarat","pentadbiran moden","keberkesanan","undang-undang tubuh","pemodenan"],
  keyExamFacts: ["Perjanjian Bangkok 1909 menimbulkan reaksi pemerintah negeri Melayu utara.","Perlis kehilangan wilayah Setul, Kedah kehilangan wilayah tertentu dan pemerintah membantah tindakan British-Siam.","Sultan Abdul Hamid Halim Shah menegaskan bantahan terhadap kesan Perjanjian Bangkok.","Raja-raja Melayu menggunakan Durbar untuk menyuarakan bantahan terhadap pemusatan kuasa British.","Durbar Kuala Lumpur 1903 menyaksikan Sultan Idris Murshidul Adzam Shah mengkritik pemusatan kuasa Residen Jeneral.","Durbar Pekan 1932, Durbar Klang 1937 dan Durbar Seri Menanti 1939 menjadi wadah tuntutan raja-raja Melayu.","Pembesar Melayu memainkan peranan dalam pemodenan negeri melalui pentadbiran, pendidikan, ekonomi dan undang-undang.","Sultan Abu Bakar bekerjasama dengan Majlis Mesyuarat Kerajaan untuk memodenkan Johor.","Pembesar Johor membantu membangunkan sistem pentadbiran moden.","Pemerintah tempatan berjaya melambatkan campur tangan British melalui diplomasi, undang-undang dan pemodenan.","Undang-Undang Tubuh Kerajaan Johor 1895 menetapkan sultan tidak boleh menyerahkan negeri kepada kuasa asing.","Undang-Undang Bagi Diri Kerajaan Terengganu 1911 mengandungi 53 fasal dan melarang penyerahan negeri kepada kuasa asing."],
  sections: [
    {
      title: "Bab Overview",
      subsections: [
        { title: "Sinopsis", content: "Bab ini menerangkan reaksi pemerintah negeri Melayu utara dan Johor terhadap tindakan Barat, tindakan raja Melayu, usaha pembesar dalam pemodenan negeri dan keberkesanan peranan pemerintah tempatan." },
        { title: "Apa yang akan dipelajari", bulletPoints: ["8.1 Reaksi Pemerintah Negeri-negeri Melayu Utara dan Johor Terhadap Tindakan Barat","8.2 Tindakan Raja Melayu Menangani Cabaran Barat","8.3 Usaha Pembesar Melayu dalam Pemodenan Negeri","8.4 Keberkesanan Peranan Pemerintah Tempatan dalam Menangani Cabaran Barat"] },
        { title: "Fokus UASA", bulletPoints: ["Kenal pasti kronologi, tokoh, tempat, perjanjian dan kesan.","Bezakan sebab, strategi dan kesan peluasan kuasa Barat.","Gunakan kata kunci seperti kedaulatan, pentadbiran, ekonomi, penentangan dan pemodenan."] },
      ],
    },
    {
      title: "8.1 Reaksi Pemerintah Negeri-negeri Melayu Utara dan Johor Terhadap Tindakan Barat",
      subsections: [
        { title: "Ringkasan", content: "Reaksi Pemerintah Negeri-negeri Melayu Utara dan Johor Terhadap Tindakan Barat menerangkan perjanjian bangkok 1909 menimbulkan reaksi pemerintah negeri melayu utara. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Perjanjian Bangkok 1909 menimbulkan reaksi pemerintah negeri Melayu utara.","Perlis kehilangan wilayah Setul, Kedah kehilangan wilayah tertentu dan pemerintah membantah tindakan British-Siam.","Sultan Abdul Hamid Halim Shah menegaskan bantahan terhadap kesan Perjanjian Bangkok.","Sultan Zainal Abidin III mengecam tindakan British dan Siam.","Johor berusaha mengekalkan kedaulatan melalui diplomasi dan pemodenan."] },
        { title: "Kata kunci", bulletPoints: ["reaksi pemerintah","Perjanjian Bangkok 1909","negeri Melayu utara","Johor","kedaulatan"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Abdul Hamid Halim Shah","Sultan Muhammad IV","Sultan Zainal Abidin III","Sultan Abu Bakar","Sultan Ibrahim"] },
        { title: "Tarikh penting", bulletPoints: ["1909: Perjanjian Bangkok"] },
        { title: "Tempat penting", bulletPoints: ["Perlis","Kedah","Kelantan","Terengganu","Johor","Setul"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Bangkok 1909"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Perjanjian dibuat tanpa persetujuan penuh pemerintah Melayu","Wilayah dan kedaulatan negeri terjejas","British mahu meluaskan kuasa"] },
        { title: "Kesan", bulletPoints: ["Pemerintah Melayu membantah","British tetap menempatkan penasihat","Kesedaran mempertahankan kedaulatan meningkat"] },
        { title: "Kepentingan", bulletPoints: ["Menunjukkan raja Melayu tidak pasif dalam menghadapi tindakan Barat."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Reaksi pemerintah membawa kepada tindakan lebih tersusun melalui Durbar, diplomasi dan undang-undang tubuh."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta kesan Perjanjian Bangkok menunjukkan wilayah yang terjejas di negeri Melayu utara.","1909 Perjanjian Bangkok dan reaksi pemerintah"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "8.2 Tindakan Raja Melayu Menangani Cabaran Barat",
      subsections: [
        { title: "Ringkasan", content: "Tindakan Raja Melayu Menangani Cabaran Barat menerangkan raja-raja melayu menggunakan durbar untuk menyuarakan bantahan terhadap pemusatan kuasa british. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Raja-raja Melayu menggunakan Durbar untuk menyuarakan bantahan terhadap pemusatan kuasa British.","Durbar Kuala Lumpur 1903 menyaksikan Sultan Idris Murshidul Adzam Shah mengkritik pemusatan kuasa Residen Jeneral.","Durbar Pekan 1932, Durbar Klang 1937 dan Durbar Seri Menanti 1939 menjadi wadah tuntutan raja-raja Melayu.","Sultan Abu Bakar mengadakan hubungan diplomatik untuk mengukuhkan kedudukan Johor.","Sultan Zainal Abidin III enggan menerima Penasihat British dan hanya menerima ejen British."] },
        { title: "Kata kunci", bulletPoints: ["Durbar","diplomasi","Raja-raja Melayu","Penasihat British","ejen British"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Idris Murshidul Adzam Shah","Sultan Iskandar Shah","Sultan Abu Bakar Riayatuddin Al-Muazzam Shah","Sultan Hisamuddin Alam Shah","Sultan Abu Bakar Johor","Sultan Zainal Abidin III"] },
        { title: "Tarikh penting", bulletPoints: ["1903: Durbar Kuala Lumpur","1932: Durbar Pekan","1937: Durbar Klang","1939: Durbar Seri Menanti","24 Mei 1919: Perjanjian Terengganu-British"] },
        { title: "Tempat penting", bulletPoints: ["Kuala Lumpur","Pekan","Klang","Seri Menanti","Johor","Terengganu"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Terengganu-British 1919"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Durbar; Penasihat British"]] } },
        { title: "Sebab", bulletPoints: ["Pemusatan kuasa British","Kuasa raja dan negeri terhakis","Penasihat British semakin mengawal pentadbiran"] },
        { title: "Kesan", bulletPoints: ["Raja Melayu menyuarakan tuntutan","Durbar menjadi platform perbincangan","Kedaulatan dipertahankan melalui diplomasi"] },
        { title: "Kepentingan", bulletPoints: ["Membuktikan kebijaksanaan raja Melayu menggunakan saluran rasmi, diplomasi dan rundingan."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Durbar dan diplomasi melengkapkan usaha undang-undang tubuh di Johor dan Terengganu."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Garis masa Durbar menunjukkan kesinambungan usaha Raja-raja Melayu menuntut pemulihan kuasa.","1903","1919","1932","1937","1939"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "8.3 Usaha Pembesar Melayu dalam Pemodenan Negeri",
      subsections: [
        { title: "Ringkasan", content: "Usaha Pembesar Melayu dalam Pemodenan Negeri menerangkan pembesar melayu memainkan peranan dalam pemodenan negeri melalui pentadbiran, pendidikan, ekonomi dan undang-undang. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Pembesar Melayu memainkan peranan dalam pemodenan negeri melalui pentadbiran, pendidikan, ekonomi dan undang-undang.","Sultan Abu Bakar bekerjasama dengan Majlis Mesyuarat Kerajaan untuk memodenkan Johor.","Pembesar Johor membantu membangunkan sistem pentadbiran moden.","Pembesar Terengganu bekerjasama dengan Sultan Zainal Abidin III mempertahankan kedaulatan negeri."] },
        { title: "Kata kunci", bulletPoints: ["pemodenan negeri","pembesar Melayu","Majlis Mesyuarat","pentadbiran moden","diplomasi"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Abu Bakar","Dato' Jaafar bin Muhammad","Dato' Abdul Rahman Andak","Sultan Zainal Abidin III","Pembesar Terengganu"] },
        { title: "Tarikh penting", bulletPoints: ["1895: Undang-Undang Tubuh Kerajaan Johor","1911: Undang-Undang Bagi Diri Kerajaan Terengganu"] },
        { title: "Tempat penting", bulletPoints: ["Johor","Terengganu","London"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Undang-Undang Tubuh Kerajaan Johor 1895; Undang-Undang Bagi Diri Kerajaan Terengganu 1911"],["Organisasi / pentadbiran","Majlis Mesyuarat"]] } },
        { title: "Sebab", bulletPoints: ["Keperluan memodenkan pentadbiran","Ancaman campur tangan British","Keinginan mempertahankan kedaulatan"] },
        { title: "Kesan", bulletPoints: ["Pentadbiran negeri lebih tersusun","British sukar menguasai negeri secara tergesa-gesa","Pembesar tempatan berperanan sebagai pentadbir moden"] },
        { title: "Kepentingan", bulletPoints: ["Murid melihat pembesar Melayu sebagai agen pemodenan, bukan hanya tokoh tradisional."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Pemodenan pentadbiran menjadi strategi menghadapi cabaran Barat."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Rajah hubungan raja-pembesar menunjukkan kerjasama dalam pemodenan negeri.","1895 Johor","1911 Terengganu","awal abad ke-20 pemodenan pentadbiran"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "8.4 Keberkesanan Peranan Pemerintah Tempatan dalam Menangani Cabaran Barat",
      subsections: [
        { title: "Ringkasan", content: "Keberkesanan Peranan Pemerintah Tempatan dalam Menangani Cabaran Barat menerangkan pemerintah tempatan berjaya melambatkan campur tangan british melalui diplomasi, undang-undang dan pemodenan. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Pemerintah tempatan berjaya melambatkan campur tangan British melalui diplomasi, undang-undang dan pemodenan.","Undang-Undang Tubuh Kerajaan Johor 1895 menetapkan sultan tidak boleh menyerahkan negeri kepada kuasa asing.","Undang-Undang Bagi Diri Kerajaan Terengganu 1911 mengandungi 53 fasal dan melarang penyerahan negeri kepada kuasa asing.","Walaupun British akhirnya meluaskan kuasa, usaha pemerintah tempatan mempertahankan identiti dan kedaulatan negeri tetap berkesan sebagai warisan politik."] },
        { title: "Kata kunci", bulletPoints: ["keberkesanan","kedaulatan","undang-undang tubuh","pemodenan","diplomasi"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Abu Bakar","Sultan Ibrahim","Sultan Zainal Abidin III","Sultan Muhammad II","Undang Luak Rembau"] },
        { title: "Tarikh penting", bulletPoints: ["1895: Undang-Undang Tubuh Kerajaan Johor","1911: Undang-Undang Bagi Diri Kerajaan Terengganu","1914: Perjanjian Johor-British"] },
        { title: "Tempat penting", bulletPoints: ["Johor","Terengganu","Perak","Selangor","Sungai Ujong","Pahang","Negeri Sembilan"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Johor-British 1914"],["Undang-undang","Undang-Undang Tubuh Kerajaan Johor 1895; Undang-Undang Bagi Diri Kerajaan Terengganu 1911"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Cabaran peluasan kuasa Barat","Keperluan mempertahankan negeri","Pemusatan kuasa British"] },
        { title: "Kesan", bulletPoints: ["Campur tangan British dapat dilambatkan","Identiti negeri dipertahankan","Pentadbiran moden tempatan berkembang","Warisan institusi raja terus kekal"] },
        { title: "Kepentingan", bulletPoints: ["Menyimpulkan kebijaksanaan pemerintah tempatan sebagai asas patriotisme dan jati diri negara."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Keberkesanan bergantung pada gabungan diplomasi, undang-undang, pemodenan dan kesatuan pemerintah-pembesar."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Rajah perbandingan menunjukkan negeri yang menerima Residen/Penasihat dan negeri yang menggunakan undang-undang tubuh untuk mempertahankan kuasa.","1895","1911","1914","1930-an Durbar"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "Rumusan Bab",
      subsections: [
        { title: "Imbas Kembali", bulletPoints: ["8.1: reaksi pemerintah, Perjanjian Bangkok 1909, negeri Melayu utara, Johor","8.2: Durbar, diplomasi, Raja-raja Melayu, Penasihat British","8.3: pemodenan negeri, pembesar Melayu, Majlis Mesyuarat, pentadbiran moden","8.4: keberkesanan, kedaulatan, undang-undang tubuh, pemodenan"] },
        { title: "Kata Kunci Peperiksaan", bulletPoints: ["reaksi pemerintah","Perjanjian Bangkok 1909","negeri Melayu utara","Johor","kedaulatan","Durbar","diplomasi","Raja-raja Melayu","Penasihat British","ejen British","pemodenan negeri","pembesar Melayu","Majlis Mesyuarat","pentadbiran moden","keberkesanan","undang-undang tubuh","pemodenan"] },
      ],
    }
  ],
};
