import type { Flashcard } from "@/data/content";

export const scienceF2C1FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c1-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud biodiversiti?",
    back: "Kepelbagaian organisma sama ada mikroorganisma, haiwan atau tumbuhan, termasuk kepelbagaian genetik.",
  },
  {
    id: "sci-f2-c1-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Malaysia ialah salah satu daripada berapa negara megabiodiversiti?",
    back: "12 negara megabiodiversiti di dunia.",
  },
  {
    id: "sci-f2-c1-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud kepelbagaian genetik?",
    back: "Kepelbagaian dalam sesuatu spesies berdasarkan variasi gen setiap organisma.",
  },
  {
    id: "sci-f2-c1-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Namakan enam kepentingan biodiversiti.",
    back: "Sumber makanan, perubatan, imbangan alam, bahan mentah industri, tempat rekreasi, pendidikan.",
  },
  {
    id: "sci-f2-c1-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bila Hari Biodiversiti Sedunia disambut?",
    back: "22 Mei setiap tahun.",
  },
  {
    id: "sci-f2-c1-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah Akta Perlindungan Hidupan Liar 1972?",
    back: "Akta yang mengharamkan pembunuhan atau perdagangan haiwan dan tumbuhan endemik serta terancam.",
  },
  {
    id: "sci-f2-c1-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud spesies endemik?",
    back: "Spesies yang hidup berkelompok dalam habitat terhad di lokasi tertentu sahaja.",
  },
  {
    id: "sci-f2-c1-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Berikan 3 contoh spesies endemik di Malaysia.",
    back: "Bunga rafflesia, periuk kera (Nepenthes rajah), penyu belimbing (harimau Malaya/gajah Borneo juga diterima).",
  },
  {
    id: "sci-f2-c1-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud pemuliharaan in situ?",
    back: "Memelihara spesies dalam habitat semula jadinya, seperti taman negara dan taman laut.",
  },
  {
    id: "sci-f2-c1-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud pemuliharaan ex situ?",
    back: "Memelihara spesies di luar habitat semula jadinya, seperti di zoo dan taman botani.",
  },
  {
    id: "sci-f2-c1-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah dua kumpulan utama klasifikasi haiwan?",
    back: "Invertebrata (tanpa tulang belakang) dan vertebrata (ada tulang belakang).",
  },
  {
    id: "sci-f2-c1-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Namakan lima kumpulan vertebrata.",
    back: "Ikan, amfibia, reptilia, burung, mamalia.",
  },
  {
    id: "sci-f2-c1-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud poikiloterma?",
    back: "Organisma yang suhu badannya berubah mengikut suhu persekitaran.",
  },
  {
    id: "sci-f2-c1-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud homeoterma?",
    back: "Haiwan yang suhu badannya malar (tetap) dan tidak dipengaruhi suhu persekitaran.",
  },
  {
    id: "sci-f2-c1-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Berikan 3 ciri ikan.",
    back: "Poikiloterma, bersisik licin & keras, bernafas melalui insang, bertelur, persenyawaan luaran.",
  },
  {
    id: "sci-f2-c1-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Berikan 2 ciri unik amfibia.",
    back: "Hidup di darat dan air; bertelur seperti agar-agar tanpa cengkerang; anak bernafas melalui insang, dewasa melalui peparu dan kulit lembap.",
  },
  {
    id: "sci-f2-c1-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah dua kumpulan utama klasifikasi tumbuhan?",
    back: "Tumbuhan tidak berbunga dan tumbuhan berbunga.",
  },
  {
    id: "sci-f2-c1-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Namakan tiga jenis tumbuhan tidak berbunga.",
    back: "Lumut, paku pakis, konifer.",
  },
  {
    id: "sci-f2-c1-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah kotiledon?",
    back: "Makanan simpanan dalam biji benih yang digunakan untuk bercambah.",
  },
  {
    id: "sci-f2-c1-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah maksud kekunci dikotomi?",
    back: "Kaedah mengenal pasti dan mengklasifikasikan organisma secara sistematik melalui satu siri kuplet ciri.",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c1-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan in situ dengan ex situ.",
    back: "In situ: pemuliharaan dalam habitat asal (taman negara). Ex situ: pemuliharaan luar habitat asal (zoo, taman botani).",
  },
  {
    id: "sci-f2-c1-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan invertebrata dengan vertebrata.",
    back: "Invertebrata: tanpa tulang belakang (contoh: siput, serangga). Vertebrata: ada tulang belakang (contoh: ikan, mamalia).",
  },
  {
    id: "sci-f2-c1-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan invertebrata tanpa kaki dan berkaki.",
    back: "Tanpa kaki: span, koral, lintah (sebahagian bersegmen). Berkaki: badan bersegmen + eksoskeleton keras, contoh serangga dan labah-labah.",
  },
  {
    id: "sci-f2-c1-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan ikan dan amfibia dari segi habitat.",
    back: "Ikan hanya hidup di air; amfibia hidup di darat dan di air.",
  },
  {
    id: "sci-f2-c1-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan telur amfibia dan telur reptilia.",
    back: "Telur amfibia: seperti agar-agar, tanpa cengkerang. Telur reptilia: bercengkerang keras.",
  },
  {
    id: "sci-f2-c1-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan persenyawaan ikan/amfibia dengan reptilia/burung/mamalia.",
    back: "Ikan & amfibia: persenyawaan luaran. Reptilia, burung & mamalia: persenyawaan dalaman.",
  },
  {
    id: "sci-f2-c1-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan burung dan mamalia dari segi penutup badan.",
    back: "Burung: ditutupi bulu (feathers). Mamalia: ditutupi bulu tebal/rambut (fur/hair).",
  },
  {
    id: "sci-f2-c1-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah ciri unik mamalia yang tidak dimiliki kumpulan vertebrata lain?",
    back: "Mamalia melahirkan anak hidup dan menyusukan anaknya.",
  },
  {
    id: "sci-f2-c1-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan lumut dengan paku pakis dari segi sistem vaskular.",
    back: "Lumut: tidak berpembuluh (non-vaskular). Paku pakis: berpembuluh (vaskular).",
  },
  {
    id: "sci-f2-c1-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan paku pakis dengan konifer dari segi cara membiak.",
    back: "Paku pakis: membiak melalui spora. Konifer: membiak melalui kon.",
  },
  {
    id: "sci-f2-c1-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan akar monokotiledon dan dikotiledon.",
    back: "Monokotiledon: akar serabut (fibrus). Dikotiledon: akar tunjang.",
  },
  {
    id: "sci-f2-c1-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan daun monokotiledon dan dikotiledon.",
    back: "Monokotiledon: daun berurat selari. Dikotiledon: daun berurat seperti jaringan/jaring-jaring.",
  },
  {
    id: "sci-f2-c1-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan batang monokotiledon dan dikotiledon.",
    back: "Monokotiledon: kebanyakan batang tidak berkayu. Dikotiledon: berbatang berkayu.",
  },
  {
    id: "sci-f2-c1-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Berikan contoh tumbuhan monokotiledon dan dikotiledon.",
    back: "Monokotiledon: padi, jagung, orkid. Dikotiledon: tomato, durian, teratai, bunga matahari.",
  },
  {
    id: "sci-f2-c1-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan tumbuhan tidak berpembuluh dengan berpembuluh.",
    back: "Tidak berpembuluh: kecil, ringkas, tanpa sistem pengangkutan (lumut). Berpembuluh: ada akar, batang, daun sebenar dengan sistem pengangkutan air & makanan.",
  },
  {
    id: "sci-f2-c1-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah perbezaan reptilia dan burung dari segi suhu badan?",
    back: "Reptilia: poikiloterma (suhu berubah). Burung: homeoterma (suhu tetap).",
  },
  {
    id: "sci-f2-c1-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan kepentingan biodiversiti 'bahan mentah industri' dengan 'tempat rekreasi'.",
    back: "Bahan mentah: balak/buluh/rotan untuk perabot & bangunan. Tempat rekreasi: kawasan kaya biodiversiti dimajukan untuk pelancongan/aktiviti luar.",
  },
  {
    id: "sci-f2-c1-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah perbezaan antara invertebrata 3 pasang kaki dengan lebih 3 pasang kaki?",
    back: "3 pasang kaki: serangga (semut, rama-rama, lipas). Lebih 3 pasang: labah-labah, lipan, udang, skorpion.",
  },
  {
    id: "sci-f2-c1-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bandingkan kulit reptilia dengan kulit amfibia.",
    back: "Reptilia: bersisik dan berkulit keras. Amfibia: berkulit lembap.",
  },
  {
    id: "sci-f2-c1-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Bagaimana kekunci dikotomi haiwan dan tumbuhan berbeza pada langkah pertama?",
    back: "Haiwan: bermula dengan poikiloterma/homeoterma. Tumbuhan: bermula dengan tidak berbunga/berbunga.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c1-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[KBAT] Haiwan X poikiloterma dan berkulit bersisik (jawab ke 4). Jika tiada sirip, apakah haiwan X?",
    back: "Ular (mengikut kekunci dikotomi contoh: poikiloterma → bersisik → tiada sirip → Ular).",
  },
  {
    id: "sci-f2-c1-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[KBAT] Mengapa serangga (950,000 spesies) tetap berjaya walaupun poikiloterma?",
    back: "Eksoskeleton keras melindungi badan, saiz kecil membolehkan menghuni banyak ceruk habitat, kadar pembiakan tinggi.",
  },
  {
    id: "sci-f2-c1-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Berapa spesies serangga dianggarkan wujud di dunia?",
    back: "950,000 spesies serangga.",
  },
  {
    id: "sci-f2-c1-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Berapa spesies burung dijumpai di Malaysia, dan bagaimana pecahannya?",
    back: "Hampir 742 spesies: sekurang-kurangnya 522 spesies tempatan, 192 spesies penghijrah, 52 spesies tempatan berciri penghijrah.",
  },
  {
    id: "sci-f2-c1-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Burung apakah yang menjadi burung rasmi negeri Sarawak dan dilindungi?",
    back: "Burung kenyalang (rhinoceros hornbill).",
  },
  {
    id: "sci-f2-c1-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah lumut tumbuhan berpembuluh?",
    back: "Tidak. Lumut TIDAK berpembuluh; hanya paku pakis dan konifer yang berpembuluh dalam kumpulan tidak berbunga.",
  },
  {
    id: "sci-f2-c1-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah burung poikiloterma kerana ia bertelur?",
    back: "Tidak. Burung adalah homeoterma (suhu badan tetap) walaupun bertelur — jenis pembiakan tidak menentukan poikiloterma/homeoterma.",
  },
  {
    id: "sci-f2-c1-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[KBAT] Haiwan baharu berbulu, melahirkan anak dan menyusukannya. Kumpulan vertebrata apa?",
    back: "Mamalia — ciri melahirkan anak hidup dan menyusukan adalah unik kepada mamalia.",
  },
  {
    id: "sci-f2-c1-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[KBAT] Tumbuhan Y tidak berbunga, berpembuluh dan menghasilkan biji benih. Apakah tumbuhan Y mengikut kekunci dikotomi standard?",
    back: "Gnetum sp. (tidak berbunga → berpembuluh → menghasilkan biji benih).",
  },
  {
    id: "sci-f2-c1-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Mengapa setiap kuplet kekunci dikotomi hanya ada 2 pilihan, (a) dan (b)?",
    back: "Kerana 'dikotomi' bermaksud pembahagian kepada dua; ini memastikan klasifikasi sistematik dan tidak mengelirukan.",
  },
  {
    id: "sci-f2-c1-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[Fakta Penting] Apakah keistimewaan bunga rafflesia disebut dalam Blog Sains?",
    back: "Bunga terbesar di dunia, parasit, berbau reput semasa berbunga, tiada daun (tiada fotosintesis) dan tiada akar sebenar.",
  },
  {
    id: "sci-f2-c1-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan 'bezakan in situ dan ex situ' dengan markah penuh?",
    back: "Nyatakan lokasi sebagai pembeza utama: in situ = dalam habitat asal (taman negara); ex situ = luar habitat asal (zoo) — sertakan contoh.",
  },
  {
    id: "sci-f2-c1-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[KBAT] Bagaimana kepelbagaian genetik membantu spesies bertahan perubahan persekitaran mendadak?",
    back: "Variasi gen membolehkan sebahagian individu mempunyai ciri yang lebih sesuai untuk terus hidup dalam keadaan baharu.",
  },
  {
    id: "sci-f2-c1-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah spesies endemik sama dengan spesies terancam?",
    back: "Tidak semestinya. Endemik bermaksud habitat terhad di satu lokasi; ia tidak semestinya terancam kepupusan, walaupun selalunya tumpang-tindih.",
  },
  {
    id: "sci-f2-c1-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Namakan dua aktiviti program pembiakan untuk pemuliharaan biodiversiti.",
    back: "Tapak semaian anak benih (penghutanan semula) dan tempat penetasan telur penyu.",
  },
  {
    id: "sci-f2-c1-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[KBAT] Mengapa ex situ (zoo/taman botani) penting walaupun bukan habitat asal?",
    back: "Membolehkan pemantauan rapi, pembiakan terkawal dan penyelidikan untuk menyelamatkan spesies yang sangat terancam.",
  },
  {
    id: "sci-f2-c1-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Apakah perbezaan utama yang membahagikan invertebrata pada langkah pertama kekunci dikotomi haiwan?",
    back: "Ada kaki atau tanpa kaki.",
  },
  {
    id: "sci-f2-c1-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[Kesilapan Lazim] Bolehkah kekunci dikotomi mempunyai tiga pilihan dalam satu kuplet?",
    back: "Tidak. Setiap kuplet mesti hanya ada dua pilihan, (a) dan (b), supaya klasifikasi tetap sistematik.",
  },
  {
    id: "sci-f2-c1-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "[KBAT] Seekor haiwan poikiloterma, telur bercengkerang, persenyawaan dalaman, bersisik keras. Kumpulan?",
    back: "Reptilia (contoh: ular, buaya, iguana, penyu).",
  },
  {
    id: "sci-f2-c1-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "bm",
    front: "Ringkaskan peta konsep Bab 1 dalam satu ayat.",
    back: "Biodiversiti merangkumi maksud, pengurusan dan kepentingan, serta klasifikasi haiwan (vertebrata & invertebrata) dan tumbuhan (berbunga & tidak berbunga) menggunakan kekunci dikotomi.",
  },
];
