import type { Flashcard } from "@/data/content";

export const scienceF2C1FlashcardsDLP: Flashcard[] = [
  // Deck 1: Basics (Cards 1-20)
  {
    id: "sci-f2-c1-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is the meaning of biodiversity?",
    back: "The diversity of organisms, whether microorganisms, animals or plants, including genetic diversity.",
  },
  {
    id: "sci-f2-c1-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Malaysia is one of how many megabiodiversity countries?",
    back: "12 megabiodiversity countries in the world.",
  },
  {
    id: "sci-f2-c1-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is genetic diversity?",
    back: "Diversity within a species based on variations in the genes of each organism.",
  },
  {
    id: "sci-f2-c1-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Name six importance of biodiversity.",
    back: "Source of food, medical, balance in nature, raw materials for industries, recreational places, education.",
  },
  {
    id: "sci-f2-c1-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "When is the International Day for Biological Diversity celebrated?",
    back: "22 May every year.",
  },
  {
    id: "sci-f2-c1-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is the Wildlife Protection Act 1972?",
    back: "An act that bans the killing or trade of endemic and endangered animals and plants.",
  },
  {
    id: "sci-f2-c1-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is an endemic species?",
    back: "A species that lives in clusters within a restricted habitat at a specific location only.",
  },
  {
    id: "sci-f2-c1-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Give 3 examples of endemic species in Malaysia.",
    back: "Rafflesia flower, pitcher plant (Nepenthes rajah), leatherback turtle (Malayan tiger/Borneo Pygmy elephant also accepted).",
  },
  {
    id: "sci-f2-c1-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is in situ conservation?",
    back: "Preserving species within their natural habitat, such as in national parks and marine parks.",
  },
  {
    id: "sci-f2-c1-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is ex situ conservation?",
    back: "Preserving species outside their natural habitat, such as in zoos and botanical parks.",
  },
  {
    id: "sci-f2-c1-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What are the two main groups in animal classification?",
    back: "Invertebrates (without backbone) and vertebrates (with backbone).",
  },
  {
    id: "sci-f2-c1-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Name the five groups of vertebrates.",
    back: "Fish, amphibians, reptiles, birds, mammals.",
  },
  {
    id: "sci-f2-c1-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is a poikilotherm?",
    back: "An organism whose body temperature changes according to the surrounding temperature.",
  },
  {
    id: "sci-f2-c1-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is a homeotherm?",
    back: "An animal whose body temperature is constant and not influenced by the surrounding temperature.",
  },
  {
    id: "sci-f2-c1-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Give 3 characteristics of fish.",
    back: "Poikilothermic, covered in hard slimy scales, breathe through gills, lay eggs, external fertilisation.",
  },
  {
    id: "sci-f2-c1-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Give 2 unique characteristics of amphibians.",
    back: "Live on land and in water; lay jelly-like eggs without a shell; young breathe through gills, adults through lungs and moist skin.",
  },
  {
    id: "sci-f2-c1-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What are the two main groups in plant classification?",
    back: "Non-flowering plants and flowering plants.",
  },
  {
    id: "sci-f2-c1-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Name three types of non-flowering plants.",
    back: "Moss, fern, conifer.",
  },
  {
    id: "sci-f2-c1-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is a cotyledon?",
    back: "Stored food in a seed used by the seed to germinate.",
  },
  {
    id: "sci-f2-c1-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is a dichotomous key?",
    back: "A method to identify and classify organisms systematically through a series of couplets of characteristics.",
  },

  // Deck 2: Understanding (Cards 21-40)
  {
    id: "sci-f2-c1-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare in situ and ex situ conservation.",
    back: "In situ: conservation within natural habitat (national park). Ex situ: conservation outside natural habitat (zoo, botanical park).",
  },
  {
    id: "sci-f2-c1-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare invertebrates and vertebrates.",
    back: "Invertebrates: without backbone (e.g. snail, insect). Vertebrates: with backbone (e.g. fish, mammal).",
  },
  {
    id: "sci-f2-c1-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare invertebrates without legs and with legs.",
    back: "Without legs: sponge, coral, leech (some segmented). With legs: segmented body + hard exoskeleton, e.g. insects and spiders.",
  },
  {
    id: "sci-f2-c1-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare fish and amphibians by habitat.",
    back: "Fish live only in water; amphibians live on land and in water.",
  },
  {
    id: "sci-f2-c1-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare amphibian eggs and reptile eggs.",
    back: "Amphibian eggs: jelly-like, no shell. Reptile eggs: hard shell.",
  },
  {
    id: "sci-f2-c1-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare fertilisation in fish/amphibians vs reptiles/birds/mammals.",
    back: "Fish & amphibians: external fertilisation. Reptiles, birds & mammals: internal fertilisation.",
  },
  {
    id: "sci-f2-c1-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare birds and mammals by body covering.",
    back: "Birds: covered with feathers. Mammals: covered with fur or hair.",
  },
  {
    id: "sci-f2-c1-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What unique characteristic do mammals have that other vertebrate groups don't?",
    back: "Mammals give birth to live young and nurse their young.",
  },
  {
    id: "sci-f2-c1-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare moss and fern by vascular system.",
    back: "Moss: non-vascular. Fern: vascular.",
  },
  {
    id: "sci-f2-c1-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare fern and conifer by reproduction method.",
    back: "Fern: reproduces by spores. Conifer: reproduces by bearing cones.",
  },
  {
    id: "sci-f2-c1-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare monocotyledon and dicotyledon roots.",
    back: "Monocotyledon: fibrous root. Dicotyledon: tap root.",
  },
  {
    id: "sci-f2-c1-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare monocotyledon and dicotyledon leaves.",
    back: "Monocotyledon: parallel-veined leaves. Dicotyledon: network-like veined leaves.",
  },
  {
    id: "sci-f2-c1-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare monocotyledon and dicotyledon stems.",
    back: "Monocotyledon: mostly non-woody stem. Dicotyledon: woody stem.",
  },
  {
    id: "sci-f2-c1-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Give examples of monocotyledon and dicotyledon plants.",
    back: "Monocotyledon: paddy, maize, orchid. Dicotyledon: tomato, durian, lotus, sunflower.",
  },
  {
    id: "sci-f2-c1-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare non-vascular and vascular plants.",
    back: "Non-vascular: small, simple, no transport system (moss). Vascular: true roots, stems, leaves with water/food transport system.",
  },
  {
    id: "sci-f2-c1-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is the difference between reptiles and birds in body temperature?",
    back: "Reptiles: poikilothermic (temperature changes). Birds: homeothermic (temperature constant).",
  },
  {
    id: "sci-f2-c1-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare the importance 'raw materials for industries' with 'recreational places'.",
    back: "Raw materials: timber/bamboo/rattan for furniture & buildings. Recreational: biodiversity-rich areas developed for tourism/outdoor activities.",
  },
  {
    id: "sci-f2-c1-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is the difference between invertebrates with three pairs of legs and more than three pairs?",
    back: "Three pairs: insects (ant, butterfly, cockroach). More than three pairs: spider, centipede, prawn, scorpion.",
  },
  {
    id: "sci-f2-c1-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Compare reptile skin and amphibian skin.",
    back: "Reptiles: scaly and hard skin. Amphibians: moist skin.",
  },
  {
    id: "sci-f2-c1-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "How do dichotomous keys for animals and plants differ at the first step?",
    back: "Animals: start with poikilothermic/homeothermic. Plants: start with non-flowering/flowering.",
  },

  // Deck 3: Exam (Cards 41-60)
  {
    id: "sci-f2-c1-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[KBAT] Animal X is poikilothermic and has scaly skin (go to 4). If it has no fins, what is animal X?",
    back: "Snake (following the example key: poikilothermic → scaly → no fins → Snake).",
  },
  {
    id: "sci-f2-c1-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[KBAT] Why do insects (950,000 species) remain successful despite being poikilothermic?",
    back: "Hard exoskeleton for protection, small size allowing them to occupy many habitat niches, high reproduction rate.",
  },
  {
    id: "sci-f2-c1-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "How many species of insects are estimated to exist worldwide?",
    back: "950,000 species of insects.",
  },
  {
    id: "sci-f2-c1-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "How many bird species are found in Malaysia, and what is the breakdown?",
    back: "Nearly 742 species: at least 522 local species, 192 migratory species, 52 local species with migratory characteristics.",
  },
  {
    id: "sci-f2-c1-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Which bird is the protected state bird of Sarawak?",
    back: "The rhinoceros hornbill.",
  },
  {
    id: "sci-f2-c1-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[Common Mistake] Is moss a vascular plant?",
    back: "No. Moss is NON-vascular; only fern and conifer are vascular among non-flowering plants.",
  },
  {
    id: "sci-f2-c1-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[Common Mistake] Are birds poikilothermic because they lay eggs?",
    back: "No. Birds are homeothermic (constant body temperature) despite laying eggs — reproduction type does not determine poikilothermic/homeothermic status.",
  },
  {
    id: "sci-f2-c1-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[KBAT] A new animal is covered in fur, gives birth to live young, and nurses them. Which vertebrate group?",
    back: "Mammal — giving birth to live young and nursing them is unique to mammals.",
  },
  {
    id: "sci-f2-c1-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[KBAT] Plant Y is non-flowering, vascular and produces seeds. What is plant Y according to the standard dichotomous key?",
    back: "Gnetum sp. (non-flowering → vascular → produces seeds).",
  },
  {
    id: "sci-f2-c1-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Why does each dichotomous key couplet have only 2 choices, (a) and (b)?",
    back: "Because 'dichotomous' means divided into two; this ensures the classification stays systematic and unambiguous.",
  },
  {
    id: "sci-f2-c1-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[Key Fact] What is special about the rafflesia flower mentioned in the Science Blog?",
    back: "World's largest flower, parasitic, gives off a rotting smell when in bloom, has no leaves (no photosynthesis) and no true roots.",
  },
  {
    id: "sci-f2-c1-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[Exam Tip] How do you fully answer a question to 'differentiate in situ and ex situ conservation'?",
    back: "State location as the main distinguishing factor: in situ = within natural habitat (national park); ex situ = outside natural habitat (zoo) — include an example.",
  },
  {
    id: "sci-f2-c1-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[KBAT] How does genetic diversity help a species survive sudden environmental change?",
    back: "Gene variation allows some individuals to have traits better suited to survive in the new conditions.",
  },
  {
    id: "sci-f2-c1-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[Common Mistake] Is an endemic species the same as an endangered species?",
    back: "Not necessarily. Endemic means restricted habitat at one location; it does not necessarily mean facing extinction, although they often overlap.",
  },
  {
    id: "sci-f2-c1-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Name two reproductive programme activities for biodiversity conservation.",
    back: "Seedling nurseries (for reforestation) and turtle hatcheries.",
  },
  {
    id: "sci-f2-c1-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[KBAT] Why is ex situ conservation (zoo/botanical park) important even though it's not the natural habitat?",
    back: "It allows close monitoring, controlled breeding and research to save critically endangered species.",
  },
  {
    id: "sci-f2-c1-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "What is the main characteristic that divides invertebrates at the first step of the animal dichotomous key?",
    back: "Having legs or not having legs.",
  },
  {
    id: "sci-f2-c1-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[Common Mistake] Can a dichotomous key couplet have three choices?",
    back: "No. Each couplet must have exactly two choices, (a) and (b), to keep the classification systematic.",
  },
  {
    id: "sci-f2-c1-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "[KBAT] An animal is poikilothermic, has shelled eggs, internal fertilisation, and hard scaly skin. Which group?",
    back: "Reptile (e.g. snake, crocodile, iguana, turtle).",
  },
  {
    id: "sci-f2-c1-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 1",
    lang: "dlp",
    front: "Summarise the Chapter 1 concept map in one sentence.",
    back: "Biodiversity covers meaning, management and importance, plus classification of animals (vertebrates & invertebrates) and plants (flowering & non-flowering) using a dichotomous key.",
  },
];
