import type { QuizQuestion } from "@/data/content";

export const scienceF2C1QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c1-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the meaning of biodiversity?",
    options: [
      "The diversity of organisms such as microorganisms, animals and plants",
      "The number of animals living in a country",
      "The type of soil found in an area",
      "The average temperature of a habitat",
    ],
    answerIndex: 0,
    explanation:
      "Biodiversity is the diversity of organisms, whether microorganisms, animals or plants, including genetic diversity.",
  },
  {
    id: "sci-f2-c1-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Malaysia is recognised as one of how many megabiodiversity countries in the world?",
    options: ["8", "10", "12", "15"],
    answerIndex: 2,
    explanation: "Malaysia is one of the 12 megabiodiversity countries in the world.",
  },
  {
    id: "sci-f2-c1-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "Biodiversity exists partly because organisms live in different habitats and climates. Why can this lead to a wide variety of organisms?",
    options: [
      "All organisms develop exactly the same characteristics",
      "Organisms develop characteristics that help them survive in different environmental conditions",
      "Climate prevents organisms from adapting to their habitats",
      "Every habitat contains the same organisms",
    ],
    answerIndex: 1,
    explanation:
      "Different habitats and climates favour different characteristics and adaptations, contributing to biodiversity.",
  },
  {
    id: "sci-f2-c1-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why is effective biodiversity management important?",
    options: [
      "To increase the number of buildings in natural habitats",
      "To prevent species loss and maintain healthy ecosystems",
      "To remove all predators from ecosystems",
      "To ensure only economically useful species survive",
    ],
    answerIndex: 1,
    explanation:
      "Effective biodiversity management prevents species loss and helps ecosystems stay balanced and healthy.",
  },
  {
    id: "sci-f2-c1-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "A species is described as endemic to a particular region. What does this mean?",
    options: [
      "It naturally occurs only in that particular geographical area",
      "It can survive in every habitat in the world",
      "It is always an extinct species",
      "It must be kept only in captivity",
    ],
    answerIndex: 0,
    explanation:
      "An endemic species is one that naturally occurs only in a specific geographical area and nowhere else.",
  },
  {
    id: "sci-f2-c1-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "An animal has no backbone and has a segmented body with an exoskeleton. Which broad group does it belong to?",
    options: ["Vertebrate", "Invertebrate", "Mammal", "Amphibian"],
    answerIndex: 1,
    explanation:
      "An animal with no backbone, a segmented body and an exoskeleton is classified as an invertebrate.",
  },
  {
    id: "sci-f2-c1-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "A forest contains plants that are used to produce medicines, timber and food. Which statement best describes the importance of biodiversity shown here?",
    options: [
      "Biodiversity provides useful biological resources",
      "Biodiversity prevents all competition between organisms",
      "Biodiversity eliminates the need for conservation",
      "Biodiversity causes all organisms to use the same resources",
    ],
    answerIndex: 0,
    explanation:
      "Biodiversity is important because it provides useful biological resources such as medicines, timber and food.",
  },
  {
    id: "sci-f2-c1-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "An organism whose body temperature changes according to the surrounding temperature is called a...",
    options: ["Homeotherm", "Poikilotherm", "Invertebrate", "Vertebrate"],
    answerIndex: 1,
    explanation: "A poikilotherm is an organism whose body temperature changes according to its surrounding temperature.",
  },
  {
    id: "sci-f2-c1-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "All of the following belong to the non-flowering plant group EXCEPT...",
    options: ["Moss", "Fern", "Conifer", "Paddy plant"],
    answerIndex: 3,
    explanation: "The paddy plant is a flowering plant (monocotyledon), not a non-flowering plant.",
  },
  {
    id: "sci-f2-c1-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Plant X has one cotyledon, fibrous roots and parallel leaf veins. How should Plant X be classified?",
    options: ["Moss", "Fern", "Monocotyledon", "Dicotyledon"],
    answerIndex: 2,
    explanation:
      "One cotyledon, fibrous roots and parallel leaf veins are all characteristics of a monocotyledon.",
  },
  {
    id: "sci-f2-c1-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the main difference between in situ and ex situ conservation?",
    options: [
      "In situ preserves species within their natural habitat, ex situ preserves species outside their natural habitat",
      "In situ is only for animals, ex situ is only for plants",
      "In situ is carried out in zoos, ex situ is carried out in national parks",
      "In situ and ex situ are the same thing",
    ],
    answerIndex: 0,
    explanation: "In situ conservation preserves species within their natural habitat, while ex situ conservation preserves species outside their natural habitat, such as in zoos or botanical parks.",
  },
  {
    id: "sci-f2-c1-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Tapeworms and leeches are classified as invertebrates that are...",
    options: [
      "With legs and a segmented body",
      "Without legs and with a segmented body",
      "Without legs and without a segmented body",
      "With more than three pairs of legs",
    ],
    answerIndex: 1,
    explanation: "Tapeworms and leeches are invertebrates without legs but with a segmented body.",
  },
  {
    id: "sci-f2-c1-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which comparison of leaf venation is correct?",
    options: [
      "Monocotyledon: parallel veins; Dicotyledon: network-like veins",
      "Monocotyledon: network-like veins; Dicotyledon: parallel veins",
      "Both have only parallel veins",
      "Both have only network-like veins",
    ],
    answerIndex: 0,
    explanation:
      "Monocotyledons have parallel leaf veins, while dicotyledons have network-like (reticulate) leaf veins.",
  },
  {
    id: "sci-f2-c1-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which of the following vertebrate groups undergo external fertilisation?",
    options: ["Birds and mammals", "Reptiles and birds", "Fish and amphibians", "Mammals and reptiles"],
    answerIndex: 2,
    explanation: "Fish and amphibians undergo external fertilisation, unlike reptiles, birds and mammals which undergo internal fertilisation.",
  },
  {
    id: "sci-f2-c1-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why are birds classified as homeothermic even though they lay eggs?",
    options: [
      "Because bird eggs do not have a shell",
      "Because a bird's body temperature is constant and not influenced by the surrounding temperature",
      "Because birds live on land and in water",
      "Because birds undergo external fertilisation",
    ],
    answerIndex: 1,
    explanation: "Homeothermic classification is determined by whether body temperature is constant, not by the method of reproduction. Birds maintain a constant body temperature using their feathers.",
  },
  {
    id: "sci-f2-c1-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the main difference between the roots of monocotyledon and dicotyledon plants?",
    options: [
      "Monocotyledons have a tap root, dicotyledons have a fibrous root",
      "Monocotyledons have a fibrous root, dicotyledons have a tap root",
      "Both have a tap root",
      "Neither has roots",
    ],
    answerIndex: 1,
    explanation: "Monocotyledon plants have a fibrous root, while dicotyledon plants have a tap root.",
  },
  {
    id: "sci-f2-c1-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Moss differs from fern and conifer because moss is...",
    options: [
      "Reproduces by bearing cones",
      "Has a vascular system",
      "Does not have a vascular system (non-vascular)",
      "A flowering plant",
    ],
    answerIndex: 2,
    explanation: "Moss does not have a vascular system (non-vascular), unlike fern and conifer which are vascular.",
  },
  {
    id: "sci-f2-c1-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "Factories release untreated waste into a river over several years. Which consequence is most likely to reduce biodiversity in the river?",
    options: [
      "More fish species will appear in the river",
      "Aquatic organisms die or leave, reducing the variety of species in the river",
      "The water becomes clearer and healthier for organisms",
      "Competition between species disappears completely",
    ],
    answerIndex: 1,
    explanation:
      "Untreated waste pollutes the water, killing or driving away aquatic organisms and reducing the variety of species in the river.",
  },
  {
    id: "sci-f2-c1-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which importance of biodiversity is referred to when herbs are used to produce medicines?",
    options: ["Source of food", "Medical", "Raw materials for industries", "Education"],
    answerIndex: 1,
    explanation: "The use of herbs in manufacturing medicines and cosmetics is the medical importance of biodiversity.",
  },
  {
    id: "sci-f2-c1-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Excessive deforestation can harm biodiversity mainly because...",
    options: [
      "It increases the number of endemic species",
      "It causes animals to lose their habitat and food sources",
      "It drastically lowers the surrounding temperature",
      "It only affects plants, not animals",
    ],
    answerIndex: 1,
    explanation: "Uncontrolled deforestation causes animals to lose their habitat and food sources, thereby threatening biodiversity.",
  },
  {
    id: "sci-f2-c1-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "A population of an endemic animal is declining because its forest habitat is being cleared. Which action would be the most effective biodiversity-management strategy?",
    options: [
      "Capture every individual and permanently keep all of them in cages",
      "Protect the natural habitat and control activities that threaten the population",
      "Introduce several unrelated species into the habitat",
      "Allow development to continue without monitoring the population",
    ],
    answerIndex: 1,
    explanation:
      "Protecting the natural habitat and controlling the activities that threaten a population is the most effective way to prevent an endemic species from declining further.",
  },
  {
    id: "sci-f2-c1-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "A researcher discovers a new animal that is covered with fur, gives birth to live young, and nurses its young. Based on these characteristics, this animal is most accurately classified as a...",
    options: ["Reptile", "Bird", "Mammal", "Amphibian"],
    answerIndex: 2,
    explanation: "Giving birth to live young and nursing them are characteristics unique to mammals, together with being covered in fur which is also specific to mammals.",
  },
  {
    id: "sci-f2-c1-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why do insects remain the most successful and abundant animal group (950,000 species) despite being poikilothermic?",
    options: [
      "Because insects have a strong backbone",
      "Because of their hard exoskeleton, small body size which allows them to occupy many habitat niches, and high reproduction rate",
      "Because insects only live in water",
      "Because insects undergo internal fertilisation like mammals",
    ],
    answerIndex: 1,
    explanation:
      "Insects' success despite being poikilothermic is due to their hard exoskeleton for protection, small size allowing them to occupy many habitat niches, and high reproduction rate.",
  },
  {
    id: "sci-f2-c1-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which combination correctly compares a monocotyledon with a dicotyledon?",
    options: [
      "Monocotyledon: taproot and network-like veins; Dicotyledon: fibrous roots and parallel veins",
      "Monocotyledon: fibrous roots and parallel veins; Dicotyledon: taproot and network-like veins",
      "Both have fibrous roots and parallel veins",
      "Both have taproots and network-like veins",
    ],
    answerIndex: 1,
    explanation:
      "Monocotyledons have fibrous roots and parallel leaf veins, while dicotyledons have a tap root and network-like leaf veins.",
  },
  {
    id: "sci-f2-c1-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why is ex situ conservation, such as zoos and botanical parks, still important even though the species is not in its natural habitat?",
    options: [
      "Because it is cheaper than in situ conservation",
      "Because it allows close monitoring, controlled breeding and research to save critically endangered species",
      "Because it replaces the need for forest reserves",
      "Because all species are more comfortable outside their natural habitat",
    ],
    answerIndex: 1,
    explanation: "Ex situ conservation allows close monitoring, controlled breeding programmes and scientific research, especially for species at high risk of extinction in their natural habitat.",
  },
  {
    id: "sci-f2-c1-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "An animal is found to have hard scaly skin, lays shelled eggs, and undergoes internal fertilisation, but its body temperature changes according to the surroundings. What vertebrate group does this animal belong to?",
    options: ["Bird", "Mammal", "Reptile", "Fish"],
    answerIndex: 2,
    explanation: "Poikilothermic, hard scaly skin, shelled eggs and internal fertilisation are characteristics specific to reptiles (e.g. snake, crocodile).",
  },
  {
    id: "sci-f2-c1-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the clearest difference between amphibian eggs and reptile eggs that allows them to be distinguished in a dichotomous key?",
    options: [
      "Amphibian eggs are larger than reptile eggs",
      "Amphibian eggs have no shell (jelly-like), reptile eggs have a shell",
      "Amphibian eggs are colourful, reptile eggs are white",
      "Only reptiles lay eggs",
    ],
    answerIndex: 1,
    explanation: "Amphibian eggs are jelly-like without a shell, while reptile eggs have a hard shell.",
  },
  {
    id: "sci-f2-c1-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "A student claims that 'all vascular plants are flowering plants'. Is this claim correct? Why?",
    options: [
      "Correct, because only flowering plants have a vascular system",
      "Incorrect, because fern and conifer are non-flowering plants that are also vascular",
      "Correct, because moss is also flowering and vascular",
      "Incorrect, because all plants are non-vascular",
    ],
    answerIndex: 1,
    explanation: "The claim is incorrect because fern and conifer are non-flowering plants but still have a vascular system.",
  },
  {
    id: "sci-f2-c1-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "How does genetic diversity within a plant species help that species survive a sudden environmental change?",
    options: [
      "Genetic diversity has no effect on a species' survival",
      "Different gene variations allow some individuals to have traits better suited to survive in the new conditions",
      "Genetic diversity only exists in animals, not plants",
      "Genetic diversity causes all individuals to die simultaneously",
    ],
    answerIndex: 1,
    explanation: "Genetic diversity refers to gene variations within a species; this variation allows some individuals to have traits better suited to survive even when the environment changes suddenly.",
  },
  {
    id: "sci-f2-c1-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "A rare species is declining because of habitat destruction and illegal hunting. Which plan is most likely to conserve the species effectively in the long term?",
    options: [
      "Protect its habitat, enforce wildlife laws and support breeding programmes where necessary",
      "Protect only a few individuals but allow the habitat to continue being destroyed",
      "Stop all scientific research on the species",
      "Move every individual permanently into a city zoo",
    ],
    answerIndex: 0,
    explanation:
      "Effective long-term conservation combines habitat protection, law enforcement against illegal hunting, and breeding programmes where necessary.",
  },
];
