import type { QuizQuestion } from "@/data/content";

export const scienceF2C1QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c1-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the meaning of biodiversity?",
    options: [
      "The diversity of organisms such as microorganisms, animals and plants",
      "The number of animals living in a country",
      "The type of soil found in an area",
      "The average temperature of a habitat",
    ],
    answerIndex: 0,
    explanation:
      "Biodiversity is the diversity of organisms, whether microorganisms, animals or plants, including genetic diversity.",
  },
  {
    id: "sci-f2-c1-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Malaysia is recognised as one of how many megabiodiversity countries in the world?",
    options: ["8", "10", "12", "15"],
    answerIndex: 2,
    explanation: "Malaysia is one of the 12 megabiodiversity countries in the world.",
  },
  {
    id: "sci-f2-c1-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "On which date is the International Day for Biological Diversity celebrated?",
    options: ["5 June", "22 May", "1 March", "16 September"],
    answerIndex: 1,
    explanation: "The International Day for Biological Diversity is celebrated on 22 May every year.",
  },
  {
    id: "sci-f2-c1-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which act bans the killing or trade of endemic and endangered animals and plants in Malaysia?",
    options: [
      "Environmental Quality Act 1974",
      "Wildlife Protection Act 1972",
      "National Forestry Act 1984",
      "National Parks Act 1980",
    ],
    answerIndex: 1,
    explanation: "The Wildlife Protection Act 1972 bans the killing or trade of endemic and endangered animals and plants.",
  },
  {
    id: "sci-f2-c1-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which of the following is an example of an endemic species in Malaysia?",
    options: ["Cat", "Dog", "Rafflesia flower", "Cow"],
    answerIndex: 2,
    explanation: "The rafflesia flower is an example of an endemic species in Malaysia, alongside the pitcher plant, leatherback turtle, Malayan tiger and Borneo Pygmy elephant.",
  },
  {
    id: "sci-f2-c1-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "An animal without a backbone is known as a/an...",
    options: ["Vertebrate", "Invertebrate", "Homeotherm", "Poikilotherm"],
    answerIndex: 1,
    explanation: "An invertebrate is an animal that does not have a backbone.",
  },
  {
    id: "sci-f2-c1-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "How many main groups of vertebrates are studied in this chapter?",
    options: ["3", "4", "5", "6"],
    answerIndex: 2,
    explanation: "The five groups of vertebrates are fish, amphibians, reptiles, birds and mammals.",
  },
  {
    id: "sci-f2-c1-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "An organism whose body temperature changes according to the surrounding temperature is called a...",
    options: ["Homeotherm", "Poikilotherm", "Invertebrate", "Vertebrate"],
    answerIndex: 1,
    explanation: "A poikilotherm is an organism whose body temperature changes according to its surrounding temperature.",
  },
  {
    id: "sci-f2-c1-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "All of the following belong to the non-flowering plant group EXCEPT...",
    options: ["Moss", "Fern", "Conifer", "Paddy plant"],
    answerIndex: 3,
    explanation: "The paddy plant is a flowering plant (monocotyledon), not a non-flowering plant.",
  },
  {
    id: "sci-f2-c1-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "A seed with one cotyledon is known as a...",
    options: ["Dicotyledon", "Monocotyledon", "Conifer", "Spore"],
    answerIndex: 1,
    explanation: "A seed with one cotyledon is called a monocotyledon, e.g. paddy and maize.",
  },
  {
    id: "sci-f2-c1-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the main difference between in situ and ex situ conservation?",
    options: [
      "In situ preserves species within their natural habitat, ex situ preserves species outside their natural habitat",
      "In situ is only for animals, ex situ is only for plants",
      "In situ is carried out in zoos, ex situ is carried out in national parks",
      "In situ and ex situ are the same thing",
    ],
    answerIndex: 0,
    explanation: "In situ conservation preserves species within their natural habitat, while ex situ conservation preserves species outside their natural habitat, such as in zoos or botanical parks.",
  },
  {
    id: "sci-f2-c1-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Tapeworms and leeches are classified as invertebrates that are...",
    options: [
      "With legs and a segmented body",
      "Without legs and with a segmented body",
      "Without legs and without a segmented body",
      "With more than three pairs of legs",
    ],
    answerIndex: 1,
    explanation: "Tapeworms and leeches are invertebrates without legs but with a segmented body.",
  },
  {
    id: "sci-f2-c1-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "How many pairs of legs do insects such as ants and butterflies have?",
    options: ["Two pairs", "Three pairs", "Four pairs", "Five pairs"],
    answerIndex: 1,
    explanation: "Insects such as ants, butterflies and cockroaches have three pairs of legs.",
  },
  {
    id: "sci-f2-c1-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which of the following vertebrate groups undergo external fertilisation?",
    options: ["Birds and mammals", "Reptiles and birds", "Fish and amphibians", "Mammals and reptiles"],
    answerIndex: 2,
    explanation: "Fish and amphibians undergo external fertilisation, unlike reptiles, birds and mammals which undergo internal fertilisation.",
  },
  {
    id: "sci-f2-c1-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why are birds classified as homeothermic even though they lay eggs?",
    options: [
      "Because bird eggs do not have a shell",
      "Because a bird's body temperature is constant and not influenced by the surrounding temperature",
      "Because birds live on land and in water",
      "Because birds undergo external fertilisation",
    ],
    answerIndex: 1,
    explanation: "Homeothermic classification is determined by whether body temperature is constant, not by the method of reproduction. Birds maintain a constant body temperature using their feathers.",
  },
  {
    id: "sci-f2-c1-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the main difference between the roots of monocotyledon and dicotyledon plants?",
    options: [
      "Monocotyledons have a tap root, dicotyledons have a fibrous root",
      "Monocotyledons have a fibrous root, dicotyledons have a tap root",
      "Both have a tap root",
      "Neither has roots",
    ],
    answerIndex: 1,
    explanation: "Monocotyledon plants have a fibrous root, while dicotyledon plants have a tap root.",
  },
  {
    id: "sci-f2-c1-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Moss differs from fern and conifer because moss is...",
    options: [
      "Reproduces by bearing cones",
      "Has a vascular system",
      "Does not have a vascular system (non-vascular)",
      "A flowering plant",
    ],
    answerIndex: 2,
    explanation: "Moss does not have a vascular system (non-vascular), unlike fern and conifer which are vascular.",
  },
  {
    id: "sci-f2-c1-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "In a dichotomous key, what is meant by a 'couplet'?",
    options: [
      "A single organism being studied",
      "Two statements of characteristics that divide organisms into two choices",
      "The total number of organisms in a group",
      "The scientific name of an organism",
    ],
    answerIndex: 1,
    explanation: "A couplet consists of two statements describing characteristics of an organism, dividing it into choice (a) or (b).",
  },
  {
    id: "sci-f2-c1-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Which importance of biodiversity is referred to when herbs are used to produce medicines?",
    options: ["Source of food", "Medical", "Raw materials for industries", "Education"],
    answerIndex: 1,
    explanation: "The use of herbs in manufacturing medicines and cosmetics is the medical importance of biodiversity.",
  },
  {
    id: "sci-f2-c1-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Excessive deforestation can harm biodiversity mainly because...",
    options: [
      "It increases the number of endemic species",
      "It causes animals to lose their habitat and food sources",
      "It drastically lowers the surrounding temperature",
      "It only affects plants, not animals",
    ],
    answerIndex: 1,
    explanation: "Uncontrolled deforestation causes animals to lose their habitat and food sources, thereby threatening biodiversity.",
  },
  {
    id: "sci-f2-c1-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "A dichotomous key gives the couplet: 1(a) Poikilothermic → go to 2, 1(b) Homeothermic → go to 3; 3(a) Non-feathered → Lion, 3(b) Feathered → Chicken. Animal X is homeothermic and feathered. What is animal X?",
    options: ["Lion", "Chicken", "Snake", "Frog"],
    answerIndex: 1,
    explanation: "Following the couplet path: homeothermic → go to 3 → feathered → Chicken.",
  },
  {
    id: "sci-f2-c1-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "A researcher discovers a new animal that is covered with fur, gives birth to live young, and nurses its young. Based on these characteristics, this animal is most accurately classified as a...",
    options: ["Reptile", "Bird", "Mammal", "Amphibian"],
    answerIndex: 2,
    explanation: "Giving birth to live young and nursing them are characteristics unique to mammals, together with being covered in fur which is also specific to mammals.",
  },
  {
    id: "sci-f2-c1-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why do insects remain the most successful and abundant animal group (950,000 species) despite being poikilothermic?",
    options: [
      "Because insects have a strong backbone",
      "Because of their hard exoskeleton, small body size which allows them to occupy many habitat niches, and high reproduction rate",
      "Because insects only live in water",
      "Because insects undergo internal fertilisation like mammals",
    ],
    answerIndex: 1,
    explanation: "Insects' success despite being poikilothermic is due to their hard exoskeleton for protection, small size allowing them to occupy many habitat niches, and high reproduction rate.",
  },
  {
    id: "sci-f2-c1-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question:
      "A plant dichotomous key: 1(a) Non-flowering → go to 2, 1(b) Flowering → go to 3; 2(a) Non-vascular → Marchantia sp., 2(b) Vascular → go to 4; 4(a) Does not produce seeds → Fern, 4(b) Produce seeds → Gnetum sp. Plant Y is non-flowering, vascular and produces seeds. What is plant Y?",
    options: ["Marchantia sp.", "Fern", "Gnetum sp.", "Maize plant"],
    answerIndex: 2,
    explanation: "Path: non-flowering → go to 2 → vascular → go to 4 → produces seeds → Gnetum sp.",
  },
  {
    id: "sci-f2-c1-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why is ex situ conservation, such as zoos and botanical parks, still important even though the species is not in its natural habitat?",
    options: [
      "Because it is cheaper than in situ conservation",
      "Because it allows close monitoring, controlled breeding and research to save critically endangered species",
      "Because it replaces the need for forest reserves",
      "Because all species are more comfortable outside their natural habitat",
    ],
    answerIndex: 1,
    explanation: "Ex situ conservation allows close monitoring, controlled breeding programmes and scientific research, especially for species at high risk of extinction in their natural habitat.",
  },
  {
    id: "sci-f2-c1-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "An animal is found to have hard scaly skin, lays shelled eggs, and undergoes internal fertilisation, but its body temperature changes according to the surroundings. What vertebrate group does this animal belong to?",
    options: ["Bird", "Mammal", "Reptile", "Fish"],
    answerIndex: 2,
    explanation: "Poikilothermic, hard scaly skin, shelled eggs and internal fertilisation are characteristics specific to reptiles (e.g. snake, crocodile).",
  },
  {
    id: "sci-f2-c1-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "What is the clearest difference between amphibian eggs and reptile eggs that allows them to be distinguished in a dichotomous key?",
    options: [
      "Amphibian eggs are larger than reptile eggs",
      "Amphibian eggs have no shell (jelly-like), reptile eggs have a shell",
      "Amphibian eggs are colourful, reptile eggs are white",
      "Only reptiles lay eggs",
    ],
    answerIndex: 1,
    explanation: "Amphibian eggs are jelly-like without a shell, while reptile eggs have a hard shell.",
  },
  {
    id: "sci-f2-c1-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "A student claims that 'all vascular plants are flowering plants'. Is this claim correct? Why?",
    options: [
      "Correct, because only flowering plants have a vascular system",
      "Incorrect, because fern and conifer are non-flowering plants that are also vascular",
      "Correct, because moss is also flowering and vascular",
      "Incorrect, because all plants are non-vascular",
    ],
    answerIndex: 1,
    explanation: "The claim is incorrect because fern and conifer are non-flowering plants but still have a vascular system.",
  },
  {
    id: "sci-f2-c1-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "How does genetic diversity within a plant species help that species survive a sudden environmental change?",
    options: [
      "Genetic diversity has no effect on a species' survival",
      "Different gene variations allow some individuals to have traits better suited to survive in the new conditions",
      "Genetic diversity only exists in animals, not plants",
      "Genetic diversity causes all individuals to die simultaneously",
    ],
    answerIndex: 1,
    explanation: "Genetic diversity refers to gene variations within a species; this variation allows some individuals to have traits better suited to survive even when the environment changes suddenly.",
  },
  {
    id: "sci-f2-c1-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "dlp",
    question: "Why is it important to construct a dichotomous key with exactly two choices (a) and (b) per couplet, not three or more?",
    options: [
      "Because this rule only exists to help students memorise, without scientific reason",
      "Because 'dichotomous' means 'divided into two', so each classification step remains systematic and unambiguous",
      "Because only two organisms can exist in the world",
      "Because a key with three choices cannot be drawn on paper",
    ],
    answerIndex: 1,
    explanation: "The word 'dichotomous' means divided into two parts; this structure ensures each classification step is consistent, systematic, and unambiguous when identifying organisms.",
  },
];
