import type { QuizQuestion } from "@/data/content";

export const scienceF2C1QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c1-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah maksud biodiversiti?",
    options: [
      "Kepelbagaian organisma seperti mikroorganisma, haiwan dan tumbuhan",
      "Bilangan haiwan yang hidup di sesebuah negara",
      "Jenis tanah yang terdapat di sesuatu kawasan",
      "Suhu purata sesebuah habitat",
    ],
    answerIndex: 0,
    explanation:
      "Biodiversiti ialah kepelbagaian organisma sama ada mikroorganisma, haiwan atau tumbuhan, termasuk kepelbagaian genetik.",
  },
  {
    id: "sci-f2-c1-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Malaysia diiktiraf sebagai salah satu daripada berapa buah negara megabiodiversiti di dunia?",
    options: ["8", "10", "12", "15"],
    answerIndex: 2,
    explanation: "Malaysia ialah salah satu daripada 12 negara megabiodiversiti di dunia.",
  },
  {
    id: "sci-f2-c1-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Biodiversiti wujud antara lain kerana organisma hidup dalam habitat dan iklim yang berbeza. Mengapakah keadaan ini boleh menghasilkan kepelbagaian organisma?",
    options: [
      "Semua organisma mempunyai ciri yang sama",
      "Organisma mempunyai ciri yang membantu mereka hidup dalam keadaan persekitaran yang berbeza",
      "Iklim menghalang organisma daripada menyesuaikan diri",
      "Setiap habitat mengandungi organisma yang sama",
    ],
    answerIndex: 1,
    explanation:
      "Habitat dan iklim yang berbeza menggalakkan ciri dan penyesuaian yang berbeza, lalu menyumbang kepada biodiversiti.",
  },
  {
    id: "sci-f2-c1-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah pengurusan biodiversiti yang berkesan penting?",
    options: [
      "Untuk menambahkan bilangan bangunan dalam habitat semula jadi",
      "Untuk mengelakkan kehilangan spesies dan mengekalkan ekosistem yang sihat",
      "Untuk menghapuskan semua pemangsa daripada ekosistem",
      "Untuk memastikan hanya spesies yang mempunyai nilai ekonomi terus hidup",
    ],
    answerIndex: 1,
    explanation:
      "Pengurusan biodiversiti yang berkesan mengelakkan kehilangan spesies dan membantu mengekalkan ekosistem yang seimbang serta sihat.",
  },
  {
    id: "sci-f2-c1-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Sesuatu spesies dikatakan endemik di sesuatu kawasan. Apakah maksudnya?",
    options: [
      "Spesies itu secara semula jadi hanya terdapat di kawasan geografi tertentu",
      "Spesies itu boleh hidup di semua habitat di dunia",
      "Spesies itu semestinya telah pupus",
      "Spesies itu mesti dipelihara hanya dalam kurungan",
    ],
    answerIndex: 0,
    explanation:
      "Spesies endemik ialah spesies yang secara semula jadi hanya terdapat di sesuatu kawasan geografi tertentu dan tiada di tempat lain.",
  },
  {
    id: "sci-f2-c1-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Seekor haiwan tidak mempunyai tulang belakang serta mempunyai badan bersegmen dan rangka luar. Haiwan itu tergolong dalam kumpulan yang mana?",
    options: ["Vertebrata", "Invertebrata", "Mamalia", "Amfibia"],
    answerIndex: 1,
    explanation:
      "Haiwan tanpa tulang belakang, berbadan bersegmen dan mempunyai rangka luar dikelaskan sebagai invertebrata.",
  },
  {
    id: "sci-f2-c1-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Sebuah hutan mempunyai tumbuhan yang digunakan untuk menghasilkan ubat, kayu dan makanan. Pernyataan manakah paling tepat menunjukkan kepentingan biodiversiti?",
    options: [
      "Biodiversiti membekalkan sumber biologi yang berguna",
      "Biodiversiti menghalang semua persaingan antara organisma",
      "Biodiversiti menghapuskan keperluan pemuliharaan",
      "Biodiversiti menyebabkan semua organisma menggunakan sumber yang sama",
    ],
    answerIndex: 0,
    explanation:
      "Biodiversiti penting kerana ia membekalkan sumber biologi yang berguna seperti ubat-ubatan, kayu dan makanan.",
  },
  {
    id: "sci-f2-c1-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Organisma yang suhu badannya berubah mengikut suhu persekitaran dipanggil...",
    options: ["Homoioterma", "Poikiloterma", "Invertebrata", "Vertebrata"],
    answerIndex: 1,
    explanation: "Poikiloterma ialah organisma yang suhu badannya berubah mengikut suhu persekitaran.",
  },
  {
    id: "sci-f2-c1-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tumbuhan berikut tergolong dalam kumpulan tidak berbunga, KECUALI...",
    options: ["Lumut", "Paku pakis", "Konifer", "Pokok padi"],
    answerIndex: 3,
    explanation: "Pokok padi ialah tumbuhan berbunga (monokotiledon), bukan tumbuhan tidak berbunga.",
  },
  {
    id: "sci-f2-c1-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tumbuhan X mempunyai satu kotiledon, akar serabut dan urat daun selari. Bagaimanakah Tumbuhan X dikelaskan?",
    options: ["Lumut", "Paku-pakis", "Monokotiledon", "Dikotiledon"],
    answerIndex: 2,
    explanation:
      "Satu kotiledon, akar serabut dan urat daun selari semuanya merupakan ciri monokotiledon.",
  },
  {
    id: "sci-f2-c1-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah perbezaan utama antara pemuliharaan in situ dan ex situ?",
    options: [
      "In situ memelihara spesies dalam habitat asal, ex situ memelihara di luar habitat asal",
      "In situ hanya untuk haiwan, ex situ hanya untuk tumbuhan",
      "In situ dijalankan di zoo, ex situ dijalankan di taman negara",
      "In situ dan ex situ adalah perkara yang sama",
    ],
    answerIndex: 0,
    explanation: "Pemuliharaan in situ memelihara spesies dalam habitat semula jadinya, manakala ex situ memelihara spesies di luar habitat asalnya seperti di zoo atau taman botani.",
  },
  {
    id: "sci-f2-c1-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Cacing pita dan lintah diklasifikasikan sebagai invertebrata yang...",
    options: [
      "Mempunyai kaki dan badan bersegmen",
      "Tanpa kaki dan badan bersegmen",
      "Tanpa kaki dan tanpa badan bersegmen",
      "Mempunyai lebih daripada tiga pasang kaki",
    ],
    answerIndex: 1,
    explanation: "Cacing pita dan lintah ialah invertebrata tanpa kaki tetapi mempunyai badan bersegmen.",
  },
  {
    id: "sci-f2-c1-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Perbandingan urat daun yang manakah betul?",
    options: [
      "Monokotiledon: urat selari; Dikotiledon: urat jejala",
      "Monokotiledon: urat jejala; Dikotiledon: urat selari",
      "Kedua-duanya hanya mempunyai urat selari",
      "Kedua-duanya hanya mempunyai urat jejala",
    ],
    answerIndex: 0,
    explanation:
      "Monokotiledon mempunyai urat daun selari, manakala dikotiledon mempunyai urat daun berjejala (seperti jaringan).",
  },
  {
    id: "sci-f2-c1-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Antara berikut, yang manakah kumpulan vertebrata yang mengalami persenyawaan luaran?",
    options: ["Burung dan mamalia", "Reptilia dan burung", "Ikan dan amfibia", "Mamalia dan reptilia"],
    answerIndex: 2,
    explanation: "Ikan dan amfibia mengalami persenyawaan luaran, berbeza dengan reptilia, burung dan mamalia yang mengalami persenyawaan dalaman.",
  },
  {
    id: "sci-f2-c1-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah burung dikategorikan sebagai homoioterma walaupun ia bertelur?",
    options: [
      "Kerana telur burung tidak bercengkerang",
      "Kerana suhu badan burung malar dan tidak dipengaruhi suhu persekitaran",
      "Kerana burung hidup di darat dan di air",
      "Kerana burung mengalami persenyawaan luaran",
    ],
    answerIndex: 1,
    explanation: "Homoioterma ditentukan oleh sama ada suhu badan malar (tetap), bukan oleh cara pembiakan. Burung mengekalkan suhu badan yang tetap menggunakan bulu.",
  },
  {
    id: "sci-f2-c1-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah perbezaan utama antara akar tumbuhan monokotiledon dan dikotiledon?",
    options: [
      "Monokotiledon mempunyai akar tunjang, dikotiledon mempunyai akar serabut",
      "Monokotiledon mempunyai akar serabut, dikotiledon mempunyai akar tunjang",
      "Kedua-duanya mempunyai akar tunjang",
      "Kedua-duanya tidak mempunyai akar",
    ],
    answerIndex: 1,
    explanation: "Tumbuhan monokotiledon mempunyai akar serabut (fibrus), manakala dikotiledon mempunyai akar tunjang.",
  },
  {
    id: "sci-f2-c1-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Lumut berbeza daripada paku pakis dan konifer kerana lumut...",
    options: [
      "Membiak melalui kon",
      "Mempunyai sistem vaskular",
      "Tidak mempunyai sistem vaskular (tidak berpembuluh)",
      "Merupakan tumbuhan berbunga",
    ],
    answerIndex: 2,
    explanation: "Lumut tidak mempunyai sistem vaskular (tidak berpembuluh), berbeza dengan paku pakis dan konifer yang berpembuluh.",
  },
  {
    id: "sci-f2-c1-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Kilang-kilang melepaskan sisa yang tidak dirawat ke dalam sungai selama beberapa tahun. Kesan manakah paling mungkin mengurangkan biodiversiti dalam sungai itu?",
    options: [
      "Lebih banyak spesies ikan akan muncul di sungai itu",
      "Organisma akuatik mati atau berpindah, mengurangkan kepelbagaian spesies dalam sungai itu",
      "Air menjadi lebih jernih dan sihat untuk organisma",
      "Persaingan antara spesies hilang sepenuhnya",
    ],
    answerIndex: 1,
    explanation:
      "Sisa yang tidak dirawat mencemarkan air, menyebabkan organisma akuatik mati atau berpindah, sekali gus mengurangkan kepelbagaian spesies di sungai itu.",
  },
  {
    id: "sci-f2-c1-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah kepentingan biodiversiti yang dirujuk apabila herba digunakan untuk menghasilkan ubat-ubatan?",
    options: ["Sumber makanan", "Perubatan", "Bahan mentah industri", "Pendidikan"],
    answerIndex: 1,
    explanation: "Penggunaan herba dalam pembuatan ubat-ubatan dan kosmetik merupakan kepentingan biodiversiti dari aspek perubatan.",
  },
  {
    id: "sci-f2-c1-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Penebangan hutan secara berlebihan boleh menjejaskan biodiversiti terutamanya kerana...",
    options: [
      "Ia meningkatkan bilangan spesies endemik",
      "Ia menyebabkan haiwan kehilangan habitat dan sumber makanan",
      "Ia mengurangkan suhu persekitaran secara mendadak",
      "Ia hanya menjejaskan tumbuhan, bukan haiwan",
    ],
    answerIndex: 1,
    explanation: "Penebangan hutan yang tidak terkawal menyebabkan haiwan kehilangan habitat dan sumber makanan, sekali gus mengancam biodiversiti.",
  },
  {
    id: "sci-f2-c1-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Populasi seekor haiwan endemik semakin berkurang kerana habitat hutannya sedang dimusnahkan. Tindakan manakah merupakan strategi pengurusan biodiversiti yang paling berkesan?",
    options: [
      "Menangkap semua individu dan menyimpannya secara kekal dalam kurungan",
      "Melindungi habitat semula jadi dan mengawal aktiviti yang mengancam populasinya",
      "Memperkenalkan beberapa spesies lain yang tidak berkaitan ke habitat tersebut",
      "Membenarkan pembangunan diteruskan tanpa memantau populasinya",
    ],
    answerIndex: 1,
    explanation:
      "Melindungi habitat semula jadi dan mengawal aktiviti yang mengancam sesuatu populasi ialah cara paling berkesan untuk mengelakkan spesies endemik daripada terus berkurangan.",
  },
  {
    id: "sci-f2-c1-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Seorang penyelidik menjumpai haiwan baharu yang berbulu, melahirkan anak hidup dan menyusukan anaknya. Berdasarkan ciri ini, haiwan tersebut paling tepat dikelaskan sebagai...",
    options: ["Reptilia", "Burung", "Mamalia", "Amfibia"],
    answerIndex: 2,
    explanation: "Ciri melahirkan anak hidup dan menyusukannya adalah ciri unik mamalia, ditambah dengan ciri berbulu yang juga khusus mamalia.",
  },
  {
    id: "sci-f2-c1-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah serangga tetap menjadi kumpulan haiwan yang paling berjaya dan banyak (950,000 spesies) walaupun ia adalah poikiloterma?",
    options: [
      "Kerana serangga mempunyai tulang belakang yang kukuh",
      "Kerana eksoskeleton yang keras, saiz badan kecil yang membolehkan menghuni pelbagai ceruk habitat, dan kadar pembiakan yang tinggi",
      "Kerana serangga hanya hidup di dalam air",
      "Kerana serangga mengalami persenyawaan dalaman seperti mamalia",
    ],
    answerIndex: 1,
    explanation:
      "Kejayaan serangga walaupun poikiloterma disebabkan oleh eksoskeleton keras untuk perlindungan, saiz kecil yang membolehkan mereka menghuni banyak ceruk habitat, dan kadar pembiakan yang tinggi.",
  },
  {
    id: "sci-f2-c1-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Gabungan manakah membandingkan monokotiledon dengan dikotiledon dengan betul?",
    options: [
      "Monokotiledon: akar tunjang dan urat jejala; Dikotiledon: akar serabut dan urat selari",
      "Monokotiledon: akar serabut dan urat selari; Dikotiledon: akar tunjang dan urat jejala",
      "Kedua-duanya mempunyai akar serabut dan urat selari",
      "Kedua-duanya mempunyai akar tunjang dan urat jejala",
    ],
    answerIndex: 1,
    explanation:
      "Monokotiledon mempunyai akar serabut dan urat daun selari, manakala dikotiledon mempunyai akar tunjang dan urat daun berjejala.",
  },
  {
    id: "sci-f2-c1-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah pemuliharaan ex situ seperti zoo dan taman botani masih penting walaupun spesies tidak berada dalam habitat asalnya?",
    options: [
      "Kerana ia lebih murah berbanding pemuliharaan in situ",
      "Kerana ia membolehkan pemantauan rapi, pembiakan terkawal dan penyelidikan untuk menyelamatkan spesies yang sangat terancam",
      "Kerana ia menggantikan keperluan kawasan hutan simpan",
      "Kerana semua spesies lebih selesa di luar habitat asal",
    ],
    answerIndex: 1,
    explanation: "Pemuliharaan ex situ membolehkan pemantauan rapi, program pembiakan terkawal dan penyelidikan saintifik, terutamanya bagi spesies yang berisiko tinggi pupus di habitat asal.",
  },
  {
    id: "sci-f2-c1-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Seekor haiwan didapati mempunyai kulit bersisik keras, bertelur bercengkerang dan mengalami persenyawaan dalaman, tetapi suhu badannya berubah mengikut persekitaran. Apakah kumpulan vertebrata bagi haiwan ini?",
    options: ["Burung", "Mamalia", "Reptilia", "Ikan"],
    answerIndex: 2,
    explanation: "Ciri poikiloterma, kulit bersisik keras, telur bercengkerang dan persenyawaan dalaman adalah ciri khusus reptilia (contoh: ular, buaya).",
  },
  {
    id: "sci-f2-c1-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah perbezaan paling jelas antara telur amfibia dan telur reptilia yang membolehkan kedua-duanya dibezakan dalam kekunci dikotomi?",
    options: [
      "Telur amfibia lebih besar daripada telur reptilia",
      "Telur amfibia tidak bercengkerang (seperti agar-agar), telur reptilia bercengkerang",
      "Telur amfibia berwarna-warni, telur reptilia putih",
      "Hanya reptilia yang bertelur",
    ],
    answerIndex: 1,
    explanation: "Telur amfibia berbentuk seperti agar-agar tanpa cengkerang, manakala telur reptilia mempunyai cengkerang yang keras.",
  },
  {
    id: "sci-f2-c1-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Seorang pelajar mendakwa 'semua tumbuhan berpembuluh adalah tumbuhan berbunga'. Adakah dakwaan ini tepat? Mengapa?",
    options: [
      "Tepat, kerana hanya tumbuhan berbunga mempunyai sistem vaskular",
      "Tidak tepat, kerana paku pakis dan konifer adalah tumbuhan tidak berbunga yang juga berpembuluh",
      "Tepat, kerana lumut juga berbunga dan berpembuluh",
      "Tidak tepat, kerana semua tumbuhan tidak berpembuluh",
    ],
    answerIndex: 1,
    explanation: "Dakwaan tidak tepat kerana paku pakis dan konifer ialah tumbuhan tidak berbunga tetapi tetap mempunyai sistem vaskular (berpembuluh).",
  },
  {
    id: "sci-f2-c1-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagaimanakah kepelbagaian genetik dalam sesuatu spesies tumbuhan dapat membantu spesies itu bertahan terhadap perubahan persekitaran secara mendadak?",
    options: [
      "Kepelbagaian genetik tidak memberi sebarang kesan kepada daya tahan spesies",
      "Variasi gen yang berbeza membolehkan sebahagian individu mempunyai ciri yang lebih sesuai untuk terus hidup dalam keadaan baharu",
      "Kepelbagaian genetik hanya wujud dalam haiwan, bukan tumbuhan",
      "Kepelbagaian genetik menyebabkan semua individu mati serentak",
    ],
    answerIndex: 1,
    explanation: "Kepelbagaian genetik bermaksud variasi gen dalam sesuatu spesies; variasi ini membolehkan sebahagian individu mempunyai ciri yang lebih sesuai untuk terus hidup walaupun persekitaran berubah secara mendadak.",
  },
  {
    id: "sci-f2-c1-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Satu spesies yang jarang ditemui semakin berkurang akibat kemusnahan habitat dan pemburuan haram. Pelan manakah paling berkesan untuk memulihara spesies itu dalam jangka panjang?",
    options: [
      "Melindungi habitatnya, menguatkuasakan undang-undang hidupan liar dan menjalankan program pembiakan apabila perlu",
      "Melindungi beberapa individu sahaja tetapi membenarkan habitat terus dimusnahkan",
      "Menghentikan semua penyelidikan saintifik terhadap spesies itu",
      "Memindahkan semua individu secara kekal ke zoo bandar",
    ],
    answerIndex: 0,
    explanation:
      "Pemuliharaan jangka panjang yang berkesan menggabungkan perlindungan habitat, penguatkuasaan undang-undang terhadap pemburuan haram, dan program pembiakan apabila perlu.",
  },
];
