import type { QuizQuestion } from "@/data/content";

export const scienceF2C1QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c1-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah maksud biodiversiti?",
    options: [
      "Kepelbagaian organisma seperti mikroorganisma, haiwan dan tumbuhan",
      "Bilangan haiwan yang hidup di sesebuah negara",
      "Jenis tanah yang terdapat di sesuatu kawasan",
      "Suhu purata sesebuah habitat",
    ],
    answerIndex: 0,
    explanation:
      "Biodiversiti ialah kepelbagaian organisma sama ada mikroorganisma, haiwan atau tumbuhan, termasuk kepelbagaian genetik.",
  },
  {
    id: "sci-f2-c1-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Malaysia diiktiraf sebagai salah satu daripada berapa buah negara megabiodiversiti di dunia?",
    options: ["8", "10", "12", "15"],
    answerIndex: 2,
    explanation: "Malaysia ialah salah satu daripada 12 negara megabiodiversiti di dunia.",
  },
  {
    id: "sci-f2-c1-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Pada tarikh berapakah Hari Biodiversiti Sedunia disambut?",
    options: ["5 Jun", "22 Mei", "1 Mac", "16 September"],
    answerIndex: 1,
    explanation: "Hari Biodiversiti Sedunia (International Day for Biological Diversity) disambut pada 22 Mei setiap tahun.",
  },
  {
    id: "sci-f2-c1-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Akta manakah yang mengharamkan pembunuhan atau perdagangan haiwan dan tumbuhan endemik serta terancam di Malaysia?",
    options: [
      "Akta Alam Sekitar 1974",
      "Akta Perlindungan Hidupan Liar 1972",
      "Akta Hutan Negara 1984",
      "Akta Taman Negara 1980",
    ],
    answerIndex: 1,
    explanation: "Akta Perlindungan Hidupan Liar 1972 mengharamkan pembunuhan atau perdagangan haiwan dan tumbuhan endemik serta terancam.",
  },
  {
    id: "sci-f2-c1-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Antara berikut, yang manakah contoh spesies endemik di Malaysia?",
    options: ["Kucing", "Anjing", "Bunga rafflesia", "Lembu"],
    answerIndex: 2,
    explanation: "Bunga rafflesia ialah contoh spesies endemik di Malaysia, selain periuk kera, penyu belimbing, harimau Malaya dan gajah Borneo.",
  },
  {
    id: "sci-f2-c1-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Haiwan tanpa tulang belakang dikenali sebagai...",
    options: ["Vertebrata", "Invertebrata", "Homeoterma", "Poikiloterma"],
    answerIndex: 1,
    explanation: "Invertebrata ialah haiwan yang tidak mempunyai tulang belakang.",
  },
  {
    id: "sci-f2-c1-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Berapa kumpulan utama vertebrata yang dipelajari dalam bab ini?",
    options: ["3", "4", "5", "6"],
    answerIndex: 2,
    explanation: "Lima kumpulan vertebrata ialah ikan, amfibia, reptilia, burung dan mamalia.",
  },
  {
    id: "sci-f2-c1-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Organisma yang suhu badannya berubah mengikut suhu persekitaran dipanggil...",
    options: ["Homeoterma", "Poikiloterma", "Invertebrata", "Vertebrata"],
    answerIndex: 1,
    explanation: "Poikiloterma ialah organisma yang suhu badannya berubah mengikut suhu persekitaran.",
  },
  {
    id: "sci-f2-c1-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Tumbuhan berikut tergolong dalam kumpulan tidak berbunga, KECUALI...",
    options: ["Lumut", "Paku pakis", "Konifer", "Pokok padi"],
    answerIndex: 3,
    explanation: "Pokok padi ialah tumbuhan berbunga (monokotiledon), bukan tumbuhan tidak berbunga.",
  },
  {
    id: "sci-f2-c1-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Biji benih dengan satu kotiledon dikenali sebagai...",
    options: ["Dikotiledon", "Monokotiledon", "Konifer", "Spora"],
    answerIndex: 1,
    explanation: "Biji benih dengan satu kotiledon dipanggil monokotiledon, contohnya padi dan jagung.",
  },
  {
    id: "sci-f2-c1-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah perbezaan utama antara pemuliharaan in situ dan ex situ?",
    options: [
      "In situ memelihara spesies dalam habitat asal, ex situ memelihara di luar habitat asal",
      "In situ hanya untuk haiwan, ex situ hanya untuk tumbuhan",
      "In situ dijalankan di zoo, ex situ dijalankan di taman negara",
      "In situ dan ex situ adalah perkara yang sama",
    ],
    answerIndex: 0,
    explanation: "Pemuliharaan in situ memelihara spesies dalam habitat semula jadinya, manakala ex situ memelihara spesies di luar habitat asalnya seperti di zoo atau taman botani.",
  },
  {
    id: "sci-f2-c1-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Cacing pita dan lintah diklasifikasikan sebagai invertebrata yang...",
    options: [
      "Mempunyai kaki dan badan bersegmen",
      "Tanpa kaki dan badan bersegmen",
      "Tanpa kaki dan tanpa badan bersegmen",
      "Mempunyai lebih daripada tiga pasang kaki",
    ],
    answerIndex: 1,
    explanation: "Cacing pita dan lintah ialah invertebrata tanpa kaki tetapi mempunyai badan bersegmen.",
  },
  {
    id: "sci-f2-c1-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Berapa pasang kaki yang dimiliki oleh serangga seperti semut dan rama-rama?",
    options: ["Dua pasang", "Tiga pasang", "Empat pasang", "Lima pasang"],
    answerIndex: 1,
    explanation: "Serangga seperti semut, rama-rama dan lipas mempunyai tiga pasang kaki.",
  },
  {
    id: "sci-f2-c1-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Antara berikut, yang manakah kumpulan vertebrata yang mengalami persenyawaan luaran?",
    options: ["Burung dan mamalia", "Reptilia dan burung", "Ikan dan amfibia", "Mamalia dan reptilia"],
    answerIndex: 2,
    explanation: "Ikan dan amfibia mengalami persenyawaan luaran, berbeza dengan reptilia, burung dan mamalia yang mengalami persenyawaan dalaman.",
  },
  {
    id: "sci-f2-c1-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah burung dikategorikan sebagai homeoterma walaupun ia bertelur?",
    options: [
      "Kerana telur burung tidak bercengkerang",
      "Kerana suhu badan burung malar dan tidak dipengaruhi suhu persekitaran",
      "Kerana burung hidup di darat dan di air",
      "Kerana burung mengalami persenyawaan luaran",
    ],
    answerIndex: 1,
    explanation: "Homeoterma ditentukan oleh sama ada suhu badan malar (tetap), bukan oleh cara pembiakan. Burung mengekalkan suhu badan yang tetap menggunakan bulu.",
  },
  {
    id: "sci-f2-c1-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah perbezaan utama antara akar tumbuhan monokotiledon dan dikotiledon?",
    options: [
      "Monokotiledon mempunyai akar tunjang, dikotiledon mempunyai akar serabut",
      "Monokotiledon mempunyai akar serabut, dikotiledon mempunyai akar tunjang",
      "Kedua-duanya mempunyai akar tunjang",
      "Kedua-duanya tidak mempunyai akar",
    ],
    answerIndex: 1,
    explanation: "Tumbuhan monokotiledon mempunyai akar serabut (fibrus), manakala dikotiledon mempunyai akar tunjang.",
  },
  {
    id: "sci-f2-c1-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Lumut berbeza daripada paku pakis dan konifer kerana lumut...",
    options: [
      "Membiak melalui kon",
      "Mempunyai sistem vaskular",
      "Tidak mempunyai sistem vaskular (tidak berpembuluh)",
      "Merupakan tumbuhan berbunga",
    ],
    answerIndex: 2,
    explanation: "Lumut tidak mempunyai sistem vaskular (tidak berpembuluh), berbeza dengan paku pakis dan konifer yang berpembuluh.",
  },
  {
    id: "sci-f2-c1-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Dalam kekunci dikotomi, apakah yang dimaksudkan dengan 'kuplet'?",
    options: [
      "Satu organisma tunggal yang dikaji",
      "Dua penyataan ciri yang membahagikan organisma kepada dua pilihan",
      "Jumlah keseluruhan organisma dalam satu kumpulan",
      "Nama saintifik bagi sesuatu organisma",
    ],
    answerIndex: 1,
    explanation: "Kuplet ialah dua penyataan yang menggambarkan ciri-ciri organisma, membahagikannya kepada pilihan (a) atau (b).",
  },
  {
    id: "sci-f2-c1-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah kepentingan biodiversiti yang dirujuk apabila herba digunakan untuk menghasilkan ubat-ubatan?",
    options: ["Sumber makanan", "Perubatan", "Bahan mentah industri", "Pendidikan"],
    answerIndex: 1,
    explanation: "Penggunaan herba dalam pembuatan ubat-ubatan dan kosmetik merupakan kepentingan biodiversiti dari aspek perubatan.",
  },
  {
    id: "sci-f2-c1-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Penebangan hutan secara berlebihan boleh menjejaskan biodiversiti terutamanya kerana...",
    options: [
      "Ia meningkatkan bilangan spesies endemik",
      "Ia menyebabkan haiwan kehilangan habitat dan sumber makanan",
      "Ia mengurangkan suhu persekitaran secara mendadak",
      "Ia hanya menjejaskan tumbuhan, bukan haiwan",
    ],
    answerIndex: 1,
    explanation: "Penebangan hutan yang tidak terkawal menyebabkan haiwan kehilangan habitat dan sumber makanan, sekali gus mengancam biodiversiti.",
  },
  {
    id: "sci-f2-c1-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Satu kekunci dikotomi memberikan kuplet: 1(a) Poikiloterma → ke 2, 1(b) Homeoterma → ke 3; 3(a) Tidak berbulu → Singa, 3(b) Berbulu → Ayam. Seekor haiwan X ialah homeoterma dan berbulu. Apakah haiwan X?",
    options: ["Singa", "Ayam", "Ular", "Katak"],
    answerIndex: 1,
    explanation: "Mengikut laluan kuplet: homeoterma → ke 3 → berbulu → Ayam.",
  },
  {
    id: "sci-f2-c1-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Seorang penyelidik menjumpai haiwan baharu yang berbulu, melahirkan anak hidup dan menyusukan anaknya. Berdasarkan ciri ini, haiwan tersebut paling tepat dikelaskan sebagai...",
    options: ["Reptilia", "Burung", "Mamalia", "Amfibia"],
    answerIndex: 2,
    explanation: "Ciri melahirkan anak hidup dan menyusukannya adalah ciri unik mamalia, ditambah dengan ciri berbulu yang juga khusus mamalia.",
  },
  {
    id: "sci-f2-c1-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah serangga tetap menjadi kumpulan haiwan yang paling berjaya dan banyak (950,000 spesies) walaupun ia adalah poikiloterma?",
    options: [
      "Kerana serangga mempunyai tulang belakang yang kukuh",
      "Kerana eksoskeleton yang keras, saiz badan kecil yang membolehkan menghuni pelbagai ceruk habitat, dan kadar pembiakan yang tinggi",
      "Kerana serangga hanya hidup di dalam air",
      "Kerana serangga mengalami persenyawaan dalaman seperti mamalia",
    ],
    answerIndex: 1,
    explanation: "Kejayaan serangga walaupun poikiloterma disebabkan oleh eksoskeleton keras untuk perlindungan, saiz kecil yang membolehkan mereka menghuni banyak ceruk habitat, dan kadar pembiakan yang tinggi.",
  },
  {
    id: "sci-f2-c1-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question:
      "Kekunci dikotomi tumbuhan: 1(a) Tidak berbunga → ke 2, 1(b) Berbunga → ke 3; 2(a) Tidak berpembuluh → Marchantia sp., 2(b) Berpembuluh → ke 4; 4(a) Tidak menghasilkan biji benih → Paku pakis, 4(b) Menghasilkan biji benih → Gnetum sp. Sebatang tumbuhan Y tidak berbunga, berpembuluh dan menghasilkan biji benih. Apakah tumbuhan Y?",
    options: ["Marchantia sp.", "Paku pakis", "Gnetum sp.", "Pokok jagung"],
    answerIndex: 2,
    explanation: "Laluan: tidak berbunga → ke 2 → berpembuluh → ke 4 → menghasilkan biji benih → Gnetum sp.",
  },
  {
    id: "sci-f2-c1-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah pemuliharaan ex situ seperti zoo dan taman botani masih penting walaupun spesies tidak berada dalam habitat asalnya?",
    options: [
      "Kerana ia lebih murah berbanding pemuliharaan in situ",
      "Kerana ia membolehkan pemantauan rapi, pembiakan terkawal dan penyelidikan untuk menyelamatkan spesies yang sangat terancam",
      "Kerana ia menggantikan keperluan kawasan hutan simpan",
      "Kerana semua spesies lebih selesa di luar habitat asal",
    ],
    answerIndex: 1,
    explanation: "Pemuliharaan ex situ membolehkan pemantauan rapi, program pembiakan terkawal dan penyelidikan saintifik, terutamanya bagi spesies yang berisiko tinggi pupus di habitat asal.",
  },
  {
    id: "sci-f2-c1-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Seekor haiwan didapati mempunyai kulit bersisik keras, bertelur bercengkerang dan mengalami persenyawaan dalaman, tetapi suhu badannya berubah mengikut persekitaran. Apakah kumpulan vertebrata bagi haiwan ini?",
    options: ["Burung", "Mamalia", "Reptilia", "Ikan"],
    answerIndex: 2,
    explanation: "Ciri poikiloterma, kulit bersisik keras, telur bercengkerang dan persenyawaan dalaman adalah ciri khusus reptilia (contoh: ular, buaya).",
  },
  {
    id: "sci-f2-c1-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Apakah perbezaan paling jelas antara telur amfibia dan telur reptilia yang membolehkan kedua-duanya dibezakan dalam kekunci dikotomi?",
    options: [
      "Telur amfibia lebih besar daripada telur reptilia",
      "Telur amfibia tidak bercengkerang (seperti agar-agar), telur reptilia bercengkerang",
      "Telur amfibia berwarna-warni, telur reptilia putih",
      "Hanya reptilia yang bertelur",
    ],
    answerIndex: 1,
    explanation: "Telur amfibia berbentuk seperti agar-agar tanpa cengkerang, manakala telur reptilia mempunyai cengkerang yang keras.",
  },
  {
    id: "sci-f2-c1-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Seorang pelajar mendakwa 'semua tumbuhan berpembuluh adalah tumbuhan berbunga'. Adakah dakwaan ini tepat? Mengapa?",
    options: [
      "Tepat, kerana hanya tumbuhan berbunga mempunyai sistem vaskular",
      "Tidak tepat, kerana paku pakis dan konifer adalah tumbuhan tidak berbunga yang juga berpembuluh",
      "Tepat, kerana lumut juga berbunga dan berpembuluh",
      "Tidak tepat, kerana semua tumbuhan tidak berpembuluh",
    ],
    answerIndex: 1,
    explanation: "Dakwaan tidak tepat kerana paku pakis dan konifer ialah tumbuhan tidak berbunga tetapi tetap mempunyai sistem vaskular (berpembuluh).",
  },
  {
    id: "sci-f2-c1-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Bagaimanakah kepelbagaian genetik dalam sesuatu spesies tumbuhan dapat membantu spesies itu bertahan terhadap perubahan persekitaran secara mendadak?",
    options: [
      "Kepelbagaian genetik tidak memberi sebarang kesan kepada daya tahan spesies",
      "Variasi gen yang berbeza membolehkan sebahagian individu mempunyai ciri yang lebih sesuai untuk terus hidup dalam keadaan baharu",
      "Kepelbagaian genetik hanya wujud dalam haiwan, bukan tumbuhan",
      "Kepelbagaian genetik menyebabkan semua individu mati serentak",
    ],
    answerIndex: 1,
    explanation: "Kepelbagaian genetik bermaksud variasi gen dalam sesuatu spesies; variasi ini membolehkan sebahagian individu mempunyai ciri yang lebih sesuai untuk terus hidup walaupun persekitaran berubah secara mendadak.",
  },
  {
    id: "sci-f2-c1-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 1",
    lang: "bm",
    question: "Mengapakah penting untuk membina kekunci dikotomi dengan tepat dua pilihan (a) dan (b) bagi setiap kuplet, bukan tiga atau lebih?",
    options: [
      "Kerana peraturan ini hanya untuk memudahkan ingatan murid tanpa sebab saintifik",
      "Kerana sistem dikotomi bermaksud 'pembahagian kepada dua', supaya setiap langkah klasifikasi tetap sistematik dan tidak mengelirukan",
      "Kerana hanya dua organisma boleh wujud dalam dunia ini",
      "Kerana kekunci dengan tiga pilihan tidak boleh dilukis di atas kertas",
    ],
    answerIndex: 1,
    explanation: "Perkataan 'dikotomi' bermaksud pembahagian kepada dua bahagian; struktur ini memastikan setiap langkah klasifikasi konsisten, sistematik dan tidak mengelirukan apabila mengenal pasti organisma.",
  },
];
