import type { Flashcard } from "@/data/content";

export const scienceF2C9FlashcardsDLP: Flashcard[] = [
  // Deck 1: Basics (Cards 1-20)
  {
    id: "sci-f2-c9-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is heat?",
    back: "A form of energy that flows from a hotter region to a colder region.",
  },
  {
    id: "sci-f2-c9-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is temperature?",
    back: "A measure of the degree of hotness or coldness of an object, measured using a thermometer.",
  },
  {
    id: "sci-f2-c9-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is the unit of heat?",
    back: "Joule (J).",
  },
  {
    id: "sci-f2-c9-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is the unit of temperature?",
    back: "Degrees Celsius (°C) or Kelvin (K).",
  },
  {
    id: "sci-f2-c9-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is conduction?",
    back: "The process of heat transfer from hotter regions to colder regions through a solid medium.",
  },
  {
    id: "sci-f2-c9-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is convection?",
    back: "Heat transfer by the movement of fluid (liquid and gas) from a hotter region to a colder region.",
  },
  {
    id: "sci-f2-c9-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is radiation?",
    back: "The process of transferring heat without any medium; can propagate through an empty space or vacuum.",
  },
  {
    id: "sci-f2-c9-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is a convection current?",
    back: "The continuous rising and falling stream of heat flow in a fluid caused by differences in density.",
  },
  {
    id: "sci-f2-c9-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is a heat conductor?",
    back: "A material that allows heat flow, such as mercury and metal.",
  },
  {
    id: "sci-f2-c9-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is a heat insulator?",
    back: "A material that prevents heat flow, such as fibreglass, wood and polystyrene.",
  },
  {
    id: "sci-f2-c9-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is thermal equilibrium?",
    back: "A condition where there is no net transfer of heat energy between two objects in thermal contact; both objects have the same temperature.",
  },
  {
    id: "sci-f2-c9-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is sea breeze?",
    back: "Wind that forms during the day when warm air on land rises and cold air from the sea moves in to replace it.",
  },
  {
    id: "sci-f2-c9-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is land breeze?",
    back: "Wind that forms at night when warm air above the sea rises and cold air from the land moves towards the sea.",
  },
  {
    id: "sci-f2-c9-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is expansion?",
    back: "An increase in the volume of a substance when heated because particles move faster and further apart.",
  },
  {
    id: "sci-f2-c9-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is contraction?",
    back: "A decrease in the volume of a substance when cooled because particles move slower and closer together.",
  },
  {
    id: "sci-f2-c9-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is an expansion gap?",
    back: "A small gap built into structures such as railway tracks to allow expansion in hot weather.",
  },
  {
    id: "sci-f2-c9-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is a bimetallic strip?",
    back: "A strip made from two different types of metal that expand and contract at different rates, used in fire alarm systems.",
  },
  {
    id: "sci-f2-c9-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is heat absorption?",
    back: "The process of an object receiving heat energy, causing its temperature to increase.",
  },
  {
    id: "sci-f2-c9-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is heat radiation (emission)?",
    back: "The process of an object releasing heat energy, causing its temperature to decrease.",
  },
  {
    id: "sci-f2-c9-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is the Green Building Concept?",
    back: "An idea to reduce the effects of development on the environment through energy efficiency, good air circulation/lighting systems and the use of recycled materials.",
  },

  // Deck 2: Understanding (Cards 21-40)
  {
    id: "sci-f2-c9-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Compare heat and temperature.",
    back: "Heat: a form of energy, measured in joule, depends on the type and quantity of material. Temperature: degree of hotness/coldness, measured in °C/K, depends on particle movement.",
  },
  {
    id: "sci-f2-c9-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Compare conduction, convection and radiation by medium.",
    back: "Conduction: requires a solid medium. Convection: requires a fluid medium (liquid/gas). Radiation: requires no medium, can propagate through a vacuum.",
  },
  {
    id: "sci-f2-c9-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does Activity 9.1 demonstrate conduction?",
    back: "Thumbtacks held by wax on a copper rod fall off in sequence when one end of the rod is heated, showing heat flows along the rod.",
  },
  {
    id: "sci-f2-c9-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does Activity 9.1 demonstrate convection in liquid?",
    back: "A potassium permanganate crystal moves upward in a beaker of heated water, showing a convection current.",
  },
  {
    id: "sci-f2-c9-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does Activity 9.1 demonstrate convection in gas?",
    back: "Smoke moves due to the movement of hot and cold air in a beaker, showing a convection current of air.",
  },
  {
    id: "sci-f2-c9-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does Activity 9.1 demonstrate radiation?",
    back: "Heat can still be felt even when air is removed from a bell jar (vacuum), showing radiation does not require a medium.",
  },
  {
    id: "sci-f2-c9-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Compare sea breeze and land breeze.",
    back: "Sea breeze: daytime, warm air on land rises, cold air from the sea replaces it. Land breeze: night, warm air above the sea rises, cold air from land moves to the sea.",
  },
  {
    id: "sci-f2-c9-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Why is heat from the Sun to the Earth transferred through radiation?",
    back: "Because radiation is the only method of heat transfer that can propagate through the empty space (vacuum) between the Sun and Earth.",
  },
  {
    id: "sci-f2-c9-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Compare solid particles with liquid and gas particles when heated.",
    back: "Solid: particles vibrate at a fixed position, vibrate faster & further apart. Liquid/gas: particles move freely, move faster & randomly; distance between particles increases.",
  },
  {
    id: "sci-f2-c9-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does Activity 9.4 demonstrate expansion and contraction of a solid?",
    back: "A heated metal bar expands and cannot fit into a gauge, but contracts again when cooled.",
  },
  {
    id: "sci-f2-c9-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does Activity 9.4 demonstrate expansion and contraction of a liquid?",
    back: "The coloured water level in a glass tube rises when a conical flask is placed in hot water, and falls when placed in ice.",
  },
  {
    id: "sci-f2-c9-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does Activity 9.4 demonstrate expansion and contraction of a gas?",
    back: "A balloon attached to a conical flask expands with hot water and contracts with ice.",
  },
  {
    id: "sci-f2-c9-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Compare dark/dull surfaces with white/shiny surfaces.",
    back: "Dark and dull surfaces: better heat absorbers and radiators. White and shiny surfaces: weaker heat absorbers and radiators.",
  },
  {
    id: "sci-f2-c9-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is the result of Experiment 9.2 Part A (heat absorber)?",
    back: "Can K (black) shows a greater increase in temperature compared to can J (white), proving dark surfaces absorb heat better.",
  },
  {
    id: "sci-f2-c9-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "What is the result of Experiment 9.2 Part B (heat radiator)?",
    back: "Can K (black) shows a greater decrease in temperature compared to can J (white), proving dark surfaces radiate heat better.",
  },
  {
    id: "sci-f2-c9-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Compare cotton/felt with aluminium foil in Experiment 9.1.",
    back: "Cotton and felt: good heat insulators (maintain the temperature of hot water). Aluminium foil: a heat conductor.",
  },
  {
    id: "sci-f2-c9-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Why is the bottom of a pan and the base of an iron made of metal?",
    back: "Metal is a good heat conductor, allowing heat to flow quickly to the food or clothes.",
  },
  {
    id: "sci-f2-c9-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Why is the wall of an ice box made of fibreglass or polystyrene?",
    back: "Because both are good heat insulators that can maintain the coolness of substances inside the box.",
  },
  {
    id: "sci-f2-c9-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Compare railway tracks and steel bridges in terms of expansion.",
    back: "Railway tracks: small gaps between rails. Steel bridges: rollers and a gap on one end — both designs allow expansion in hot weather.",
  },
  {
    id: "sci-f2-c9-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "How does a bimetallic strip function in a fire alarm?",
    back: "The copper strip expands faster than the steel strip when exposed to heat, causing the strip to bend towards the contact point and complete the circuit.",
  },

  // Deck 3: Exam (Cards 41-60)
  {
    id: "sci-f2-c9-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why are heat and temperature not the same even though they are interrelated?",
    back: "Heat is energy (joule) that depends on the type & quantity of material as well as temperature; temperature depends on the degree of particle movement, measured in °C/K.",
  },
  {
    id: "sci-f2-c9-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] A metal bar cannot fit into a gauge after being heated. What is the explanation?",
    back: "Particles in the bar vibrate faster and move further apart when heated, causing the bar to expand and its volume to increase.",
  },
  {
    id: "sci-f2-c9-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why are expansion gaps important on railway tracks?",
    back: "Without these gaps, the tracks would buckle and overlap due to the expansion of the metal in hot weather.",
  },
  {
    id: "sci-f2-c9-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] How does a bimetallic strip ring a fire alarm?",
    back: "The copper strip expands faster than the steel strip when exposed to fire heat, bending towards the contact point and completing the electrical circuit.",
  },
  {
    id: "sci-f2-c9-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why does the black can show a greater temperature change in Experiment 9.2?",
    back: "Dark and dull surfaces are better heat absorbers and radiators compared to white and shiny surfaces.",
  },
  {
    id: "sci-f2-c9-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[Common Mistake] Does radiation require a medium to propagate?",
    back: "No. Radiation is the only method of heat transfer that does not require a medium and can propagate through a vacuum.",
  },
  {
    id: "sci-f2-c9-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[Common Mistake] Do sea breeze and land breeze occur at the same time?",
    back: "No. Sea breeze occurs during the day, land breeze occurs at night, due to different heating/cooling rates between land and sea.",
  },
  {
    id: "sci-f2-c9-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why are fuel tanks painted white or silver?",
    back: "Bright colours do not absorb a lot of heat, thereby reducing the evaporation of fuel inside the tank.",
  },
  {
    id: "sci-f2-c9-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why is mercury in a thermometer suitable for detecting temperature changes quickly?",
    back: "Mercury is a good heat conductor and can expand/contract noticeably when receiving/releasing heat.",
  },
  {
    id: "sci-f2-c9-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[Exam Tip] How do you answer a question to 'differentiate conduction, convection and radiation'?",
    back: "State the medium as the main distinguishing factor: conduction (solid), convection (liquid/gas), radiation (no medium) — include an example for each.",
  },
  {
    id: "sci-f2-c9-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Objects A and B are in thermal contact and have the same temperature. What can be concluded?",
    back: "Objects A and B are in thermal equilibrium; there is no net transfer of heat energy between them.",
  },
  {
    id: "sci-f2-c9-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[Common Mistake] Are all metals heat insulators?",
    back: "No. Metals are good heat conductors, not heat insulators.",
  },
  {
    id: "sci-f2-c9-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why can a dented table tennis ball be fixed using hot water?",
    back: "The air inside the ball expands when heated, pushing the ball's wall back to its original shape.",
  },
  {
    id: "sci-f2-c9-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] How does the Green Building Concept reduce heat/energy usage?",
    back: "Through high energy efficiency (solar/renewable energy), good air circulation and lighting systems, and the use of recycled materials.",
  },
  {
    id: "sci-f2-c9-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Name two examples of heat insulator use in daily life.",
    back: "Oven gloves and wooden cooking utensils (also: polystyrene ice boxes, thermos flasks).",
  },
  {
    id: "sci-f2-c9-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why is roasted chicken wrapped in aluminium foil in an oven?",
    back: "To help retain/reflect heat around the food so it cooks evenly.",
  },
  {
    id: "sci-f2-c9-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why are electric transmission cables hung loosely on poles?",
    back: "To allow the cables to contract and expand due to temperature changes without breaking.",
  },
  {
    id: "sci-f2-c9-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[Common Mistake] Does an object that absorbs heat become colder?",
    back: "No. When an object absorbs heat, its temperature increases (it becomes hotter), not colder.",
  },
  {
    id: "sci-f2-c9-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "[KBAT] Why does an electric kettle have a heating coil at the bottom?",
    back: "So the whole volume of water is heated efficiently through a convection current that forms from the bottom upward.",
  },
  {
    id: "sci-f2-c9-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "dlp",
    front: "Summarise Chapter 9 in one sentence.",
    back: "Heat flows through conduction, convection and radiation from hot to cold regions, causing matter to expand/contract, and its rate of absorption/emission is influenced by the type of surface of an object.",
  },
];
