import type { Flashcard } from "@/data/content";

export const scienceF2C9FlashcardsBM: Flashcard[] = [
  // Set 1: Haba, Suhu & Pengaliran Haba
  {
    id: "sci-f2-c9-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah haba?",
    back: "Satu bentuk tenaga yang mengalir daripada kawasan lebih panas ke kawasan lebih sejuk.",
  },
  {
    id: "sci-f2-c9-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah suhu?",
    back: "Ukuran tahap kepanasan atau kesejukan sesuatu objek, diukur menggunakan termometer.",
  },
  {
    id: "sci-f2-c9-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah unit bagi haba?",
    back: "Joule (J).",
  },
  {
    id: "sci-f2-c9-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah unit bagi suhu?",
    back: "Darjah Celsius (°C) atau Kelvin (K).",
  },
  {
    id: "sci-f2-c9-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan haba dengan suhu.",
    back: "Haba: bentuk tenaga, diukur dalam joule, bergantung pada jenis dan kuantiti bahan. Suhu: tahap kepanasan/kesejukan, diukur dalam °C/K, bergantung pada gerakan zarah.",
  },
  {
    id: "sci-f2-c9-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud konduksi?",
    back: "Pemindahan haba daripada kawasan lebih panas ke kawasan lebih sejuk apabila zarah yang bergetar memindahkan tenaga kepada zarah bersebelahan; berlaku terutamanya dalam pepejal.",
  },
  {
    id: "sci-f2-c9-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud perolakan?",
    back: "Pemindahan haba melalui pergerakan bendalir (cecair dan gas) daripada kawasan panas ke kawasan sejuk.",
  },
  {
    id: "sci-f2-c9-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud sinaran?",
    back: "Proses pemindahan haba tanpa sebarang medium; boleh merebak melalui ruang kosong atau vakum.",
  },
  {
    id: "sci-f2-c9-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan konduksi, perolakan dan sinaran dari segi medium.",
    back: "Konduksi: terutamanya melalui pepejal. Perolakan: melalui bendalir (cecair dan gas). Sinaran: tidak memerlukan medium dan boleh merambat melalui vakum.",
  },
  {
    id: "sci-f2-c9-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah arus perolakan?",
    back: "Aliran haba yang naik dan turun secara berterusan dalam bendalir akibat perbezaan ketumpatan.",
  },
  {
    id: "sci-f2-c9-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah demonstrasi rod kuprum menunjukkan konduksi?",
    back: "Paku tekan yang ditampung dengan lilin pada rod kuprum jatuh secara berurutan apabila satu hujung rod dipanaskan, menunjukkan haba mengalir melalui rod.",
  },
  {
    id: "sci-f2-c9-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah demonstrasi hablur kalium permanganat menunjukkan perolakan dalam cecair?",
    back: "Warna ungu daripada hablur itu naik di atas bahagian yang dipanaskan dan beredar, menunjukkan arus perolakan.",
  },
  {
    id: "sci-f2-c9-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah demonstrasi colok berbara menunjukkan perolakan dalam gas?",
    back: "Asap dibawa oleh udara panas yang naik dan udara sejuk yang turun, menunjukkan arus perolakan udara.",
  },
  {
    id: "sci-f2-c9-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah demonstrasi balang vakum menunjukkan sinaran?",
    back: "Haba masih dapat dirasakan walaupun udara dikeluarkan daripada balang loceng (vakum), menunjukkan sinaran tidak memerlukan medium.",
  },
  {
    id: "sci-f2-c9-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah haba daripada Matahari ke Bumi dipindahkan melalui sinaran?",
    back: "Kerana sinaran adalah satu-satunya kaedah pemindahan haba yang boleh merebak melalui ruang kosong (vakum) antara Matahari dan Bumi.",
  },
  {
    id: "sci-f2-c9-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah cerek elektrik mempunyai gegelung pemanas di bahagian bawah?",
    back: "Supaya keseluruhan air dipanaskan secara cekap melalui arus perolakan yang terbentuk dari bawah ke atas.",
  },
  {
    id: "sci-f2-c9-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah keseimbangan terma?",
    back: "Keadaan apabila tidak ada pemindahan bersih tenaga haba antara dua objek yang bersentuhan terma; kedua-dua objek mempunyai suhu yang sama.",
  },
  {
    id: "sci-f2-c9-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Dua objek A dan B bersentuhan terma dan suhunya sama. Apakah yang dapat disimpulkan?",
    back: "Objek A dan B berada dalam keseimbangan terma; tidak ada pemindahan bersih tenaga haba antara mereka.",
  },
  {
    id: "sci-f2-c9-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah bayu laut?",
    back: "Angin yang terhasil pada waktu siang apabila udara panas di daratan naik dan udara sejuk daripada laut bergerak masuk menggantikannya.",
  },
  {
    id: "sci-f2-c9-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah bayu darat?",
    back: "Angin yang terhasil pada waktu malam apabila udara panas di atas laut naik dan udara sejuk daripada daratan bergerak ke laut.",
  },
  // Set 2: Pengembangan & Pengecutan
  {
    id: "sci-f2-c9-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud pengembangan?",
    back: "Peningkatan isi padu bahan apabila dipanaskan kerana zarah bergerak lebih cepat dan lebih jauh.",
  },
  {
    id: "sci-f2-c9-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud pengecutan?",
    back: "Penurunan isi padu bahan apabila disejukkan kerana zarah bergerak lebih perlahan dan lebih rapat.",
  },
  {
    id: "sci-f2-c9-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan zarah pepejal dengan zarah cecair dan gas apabila dipanaskan.",
    back: "Pepejal: zarah bergetar pada kedudukan tetap, bergetar lebih cepat & jauh. Cecair/gas: zarah bergerak bebas, bergerak lebih cepat & rawak; jarak antara zarah meningkat.",
  },
  {
    id: "sci-f2-c9-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah yang berlaku kepada jisim sesuatu bahan apabila ia mengembang?",
    back: "Jisim kekal sama; hanya isi padu bertambah, jadi ketumpatannya berkurang.",
  },
  {
    id: "sci-f2-c9-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Mengapakah gas mengembang jauh lebih banyak daripada pepejal bagi kenaikan suhu yang sama?",
    back: "Zarah gas berjauhan dan bergerak bebas, manakala zarah pepejal dipegang rapat oleh daya yang kuat.",
  },
  {
    id: "sci-f2-c9-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Rod logam yang dipanaskan tidak lagi muat ke dalam toloknya. Apakah yang ditunjukkan?",
    back: "Pepejal mengembang apabila dipanaskan; rod itu muat semula selepas sejuk dan mengecut.",
  },
  {
    id: "sci-f2-c9-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Bagaimanakah air berwarna dalam tiub kaca yang dipasang pada kelalang menunjukkan pengembangan dan pengecutan cecair?",
    back: "Paras air berwarna dalam tiub kaca meningkat apabila kelalang kon direndam dalam air panas, dan menurun apabila direndam dalam ais.",
  },
  {
    id: "sci-f2-c9-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Bagaimanakah belon yang dipasang pada kelalang menunjukkan pengembangan dan pengecutan gas?",
    back: "Belon mengembang apabila kelalang diletakkan dalam air panas dan mengecut apabila diletakkan dalam ais.",
  },
  {
    id: "sci-f2-c9-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah termometer cecair dalam kaca berfungsi?",
    back: "Cecair (merkuri atau alkohol) mengembang dan naik dalam tiub sempit apabila dipanaskan, serta mengecut dan turun apabila disejukkan.",
  },
  {
    id: "sci-f2-c9-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Bagaimanakah merkuri dalam termometer sesuai untuk mengesan perubahan suhu dengan cepat?",
    back: "Merkuri adalah konduktor haba yang baik dan dapat mengembang/mengecut dengan ketara apabila menerima/melepaskan haba.",
  },
  {
    id: "sci-f2-c9-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah jurang dilatasi (expansion gap)?",
    back: "Jurang kecil yang dibina pada struktur seperti landasan kereta api untuk membolehkan pengembangan semasa cuaca panas.",
  },
  {
    id: "sci-f2-c9-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan landasan kereta api dengan jambatan keluli dari segi pengembangan.",
    back: "Landasan kereta api: jurang kecil antara rel. Jambatan keluli: roda gelek dan jurang pada satu hujung — kedua-dua reka bentuk membolehkan pengembangan semasa cuaca panas.",
  },
  {
    id: "sci-f2-c9-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah jurang dilatasi penting pada landasan kereta api?",
    back: "Tanpa jurang ini, landasan akan melengkung dan bertindih akibat pengembangan logam semasa cuaca panas.",
  },
  {
    id: "sci-f2-c9-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah kabel penghantaran elektrik digantung secara longgar di atas tiang?",
    back: "Untuk membenarkan pengecutan dan pengembangan kabel akibat perubahan suhu tanpa kabel terputus.",
  },
  {
    id: "sci-f2-c9-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah jalur dwilogam (bimetallic strip)?",
    back: "Jalur yang dibuat daripada dua jenis logam berbeza yang mengembang dan mengecut pada kadar berbeza, digunakan dalam penggera kebakaran.",
  },
  {
    id: "sci-f2-c9-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah jalur dwilogam berfungsi dalam penggera kebakaran?",
    back: "Jalur kuprum mengembang lebih cepat berbanding jalur besi apabila terdedah kepada haba, menyebabkan jalur melentur ke arah titik sentuhan dan melengkapkan litar.",
  },
  {
    id: "sci-f2-c9-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Sebatang rod logam tidak boleh dimasukkan ke dalam tolok selepas dipanaskan. Apakah penjelasannya?",
    back: "Zarah dalam rod bergetar lebih cepat dan bergerak lebih jauh apabila dipanaskan, menyebabkan rod mengembang dan isi padunya meningkat.",
  },
  {
    id: "sci-f2-c9-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah bola ping pong yang kemek dapat diperbaiki dengan air panas?",
    back: "Udara di dalam bola mengembang apabila dipanaskan, mendorong dinding bola kembali ke bentuk asal.",
  },
  {
    id: "sci-f2-c9-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah tayar logam dipasang dengan ketat pada roda kayu?",
    back: "Tayar logam dipanaskan supaya mengembang dan muat pada roda; apabila sejuk ia mengecut dan mencengkam roda dengan ketat.",
  },
  {
    id: "sci-f2-c9-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Mengapakah penutup logam yang ketat pada balang kaca lebih mudah dibuka selepas dialirkan air panas?",
    back: "Penutup logam mengembang lebih banyak daripada kaca, jadi ia menjadi longgar.",
  },
  // Set 3: Konduktor Haba, Penebat & Sifat Permukaan
  {
    id: "sci-f2-c9-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah konduktor haba?",
    back: "Bahan yang membenarkan aliran haba, contohnya merkuri dan logam.",
  },
  {
    id: "sci-f2-c9-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah penebat haba?",
    back: "Bahan yang menghalang aliran haba, contohnya gentian kaca, kayu dan polistirena.",
  },
  {
    id: "sci-f2-c9-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Adakah semua logam adalah penebat haba?",
    back: "Tidak. Logam adalah konduktor haba yang baik, bukan penebat haba.",
  },
  {
    id: "sci-f2-c9-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah tapak periuk dan dasar besi pelicin dibuat daripada logam?",
    back: "Logam adalah konduktor haba yang baik, membolehkan haba mengalir dengan cepat ke makanan atau pakaian.",
  },
  {
    id: "sci-f2-c9-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah dinding kotak ais dibuat daripada gentian kaca atau polistirena?",
    back: "Kerana kedua-duanya adalah penebat haba yang baik, dapat mengekalkan kesejukan bahan di dalam kotak.",
  },
  {
    id: "sci-f2-c9-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah pemegang periuk dibuat daripada kayu atau plastik?",
    back: "Kayu dan plastik ialah penebat haba, jadi haba tidak mengalir dengan cepat ke tangan.",
  },
  {
    id: "sci-f2-c9-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Namakan dua contoh penggunaan penebat haba dalam kehidupan harian.",
    back: "Sarung tangan ketuhar dan peralatan masakan kayu (juga: kotak ais polistirena, kelalang termos).",
  },
  {
    id: "sci-f2-c9-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan kapas/felt dengan kerajang aluminium dalam penyiasatan penebat haba.",
    back: "Kapas dan felt: penebat haba yang baik (mengekalkan suhu air panas). Kerajang aluminium: konduktor haba.",
  },
  {
    id: "sci-f2-c9-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah kelalang vakum mempunyai vakum di antara dinding berlapisnya?",
    back: "Vakum menghalang pemindahan haba secara konduksi dan perolakan.",
  },
  {
    id: "sci-f2-c9-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah penyerapan haba?",
    back: "Proses sesuatu objek menerima tenaga haba, menyebabkan suhunya meningkat.",
  },
  {
    id: "sci-f2-c9-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah pembebasan haba (sinaran)?",
    back: "Proses sesuatu objek melepaskan tenaga haba, menyebabkan suhunya menurun.",
  },
  {
    id: "sci-f2-c9-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan permukaan gelap/kusam dengan permukaan putih/berkilat.",
    back: "Permukaan gelap dan kusam: penyerap dan pembebas haba yang lebih baik. Permukaan putih dan berkilat: penyerap dan pembebas haba yang lebih lemah.",
  },
  {
    id: "sci-f2-c9-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Dua tin yang sama, satu hitam dan satu putih, dibiarkan di bawah cahaya matahari. Tin manakah lebih cepat panas, dan mengapa?",
    back: "Tin hitam, kerana permukaan gelap dan kusam ialah penyerap haba yang lebih baik.",
  },
  {
    id: "sci-f2-c9-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Dua tin sama yang berisi air panas, satu hitam dan satu putih, dibiarkan menyejuk. Tin manakah lebih cepat sejuk, dan mengapa?",
    back: "Tin hitam, kerana permukaan gelap dan kusam ialah pembebas haba yang lebih baik.",
  },
  {
    id: "sci-f2-c9-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah penduduk di negara panas selalu memakai pakaian berwarna cerah?",
    back: "Permukaan berwarna cerah menyerap kurang haba daripada Matahari, jadi pemakainya berasa lebih sejuk.",
  },
  {
    id: "sci-f2-c9-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah tangki bahan api dicat putih atau perak?",
    back: "Warna terang tidak menyerap banyak haba, dengan itu mengurangkan penyejatan bahan api di dalam tangki.",
  },
  {
    id: "sci-f2-c9-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front:
      "Apakah ciri permukaan dinding kelalang termos yang membantu mengekalkan suhu air panas?",
    back: "Permukaan yang berkilat. Permukaan berkilat ialah pembebas haba yang kurang baik, jadi haba lebih lambat hilang daripada air panas di dalamnya.",
  },
  {
    id: "sci-f2-c9-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah sirip penyejuk di belakang peti sejuk dicat hitam?",
    back: "Permukaan gelap dan kusam ialah pembebas haba yang baik, jadi haba dibebaskan dengan cepat.",
  },
  {
    id: "sci-f2-c9-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah Konsep Bangunan Hijau?",
    back: "Idea untuk mengurangkan kesan pembangunan terhadap alam sekitar melalui kecekapan tenaga, sistem aliran udara/pencahayaan yang baik dan penggunaan bahan kitar semula.",
  },
  {
    id: "sci-f2-c9-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Adakah objek yang menyerap haba menjadi lebih sejuk?",
    back: "Tidak. Apabila objek menyerap haba, suhunya meningkat (menjadi lebih panas), bukan menjadi sejuk.",
  },
];
