import type { Flashcard } from "@/data/content";

export const scienceF2C9FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c9-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah haba?",
    back: "Satu bentuk tenaga yang mengalir daripada kawasan lebih panas ke kawasan lebih sejuk.",
  },
  {
    id: "sci-f2-c9-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah suhu?",
    back: "Ukuran tahap kepanasan atau kesejukan sesuatu objek, diukur menggunakan termometer.",
  },
  {
    id: "sci-f2-c9-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah unit bagi haba?",
    back: "Joule (J).",
  },
  {
    id: "sci-f2-c9-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah unit bagi suhu?",
    back: "Darjah Celsius (°C) atau Kelvin (K).",
  },
  {
    id: "sci-f2-c9-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud konduksi?",
    back: "Proses pemindahan haba daripada kawasan lebih panas kepada kawasan lebih sejuk melalui medium pepejal.",
  },
  {
    id: "sci-f2-c9-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud perolakan?",
    back: "Pemindahan haba melalui pergerakan bendalir (cecair dan gas) daripada kawasan panas ke kawasan sejuk.",
  },
  {
    id: "sci-f2-c9-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud sinaran?",
    back: "Proses pemindahan haba tanpa sebarang medium; boleh merebak melalui ruang kosong atau vakum.",
  },
  {
    id: "sci-f2-c9-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah arus perolakan?",
    back: "Aliran haba yang naik dan turun secara berterusan dalam bendalir akibat perbezaan ketumpatan.",
  },
  {
    id: "sci-f2-c9-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah konduktor haba?",
    back: "Bahan yang membenarkan aliran haba, contohnya merkuri dan logam.",
  },
  {
    id: "sci-f2-c9-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah penebat haba?",
    back: "Bahan yang menghalang aliran haba, contohnya gentian kaca, kayu dan polistirena.",
  },
  {
    id: "sci-f2-c9-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah keseimbangan terma?",
    back: "Keadaan apabila tidak ada pemindahan bersih tenaga haba antara dua objek yang bersentuhan terma; kedua-dua objek mempunyai suhu yang sama.",
  },
  {
    id: "sci-f2-c9-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah bayu laut?",
    back: "Angin yang terhasil pada waktu siang apabila udara panas di daratan naik dan udara sejuk daripada laut bergerak masuk menggantikannya.",
  },
  {
    id: "sci-f2-c9-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah bayu darat?",
    back: "Angin yang terhasil pada waktu malam apabila udara panas di atas laut naik dan udara sejuk daripada daratan bergerak ke laut.",
  },
  {
    id: "sci-f2-c9-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud pengembangan?",
    back: "Peningkatan isi padu bahan apabila dipanaskan kerana zarah bergerak lebih cepat dan lebih jauh.",
  },
  {
    id: "sci-f2-c9-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah maksud pengecutan?",
    back: "Penurunan isi padu bahan apabila disejukkan kerana zarah bergerak lebih perlahan dan lebih rapat.",
  },
  {
    id: "sci-f2-c9-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah jurang dilatasi (expansion gap)?",
    back: "Jurang kecil yang dibina pada struktur seperti landasan kereta api untuk membolehkan pengembangan semasa cuaca panas.",
  },
  {
    id: "sci-f2-c9-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah jalur dwilogam (bimetallic strip)?",
    back: "Jalur yang dibuat daripada dua jenis logam berbeza yang mengembang dan mengecut pada kadar berbeza, digunakan dalam penggera kebakaran.",
  },
  {
    id: "sci-f2-c9-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah penyerapan haba?",
    back: "Proses sesuatu objek menerima tenaga haba, menyebabkan suhunya meningkat.",
  },
  {
    id: "sci-f2-c9-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah pembebasan haba (sinaran)?",
    back: "Proses sesuatu objek melepaskan tenaga haba, menyebabkan suhunya menurun.",
  },
  {
    id: "sci-f2-c9-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah Konsep Bangunan Hijau?",
    back: "Idea untuk mengurangkan kesan pembangunan terhadap alam sekitar melalui kecekapan tenaga, sistem aliran udara/pencahayaan yang baik dan penggunaan bahan kitar semula.",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c9-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan haba dengan suhu.",
    back: "Haba: bentuk tenaga, diukur dalam joule, bergantung pada jenis dan kuantiti bahan. Suhu: tahap kepanasan/kesejukan, diukur dalam °C/K, bergantung pada gerakan zarah.",
  },
  {
    id: "sci-f2-c9-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan konduksi, perolakan dan sinaran dari segi medium.",
    back: "Konduksi: memerlukan medium pepejal. Perolakan: memerlukan medium bendalir (cecair/gas). Sinaran: tidak memerlukan sebarang medium, boleh merebak melalui vakum.",
  },
  {
    id: "sci-f2-c9-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah Aktiviti 9.1 menunjukkan konduksi?",
    back: "Paku tekan yang ditampung dengan lilin pada rod kuprum jatuh secara berurutan apabila satu hujung rod dipanaskan, menunjukkan haba mengalir melalui rod.",
  },
  {
    id: "sci-f2-c9-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah Aktiviti 9.1 menunjukkan perolakan dalam cecair?",
    back: "Hablur kalium permanganat bergerak ke atas dalam bikar air yang dipanaskan, menunjukkan arus perolakan.",
  },
  {
    id: "sci-f2-c9-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah Aktiviti 9.1 menunjukkan perolakan dalam gas?",
    back: "Asap bergerak akibat pergerakan udara panas dan sejuk dalam bikar, menunjukkan arus perolakan udara.",
  },
  {
    id: "sci-f2-c9-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah Aktiviti 9.1 menunjukkan sinaran?",
    back: "Haba masih dapat dirasakan walaupun udara dikeluarkan daripada balang loceng (vakum), menunjukkan sinaran tidak memerlukan medium.",
  },
  {
    id: "sci-f2-c9-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan bayu laut dan bayu darat.",
    back: "Bayu laut: waktu siang, udara panas di daratan naik, udara sejuk laut menggantikannya. Bayu darat: waktu malam, udara panas di laut naik, udara sejuk daratan bergerak ke laut.",
  },
  {
    id: "sci-f2-c9-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah haba daripada Matahari ke Bumi dipindahkan melalui sinaran?",
    back: "Kerana sinaran adalah satu-satunya kaedah pemindahan haba yang boleh merebak melalui ruang kosong (vakum) antara Matahari dan Bumi.",
  },
  {
    id: "sci-f2-c9-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan zarah pepejal dengan zarah cecair dan gas apabila dipanaskan.",
    back: "Pepejal: zarah bergetar pada kedudukan tetap, bergetar lebih cepat & jauh. Cecair/gas: zarah bergerak bebas, bergerak lebih cepat & rawak; jarak antara zarah meningkat.",
  },
  {
    id: "sci-f2-c9-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah Aktiviti 9.4 menunjukkan pengembangan dan pengecutan pepejal?",
    back: "Rod logam yang dipanaskan mengembang dan tidak dapat dimasukkan ke dalam tolok, tetapi mengecut semula apabila disejukkan.",
  },
  {
    id: "sci-f2-c9-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah Aktiviti 9.4 menunjukkan pengembangan dan pengecutan cecair?",
    back: "Paras air berwarna dalam tiub kaca meningkat apabila kelalang kon direndam dalam air panas, dan menurun apabila direndam dalam ais.",
  },
  {
    id: "sci-f2-c9-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah Aktiviti 9.4 menunjukkan pengembangan dan pengecutan gas?",
    back: "Belon yang dikenakan udara panas mengembang, dan mengecut apabila dikenakan ais.",
  },
  {
    id: "sci-f2-c9-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan permukaan gelap/kasar dengan permukaan putih/berkilat.",
    back: "Permukaan gelap dan kasar: penyerap dan pembebas haba yang lebih baik. Permukaan putih dan berkilat: penyerap dan pembebas haba yang lebih lemah.",
  },
  {
    id: "sci-f2-c9-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah keputusan Eksperimen 9.2 Bahagian A (penyerap haba)?",
    back: "Tin K (hitam) menunjukkan peningkatan suhu yang lebih besar berbanding tin J (putih), membuktikan permukaan gelap lebih baik menyerap haba.",
  },
  {
    id: "sci-f2-c9-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Apakah keputusan Eksperimen 9.2 Bahagian B (pembebas haba)?",
    back: "Tin K (hitam) menunjukkan penurunan suhu yang lebih besar berbanding tin J (putih), membuktikan permukaan gelap lebih baik membebaskan haba.",
  },
  {
    id: "sci-f2-c9-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan kapas/felt dengan kerajang aluminium dalam Eksperimen 9.1.",
    back: "Kapas dan felt: penebat haba yang baik (mengekalkan suhu air panas). Kerajang aluminium: konduktor haba.",
  },
  {
    id: "sci-f2-c9-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah tapak periuk dan dasar besi pelicin dibuat daripada logam?",
    back: "Logam adalah konduktor haba yang baik, membolehkan haba mengalir dengan cepat ke makanan atau pakaian.",
  },
  {
    id: "sci-f2-c9-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Mengapakah dinding kotak ais dibuat daripada gentian kaca atau polistirena?",
    back: "Kerana kedua-duanya adalah penebat haba yang baik, dapat mengekalkan kesejukan bahan di dalam kotak.",
  },
  {
    id: "sci-f2-c9-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bandingkan landasan kereta api dengan jambatan keluli dari segi pengembangan.",
    back: "Landasan kereta api: jurang kecil antara rel. Jambatan keluli: roda gelek dan jurang pada satu hujung — kedua-dua reka bentuk membolehkan pengembangan semasa cuaca panas.",
  },
  {
    id: "sci-f2-c9-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Bagaimanakah jalur dwilogam berfungsi dalam penggera kebakaran?",
    back: "Jalur kuprum mengembang lebih cepat berbanding jalur keluli apabila terdedah kepada haba, menyebabkan jalur melentur ke arah titik sentuhan dan melengkapkan litar.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c9-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah haba dan suhu tidak sama walaupun saling berkait?",
    back: "Haba adalah tenaga (joule) yang bergantung pada jenis & kuantiti bahan serta suhu; suhu bergantung pada darjah gerakan zarah, diukur dalam °C/K.",
  },
  {
    id: "sci-f2-c9-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Sebatang rod logam tidak boleh dimasukkan ke dalam tolok selepas dipanaskan. Apakah penjelasannya?",
    back: "Zarah dalam rod bergetar lebih cepat dan bergerak lebih jauh apabila dipanaskan, menyebabkan rod mengembang dan isi padunya meningkat.",
  },
  {
    id: "sci-f2-c9-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah jurang dilatasi penting pada landasan kereta api?",
    back: "Tanpa jurang ini, landasan akan melengkung dan bertindih akibat pengembangan logam semasa cuaca panas.",
  },
  {
    id: "sci-f2-c9-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Bagaimanakah jalur dwilogam membunyikan penggera kebakaran?",
    back: "Jalur kuprum mengembang lebih cepat daripada jalur keluli apabila terdedah haba kebakaran, melentur ke arah titik sentuhan dan melengkapkan litar elektrik.",
  },
  {
    id: "sci-f2-c9-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah tin hitam menunjukkan perubahan suhu yang lebih besar dalam Eksperimen 9.2?",
    back: "Permukaan gelap dan kasar adalah penyerap dan pembebas haba yang lebih baik berbanding permukaan putih dan berkilat.",
  },
  {
    id: "sci-f2-c9-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah sinaran memerlukan medium untuk merebak?",
    back: "Tidak. Sinaran ialah satu-satunya kaedah pemindahan haba yang tidak memerlukan medium dan boleh merebak melalui vakum.",
  },
  {
    id: "sci-f2-c9-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah bayu laut dan bayu darat berlaku pada masa yang sama?",
    back: "Tidak. Bayu laut berlaku pada waktu siang, bayu darat berlaku pada waktu malam, disebabkan kadar pemanasan/penyejukan berbeza antara daratan dan laut.",
  },
  {
    id: "sci-f2-c9-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah tangki bahan api dicat putih atau perak?",
    back: "Warna terang tidak menyerap banyak haba, dengan itu mengurangkan penyejatan bahan api di dalam tangki.",
  },
  {
    id: "sci-f2-c9-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Bagaimanakah merkuri dalam termometer sesuai untuk mengesan perubahan suhu dengan cepat?",
    back: "Merkuri adalah konduktor haba yang baik dan dapat mengembang/mengecut dengan ketara apabila menerima/melepaskan haba.",
  },
  {
    id: "sci-f2-c9-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan 'bezakan konduksi, perolakan dan sinaran'?",
    back: "Nyatakan medium sebagai pembeza utama: konduksi (pepejal), perolakan (cecair/gas), sinaran (tanpa medium) — sertakan contoh setiap satu.",
  },
  {
    id: "sci-f2-c9-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Dua objek A dan B bersentuhan terma dan suhunya sama. Apakah yang dapat disimpulkan?",
    back: "Objek A dan B berada dalam keseimbangan terma; tidak ada pemindahan bersih tenaga haba antara mereka.",
  },
  {
    id: "sci-f2-c9-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah semua logam adalah penebat haba?",
    back: "Tidak. Logam adalah konduktor haba yang baik, bukan penebat haba.",
  },
  {
    id: "sci-f2-c9-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah bola ping pong yang kemek dapat diperbaiki dengan air panas?",
    back: "Udara di dalam bola mengembang apabila dipanaskan, mendorong dinding bola kembali ke bentuk asal.",
  },
  {
    id: "sci-f2-c9-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Bagaimanakah Konsep Bangunan Hijau mengurangkan penggunaan haba/tenaga?",
    back: "Melalui kecekapan tenaga tinggi (tenaga solar/boleh diperbaharui), sistem aliran udara dan pencahayaan yang baik, serta penggunaan bahan kitar semula.",
  },
  {
    id: "sci-f2-c9-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Namakan dua contoh penggunaan penebat haba dalam kehidupan harian.",
    back: "Sarung tangan ketuhar dan peralatan masakan kayu (juga: kotak ais polistirena, kelalang termos).",
  },
  {
    id: "sci-f2-c9-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah ayam panggang dibalut kerajang aluminium dalam ketuhar?",
    back: "Untuk membantu mengekalkan/memantulkan haba di sekeliling makanan supaya ia masak secara sekata.",
  },
  {
    id: "sci-f2-c9-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah kabel penghantaran elektrik digantung secara longgar di atas tiang?",
    back: "Untuk membenarkan pengecutan dan pengembangan kabel akibat perubahan suhu tanpa kabel terputus.",
  },
  {
    id: "sci-f2-c9-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah objek yang menyerap haba menjadi lebih sejuk?",
    back: "Tidak. Apabila objek menyerap haba, suhunya meningkat (menjadi lebih panas), bukan menjadi sejuk.",
  },
  {
    id: "sci-f2-c9-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "[KBAT] Mengapakah periuk elektrik mempunyai gegelung pemanas di bahagian bawah?",
    back: "Supaya keseluruhan air dipanaskan secara cekap melalui arus perolakan yang terbentuk dari bawah ke atas.",
  },
  {
    id: "sci-f2-c9-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 9",
    lang: "bm",
    front: "Ringkaskan Bab 9 dalam satu ayat.",
    back: "Haba mengalir melalui konduksi, perolakan dan sinaran daripada kawasan panas ke sejuk, menyebabkan pengembangan/pengecutan jirim, dan kadar penyerapan/pembebasannya dipengaruhi oleh jenis permukaan objek.",
  },
];
