import type { QuizQuestion } from "@/data/content";

export const scienceF2C9QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c9-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah haba?",
    options: [
      "Satu bentuk tenaga",
      "Ukuran tahap kepanasan sesuatu objek",
      "Kadar pemindahan tenaga haba",
      "Jumlah pengembangan sesuatu pepejal",
    ],
    answerIndex: 0,
    explanation: "Haba ialah satu bentuk tenaga yang mengalir dari kawasan lebih panas ke kawasan lebih sejuk.",
  },
  {
    id: "sci-f2-c9-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah suhu?",
    options: [
      "Satu bentuk tenaga",
      "Ukuran tahap kepanasan atau kesejukan sesuatu objek",
      "Jumlah haba yang terkandung dalam suatu bahan",
      "Kadar pemindahan haba antara dua objek",
    ],
    answerIndex: 1,
    explanation: "Suhu mengukur tahap kepanasan atau kesejukan sesuatu objek.",
  },
  {
    id: "sci-f2-c9-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Yang manakah berikut membandingkan dengan betul unit haba dan suhu?",
    options: [
      "Haba diukur dalam joule (J); suhu diukur dalam °C atau K",
      "Haba diukur dalam °C; suhu diukur dalam joule (J)",
      "Kedua-dua haba dan suhu diukur dalam joule (J)",
      "Kedua-dua haba dan suhu diukur dalam °C",
    ],
    answerIndex: 0,
    explanation: "Haba ialah tenaga dan diukur dalam joule. Suhu diukur dalam °C atau K.",
  },
  {
    id: "sci-f2-c9-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question:
      "Bikar P mengandungi 500 ml air dan bikar Q mengandungi 100 ml air, kedua-duanya pada suhu yang sama. Bikar manakah mengandungi lebih banyak haba, dan mengapa?",
    options: [
      "Bikar P, kerana ia mengandungi kuantiti air yang lebih banyak walaupun suhunya sama",
      "Bikar Q, kerana isi padu yang lebih kecil menyimpan haba dengan lebih cekap",
      "Kedua-duanya sama, kerana jumlah haba bergantung pada suhu sahaja",
      "Bikar Q, kerana haba tertumpu dalam isi padu air yang lebih kecil",
    ],
    answerIndex: 0,
    explanation: "Pada suhu yang sama, kuantiti bahan yang lebih banyak mengandungi lebih banyak haba.",
  },
  {
    id: "sci-f2-c9-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah arah aliran haba yang betul?",
    options: [
      "Daripada kawasan panas ke kawasan sejuk",
      "Daripada kawasan sejuk ke kawasan panas",
      "Apabila kedua-dua objek sudah sama suhu",
      "Daripada objek yang lebih besar ke objek yang lebih kecil, tanpa mengira suhu",
    ],
    answerIndex: 0,
    explanation: "Haba mengalir dari kawasan yang lebih panas ke kawasan yang lebih sejuk.",
  },
  {
    id: "sci-f2-c9-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah konduksi?",
    options: [
      "Pemindahan haba melalui pergerakan bendalir",
      "Pemindahan haba melalui pepejal tanpa pepejal itu berpindah",
      "Pemindahan haba tanpa sebarang medium",
      "Pemindahan haba oleh arus udara panas yang naik",
    ],
    answerIndex: 1,
    explanation: "Konduksi memindahkan haba melalui pepejal dari bahagian panas ke bahagian sejuk.",
  },
  {
    id: "sci-f2-c9-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah perolakan?",
    options: [
      "Pemindahan haba melalui getaran zarah dalam pepejal",
      "Pemindahan haba tanpa medium, termasuk melalui vakum",
      "Pemindahan haba melalui pergerakan bendalir yang panas",
      "Pemindahan haba apabila dua pepejal mencapai suhu yang sama",
    ],
    answerIndex: 2,
    explanation: "Perolakan memindahkan haba apabila bendalir yang dipanaskan bergerak.",
  },
  {
    id: "sci-f2-c9-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah sinaran?",
    options: [
      "Pemindahan haba melalui getaran zarah pepejal",
      "Pemindahan haba oleh bendalir yang naik dan turun",
      "Pemindahan haba yang memerlukan udara sebagai medium",
      "Pemindahan haba tanpa medium, termasuk melalui vakum",
    ],
    answerIndex: 3,
    explanation: "Sinaran memindahkan haba tanpa medium dan boleh melalui vakum.",
  },
  {
    id: "sci-f2-c9-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Kenyataan manakah yang membandingkan dengan betul konduktor haba dan penebat haba?",
    options: [
      "Konduktor mengalirkan haba dengan mudah; penebat memperlahankan aliran haba",
      "Konduktor memperlahankan haba; penebat mengalirkan haba dengan mudah",
      "Kedua-duanya mengalirkan haba pada kadar yang sama",
      "Kedua-duanya menghentikan aliran haba sepenuhnya",
    ],
    answerIndex: 0,
    explanation: "Konduktor haba seperti logam mengalirkan haba dengan mudah. Penebat memperlahankan aliran itu.",
  },
  {
    id: "sci-f2-c9-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah tenaga haba daripada Matahari sampai ke Bumi?",
    options: [
      "Melalui konduksi merentasi vakum angkasa lepas",
      "Melalui arus perolakan di angkasa lepas",
      "Melalui sinaran, yang boleh merambat melalui vakum",
      "Melalui konduksi dalam atmosfera sahaja, kerana vakum menghalang haba",
    ],
    answerIndex: 2,
    explanation: "Haba Matahari sampai ke Bumi melalui sinaran, yang tidak memerlukan medium.",
  },
  {
    id: "sci-f2-c9-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah maksud keseimbangan terma?",
    options: [
      "Satu objek kekal lebih panas daripada objek yang bersentuhan dengannya",
      "Haba bersih berpindah melalui sinaran, bukan melalui konduksi",
      "Tiada pemindahan bersih haba antara dua objek yang sama suhu",
      "Dua objek terus memindahkan haba bersih walaupun suhu sudah sama",
    ],
    answerIndex: 2,
    explanation: "Keseimbangan terma berlaku apabila tiada pemindahan bersih haba dan kedua-dua objek sama suhu.",
  },
  {
    id: "sci-f2-c9-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question:
      "Dalam demonstrasi konduksi, mengapakah paku tekan jatuh secara berurutan apabila rod kuprum dipanaskan pada satu hujung?",
    options: [
      "Rod mengembang dan menggugurkan paku dari hujung yang dipanaskan dahulu",
      "Udara panas naik dan melelehkan lilin dari hujung yang jauh dahulu",
      "Sinaran nyalaan melelehkan semua lilin pada masa yang sama",
      "Haba mengalir melalui konduksi dan melelehkan lilin mengikut turutan sepanjang rod",
    ],
    answerIndex: 3,
    explanation: "Konduksi memindahkan haba sepanjang rod, jadi lilin meleleh dan paku jatuh mengikut turutan.",
  },
  {
    id: "sci-f2-c9-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah hablur kalium permanganat bergerak ke atas dalam bikar air yang dipanaskan?",
    options: [
      "Air panas menjadi kurang tumpat, naik, dan membawa hablur dalam arus perolakan",
      "Hablur menjadi kurang tumpat daripada air lalu terapung dengan sendirinya",
      "Konduksi melalui kaca menolak hablur ke tepi bikar",
      "Sinaran dari penunu menjadikan hablur lebih ringan daripada udara",
    ],
    answerIndex: 0,
    explanation: "Air yang dipanaskan mengembang, menjadi kurang tumpat dan naik, lalu membawa hablur dalam arus perolakan.",
  },
  {
    id: "sci-f2-c9-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah demonstrasi balang vakum menunjukkan sinaran sebagai cara pemindahan haba?",
    options: [
      "Haba dirasakan hanya semasa udara masih ada, jadi udara diperlukan",
      "Haba masih dapat dirasakan selepas udara dikeluarkan dari balang",
      "Dinding balang mengalirkan haba, jadi mengeluarkan udara tidak mengubah apa-apa",
      "Balang menghentikan sinaran, jadi haba hanya sampai melalui perolakan udara yang tinggal",
    ],
    answerIndex: 1,
    explanation: "Haba masih dirasakan dalam vakum, jadi pemindahan itu tidak memerlukan udara.",
  },
  {
    id: "sci-f2-c9-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah bayu laut terbentuk pada waktu siang?",
    options: [
      "Udara sejuk di daratan mengalir ke laut yang lebih panas",
      "Daratan menyejuk lebih cepat, jadi udara daratan mengalir ke laut",
      "Udara panas di daratan naik, dan udara lebih sejuk dari laut masuk menggantikannya",
      "Udara di atas laut naik dahulu, dan udara daratan masuk menggantikannya",
    ],
    answerIndex: 2,
    explanation: "Pada siang, daratan lebih cepat panas. Udara daratan naik dan udara laut yang lebih sejuk masuk.",
  },
  {
    id: "sci-f2-c9-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah bayu darat terbentuk pada waktu malam?",
    options: [
      "Udara daratan dan udara laut berhenti bergerak apabila tiada cahaya matahari",
      "Daratan kekal lebih panas, jadi udara laut terus masuk ke daratan",
      "Udara daratan naik dan udara laut yang lebih sejuk masuk menggantikannya",
      "Daratan menyejuk lebih cepat, udara laut naik, dan udara daratan mengalir ke laut",
    ],
    answerIndex: 3,
    explanation: "Pada malam, daratan menyejuk lebih cepat. Udara laut yang lebih panas naik dan udara daratan mengalir ke laut.",
  },
  {
    id: "sci-f2-c9-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah merkuri digunakan dalam termometer?",
    options: [
      "Ia mengalirkan haba dengan baik dan mengembang apabila suhu berubah",
      "Ia penebat haba, jadi suhu di dalamnya kekal malar",
      "Ia hampir tidak mengembang, jadi skala boleh dibuat sangat panjang",
      "Ia membeku pada suhu bilik, jadi lajur mudah dilihat",
    ],
    answerIndex: 0,
    explanation: "Merkuri mengalirkan haba dengan baik dan mengembang atau mengecut apabila suhu berubah.",
  },
  {
    id: "sci-f2-c9-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Dalam penyiasatan penebat haba, bahan manakah yang merupakan penebat haba yang baik?",
    options: ["Kerajang aluminium", "Kapas dan felt", "Logam kuprum", "Rod besi"],
    answerIndex: 1,
    explanation: "Kapas dan felt memperlahankan kehilangan haba. Logam seperti aluminium, kuprum dan besi mengalirkan haba.",
  },
  {
    id: "sci-f2-c9-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah sarung tangan ketuhar digunakan untuk mengeluarkan dulang makanan daripada ketuhar?",
    options: [
      "Sarung itu konduktor haba, jadi haba dulang sampai ke tangan dengan cepat",
      "Sarung itu menyejukkan dulang sebelum dulang diangkat",
      "Sarung itu penebat haba, jadi aliran haba ke tangan diperlahankan",
      "Sarung itu meningkatkan suhu dulang supaya makanan kekal panas",
    ],
    answerIndex: 2,
    explanation: "Sarung tangan ketuhar ialah penebat haba yang memperlahankan haba sampai ke tangan.",
  },
  {
    id: "sci-f2-c9-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apa yang berlaku kepada zarah pepejal apabila pepejal itu dipanaskan?",
    options: [
      "Zarah bergetar lebih perlahan dan saling mendekat",
      "Zarah bergetar lebih cepat tetapi jarak antara zarah tidak berubah",
      "Zarah meninggalkan kedudukan tetap dan mengalir seperti cecair",
      "Zarah bergetar lebih cepat dan saling menjauh, lalu pepejal mengembang",
    ],
    answerIndex: 3,
    explanation: "Pemanasan membuat zarah pepejal bergetar lebih cepat dan lebih jauh, jadi pepejal mengembang.",
  },
  {
    id: "sci-f2-c9-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question:
      "Sebatang rod logam yang baru dikeluarkan daripada api tidak boleh dimasukkan ke dalam tolok, tetapi boleh dimasukkan semula selepas disejukkan dengan air. Apakah penjelasan yang sesuai bagi pemerhatian ini?",
    options: [
      "Zarah rod bergetar lebih jauh apabila panas, jadi rod mengembang; penyejukan mendekatkan zarah dan rod mengecut",
      "Zarah rod bergetar lebih cepat apabila panas, tetapi rod mengecut kerana logam mengalirkan haba",
      "Tolok mengembang lebih banyak daripada rod, jadi rod panas tidak muat",
      "Penyejukan menjauhkan zarah rod, jadi rod yang sejuk menjadi lebih panjang",
    ],
    answerIndex: 0,
    explanation: "Rod panas mengembang kerana zarahnya bergetar lebih jauh. Apabila disejukkan, rod mengecut dan muat semula.",
  },
  {
    id: "sci-f2-c9-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah landasan kereta api dibina dengan jurang kecil antara relnya?",
    options: [
      "Supaya rel mengecut semasa panas dan jurang menjadi lebih besar",
      "Supaya rel boleh mengembang semasa panas tanpa melengkung",
      "Supaya haba rel terbebas lebih cepat melalui jurang itu",
      "Supaya pengembangan rel terhenti sepenuhnya oleh penyambung",
    ],
    answerIndex: 1,
    explanation: "Jurang memberi ruang untuk rel mengembang semasa panas supaya landasan tidak melengkung.",
  },
  {
    id: "sci-f2-c9-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah jalur dwilogam berfungsi dalam sistem penggera kebakaran?",
    options: [
      "Kuprum dan besi mengembang sama banyak, lalu litar tertutup serta-merta",
      "Kedua-dua logam mengecut apabila panas, lalu litar terbuka",
      "Kuprum mengembang lebih cepat daripada besi, jalur melentur dan menutup litar",
      "Besi mengembang lebih cepat daripada kuprum, jalur melentur menjauhi sentuhan",
    ],
    answerIndex: 2,
    explanation: "Kuprum mengembang lebih cepat daripada besi, jadi jalur melentur, menutup litar dan membunyikan penggera.",
  },
  {
    id: "sci-f2-c9-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question:
      "Dalam penyiasatan permukaan gelap dan cerah, tin J dicat putih dan tin K dicat hitam, kemudian kedua-duanya diletakkan berhampiran penunu. Apakah pemerhatian dan kesimpulannya?",
    options: [
      "Tin J lebih panas; permukaan putih dan berkilat menyerap haba lebih baik",
      "Kedua-dua tin sama suhu; warna permukaan tidak mempengaruhi penyerapan",
      "Tin K lebih sejuk; permukaan gelap memantulkan haba lebih baik",
      "Tin K lebih panas; permukaan gelap dan kusam menyerap haba lebih baik",
    ],
    answerIndex: 3,
    explanation: "Tin hitam menjadi lebih panas kerana permukaan gelap dan kusam menyerap haba lebih baik.",
  },
  {
    id: "sci-f2-c9-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question:
      "Dalam penyiasatan pembebasan haba, tin J (putih) dan tin K (hitam) diisi air panas. Apakah pemerhatian yang menunjukkan tin K pembebas haba yang lebih baik?",
    options: [
      "Suhu tin K menurun lebih banyak daripada suhu tin J",
      "Suhu tin K menurun lebih sedikit daripada suhu tin J",
      "Suhu kedua-dua tin tidak berubah",
      "Suhu tin J menurun lebih banyak daripada suhu tin K",
    ],
    answerIndex: 0,
    explanation: "Penurunan suhu yang lebih besar pada tin hitam menunjukkan permukaan gelap membebaskan haba lebih baik.",
  },
  {
    id: "sci-f2-c9-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah tangki bahan api biasanya dicat dengan warna terang seperti putih atau perak?",
    options: [
      "Warna terang menyerap lebih banyak haba dan menyejukkan bahan api",
      "Warna terang menyerap kurang haba, jadi penyejatan bahan api berkurang",
      "Warna gelap akan memantulkan haba dan mengurangkan penyejatan",
      "Warna cat tidak mempengaruhi penyerapan; ketebalan logam yang menentukannya",
    ],
    answerIndex: 1,
    explanation: "Warna terang menyerap kurang haba daripada warna gelap, jadi bahan api kurang menyerap haba dan kurang menyejat.",
  },
  {
    id: "sci-f2-c9-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question:
      "Seorang murid mendakwa haba dan suhu adalah perkara yang sama. Pernyataan manakah yang membetulkan dakwaan ini?",
    options: [
      "Dakwaan betul, kerana kedua-duanya diukur dalam joule",
      "Dakwaan tidak tepat, kerana suhu ialah tenaga dan haba ialah bacaan termometer",
      "Dakwaan tidak tepat; haba ialah tenaga dalam joule yang bergantung pada kuantiti bahan, manakala suhu mengukur gerakan zarah",
      "Dakwaan tidak tepat, kerana jumlah haba bergantung pada suhu sahaja, bukan kuantiti bahan",
    ],
    answerIndex: 2,
    explanation: "Haba ialah tenaga dan bergantung pada jenis, kuantiti dan suhu bahan. Suhu mengukur darjah kepanasan.",
  },
  {
    id: "sci-f2-c9-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah pengembangan haba boleh melonggarkan penutup botol logam yang ketat?",
    options: [
      "Rendam penutup dalam air sejuk supaya logam mengembang",
      "Biarkan botol pada suhu bilik supaya penutup mengecut pada kaca",
      "Rendam penutup dalam air panas supaya logam mengecut dan menekan leher kaca",
      "Rendam penutup dalam air panas supaya logam mengembang dan longgar",
    ],
    answerIndex: 3,
    explanation: "Air panas mengembangkan penutup logam, lalu penutup menjadi lebih longgar.",
  },
  {
    id: "sci-f2-c9-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Jambatan keluli dibina dengan roda gelek dan jurang pada satu hujung. Apakah tujuan reka bentuk ini?",
    options: [
      "Membolehkan jambatan mengembang semasa panas tanpa rosak",
      "Membolehkan jambatan mengecut semasa panas supaya kekal tegang",
      "Menghentikan semua pengembangan dengan memaut kedua-dua hujung",
      "Mempercepat kehilangan haba supaya panjang keluli tidak berubah",
    ],
    answerIndex: 0,
    explanation: "Roda gelek dan jurang memberi ruang untuk keluli mengembang semasa panas.",
  },
  {
    id: "sci-f2-c9-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah ciri Konsep Bangunan Hijau yang berkaitan dengan pengurusan haba dan tenaga?",
    options: [
      "Mengurangkan kecekapan tenaga supaya bangunan menggunakan lebih banyak elektrik",
      "Kecekapan tenaga yang tinggi, termasuk tenaga boleh diperbaharui serta pengudaraan dan pencahayaan yang baik",
      "Kaca gelap sahaja, supaya bangunan menyerap lebih banyak haba matahari",
      "Menutup semua pengudaraan supaya udara sejuk tidak pernah keluar",
    ],
    answerIndex: 1,
    explanation: "Bangunan Hijau menekankan kecekapan tenaga, tenaga boleh diperbaharui, pengudaraan dan pencahayaan yang baik.",
  },
];
