import type { QuizQuestion } from "@/data/content";

export const scienceF2C9QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c9-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is heat?",
    options: [
      "A form of energy",
      "A measure of how hot an object is",
      "The rate of heat-energy transfer",
      "The total expansion of a solid",
    ],
    answerIndex: 0,
    explanation: "Heat is a form of energy that flows from a hotter region to a cooler region.",
  },
  {
    id: "sci-f2-c9-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is temperature?",
    options: [
      "A form of energy",
      "A measure of how hot or cold an object is",
      "The amount of heat contained in a material",
      "The rate of heat transfer between two objects",
    ],
    answerIndex: 1,
    explanation: "Temperature measures how hot or cold an object is.",
  },
  {
    id: "sci-f2-c9-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Which of the following correctly compares the units of heat and temperature?",
    options: [
      "Heat is measured in joules (J); temperature is measured in °C or K",
      "Heat is measured in °C; temperature is measured in joules (J)",
      "Both heat and temperature are measured in joules (J)",
      "Both heat and temperature are measured in °C",
    ],
    answerIndex: 0,
    explanation: "Heat is energy and is measured in joules. Temperature is measured in °C or K.",
  },
  {
    id: "sci-f2-c9-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question:
      "Beaker P contains 500 ml of water and beaker Q contains 100 ml of water, both at the same temperature. Which beaker contains more heat, and why?",
    options: [
      "Beaker P, because it contains a greater quantity of water even though the temperature is the same",
      "Beaker Q, because a smaller volume stores heat more efficiently",
      "Both are the same, because the amount of heat depends only on temperature",
      "Beaker Q, because the heat is concentrated in the smaller volume of water",
    ],
    answerIndex: 0,
    explanation: "At the same temperature, a greater quantity of material contains more heat.",
  },
  {
    id: "sci-f2-c9-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is the correct direction of heat flow?",
    options: [
      "From a hot region to a cold region",
      "From a cold region to a hot region",
      "When both objects are already at the same temperature",
      "From a larger object to a smaller object, regardless of temperature",
    ],
    answerIndex: 0,
    explanation: "Heat flows from a hotter region to a cooler region.",
  },
  {
    id: "sci-f2-c9-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is conduction?",
    options: [
      "Heat transfer by the movement of a fluid",
      "Heat transfer through a solid without the solid itself moving",
      "Heat transfer without any medium",
      "Heat transfer by rising currents of hot air",
    ],
    answerIndex: 1,
    explanation: "Conduction transfers heat through a solid from the hot part to the cold part.",
  },
  {
    id: "sci-f2-c9-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is convection?",
    options: [
      "Heat transfer through particle vibration in a solid",
      "Heat transfer without a medium, including through a vacuum",
      "Heat transfer by the movement of a heated fluid",
      "Heat transfer when two solids reach the same temperature",
    ],
    answerIndex: 2,
    explanation: "Convection transfers heat when a heated fluid moves.",
  },
  {
    id: "sci-f2-c9-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is radiation?",
    options: [
      "Heat transfer through vibration of solid particles",
      "Heat transfer by a fluid that rises and sinks",
      "Heat transfer that requires air as a medium",
      "Heat transfer without a medium, including through a vacuum",
    ],
    answerIndex: 3,
    explanation: "Radiation transfers heat without a medium and can pass through a vacuum.",
  },
  {
    id: "sci-f2-c9-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Which statement correctly compares heat conductors and heat insulators?",
    options: [
      "Conductors transfer heat easily; insulators slow down heat flow",
      "Conductors slow down heat; insulators transfer heat easily",
      "Both transfer heat at the same rate",
      "Both stop heat flow completely",
    ],
    answerIndex: 0,
    explanation: "Heat conductors such as metals transfer heat easily. Insulators slow that flow.",
  },
  {
    id: "sci-f2-c9-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does heat energy from the Sun reach the Earth?",
    options: [
      "By conduction across the vacuum of space",
      "By convection currents in space",
      "By radiation, which can travel through a vacuum",
      "By conduction in the atmosphere only, because a vacuum blocks heat",
    ],
    answerIndex: 2,
    explanation: "Heat from the Sun reaches the Earth by radiation, which does not need a medium.",
  },
  {
    id: "sci-f2-c9-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is thermal equilibrium?",
    options: [
      "One object stays hotter than the object touching it",
      "Net heat is transferred by radiation, not by conduction",
      "No net heat transfer between two objects at the same temperature",
      "Two objects keep transferring net heat even after their temperatures are equal",
    ],
    answerIndex: 2,
    explanation: "Thermal equilibrium occurs when there is no net heat transfer and both objects are at the same temperature.",
  },
  {
    id: "sci-f2-c9-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question:
      "In the conduction demonstration, why do the drawing pins fall in sequence when a copper rod is heated at one end?",
    options: [
      "The rod expands and shakes the pins off from the heated end first",
      "Hot air rises and melts the wax from the far end first",
      "Radiation from the flame melts all the wax at the same time",
      "Heat flows by conduction and melts the wax in order along the rod",
    ],
    answerIndex: 3,
    explanation: "Conduction transfers heat along the rod, so the wax melts and the pins fall in sequence.",
  },
  {
    id: "sci-f2-c9-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why do potassium permanganate crystals move upwards in a beaker of water that is heated?",
    options: [
      "Hot water becomes less dense, rises, and carries the crystals in a convection current",
      "The crystals become less dense than water and float by themselves",
      "Conduction through the glass pushes the crystals to the side of the beaker",
      "Radiation from the burner makes the crystals lighter than air",
    ],
    answerIndex: 0,
    explanation: "Heated water expands, becomes less dense and rises, carrying the crystals in a convection current.",
  },
  {
    id: "sci-f2-c9-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does the vacuum-jar demonstration show radiation as a method of heat transfer?",
    options: [
      "Heat is felt only while air is still present, so air is required",
      "Heat can still be felt after the air is removed from the jar",
      "The jar walls conduct the heat, so removing the air changes nothing",
      "The jar stops radiation, so heat arrives only by convection of the remaining air",
    ],
    answerIndex: 1,
    explanation: "Heat is still felt in a vacuum, so the transfer does not need air.",
  },
  {
    id: "sci-f2-c9-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does sea breeze form during the day?",
    options: [
      "Cool air over the land flows towards the warmer sea",
      "The land cools faster, so land air flows towards the sea",
      "Hot air over the land rises, and cooler air from the sea moves in to replace it",
      "Air over the sea rises first, and land air moves in to replace it",
    ],
    answerIndex: 2,
    explanation: "During the day the land heats faster. Land air rises and cooler sea air moves in.",
  },
  {
    id: "sci-f2-c9-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does land breeze form at night?",
    options: [
      "Land air and sea air stop moving when there is no sunlight",
      "The land stays warmer, so sea air keeps moving inland",
      "Land air rises and cooler sea air moves in to replace it",
      "The land cools faster, sea air rises, and land air flows towards the sea",
    ],
    answerIndex: 3,
    explanation: "At night the land cools faster. Warmer sea air rises and land air flows towards the sea.",
  },
  {
    id: "sci-f2-c9-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why is mercury used in thermometers?",
    options: [
      "It conducts heat well and expands when the temperature changes",
      "It is a heat insulator, so the temperature inside stays constant",
      "It hardly expands, so the scale can be made very long",
      "It freezes at room temperature, so the column is easy to see",
    ],
    answerIndex: 0,
    explanation: "Mercury conducts heat well and expands or contracts when the temperature changes.",
  },
  {
    id: "sci-f2-c9-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "In the heat-insulator investigation, which material is a good heat insulator?",
    options: ["Aluminium foil", "Cotton and felt", "Copper metal", "An iron rod"],
    answerIndex: 1,
    explanation: "Cotton and felt slow heat loss. Metals such as aluminium, copper and iron conduct heat.",
  },
  {
    id: "sci-f2-c9-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why are oven gloves used to take food trays out of the oven?",
    options: [
      "The gloves are heat conductors, so tray heat reaches the hand quickly",
      "The gloves cool the tray before it is lifted",
      "The gloves are heat insulators, so heat flow to the hand is slowed",
      "The gloves raise the tray temperature so the food stays hot",
    ],
    answerIndex: 2,
    explanation: "Oven gloves are heat insulators that slow heat reaching the hand.",
  },
  {
    id: "sci-f2-c9-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What happens to particles in a solid when the solid is heated?",
    options: [
      "The particles vibrate more slowly and move closer together",
      "The particles vibrate faster but the distance between them does not change",
      "The particles leave their fixed positions and flow like a liquid",
      "The particles vibrate faster and move farther apart, so the solid expands",
    ],
    answerIndex: 3,
    explanation: "Heating makes solid particles vibrate faster and farther apart, so the solid expands.",
  },
  {
    id: "sci-f2-c9-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question:
      "A metal rod just taken from a flame cannot be fitted into a gauge, but it fits again after it is cooled with water. What is a suitable explanation of this observation?",
    options: [
      "The rod's particles vibrate farther apart when hot, so the rod expands; cooling brings the particles closer and the rod contracts",
      "The rod's particles vibrate faster when hot, but the rod contracts because metal conducts heat",
      "The gauge expands more than the rod, so the hot rod does not fit",
      "Cooling moves the rod's particles farther apart, so the cold rod becomes longer",
    ],
    answerIndex: 0,
    explanation: "A hot rod expands because its particles vibrate farther apart. When cooled, the rod contracts and fits again.",
  },
  {
    id: "sci-f2-c9-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why are railway tracks built with small gaps between their rails?",
    options: [
      "So the rails contract when hot and the gaps become larger",
      "So the rails can expand when hot without buckling",
      "So heat escapes from the rails more quickly through the gaps",
      "So expansion of the rails is stopped completely by the joints",
    ],
    answerIndex: 1,
    explanation: "The gaps give the rails room to expand when hot so the track does not buckle.",
  },
  {
    id: "sci-f2-c9-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does a bimetallic strip function in a fire alarm system?",
    options: [
      "Copper and iron expand by the same amount, so the circuit closes immediately",
      "Both metals contract when heated, so the circuit opens",
      "Copper expands faster than iron, the strip bends and closes the circuit",
      "Iron expands faster than copper, so the strip bends away from the contact",
    ],
    answerIndex: 2,
    explanation: "Copper expands faster than iron, so the strip bends, closes the circuit and sounds the alarm.",
  },
  {
    id: "sci-f2-c9-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question:
      "In the dark-and-bright surface investigation, tin J is painted white and tin K is painted black, then both are placed near a burner. What is the observation and conclusion?",
    options: [
      "Tin J is hotter; a white and shiny surface absorbs heat better",
      "Both tins reach the same temperature; surface colour does not affect absorption",
      "Tin K is cooler; a dark surface reflects heat better",
      "Tin K is hotter; dark and dull surfaces absorb heat better",
    ],
    answerIndex: 3,
    explanation: "The black tin becomes hotter because dark and dull surfaces absorb heat better.",
  },
  {
    id: "sci-f2-c9-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question:
      "In the heat-emission investigation, tin J (white) and tin K (black) are filled with hot water. Which observation shows that tin K is the better heat emitter?",
    options: [
      "The temperature of tin K falls more than the temperature of tin J",
      "The temperature of tin K falls less than the temperature of tin J",
      "The temperatures of both tins do not change",
      "The temperature of tin J falls more than the temperature of tin K",
    ],
    answerIndex: 0,
    explanation: "A larger temperature drop in the black tin shows that a dark surface emits heat better.",
  },
  {
    id: "sci-f2-c9-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why are fuel tanks usually painted in bright colours such as white or silver?",
    options: [
      "Bright colours absorb more heat and cool the fuel",
      "Bright colours absorb less heat, so less fuel evaporates",
      "Dark colours would reflect heat and reduce evaporation",
      "Paint colour does not affect absorption; the thickness of the metal does",
    ],
    answerIndex: 1,
    explanation: "Bright colours absorb less heat than dark colours, so the fuel absorbs less heat and evaporates less.",
  },
  {
    id: "sci-f2-c9-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question:
      "A student claims that heat and temperature are the same thing. Which statement corrects this claim?",
    options: [
      "The claim is correct, because both are measured in joules",
      "The claim is inaccurate, because temperature is energy and heat is the thermometer reading",
      "The claim is inaccurate; heat is energy in joules that depends on the quantity of material, whereas temperature measures particle motion",
      "The claim is inaccurate, because the amount of heat depends only on temperature, not on the quantity of material",
    ],
    answerIndex: 2,
    explanation: "Heat is energy and depends on the type, quantity and temperature of the material. Temperature measures the degree of hotness.",
  },
  {
    id: "sci-f2-c9-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How can thermal expansion loosen a tight metal bottle cap?",
    options: [
      "Soak the cap in cold water so the metal expands",
      "Leave the bottle at room temperature so the cap contracts onto the glass",
      "Soak the cap in hot water so the metal contracts and presses on the glass neck",
      "Soak the cap in hot water so the metal expands and loosens",
    ],
    answerIndex: 3,
    explanation: "Hot water expands the metal cap, so the cap becomes looser.",
  },
  {
    id: "sci-f2-c9-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "A steel bridge is built with rollers and a gap at one end. What is the purpose of this design?",
    options: [
      "To let the bridge expand when hot without being damaged",
      "To let the bridge contract when hot so that it stays tight",
      "To stop all expansion by fixing both ends",
      "To speed up heat loss so the length of the steel does not change",
    ],
    answerIndex: 0,
    explanation: "The rollers and gap give the steel room to expand when hot.",
  },
  {
    id: "sci-f2-c9-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Which feature of the Green Building Concept is related to heat and energy management?",
    options: [
      "Reducing energy efficiency so the building uses more electricity",
      "High energy efficiency, including renewable energy together with good ventilation and lighting",
      "Dark glass only, so the building absorbs more heat from the Sun",
      "Closing all ventilation so cooled air never escapes",
    ],
    answerIndex: 1,
    explanation: "Green buildings emphasise energy efficiency, renewable energy, good ventilation and good lighting.",
  },
];
