import type { QuizQuestion } from "@/data/content";

export const scienceF2C9QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c9-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is heat?",
    options: [
      "A form of energy",
      "A measure of the degree of hotness of an object",
      "An instrument used to measure temperature",
      "A type of chemical substance",
    ],
    answerIndex: 0,
    explanation: "Heat is a form of energy that flows from a hotter region to a colder region.",
  },
  {
    id: "sci-f2-c9-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is temperature?",
    options: [
      "A form of energy",
      "A measure of the degree of hotness or coldness of an object",
      "The amount of heat absorbed by a substance",
      "The rate of heat transfer",
    ],
    answerIndex: 1,
    explanation: "Temperature is a measure of the degree of hotness or coldness of an object, measured using a thermometer.",
  },
  {
    id: "sci-f2-c9-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Heat is measured in...",
    options: ["Joule (J)", "Degrees Celsius (°C)", "Kelvin (K)", "Newton (N)"],
    answerIndex: 0,
    explanation: "Heat is a form of energy measured in joule (J), unlike temperature which is measured in degrees Celsius or kelvin.",
  },
  {
    id: "sci-f2-c9-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Temperature is measured in...",
    options: ["Joule (J)", "Degrees Celsius (°C) or Kelvin (K)", "Newton (N)", "Pascal (Pa)"],
    answerIndex: 1,
    explanation: "Temperature is measured in degrees Celsius (°C) or kelvin (K), unlike heat which is measured in joule.",
  },
  {
    id: "sci-f2-c9-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is the correct direction of heat flow?",
    options: [
      "From a colder region to a hotter region",
      "From a hotter region to a colder region",
      "Heat does not flow at all",
      "Heat flows randomly without any specific direction",
    ],
    answerIndex: 1,
    explanation: "Heat flows from a hotter region to a colder region.",
  },
  {
    id: "sci-f2-c9-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is conduction?",
    options: [
      "Heat transfer through the movement of fluid",
      "Heat transfer from a hotter region to a colder region through a solid medium",
      "Heat transfer without any medium",
      "Heat transfer that only occurs through a vacuum",
    ],
    answerIndex: 1,
    explanation: "Conduction is the process of heat transfer from hotter regions to colder regions through a solid medium.",
  },
  {
    id: "sci-f2-c9-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is convection?",
    options: [
      "Heat transfer through a solid medium",
      "Heat transfer through the movement of fluid (liquid and gas)",
      "Heat transfer without any medium",
      "Heat transfer through the vibration of solid particles",
    ],
    answerIndex: 1,
    explanation: "Convection is the process of heat transfer by the movement of fluid (liquid and gas) from hotter regions to colder regions.",
  },
  {
    id: "sci-f2-c9-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is radiation?",
    options: [
      "Heat transfer through a solid medium only",
      "Heat transfer through the movement of liquid particles",
      "Heat transfer without any medium, can propagate through a vacuum",
      "Heat transfer that only occurs at night",
    ],
    answerIndex: 2,
    explanation: "Radiation is the process of transferring heat without any medium and can propagate through an empty space or vacuum.",
  },
  {
    id: "sci-f2-c9-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Materials that allow heat flow are known as...",
    options: ["Heat insulators", "Heat conductors", "Fluids", "Solids"],
    answerIndex: 1,
    explanation: "Heat conductors are materials that allow heat flow, such as metals and mercury.",
  },
  {
    id: "sci-f2-c9-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Materials that prevent heat flow are known as...",
    options: ["Heat conductors", "Heat insulators", "Radiation", "Convection current"],
    answerIndex: 1,
    explanation: "Heat insulators are materials that prevent heat flow, such as fibreglass, wood and polystyrene.",
  },
  {
    id: "sci-f2-c9-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What is thermal equilibrium?",
    options: [
      "A condition where one object is hotter than another",
      "A condition where there is no net transfer of heat energy between two objects in contact",
      "A condition where heat is transferred only through radiation",
      "A condition where an object does not absorb any heat at all",
    ],
    answerIndex: 1,
    explanation: "Thermal equilibrium is achieved when there is no net transfer of heat energy between two objects in thermal contact, and both objects have the same temperature.",
  },
  {
    id: "sci-f2-c9-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "In Activity 9.1, why do the thumbtacks fall off in sequence when a copper rod is heated at one end?",
    options: [
      "Because the copper rod expands",
      "Because heat is transferred via conduction along the rod, melting the wax holding the thumbtacks one by one",
      "Because the air around the rod becomes hot and rises",
      "Because the thumbtacks are heat insulators",
    ],
    answerIndex: 1,
    explanation: "Heat is transferred via conduction along the copper rod, melting the wax in sequence and causing the thumbtacks to fall off one by one, showing the direction of heat flow.",
  },
  {
    id: "sci-f2-c9-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why does the potassium permanganate crystal move upward in a beaker of heated water?",
    options: [
      "Because potassium permanganate is a heat insulator",
      "Because the heated water becomes less dense and rises, carrying the crystal with it (convection current)",
      "Because the crystal is lighter than air",
      "Because heat is transferred through radiation in the beaker",
    ],
    answerIndex: 1,
    explanation: "Water heated at the bottom expands, becomes less dense and rises, carrying the potassium permanganate crystal with it — this demonstrates convection current in a liquid.",
  },
  {
    id: "sci-f2-c9-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does Activity 9.1 demonstrate radiation as a method of heat transfer?",
    options: [
      "Heat can still be felt even when air is removed from a bell jar (vacuum)",
      "Smoke moves due to hot and cold air",
      "Thumbtacks fall off in sequence",
      "The potassium permanganate crystal moves upward",
    ],
    answerIndex: 0,
    explanation: "Heat can still be felt even when air is removed from a bell jar (creating a vacuum), showing that radiation does not require a medium to propagate.",
  },
  {
    id: "sci-f2-c9-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does sea breeze form during the day?",
    options: [
      "Cold air on land is drawn towards the warmer sea",
      "Warm air on land expands and rises, then cold air from the sea is drawn in to replace it",
      "The land cools faster than the sea",
      "The air above the sea becomes less dense and rises first",
    ],
    answerIndex: 1,
    explanation: "During the day, the Sun heats the land faster. Warm air on land expands, becomes less dense and rises; cold air from the sea is drawn in to replace it, resulting in sea breeze.",
  },
  {
    id: "sci-f2-c9-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does land breeze form at night?",
    options: [
      "The land cools faster than the sea, the warmer air above the sea rises and cold air from the land moves towards the sea",
      "The land remains warmer than the sea throughout the night",
      "The air on land rises and replaces the air over the sea",
      "There is no air movement at night",
    ],
    answerIndex: 0,
    explanation: "At night, the land cools faster than the sea. The warmer air above the sea becomes less dense and rises, and the colder, denser air from land moves to the sea, resulting in land breeze.",
  },
  {
    id: "sci-f2-c9-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why is mercury used in thermometers?",
    options: [
      "Because mercury is a good heat insulator",
      "Because mercury is a good heat conductor and can detect changes in temperature very quickly",
      "Because mercury does not expand when heated",
      "Because mercury is white in colour",
    ],
    answerIndex: 1,
    explanation: "Mercury in thermometers is a good heat conductor that can detect changes in temperature very quickly, and it expands and contracts noticeably.",
  },
  {
    id: "sci-f2-c9-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "In Experiment 9.1, which material is a good heat insulator?",
    options: ["Aluminium foil", "Cotton and felt", "Copper metal", "Water"],
    answerIndex: 1,
    explanation: "Experiment 9.1 shows that cotton and felt are good heat insulators (maintaining the temperature of hot water), while aluminium foil is a heat conductor.",
  },
  {
    id: "sci-f2-c9-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why are oven gloves used to take food trays out of the oven?",
    options: [
      "Because oven gloves are good heat conductors",
      "Because oven gloves are heat insulators that prevent hands from getting scalded",
      "Because oven gloves make the hands hotter",
      "Because oven gloves can expand",
    ],
    answerIndex: 1,
    explanation: "Oven gloves are heat insulators that prevent hands from getting scalded while taking hot food trays out of the oven.",
  },
  {
    id: "sci-f2-c9-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What happens to particles in a solid when the solid is heated?",
    options: [
      "Particles vibrate slower and move closer together",
      "Particles vibrate faster and move further apart, causing the solid to expand",
      "Particles stop moving completely",
      "Particles turn into liquid instantly",
    ],
    answerIndex: 1,
    explanation: "When a solid is heated, particles vibrate faster and move further apart from one another, causing the volume to increase as the solid expands.",
  },
  {
    id: "sci-f2-c9-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "A metal bar that was just heated cannot fit into a gauge, but it fits again after being cooled with water. What is the most accurate explanation?",
    options: [
      "The metal bar turns into a liquid when hot",
      "Particles in the metal bar vibrate faster and move further apart when heated, causing the bar to expand; when cooled, particles vibrate slower and the bar contracts again",
      "The gauge expands when exposed to heat from the bar",
      "The water cools the gauge, not the bar",
    ],
    answerIndex: 1,
    explanation: "Heating causes particles in the metal bar to vibrate faster and move further apart, resulting in expansion; cooling causes particles to vibrate slower and the bar contracts again, as shown in Activity 9.4.",
  },
  {
    id: "sci-f2-c9-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why are railway tracks built with small gaps between their rails?",
    options: [
      "To save on construction costs",
      "To allow the rails to expand in hot weather, so the tracks do not buckle and overlap",
      "To allow water to flow through the tracks",
      "To make it easier to install new rails",
    ],
    answerIndex: 1,
    explanation: "Expansion gaps on railway tracks allow the rails to expand in hot weather; without these gaps, the tracks would buckle and overlap.",
  },
  {
    id: "sci-f2-c9-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How does a bimetallic strip function in a fire alarm system?",
    options: [
      "Both metal strips expand at the same rate, completing the circuit instantly",
      "When exposed to heat from a fire, the copper strip expands faster than the steel strip, causing the strip to bend towards the contact point and complete the circuit",
      "The bimetallic strip contracts when exposed to heat and opens the circuit",
      "The bimetallic strip is unaffected by heat",
    ],
    answerIndex: 1,
    explanation: "A bimetallic strip is made from two types of metal that expand at different rates; when exposed to heat, the copper strip expands faster than the steel strip, causing the strip to bend towards the contact point, completing the circuit and ringing the alarm.",
  },
  {
    id: "sci-f2-c9-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "In Experiment 9.2, two milk cans — one painted white (J) and one painted black (K) — are placed close to a Bunsen burner. What is observed and what is the conclusion?",
    options: [
      "Can J shows a greater increase in temperature, showing white surfaces absorb heat better",
      "Can K shows a greater increase in temperature, showing dark and dull surfaces absorb heat better than white and shiny surfaces",
      "Both cans show the same increase in temperature",
      "Neither can shows any change in temperature",
    ],
    answerIndex: 1,
    explanation: "Can K (black) shows a greater increase in temperature, proving that dark and dull surfaces are better heat absorbers compared to white and shiny surfaces.",
  },
  {
    id: "sci-f2-c9-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "In Experiment 9.2 Part B, both cans J (white) and K (black) are filled with hot water. What observation shows that can K is a better heat radiator?",
    options: [
      "Can K shows a smaller decrease in temperature compared to can J",
      "Can K shows a greater decrease in temperature compared to can J",
      "Neither can shows any decrease in temperature",
      "Can J shows a greater decrease in temperature",
    ],
    answerIndex: 1,
    explanation: "Can K (black) shows a greater decrease in temperature compared to can J (white), showing that dark and dull surfaces radiate heat better than white and shiny surfaces.",
  },
  {
    id: "sci-f2-c9-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Why are fuel tanks usually painted in bright colours such as white or silver?",
    options: [
      "To make the tank more visually appealing",
      "Because bright colours do not absorb a lot of heat, thereby reducing the evaporation of fuel",
      "Because bright colours are good heat absorbers",
      "To add more weight to the fuel tank",
    ],
    answerIndex: 1,
    explanation: "Bright colours such as white or silver do not absorb a lot of heat compared to dark colours, thereby reducing heat absorption and fuel evaporation inside the tank.",
  },
  {
    id: "sci-f2-c9-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "A student claims that heat and temperature are the same thing because both relate to hotness. What is the most accurate correction to this claim?",
    options: [
      "The claim is correct because heat and temperature have the same unit",
      "The claim is incorrect; heat is a form of energy (measured in joule) that depends on the type and quantity of material as well as temperature, while temperature is a measure of the degree of movement of particles",
      "The claim is incorrect because temperature is a form of energy",
      "The claim is correct because both are measured using a thermometer",
    ],
    answerIndex: 1,
    explanation: "Although interrelated, heat and temperature are two different quantities: heat is energy (joule) that depends on the type and quantity of material as well as temperature, while temperature depends on the degree of movement of particles and is measured in °C or K.",
  },
  {
    id: "sci-f2-c9-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "How is the principle of heat expansion used to solve the problem of a tight bottle lid?",
    options: [
      "Submerging the bottle lid in ice so it contracts",
      "Submerging the bottle lid in hot water so the metal expands and becomes looser",
      "Hitting the bottle lid hard",
      "Leaving the bottle at room temperature for a long time",
    ],
    answerIndex: 1,
    explanation: "Submerging a metal bottle lid in hot water causes the metal to expand, thereby loosening a tight bottle lid.",
  },
  {
    id: "sci-f2-c9-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "Steel bridges are built with rollers and a gap on one end. What is the purpose of this design?",
    options: [
      "To reduce the cost of building the bridge",
      "To allow the bridge to expand in hot weather without suffering damage",
      "To allow the bridge to move during an earthquake",
      "To make it easier for vehicles to cross the bridge",
    ],
    answerIndex: 1,
    explanation: "Rollers and a gap on one end of a steel bridge allow the bridge to expand in hot weather without experiencing structural stress that could cause damage.",
  },
  {
    id: "sci-f2-c9-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "dlp",
    question: "What are the main features of the Green Building Concept related to heat and energy management?",
    options: [
      "Using only new materials and avoiding any renewable energy",
      "Having high energy efficiency through the usage of solar or renewable energy, good air circulation and lighting systems, and using recycled materials",
      "Using only dark glass windows to absorb more heat",
      "Not considering any environmental aspects at all",
    ],
    answerIndex: 1,
    explanation: "The Green Building Concept aims to reduce the effects of development on the environment through features such as high energy efficiency (solar/renewable energy), good air circulation and lighting systems, and the use of recycled materials.",
  },
];
