import type { QuizQuestion } from "@/data/content";

export const scienceF2C9QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c9-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah haba?",
    options: [
      "Satu bentuk tenaga",
      "Ukuran tahap kepanasan sesuatu objek",
      "Alat untuk mengukur suhu",
      "Sejenis bahan kimia",
    ],
    answerIndex: 0,
    explanation: "Haba ialah satu bentuk tenaga yang mengalir daripada kawasan yang lebih panas ke kawasan yang lebih sejuk.",
  },
  {
    id: "sci-f2-c9-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah suhu?",
    options: [
      "Satu bentuk tenaga",
      "Ukuran tahap kepanasan atau kesejukan sesuatu objek",
      "Jumlah haba yang diserap oleh suatu bahan",
      "Kadar pemindahan haba",
    ],
    answerIndex: 1,
    explanation: "Suhu ialah ukuran tahap kepanasan atau kesejukan sesuatu objek, diukur menggunakan termometer.",
  },
  {
    id: "sci-f2-c9-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Haba diukur dalam unit...",
    options: ["Joule (J)", "Darjah Celsius (°C)", "Kelvin (K)", "Newton (N)"],
    answerIndex: 0,
    explanation: "Haba ialah satu bentuk tenaga yang diukur dalam joule (J), berbeza dengan suhu yang diukur dalam darjah Celsius atau kelvin.",
  },
  {
    id: "sci-f2-c9-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Suhu diukur dalam unit...",
    options: ["Joule (J)", "Darjah Celsius (°C) atau Kelvin (K)", "Newton (N)", "Pascal (Pa)"],
    answerIndex: 1,
    explanation: "Suhu diukur dalam darjah Celsius (°C) atau kelvin (K), berbeza dengan haba yang diukur dalam joule.",
  },
  {
    id: "sci-f2-c9-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah arah aliran haba yang betul?",
    options: [
      "Daripada kawasan sejuk ke kawasan panas",
      "Daripada kawasan panas ke kawasan sejuk",
      "Haba tidak mengalir sama sekali",
      "Haba mengalir secara rawak tanpa arah tertentu",
    ],
    answerIndex: 1,
    explanation: "Haba mengalir daripada kawasan yang lebih panas ke kawasan yang lebih sejuk.",
  },
  {
    id: "sci-f2-c9-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah konduksi?",
    options: [
      "Pemindahan haba melalui pergerakan bendalir",
      "Pemindahan haba daripada kawasan panas ke kawasan sejuk melalui medium pepejal",
      "Pemindahan haba tanpa sebarang medium",
      "Pemindahan haba melalui ruang vakum sahaja",
    ],
    answerIndex: 1,
    explanation: "Konduksi ialah proses pemindahan haba daripada kawasan lebih panas kepada kawasan lebih sejuk melalui medium pepejal.",
  },
  {
    id: "sci-f2-c9-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah perolakan?",
    options: [
      "Pemindahan haba melalui medium pepejal",
      "Pemindahan haba melalui pergerakan bendalir (cecair dan gas)",
      "Pemindahan haba tanpa sebarang medium",
      "Pemindahan haba melalui getaran zarah pepejal",
    ],
    answerIndex: 1,
    explanation: "Perolakan ialah proses pemindahan haba melalui pergerakan bendalir (cecair dan gas) daripada kawasan panas ke kawasan sejuk.",
  },
  {
    id: "sci-f2-c9-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah sinaran?",
    options: [
      "Pemindahan haba melalui medium pepejal sahaja",
      "Pemindahan haba melalui pergerakan zarah cecair",
      "Pemindahan haba tanpa sebarang medium, boleh merebak melalui vakum",
      "Pemindahan haba yang hanya berlaku pada waktu malam",
    ],
    answerIndex: 2,
    explanation: "Sinaran ialah proses pemindahan haba tanpa sebarang medium dan boleh merebak melalui ruang kosong atau vakum.",
  },
  {
    id: "sci-f2-c9-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bahan yang membenarkan aliran haba dikenali sebagai...",
    options: ["Penebat haba", "Konduktor haba", "Bendalir", "Pepejal"],
    answerIndex: 1,
    explanation: "Konduktor haba ialah bahan yang membenarkan aliran haba, contohnya logam dan merkuri.",
  },
  {
    id: "sci-f2-c9-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bahan yang menghalang aliran haba dikenali sebagai...",
    options: ["Konduktor haba", "Penebat haba", "Sinaran", "Arus perolakan"],
    answerIndex: 1,
    explanation: "Penebat haba ialah bahan yang menghalang aliran haba, contohnya gentian kaca, kayu dan polistirena.",
  },
  {
    id: "sci-f2-c9-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah maksud keseimbangan terma?",
    options: [
      "Keadaan apabila salah satu objek lebih panas daripada objek lain",
      "Keadaan apabila tidak ada pemindahan bersih tenaga haba antara dua objek yang bersentuhan",
      "Keadaan apabila haba dipindahkan melalui sinaran sahaja",
      "Keadaan apabila suatu objek tidak menyerap haba langsung",
    ],
    answerIndex: 1,
    explanation: "Keseimbangan terma tercapai apabila tidak ada pemindahan bersih tenaga haba antara dua objek yang bersentuhan terma, dan kedua-dua objek mempunyai suhu yang sama.",
  },
  {
    id: "sci-f2-c9-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Dalam Aktiviti 9.1, mengapakah paku tekan jatuh secara berurutan apabila rod kuprum dipanaskan pada satu hujung?",
    options: [
      "Kerana rod kuprum mengembang",
      "Kerana haba dipindahkan melalui konduksi sepanjang rod, melelehkan lilin yang menampung paku tekan satu demi satu",
      "Kerana udara di sekeliling rod menjadi panas dan naik",
      "Kerana paku tekan adalah penebat haba",
    ],
    answerIndex: 1,
    explanation: "Haba dipindahkan melalui konduksi sepanjang rod kuprum, melelehkan lilin secara berurutan dan menyebabkan paku tekan jatuh satu demi satu, menunjukkan arah aliran haba.",
  },
  {
    id: "sci-f2-c9-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah hablur kalium permanganat bergerak ke atas dalam bikar air yang dipanaskan?",
    options: [
      "Kerana kalium permanganat adalah penebat haba",
      "Kerana air yang dipanaskan menjadi kurang tumpat dan naik, membawa hablur bersamanya (arus perolakan)",
      "Kerana hablur kalium permanganat lebih ringan daripada udara",
      "Kerana haba dipindahkan melalui sinaran dalam bikar",
    ],
    answerIndex: 1,
    explanation: "Air yang dipanaskan di bahagian bawah mengembang, menjadi kurang tumpat dan naik, membawa hablur kalium permanganat bersamanya — ini menunjukkan arus perolakan dalam cecair.",
  },
  {
    id: "sci-f2-c9-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah Aktiviti 9.1 menunjukkan sinaran sebagai cara pemindahan haba?",
    options: [
      "Haba dirasakan walaupun udara dikeluarkan daripada balang loceng (vakum)",
      "Asap bergerak akibat udara panas dan sejuk",
      "Paku tekan jatuh secara berurutan",
      "Hablur kalium permanganat bergerak ke atas",
    ],
    answerIndex: 0,
    explanation: "Haba masih dapat dirasakan walaupun udara dikeluarkan daripada balang loceng (mewujudkan vakum), menunjukkan sinaran tidak memerlukan medium untuk merebak.",
  },
  {
    id: "sci-f2-c9-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah bayu laut terbentuk pada waktu siang?",
    options: [
      "Udara sejuk di daratan ditarik ke laut yang lebih panas",
      "Udara panas di daratan mengembang dan naik, lalu udara sejuk daripada laut ditarik masuk menggantikannya",
      "Daratan menyejuk lebih cepat daripada laut",
      "Udara di atas laut menjadi kurang tumpat dan naik terlebih dahulu",
    ],
    answerIndex: 1,
    explanation: "Pada waktu siang, Matahari memanaskan daratan lebih cepat. Udara panas di daratan mengembang, menjadi kurang tumpat dan naik; udara sejuk daripada laut ditarik masuk menggantikannya, menghasilkan bayu laut.",
  },
  {
    id: "sci-f2-c9-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah bayu darat terbentuk pada waktu malam?",
    options: [
      "Daratan menyejuk lebih cepat berbanding laut, udara panas di atas laut naik dan udara sejuk daripada daratan bergerak ke laut",
      "Daratan kekal lebih panas berbanding laut sepanjang malam",
      "Udara di daratan naik dan menggantikan udara di laut",
      "Tidak ada pergerakan udara pada waktu malam",
    ],
    answerIndex: 0,
    explanation: "Pada waktu malam, daratan menyejuk lebih cepat berbanding laut. Udara di atas laut yang lebih panas menjadi kurang tumpat dan naik, lalu udara sejuk dan lebih tumpat daripada daratan bergerak ke laut, menghasilkan bayu darat.",
  },
  {
    id: "sci-f2-c9-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah merkuri digunakan dalam termometer?",
    options: [
      "Kerana merkuri adalah penebat haba yang baik",
      "Kerana merkuri adalah konduktor haba yang baik dan dapat mengesan perubahan suhu dengan sangat cepat",
      "Kerana merkuri tidak mengembang apabila dipanaskan",
      "Kerana merkuri berwarna putih",
    ],
    answerIndex: 1,
    explanation: "Merkuri dalam termometer adalah konduktor haba yang baik dan dapat mengesan perubahan suhu dengan sangat cepat, serta dapat mengembang dan mengecut dengan ketara.",
  },
  {
    id: "sci-f2-c9-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Dalam Eksperimen 9.1, bahan manakah yang merupakan penebat haba yang baik?",
    options: ["Kerajang aluminium", "Kapas dan felt", "Logam kuprum", "Air"],
    answerIndex: 1,
    explanation: "Eksperimen 9.1 menunjukkan kapas dan felt merupakan penebat haba yang baik (mengekalkan suhu air panas), manakala kerajang aluminium merupakan konduktor haba.",
  },
  {
    id: "sci-f2-c9-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah sarung tangan ketuhar (oven gloves) digunakan untuk mengeluarkan dulang makanan daripada ketuhar?",
    options: [
      "Kerana sarung tangan ketuhar adalah konduktor haba yang baik",
      "Kerana sarung tangan ketuhar adalah penebat haba yang dapat mencegah tangan daripada melecur",
      "Kerana sarung tangan ketuhar membuatkan tangan lebih panas",
      "Kerana sarung tangan ketuhar boleh mengembang",
    ],
    answerIndex: 1,
    explanation: "Sarung tangan ketuhar adalah penebat haba yang dapat mencegah tangan daripada melecur semasa mengeluarkan dulang makanan yang panas daripada ketuhar.",
  },
  {
    id: "sci-f2-c9-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apa yang berlaku kepada zarah pepejal apabila pepejal itu dipanaskan?",
    options: [
      "Zarah bergetar lebih perlahan dan bergerak lebih rapat",
      "Zarah bergetar lebih cepat dan bergerak lebih jauh antara satu sama lain, menyebabkan pepejal mengembang",
      "Zarah berhenti bergerak sepenuhnya",
      "Zarah bertukar menjadi cecair serta-merta",
    ],
    answerIndex: 1,
    explanation: "Apabila pepejal dipanaskan, zarah bergetar lebih cepat dan bergerak lebih jauh antara satu sama lain, menyebabkan isi padu pepejal meningkat kerana pepejal mengembang.",
  },
  {
    id: "sci-f2-c9-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Sebatang rod logam yang baru dikeluarkan daripada api tidak boleh dimasukkan ke dalam tolok (gauge), tetapi boleh dimasukkan semula selepas disejukkan dengan air. Apakah penjelasan yang sesuai bagi pemerhatian ini?",
    options: [
      "Rod logam bertukar menjadi cecair apabila panas",
      "Zarah dalam rod logam bergetar lebih cepat dan bergerak lebih jauh apabila dipanaskan, menyebabkan rod mengembang; apabila disejukkan, zarah bergetar lebih perlahan dan rod mengecut semula",
      "Tolok itu mengembang apabila terkena haba daripada rod",
      "Air menyejukkan tolok, bukan rod",
    ],
    answerIndex: 1,
    explanation: "Pemanasan menyebabkan zarah dalam rod logam bergetar lebih cepat dan bergerak lebih jauh, mengakibatkan pengembangan; penyejukan menyebabkan zarah bergetar lebih perlahan dan rod mengecut semula seperti dalam Aktiviti 9.4.",
  },
  {
    id: "sci-f2-c9-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah landasan kereta api dibina dengan jurang kecil antara relnya?",
    options: [
      "Untuk menjimatkan kos pembinaan",
      "Untuk membolehkan pengembangan rel semasa cuaca panas, supaya landasan tidak melengkung dan bertindih",
      "Untuk membolehkan air mengalir melalui landasan",
      "Untuk memudahkan pemasangan rel baharu",
    ],
    answerIndex: 1,
    explanation: "Jurang dilatasi pada landasan kereta api membolehkan rel mengembang semasa cuaca panas; tanpa jurang ini, landasan akan melengkung dan bertindih.",
  },
  {
    id: "sci-f2-c9-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah jalur dwilogam berfungsi dalam sistem penggera kebakaran?",
    options: [
      "Kedua-dua jalur logam mengembang pada kadar yang sama, melengkapkan litar serta-merta",
      "Apabila terdedah kepada haba kebakaran, jalur kuprum mengembang lebih cepat berbanding jalur keluli, menyebabkan jalur melentur ke arah titik sentuhan dan melengkapkan litar",
      "Jalur dwilogam mengecut apabila terdedah kepada haba dan membuka litar",
      "Jalur dwilogam tidak terjejas oleh haba sama sekali",
    ],
    answerIndex: 1,
    explanation: "Jalur dwilogam dibuat daripada dua jenis logam yang mengembang pada kadar berbeza; apabila terdedah kepada haba, jalur kuprum mengembang lebih cepat berbanding jalur keluli, menyebabkan jalur melentur ke arah titik sentuhan, melengkapkan litar dan membunyikan penggera.",
  },
  {
    id: "sci-f2-c9-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Dalam Eksperimen 9.2, dua tin susu — satu dicat putih (J) dan satu dicat hitam (K) — diletakkan berdekatan penunu Bunsen. Apakah yang diperhatikan dan apakah kesimpulannya?",
    options: [
      "Tin J menunjukkan peningkatan suhu lebih besar, menunjukkan permukaan putih menyerap haba lebih baik",
      "Tin K menunjukkan peningkatan suhu lebih besar, menunjukkan permukaan gelap dan kasar menyerap haba lebih baik berbanding permukaan putih dan berkilat",
      "Kedua-dua tin menunjukkan peningkatan suhu yang sama",
      "Tidak ada perubahan suhu pada kedua-dua tin",
    ],
    answerIndex: 1,
    explanation: "Tin K (hitam) menunjukkan peningkatan suhu yang lebih besar, membuktikan permukaan gelap dan kasar adalah penyerap haba yang lebih baik berbanding permukaan putih dan berkilat.",
  },
  {
    id: "sci-f2-c9-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Dalam Eksperimen 9.2 Bahagian B, kedua-dua tin J (putih) dan K (hitam) diisi air panas. Apakah pemerhatian yang menunjukkan tin K adalah pembebas haba yang lebih baik?",
    options: [
      "Tin K menunjukkan penurunan suhu yang lebih kecil berbanding tin J",
      "Tin K menunjukkan penurunan suhu yang lebih besar berbanding tin J",
      "Kedua-dua tin tidak mengalami sebarang penurunan suhu",
      "Tin J menunjukkan penurunan suhu yang lebih besar",
    ],
    answerIndex: 1,
    explanation: "Tin K (hitam) menunjukkan penurunan suhu yang lebih besar berbanding tin J (putih), menunjukkan permukaan gelap dan kasar membebaskan haba dengan lebih baik berbanding permukaan putih dan berkilat.",
  },
  {
    id: "sci-f2-c9-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Mengapakah tangki bahan api biasanya dicat dengan warna terang seperti putih atau perak?",
    options: [
      "Untuk menjadikan tangki lebih menarik dari segi rekaan",
      "Kerana warna terang tidak menyerap banyak haba, dengan itu mengurangkan penyejatan bahan api",
      "Kerana warna terang adalah penyerap haba yang baik",
      "Untuk menambah berat tangki bahan api",
    ],
    answerIndex: 1,
    explanation: "Warna terang seperti putih atau perak tidak menyerap banyak haba berbanding warna gelap, dengan itu mengurangkan penyerapan haba dan penyejatan bahan api di dalam tangki.",
  },
  {
    id: "sci-f2-c9-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Seorang murid mendakwa bahawa haba dan suhu adalah perkara yang sama kerana kedua-duanya berkaitan dengan kepanasan. Apakah pernyataan yang membetulkan dakwaan ini?",
    options: [
      "Dakwaan adalah betul kerana haba dan suhu mempunyai unit yang sama",
      "Dakwaan tidak tepat; haba ialah satu bentuk tenaga (diukur dalam joule) yang bergantung pada jenis dan kuantiti bahan serta suhu, manakala suhu adalah ukuran darjah gerakan zarah",
      "Dakwaan tidak tepat kerana suhu adalah satu bentuk tenaga",
      "Dakwaan adalah betul kerana kedua-duanya diukur menggunakan termometer",
    ],
    answerIndex: 1,
    explanation: "Walaupun saling berkait, haba dan suhu adalah dua kuantiti berbeza: haba adalah tenaga (joule) yang bergantung kepada jenis dan kuantiti bahan serta suhu, manakala suhu bergantung kepada darjah gerakan zarah dan diukur dalam °C atau K.",
  },
  {
    id: "sci-f2-c9-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Bagaimanakah konsep pengembangan haba digunakan untuk menyelesaikan masalah penutup botol yang ketat?",
    options: [
      "Merendam penutup botol dalam ais supaya ia mengecut",
      "Merendam penutup botol dalam air panas supaya logam mengembang dan menjadi lebih longgar",
      "Memukul penutup botol dengan kuat",
      "Membiarkan botol pada suhu bilik dalam tempoh yang lama",
    ],
    answerIndex: 1,
    explanation: "Merendam penutup botol logam dalam air panas menyebabkan logam mengembang, dengan itu melonggarkan penutup botol yang ketat.",
  },
  {
    id: "sci-f2-c9-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Jambatan keluli dibina dengan roda gelek (roller) dan jurang pada satu hujung. Apakah tujuan reka bentuk ini?",
    options: [
      "Untuk mengurangkan kos pembinaan jambatan",
      "Untuk membolehkan jambatan mengembang semasa cuaca panas tanpa mengalami kerosakan",
      "Untuk membolehkan jambatan bergerak semasa gempa bumi",
      "Untuk memudahkan kenderaan melintasi jambatan",
    ],
    answerIndex: 1,
    explanation: "Roda gelek dan jurang pada satu hujung jambatan keluli membolehkan jambatan mengembang semasa cuaca panas tanpa mengalami tekanan struktur yang boleh menyebabkan kerosakan.",
  },
  {
    id: "sci-f2-c9-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 9",
    lang: "bm",
    question: "Apakah ciri-ciri utama Konsep Bangunan Hijau yang berkaitan dengan pengurusan haba dan tenaga?",
    options: [
      "Menggunakan hanya bahan baharu dan mengelakkan sebarang tenaga boleh diperbaharui",
      "Mempunyai kecekapan tenaga yang tinggi melalui penggunaan tenaga solar atau tenaga boleh diperbaharui, sistem aliran udara dan pencahayaan yang baik, serta menggunakan bahan kitar semula",
      "Menggunakan tingkap kaca gelap sahaja untuk menyerap lebih banyak haba",
      "Tidak mengambil kira sebarang aspek alam sekitar",
    ],
    answerIndex: 1,
    explanation: "Konsep Bangunan Hijau bertujuan mengurangkan kesan pembangunan terhadap alam sekitar dengan ciri-ciri seperti kecekapan tenaga tinggi (tenaga solar/boleh diperbaharui), sistem aliran udara dan pencahayaan yang baik, serta penggunaan bahan kitar semula.",
  },
];
