import type { Flashcard } from "@/data/types";

export const geographyF3C2Flashcards: Flashcard[] = [
  {
    id: "geo-f3-c2-f1",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah definisi carta pai?",
    back: "Carta pai ialah persembahan data dalam bentuk bulatan yang dibahagikan kepada beberapa sektor.",
  },
  {
    id: "geo-f3-c2-f2",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah kegunaan utama carta pai?",
    back: "Untuk menunjukkan bahagian setiap komponen daripada jumlah keseluruhan dalam bentuk peratus.",
  },
  {
    id: "geo-f3-c2-f3",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Berapakah jumlah peratus bagi sebuah carta pai?",
    back: "100%.",
  },
  {
    id: "geo-f3-c2-f4",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Berapakah jumlah keseluruhan saiz sudut sebuah carta pai?",
    back: "360°.",
  },
  {
    id: "geo-f3-c2-f5",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah alat yang digunakan untuk melukis bulatan carta pai?",
    back: "Jangka lukis.",
  },
  {
    id: "geo-f3-c2-f6",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah alat yang digunakan untuk mengukur saiz sudut sektor?",
    back: "Jangka sudut.",
  },
  {
    id: "geo-f3-c2-f7",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Bagaimanakah cara mengira peratus bagi sesuatu komponen?",
    back: "(Nilai komponen ÷ jumlah keseluruhan) × 100%.",
  },
  {
    id: "geo-f3-c2-f8",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah formula untuk menentukan saiz sudut sektor?",
    back: "(Nilai komponen ÷ jumlah keseluruhan) × 360°.",
  },
  {
    id: "geo-f3-c2-f9",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Bagaimanakah sektor dalam carta pai disusun?",
    back: "Mengikut arah putaran jam bermula daripada sektor yang paling besar.",
  },
  {
    id: "geo-f3-c2-f10",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah fungsi petunjuk dalam carta pai?",
    back: "Menjelaskan warna atau corak bagi setiap sektor.",
  },
  {
    id: "geo-f3-c2-f11",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah langkah pertama semasa mentafsir carta pai?",
    back: "Mengenal pasti tajuk carta pai.",
  },
  {
    id: "geo-f3-c2-f12",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah yang dimaksudkan dengan isi tersirat semasa mentafsir carta pai?",
    back: "Faktor atau kesan yang dapat dihuraikan berdasarkan data.",
  },
  {
    id: "geo-f3-c2-f13",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Bilakah carta pai paling sesuai digunakan?",
    back: "Apabila data ingin menunjukkan bahagian daripada jumlah keseluruhan.",
  },
  {
    id: "geo-f3-c2-f14",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah yang diwakili oleh setiap sektor dalam carta pai?",
    back: "Satu komponen daripada keseluruhan data.",
  },
  {
    id: "geo-f3-c2-f15",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Mengapakah setiap sektor menggunakan warna atau corak yang berbeza?",
    back: "Untuk memudahkan setiap komponen dibezakan.",
  },
  {
    id: "geo-f3-c2-f16",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah fungsi tajuk dalam carta pai?",
    back: "Menjelaskan data yang dipersembahkan.",
  },
  {
    id: "geo-f3-c2-f17",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Bagaimanakah mengenal pasti komponen yang mempunyai nilai paling tinggi?",
    back: "Melalui sektor yang mempunyai saiz paling besar.",
  },
  {
    id: "geo-f3-c2-f18",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah yang berlaku jika jumlah saiz sudut sektor tidak bersamaan 360°?",
    back: "Carta pai menjadi tidak tepat.",
  },
  {
    id: "geo-f3-c2-f19",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Apakah kesilapan yang perlu dielakkan semasa membina carta pai?",
    back: "Kesilapan mengira peratus atau saiz sudut serta tidak menyertakan tajuk dan petunjuk.",
  },
  {
    id: "geo-f3-c2-f20",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 2",
    front: "Mengapakah carta pai memudahkan pembaca memahami data?",
    back: "Kerana perbandingan antara komponen dapat dilihat dengan jelas secara visual.",
  },
];
