import type { Flashcard } from "@/data/content";

export const scienceF2C11FlashcardsDLP: Flashcard[] = [
  // Set 1: The Universe & Galaxies
  {
    id: "sci-f2-c11-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of the universe?",
    back: "Everything that exists around us.",
  },
  {
    id: "sci-f2-c11-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "Arrange the relative size from smallest to largest: Earth, Solar System, Milky Way, Group of Galaxies, Galaxy Cluster, Universe.",
    back: "Earth < Solar System < Milky Way < Group of Galaxies < Galaxy Cluster < Universe.",
  },
  {
    id: "sci-f2-c11-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "What is meant by a 'group of galaxies' and a 'galaxy cluster' in the size hierarchy of the universe?",
    back: "A group of galaxies is several galaxies clustered together; a galaxy cluster is a larger structure encompassing many groups of galaxies, larger than the Milky Way but smaller than the universe.",
  },
  {
    id: "sci-f2-c11-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Is the Milky Way the only galaxy in the universe?",
    back: "No. The universe contains hundreds of billions of galaxies; the Milky Way is the galaxy that contains our Solar System.",
  },
  {
    id: "sci-f2-c11-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a galaxy?",
    back: "A huge system of millions to billions of stars, together with gas and dust, held together by gravity.",
  },
  {
    id: "sci-f2-c11-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the name of the galaxy that hosts our solar system?",
    back: "The Milky Way.",
  },
  {
    id: "sci-f2-c11-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "How many stars are estimated to be in the Milky Way?",
    back: "About 200 billion stars, and the Sun is one of them.",
  },
  {
    id: "sci-f2-c11-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Give an example of a spiral galaxy.",
    back: "Andromeda and the Milky Way.",
  },
  {
    id: "sci-f2-c11-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the Andromeda Galaxy?",
    back: "The nearest large spiral galaxy to the Milky Way.",
  },
  {
    id: "sci-f2-c11-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Name three types of galaxy shapes.",
    back: "Spiral galaxy, elliptical galaxy, irregular galaxy.",
  },
  {
    id: "sci-f2-c11-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Give an example of an elliptical galaxy.",
    back: "Messier 87 (M87).",
  },
  {
    id: "sci-f2-c11-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Give an example of an irregular galaxy.",
    back: "The Small Magellanic Cloud and the Large Magellanic Cloud.",
  },
  {
    id: "sci-f2-c11-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a spiral galaxy with an irregular galaxy in terms of shape.",
    back: "A spiral galaxy has a clear shape and arms (e.g. the Milky Way). An irregular galaxy has no fixed shape (e.g. Magellanic Clouds).",
  },
  {
    id: "sci-f2-c11-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Do all galaxies have a spiral shape like the Milky Way?",
    back: "No. There are also elliptical galaxies (e.g. Messier 87) and irregular galaxies (e.g. Magellanic Clouds) that are not spiral-shaped.",
  },
  {
    id: "sci-f2-c11-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "When was the Hubble Telescope launched?",
    back: "24 April 1990.",
  },
  {
    id: "sci-f2-c11-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the Hubble Space Telescope?",
    back: "A telescope orbiting the Earth that observes distant stars and galaxies clearly because it is above the blurring effect of the atmosphere.",
  },
  {
    id: "sci-f2-c11-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why is the Hubble Telescope important in astronomical research?",
    back: "It allows observation of distant and faint space objects, improving humanity's understanding of the vastness of the universe.",
  },
  {
    id: "sci-f2-c11-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "Compare the contribution of Dato' Dr. Sheikh Muszaphar Shukor with Nur Adlyka Ainul Annuar.",
    back: "Sheikh Muszaphar: the first Malaysian in space (2007). Nur Adlyka: proved the existence of a supermassive black hole (2017).",
  },
  {
    id: "sci-f2-c11-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the importance of the National Planetarium in Kuala Lumpur?",
    back: "It combines Islamic architecture with astronomy, officially opened in 1994, for education and public awareness about space.",
  },
  {
    id: "sci-f2-c11-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why is the field of astronomy important to humans?",
    back: "It increases our awareness of the beauty and vastness of God's creation of the universe.",
  },
  // Set 2: Characteristics of Stars
  {
    id: "sci-f2-c11-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is a star?",
    back: "A huge ball of hot gas that produces its own light and heat through nuclear reactions in its core.",
  },
  {
    id: "sci-f2-c11-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Name five characteristics used to classify stars.",
    back: "Colour, temperature, size, brightness and distance (from Earth).",
  },
  {
    id: "sci-f2-c11-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the colour of a star with a surface temperature less than 3,500 K?",
    back: "Red.",
  },
  {
    id: "sci-f2-c11-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the colour of a star with a surface temperature more than 25,000 K?",
    back: "Blue.",
  },
  {
    id: "sci-f2-c11-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a red star with a blue star in terms of temperature.",
    back: "Red star: lowest surface temperature (<3,500 K). Blue star: highest surface temperature (>25,000 K).",
  },
  {
    id: "sci-f2-c11-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a yellow star with a yellowish-white star in terms of temperature range.",
    back: "Yellow: 5,000–6,000 K. Yellowish-white: 6,000–7,500 K (hotter).",
  },
  {
    id: "sci-f2-c11-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Arrange the star colours from the coolest to the hottest.",
    back: "Red → Orange → Yellow → Yellowish-white → White → Bluish-white → Blue.",
  },
  {
    id: "sci-f2-c11-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "A yellowish-white star is detected. What is the most likely surface temperature range?",
    back: "6,000–7,500 K.",
  },
  {
    id: "sci-f2-c11-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What colour is the Sun as a star, and what is its surface temperature?",
    back: "A yellow star, with a surface temperature of about 5,500–6,000 K.",
  },
  {
    id: "sci-f2-c11-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Name three categories of star sizes.",
    back: "Supergiant stars (very large), giant stars (large), dwarf stars (very small).",
  },
  {
    id: "sci-f2-c11-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a supergiant star with a dwarf star.",
    back: "Supergiant: a star that is very large in size. Dwarf: a star that is very small in size.",
  },
  {
    id: "sci-f2-c11-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What factors affect the brightness of a star?",
    back: "Its size, distance and surface temperature.",
  },
  {
    id: "sci-f2-c11-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "If two stars have the same size and distance but different surface temperatures, what is the relationship between temperature and brightness?",
    back: "The star with a higher surface temperature will be brighter, because brightness is also influenced by surface temperature.",
  },
  {
    id: "sci-f2-c11-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "Star R is supergiant-sized and star S is dwarf-sized, with the same temperature and distance. Which star is brighter?",
    back: "Star R, because a larger size contributes to greater brightness when temperature and distance are equal.",
  },
  {
    id: "sci-f2-c11-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Does a star's temperature alone determine its brightness?",
    back: "No. Brightness depends on a combination of size, distance AND surface temperature, not temperature alone.",
  },
  {
    id: "sci-f2-c11-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "Why must astronomers consider distance, not just size and temperature, when assessing a star's brightness?",
    back: "Because a large, hot star may appear less bright if it is very far from Earth compared to a smaller star that is closer.",
  },
  {
    id: "sci-f2-c11-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why does the Sun appear much brighter than all other stars?",
    back: "Because it is far closer to Earth than any other star.",
  },
  {
    id: "sci-f2-c11-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the brightest star in the night sky?",
    back: "Sirius.",
  },
  {
    id: "sci-f2-c11-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why do stars appear to twinkle?",
    back: "Their light is bent by moving layers of air in Earth's atmosphere.",
  },
  {
    id: "sci-f2-c11-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is a constellation? Give an example.",
    back: "A group of stars that forms a pattern in the night sky, e.g. Ursa Major or Orion. A constellation is not a galaxy.",
  },
  // Set 3: Life Cycle of Stars
  {
    id: "sci-f2-c11-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a nebula?",
    back: "A cloud of gas and dust in space that is the birthplace of stars.",
  },
  {
    id: "sci-f2-c11-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What pulls the gas and dust in a nebula together to form a star?",
    back: "Gravitational attraction. The gas and dust clump together and become denser and hotter until nuclear reactions begin.",
  },
  {
    id: "sci-f2-c11-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "How is a star born from a nebula?",
    back: "Gravitational attraction pulls gas and dust particles into a clump that contracts and compresses into a core. When the temperature and pressure in the core become very high, a nuclear reaction converts hydrogen gas into helium, the core shines and a star is born.",
  },
  {
    id: "sci-f2-c11-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Which gas makes up most of a new star, and what is it converted into?",
    back: "Hydrogen, which is converted into helium in the core.",
  },
  {
    id: "sci-f2-c11-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is meant by a red giant in the life cycle of a star?",
    back: "The stage when a star expands and becomes very bright after its hydrogen fuel decreases.",
  },
  {
    id: "sci-f2-c11-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why does a star swell into a red giant?",
    back: "When hydrogen in the core runs low, the core contracts and heats up while the outer layers expand and cool, glowing red.",
  },
  {
    id: "sci-f2-c11-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a white dwarf?",
    back: "The remnant of a small/medium-sized star after death, small in size and dense.",
  },
  {
    id: "sci-f2-c11-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a black hole?",
    back: "A space object that is extremely dense with extremely strong gravity, formed from a large star that has died.",
  },
  {
    id: "sci-f2-c11-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why is a black hole called 'black'?",
    back: "Its gravity is so strong that not even light can escape from it.",
  },
  {
    id: "sci-f2-c11-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is a supergiant star?",
    back: "A very large, very bright star; very large stars swell into supergiants before exploding as supernovae.",
  },
  {
    id: "sci-f2-c11-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is a supernova?",
    back: "The huge explosion of a large or very large star at the end of its life.",
  },
  {
    id: "sci-f2-c11-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is a neutron star?",
    back: "The extremely dense core left behind after a large star explodes as a supernova.",
  },
  {
    id: "sci-f2-c11-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "State the three life-cycle pathways of a star.",
    back: "Medium-sized star → red giant → white dwarf. Large star → red giant → supergiant → supernova → neutron star. Very large star → red giant → supergiant → supernova → black hole.",
  },
  {
    id: "sci-f2-c11-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "What is the difference in the end result of the life cycle of a small/medium-sized star compared to a large/supergiant star?",
    back: "Small/medium-sized stars usually end as a white dwarf. Large/supergiant stars end as a neutron star or black hole.",
  },
  {
    id: "sci-f2-c11-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What are the three possible final stages of a star?",
    back: "A white dwarf, a neutron star or a black hole, depending on the size of the star.",
  },
  {
    id: "sci-f2-c11-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "Compare a red giant star with a white dwarf star in terms of their position in the life cycle.",
    back: "Red giant: a middle stage when a star expands and becomes bright. White dwarf: the final stage for a small/medium-sized star after death.",
  },
  {
    id: "sci-f2-c11-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front:
      "Why do supergiant stars tend to die as a neutron star or black hole, not a white dwarf?",
    back: "Because their very large original mass causes a stronger gravitational collapse after their nuclear fuel runs out, unlike small/medium-sized stars.",
  },
  {
    id: "sci-f2-c11-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why will the Sun not become a black hole?",
    back: "The Sun is a medium-sized star. Its pathway is red giant then white dwarf, and that pathway does not pass through a supernova. Only very large stars form black holes after a supernova explosion.",
  },
  {
    id: "sci-f2-c11-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Will all large stars become black holes after death?",
    back: "Not necessarily. Large/supergiant stars can end as a neutron star OR a black hole, depending on their original mass.",
  },
  {
    id: "sci-f2-c11-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is a nebula and what is it made of?",
    back: "A nebula is a vast cloud made up of dust and gases such as hydrogen and helium. Every star is born from a nebula.",
  },
];
