import type { Flashcard } from "@/data/content";

export const scienceF2C11FlashcardsBM: Flashcard[] = [
  // Set 1: Alam Semesta & Galaksi
  {
    id: "sci-f2-c11-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah maksud alam semesta?",
    back: "Segala sesuatu yang wujud di sekeliling kita.",
  },
  {
    id: "sci-f2-c11-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Susunkan saiz relatif daripada terkecil ke terbesar: Bumi, Sistem Suria, Bima Sakti, Sekumpulan Galaksi, Kluster Galaksi, Alam Semesta.",
    back: "Bumi < Sistem Suria < Bima Sakti < Sekumpulan Galaksi < Kluster Galaksi < Alam Semesta.",
  },
  {
    id: "sci-f2-c11-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Apakah maksud 'sekumpulan galaksi' dan 'kluster galaksi' dalam hierarki saiz alam semesta?",
    back: "Sekumpulan galaksi ialah beberapa galaksi yang berkumpul bersama; kluster galaksi ialah struktur lebih besar yang merangkumi banyak sekumpulan galaksi, lebih besar daripada Bima Sakti tetapi lebih kecil daripada alam semesta.",
  },
  {
    id: "sci-f2-c11-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Adakah Bima Sakti adalah satu-satunya galaksi dalam alam semesta?",
    back: "Tidak. Alam semesta mengandungi beratus-ratus bilion galaksi; Bima Sakti ialah galaksi yang menempatkan sistem suria kita.",
  },
  {
    id: "sci-f2-c11-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah maksud galaksi?",
    back: "Sistem yang sangat besar terdiri daripada berjuta hingga berbilion bintang bersama gas dan debu, yang diikat oleh graviti.",
  },
  {
    id: "sci-f2-c11-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah nama galaksi yang menempatkan sistem suria kita?",
    back: "Bima Sakti (Milky Way).",
  },
  {
    id: "sci-f2-c11-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Berapa banyak bintang yang dianggarkan terdapat dalam Bima Sakti?",
    back: "Kira-kira 200 bilion bintang, dan Matahari adalah salah satunya.",
  },
  {
    id: "sci-f2-c11-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Berikan contoh galaksi berpilin.",
    back: "Andromeda dan Bima Sakti.",
  },
  {
    id: "sci-f2-c11-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah Galaksi Andromeda?",
    back: "Galaksi berpilin besar yang paling hampir dengan Bima Sakti.",
  },
  {
    id: "sci-f2-c11-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Namakan tiga jenis bentuk galaksi.",
    back: "Galaksi berpilin, galaksi elips, galaksi tidak seragam.",
  },
  {
    id: "sci-f2-c11-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Berikan satu contoh galaksi elips.",
    back: "Messier 87 (M87).",
  },
  {
    id: "sci-f2-c11-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Berikan contoh galaksi tidak seragam.",
    back: "Awan Magellan Kecil dan Awan Magellan Besar.",
  },
  {
    id: "sci-f2-c11-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Bandingkan galaksi berpilin dengan galaksi tidak seragam dari segi bentuk.",
    back: "Galaksi berpilin mempunyai bentuk dan lengan jelas (contoh: Bima Sakti). Galaksi tidak seragam tidak mempunyai bentuk tetap (contoh: Awan Magellan).",
  },
  {
    id: "sci-f2-c11-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Adakah semua galaksi mempunyai bentuk berpilin seperti Bima Sakti?",
    back: "Tidak. Terdapat juga galaksi elips (contoh: Messier 87) dan galaksi tidak seragam (contoh: Awan Magellan) yang tidak berbentuk berpilin.",
  },
  {
    id: "sci-f2-c11-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Bilakah Teleskop Hubble dilancarkan?",
    back: "24 April 1990.",
  },
  {
    id: "sci-f2-c11-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah Teleskop Angkasa Hubble?",
    back: "Teleskop yang mengorbit Bumi dan memerhati bintang serta galaksi yang jauh dengan jelas kerana ia berada di atas kesan kabur atmosfera.",
  },
  {
    id: "sci-f2-c11-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Mengapakah Teleskop Hubble penting dalam kajian astronomi?",
    back: "Ia membolehkan pemerhatian objek angkasa lepas yang jauh dan halus, meningkatkan pemahaman manusia tentang keluasan alam semesta.",
  },
  {
    id: "sci-f2-c11-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Bandingkan sumbangan Dato' Dr. Sheikh Muszaphar Shukor dengan Nur Adlyka Ainul Annuar.",
    back: "Sheikh Muszaphar: orang Malaysia pertama ke angkasa lepas (2007). Nur Adlyka: membuktikan kewujudan lohong hitam supermasif (2017).",
  },
  {
    id: "sci-f2-c11-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah kepentingan Planetarium Negara di Kuala Lumpur?",
    back: "Menggabungkan seni bina Islam dengan astronomi, dibuka secara rasmi pada 1994, untuk pendidikan dan kesedaran awam tentang angkasa lepas.",
  },
  {
    id: "sci-f2-c11-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Mengapakah bidang astronomi penting kepada manusia?",
    back: "Ia meningkatkan kesedaran kita terhadap keindahan dan keluasan ciptaan Tuhan terhadap alam semesta.",
  },
  // Set 2: Ciri-ciri Bintang
  {
    id: "sci-f2-c11-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah bintang?",
    back: "Bebola gas panas yang sangat besar dan menghasilkan cahaya serta habanya sendiri melalui tindak balas nuklear dalam terasnya.",
  },
  {
    id: "sci-f2-c11-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Namakan lima ciri untuk mengklasifikasikan bintang.",
    back: "Warna, suhu, saiz, kecerahan dan jarak (daripada Bumi).",
  },
  {
    id: "sci-f2-c11-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah warna bintang dengan suhu permukaan kurang daripada 3,500 K?",
    back: "Merah.",
  },
  {
    id: "sci-f2-c11-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah warna bintang dengan suhu permukaan lebih daripada 25,000 K?",
    back: "Biru.",
  },
  {
    id: "sci-f2-c11-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Bandingkan bintang merah dengan bintang biru dari segi suhu.",
    back: "Bintang merah: suhu permukaan terendah (<3,500 K). Bintang biru: suhu permukaan tertinggi (>25,000 K).",
  },
  {
    id: "sci-f2-c11-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Bandingkan bintang berwarna kuning dengan bintang berwarna kuning-keputihan dari segi julat suhu.",
    back: "Kuning: 5,000–6,000 K. Kuning-keputihan: 6,000–7,500 K (lebih panas).",
  },
  {
    id: "sci-f2-c11-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Susun warna bintang daripada yang paling sejuk hingga yang paling panas.",
    back: "Merah → Jingga → Kuning → Kuning-keputihan → Putih → Putih-kebiruan → Biru.",
  },
  {
    id: "sci-f2-c11-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Sebuah bintang berwarna kuning-keputihan dikesan. Apakah julat suhu permukaan yang paling mungkin?",
    back: "6,000–7,500 K.",
  },
  {
    id: "sci-f2-c11-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah warna Matahari sebagai bintang, dan berapakah suhu permukaannya?",
    back: "Bintang kuning, dengan suhu permukaan kira-kira 5,500–6,000 K.",
  },
  {
    id: "sci-f2-c11-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Namakan tiga kategori saiz bintang.",
    back: "Bintang super raksasa (sangat besar), bintang raksasa (besar), bintang kerdil (sangat kecil).",
  },
  {
    id: "sci-f2-c11-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Bandingkan bintang super raksasa dengan bintang kerdil.",
    back: "Super raksasa: bintang yang sangat besar saiznya. Kerdil: bintang yang sangat kecil saiznya.",
  },
  {
    id: "sci-f2-c11-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah faktor-faktor yang mempengaruhi kecerahan sesebuah bintang?",
    back: "Saiz, jarak dan suhu permukaannya.",
  },
  {
    id: "sci-f2-c11-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Jika dua bintang mempunyai saiz dan jarak yang sama tetapi suhu permukaan berbeza, apakah hubungan suhu dengan kecerahan?",
    back: "Bintang dengan suhu permukaan lebih tinggi akan lebih cerah, kerana kecerahan turut dipengaruhi suhu permukaan.",
  },
  {
    id: "sci-f2-c11-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Bintang R bersaiz super raksasa dan bintang S bersaiz kerdil, dengan suhu dan jarak sama. Bintang manakah lebih cerah?",
    back: "Bintang R, kerana saiz yang lebih besar menyumbang kepada kecerahan yang lebih besar apabila suhu dan jarak adalah sama.",
  },
  {
    id: "sci-f2-c11-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Adakah suhu bintang sahaja menentukan kecerahannya?",
    back: "Tidak. Kecerahan bergantung kepada gabungan saiz, jarak DAN suhu permukaan, bukan suhu sahaja.",
  },
  {
    id: "sci-f2-c11-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Mengapakah ahli astronomi perlu mengambil kira jarak, bukan hanya saiz dan suhu, semasa menilai kecerahan bintang?",
    back: "Kerana bintang yang besar dan panas mungkin kelihatan kurang cerah jika ia sangat jauh daripada Bumi berbanding bintang yang lebih kecil tetapi lebih hampir.",
  },
  {
    id: "sci-f2-c11-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Mengapakah Matahari kelihatan jauh lebih cerah daripada semua bintang lain?",
    back: "Kerana ia jauh lebih hampir dengan Bumi berbanding bintang lain.",
  },
  {
    id: "sci-f2-c11-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah bintang paling cerah di langit malam?",
    back: "Sirius.",
  },
  {
    id: "sci-f2-c11-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Mengapakah bintang kelihatan berkelip-kelip?",
    back: "Cahayanya dibiaskan oleh lapisan udara yang bergerak dalam atmosfera Bumi.",
  },
  {
    id: "sci-f2-c11-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah buruj? Berikan satu contoh.",
    back: "Sekumpulan bintang yang membentuk corak di langit malam, contohnya Ursa Mayor atau Orion. Buruj bukan galaksi.",
  },
  // Set 3: Kitar Hidup Bintang
  {
    id: "sci-f2-c11-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah maksud nebula?",
    back: "Awan gas dan debu di angkasa lepas yang menjadi tempat kelahiran bintang.",
  },
  {
    id: "sci-f2-c11-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah yang menarik gas dan debu dalam nebula untuk bergabung membentuk bintang?",
    back: "Daya tarikan graviti. Gas dan debu bergumpal lalu menjadi lebih tumpat dan lebih panas sehingga tindak balas nuklear bermula.",
  },
  {
    id: "sci-f2-c11-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Bagaimanakah sebuah bintang dilahirkan daripada nebula?",
    back: "Daya tarikan graviti menarik gas dan zarah debu membentuk gumpalan yang mengecut serta termampat menjadi satu teras. Apabila suhu dan tekanan dalam teras terlalu tinggi, tindak balas nuklear menukarkan gas hidrogen kepada helium, teras menyinar dan satu bintang dilahirkan.",
  },
  {
    id: "sci-f2-c11-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Gas manakah yang membentuk sebahagian besar bintang baharu, dan gas itu ditukarkan kepada apa?",
    back: "Hidrogen, yang ditukarkan kepada helium dalam teras.",
  },
  {
    id: "sci-f2-c11-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah yang dimaksudkan dengan raksasa merah dalam kitaran hidup bintang?",
    back: "Peringkat bintang membesar dan menjadi sangat cerah selepas bahan api hidrogennya berkurangan.",
  },
  {
    id: "sci-f2-c11-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Mengapakah bintang membesar menjadi raksasa merah?",
    back: "Apabila hidrogen dalam teras berkurang, teras mengecut dan menjadi lebih panas manakala lapisan luar mengembang dan menyejuk lalu bercahaya merah.",
  },
  {
    id: "sci-f2-c11-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah maksud kerdil putih?",
    back: "Sisa bintang bersaiz kecil/sederhana selepas mati, bersaiz kecil dan padat.",
  },
  {
    id: "sci-f2-c11-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah maksud lohong hitam?",
    back: "Jasad angkasa yang amat padat dengan graviti yang sangat kuat, terbentuk daripada bintang besar yang mati.",
  },
  {
    id: "sci-f2-c11-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Mengapakah lohong hitam dipanggil 'hitam'?",
    back: "Gravitinya sangat kuat sehingga cahaya pun tidak dapat melepasinya.",
  },
  {
    id: "sci-f2-c11-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah bintang super raksasa?",
    back: "Bintang yang sangat besar dan sangat cerah; bintang yang sangat besar membesar menjadi super raksasa sebelum meletup sebagai supernova.",
  },
  {
    id: "sci-f2-c11-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah supernova?",
    back: "Letupan besar bintang besar atau sangat besar di akhir hayatnya.",
  },
  {
    id: "sci-f2-c11-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah bintang neutron?",
    back: "Teras yang amat tumpat yang tertinggal selepas bintang besar meletup sebagai supernova.",
  },
  {
    id: "sci-f2-c11-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Nyatakan tiga laluan kitar hidup bintang.",
    back: "Bintang bersaiz sederhana → raksasa merah → kerdil putih. Bintang besar → raksasa merah → super raksasa → supernova → bintang neutron. Bintang super besar → raksasa merah → super raksasa → supernova → lohong hitam.",
  },
  {
    id: "sci-f2-c11-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Apakah perbezaan hasil akhir kitaran hidup bintang bersaiz kecil/sederhana dengan bintang besar/super raksasa?",
    back: "Bintang kecil/sederhana biasanya berakhir sebagai kerdil putih. Bintang besar/super raksasa berakhir sebagai bintang neutron atau lohong hitam.",
  },
  {
    id: "sci-f2-c11-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah tiga kemungkinan peringkat akhir sebuah bintang?",
    back: "Kerdil putih, bintang neutron atau lohong hitam, bergantung pada saiz bintang itu.",
  },
  {
    id: "sci-f2-c11-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Bandingkan bintang raksasa merah dengan bintang kerdil putih dari segi kedudukan dalam kitaran hidup.",
    back: "Raksasa merah: peringkat pertengahan apabila bintang membesar dan menjadi cerah. Kerdil putih: peringkat akhir bagi bintang bersaiz kecil/sederhana selepas mati.",
  },
  {
    id: "sci-f2-c11-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front:
      "Mengapakah bintang super raksasa cenderung mati sebagai bintang neutron atau lohong hitam, bukan kerdil putih?",
    back: "Kerana jisim asalnya yang sangat besar menyebabkan runtuhan graviti yang lebih kuat selepas bahan api nuklearnya kehabisan, berbeza dengan bintang bersaiz kecil/sederhana.",
  },
  {
    id: "sci-f2-c11-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Mengapakah Matahari tidak akan menjadi lohong hitam?",
    back: "Matahari ialah bintang bersaiz sederhana. Laluannya ialah raksasa merah kemudian kerdil putih, dan laluan itu tidak melalui supernova. Hanya bintang super besar membentuk lohong hitam selepas letupan supernova.",
  },
  {
    id: "sci-f2-c11-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Adakah semua bintang besar akan menjadi lohong hitam selepas mati?",
    back: "Tidak semestinya. Bintang besar/super raksasa boleh berakhir sebagai bintang neutron ATAU lohong hitam, bergantung pada jisim asalnya.",
  },
  {
    id: "sci-f2-c11-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "bm",
    front: "Apakah nebula dan apakah kandungannya?",
    back: "Nebula ialah awan besar yang terdiri daripada debu dan gas-gas seperti hidrogen dan helium. Semua bintang dilahirkan daripada nebula.",
  },
];
