import type { Flashcard } from "@/data/content";

export const scienceF2C11FlashcardsDLP: Flashcard[] = [
  // Deck 1: Basics (Cards 1-20)
  {
    id: "sci-f2-c11-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of the universe?",
    back: "Everything that exists around us.",
  },
  {
    id: "sci-f2-c11-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a galaxy?",
    back: "A collection of bodies consisting of millions of stars together with gas and dust particles.",
  },
  {
    id: "sci-f2-c11-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the name of the galaxy that hosts our solar system?",
    back: "The Milky Way.",
  },
  {
    id: "sci-f2-c11-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "How many stars are estimated to be in the Milky Way?",
    back: "About 200 billion stars, and the Sun is one of them.",
  },
  {
    id: "sci-f2-c11-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Name three types of galaxy shapes.",
    back: "Spiral galaxy, elliptical galaxy, irregular galaxy.",
  },
  {
    id: "sci-f2-c11-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Give an example of a spiral galaxy.",
    back: "Andromeda and the Milky Way.",
  },
  {
    id: "sci-f2-c11-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Give an example of an elliptical galaxy.",
    back: "Ursa Major and Messier 87.",
  },
  {
    id: "sci-f2-c11-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Give an example of an irregular galaxy.",
    back: "The Small Magellanic Cloud and the Large Magellanic Cloud.",
  },
  {
    id: "sci-f2-c11-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "When was the Hubble Telescope launched?",
    back: "24 April 1990.",
  },
  {
    id: "sci-f2-c11-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the special capability of the Hubble Telescope?",
    back: "It is so powerful that it can see a coin from a distance of 725 km.",
  },
  {
    id: "sci-f2-c11-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a nebula?",
    back: "A cloud of gas and dust in space that is the birthplace of stars.",
  },
  {
    id: "sci-f2-c11-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a protostar?",
    back: "The early stage of star formation due to gravity compressing the nebula before nuclear reactions begin.",
  },
  {
    id: "sci-f2-c11-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Name five characteristics used to classify stars.",
    back: "Colour, temperature, size, brightness and distance (from Earth).",
  },
  {
    id: "sci-f2-c11-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the colour of a star with a surface temperature less than 3,500 K?",
    back: "Red.",
  },
  {
    id: "sci-f2-c11-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the colour of a star with a surface temperature more than 25,000 K?",
    back: "Blue.",
  },
  {
    id: "sci-f2-c11-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Name three categories of star sizes.",
    back: "Supergiant stars (very large), giant stars (large), dwarf stars (very small).",
  },
  {
    id: "sci-f2-c11-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What are the two brightest stars in the sky?",
    back: "Sirius and Rigel.",
  },
  {
    id: "sci-f2-c11-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is meant by a red giant in the life cycle of a star?",
    back: "The stage when a star expands and becomes very bright after its hydrogen fuel decreases.",
  },
  {
    id: "sci-f2-c11-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a white dwarf?",
    back: "The remnant of a small/medium-sized star after death, small in size and dense.",
  },
  {
    id: "sci-f2-c11-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the meaning of a black hole?",
    back: "A space object that is extremely dense with extremely strong gravity, formed from a large star that has died.",
  },

  // Deck 2: Understanding (Cards 21-40)
  {
    id: "sci-f2-c11-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Arrange the relative size from smallest to largest: Earth, Solar System, Milky Way, Group of Galaxies, Galaxy Cluster, Universe.",
    back: "Earth < Solar System < Milky Way < Group of Galaxies < Galaxy Cluster < Universe.",
  },
  {
    id: "sci-f2-c11-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a spiral galaxy with an irregular galaxy in terms of shape.",
    back: "A spiral galaxy has a clear shape and arms (e.g. the Milky Way). An irregular galaxy has no fixed shape (e.g. Magellanic Clouds).",
  },
  {
    id: "sci-f2-c11-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a red star with a blue star in terms of temperature.",
    back: "Red star: lowest surface temperature (<3,500 K). Blue star: highest surface temperature (>25,000 K).",
  },
  {
    id: "sci-f2-c11-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a supergiant star with a dwarf star.",
    back: "Supergiant: a star that is very large in size. Dwarf: a star that is very small in size.",
  },
  {
    id: "sci-f2-c11-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What factors affect the brightness of a star?",
    back: "Its size, distance and surface temperature.",
  },
  {
    id: "sci-f2-c11-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Arrange the stages of a star's life cycle briefly.",
    back: "Nebula → Protostar → Red giant → White dwarf / Neutron star / Black hole (depending on original size).",
  },
  {
    id: "sci-f2-c11-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the difference in the end result of the life cycle of a small/medium-sized star compared to a large/supergiant star?",
    back: "Small/medium-sized stars usually end as a white dwarf. Large/supergiant stars end as a neutron star or black hole.",
  },
  {
    id: "sci-f2-c11-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a yellow star with a yellowish-white star in terms of temperature range.",
    back: "Yellow: 5,000–6,000 K. Yellowish-white: 6,000–7,500 K (hotter).",
  },
  {
    id: "sci-f2-c11-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare the star classification table by colour from coolest to hottest.",
    back: "Red → Orange → Yellow → Yellowish-white → White → Bluish-white → Blue.",
  },
  {
    id: "sci-f2-c11-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why is the Hubble Telescope important in astronomical research?",
    back: "It allows observation of distant and faint space objects, improving humanity's understanding of the vastness of the universe.",
  },
  {
    id: "sci-f2-c11-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why is the Earth described as 'smaller than a dust particle' compared to the universe?",
    back: "Because the scale of the universe is enormous, encompassing structures such as the Milky Way, groups of galaxies and galaxy clusters that are far larger than Earth.",
  },
  {
    id: "sci-f2-c11-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare the contribution of Dato' Dr. Sheikh Muszaphar Shukor with Nur Adlyka Ainul Annuar.",
    back: "Sheikh Muszaphar: the first Malaysian in space (2007). Nur Adlyka: proved the existence of a supermassive black hole (2017).",
  },
  {
    id: "sci-f2-c11-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is the importance of the National Planetarium in Kuala Lumpur?",
    back: "It combines Islamic architecture with astronomy, officially opened in 1994, for education and public awareness about space.",
  },
  {
    id: "sci-f2-c11-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "How does the nebular hypothesis explain the death of stars?",
    back: "A star ends as a white dwarf, neutron star, or black hole, depending on the original size of the star.",
  },
  {
    id: "sci-f2-c11-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a nebula with a protostar.",
    back: "Nebula: a cloud of gas and dust before gravity begins acting. Protostar: the early stage after the nebula collapses due to gravity, before nuclear reactions begin.",
  },
  {
    id: "sci-f2-c11-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "If two stars have the same size and distance but different surface temperatures, what is the relationship between temperature and brightness?",
    back: "The star with a higher surface temperature will be brighter, because brightness is also influenced by surface temperature.",
  },
  {
    id: "sci-f2-c11-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare an elliptical galaxy with a spiral galaxy in terms of examples.",
    back: "Elliptical galaxy: Ursa Major and Messier 87. Spiral galaxy: Andromeda and the Milky Way.",
  },
  {
    id: "sci-f2-c11-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "What is meant by a 'group of galaxies' and a 'galaxy cluster' in the size hierarchy of the universe?",
    back: "A group of galaxies is several galaxies clustered together; a galaxy cluster is a larger structure encompassing many groups of galaxies, larger than the Milky Way but smaller than the universe.",
  },
  {
    id: "sci-f2-c11-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Why is the field of astronomy important to humans?",
    back: "It increases our awareness of the beauty and vastness of God's creation of the universe.",
  },
  {
    id: "sci-f2-c11-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Compare a red giant star with a white dwarf star in terms of their position in the life cycle.",
    back: "Red giant: a middle stage when a star expands and becomes bright. White dwarf: the final stage for a small/medium-sized star after death.",
  },

  // Deck 3: Exam (Cards 41-60)
  {
    id: "sci-f2-c11-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] Two stars P and Q have the same size and distance but star P has a higher surface temperature. Which star is brighter?",
    back: "Star P, because a higher surface temperature contributes to greater brightness when size and distance are equal.",
  },
  {
    id: "sci-f2-c11-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] Why do supergiant stars tend to die as a neutron star or black hole, not a white dwarf?",
    back: "Because their very large original mass causes a stronger gravitational collapse after their nuclear fuel runs out, unlike small/medium-sized stars.",
  },
  {
    id: "sci-f2-c11-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] A yellowish-white star is detected. What is the most likely surface temperature range?",
    back: "6,000–7,500 K, according to the star classification table based on colour and temperature.",
  },
  {
    id: "sci-f2-c11-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] Star R is supergiant-sized and star S is dwarf-sized, with the same temperature and distance. Which star is brighter?",
    back: "Star R, because a larger size contributes to greater brightness when temperature and distance are equal.",
  },
  {
    id: "sci-f2-c11-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Common Mistake] Do all galaxies have a spiral shape like the Milky Way?",
    back: "No. There are also elliptical galaxies (e.g. Messier 87) and irregular galaxies (e.g. Magellanic Clouds) that are not spiral-shaped.",
  },
  {
    id: "sci-f2-c11-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Common Mistake] Does a star's temperature alone determine its brightness?",
    back: "No. Brightness depends on a combination of size, distance AND surface temperature, not temperature alone.",
  },
  {
    id: "sci-f2-c11-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Exam Tip] How do you answer 'arrange according to relative size' for full marks?",
    back: "State the full and accurate sequence: Earth < Solar System < Milky Way < Group of Galaxies < Galaxy Cluster < Universe.",
  },
  {
    id: "sci-f2-c11-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Important Fact] What evidence of the Hubble Telescope's power is often mentioned in exams?",
    back: "It is so powerful that it can see a coin from a distance of 725 km.",
  },
  {
    id: "sci-f2-c11-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] Arrange correctly: Red giant, Nebula, Protostar, White dwarf/neutron star/black hole.",
    back: "Nebula → Protostar → Red giant → White dwarf/neutron star/black hole.",
  },
  {
    id: "sci-f2-c11-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Important Fact] When and by whom were Malaysia's important astronomy achievements recorded?",
    back: "10 October 2007 — Dato' Dr. Sheikh Muszaphar Shukor (first Malaysian in space); early 2017 — Nur Adlyka Ainul Annuar (supermassive black hole).",
  },
  {
    id: "sci-f2-c11-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] Why is Earth scientifically 'smaller than a dust particle' compared to the universe?",
    back: "Because the size hierarchy shows there are many levels of structure (Solar System, Milky Way, groups of galaxies, galaxy clusters) far larger than Earth before reaching the scale of the universe.",
  },
  {
    id: "sci-f2-c11-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Common Mistake] Is the Milky Way the only galaxy in the universe?",
    back: "No. The universe contains millions of galaxies; the Milky Way is just the galaxy that hosts our solar system.",
  },
  {
    id: "sci-f2-c11-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Exam Tip] How do you answer 'state two brightest stars in the sky'?",
    back: "Sirius and Rigel — remember both names as concrete examples in your answer.",
  },
  {
    id: "sci-f2-c11-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] What is the main structural difference between a spiral galaxy and an irregular galaxy?",
    back: "A spiral galaxy has a clear shape and structured arms; an irregular galaxy has no fixed shape or structure.",
  },
  {
    id: "sci-f2-c11-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Important Fact] What architecture is combined in the design of the National Planetarium?",
    back: "Islamic architecture combined with astronomy.",
  },
  {
    id: "sci-f2-c11-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] Why must astronomers consider distance, not just size and temperature, when assessing a star's brightness?",
    back: "Because a large, hot star may appear less bright if it is very far from Earth compared to a smaller star that is closer.",
  },
  {
    id: "sci-f2-c11-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Common Mistake] Will all large stars become black holes after death?",
    back: "Not necessarily. Large/supergiant stars can end as a neutron star OR a black hole, depending on their original mass.",
  },
  {
    id: "sci-f2-c11-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[Exam Tip] How do you answer questions on the star colour-temperature classification table accurately?",
    back: "Memorise the sequence: Red (<3,500 K) → Orange → Yellow → Yellowish-white → White → Bluish-white → Blue (>25,000 K), from cool to hot.",
  },
  {
    id: "sci-f2-c11-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "[KBAT] How do the achievements of Sheikh Muszaphar and Nur Adlyka show Malaysia's progress in astronomy at the international level?",
    back: "Both achievements prove that Malaysians can contribute directly to space exploration and global astronomical discoveries, not merely act as observers.",
  },
  {
    id: "sci-f2-c11-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 11",
    lang: "dlp",
    front: "Summarise the subtopic Stars and Galaxies in the Universe in one sentence.",
    back: "The universe contains millions of galaxies including the Milky Way; stars form from nebulae and end as white dwarfs, neutron stars, or black holes depending on their size, and are classified by colour, temperature, size, brightness and distance.",
  },
];
