import type { QuizQuestion } from "@/data/content";

export const scienceF2C11QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c11-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is the meaning of the universe?",
    options: [
      "Every existing thing around us",
      "Only our solar system",
      "Only the Milky Way galaxy",
      "A group of stars visible to the naked eye",
    ],
    answerIndex: 0,
    explanation: "The universe consists of every existing thing around us.",
  },
  {
    id: "sci-f2-c11-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is the name of the galaxy that houses our solar system?",
    options: ["Andromeda", "The Milky Way", "Messier 87", "Large Magellanic Cloud"],
    answerIndex: 1,
    explanation: "Our solar system is located at the edge of one of the spiral arms of the Milky Way galaxy.",
  },
  {
    id: "sci-f2-c11-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "The Milky Way is estimated to consist of approximately how many billion stars?",
    options: ["20 billion", "100 billion", "200 billion", "500 billion"],
    answerIndex: 2,
    explanation: "The Milky Way consists of approximately 200 billion stars, and the Sun is one of them.",
  },
  {
    id: "sci-f2-c11-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is a galaxy?",
    options: [
      "A set of bodies consisting of millions of stars with gas and dust particles",
      "A single, very large star",
      "A group of planets orbiting the Sun",
      "A black hole found in outer space",
    ],
    answerIndex: 0,
    explanation: "A galaxy is a set of bodies consisting of millions of stars with gas and dust particles.",
  },
  {
    id: "sci-f2-c11-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What type of galaxy are Andromeda and the Milky Way?",
    options: ["Elliptical galaxy", "Spiral galaxy", "Irregular galaxy", "Dwarf galaxy"],
    answerIndex: 1,
    explanation: "Andromeda and the Milky Way are examples of spiral galaxies.",
  },
  {
    id: "sci-f2-c11-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "Ursa Major and Messier 87 are examples of which type of galaxy?",
    options: ["Spiral galaxy", "Elliptical galaxy", "Irregular galaxy", "Barred spiral galaxy"],
    answerIndex: 1,
    explanation: "Ursa Major and Messier 87 are examples of elliptical galaxies.",
  },
  {
    id: "sci-f2-c11-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "The Small Magellanic Cloud and Large Magellanic Cloud are examples of which type of galaxy?",
    options: ["Spiral galaxy", "Elliptical galaxy", "Irregular galaxy", "Ring galaxy"],
    answerIndex: 2,
    explanation: "The Small Magellanic Cloud and Large Magellanic Cloud are examples of irregular galaxies.",
  },
  {
    id: "sci-f2-c11-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "When was the Hubble Space Telescope launched?",
    options: ["24th April 1990", "10th October 2007", "22nd May 1994", "16th September 2017"],
    answerIndex: 0,
    explanation: "The Hubble Space Telescope was launched on 24th April 1990.",
  },
  {
    id: "sci-f2-c11-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is a nebula?",
    options: [
      "A very large star",
      "A cloud of gas and dust in outer space where stars are born",
      "A type of irregular galaxy",
      "The remains of a star that has died",
    ],
    answerIndex: 1,
    explanation: "A nebula is a cloud of gas and dust in outer space that becomes the birthplace of stars.",
  },
  {
    id: "sci-f2-c11-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "Who was the first Malaysian to venture into outer space?",
    options: [
      "Nur Adlyka Ainul Annuar",
      "Dato' Dr. Sheikh Muszaphar Shukor",
      "Tunku Abdul Rahman",
      "Mahathir Mohamad",
    ],
    answerIndex: 1,
    explanation: "Dato' Dr. Sheikh Muszaphar Shukor was the first Malaysian to venture into outer space, on 10th October 2007.",
  },
  {
    id: "sci-f2-c11-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "Arrange the following in order of relative size, from smallest to largest.",
    options: [
      "Earth < Solar System < The Milky Way < A group of galaxies < A cluster of galaxies < Universe",
      "Universe < Earth < Solar System < The Milky Way",
      "The Milky Way < Earth < Solar System < Universe",
      "Solar System < Earth < A cluster of galaxies < The Milky Way",
    ],
    answerIndex: 0,
    explanation: "The correct order of relative size is: Earth < Solar System < The Milky Way < A group of galaxies < A cluster of galaxies < Universe.",
  },
  {
    id: "sci-f2-c11-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What are the five characteristics used to classify stars?",
    options: [
      "Colour, temperature, size, brightness, distance from Earth",
      "Weight, volume, shape, speed, density",
      "Name, age, group, location, gas content",
      "Sun's size, Earth-Moon distance, speed of light, gravity, mass",
    ],
    answerIndex: 0,
    explanation: "Stars are classified based on colour, temperature, size, brightness and distance from Earth.",
  },
  {
    id: "sci-f2-c11-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "A blue star has a surface temperature of approximately how many Kelvin?",
    options: ["Less than 3,500 K", "5,000–6,000 K", "11,000–25,000 K", "More than 25,000 K"],
    answerIndex: 3,
    explanation: "A blue star has a surface temperature of more than 25,000 K, the highest in the classification table.",
  },
  {
    id: "sci-f2-c11-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "A red star has a surface temperature of approximately how many Kelvin?",
    options: ["Less than 3,500 K", "5,000–6,000 K", "7,500–11,000 K", "More than 25,000 K"],
    answerIndex: 0,
    explanation: "A red star has a surface temperature of less than 3,500 K, the lowest in the classification table.",
  },
  {
    id: "sci-f2-c11-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is the term for a star that is much bigger than other stars?",
    options: ["Dwarf star", "Giant star", "Supergiant star", "Neutron star"],
    answerIndex: 2,
    explanation: "Really big stars are called supergiant stars, big stars are called giant stars, and really small ones are called dwarf stars.",
  },
  {
    id: "sci-f2-c11-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What are the two brightest stars visible in the sky?",
    options: ["The Sun and Moon", "Sirius and Rigel", "Andromeda and The Milky Way", "Mars and Jupiter"],
    answerIndex: 1,
    explanation: "The brightest stars in the sky are Sirius and Rigel.",
  },
  {
    id: "sci-f2-c11-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What does the brightness of a star depend on?",
    options: [
      "Its size, distance and surface temperature",
      "Its colour scheme alone",
      "The number of planets orbiting it",
      "Its distance from the Moon only",
    ],
    answerIndex: 0,
    explanation: "The brightness of a star depends on its size, distance and surface temperature.",
  },
  {
    id: "sci-f2-c11-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is a protostar in the life cycle of a star?",
    options: [
      "A star that has already died",
      "An early stage of star formation caused by the gravitational collapse of a nebula before nuclear reactions begin",
      "Another name for a black hole",
      "A very bright star such as Sirius",
    ],
    answerIndex: 1,
    explanation: "A protostar is an early stage in a star's life cycle when a nebula collapses due to gravity, before nuclear reactions begin at the core.",
  },
  {
    id: "sci-f2-c11-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What does the Nebular Hypothesis explain about the life cycle of a star?",
    options: [
      "The idea that all stars last forever",
      "The idea that stars form from a nebula and end as a white dwarf, neutron star or black hole",
      "The idea that galaxies contain no stars",
      "The idea that the Earth is the centre of the universe",
    ],
    answerIndex: 1,
    explanation: "The Nebular Hypothesis explains that stars form from nebulae through gravitational collapse and nuclear reaction, and eventually die as a white dwarf, neutron star, or black hole, depending on their original size.",
  },
  {
    id: "sci-f2-c11-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What was Nur Adlyka Ainul Annuar's contribution to astronomy?",
    options: [
      "She was the first Malaysian to venture into outer space",
      "She proved the existence of a supermassive black hole in early 2017",
      "She designed the Hubble Space Telescope",
      "She built the National Planetarium",
    ],
    answerIndex: 1,
    explanation: "Nur Adlyka Ainul Annuar proved the existence of a supermassive black hole in early 2017.",
  },
  {
    id: "sci-f2-c11-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "Two stars, P and Q, have the same size and distance from Earth, but star P has a higher surface temperature than star Q. What can be concluded about the brightness of the two stars?",
    options: [
      "Star Q is brighter because lower temperature produces more light",
      "Star P is brighter because a higher surface temperature contributes to greater brightness",
      "Both stars are equally bright since size and distance are the same",
      "Brightness is unrelated to surface temperature",
    ],
    answerIndex: 1,
    explanation: "Since brightness depends on size, distance, and surface temperature, and size and distance are equal, the star with the higher surface temperature (Star P) will be brighter.",
  },
  {
    id: "sci-f2-c11-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "If a very large (supergiant) star reaches the end of its life cycle, the most likely final outcome is...",
    options: [
      "A white dwarf only",
      "A neutron star or black hole, depending on the star's original mass",
      "A nebula that remains unchanged forever",
      "A new protostar automatically forms",
    ],
    answerIndex: 1,
    explanation: "According to the Nebular Hypothesis, large/supergiant stars usually end as a neutron star or black hole depending on their original mass, unlike smaller stars such as the Sun which typically end as a white dwarf.",
  },
  {
    id: "sci-f2-c11-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "Why is the Earth's size compared to the universe described as being like a 'speck of dust'?",
    options: [
      "Because the Earth is actually made of space dust",
      "Because the scale of the universe is so vast that the Earth becomes insignificant compared to structures such as the Milky Way, groups of galaxies and clusters of galaxies",
      "Because the Earth is located outside the Milky Way",
      "Because the Earth is the smallest planet in the solar system",
    ],
    answerIndex: 1,
    explanation: "The size order Earth < Solar System < The Milky Way < A group of galaxies < A cluster of galaxies < Universe shows how vast the universe's scale is, making the Earth 'smaller than a speck of dust' in comparison.",
  },
  {
    id: "sci-f2-c11-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "An astronomer detects a star that is yellowish-white in colour. Based on the star classification table, what is the most likely surface temperature range of this star?",
    options: ["Less than 3,500 K", "6,000–7,500 K", "11,000–25,000 K", "More than 25,000 K"],
    answerIndex: 1,
    explanation: "According to the classification table, a yellowish-white star has a surface temperature in the range of 6,000–7,500 K.",
  },
  {
    id: "sci-f2-c11-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "How has technology such as the Hubble Space Telescope changed human understanding of the universe?",
    options: [
      "It allows humans to build new galaxies",
      "It enables the observation of extremely distant and fine details in outer space, increasing awareness of the vastness and beauty of the universe",
      "It is only used to predict weather on Earth",
      "It completely replaces the need for astronomical study",
    ],
    answerIndex: 1,
    explanation: "The extremely powerful Hubble Space Telescope (able to see a coin from 725 km away) allows the study of distant objects in space, raising human awareness of the beauty and vastness of the universe.",
  },
  {
    id: "sci-f2-c11-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is the main structural difference between a spiral galaxy like the Milky Way and an irregular galaxy like the Magellanic Clouds?",
    options: [
      "Spiral galaxies have a clear shape with arms, whereas irregular galaxies have no fixed shape",
      "Spiral galaxies have no stars, while irregular galaxies are full of stars",
      "Spiral galaxies are only found outside the Milky Way, irregular galaxies are found inside the Milky Way",
      "Both have exactly the same shape and structure",
    ],
    answerIndex: 0,
    explanation: "Spiral galaxies (such as the Milky Way and Andromeda) have a clear spiral shape with arms, unlike irregular galaxies (such as the Magellanic Clouds) which have no fixed shape or structure.",
  },
  {
    id: "sci-f2-c11-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "If two stars have the same surface temperature and the same distance from Earth, but star R is supergiant-sized and star S is dwarf-sized, which star is expected to be brighter, and why?",
    options: [
      "Star S, because small stars are brighter",
      "Star R, because a larger size contributes to greater brightness when temperature and distance are equal",
      "Both stars are equally bright because size has no effect on brightness",
      "Cannot be determined without knowing the star's colour",
    ],
    answerIndex: 1,
    explanation: "Since brightness is influenced by size, distance and temperature, and distance and temperature are equal for both stars, the larger star (supergiant, Star R) will produce more light and appear brighter.",
  },
  {
    id: "sci-f2-c11-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "Why are the achievements of Dato' Dr. Sheikh Muszaphar Shukor and Nur Adlyka Ainul Annuar considered important in the context of Malaysian astronomy?",
    options: [
      "Because they are the only people who have ever studied the universe in the world",
      "Because their achievements show Malaysia's contribution and progress in space science and astronomy at an international level",
      "Because they built the Milky Way",
      "Because they invented the Hubble Space Telescope",
    ],
    answerIndex: 1,
    explanation: "The achievements of Dato' Dr. Sheikh Muszaphar Shukor (first Malaysian in outer space) and Nur Adlyka Ainul Annuar (proved the existence of a supermassive black hole) reflect Malaysia's contribution and progress in astronomy and space science at an international level.",
  },
  {
    id: "sci-f2-c11-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "Based on the life cycle of a star, arrange the following stages in the correct order: (i) Red giant, (ii) Nebula, (iii) Protostar, (iv) White dwarf/neutron star/black hole.",
    options: [
      "(ii) → (iii) → (i) → (iv)",
      "(i) → (ii) → (iii) → (iv)",
      "(iv) → (i) → (ii) → (iii)",
      "(iii) → (ii) → (iv) → (i)",
    ],
    answerIndex: 0,
    explanation: "The correct order of a star's life cycle is: Nebula → Protostar → Red giant → White dwarf/neutron star/black hole (depending on the star's original size).",
  },
  {
    id: "sci-f2-c11-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "dlp",
    question: "What is the significance of the National Planetarium in Kuala Lumpur in the context of astronomy education in Malaysia?",
    options: [
      "It only functions as a historical building unrelated to astronomy",
      "It combines Islamic architecture with astronomy and helps expose the public to knowledge about outer space",
      "It is the only place in the world to view stars",
      "It is used specifically to launch satellites",
    ],
    answerIndex: 1,
    explanation: "The National Planetarium, officially opened in 1994, combines Islamic architecture with astronomy, making it a centre for public education and awareness about the universe and stars.",
  },
];
