import type { QuizQuestion } from "@/data/content";

export const scienceF2C11QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c11-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah maksud alam semesta?",
    options: [
      "Segala sesuatu yang wujud di sekeliling kita",
      "Hanya sistem suria kita sahaja",
      "Hanya galaksi Bima Sakti sahaja",
      "Kumpulan bintang yang dapat dilihat dengan mata kasar",
    ],
    answerIndex: 0,
    explanation: "Alam semesta terdiri daripada segala sesuatu yang wujud di sekeliling kita.",
  },
  {
    id: "sci-f2-c11-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah nama galaksi yang menempatkan sistem suria kita?",
    options: ["Andromeda", "Bima Sakti", "Messier 87", "Awan Magellan Besar"],
    answerIndex: 1,
    explanation: "Sistem suria kita terletak di tepi salah satu lengan pilin galaksi Bima Sakti (Milky Way).",
  },
  {
    id: "sci-f2-c11-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Bima Sakti dianggarkan terdiri daripada kira-kira berapa bilion bintang?",
    options: ["20 bilion", "100 bilion", "200 bilion", "500 bilion"],
    answerIndex: 2,
    explanation: "Bima Sakti terdiri daripada kira-kira 200 bilion bintang, dan Matahari adalah salah satunya.",
  },
  {
    id: "sci-f2-c11-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah maksud galaksi?",
    options: [
      "Sekumpulan jasad yang terdiri daripada berjuta-juta bintang bersama gas dan zarah debu",
      "Satu bintang tunggal yang sangat besar",
      "Kumpulan planet yang mengelilingi Matahari",
      "Lohong hitam yang terdapat di angkasa lepas",
    ],
    answerIndex: 0,
    explanation: "Galaksi ialah sekumpulan jasad yang terdiri daripada berjuta-juta bintang bersama gas dan zarah debu.",
  },
  {
    id: "sci-f2-c11-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah jenis galaksi bagi Andromeda dan Bima Sakti?",
    options: ["Galaksi elips", "Galaksi pilin", "Galaksi tidak sekata", "Galaksi kerdil"],
    answerIndex: 1,
    explanation: "Andromeda dan Bima Sakti ialah contoh galaksi pilin (spiral).",
  },
  {
    id: "sci-f2-c11-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Ursa Major dan Messier 87 adalah contoh galaksi jenis apa?",
    options: ["Galaksi pilin", "Galaksi elips", "Galaksi tidak sekata", "Galaksi pilin terhalang"],
    answerIndex: 1,
    explanation: "Ursa Major dan Messier 87 ialah contoh galaksi elips.",
  },
  {
    id: "sci-f2-c11-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Awan Magellan Kecil dan Awan Magellan Besar ialah contoh galaksi jenis apa?",
    options: ["Galaksi pilin", "Galaksi elips", "Galaksi tidak sekata", "Galaksi cincin"],
    answerIndex: 2,
    explanation: "Awan Magellan Kecil dan Awan Magellan Besar ialah contoh galaksi tidak sekata (irregular).",
  },
  {
    id: "sci-f2-c11-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Bilakah Teleskop Hubble dilancarkan?",
    options: ["24 April 1990", "10 Oktober 2007", "22 Mei 1994", "16 September 2017"],
    answerIndex: 0,
    explanation: "Teleskop Hubble dilancarkan pada 24 April 1990.",
  },
  {
    id: "sci-f2-c11-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah maksud nebula?",
    options: [
      "Bintang yang sangat besar",
      "Kawan awan gas dan debu di angkasa lepas tempat bintang dilahirkan",
      "Jenis galaksi tidak sekata",
      "Sisa bintang yang telah mati",
    ],
    answerIndex: 1,
    explanation: "Nebula ialah awan gas dan debu di angkasa lepas yang menjadi tempat kelahiran bintang.",
  },
  {
    id: "sci-f2-c11-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Siapakah orang Malaysia pertama yang ke angkasa lepas?",
    options: [
      "Nur Adlyka Ainul Annuar",
      "Dato' Dr. Sheikh Muszaphar Shukor",
      "Tunku Abdul Rahman",
      "Mahathir Mohamad",
    ],
    answerIndex: 1,
    explanation: "Dato' Dr. Sheikh Muszaphar Shukor merupakan orang Malaysia pertama yang ke angkasa lepas pada 10 Oktober 2007.",
  },
  {
    id: "sci-f2-c11-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Susun mengikut urutan saiz relatif daripada terkecil kepada terbesar.",
    options: [
      "Bumi < Sistem Suria < Bima Sakti < Sekumpulan Galaksi < Kluster Galaksi < Alam Semesta",
      "Alam Semesta < Bumi < Sistem Suria < Bima Sakti",
      "Bima Sakti < Bumi < Sistem Suria < Alam Semesta",
      "Sistem Suria < Bumi < Kluster Galaksi < Bima Sakti",
    ],
    answerIndex: 0,
    explanation: "Urutan saiz relatif yang betul: Bumi < Sistem Suria < Bima Sakti < Sekumpulan Galaksi < Kluster Galaksi < Alam Semesta.",
  },
  {
    id: "sci-f2-c11-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah lima ciri yang digunakan untuk mengklasifikasikan bintang?",
    options: [
      "Warna, suhu, saiz, kecerahan, jarak daripada Bumi",
      "Berat, isi padu, bentuk, kelajuan, kepadatan",
      "Nama, usia, kumpulan, lokasi, kandungan gas",
      "Saiz Matahari, jarak Bumi-Bulan, kelajuan cahaya, graviti, jisim",
    ],
    answerIndex: 0,
    explanation: "Bintang diklasifikasikan berdasarkan warna, suhu, saiz, kecerahan dan jarak daripada Bumi.",
  },
  {
    id: "sci-f2-c11-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Bintang berwarna biru mempunyai suhu permukaan kira-kira berapa Kelvin?",
    options: ["Kurang daripada 3,500 K", "5,000–6,000 K", "11,000–25,000 K", "Lebih daripada 25,000 K"],
    answerIndex: 3,
    explanation: "Bintang berwarna biru mempunyai suhu permukaan lebih daripada 25,000 K, iaitu suhu tertinggi dalam jadual klasifikasi.",
  },
  {
    id: "sci-f2-c11-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Bintang berwarna merah mempunyai suhu permukaan kira-kira berapa Kelvin?",
    options: ["Kurang daripada 3,500 K", "5,000–6,000 K", "7,500–11,000 K", "Lebih daripada 25,000 K"],
    answerIndex: 0,
    explanation: "Bintang berwarna merah mempunyai suhu permukaan kurang daripada 3,500 K, iaitu suhu terendah dalam jadual klasifikasi.",
  },
  {
    id: "sci-f2-c11-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah nama bagi bintang yang sangat besar berbanding bintang lain?",
    options: ["Bintang kerdil", "Bintang gergasi", "Bintang supergergasi", "Bintang neutron"],
    answerIndex: 2,
    explanation: "Bintang yang sangat besar dipanggil bintang supergergasi, bintang besar dipanggil bintang gergasi, dan bintang yang sangat kecil dipanggil bintang kerdil.",
  },
  {
    id: "sci-f2-c11-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah dua bintang paling cerah yang dapat dilihat di langit?",
    options: ["Matahari dan Bulan", "Sirius dan Rigel", "Andromeda dan Bima Sakti", "Marikh dan Musytari"],
    answerIndex: 1,
    explanation: "Bintang paling cerah di langit adalah Sirius dan Rigel.",
  },
  {
    id: "sci-f2-c11-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Kecerahan sesebuah bintang bergantung kepada apa?",
    options: [
      "Saiz, jarak dan suhu permukaannya",
      "Warna rambutnya sahaja",
      "Bilangan planet yang mengelilinginya",
      "Jarak daripada Bulan sahaja",
    ],
    answerIndex: 0,
    explanation: "Kecerahan bintang bergantung kepada saiz, jarak dan suhu permukaannya.",
  },
  {
    id: "sci-f2-c11-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah yang dimaksudkan dengan protobintang dalam kitaran hidup bintang?",
    options: [
      "Bintang yang sudah mati",
      "Peringkat awal pembentukan bintang daripada runtuhan graviti nebula sebelum tindak balas nuklear bermula",
      "Nama lain bagi lohong hitam",
      "Bintang yang sangat cerah seperti Sirius",
    ],
    answerIndex: 1,
    explanation: "Protobintang ialah peringkat awal dalam kitaran hidup bintang apabila nebula runtuh akibat graviti sebelum tindak balas nuklear bermula di teras.",
  },
  {
    id: "sci-f2-c11-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah yang dimaksudkan dengan hipotesis nebular berkaitan kitaran hidup bintang?",
    options: [
      "Idea bahawa semua bintang adalah kekal selama-lamanya",
      "Idea bahawa bintang terbentuk daripada nebula dan berakhir sebagai kerdil putih, bintang neutron atau lohong hitam",
      "Idea bahawa galaksi tidak mempunyai bintang",
      "Idea bahawa Bumi adalah pusat alam semesta",
    ],
    answerIndex: 1,
    explanation: "Hipotesis nebular menjelaskan bahawa bintang terbentuk daripada nebula melalui graviti dan tindak balas nuklear, dan akhirnya mati sebagai kerdil putih, bintang neutron atau lohong hitam, bergantung pada saiz asalnya.",
  },
  {
    id: "sci-f2-c11-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah sumbangan Nur Adlyka Ainul Annuar kepada bidang astronomi?",
    options: [
      "Beliau merupakan orang Malaysia pertama ke angkasa lepas",
      "Beliau membuktikan kewujudan lohong hitam supermasif pada awal 2017",
      "Beliau mereka bentuk Teleskop Hubble",
      "Beliau membina Planetarium Negara",
    ],
    answerIndex: 1,
    explanation: "Nur Adlyka Ainul Annuar membuktikan kewujudan lohong hitam supermasif pada awal 2017.",
  },
  {
    id: "sci-f2-c11-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Dua bintang, P dan Q, mempunyai saiz dan jarak daripada Bumi yang sama, tetapi suhu permukaan bintang P lebih tinggi daripada bintang Q. Apakah yang dapat disimpulkan tentang kecerahan kedua-dua bintang?",
    options: [
      "Bintang Q lebih cerah kerana suhu rendah menghasilkan lebih banyak cahaya",
      "Bintang P lebih cerah kerana suhu permukaan yang lebih tinggi menyumbang kepada kecerahan yang lebih besar",
      "Kedua-dua bintang sama cerah kerana saiz dan jarak adalah sama",
      "Kecerahan tidak berkaitan dengan suhu permukaan langsung",
    ],
    answerIndex: 1,
    explanation: "Oleh sebab kecerahan bergantung kepada saiz, jarak dan suhu permukaan, dan saiz serta jarak adalah sama, bintang dengan suhu permukaan lebih tinggi (Bintang P) akan lebih cerah.",
  },
  {
    id: "sci-f2-c11-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Jika sebuah bintang yang sangat besar (supergergasi) mencapai akhir kitaran hidupnya, hasil akhir yang paling mungkin terbentuk adalah...",
    options: [
      "Kerdil putih sahaja",
      "Bintang neutron atau lohong hitam, bergantung kepada jisim asal bintang itu",
      "Nebula yang kekal selama-lamanya tanpa berubah",
      "Protobintang yang baharu secara automatik",
    ],
    answerIndex: 1,
    explanation: "Mengikut hipotesis nebular, bintang besar/supergergasi yang mati biasanya menjadi bintang neutron atau lohong hitam bergantung kepada jisim asalnya, berbeza dengan bintang bersaiz lebih kecil seperti Matahari yang biasanya berakhir sebagai kerdil putih.",
  },
  {
    id: "sci-f2-c11-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Mengapakah perbandingan saiz Bumi dengan alam semesta digambarkan seperti 'zarah debu'?",
    options: [
      "Kerana Bumi sebenarnya diperbuat daripada debu angkasa lepas",
      "Kerana skala alam semesta amat besar sehingga Bumi menjadi tidak ketara berbanding struktur seperti Bima Sakti, sekumpulan galaksi dan kluster galaksi",
      "Kerana Bumi terletak di luar Bima Sakti",
      "Kerana Bumi adalah planet terkecil dalam sistem suria",
    ],
    answerIndex: 1,
    explanation: "Susunan saiz Bumi < Sistem Suria < Bima Sakti < Sekumpulan Galaksi < Kluster Galaksi < Alam Semesta menunjukkan betapa besarnya skala alam semesta, menjadikan Bumi 'lebih kecil daripada zarah debu' apabila dibandingkan dengannya.",
  },
  {
    id: "sci-f2-c11-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Seorang ahli astronomi mengesan sebuah bintang yang berwarna kuning-keputihan. Berdasarkan jadual klasifikasi bintang, apakah julat suhu permukaan yang paling mungkin bagi bintang ini?",
    options: ["Kurang daripada 3,500 K", "6,000–7,500 K", "11,000–25,000 K", "Lebih daripada 25,000 K"],
    answerIndex: 1,
    explanation: "Mengikut jadual klasifikasi, bintang berwarna kuning-keputihan mempunyai suhu permukaan dalam julat 6,000–7,500 K.",
  },
  {
    id: "sci-f2-c11-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Bagaimanakah teknologi seperti Teleskop Hubble telah mengubah pemahaman manusia tentang alam semesta?",
    options: [
      "Ia membenarkan manusia membina galaksi baharu",
      "Ia membolehkan pemerhatian objek angkasa lepas yang amat jauh dan halus, sekali gus meningkatkan kesedaran tentang keluasan dan keindahan alam semesta",
      "Ia hanya digunakan untuk meramal cuaca di Bumi",
      "Ia menggantikan keperluan kajian astronomi sepenuhnya",
    ],
    answerIndex: 1,
    explanation: "Teleskop Hubble yang amat berkuasa (boleh melihat duit syiling dari 725 km) membolehkan kajian objek angkasa lepas yang jauh, meningkatkan kesedaran manusia terhadap keluasan dan keindahan ciptaan alam semesta.",
  },
  {
    id: "sci-f2-c11-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah perbezaan struktur utama antara galaksi pilin seperti Bima Sakti dan galaksi tidak sekata seperti Awan Magellan?",
    options: [
      "Galaksi pilin mempunyai bentuk dan lengan berstruktur jelas, manakala galaksi tidak sekata tidak mempunyai bentuk tetap",
      "Galaksi pilin tidak mempunyai bintang, manakala galaksi tidak sekata penuh dengan bintang",
      "Galaksi pilin hanya terdapat di luar Bima Sakti, galaksi tidak sekata terdapat di dalam Bima Sakti",
      "Kedua-duanya mempunyai struktur dan bentuk yang sama tepat",
    ],
    answerIndex: 0,
    explanation: "Galaksi pilin (seperti Bima Sakti dan Andromeda) mempunyai bentuk pilin dengan lengan-lengan jelas, berbeza dengan galaksi tidak sekata (seperti Awan Magellan) yang tidak mempunyai bentuk atau struktur yang tetap.",
  },
  {
    id: "sci-f2-c11-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Jika dua bintang mempunyai suhu permukaan dan jarak yang sama daripada Bumi tetapi bintang R bersaiz supergergasi dan bintang S bersaiz kerdil, bintang manakah dijangka lebih cerah, dan mengapa?",
    options: [
      "Bintang S, kerana bintang kecil lebih cerah",
      "Bintang R, kerana saiz yang lebih besar menyumbang kepada kecerahan yang lebih besar apabila suhu dan jarak adalah sama",
      "Kedua-dua bintang sama cerah kerana saiz tidak memberi kesan kepada kecerahan",
      "Tidak dapat ditentukan tanpa mengetahui warna bintang",
    ],
    answerIndex: 1,
    explanation: "Oleh sebab kecerahan dipengaruhi oleh saiz, jarak dan suhu, dan jarak serta suhu adalah sama bagi kedua-dua bintang, bintang yang bersaiz lebih besar (supergergasi, bintang R) akan menghasilkan lebih banyak cahaya dan kelihatan lebih cerah.",
  },
  {
    id: "sci-f2-c11-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Mengapakah pencapaian Dato' Dr. Sheikh Muszaphar Shukor dan Nur Adlyka Ainul Annuar dianggap penting dalam konteks astronomi Malaysia?",
    options: [
      "Kerana mereka adalah satu-satunya orang yang pernah mengkaji alam semesta di dunia",
      "Kerana pencapaian mereka menunjukkan sumbangan dan kemajuan Malaysia dalam bidang sains angkasa lepas dan astronomi di peringkat antarabangsa",
      "Kerana mereka membina Bima Sakti",
      "Kerana mereka mencipta Teleskop Hubble",

    ],
    answerIndex: 1,
    explanation: "Pencapaian Dato' Dr. Sheikh Muszaphar Shukor (orang Malaysia pertama ke angkasa lepas) dan Nur Adlyka Ainul Annuar (membuktikan kewujudan lohong hitam supermasif) mencerminkan sumbangan dan kemajuan Malaysia dalam bidang astronomi dan sains angkasa lepas di peringkat antarabangsa.",
  },
  {
    id: "sci-f2-c11-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Berdasarkan kitaran hidup bintang, susunkan peringkat berikut mengikut urutan yang betul: (i) Gergasi merah, (ii) Nebula, (iii) Protobintang, (iv) Kerdil putih/bintang neutron/lohong hitam.",
    options: [
      "(ii) → (iii) → (i) → (iv)",
      "(i) → (ii) → (iii) → (iv)",
      "(iv) → (i) → (ii) → (iii)",
      "(iii) → (ii) → (iv) → (i)",
    ],
    answerIndex: 0,
    explanation: "Urutan kitaran hidup bintang yang betul ialah: Nebula → Protobintang → Gergasi merah → Kerdil putih/bintang neutron/lohong hitam (bergantung pada saiz asal bintang).",
  },
  {
    id: "sci-f2-c11-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 11",
    lang: "bm",
    question: "Apakah kepentingan Planetarium Negara di Kuala Lumpur dalam konteks pendidikan astronomi di Malaysia?",
    options: [
      "Ia hanya berfungsi sebagai bangunan bersejarah tanpa kaitan dengan astronomi",
      "Ia menggabungkan seni bina Islam dengan astronomi dan membantu mendedahkan orang ramai kepada ilmu angkasa lepas",
      "Ia adalah satu-satunya tempat di dunia untuk melihat bintang",
      "Ia digunakan khusus untuk melancarkan satelit",
    ],
    answerIndex: 1,
    explanation: "Planetarium Negara, dibuka secara rasmi pada 1994, menggabungkan seni bina Islam dengan astronomi, menjadikannya pusat pendidikan dan kesedaran awam tentang alam semesta dan bintang.",
  },
];
