import type { StructuredNotes } from "@/data/types";

export const sejarahF3C3Notes: StructuredNotes = {
  chapterSummary: "Bab ini membincangkan kekayaan hasil bumi Perak, Selangor, Negeri Sembilan dan Pahang, peluasan kuasa British, pembentukan NNMB dan pentadbirannya.",
  quickRevision: ["3.1 Kekayaan Hasil Bumi di Perak, Selangor, Negeri Sembilan dan Pahang: Perak, Selangor, Negeri Sembilan dan Pahang kaya dengan bijih timah, emas dan hasil bumi.","Tarikh penting 3.1: 1857-1898: pemerintahan Sultan Abdul Samad di Selangor","3.2 Peluasan Kuasa British di Perak, Selangor, Negeri Sembilan dan Pahang: British menggunakan alasan kekacauan untuk campur tangan.","Tarikh penting 3.2: 1874: Perjanjian Pangkor","3.3 Pembentukan Negeri-negeri Melayu Bersekutu: Negeri-negeri Melayu Bersekutu terdiri daripada Perak, Selangor, Negeri Sembilan dan Pahang.","Tarikh penting 3.3: 1895: Perjanjian Persekutuan","3.4 Pentadbiran Negeri-negeri Melayu Bersekutu: Pentadbiran NNMB melibatkan Residen Jeneral, Residen negeri, Majlis Mesyuarat Negeri, Durbar dan Majlis Mesyuarat Persekutuan.","Tarikh penting 3.4: 1897: Durbar pertama di Kuala Kangsar"],
  keyTerms: ["bijih timah","emas","hasil bumi","perlombongan","cukai","Sistem Residen","Perjanjian Pangkor","campur tangan","Residen British","NNMB","Perjanjian Persekutuan 1895","Residen Jeneral","pemusatan kuasa","Durbar","Majlis Mesyuarat Negeri","Majlis Mesyuarat Persekutuan"],
  keyExamFacts: ["Perak, Selangor, Negeri Sembilan dan Pahang kaya dengan bijih timah, emas dan hasil bumi.","Kekayaan hasil bumi menarik minat British untuk campur tangan.","Pembesar dan sultan memperoleh pendapatan daripada hasil perlombongan dan cukai.","British menggunakan alasan kekacauan untuk campur tangan.","Perjanjian Pangkor 1874 menandakan penguasaan British secara langsung di Perak.","Raja Abdullah diiktiraf sebagai Sultan Perak dan Sultan menerima Residen British.","Negeri-negeri Melayu Bersekutu terdiri daripada Perak, Selangor, Negeri Sembilan dan Pahang.","Perjanjian Persekutuan 1895 membawa kepada pembentukan NNMB.","Residen Jeneral menjadi ketua pentadbiran kerajaan persekutuan.","Pentadbiran NNMB melibatkan Residen Jeneral, Residen negeri, Majlis Mesyuarat Negeri, Durbar dan Majlis Mesyuarat Persekutuan.","Durbar pertama diadakan di Kuala Kangsar.","Pada tahun 1909, Majlis Mesyuarat Persekutuan ditubuhkan."],
  sections: [
    {
      title: "Bab Overview",
      subsections: [
        { title: "Sinopsis", content: "Bab ini membincangkan kekayaan hasil bumi Perak, Selangor, Negeri Sembilan dan Pahang, peluasan kuasa British, pembentukan NNMB dan pentadbirannya." },
        { title: "Apa yang akan dipelajari", bulletPoints: ["3.1 Kekayaan Hasil Bumi di Perak, Selangor, Negeri Sembilan dan Pahang","3.2 Peluasan Kuasa British di Perak, Selangor, Negeri Sembilan dan Pahang","3.3 Pembentukan Negeri-negeri Melayu Bersekutu","3.4 Pentadbiran Negeri-negeri Melayu Bersekutu"] },
        { title: "Fokus UASA", bulletPoints: ["Kenal pasti kronologi, tokoh, tempat, perjanjian dan kesan.","Bezakan sebab, strategi dan kesan peluasan kuasa Barat.","Gunakan kata kunci seperti kedaulatan, pentadbiran, ekonomi, penentangan dan pemodenan."] },
      ],
    },
    {
      title: "3.1 Kekayaan Hasil Bumi di Perak, Selangor, Negeri Sembilan dan Pahang",
      subsections: [
        { title: "Ringkasan", content: "Kekayaan Hasil Bumi di Perak, Selangor, Negeri Sembilan dan Pahang menerangkan perak, selangor, negeri sembilan dan pahang kaya dengan bijih timah, emas dan hasil bumi. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Perak, Selangor, Negeri Sembilan dan Pahang kaya dengan bijih timah, emas dan hasil bumi.","Kekayaan hasil bumi menarik minat British untuk campur tangan.","Pembesar dan sultan memperoleh pendapatan daripada hasil perlombongan dan cukai.","Perkembangan perlombongan menyebabkan kemasukan modal dan buruh luar."] },
        { title: "Kata kunci", bulletPoints: ["bijih timah","emas","hasil bumi","perlombongan","cukai"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Muzaffar Shah","Sultan Abdul Samad","Sultan Ahmad","Ngah Ibrahim"] },
        { title: "Tarikh penting", bulletPoints: ["1857-1898: pemerintahan Sultan Abdul Samad di Selangor","1885: Sultan Ahmad di Pahang dirakam dalam sumber textbook"] },
        { title: "Tempat penting", bulletPoints: ["Larut","Kinta","Kuala Lumpur","Lukut","Sungai Ujong","Pahang"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Rujuk fakta pentadbiran dalam subtopik"]] } },
        { title: "Sebab", bulletPoints: ["Permintaan bijih timah meningkat","Kekayaan lombong","Kepentingan cukai dan perdagangan"] },
        { title: "Kesan", bulletPoints: ["British memberi perhatian kepada negeri Melayu","Persaingan pembesar dan pelombong meningkat","Campur tangan British menjadi lebih mudah"] },
        { title: "Kepentingan", bulletPoints: ["Kekayaan hasil bumi ialah punca utama British mahu menguasai negeri-negeri Melayu."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Kekayaan ekonomi membawa kepada perebutan kuasa dan alasan campur tangan British."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta kawasan lombong menunjukkan tumpuan ekonomi di Perak, Selangor, Negeri Sembilan dan Pahang.","Abad ke-19: permintaan bijih timah dan hasil bumi meningkat"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "3.2 Peluasan Kuasa British di Perak, Selangor, Negeri Sembilan dan Pahang",
      subsections: [
        { title: "Ringkasan", content: "Peluasan Kuasa British di Perak, Selangor, Negeri Sembilan dan Pahang menerangkan british menggunakan alasan kekacauan untuk campur tangan. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["British menggunakan alasan kekacauan untuk campur tangan.","Perjanjian Pangkor 1874 menandakan penguasaan British secara langsung di Perak.","Raja Abdullah diiktiraf sebagai Sultan Perak dan Sultan menerima Residen British.","Perjanjian British-Selangor 1875, British-Sungai Ujong, British-Pahang 1887 dan British-Negeri Sembilan 1895 mengukuhkan Sistem Residen."] },
        { title: "Kata kunci", bulletPoints: ["Sistem Residen","Perjanjian Pangkor","campur tangan","Residen British"] },
        { title: "Tokoh penting", bulletPoints: ["Andrew Clarke","Raja Abdullah","Raja Ismail","Ngah Ibrahim","Dato' Sagor","J.W.W. Birch","J.G. Davidson","Martin Lister","J.P. Rodger"] },
        { title: "Tarikh penting", bulletPoints: ["1874: Perjanjian Pangkor","1875: Perjanjian British-Selangor","1887: Perjanjian British-Pahang","1895: Perjanjian British-Negeri Sembilan"] },
        { title: "Tempat penting", bulletPoints: ["Pulau Pangkor","Perak","Selangor","Sungai Ujong","Pahang","HMS Pluto"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Pangkor 1874; Perjanjian British-Sungai Ujong; Perjanjian British-Selangor 1875; Perjanjian British-Pahang 1887; Perjanjian British-Negeri Sembilan 1895"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Sistem Residen; Residen British"]] } },
        { title: "Sebab", bulletPoints: ["Pergaduhan kongsi gelap","Perebutan takhta","Kepentingan bijih timah","British mahu mengawal cukai"] },
        { title: "Kesan", bulletPoints: ["Residen British ditempatkan","Sultan dan pembesar kehilangan kuasa pentadbiran","British menguasai pungutan cukai"] },
        { title: "Kepentingan", bulletPoints: ["Menunjukkan bagaimana perjanjian digunakan untuk menghakis kedaulatan negeri Melayu."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Sistem Residen menjadi asas pembentukan NNMB."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta Pulau Pangkor menunjukkan lokasi perjanjian penting antara British dengan pembesar Perak.","1874 Perak","1875 Selangor","1887 Pahang","1895 Negeri Sembilan"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "3.3 Pembentukan Negeri-negeri Melayu Bersekutu",
      subsections: [
        { title: "Ringkasan", content: "Pembentukan Negeri-negeri Melayu Bersekutu menerangkan negeri-negeri melayu bersekutu terdiri daripada perak, selangor, negeri sembilan dan pahang. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Negeri-negeri Melayu Bersekutu terdiri daripada Perak, Selangor, Negeri Sembilan dan Pahang.","Perjanjian Persekutuan 1895 membawa kepada pembentukan NNMB.","Residen Jeneral menjadi ketua pentadbiran kerajaan persekutuan.","Pembentukan NNMB bertujuan menyeragamkan pentadbiran dan mengatasi kelemahan Sistem Residen."] },
        { title: "Kata kunci", bulletPoints: ["NNMB","Perjanjian Persekutuan 1895","Residen Jeneral","pemusatan kuasa"] },
        { title: "Tokoh penting", bulletPoints: ["Frank Swettenham","Raja-raja Melayu","Residen Jeneral"] },
        { title: "Tarikh penting", bulletPoints: ["1895: Perjanjian Persekutuan","1896: NNMB dilaksanakan"] },
        { title: "Tempat penting", bulletPoints: ["Perak","Selangor","Negeri Sembilan","Pahang","Kuala Lumpur"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Persekutuan 1895"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","NNMB; Residen Jeneral"]] } },
        { title: "Sebab", bulletPoints: ["Sistem Residen tidak seragam","British mahu kawalan kewangan dan pentadbiran lebih berpusat","Keperluan menyelaraskan pembangunan"] },
        { title: "Kesan", bulletPoints: ["Kuasa Residen Jeneral meningkat","Raja-raja Melayu kehilangan lebih banyak kuasa","Pentadbiran menjadi lebih berpusat"] },
        { title: "Kepentingan", bulletPoints: ["Pembentukan NNMB mempercepat pemusatan kuasa British."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Campur tangan melalui Residen membawa kepada persekutuan yang lebih terkawal oleh British."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta NNMB menunjukkan gabungan empat negeri kaya hasil bumi.","1895 perjanjian","1896 pelaksanaan NNMB"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "3.4 Pentadbiran Negeri-negeri Melayu Bersekutu",
      subsections: [
        { title: "Ringkasan", content: "Pentadbiran Negeri-negeri Melayu Bersekutu menerangkan pentadbiran nnmb melibatkan residen jeneral, residen negeri, majlis mesyuarat negeri, durbar dan majlis mesyuarat persekutuan. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Pentadbiran NNMB melibatkan Residen Jeneral, Residen negeri, Majlis Mesyuarat Negeri, Durbar dan Majlis Mesyuarat Persekutuan.","Durbar pertama diadakan di Kuala Kangsar.","Pada tahun 1909, Majlis Mesyuarat Persekutuan ditubuhkan.","Majlis Mesyuarat Persekutuan memberikan ruang kepada British mengawal undang-undang dan kewangan negeri."] },
        { title: "Kata kunci", bulletPoints: ["Residen Jeneral","Durbar","Majlis Mesyuarat Negeri","Majlis Mesyuarat Persekutuan"] },
        { title: "Tokoh penting", bulletPoints: ["Pesuruhjaya Tinggi British","Raja-raja Melayu","Residen Jeneral","Residen British"] },
        { title: "Tarikh penting", bulletPoints: ["1897: Durbar pertama di Kuala Kangsar","1909: Majlis Mesyuarat Persekutuan ditubuhkan"] },
        { title: "Tempat penting", bulletPoints: ["Kuala Kangsar","Kuala Lumpur","Pekan","Klang","Seri Menanti"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Undang-undang yang diluluskan Majlis Mesyuarat Persekutuan"],["Organisasi / pentadbiran","Residen Jeneral; Durbar; Majlis Mesyuarat Negeri; Majlis Mesyuarat Persekutuan"]] } },
        { title: "Sebab", bulletPoints: ["British mahu sokongan Raja-raja Melayu","Pemusatan pentadbiran memerlukan badan perundangan","Keperluan mengawal kewangan"] },
        { title: "Kesan", bulletPoints: ["Kewibawaan Raja-raja Melayu terjejas","British mengawal undang-undang dan kewangan","Durbar menjadi ruang pertemuan Raja-raja Melayu"] },
        { title: "Kepentingan", bulletPoints: ["Menunjukkan perkembangan institusi pentadbiran kolonial dan reaksi Raja-raja Melayu."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Durbar menjadi asas perbincangan Raja-raja Melayu dalam menghadapi pemusatan kuasa British."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Rajah keahlian Majlis Mesyuarat Persekutuan menunjukkan dominasi pegawai British dalam pentadbiran NNMB.","1897 Durbar pertama","1909 Majlis Mesyuarat Persekutuan"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "Rumusan Bab",
      subsections: [
        { title: "Imbas Kembali", bulletPoints: ["3.1: bijih timah, emas, hasil bumi, perlombongan","3.2: Sistem Residen, Perjanjian Pangkor, campur tangan, Residen British","3.3: NNMB, Perjanjian Persekutuan 1895, Residen Jeneral, pemusatan kuasa","3.4: Residen Jeneral, Durbar, Majlis Mesyuarat Negeri, Majlis Mesyuarat Persekutuan"] },
        { title: "Kata Kunci Peperiksaan", bulletPoints: ["bijih timah","emas","hasil bumi","perlombongan","cukai","Sistem Residen","Perjanjian Pangkor","campur tangan","Residen British","NNMB","Perjanjian Persekutuan 1895","Residen Jeneral","pemusatan kuasa","Durbar","Majlis Mesyuarat Negeri","Majlis Mesyuarat Persekutuan"] },
      ],
    }
  ],
};
