import type { Flashcard } from "@/data/content";

export const scienceF2C13FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c13-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud meteoroid?",
    back: "Sekeping batu dan logam terapung yang bergerak di angkasa lepas.",
  },
  {
    id: "sci-f2-c13-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud asteroid?",
    back: "Jasad besar logam dan berbatu yang bergerak mengelilingi Matahari pada orbitnya sendiri.",
  },
  {
    id: "sci-f2-c13-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud komet?",
    back: "Jasad kecil terdiri daripada campuran ais, gas dan debu yang membeku, bergerak mengelilingi Matahari pada orbitnya sendiri.",
  },
  {
    id: "sci-f2-c13-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud meteor?",
    back: "Meteoroid yang terbakar apabila memasuki atmosfera Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud meteorit?",
    back: "Meteoroid (atau baki meteor) yang berjaya sampai ke permukaan Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah julat saiz meteoroid?",
    back: "Daripada 10 m hingga 1 m.",
  },
  {
    id: "sci-f2-c13-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah julat saiz asteroid?",
    back: "Daripada 1 m hingga 1,000 km.",
  },
  {
    id: "sci-f2-c13-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah komposisi meteoroid dan asteroid?",
    back: "Batu dan logam seperti besi dan nikel.",
  },
  {
    id: "sci-f2-c13-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah suhu permukaan meteoroid di angkasa lepas?",
    back: "Kira-kira 0°C.",
  },
  {
    id: "sci-f2-c13-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah suhu permukaan asteroid?",
    back: "Sejuk, kira-kira −73°C.",
  },
  {
    id: "sci-f2-c13-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah kelajuan meteoroid paling pantas?",
    back: "42 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah kelajuan purata asteroid mengelilingi Matahari?",
    back: "25 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah Lingkaran Asteroid (asteroid belt)?",
    back: "Kawasan antara orbit Marikh dan Musytari tempat kebanyakan asteroid berada.",
  },
  {
    id: "sci-f2-c13-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Namakan empat asteroid besar dalam nota.",
    back: "Ceres, Pallas, Juno dan Vesta.",
  },
  {
    id: "sci-f2-c13-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah gelaran lain bagi asteroid?",
    back: "Planet kecil.",
  },
  {
    id: "sci-f2-c13-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah dua bahagian utama komet?",
    back: "Kepala dan ekor.",
  },
  {
    id: "sci-f2-c13-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah panjang maksimum ekor komet?",
    back: "150,000,000 km.",
  },
  {
    id: "sci-f2-c13-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah saiz maksimum kepala komet?",
    back: "250,000 km.",
  },
  {
    id: "sci-f2-c13-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah komposisi komet?",
    back: "Gas dan air yang membeku menjadi ais, debu dan zarah berbatu.",
  },
  {
    id: "sci-f2-c13-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah julat kelajuan purata komet?",
    back: "10 km s⁻¹ hingga 70 km s⁻¹.",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c13-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bandingkan meteoroid dengan meteor.",
    back: "Meteoroid: objek di angkasa lepas. Meteor: meteoroid yang terbakar semasa memasuki atmosfera Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bandingkan meteor dengan meteorit.",
    back: "Meteor: terbakar di atmosfera, biasanya habis terbakar. Meteorit: serpihan yang berjaya sampai ke permukaan Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bandingkan saiz meteoroid dengan saiz asteroid.",
    back: "Meteoroid: 10 m hingga 1 m. Asteroid: 1 m hingga 1,000 km — asteroid jauh lebih besar.",
  },
  {
    id: "sci-f2-c13-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bandingkan suhu permukaan meteoroid dan asteroid.",
    back: "Meteoroid: kira-kira 0°C. Asteroid: kira-kira −73°C (lebih sejuk).",
  },
  {
    id: "sci-f2-c13-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bandingkan kelajuan asteroid dengan kelajuan komet.",
    back: "Asteroid: purata 25 km s⁻¹ (agak tetap). Komet: julat luas 10 km s⁻¹ hingga 70 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bandingkan komposisi asteroid dengan komposisi komet.",
    back: "Asteroid: batu dan logam (besi, nikel) — pejal. Komet: ais, gas, debu dan zarah berbatu — banyak bahan beku.",
  },
  {
    id: "sci-f2-c13-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bandingkan orbit asteroid dengan orbit komet.",
    back: "Asteroid: kebanyakan dalam Lingkaran Asteroid antara Marikh dan Musytari. Komet: orbit elips sendiri, boleh melepasi Lingkaran Kuiper dan Awan Oort.",
  },
  {
    id: "sci-f2-c13-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Dari mana meteoroid berasal?",
    back: "Daripada serpihan asteroid dan komet.",
  },
  {
    id: "sci-f2-c13-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud Lingkaran Kuiper?",
    back: "Kawasan di tepi sistem suria, di luar orbit Neptun, yang menjadi salah satu asal usul komet.",
  },
  {
    id: "sci-f2-c13-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud Awan Oort?",
    back: "Kawasan sfera yang sangat jauh mengelilingi sistem suria, dipercayai menjadi sumber komet berjangka masa lama.",
  },
  {
    id: "sci-f2-c13-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Namakan dua komet yang dikenali dalam nota.",
    back: "Komet Halley dan komet Shoemaker-Levy 9.",
  },
  {
    id: "sci-f2-c13-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Bilakah komet Halley terakhir dilihat dan bila ia dijangka kelihatan semula?",
    back: "Terakhir dilihat pada 1986; dijangka kelihatan semula pada 2061.",
  },
  {
    id: "sci-f2-c13-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah peristiwa penting komet Shoemaker-Levy 9 pada tahun 1994?",
    back: "Ia melanggar Musytari — perlanggaran langsung pertama komet dengan objek dalam sistem suria yang direkodkan.",
  },
  {
    id: "sci-f2-c13-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah Orbit Apollo, Amor dan Aten?",
    back: "Contoh orbit asteroid di luar Lingkaran Asteroid yang boleh bersilang dengan orbit Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah Meteorit Hoba?",
    back: "Meteorit terbesar yang pernah direkodkan di dunia, dijumpai berhampiran Grootfontein, Namibia pada 1920.",
  },
  {
    id: "sci-f2-c13-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berapakah diameter kawah meteorit di Arizona, Amerika Syarikat?",
    back: "Kira-kira 1.2 km, terbentuk kira-kira 50,000 tahun lalu.",
  },
  {
    id: "sci-f2-c13-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah hubungan asteroid dengan kepupusan dinosaur?",
    back: "Pakar paleontologi mempercayai kepupusan dinosaur disebabkan perlanggaran asteroid berukuran 10 km dengan Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Mengapa saintis memantau orbit asteroid?",
    back: "Untuk memastikan orbitnya selamat daripada orbit Bumi dan mengeluarkan amaran jika ada risiko perlanggaran.",
  },
  {
    id: "sci-f2-c13-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah tindakan yang boleh diambil jika asteroid menghampiri Bumi dengan risiko perlanggaran?",
    back: "Asteroid itu boleh dimusnahkan atau diubah arahnya.",
  },
  {
    id: "sci-f2-c13-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah peranan ANGKASA?",
    back: "Agensi Angkasa Negara yang bertanggungjawab menggerakkan dan memantau pembangunan sains angkasa lepas di Malaysia.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c13-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Mengapa asteroid lebih sejuk berbanding meteoroid?",
    back: "Asteroid kebanyakannya berada lebih jauh daripada Matahari dalam Lingkaran Asteroid, berbanding meteoroid yang lebih kerap dijumpai berhampiran orbit dalam.",
  },
  {
    id: "sci-f2-c13-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Mengapa orbit Apollo, Amor dan Aten dianggap berisiko lebih tinggi?",
    back: "Kerana orbitnya berada di luar Lingkaran Asteroid dan boleh bersilang dengan orbit Bumi, meningkatkan risiko perlanggaran.",
  },
  {
    id: "sci-f2-c13-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Apakah kesimpulan daripada kawah Arizona tentang kesan perlanggaran objek angkasa?",
    back: "Objek angkasa walaupun tidak terlalu besar boleh meninggalkan kesan fizikal kekal yang besar disebabkan tenaga kinetik tinggi semasa perlanggaran.",
  },
  {
    id: "sci-f2-c13-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Mengapa perlanggaran Shoemaker-Levy 9 dengan Musytari pada 1994 penting bagi sains angkasa lepas?",
    back: "Ia membuktikan secara langsung bahawa perlanggaran komet dengan objek sistem suria boleh berlaku dan diamati, meningkatkan keperluan pemantauan objek angkasa.",
  },
  {
    id: "sci-f2-c13-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana membezakan meteoroid, meteor dan meteorit dalam jawapan peperiksaan?",
    back: "Nyatakan lokasi/keadaan: meteoroid = di angkasa lepas; meteor = terbakar semasa memasuki atmosfera; meteorit = sampai ke permukaan Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah asteroid dan meteoroid diperbuat daripada bahan yang sama sepenuhnya?",
    back: "Kebanyakannya sama (batu dan logam seperti besi dan nikel), tetapi berbeza dari segi saiz, suhu dan kelajuan pergerakan.",
  },
  {
    id: "sci-f2-c13-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah komet sama dengan asteroid?",
    back: "Tidak. Komet terdiri terutamanya daripada ais, gas dan debu beku dengan ekor panjang; asteroid terdiri daripada batu dan logam pejal tanpa ekor.",
  },
  {
    id: "sci-f2-c13-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Bagaimana komet Halley membantu saintis mengesahkan jangkaan orbit objek angkasa?",
    back: "Kemunculan berulang komet Halley pada selang masa yang boleh diramal (1986 → 2061) membolehkan saintis mengesahkan ketepatan model orbit elips komet.",
  },
  {
    id: "sci-f2-c13-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[Fakta Penting] Apakah yang istimewa tentang Meteorit Hoba?",
    back: "Ia meteorit terbesar direkodkan di dunia, dipercayai jatuh kira-kira 80,000 tahun lalu, ditemui di Namibia pada 1920.",
  },
  {
    id: "sci-f2-c13-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Mengapa pemantauan saintifik berterusan terhadap asteroid penting untuk keselamatan Bumi?",
    back: "Ia membolehkan amaran awal dikeluarkan jika risiko perlanggaran dikenal pasti, supaya tindakan seperti memusnahkan atau mengubah arah asteroid dapat dirancang sebelum perlanggaran berlaku.",
  },
  {
    id: "sci-f2-c13-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berikan tiga ciri umum meteoroid.",
    back: "Bersaiz 10 m hingga 1 m, terdiri daripada batu dan logam, suhu permukaan kira-kira 0°C.",
  },
  {
    id: "sci-f2-c13-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berikan tiga ciri umum asteroid.",
    back: "Bersaiz 1 m hingga 1,000 km, suhu kira-kira −73°C, kebanyakannya dalam Lingkaran Asteroid antara Marikh dan Musytari.",
  },
  {
    id: "sci-f2-c13-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Berikan tiga ciri umum komet.",
    back: "Terdiri daripada kepala dan ekor, komposisi ais/gas/debu, bergerak pada orbit elips dengan kelajuan 10-70 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Jika sebuah objek angkasa bersaiz 500 km dan terdiri daripada batu dan logam, apakah ia kemungkinan besar?",
    back: "Sebuah asteroid, kerana saiznya (1 m hingga 1,000 km) dan komposisinya (batu dan logam) sepadan dengan ciri asteroid, bukan meteoroid atau komet.",
  },
  {
    id: "sci-f2-c13-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Jika sebuah objek mempunyai ekor sepanjang 100,000,000 km, apakah ia?",
    back: "Sebuah komet, kerana hanya komet mempunyai ekor yang boleh mencapai sehingga 150,000,000 km.",
  },
  {
    id: "sci-f2-c13-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Apakah maksud orbit elips bagi komet?",
    back: "Bentuk laluan bujur (bukan bulat sempurna) yang dilalui komet semasa mengelilingi Matahari.",
  },
  {
    id: "sci-f2-c13-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah semua asteroid berada dalam Lingkaran Asteroid?",
    back: "Tidak semua. Sebahagian seperti dalam orbit Apollo, Amor dan Aten berada di luar Lingkaran Asteroid dan boleh bersilang dengan orbit Bumi.",
  },
  {
    id: "sci-f2-c13-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan membandingkan tiga objek angkasa ini dengan markah penuh?",
    back: "Bandingkan mengikut tiga aspek: saiz, komposisi/suhu dan kelajuan/orbit untuk setiap objek (meteoroid, asteroid, komet).",
  },
  {
    id: "sci-f2-c13-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "[KBAT] Mengapa komet kelihatan bercahaya dengan ekor panjang apabila menghampiri Matahari?",
    back: "Haba daripada Matahari menyebabkan ais pada komet menyejat (sublimasi) membentuk gas dan debu yang dipancarkan menjauhi Matahari, menghasilkan ekor bercahaya.",
  },
  {
    id: "sci-f2-c13-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "bm",
    front: "Ringkaskan topik Bab 13 dalam satu ayat.",
    back: "Meteoroid, asteroid dan komet ialah objek lain dalam sistem suria selain galaksi, bintang dan planet, masing-masing berbeza dari segi saiz, komposisi, suhu dan orbit, dan dipantau oleh saintis kerana risiko perlanggaran dengan Bumi.",
  },
];
