import type { Flashcard } from "@/data/content";

export const scienceF2C13FlashcardsDLP: Flashcard[] = [
  // Deck 1: Basics (Cards 1-20)
  {
    id: "sci-f2-c13-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of a meteoroid?",
    back: "A floating piece of rock and metal that moves in outer space.",
  },
  {
    id: "sci-f2-c13-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of an asteroid?",
    back: "A large rocky and metallic body that moves around the Sun in its own orbit.",
  },
  {
    id: "sci-f2-c13-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of a comet?",
    back: "A small body made up of a mixture of frozen ice, gas and dust, moving around the Sun in its own orbit.",
  },
  {
    id: "sci-f2-c13-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of a meteor?",
    back: "A meteoroid that burns up when it enters the Earth's atmosphere.",
  },
  {
    id: "sci-f2-c13-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of a meteorite?",
    back: "A meteoroid (or the remains of a meteor) that successfully reaches the Earth's surface.",
  },
  {
    id: "sci-f2-c13-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the size range of a meteoroid?",
    back: "From 10 m to 1 m.",
  },
  {
    id: "sci-f2-c13-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the size range of an asteroid?",
    back: "From 1 m to 1,000 km.",
  },
  {
    id: "sci-f2-c13-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the composition of meteoroids and asteroids?",
    back: "Rock and metals such as iron and nickel.",
  },
  {
    id: "sci-f2-c13-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the surface temperature of a meteoroid in outer space?",
    back: "About 0°C.",
  },
  {
    id: "sci-f2-c13-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the surface temperature of an asteroid?",
    back: "Cold, about −73°C.",
  },
  {
    id: "sci-f2-c13-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the fastest speed of a meteoroid?",
    back: "42 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the average speed of an asteroid orbiting the Sun?",
    back: "25 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the Asteroid Belt?",
    back: "The region between the orbits of Mars and Jupiter where most asteroids are located.",
  },
  {
    id: "sci-f2-c13-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Name four large asteroids mentioned in the notes.",
    back: "Ceres, Pallas, Juno and Vesta.",
  },
  {
    id: "sci-f2-c13-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is another name for an asteroid?",
    back: "A minor planet.",
  },
  {
    id: "sci-f2-c13-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What are the two main parts of a comet?",
    back: "The head and the tail.",
  },
  {
    id: "sci-f2-c13-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the maximum length of a comet's tail?",
    back: "150,000,000 km.",
  },
  {
    id: "sci-f2-c13-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the maximum size of a comet's head?",
    back: "250,000 km.",
  },
  {
    id: "sci-f2-c13-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the composition of a comet?",
    back: "Gas and water frozen into ice, dust and rocky particles.",
  },
  {
    id: "sci-f2-c13-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the average speed range of a comet?",
    back: "10 km s⁻¹ to 70 km s⁻¹.",
  },

  // Deck 2: Understanding (Cards 21-40)
  {
    id: "sci-f2-c13-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Compare a meteoroid with a meteor.",
    back: "Meteoroid: an object in outer space. Meteor: a meteoroid that burns up while entering the Earth's atmosphere.",
  },
  {
    id: "sci-f2-c13-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Compare a meteor with a meteorite.",
    back: "Meteor: burns up in the atmosphere, usually completely burnt up. Meteorite: the fragment that successfully reaches the Earth's surface.",
  },
  {
    id: "sci-f2-c13-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Compare the size of a meteoroid with the size of an asteroid.",
    back: "Meteoroid: 10 m to 1 m. Asteroid: 1 m to 1,000 km — asteroids are far larger.",
  },
  {
    id: "sci-f2-c13-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Compare the surface temperature of a meteoroid and an asteroid.",
    back: "Meteoroid: about 0°C. Asteroid: about −73°C (colder).",
  },
  {
    id: "sci-f2-c13-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Compare the speed of an asteroid with the speed of a comet.",
    back: "Asteroid: average 25 km s⁻¹ (fairly constant). Comet: wide range from 10 km s⁻¹ to 70 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Compare the composition of an asteroid with the composition of a comet.",
    back: "Asteroid: rock and metal (iron, nickel) — solid. Comet: ice, gas, dust and rocky particles — mostly frozen material.",
  },
  {
    id: "sci-f2-c13-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Compare the orbit of an asteroid with the orbit of a comet.",
    back: "Asteroid: mostly within the Asteroid Belt between Mars and Jupiter. Comet: its own elliptical orbit, which can extend past the Kuiper Belt and the Oort Cloud.",
  },
  {
    id: "sci-f2-c13-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Where do meteoroids originate from?",
    back: "From fragments of asteroids and comets.",
  },
  {
    id: "sci-f2-c13-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of the Kuiper Belt?",
    back: "A region at the edge of the solar system, beyond Neptune's orbit, which is one of the origins of comets.",
  },
  {
    id: "sci-f2-c13-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of the Oort Cloud?",
    back: "A very distant spherical region surrounding the solar system, believed to be the source of long-period comets.",
  },
  {
    id: "sci-f2-c13-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Name two comets known from the notes.",
    back: "Halley's Comet and Comet Shoemaker-Levy 9.",
  },
  {
    id: "sci-f2-c13-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "When was Halley's Comet last seen and when is it expected to be seen again?",
    back: "Last seen in 1986; expected to be seen again in 2061.",
  },
  {
    id: "sci-f2-c13-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What was the significant event involving Comet Shoemaker-Levy 9 in 1994?",
    back: "It collided with Jupiter — the first directly recorded collision of a comet with an object in the solar system.",
  },
  {
    id: "sci-f2-c13-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What are the Apollo, Amor and Aten orbits?",
    back: "Examples of asteroid orbits outside the Asteroid Belt that can cross Earth's orbit.",
  },
  {
    id: "sci-f2-c13-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the Hoba Meteorite?",
    back: "The largest meteorite ever recorded in the world, found near Grootfontein, Namibia in 1920.",
  },
  {
    id: "sci-f2-c13-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the diameter of the meteorite crater in Arizona, United States?",
    back: "About 1.2 km, formed about 50,000 years ago.",
  },
  {
    id: "sci-f2-c13-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the connection between asteroids and the extinction of dinosaurs?",
    back: "Paleontologists believe the extinction of dinosaurs was caused by a collision between a 10 km-sized asteroid and Earth.",
  },
  {
    id: "sci-f2-c13-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Why do scientists monitor the orbits of asteroids?",
    back: "To ensure their orbits are safe from Earth's orbit and to issue warnings if there is a risk of collision.",
  },
  {
    id: "sci-f2-c13-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What action can be taken if an asteroid approaches Earth with a risk of collision?",
    back: "The asteroid can be destroyed or its direction altered.",
  },
  {
    id: "sci-f2-c13-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the role of ANGKASA?",
    back: "The National Space Agency responsible for driving and monitoring the development of space science in Malaysia.",
  },

  // Deck 3: Exam (Cards 41-60)
  {
    id: "sci-f2-c13-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] Why are asteroids colder compared to meteoroids?",
    back: "Asteroids are mostly located farther from the Sun in the Asteroid Belt, compared to meteoroids which are more often found near inner orbits.",
  },
  {
    id: "sci-f2-c13-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] Why are the Apollo, Amor and Aten orbits considered higher risk?",
    back: "Because their orbits lie outside the Asteroid Belt and can cross Earth's orbit, increasing the risk of collision.",
  },
  {
    id: "sci-f2-c13-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] What conclusion can be drawn from the Arizona crater about the effect of a space object collision?",
    back: "A space object, even if not very large, can leave a permanent large physical impact due to the high kinetic energy during collision.",
  },
  {
    id: "sci-f2-c13-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] Why was the collision of Shoemaker-Levy 9 with Jupiter in 1994 significant for space science?",
    back: "It directly proved that collisions between comets and solar system objects can occur and be observed, increasing the need for monitoring space objects.",
  },
  {
    id: "sci-f2-c13-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[Exam Tip] How do you distinguish between meteoroid, meteor and meteorite in an exam answer?",
    back: "State the location/condition: meteoroid = in outer space; meteor = burns up while entering the atmosphere; meteorite = reaches Earth's surface.",
  },
  {
    id: "sci-f2-c13-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[Common Mistake] Are asteroids and meteoroids made entirely of the same material?",
    back: "Mostly the same (rock and metals such as iron and nickel), but they differ in size, temperature and speed of movement.",
  },
  {
    id: "sci-f2-c13-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[Common Mistake] Is a comet the same as an asteroid?",
    back: "No. A comet consists mainly of frozen ice, gas and dust with a long tail; an asteroid consists of solid rock and metal without a tail.",
  },
  {
    id: "sci-f2-c13-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] How does Halley's Comet help scientists confirm predictions of space object orbits?",
    back: "The recurring appearance of Halley's Comet at predictable intervals (1986 → 2061) allows scientists to verify the accuracy of the comet's elliptical orbit model.",
  },
  {
    id: "sci-f2-c13-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[Important Fact] What is special about the Hoba Meteorite?",
    back: "It is the largest meteorite ever recorded in the world, believed to have fallen about 80,000 years ago, discovered in Namibia in 1920.",
  },
  {
    id: "sci-f2-c13-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] Why is continuous scientific monitoring of asteroids important for Earth's safety?",
    back: "It allows early warnings to be issued if a collision risk is identified, so that actions such as destroying or redirecting the asteroid can be planned before a collision occurs.",
  },
  {
    id: "sci-f2-c13-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Give three general characteristics of a meteoroid.",
    back: "Sized 10 m to 1 m, made of rock and metal, surface temperature about 0°C.",
  },
  {
    id: "sci-f2-c13-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Give three general characteristics of an asteroid.",
    back: "Sized 1 m to 1,000 km, temperature about −73°C, mostly within the Asteroid Belt between Mars and Jupiter.",
  },
  {
    id: "sci-f2-c13-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Give three general characteristics of a comet.",
    back: "Consists of a head and a tail, composed of ice/gas/dust, moves in an elliptical orbit with a speed of 10-70 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] If a space object is 500 km in size and made of rock and metal, what is it most likely to be?",
    back: "An asteroid, because its size (1 m to 1,000 km) and composition (rock and metal) match the characteristics of an asteroid, not a meteoroid or comet.",
  },
  {
    id: "sci-f2-c13-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] If an object has a tail 100,000,000 km long, what is it?",
    back: "A comet, because only comets have tails that can reach up to 150,000,000 km.",
  },
  {
    id: "sci-f2-c13-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "What is the meaning of an elliptical orbit for a comet?",
    back: "An oval-shaped (not perfectly circular) path that a comet follows while orbiting the Sun.",
  },
  {
    id: "sci-f2-c13-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[Common Mistake] Are all asteroids located within the Asteroid Belt?",
    back: "Not all. Some, such as those in the Apollo, Amor and Aten orbits, are located outside the Asteroid Belt and can cross Earth's orbit.",
  },
  {
    id: "sci-f2-c13-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[Exam Tip] How do you answer a question comparing these three space objects for full marks?",
    back: "Compare according to three aspects: size, composition/temperature and speed/orbit for each object (meteoroid, asteroid, comet).",
  },
  {
    id: "sci-f2-c13-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "[KBAT] Why does a comet appear to glow with a long tail when approaching the Sun?",
    back: "Heat from the Sun causes the ice on the comet to evaporate (sublime), forming gas and dust that is pushed away from the Sun, producing a glowing tail.",
  },
  {
    id: "sci-f2-c13-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 13",
    lang: "dlp",
    front: "Summarise the topic of Chapter 13 in one sentence.",
    back: "Meteoroids, asteroids and comets are other objects in the solar system besides galaxies, stars and planets, each differing in size, composition, temperature and orbit, and are monitored by scientists due to the risk of collision with Earth.",
  },
];
