import type { QuizQuestion } from "@/data/content";

export const scienceF2C13QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c13-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah maksud meteoroid?",
    options: [
      "Sekeping batu dan logam terapung yang bergerak di angkasa lepas",
      "Jasad besar logam dan berbatu yang mengelilingi Matahari pada orbitnya sendiri",
      "Jasad kecil terdiri daripada campuran ais, gas dan debu yang membeku",
      "Bintang yang sangat kecil dan tidak memancarkan cahaya",
    ],
    answerIndex: 0,
    explanation: "Meteoroid ialah sekeping batu dan logam terapung yang bergerak di angkasa lepas.",
  },
  {
    id: "sci-f2-c13-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah maksud asteroid?",
    options: [
      "Jasad kecil ais, gas dan debu membeku",
      "Jasad besar logam dan berbatu yang bergerak mengelilingi Matahari pada orbitnya sendiri",
      "Serpihan batu yang terbakar di atmosfera Bumi",
      "Sekeping batu kecil yang sampai ke permukaan Bumi",
    ],
    answerIndex: 1,
    explanation: "Asteroid ialah jasad besar logam dan berbatu yang bergerak mengelilingi Matahari pada orbitnya sendiri.",
  },
  {
    id: "sci-f2-c13-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah maksud komet?",
    options: [
      "Jasad besar berbatu sahaja",
      "Jasad kecil terdiri daripada campuran ais, gas dan debu yang membeku, bergerak mengelilingi Matahari",
      "Sekeping logam yang terapung di angkasa lepas",
      "Planet kecil dalam Lingkaran Asteroid",
    ],
    answerIndex: 1,
    explanation: "Komet ialah jasad kecil yang terdiri daripada campuran ais, gas dan debu yang membeku, bergerak mengelilingi Matahari pada orbitnya sendiri.",
  },
  {
    id: "sci-f2-c13-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Berapakah julat saiz meteoroid?",
    options: ["10 m hingga 1 m", "1 m hingga 1,000 km", "250,000 km", "150,000,000 km"],
    answerIndex: 0,
    explanation: "Meteoroid bersaiz pelbagai, daripada 10 m hingga 1 m.",
  },
  {
    id: "sci-f2-c13-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah dua unsur logam utama yang terdapat dalam meteoroid dan asteroid?",
    options: ["Emas dan perak", "Besi dan nikel", "Aluminium dan kuprum", "Plumbum dan zink"],
    answerIndex: 1,
    explanation: "Meteoroid dan asteroid terdiri daripada batu dan logam seperti besi dan nikel.",
  },
  {
    id: "sci-f2-c13-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Berapakah suhu permukaan meteoroid di angkasa lepas?",
    options: ["Kira-kira 0°C", "Kira-kira −73°C", "Kira-kira 100°C", "Kira-kira −200°C"],
    answerIndex: 0,
    explanation: "Suhu permukaan meteoroid di angkasa lepas kira-kira 0°C.",
  },
  {
    id: "sci-f2-c13-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Berapakah julat saiz asteroid?",
    options: ["1 m hingga 1,000 km", "10 m hingga 1 m", "250,000 km", "Lebih daripada 1,000,000 km"],
    answerIndex: 0,
    explanation: "Asteroid bersaiz daripada 1 m hingga 1,000 km.",
  },
  {
    id: "sci-f2-c13-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Di antara orbit planet manakah Lingkaran Asteroid terletak?",
    options: [
      "Antara orbit Bumi dan Marikh",
      "Antara orbit Marikh dan Musytari",
      "Antara orbit Musytari dan Zuhal",
      "Antara orbit Zuhal dan Uranus",
    ],
    answerIndex: 1,
    explanation: "Lingkaran Asteroid terletak antara orbit Marikh dan Musytari.",
  },
  {
    id: "sci-f2-c13-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Asteroid juga dikenali sebagai...",
    options: ["Bintang kecil", "Planet kecil", "Galaksi kecil", "Bulan kecil"],
    answerIndex: 1,
    explanation: "Asteroid juga dikenali sebagai \"planet kecil\".",
  },
  {
    id: "sci-f2-c13-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah dua bahagian utama komet?",
    options: ["Nukleus dan teras", "Kepala dan ekor", "Permukaan dan inti", "Lapisan dan zarah"],
    answerIndex: 1,
    explanation: "Komet terdiri daripada dua bahagian utama: kepala dan ekor.",
  },
  {
    id: "sci-f2-c13-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah perbezaan utama antara meteoroid dan meteor?",
    options: [
      "Meteoroid ialah objek di angkasa lepas, meteor ialah meteoroid yang terbakar memasuki atmosfera Bumi",
      "Meteor ialah objek di angkasa lepas, meteoroid ialah objek yang sampai ke permukaan Bumi",
      "Tidak ada perbezaan, keduanya sama",
      "Meteoroid hanya wujud di Lingkaran Kuiper",
    ],
    answerIndex: 0,
    explanation: "Meteoroid ialah serpihan batu/logam di angkasa lepas. Apabila ia memasuki atmosfera Bumi dan terbakar, ia dipanggil meteor; jika sampai ke permukaan Bumi ia menjadi meteorit.",
  },
  {
    id: "sci-f2-c13-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Bagaimanakah meteoroid dan asteroid berkaitan antara satu sama lain?",
    options: [
      "Meteoroid berasal daripada serpihan asteroid dan komet",
      "Asteroid berasal daripada serpihan meteoroid",
      "Kedua-duanya tidak berkaitan",
      "Asteroid adalah meteoroid yang sudah jatuh ke Bumi",
    ],
    answerIndex: 0,
    explanation: "Meteoroid berasal daripada serpihan asteroid dan komet.",
  },
  {
    id: "sci-f2-c13-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah kelajuan purata pergerakan asteroid mengelilingi Matahari?",
    options: ["10 km s⁻¹", "25 km s⁻¹", "42 km s⁻¹", "70 km s⁻¹"],
    answerIndex: 1,
    explanation: "Asteroid bergerak mengelilingi Matahari pada kelajuan purata 25 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah kelajuan meteoroid yang paling pantas bergerak?",
    options: ["10 km s⁻¹", "25 km s⁻¹", "42 km s⁻¹", "150 km s⁻¹"],
    answerIndex: 2,
    explanation: "Meteoroid paling pantas bergerak pada kelajuan 42 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Namakan empat asteroid besar yang dinyatakan dalam nota.",
    options: [
      "Ceres, Pallas, Juno dan Vesta",
      "Halley, Encke, Hale-Bopp dan Tempel",
      "Apollo, Amor, Aten dan Icarus",
      "Hoba, Arizona, Namibia dan Grootfontein",
    ],
    answerIndex: 0,
    explanation: "Asteroid besar seperti Ceres, Pallas, Juno dan Vesta mempunyai diameter beberapa kilometer hingga 1,000 kilometer.",
  },
  {
    id: "sci-f2-c13-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Berapakah panjang maksimum ekor komet?",
    options: ["250,000 km", "1,000 km", "150,000,000 km", "80,000 km"],
    answerIndex: 2,
    explanation: "Panjang ekor komet boleh mencapai 150,000,000 km.",
  },
  {
    id: "sci-f2-c13-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Berapakah saiz maksimum kepala komet?",
    options: ["250,000 km", "1,000 km", "150,000,000 km", "1.2 km"],
    answerIndex: 0,
    explanation: "Saiz kepala komet boleh mencapai 250,000 km.",
  },
  {
    id: "sci-f2-c13-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah bentuk orbit komet mengelilingi Matahari?",
    options: ["Bulat sempurna", "Elips", "Garis lurus", "Heliks"],
    answerIndex: 1,
    explanation: "Komet bergerak mengelilingi Matahari pada orbit elipsnya sendiri.",
  },
  {
    id: "sci-f2-c13-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah julat kelajuan purata pergerakan komet?",
    options: ["10 km s⁻¹ hingga 70 km s⁻¹", "25 km s⁻¹ tetap", "42 km s⁻¹ tetap", "100 km s⁻¹ hingga 200 km s⁻¹"],
    answerIndex: 0,
    explanation: "Komet bergerak pada julat kelajuan purata 10 km s⁻¹ hingga 70 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah komposisi kepala dan ekor komet?",
    options: [
      "Gas dan air yang membeku menjadi ais, debu dan zarah berbatu",
      "Besi dan nikel pejal sahaja",
      "Hidrogen cecair sahaja",
      "Batu granit dan marmar",
    ],
    answerIndex: 0,
    explanation: "Komet terdiri daripada gas dan air yang membeku menjadi ais, debu dan zarah berbatu.",
  },
  {
    id: "sci-f2-c13-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Mengapakah asteroid mempunyai suhu permukaan yang lebih sejuk (kira-kira −73°C) berbanding meteoroid (kira-kira 0°C)?",
    options: [
      "Kerana asteroid lebih jauh daripada Matahari berbanding kebanyakan meteoroid yang dijumpai berhampiran Bumi",
      "Kerana asteroid diperbuat daripada bahan yang berbeza sepenuhnya",
      "Kerana asteroid sentiasa berada dalam bayang-bayang Bumi",
      "Suhu kedua-duanya adalah sama, tidak ada perbezaan",
    ],
    answerIndex: 0,
    explanation: "Asteroid kebanyakannya berada dalam Lingkaran Asteroid antara Marikh dan Musytari, lebih jauh daripada Matahari berbanding meteoroid yang sering ditemui berhampiran orbit dalam, sehingga suhu permukaannya lebih sejuk.",
  },
  {
    id: "sci-f2-c13-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah kepentingan saintis memantau orbit asteroid secara berterusan?",
    options: [
      "Untuk memastikan orbit asteroid berada pada jarak selamat daripada orbit Bumi dan mengeluarkan amaran jika ada risiko perlanggaran",
      "Untuk mengira jumlah asteroid yang wujud di alam semesta",
      "Untuk menentukan warna asteroid",
      "Untuk membuktikan asteroid tidak mempunyai logam",
    ],
    answerIndex: 0,
    explanation: "Saintis memantau asteroid untuk memastikan orbitnya berada pada jarak selamat daripada orbit Bumi; amaran dikeluarkan jika terdapat risiko perlanggaran, dan asteroid berbahaya boleh dimusnahkan atau diubah arahnya.",
  },
  {
    id: "sci-f2-c13-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah bukti yang dikaitkan dengan kepupusan dinosaur menurut pakar paleontologi?",
    options: [
      "Perlanggaran asteroid berukuran 10 km dengan permukaan Bumi",
      "Letupan komet Halley berhampiran Bumi",
      "Pertembungan dua meteoroid kecil di angkasa lepas",
      "Perubahan orbit Bumi secara mendadak",
    ],
    answerIndex: 0,
    explanation: "Pakar paleontologi mempercayai kepupusan dinosaur disebabkan oleh perlanggaran asteroid berukuran 10 km dengan permukaan Bumi.",
  },
  {
    id: "sci-f2-c13-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah peristiwa yang berlaku pada tahun 1994 antara komet Shoemaker-Levy 9 dan Musytari, dan mengapa peristiwa ini penting?",
    options: [
      "Perlanggaran langsung pertama komet dengan objek dalam sistem suria yang pernah direkodkan",
      "Komet itu menjadi asteroid selepas melepasi Musytari",
      "Musytari menarik komet itu ke dalam Lingkaran Asteroid",
      "Ia adalah kali pertama meteoroid jatuh ke Musytari",
    ],
    answerIndex: 0,
    explanation: "Perlanggaran langsung pertama komet dengan objek dalam sistem suria berlaku pada tahun 1994, antara komet Shoemaker-Levy 9 dengan Musytari — peristiwa ini penting kerana ia membuktikan secara langsung bahawa perlanggaran sebegini boleh berlaku dan dipantau.",
  },
  {
    id: "sci-f2-c13-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Komet Halley terakhir dilihat melintasi Bumi pada tahun 1986. Berdasarkan kitaran orbitnya, pada tahun bilakah ia dijangka kelihatan semula?",
    options: ["2030", "2050", "2061", "2086"],
    answerIndex: 2,
    explanation: "Komet Halley terakhir dilihat melintasi Bumi pada tahun 1986 dan dijangka melintasi Bumi semula pada tahun 2061.",
  },
  {
    id: "sci-f2-c13-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Meteorit Hoba dijumpai berhampiran Grootfontein, Namibia pada tahun 1920. Mengapakah ia dianggap istimewa dalam kajian sains angkasa lepas?",
    options: [
      "Ia merupakan meteorit terbesar yang pernah direkodkan di dunia",
      "Ia adalah meteorit pertama yang dijumpai di Bumi",
      "Ia adalah satu-satunya meteorit yang mengandungi ais",
      "Ia membawa kepada penemuan Lingkaran Asteroid",
    ],
    answerIndex: 0,
    explanation: "Meteorit Hoba ialah meteorit terbesar yang pernah direkodkan di dunia, dipercayai jatuh ke Bumi kira-kira 80,000 tahun lalu.",
  },
  {
    id: "sci-f2-c13-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Kawah meteorit di Arizona, Amerika Syarikat berdiameter kira-kira 1.2 km dan terbentuk kira-kira 50,000 tahun lalu. Apakah kesimpulan yang boleh dibuat tentang hubungan antara saiz objek angkasa dengan kesan perlanggaran di Bumi?",
    options: [
      "Objek angkasa walaupun kecil boleh meninggalkan kesan kekal yang besar di permukaan Bumi akibat tenaga perlanggaran yang tinggi",
      "Hanya objek bersaiz lebih daripada 1,000 km mampu membentuk kawah",
      "Kawah hanya terbentuk akibat letupan gunung berapi, bukan perlanggaran objek angkasa",
      "Saiz kawah tidak berkaitan dengan saiz objek yang melanggar",
    ],
    answerIndex: 0,
    explanation: "Kawah Arizona menunjukkan bahawa perlanggaran objek angkasa, walaupun bukan yang terbesar, mampu menghasilkan kesan fizikal kekal yang besar akibat tenaga kinetik yang tinggi semasa perlanggaran.",
  },
  {
    id: "sci-f2-c13-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Orbit Apollo, Amor dan Aten dianggap berisiko lebih tinggi berbanding asteroid lain dalam Lingkaran Asteroid. Mengapa?",
    options: [
      "Kerana orbitnya boleh bersilang dengan orbit Bumi, di luar Lingkaran Asteroid",
      "Kerana ia bergerak lebih perlahan daripada asteroid lain",
      "Kerana ia diperbuat daripada bahan yang lebih ringan",
      "Kerana ia sentiasa berada jauh daripada Matahari",
    ],
    answerIndex: 0,
    explanation: "Orbit Apollo, Amor dan Aten adalah contoh orbit asteroid di luar Lingkaran Asteroid yang boleh bersilang dengan orbit Bumi, meningkatkan risiko perlanggaran berbanding asteroid yang kekal dalam Lingkaran Asteroid.",
  },
  {
    id: "sci-f2-c13-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Apakah peranan Agensi Angkasa Negara (ANGKASA) berkaitan dengan ancaman objek angkasa seperti asteroid?",
    options: [
      "Bertanggungjawab menggerakkan dan memantau pembangunan sains angkasa lepas di Malaysia",
      "Hanya menguruskan pelancaran satelit komersial",
      "Mengawal harga bahan logam yang diimport dari angkasa lepas",
      "Tidak berkaitan dengan pemantauan objek angkasa",
    ],
    answerIndex: 0,
    explanation: "Agensi Angkasa Negara (ANGKASA) bertanggungjawab menggerakkan dan memantau pembangunan sains angkasa lepas di Malaysia, termasuk usaha berkaitan pemantauan objek angkasa.",
  },
  {
    id: "sci-f2-c13-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "bm",
    question: "Berdasarkan ciri-ciri komposisi, saiz dan orbit, mengapakah meteoroid, asteroid dan komet dikategorikan sebagai objek yang berbeza walaupun semuanya bergerak dalam sistem suria?",
    options: [
      "Kerana saiz, komposisi bahan dan jenis orbitnya yang berbeza membezakan ciri fizikal dan pergerakan setiap objek",
      "Kerana hanya nama yang membezakan ketiga-tiganya, ciri fizikalnya adalah sama",
      "Kerana hanya komet yang bergerak mengelilingi Matahari",
      "Kerana meteoroid dan asteroid tidak wujud dalam sistem suria yang sama dengan komet",
    ],
    answerIndex: 0,
    explanation: "Meteoroid (serpihan kecil batu/logam), asteroid (jasad besar berbatu/logam dalam Lingkaran Asteroid) dan komet (jasad ais/gas/debu berorbit elips) mempunyai saiz, komposisi dan ciri orbit yang berbeza, menjadikan setiap satu kategori objek sistem suria yang tersendiri.",
  },
];
