import type { QuizQuestion } from "@/data/content";

export const scienceF2C13QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c13-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the meaning of a meteoroid?",
    options: [
      "A floating piece of stone and metal that moves in space",
      "A large metal and rocky body that travels around the Sun in its own orbit",
      "A small body made up of a mixture of ice, gas and frozen dust",
      "A star that is very small and does not emit light",
    ],
    answerIndex: 0,
    explanation: "A meteoroid is a floating piece of stone and metal that moves in space.",
  },
  {
    id: "sci-f2-c13-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the meaning of an asteroid?",
    options: [
      "A small body of frozen ice, gas and dust",
      "A large metal and rocky body that travels around the Sun in its own orbit",
      "A rock fragment that burns up in Earth's atmosphere",
      "A small piece of rock that reaches the Earth's surface",
    ],
    answerIndex: 1,
    explanation: "An asteroid is a large metal and rocky body that travels around the Sun in its own orbit.",
  },
  {
    id: "sci-f2-c13-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the meaning of a comet?",
    options: [
      "A large rocky body only",
      "A small body made up of a mixture of ice, gas and frozen dust, travelling around the Sun",
      "A piece of metal floating in outer space",
      "A small planet within the asteroid belt",
    ],
    answerIndex: 1,
    explanation: "A comet is a small body made up of a mixture of ice, gas and frozen dust, travelling around the Sun in its own orbit.",
  },
  {
    id: "sci-f2-c13-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the size range of a meteoroid?",
    options: ["10 m to 1 m", "1 m to 1,000 km", "250,000 km", "150,000,000 km"],
    answerIndex: 0,
    explanation: "A meteoroid appears in various sizes, from 10 m to 1 m.",
  },
  {
    id: "sci-f2-c13-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What are the two main metals found in meteoroids and asteroids?",
    options: ["Gold and silver", "Iron and nickel", "Aluminium and copper", "Lead and zinc"],
    answerIndex: 1,
    explanation: "Meteoroids and asteroids are made up of stones and metals such as iron and nickel.",
  },
  {
    id: "sci-f2-c13-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the surface temperature of a meteoroid in outer space?",
    options: ["About 0°C", "About −73°C", "About 100°C", "About −200°C"],
    answerIndex: 0,
    explanation: "The surface temperature of a meteoroid in outer space is about 0°C.",
  },
  {
    id: "sci-f2-c13-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the size range of an asteroid?",
    options: ["1 m to 1,000 km", "10 m to 1 m", "250,000 km", "More than 1,000,000 km"],
    answerIndex: 0,
    explanation: "An asteroid's size starts from 1 m to 1,000 km.",
  },
  {
    id: "sci-f2-c13-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "Between which two planetary orbits is the asteroid belt located?",
    options: [
      "Between the orbits of Earth and Mars",
      "Between the orbits of Mars and Jupiter",
      "Between the orbits of Jupiter and Saturn",
      "Between the orbits of Saturn and Uranus",
    ],
    answerIndex: 1,
    explanation: "Asteroids form an asteroid belt between the orbits of Mars and Jupiter.",
  },
  {
    id: "sci-f2-c13-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "Asteroids are also known as...",
    options: ["Small stars", "Small planets", "Small galaxies", "Small moons"],
    answerIndex: 1,
    explanation: "Asteroids are also known as small planets.",
  },
  {
    id: "sci-f2-c13-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What are the two main parts of a comet?",
    options: ["Nucleus and core", "Head and tail", "Surface and core", "Layer and particle"],
    answerIndex: 1,
    explanation: "A comet consists of two main parts: a head and a tail.",
  },
  {
    id: "sci-f2-c13-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the main difference between a meteoroid and a meteor?",
    options: [
      "A meteoroid is an object in outer space; a meteor is a meteoroid that burns up entering Earth's atmosphere",
      "A meteor is an object in outer space; a meteoroid is an object that reaches the Earth's surface",
      "There is no difference, they are the same",
      "Meteoroids only exist in the Kuiper belt",
    ],
    answerIndex: 0,
    explanation: "A meteoroid is a rock/metal fragment in outer space. When it enters Earth's atmosphere and burns up, it is called a meteor; if it reaches the Earth's surface, it becomes a meteorite.",
  },
  {
    id: "sci-f2-c13-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "How are meteoroids and asteroids related to each other?",
    options: [
      "Meteoroids originate from fragments of asteroids and comets",
      "Asteroids originate from fragments of meteoroids",
      "They are not related at all",
      "Asteroids are meteoroids that have already fallen to Earth",
    ],
    answerIndex: 0,
    explanation: "Meteoroids originate from fragments of asteroids and comets.",
  },
  {
    id: "sci-f2-c13-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the average speed of an asteroid travelling around the Sun?",
    options: ["10 km s⁻¹", "25 km s⁻¹", "42 km s⁻¹", "70 km s⁻¹"],
    answerIndex: 1,
    explanation: "An asteroid travels around the Sun at an average speed of 25 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the speed of the fastest moving meteoroid?",
    options: ["10 km s⁻¹", "25 km s⁻¹", "42 km s⁻¹", "150 km s⁻¹"],
    answerIndex: 2,
    explanation: "The fastest meteoroid travels at 42 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "Name four large asteroids mentioned in the notes.",
    options: [
      "Ceres, Pallas, Juno and Vesta",
      "Halley, Encke, Hale-Bopp and Tempel",
      "Apollo, Amor, Aten and Icarus",
      "Hoba, Arizona, Namibia and Grootfontein",
    ],
    answerIndex: 0,
    explanation: "Large asteroids such as Ceres, Pallas, Juno and Vesta have diameters of a few kilometres to 1,000 kilometres.",
  },
  {
    id: "sci-f2-c13-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the maximum length of a comet's tail?",
    options: ["250,000 km", "1,000 km", "150,000,000 km", "80,000 km"],
    answerIndex: 2,
    explanation: "The length of the tail of a comet can reach up to 150,000,000 km.",
  },
  {
    id: "sci-f2-c13-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the maximum size of a comet's head?",
    options: ["250,000 km", "1,000 km", "150,000,000 km", "1.2 km"],
    answerIndex: 0,
    explanation: "The size of the head of a comet can reach up to 250,000 km.",
  },
  {
    id: "sci-f2-c13-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the shape of a comet's orbit around the Sun?",
    options: ["A perfect circle", "Elliptical", "A straight line", "A helix"],
    answerIndex: 1,
    explanation: "A comet travels around the Sun in its own elliptical orbit.",
  },
  {
    id: "sci-f2-c13-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the average speed range of a comet's movement?",
    options: ["10 km s⁻¹ to 70 km s⁻¹", "A constant 25 km s⁻¹", "A constant 42 km s⁻¹", "100 km s⁻¹ to 200 km s⁻¹"],
    answerIndex: 0,
    explanation: "A comet travels at an average speed range of 10 km s⁻¹ to 70 km s⁻¹.",
  },
  {
    id: "sci-f2-c13-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the composition of a comet's head and tail?",
    options: [
      "Gas and water that freeze into ice, dust and rocky particles",
      "Solid iron and nickel only",
      "Liquid hydrogen only",
      "Granite and marble rock",
    ],
    answerIndex: 0,
    explanation: "A comet comprises gas and water that freeze into ice, dust and rocky particles.",
  },
  {
    id: "sci-f2-c13-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "Why does an asteroid have a colder surface temperature (about −73°C) compared to a meteoroid (about 0°C)?",
    options: [
      "Because asteroids are generally farther from the Sun than most meteoroids found near Earth",
      "Because asteroids are made of completely different materials",
      "Because asteroids are always in Earth's shadow",
      "The temperatures are actually the same, there is no difference",
    ],
    answerIndex: 0,
    explanation: "Asteroids are mostly located within the asteroid belt between Mars and Jupiter, farther from the Sun than meteoroids commonly found near the inner orbits, resulting in a colder surface temperature.",
  },
  {
    id: "sci-f2-c13-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "Why is it important for scientists to continuously monitor asteroid orbits?",
    options: [
      "To ensure asteroid orbits are at a safe distance from Earth's orbit and issue warnings if there is a risk of collision",
      "To count the total number of asteroids that exist in the universe",
      "To determine the colour of asteroids",
      "To prove that asteroids do not contain metal",
    ],
    answerIndex: 0,
    explanation: "Scientists monitor asteroids to ensure their orbits remain at a safe distance from Earth's orbit; warnings are issued if there is a risk of collision, and dangerous asteroids may be destroyed or have their course changed.",
  },
  {
    id: "sci-f2-c13-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What evidence is linked to the extinction of dinosaurs according to paleontologists?",
    options: [
      "The collision of a 10 km sized asteroid with the surface of the Earth",
      "An explosion of Halley's Comet near the Earth",
      "A collision between two small meteoroids in outer space",
      "A sudden change in Earth's orbit",
    ],
    answerIndex: 0,
    explanation: "Paleontologists believe the extinction of dinosaurs was caused by the collision of a 10 km sized asteroid with the surface of the Earth.",
  },
  {
    id: "sci-f2-c13-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What event occurred in 1994 between comet Shoemaker-Levy 9 and Jupiter, and why is it significant?",
    options: [
      "The first ever recorded direct collision of a comet with an object in the solar system",
      "The comet turned into an asteroid after passing Jupiter",
      "Jupiter pulled the comet into the asteroid belt",
      "It was the first time a meteoroid fell onto Jupiter",
    ],
    answerIndex: 0,
    explanation: "The first direct collision of a comet with objects in the solar system occurred in 1994, between the Shoemaker-Levy 9 comet and Jupiter — significant because it directly demonstrated such collisions can occur and be observed.",
  },
  {
    id: "sci-f2-c13-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "Halley's Comet was last seen passing the Earth in 1986. Based on its orbital cycle, in what year is it expected to be seen again?",
    options: ["2030", "2050", "2061", "2086"],
    answerIndex: 2,
    explanation: "The Halley Comet was last seen passing the Earth in 1986 and is expected to pass the Earth again in 2061.",
  },
  {
    id: "sci-f2-c13-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "The Hoba Meteorite was discovered near Grootfontein, Namibia, in 1920. Why is it considered special in the study of space science?",
    options: [
      "It is the largest meteorite ever recorded in the world",
      "It is the first meteorite ever found on Earth",
      "It is the only meteorite known to contain ice",
      "It led to the discovery of the asteroid belt",
    ],
    answerIndex: 0,
    explanation: "The Hoba Meteorite is the largest meteorite ever recorded in the world, believed to have fallen to Earth approximately 80,000 years ago.",
  },
  {
    id: "sci-f2-c13-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "The meteorite crater in Arizona, United States, has a diameter of approximately 1.2 km and formed approximately 50,000 years ago. What conclusion can be drawn about the relationship between the size of a space object and its impact on Earth?",
    options: [
      "Even relatively small space objects can leave large, lasting impacts on Earth's surface due to the high energy of collision",
      "Only objects larger than 1,000 km can form craters",
      "Craters only form from volcanic eruptions, not space object collisions",
      "Crater size has no relationship to the size of the colliding object",
    ],
    answerIndex: 0,
    explanation: "The Arizona crater shows that the collision of a space object, even one that is not extremely large, can produce major lasting physical effects due to the high kinetic energy involved during impact.",
  },
  {
    id: "sci-f2-c13-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "The orbits of Apollo, Amor and Aten are considered higher risk compared to other asteroids within the asteroid belt. Why?",
    options: [
      "Because their orbits can intersect with Earth's orbit, lying outside the asteroid belt",
      "Because they move more slowly than other asteroids",
      "Because they are made of lighter materials",
      "Because they always stay far from the Sun",
    ],
    answerIndex: 0,
    explanation: "The orbits of Apollo, Amor and Aten are examples of asteroid orbits outside the asteroid belt that can intersect with Earth's orbit, increasing collision risk compared to asteroids that remain within the asteroid belt.",
  },
  {
    id: "sci-f2-c13-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "What is the role of the National Space Agency (ANGKASA) in relation to threats from space objects such as asteroids?",
    options: [
      "It is responsible for driving and monitoring the development of space science in Malaysia",
      "It only manages commercial satellite launches",
      "It controls the prices of imported space metals",
      "It has no role in monitoring space objects",
    ],
    answerIndex: 0,
    explanation: "The National Space Agency (ANGKASA) is responsible for driving and monitoring the development of space science in Malaysia, including efforts related to monitoring space objects.",
  },
  {
    id: "sci-f2-c13-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 13",
    lang: "dlp",
    question: "Based on their composition, size and orbit, why are meteoroids, asteroids and comets categorised as different objects even though all of them move within the solar system?",
    options: [
      "Because differences in size, material composition and orbit type distinguish the physical characteristics and movement of each object",
      "Because only the names differ; their physical characteristics are exactly the same",
      "Because only comets travel around the Sun",
      "Because meteoroids and asteroids do not exist in the same solar system as comets",
    ],
    answerIndex: 0,
    explanation: "Meteoroids (small rock/metal fragments), asteroids (large rocky/metal bodies in the asteroid belt) and comets (ice/gas/dust bodies with elliptical orbits) differ in size, composition and orbital characteristics, making each a distinct category of solar system object.",
  },
];
