import type { QuizQuestion } from "@/data/types";

function q(
  number: number,
  difficulty: "Easy" | "Medium" | "Hard",
  question: string,
  options: [string, string, string, string],
  answerIndex: number,
  explanation: string,
): QuizQuestion {
  const correct = options[answerIndex];
  const rotation = (number - 1) % options.length;
  const rotatedOptions = [
    ...options.slice(rotation),
    ...options.slice(0, rotation),
  ] as [string, string, string, string];

  return {
    id: `geo-f3-c1-q${number}`,
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty,
    question,
    options: rotatedOptions,
    answerIndex: rotatedOptions.indexOf(correct),
    explanation,
  };
}

export const geographyF3C1Quizzes: QuizQuestion[] = [
  q(
    1,
    "Easy",
    "Apakah maksud jadual dalam Geografi?",
    [
      "Persembahan data dan maklumat secara tersusun",
      "Lukisan bentuk muka bumi menggunakan simbol",
      "Graf yang menggabungkan suhu dan hujan",
      "Kaedah menentukan arah menggunakan kompas",
    ],
    0,
    "Jadual menyusun data dan maklumat supaya lebih mudah dibaca, dibandingkan dan ditafsir.",
  ),
  q(
    2,
    "Easy",
    "Antara berikut, yang manakah merupakan tiga ciri utama sebuah jadual?",
    [
      "Tajuk, data dan sumber",
      "Tajuk, skala dan arah utara",
      "Paksi, simbol dan petunjuk",
      "Sektor, sudut dan peratus",
    ],
    0,
    "Jadual yang lengkap mempunyai tajuk, data atau maklumat, serta sumber yang sesuai.",
  ),
  q(
    3,
    "Easy",
    "Apakah fungsi tajuk dalam jadual?",
    [
      "Menjelaskan perkara yang dipersembahkan",
      "Menentukan nilai paling tinggi secara automatik",
      "Menukar data kepada peratus",
      "Menunjukkan arah perubahan data",
    ],
    0,
    "Tajuk memberitahu pembaca perkara, tempat atau tempoh yang berkaitan dengan data.",
  ),
  q(
    4,
    "Easy",
    "Kaedah pengumpulan maklumat yang melibatkan melihat keadaan sebenar dan mencatat dapatan dikenali sebagai:",
    ["Pemerhatian", "Temu bual", "Banci", "Soal selidik"],
    0,
    "Pemerhatian ialah kaedah mendapatkan maklumat dengan melihat dan mencatat perkara yang berkaitan secara langsung.",
  ),
  q(
    5,
    "Easy",
    "Kaedah manakah paling sesuai untuk mendapatkan pendapat atau penjelasan seseorang secara langsung?",
    ["Temu bual", "Pemerhatian", "Banci", "Rujukan kepustakaan"],
    0,
    "Temu bual sesuai digunakan apabila maklumat perlu diperoleh secara lisan melalui soal jawab.",
  ),
  q(
    6,
    "Easy",
    "Kaedah manakah paling sesuai untuk menghitung jumlah penduduk sesebuah kawasan?",
    ["Banci", "Temu bual", "Pemerhatian", "Rujukan kepustakaan"],
    0,
    "Banci digunakan untuk mengumpul maklumat dengan menghitung keseluruhan jumlah dalam sesuatu kumpulan atau kawasan.",
  ),
  q(
    7,
    "Easy",
    "Apakah ciri utama kaedah soal selidik?",
    [
      "Borang soalan diedarkan kepada responden",
      "Maklumat diperoleh hanya melalui pemerhatian",
      "Semua penduduk dihitung seorang demi seorang",
      "Data diperoleh daripada bahan yang telah diterbitkan",
    ],
    0,
    "Soal selidik menggunakan borang soalan yang diedarkan kepada responden dan dikumpulkan semula selepas dijawab.",
  ),
  q(
    8,
    "Easy",
    "Jika maklumat yang diperlukan sudah terdapat dalam buku, majalah atau laman rasmi, kaedah yang paling sesuai ialah:",
    ["Rujukan kepustakaan", "Banci", "Temu bual", "Pemerhatian"],
    0,
    "Rujukan kepustakaan mendapatkan maklumat daripada bahan yang telah diterbitkan.",
  ),
  q(
    9,
    "Easy",
    "Antara berikut, yang manakah merupakan jenis graf yang dipelajari dalam Bab Jadual dan Graf?",
    ["Graf bar mudah", "Peta topografi", "Carta alir", "Rajah blok"],
    0,
    "Bab ini merangkumi graf bar mudah, graf garisan mudah dan graf gabungan.",
  ),
  q(
    10,
    "Easy",
    "Apakah fungsi utama paksi menegak dalam graf bar mudah?",
    [
      "Menunjukkan nilai atau kuantiti",
      "Menunjukkan kategori yang dibandingkan",
      "Menunjukkan sumber data",
      "Menunjukkan arah utara",
    ],
    0,
    "Paksi menegak lazimnya menunjukkan nilai, bilangan atau kuantiti.",
  ),

  q(
    11,
    "Medium",
    "Apakah yang biasanya ditunjukkan pada paksi mendatar dalam graf bar mudah?",
    [
      "Kategori atau komponen",
      "Nilai atau bilangan",
      "Jumlah keseluruhan data",
      "Sumber maklumat",
    ],
    0,
    "Paksi mendatar biasanya memaparkan kategori atau komponen yang hendak dibandingkan.",
  ),
  q(
    12,
    "Medium",
    "Apakah maksud garisan yang semakin menaik dalam graf garisan?",
    [
      "Nilai data menunjukkan peningkatan",
      "Nilai data menunjukkan penurunan",
      "Nilai data tidak berubah",
      "Nilai data berubah secara turun naik",
    ],
    0,
    "Garisan yang bergerak ke atas menunjukkan nilai meningkat.",
  ),
  q(
    13,
    "Medium",
    "Apakah maksud garisan yang semakin menurun dalam graf garisan?",
    [
      "Nilai data menunjukkan penurunan",
      "Nilai data menunjukkan peningkatan",
      "Nilai data tidak berubah",
      "Nilai data berubah secara turun naik",
    ],
    0,
    "Garisan yang bergerak ke bawah menunjukkan nilai data menurun.",
  ),
  q(
    14,
    "Medium",
    "Apakah maksud garisan mendatar dalam graf garisan?",
    [
      "Nilai data tidak berubah",
      "Nilai data meningkat dengan cepat",
      "Nilai data menurun dengan cepat",
      "Nilai data turun naik",
    ],
    0,
    "Garisan mendatar menunjukkan nilai kekal sama dalam tempoh berkenaan.",
  ),
  q(
    15,
    "Medium",
    "Garisan yang sangat curam pada graf garisan menunjukkan:",
    [
      "Perubahan nilai yang besar",
      "Perubahan nilai yang kecil",
      "Tiada perubahan nilai",
      "Nilai yang tidak dapat ditentukan",
    ],
    0,
    "Garisan yang curam menunjukkan perubahan nilai yang besar dalam tempoh yang singkat.",
  ),
  q(
    16,
    "Medium",
    "Garisan yang landai pada graf garisan menunjukkan:",
    [
      "Perubahan nilai yang kecil",
      "Perubahan nilai yang sangat besar",
      "Tiada data direkodkan",
      "Nilai sentiasa sifar",
    ],
    0,
    "Garisan yang landai menggambarkan perubahan nilai yang kecil atau perlahan.",
  ),
  q(
    17,
    "Medium",
    "Apakah maksud graf gabungan?",
    [
      "Gabungan graf bar mudah dan graf garisan mudah",
      "Gabungan dua graf bar sahaja",
      "Gabungan carta pai dan peta",
      "Gabungan jadual dan peta lakar",
    ],
    0,
    "Graf gabungan menggabungkan graf bar mudah dengan graf garisan mudah dalam satu persembahan.",
  ),
  q(
    18,
    "Medium",
    "Pasangan data manakah paling sesuai dipersembahkan menggunakan graf gabungan?",
    [
      "Jumlah hujan dan min suhu bulanan",
      "Bilangan murid mengikut kelas sahaja",
      "Jenis kenderaan mengikut warna sahaja",
      "Arah mata angin dan bearing",
    ],
    0,
    "Graf gabungan sesuai untuk dua set data berbeza tetapi saling berkaitan, seperti hujan dan suhu.",
  ),
  q(
    19,
    "Medium",
    "Mengapakah skala perlu dipilih dengan teliti semasa membina graf?",
    [
      "Supaya nilai dapat diplot dengan tepat",
      "Supaya semua bar mempunyai warna yang sama",
      "Supaya tajuk menjadi lebih panjang",
      "Supaya petunjuk tidak diperlukan",
    ],
    0,
    "Skala yang sesuai memastikan semua nilai dapat diplot dengan tepat dan mudah dibaca.",
  ),
  q(
    20,
    "Medium",
    "Apakah fungsi petunjuk dalam graf?",
    [
      "Menerangkan warna atau simbol bagi set data",
      "Menentukan nilai maksimum secara automatik",
      "Menggantikan tajuk graf",
      "Menunjukkan sumber data sahaja",
    ],
    0,
    "Petunjuk menerangkan warna, simbol atau corak yang mewakili set data tertentu.",
  ),

  q(
    21,
    "Hard",
    "Apakah langkah pertama yang paling tepat ketika mentafsir jadual atau graf?",
    [
      "Baca tajuk terlebih dahulu",
      "Cari nilai paling tinggi dahulu",
      "Tulis rumusan sebelum membaca data",
      "Tentukan sebab bagi setiap perubahan",
    ],
    0,
    "Tajuk perlu dibaca terlebih dahulu supaya pembaca mengetahui perkara yang sedang ditafsir.",
  ),
  q(
    22,
    "Hard",
    "Sebuah graf menunjukkan nilai 10, 14, 18, 22 dan 26 bagi lima tahun berturut-turut. Apakah trend utamanya?",
    [
      "Meningkat secara berterusan",
      "Menurun secara berterusan",
      "Tidak berubah",
      "Turun naik",
    ],
    0,
    "Setiap nilai lebih tinggi daripada tahun sebelumnya, jadi trendnya meningkat secara berterusan.",
  ),
  q(
    23,
    "Hard",
    "Dalam tafsiran graf, apakah yang dimaksudkan dengan isi tersirat?",
    [
      "Sebab atau kesan yang dihuraikan berdasarkan pola data",
      "Nilai yang boleh dibaca terus pada paksi",
      "Tajuk yang dicetak di bahagian atas graf",
      "Unit yang ditulis pada paksi menegak",
    ],
    0,
    "Isi tersirat ialah huraian seperti sebab, faktor atau kesan yang dibuat berdasarkan pola data.",
  ),
  q(
    24,
    "Hard",
    "Apakah langkah terakhir dalam mentafsir jadual atau graf?",
    [
      "Membuat rumusan keseluruhan",
      "Mengenal pasti tajuk",
      "Menyemak unit pada paksi",
      "Mencari nilai tertinggi",
    ],
    0,
    "Selepas mengenal pasti pola dan menghuraikan data, tafsiran diakhiri dengan rumusan keseluruhan.",
  ),
  q(
    25,
    "Hard",
    "Data cara murid datang ke sekolah ialah berjalan kaki 12 orang, bas 7 orang, kereta 5 orang dan basikal 4 orang. Pernyataan manakah tepat?",
    [
      "Berjalan kaki paling ramai, manakala basikal paling sedikit",
      "Bas paling ramai, manakala kereta paling sedikit",
      "Kereta paling ramai, manakala berjalan kaki paling sedikit",
      "Basikal paling ramai, manakala bas paling sedikit",
    ],
    0,
    "Nilai tertinggi ialah berjalan kaki, 12 orang, manakala nilai terendah ialah basikal, 4 orang.",
  ),
  q(
    26,
    "Hard",
    "Apakah kesan penggunaan skala yang tidak konsisten pada paksi graf?",
    [
      "Perbandingan data boleh menjadi mengelirukan",
      "Data asal akan bertambah secara automatik",
      "Jumlah kategori akan berkurang",
      "Graf akan bertukar menjadi carta pai",
    ],
    0,
    "Skala yang tidak konsisten boleh memesongkan gambaran perubahan dan menyebabkan pembaca tersalah tafsir.",
  ),
  q(
    27,
    "Hard",
    "Apakah masalah utama jika unit pada paksi graf tidak dinyatakan?",
    [
      "Pembaca tidak dapat menentukan ukuran sebenar nilai",
      "Pembaca tidak dapat melihat warna bar",
      "Tajuk graf akan menjadi salah",
      "Bilangan kategori akan berubah",
    ],
    0,
    "Tanpa unit, pembaca tidak tahu sama ada nilai mewakili orang, mm, °C atau ukuran lain.",
  ),
  q(
    28,
    "Hard",
    "Apakah ciri yang membezakan graf bar mudah daripada histogram?",
    [
      "Graf bar mempunyai ruang antara kategori yang berasingan",
      "Graf bar tidak menggunakan paksi",
      "Graf bar hanya menunjukkan perubahan mengikut masa",
      "Graf bar mesti mempunyai dua paksi menegak",
    ],
    0,
    "Graf bar menunjukkan kategori berasingan, jadi bar lazimnya dipisahkan oleh ruang.",
  ),
  q(
    29,
    "Hard",
    "Mengapakah titik-titik dalam graf garisan disambungkan?",
    [
      "Untuk menunjukkan arah perubahan antara satu tempoh dengan tempoh berikutnya",
      "Untuk menunjukkan setiap kategori tidak berkaitan",
      "Untuk menggantikan skala pada paksi menegak",
      "Untuk menunjukkan jumlah keseluruhan sentiasa 100%",
    ],
    0,
    "Sambungan antara titik membantu pembaca melihat arah dan kadar perubahan data dari satu tempoh ke tempoh seterusnya.",
  ),
  q(
    30,
    "Hard",
    "Dalam graf gabungan suhu dan hujan bulanan, mengapakah dua paksi menegak boleh digunakan?",
    [
      "Kerana suhu dan hujan menggunakan unit yang berbeza",
      "Kerana kedua-dua data mesti mempunyai nilai yang sama",
      "Kerana graf gabungan tidak mempunyai paksi mendatar",
      "Kerana satu paksi digunakan untuk tajuk dan satu lagi untuk sumber",
    ],
    0,
    "Suhu dan hujan menggunakan unit serta julat berbeza, jadi dua paksi menegak membantu kedua-duanya dipersembahkan dengan tepat.",
  ),
];
