import type { QuizQuestion } from "@/data/types";

export const geographyF3C1Quizzes: QuizQuestion[] = [
  {
    id: "geo-f3-c1-bm-set-a-q9",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah definisi bagi jadual mengikut buku teks?",
    options: [
      "Cara mempersembahkan data secara tersusun supaya mudah dibaca",
      "Rajah yang terdiri daripada bar untuk menunjukkan pertalian",
      "Alatan visual untuk mengira data penduduk",
      "Satu proses pengumpulan data mentah melalui rujukan",
    ],
    answerIndex: 0,
  },
  {
    id: "geo-f3-c1-bm-set-a-q10",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah fungsi utama paksi menegak dalam sebuah graf?",
    options: [
      "Menunjukkan tajuk graf",
      "Menunjukkan kuantiti sesuatu komponen",
      "Menunjukkan jenis pengangkutan murid",
      "Menunjukkan sumber data",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q11",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah yang biasanya ditunjukkan pada paksi mendatar dalam graf?",
    options: [
      "Ketinggian bar",
      "Kategori atau komponen yang dikaji",
      "Skala ukuran",
      "Jumlah keseluruhan data",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q12",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Garisan mendatar dalam sesebuah graf garisan membawa maksud:",
    options: [
      "Berlaku peningkatan data yang drastik",
      "Berlaku penurunan data yang drastik",
      "Tiada perubahan berlaku pada data dalam tempoh tertentu",
      "Perubahan data berlaku secara perlahan",
    ],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q13",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Apakah nama kaedah pengiraan menggunakan tanda 'garis' (tally) semasa membina jadual kekerapan?",
    options: ["Gundalan", "Peratus", "Nisbah", "Purata"],
    answerIndex: 0,
  },
  {
    id: "geo-f3-c1-bm-set-a-q14",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Istilah 'Guna tenaga' dalam geografi merujuk kepada:",
    options: [
      "Jumlah penduduk yang tidak bekerja",
      "Penggunaan tenaga manusia dalam kegiatan ekonomi",
      "Jumlah tenaga elektrik yang digunakan kilang",
      "Penggunaan mesin dalam pertanian",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q15",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah ketepatan skala sangat kritikal semasa membina graf?",
    options: [
      "Supaya graf nampak cantik dan berwarna-warni",
      "Untuk memastikan mesej data tidak disalah faham",
      "Supaya tajuk graf nampak lebih besar",
      "Untuk memudahkan penggunaan pembaris",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q16",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Dalam langkah mentafsir, proses mencari 'isi tersirat' bertujuan untuk:",
    options: [
      "Mengenal pasti tajuk graf",
      "Melihat nilai paling rendah",
      "Menerangkan mengapa trend data berkelakuan sedemikian",
      "Melukis semula graf yang lebih jelas",
    ],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q17",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Kaedah pengumpulan maklumat yang manakah dianggap paling mudah dan cepat dilakukan?",
    options: ["Temu Bual", "Banci", "Pemerhatian", "Soal Selidik"],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q18",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Bagi mendapatkan maklumat berkaitan berita, pendapat, atau nasihat daripada seseorang, kaedah manakah yang paling sesuai?",
    options: ["Rujukan Kepustakaan", "Banci", "Temu Bual", "Pemerhatian"],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q19",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah graf garisan mudah biasanya tidak memerlukan petunjuk?",
    options: [
      "Kerana ia mempunyai banyak garisan",
      "Kerana fokusnya hanya pada pergerakan satu garisan sahaja",
      "Kerana ia tidak mempunyai tajuk",
      "Kerana nilainya sentiasa tetap",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q20",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Dalam graf gabungan suhu dan hujan bulanan, paksi menegak di sebelah kanan biasanya mewakili:",
    options: ["Jumlah Hujan", "Bulan Januari hingga Disember", "Suhu", "Petunjuk warna"],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q21",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Graf garisan dengan garisan yang landai menggambarkan:",
    options: [
      "Perubahan data yang besar",
      "Perubahan data yang kecil",
      "Tiada perubahan data",
      "Data yang hilang",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q22",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah kegunaan utama pengkelasan maklumat di dalam jadual?",
    options: [
      "Menyukarkan pembacaan data",
      "Menghilangkan sumber maklumat",
      "Menjadikan maklumat lebih tersusun dan menarik perhatian",
      "Menambah jumlah data mentah",
    ],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q23",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Berdasarkan contoh graf gabungan Bandaraya Kuala Lumpur, bulan manakah mencatatkan hujan paling tinggi (286 mm)?",
    options: ["Januari", "Mei", "Julai", "November"],
    answerIndex: 3,
  },
  {
    id: "geo-f3-c1-bm-set-a-q24",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Agensi manakah yang biasanya membekalkan data statistik guna tenaga dan penduduk di Malaysia?",
    options: [
      "Jabatan Alam Sekitar",
      "Jabatan Perangkaan Malaysia",
      "Jabatan Meteorologi Malaysia",
      "Lembaga Peperiksaan Malaysia",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q25",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Langkah terakhir dalam mentafsir jadual dan graf ialah:",
    options: [
      "Mengenal pasti tajuk",
      "Memerhatikan paksi",
      "Membuat rumusan secara keseluruhan",
      "Menghuraikan nilai maksimum",
    ],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q26",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Apakah alat yang perlu digunakan untuk melukis paksi asas dengan teliti di atas kertas graf?",
    options: ["Jangka sudut", "Pembaris", "Jangka lukis", "Pen penanda"],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q27",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Graf bar mudah sesuai untuk data yang boleh dikira satu per satu, contohnya:",
    options: [
      "Min suhu tahunan",
      "Bilangan kereta yang melalui jalan raya",
      "Aliran perubahan penduduk",
      "Harga jualan pasaran",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q28",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Berapakah nilai peratus yang diwakili oleh keseluruhan maklumat dalam sesuatu jadual yang lengkap?",
    options: ["50%", "90%", "100%", "360%"],
    answerIndex: 2,
  },
  {
    id: "geo-f3-c1-bm-set-a-q29",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question:
      "Dalam membina graf garisan, apakah langkah yang dilakukan selepas menandakan titik-titik data?",
    options: [
      "Memadam semula semua titik",
      "Menyambungkan semua titik dengan satu garisan",
      "Melukis bar yang tinggi",
      "Memilih skala baru",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-f3-c1-bm-set-a-q30",
    subjectId: "geography",
    form: "Form 3",
    chapter: "Chapter 1",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapa murid digalakkan menyertakan sumber rujukan di bawah jadual?",
    options: [
      "Supaya jadual nampak lebih panjang",
      "Untuk membuktikan data tersebut sah dan boleh dipercayai",
      "Sebagai hiasan tambahan",
      "Untuk menggantikan tajuk jadual",
    ],
    answerIndex: 1,
  },
];
