import type { Flashcard } from "@/data/content";

export const scienceF2C4FlashcardsDLP: Flashcard[] = [
  // Set 1: Diseases & How They Spread
  {
    id: "sci-f2-c4-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is a disease?",
    back: "An abnormal condition of body or mind that causes discomfort, difficulty to function or stress to an individual.",
  },
  {
    id: "sci-f2-c4-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is an infectious disease?",
    back: "A disease caused by infection of pathogens directly through mediums and vectors; can be transmitted between individuals.",
  },
  {
    id: "sci-f2-c4-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is a non-infectious disease?",
    back: "A disease caused by genetic factor or lifestyle; cannot be transmitted between individuals.",
  },
  {
    id: "sci-f2-c4-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Give 4 examples of infectious diseases.",
    back: "Tuberculosis, flu, ringworm, dengue fever (also: tinea, leptospirosis, malaria fever, Zika fever).",
  },
  {
    id: "sci-f2-c4-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Give 4 examples of non-infectious diseases.",
    back: "Cancer, hypertension, diabetes, asthma (also: cardiovascular diseases).",
  },
  {
    id: "sci-f2-c4-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is a pathogen?",
    back: "An organism that causes disease — all viruses, and some bacteria, protozoa, fungi and worms.",
  },
  {
    id: "sci-f2-c4-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is a vector?",
    back: "An animal that transmits pathogens from one host to a new host.",
  },
  {
    id: "sci-f2-c4-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is a host?",
    back: "An organism that is infected by a pathogen and shows symptoms of the disease.",
  },
  {
    id: "sci-f2-c4-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Name 4 ways infectious diseases spread.",
    back: "Through air, water, contact, and vectors.",
  },
  {
    id: "sci-f2-c4-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Give 3 examples of airborne diseases.",
    back: "Tuberculosis, flu, SARS (also: Influenza A H1N1, chicken pox).",
  },
  {
    id: "sci-f2-c4-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Give 3 examples of waterborne diseases.",
    back: "Cholera, typhoid, amoebic dysentery.",
  },
  {
    id: "sci-f2-c4-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How are syphilis and gonorrhoea spread?",
    back: "Through sexual intercourse — pathogens are present in body fluids such as semen and vaginal fluid.",
  },
  {
    id: "sci-f2-c4-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How can HIV (which causes AIDS) be transmitted?",
    back: "Through sexual intercourse, blood, and syringe-sharing among drug addicts/patients.",
  },
  {
    id: "sci-f2-c4-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Which vector spreads dengue fever and Zika fever?",
    back: "Aedes mosquito.",
  },
  {
    id: "sci-f2-c4-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Which vector spreads malaria?",
    back: "The female Anopheles mosquito (the pathogen is Plasmodium).",
  },
  {
    id: "sci-f2-c4-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Which vector spreads leptospirosis?",
    back: "Rat (pathogen: Leptospira sp. bacteria).",
  },
  {
    id: "sci-f2-c4-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How does a mosquito spread disease to a new victim?",
    back: "A mosquito with pathogens in its salivary glands sucks blood from an infected person, then secretes saliva (preventing clotting) when biting another person, transmitting the pathogen.",
  },
  {
    id: "sci-f2-c4-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How does a fly spread disease?",
    back: "A fly that lands on dirt carries pathogens on its legs/body, then transmits them to food, which infects the person who eats the contaminated food.",
  },
  {
    id: "sci-f2-c4-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What examples show that pathogens enter through multiple body systems?",
    back: "Pathogens enter the body through the respiratory system, digestive system, excretory system and skin.",
  },
  {
    id: "sci-f2-c4-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How can the spread of mosquito-borne diseases be prevented?",
    back: "Destroy breeding places such as stagnant water, carry out fogging, and use mosquito nets or repellent.",
  },
  // Set 2: Body Defence
  {
    id: "sci-f2-c4-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is the first line of body defence?",
    back: "Skin and mucous membrane — prevents pathogens from entering the body.",
  },
  {
    id: "sci-f2-c4-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Why is the skin difficult for microorganisms to penetrate?",
    back: "The human skin is made of a tough layer; microorganisms can only enter if there is a wound or the skin is injured.",
  },
  {
    id: "sci-f2-c4-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How do sweat and sebum help the skin defend the body?",
    back: "They contain chemicals that kill microorganisms on the skin surface.",
  },
  {
    id: "sci-f2-c4-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How does the mucous membrane trap microorganisms in the respiratory tract?",
    back: "Microorganisms are filtered by nasal hairs and trapped by mucous lining the nasal cavity.",
  },
  {
    id: "sci-f2-c4-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Name 3 other body secretions that act as antiseptics.",
    back: "Earwax, tears and vaginal secretions.",
  },
  {
    id: "sci-f2-c4-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How does hydrochloric acid in the stomach help defend the body?",
    back: "It kills pathogens that enter the body with food and drink.",
  },
  {
    id: "sci-f2-c4-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is the second line of body defence?",
    back: "Phagocytosis — white blood cells engulf and digest pathogens.",
  },
  {
    id: "sci-f2-c4-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Why are the first and second lines of defence described as non-specific?",
    back: "They act against all types of pathogens in the same way, not against one particular pathogen.",
  },
  {
    id: "sci-f2-c4-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is the third line of body defence?",
    back: "The immune system — production of antibodies against pathogens.",
  },
  {
    id: "sci-f2-c4-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Why is the third line of defence described as specific?",
    back: "Each antibody acts only against the particular antigen that triggered its production.",
  },
  {
    id: "sci-f2-c4-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is an antigen?",
    back: "A foreign substance from outside the body that induces the production of antibodies.",
  },
  {
    id: "sci-f2-c4-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is an antibody?",
    back: "A protein produced by white blood cells into the bloodstream in response to antigens.",
  },
  {
    id: "sci-f2-c4-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "How do antibodies neutralise pathogens?",
    back: "Antibodies attach to pathogens (preventing them from entering a host cell) and cause pathogens to clump together.",
  },
  {
    id: "sci-f2-c4-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Give an example of blood-group antigen.",
    back: "Blood cells from another blood group can act as an antigen and trigger antibody production if introduced into the body.",
  },
  {
    id: "sci-f2-c4-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Why are not all microorganisms harmful pathogens?",
    back: "Some bacteria act on food residue in the large intestine to produce vitamin K and vitamin B12, which are absorbed by the body.",
  },
  {
    id: "sci-f2-c4-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "In what two ways do white blood cells defend the body against pathogens?",
    back: "Some engulf and digest pathogens (phagocytosis); others produce antibodies against specific antigens.",
  },
  {
    id: "sci-f2-c4-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is an allergy?",
    back: "The response of the body's immune system to an allergen that is usually harmless for most people.",
  },
  {
    id: "sci-f2-c4-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Give 4 examples of allergens.",
    back: "Mites, animal hair, dust, pollen (also: spores, certain foods like seafood/milk/eggs, animal stings, some medicines).",
  },
  {
    id: "sci-f2-c4-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Name 5 causes that weaken the immune system.",
    back: "Exposure to polluted air, exposure to pesticides, stress, excessive intake of sugar, smoking.",
  },
  {
    id: "sci-f2-c4-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Name 4 practices that strengthen the immune system.",
    back: "Getting enough sleep and rest, exercising and inhaling fresh air, not smoking, doing periodic health examinations.",
  },
  // Set 3: Immunity & Immunisation
  {
    id: "sci-f2-c4-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is immunisation?",
    back: "An effort to stimulate the body's defence against infections in babies, children and adults by injecting vaccines.",
  },
  {
    id: "sci-f2-c4-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What does a vaccine contain?",
    back: "Antigens obtained from a part or the whole structure of a weakened or dead virus or bacterium.",
  },
  {
    id: "sci-f2-c4-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What does the BCG vaccine protect against?",
    back: "Tuberculosis.",
  },
  {
    id: "sci-f2-c4-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What does DTaP stand for?",
    back: "Diphtheria, Tetanus and Pertussis (combination vaccine).",
  },
  {
    id: "sci-f2-c4-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What does MMR stand for?",
    back: "Measles, Mumps and Rubella (combination vaccine).",
  },
  {
    id: "sci-f2-c4-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is IPV?",
    back: "Inactivated Polio Vaccine — protects against Polio.",
  },
  {
    id: "sci-f2-c4-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Who receives the HPV vaccine in Malaysia?",
    back: "Girls aged 13 years old only; dose 2 given six months after dose 1.",
  },
  {
    id: "sci-f2-c4-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Where is the JE (Japanese Encephalitis) vaccine given?",
    back: "Only in Sarawak.",
  },
  {
    id: "sci-f2-c4-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What are the two types of immunity?",
    back: "Passive immunity and active immunity.",
  },
  {
    id: "sci-f2-c4-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is passive immunity?",
    back: "Immunity gained when the body receives antibodies from an external source rather than producing its own.",
  },
  {
    id: "sci-f2-c4-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is active immunity?",
    back: "Immunity gained when the body produces its own antibodies after being stimulated by antigens.",
  },
  {
    id: "sci-f2-c4-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is natural passive immunity?",
    back: "Antibody received by a baby from breast milk or the mother's blood across the placenta; temporary, lasting only the first few months after birth.",
  },
  {
    id: "sci-f2-c4-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is artificial passive immunity?",
    back: "Gained when an antiserum is injected into the patient's body; fast-acting but temporary.",
  },
  {
    id: "sci-f2-c4-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is an antiserum?",
    back: "A clear liquid in the blood that contains antibodies to prevent diseases, injected directly into a patient.",
  },
  {
    id: "sci-f2-c4-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is natural active immunity?",
    back: "Immunity that occurs when a person recovers from an infection; lasts long after the infection.",
  },
  {
    id: "sci-f2-c4-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "What is artificial active immunity?",
    back: "Immunity that occurs when a vaccine containing a dead or weakened pathogen is injected, and the immune system responds by producing antibodies; lasts long after vaccination.",
  },
  {
    id: "sci-f2-c4-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "In passive immunity, how does the antibody concentration change over time?",
    back: "It rises quickly to the immunity level after the antibody source is received, then declines as it is not replenished (short-lived).",
  },
  {
    id: "sci-f2-c4-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front:
      "In natural active immunity, how does the antibody response differ between the first and second infection?",
    back: "During the first infection, the antibody level stays low and does not reach the immunity level; during the second infection, it rises above the immunity level and immunity is achieved.",
  },
  {
    id: "sci-f2-c4-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front: "Why might controlled diseases like leprosy or whooping cough reoccur?",
    back: "If immunisation coverage decreases or is neglected, previously-controlled infectious diseases can re-emerge in the population.",
  },
  {
    id: "sci-f2-c4-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 4",
    lang: "dlp",
    front:
      "Why is immunisation important to the family, economy and nation, not just the individual?",
    back: "Low immunisation coverage increases healthcare costs, affects quality of work, and can cause recurrence of controlled diseases, impacting the whole of society and the economy.",
  },
];
