import type { QuizQuestion } from "@/data/content";

export const scienceF2C4QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c4-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is a disease?",
    options: [
      "An abnormal condition of body or mind that causes discomfort, difficulty to function or stress",
      "A normal condition of the human body",
      "A type of vaccine",
      "A type of antibody",
    ],
    answerIndex: 0,
    explanation: "A disease is an abnormal condition of body or mind that causes discomfort, difficulty to function or stress to an individual.",
  },
  {
    id: "sci-f2-c4-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Which of the following is an infectious disease?",
    options: ["Diabetes", "Hypertension", "Tuberculosis", "Cancer"],
    answerIndex: 2,
    explanation: "Tuberculosis is an infectious disease caused by a pathogen and can be transmitted between individuals; diabetes, hypertension and cancer are non-infectious diseases.",
  },
  {
    id: "sci-f2-c4-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Which of the following is a non-infectious disease?",
    options: ["Flu", "Asthma", "Ringworm", "Dengue fever"],
    answerIndex: 1,
    explanation: "Asthma is caused by genetic factors or lifestyle and cannot be transmitted from one person to another, making it a non-infectious disease.",
  },
  {
    id: "sci-f2-c4-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is a pathogen?",
    options: [
      "A vaccine that protects against disease",
      "An organism that causes disease",
      "A protein produced by white blood cells",
      "A type of vitamin",
    ],
    answerIndex: 1,
    explanation: "A pathogen is an organism that causes disease. All viruses, and some bacteria, protozoa, fungi and worms are pathogens.",
  },
  {
    id: "sci-f2-c4-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is a vector?",
    options: [
      "An animal that transmits pathogens from one host to another",
      "A type of antibody",
      "A weakened pathogen used in vaccines",
      "An organ that produces white blood cells",
    ],
    answerIndex: 0,
    explanation: "A vector is an animal, such as the Aedes mosquito or rat, that transmits pathogens from one host to a new host.",
  },
  {
    id: "sci-f2-c4-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Which vector spreads dengue fever and Zika fever?",
    options: ["Anopheles mosquito", "Aedes mosquito", "Housefly", "Rat"],
    answerIndex: 1,
    explanation: "The Aedes mosquito is the vector for both dengue virus and Zika virus.",
  },
  {
    id: "sci-f2-c4-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is the first line of body defence?",
    options: ["Phagocytosis", "Antibody production", "Skin and mucous membrane", "Vaccination"],
    answerIndex: 2,
    explanation: "The skin and mucous membrane form the first line of defence, preventing pathogens from entering the body.",
  },
  {
    id: "sci-f2-c4-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is the second line of body defence?",
    options: ["Skin", "Mucous membrane", "Phagocytosis by white blood cells", "Antibody production"],
    answerIndex: 2,
    explanation: "Pathogens that pass the first line of defence enter the bloodstream and face the second line of defence: phagocytosis, where white blood cells engulf and digest pathogens.",
  },
  {
    id: "sci-f2-c4-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is an antigen?",
    options: [
      "A protein that destroys pathogens",
      "A foreign substance that induces antibody production",
      "A vaccine ingredient that cures disease instantly",
      "A type of white blood cell",
    ],
    answerIndex: 1,
    explanation: "An antigen is a foreign substance that comes from outside the body and induces the production of antibodies.",
  },
  {
    id: "sci-f2-c4-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is immunisation?",
    options: [
      "An effort to stimulate the body's defence against infections by injecting vaccines",
      "A surgical procedure to remove pathogens",
      "A test to detect pathogens in blood",
      "A way to clean drinking water",
    ],
    answerIndex: 0,
    explanation: "Immunisation is an effort to stimulate the body's defence against infections in babies, children and adults by injecting vaccines.",
  },
  {
    id: "sci-f2-c4-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is the main difference between an infectious disease and a non-infectious disease?",
    options: [
      "Infectious diseases are always more dangerous",
      "Infectious diseases can be transmitted between individuals; non-infectious diseases cannot",
      "Non-infectious diseases are caused by pathogens",
      "Infectious diseases only affect children",
    ],
    answerIndex: 1,
    explanation: "Infectious diseases are caused by pathogens and can spread from one individual to another, while non-infectious diseases are caused by genetic factors or lifestyle and cannot be transmitted.",
  },
  {
    id: "sci-f2-c4-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Which of the following is NOT a way airborne diseases are prevented?",
    options: [
      "Covering the mouth and nose when sneezing or coughing",
      "Avoiding crowded places",
      "Adding chlorine to swimming pools",
      "Ensuring living places get enough light",
    ],
    answerIndex: 2,
    explanation: "Adding chlorine to swimming pools and water supply systems is a method to prevent waterborne diseases, not airborne diseases.",
  },
  {
    id: "sci-f2-c4-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Why can floods spread infectious diseases?",
    options: [
      "Floods kill all pathogens in water",
      "Floods cause inadequate water supply and poor sanitation, contaminating water sources",
      "Floods only affect non-infectious diseases",
      "Floods increase the number of vaccines available",
    ],
    answerIndex: 1,
    explanation: "Floods can spread infectious diseases because they worsen sanitation conditions and contaminate water supplies with pathogens, similar to areas with inadequate water supply.",
  },
  {
    id: "sci-f2-c4-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Ringworm and tinea are spread through which method?",
    options: ["Air", "Water", "Contact", "Vectors only"],
    answerIndex: 2,
    explanation: "Ringworm and tinea are caused by fungi and spread through contact, such as touching infected skin or wearing the clothes of an infected person.",
  },
  {
    id: "sci-f2-c4-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What happens during the primary stage of disease prevention?",
    options: [
      "Patients are separated from others",
      "Vectors are destroyed using fogging",
      "Personal hygiene is improved and the body's defence system is strengthened through vaccination",
      "Compounds are issued to dirty food premises",
    ],
    answerIndex: 2,
    explanation: "The primary stage focuses on improving health and strengthening the body's defence system before infection occurs, including personal hygiene and immunisation.",
  },
  {
    id: "sci-f2-c4-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What happens during the tertiary stage of disease prevention?",
    options: [
      "Strengthening the body's defence system through vaccines",
      "Controlling vector populations and protecting hosts",
      "Maintaining a healthy lifestyle",
      "Conducting frequent health check-ups",
    ],
    answerIndex: 1,
    explanation: "The tertiary stage involves controlling vector populations (destroying breeding places, fogging) and protecting hosts (using mosquito nets, wearing thick clothes).",
  },
  {
    id: "sci-f2-c4-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is the function of mucous membrane in body defence?",
    options: [
      "It produces antibodies",
      "It engulfs pathogens through phagocytosis",
      "It filters and traps microorganisms in the respiratory and digestive tract",
      "It injects vaccines into the body",
    ],
    answerIndex: 2,
    explanation: "Mucous membrane lines the digestive tract and respiratory tract; it filters and traps microorganisms, preventing them from entering the body, as part of the first line of defence.",
  },
  {
    id: "sci-f2-c4-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What is the relationship between antigen and antibody?",
    options: [
      "Antigen is produced in response to antibody",
      "Antibody is a foreign substance that triggers antigen production",
      "Antigen is a foreign substance that induces antibody production",
      "They are the same substance with different names",
    ],
    answerIndex: 2,
    explanation: "An antigen is a foreign substance that induces the production of antibodies; antibody is the protein produced by white blood cells in response to the antigen.",
  },
  {
    id: "sci-f2-c4-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "What does a vaccine contain?",
    options: [
      "Antibodies ready to fight pathogens",
      "Antigens from a weakened or dead pathogen",
      "Live, full-strength pathogens",
      "White blood cells",
    ],
    answerIndex: 1,
    explanation: "A vaccine contains antigens obtained from a part or the whole structure of a weakened or dead virus or bacterium, which stimulates immunity without causing disease.",
  },
  {
    id: "sci-f2-c4-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Which vaccine is only given to girls aged 13 years old in Malaysia?",
    options: ["BCG", "MMR", "HPV", "JE"],
    answerIndex: 2,
    explanation: "The HPV (Human Papillomavirus) vaccine is given only to girls aged 13 years old, with dose 2 given six months after dose 1.",
  },
  {
    id: "sci-f2-c4-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "A patient receives an antiserum injection. Which type of immunity is this, and why?",
    options: [
      "Active artificial immunity, because the body produces antibodies",
      "Passive artificial immunity, because the antibodies are obtained directly from an external source",
      "Active natural immunity, because the body recovers from infection",
      "Passive natural immunity, because the antibodies come from the mother",
    ],
    answerIndex: 1,
    explanation: "An antiserum injection provides ready-made antibodies from an external source without the patient's body producing its own, making it passive artificial immunity, which is fast but temporary.",
  },
  {
    id: "sci-f2-c4-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "A graph shows antibody concentration rising sharply after a second exposure to the same antigen, exceeding the immunity level, while the first exposure produced a low antibody level. What does this graph represent?",
    options: [
      "Passive natural immunity",
      "Passive artificial immunity",
      "Active natural immunity",
      "A vaccine failure",
    ],
    answerIndex: 2,
    explanation: "This pattern, where the second infection produces a much higher antibody response exceeding the immunity level, is characteristic of active natural immunity gained after recovering from an infection.",
  },
  {
    id: "sci-f2-c4-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Why is passive immunity, whether natural or artificial, always temporary?",
    options: [
      "Because the antibodies are destroyed by the vaccine",
      "Because the body did not produce the antibodies itself, so they are not continuously replenished",
      "Because passive immunity only works against viruses",
      "Because passive immunity requires multiple injections",
    ],
    answerIndex: 1,
    explanation: "In passive immunity, the antibodies come from an external source rather than being produced by the recipient's own immune system, so the antibody level decreases over time without being replenished.",
  },
  {
    id: "sci-f2-c4-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "A worker frequently complains of stress, eats excessive sugar, and is exposed to polluted air at the workplace. Based on this scenario, what is most likely to happen to the worker's immune system?",
    options: [
      "It will become stronger due to constant challenges",
      "It will become weakened, making the worker more prone to infections",
      "It will produce more antibodies automatically",
      "It will not be affected since these factors only affect non-infectious diseases",
    ],
    answerIndex: 1,
    explanation: "Stress, excessive sugar intake and exposure to polluted air are all factors that weaken the immune system, making a person more susceptible to infections.",
  },
  {
    id: "sci-f2-c4-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Why do health authorities recommend fogging in dengue outbreak areas as a tertiary prevention measure rather than relying only on primary prevention?",
    options: [
      "Fogging replaces the need for vaccination",
      "Fogging directly kills adult mosquito vectors to immediately reduce transmission when an outbreak is already occurring",
      "Fogging strengthens the human immune system",
      "Fogging removes the need for hygiene practices",
    ],
    answerIndex: 1,
    explanation: "Tertiary prevention (such as fogging) targets controlling vector populations directly during an active outbreak, providing immediate reduction in transmission, which primary prevention (improving health/hygiene before infection) cannot achieve on its own.",
  },
  {
    id: "sci-f2-c4-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "A baby develops temporary immunity from breast milk but this immunity fades within months. Later, the baby is vaccinated and develops long-lasting immunity. What best explains this difference?",
    options: [
      "Breast milk antibodies are artificial while vaccines are natural",
      "Breast milk provides passive immunity (borrowed antibodies that are not replenished); the vaccine triggers active immunity (the baby's own immune system produces and can keep producing antibodies)",
      "Vaccines work faster than breast milk in all cases",
      "Breast milk and vaccines provide the exact same type of immunity",
    ],
    answerIndex: 1,
    explanation: "Breast milk gives passive natural immunity using the mother's antibodies, which are not replenished and fade quickly. Vaccination gives active artificial immunity, stimulating the baby's own immune system to produce antibodies that persist long-term.",
  },
  {
    id: "sci-f2-c4-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "If a person has a wound on their skin, which line of defence is most directly compromised, and what is the consequence?",
    options: [
      "The third line of defence is compromised, so no antibodies can be made",
      "The first line of defence is compromised, allowing pathogens easier entry into the body and increasing reliance on the second and third lines",
      "The second line of defence is compromised, stopping phagocytosis completely",
      "All three lines of defence stop working entirely",
    ],
    answerIndex: 1,
    explanation: "The skin is part of the first line of defence; a wound breaks this barrier, allowing pathogens to enter more easily, which then requires the second line (phagocytosis) and third line (antibody production) to respond.",
  },
  {
    id: "sci-f2-c4-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "A list of diseases includes diabetes, leptospirosis, cancer and dengue. Which two are correctly grouped as infectious diseases?",
    options: [
      "Diabetes and cancer",
      "Leptospirosis and dengue",
      "Diabetes and dengue",
      "Cancer and leptospirosis",
    ],
    answerIndex: 1,
    explanation: "Leptospirosis (caused by Leptospira sp. bacteria, spread by rats) and dengue (caused by a virus, spread by Aedes mosquitoes) are both infectious diseases caused by pathogens; diabetes and cancer are non-infectious.",
  },
  {
    id: "sci-f2-c4-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "Why is it important for hajj pilgrims and food premises operators specifically to receive certain vaccines before travelling or working, according to the disease prevention framework?",
    options: [
      "It is part of the secondary stage to treat existing infections",
      "It is part of the primary stage, strengthening the body's defence system before exposure to crowded or high-risk environments",
      "It is part of the tertiary stage to control vector populations",
      "It has no connection to the three stages of prevention",
    ],
    answerIndex: 1,
    explanation: "Vaccinating high-risk groups such as hajj pilgrims, travellers and food premises operators is part of primary prevention, strengthening their body defence system before they are exposed to potential infection sources.",
  },
  {
    id: "sci-f2-c4-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "dlp",
    question: "A person recovers from chickenpox and never gets infected by it again, even decades later. Which concept best explains this lifelong protection?",
    options: [
      "Passive natural immunity, since antibodies came from the mother",
      "Active natural immunity, since the body produced its own antibodies during the infection that persist long-term",
      "Artificial passive immunity from an antiserum",
      "The chickenpox virus permanently disappeared from the environment",
    ],
    answerIndex: 1,
    explanation: "Recovering from an infection like chickenpox triggers active natural immunity — the body produces its own antibodies, and this immunity typically lasts long after the infection, sometimes for life.",
  },
];
