import type { QuizQuestion } from "@/data/content";

export const scienceF2C4QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c4-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah maksud penyakit?",
    options: [
      "Keadaan tidak normal pada badan atau minda yang menyebabkan rasa tidak selesa, kesukaran berfungsi atau tekanan",
      "Keadaan normal badan manusia",
      "Sejenis vaksin",
      "Sejenis antibodi",
    ],
    answerIndex: 0,
    explanation: "Penyakit ialah keadaan tidak normal pada badan atau minda yang menyebabkan rasa tidak selesa, kesukaran berfungsi atau tekanan kepada seseorang individu.",
  },
  {
    id: "sci-f2-c4-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Antara berikut, yang manakah penyakit berjangkit?",
    options: ["Diabetes", "Darah tinggi", "Tibi", "Kanser"],
    answerIndex: 2,
    explanation: "Tibi ialah penyakit berjangkit yang disebabkan patogen dan boleh dijangkiti antara individu; diabetes, darah tinggi dan kanser ialah penyakit tidak berjangkit.",
  },
  {
    id: "sci-f2-c4-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Antara berikut, yang manakah contoh penyakit yang boleh merebak melalui air tercemar?",
    options: ["Diabetes", "Kolera", "Kanser", "Hipertensi"],
    answerIndex: 1,
    explanation:
      "Kolera ialah penyakit berjangkit yang boleh merebak melalui makanan atau air yang tercemar oleh patogen.",
  },
  {
    id: "sci-f2-c4-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah maksud patogen?",
    options: [
      "Vaksin yang melindungi daripada penyakit",
      "Organisma yang menyebabkan penyakit",
      "Protein yang dihasilkan oleh sel darah putih",
      "Sejenis vitamin",
    ],
    answerIndex: 1,
    explanation: "Patogen ialah organisma yang menyebabkan penyakit. Semua virus, serta sebahagian bakteria, protozoa, kulat dan cacing adalah patogen.",
  },
  {
    id: "sci-f2-c4-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah maksud vektor?",
    options: [
      "Haiwan yang memindahkan patogen daripada satu perumah kepada perumah lain",
      "Sejenis antibodi",
      "Patogen yang dilemahkan dan digunakan dalam vaksin",
      "Organ yang menghasilkan sel darah putih",
    ],
    answerIndex: 0,
    explanation: "Vektor ialah haiwan, seperti nyamuk Aedes atau tikus, yang memindahkan patogen daripada satu perumah kepada perumah baharu.",
  },
  {
    id: "sci-f2-c4-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Vektor manakah yang merebakkan penyakit denggi dan Zika?",
    options: ["Nyamuk Anopheles", "Nyamuk Aedes", "Lalat rumah", "Tikus"],
    answerIndex: 1,
    explanation: "Nyamuk Aedes ialah vektor bagi kedua-dua virus denggi dan virus Zika.",
  },
  {
    id: "sci-f2-c4-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah pertahanan badan yang pertama?",
    options: ["Fagositosis", "Penghasilan antibodi", "Kulit dan membran mukus", "Vaksinasi"],
    answerIndex: 2,
    explanation: "Kulit dan membran mukus membentuk pertahanan pertama, mengelakkan patogen daripada memasuki badan.",
  },
  {
    id: "sci-f2-c4-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah pertahanan badan yang kedua?",
    options: ["Kulit", "Membran mukus", "Fagositosis oleh sel darah putih", "Penghasilan antibodi"],
    answerIndex: 2,
    explanation: "Patogen yang melepasi pertahanan pertama memasuki aliran darah dan berhadapan dengan pertahanan kedua: fagositosis, di mana sel darah putih menelan dan mencerna patogen.",
  },
  {
    id: "sci-f2-c4-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah maksud antigen?",
    options: [
      "Protein yang memusnahkan patogen",
      "Bahan asing yang merangsang penghasilan antibodi",
      "Bahan vaksin yang menyembuhkan penyakit serta-merta",
      "Sejenis sel darah putih",
    ],
    answerIndex: 1,
    explanation: "Antigen ialah bahan asing yang datang dari luar badan dan merangsang penghasilan antibodi.",
  },
  {
    id: "sci-f2-c4-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah maksud imunisasi?",
    options: [
      "Usaha untuk merangsang pertahanan badan terhadap jangkitan melalui suntikan vaksin",
      "Prosedur pembedahan untuk membuang patogen",
      "Ujian untuk mengesan patogen dalam darah",
      "Cara membersihkan air minuman",
    ],
    answerIndex: 0,
    explanation: "Imunisasi ialah usaha untuk merangsang pertahanan badan terhadap jangkitan dalam kalangan bayi, kanak-kanak dan orang dewasa melalui suntikan vaksin.",
  },
  {
    id: "sci-f2-c4-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah perbezaan utama antara penyakit berjangkit dan penyakit tidak berjangkit?",
    options: [
      "Penyakit berjangkit sentiasa lebih berbahaya",
      "Penyakit berjangkit boleh dijangkiti antara individu; penyakit tidak berjangkit tidak boleh",
      "Penyakit tidak berjangkit disebabkan oleh patogen",
      "Penyakit berjangkit hanya menjejaskan kanak-kanak",
    ],
    answerIndex: 1,
    explanation: "Penyakit berjangkit disebabkan oleh patogen dan boleh merebak daripada satu individu kepada individu lain, sementara penyakit tidak berjangkit disebabkan faktor genetik/gaya hidup dan tidak boleh dijangkiti.",
  },
  {
    id: "sci-f2-c4-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Antara berikut, manakah BUKAN cara mencegah penyakit bawaan udara?",
    options: [
      "Menutup mulut dan hidung semasa bersin atau batuk",
      "Mengelakkan tempat yang sesak",
      "Menambah klorin ke dalam kolam renang",
      "Memastikan tempat tinggal mendapat cahaya yang cukup",
    ],
    answerIndex: 2,
    explanation: "Menambah klorin ke dalam kolam renang dan sistem bekalan air adalah kaedah mencegah penyakit bawaan air, bukan penyakit bawaan udara.",
  },
  {
    id: "sci-f2-c4-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Mengapakah banjir boleh merebakkan penyakit berjangkit?",
    options: [
      "Banjir membunuh semua patogen dalam air",
      "Banjir menyebabkan bekalan air tidak mencukupi dan sanitasi lemah, mencemarkan sumber air",
      "Banjir hanya menjejaskan penyakit tidak berjangkit",
      "Banjir meningkatkan bilangan vaksin yang tersedia",
    ],
    answerIndex: 1,
    explanation: "Banjir boleh merebakkan penyakit berjangkit kerana ia menjejaskan keadaan sanitasi dan mencemarkan bekalan air dengan patogen, serupa dengan kawasan yang mempunyai bekalan air tidak mencukupi.",
  },
  {
    id: "sci-f2-c4-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Kurap dan kurap kaki disebarkan melalui cara yang manakah?",
    options: ["Udara", "Air", "Sentuhan", "Vektor sahaja"],
    answerIndex: 2,
    explanation: "Kurap dan kurap kaki disebabkan oleh kulat dan disebarkan melalui sentuhan, seperti menyentuh kulit yang dijangkiti atau memakai pakaian orang yang dijangkiti.",
  },
  {
    id: "sci-f2-c4-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah yang berlaku semasa peringkat primer pencegahan penyakit?",
    options: [
      "Pesakit diasingkan daripada orang lain",
      "Vektor dimusnahkan melalui pengasapan",
      "Kebersihan diri ditingkatkan dan sistem pertahanan badan dikukuhkan melalui vaksinasi",
      "Kompaun dikeluarkan kepada premis makanan kotor",
    ],
    answerIndex: 2,
    explanation: "Peringkat primer memberi tumpuan kepada meningkatkan kesihatan dan mengukuhkan sistem pertahanan badan sebelum jangkitan berlaku, termasuk kebersihan diri dan imunisasi.",
  },
  {
    id: "sci-f2-c4-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah yang berlaku semasa peringkat tertiari pencegahan penyakit?",
    options: [
      "Mengukuhkan sistem pertahanan badan melalui vaksin",
      "Mengawal populasi vektor dan melindungi perumah",
      "Mengamalkan gaya hidup sihat",
      "Menjalankan pemeriksaan kesihatan kerap",
    ],
    answerIndex: 1,
    explanation: "Peringkat tertiari melibatkan mengawal populasi vektor (memusnahkan tempat pembiakan, pengasapan) dan melindungi perumah (menggunakan kelambu, memakai pakaian tebal).",
  },
  {
    id: "sci-f2-c4-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah fungsi membran mukus dalam pertahanan badan?",
    options: [
      "Menghasilkan antibodi",
      "Menelan patogen melalui fagositosis",
      "Menapis dan memerangkap mikroorganisma dalam saluran pernafasan dan pencernaan",
      "Menyuntik vaksin ke dalam badan",
    ],
    answerIndex: 2,
    explanation: "Membran mukus melapisi saluran pencernaan dan saluran pernafasan; ia menapis dan memerangkap mikroorganisma, mengelakkannya daripada memasuki badan, sebagai sebahagian daripada pertahanan pertama.",
  },
  {
    id: "sci-f2-c4-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah hubungan antara antigen dan antibodi?",
    options: [
      "Antigen dihasilkan sebagai tindak balas kepada antibodi",
      "Antibodi ialah bahan asing yang merangsang penghasilan antigen",
      "Antigen ialah bahan asing yang merangsang penghasilan antibodi",
      "Kedua-duanya bahan yang sama dengan nama berbeza",
    ],
    answerIndex: 2,
    explanation: "Antigen ialah bahan asing yang merangsang penghasilan antibodi; antibodi ialah protein yang dihasilkan oleh sel darah putih sebagai tindak balas terhadap antigen.",
  },
  {
    id: "sci-f2-c4-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Apakah yang terkandung dalam vaksin?",
    options: [
      "Antibodi sedia ada untuk melawan patogen",
      "Antigen daripada patogen yang dilemahkan atau mati",
      "Patogen hidup yang berkuasa penuh",
      "Sel darah putih",
    ],
    answerIndex: 1,
    explanation: "Vaksin mengandungi antigen daripada sebahagian atau keseluruhan struktur virus/bakteria yang dilemahkan atau mati, yang merangsang imuniti tanpa menyebabkan penyakit.",
  },
  {
    id: "sci-f2-c4-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Mengapakah vaksinasi boleh memberikan imuniti aktif buatan?",
    options: [
      "Vaksin membekalkan antibodi kekal secara terus",
      "Vaksin merangsang sistem imun badan menghasilkan antibodi terhadap antigen tertentu",
      "Vaksin membunuh semua mikroorganisma di dalam badan",
      "Vaksin menghalang sel darah putih daripada bertindak",
    ],
    answerIndex: 1,
    explanation:
      "Vaksin membawa antigen yang merangsang sistem imun badan menghasilkan antibodinya sendiri. Oleh sebab badan sendiri menghasilkan tindak balas imun, ini ialah imuniti aktif buatan.",
  },
  {
    id: "sci-f2-c4-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Seorang pesakit menerima suntikan antiserum. Apakah jenis imuniti ini, dan mengapa?",
    options: [
      "Imuniti aktif buatan, kerana badan menghasilkan antibodi",
      "Imuniti pasif buatan, kerana antibodi diperoleh terus daripada sumber luaran",
      "Imuniti aktif semula jadi, kerana badan sembuh daripada jangkitan",
      "Imuniti pasif semula jadi, kerana antibodi datang daripada ibu",
    ],
    answerIndex: 1,
    explanation: "Suntikan antiserum memberikan antibodi sedia ada daripada sumber luaran tanpa badan pesakit menghasilkan antibodinya sendiri, menjadikannya imuniti pasif buatan, yang pantas tetapi sementara.",
  },
  {
    id: "sci-f2-c4-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Satu graf menunjukkan kepekatan antibodi meningkat mendadak selepas pendedahan kedua kepada antigen yang sama, melebihi paras imuniti, sementara pendedahan pertama hanya menghasilkan paras antibodi yang rendah. Apakah yang diwakili oleh graf ini?",
    options: [
      "Imuniti pasif semula jadi",
      "Imuniti pasif buatan",
      "Imuniti aktif semula jadi",
      "Kegagalan vaksin",
    ],
    answerIndex: 2,
    explanation: "Corak ini, di mana jangkitan kedua menghasilkan tindak balas antibodi yang jauh lebih tinggi melebihi paras imuniti, adalah ciri imuniti aktif semula jadi yang diperoleh selepas sembuh daripada jangkitan.",
  },
  {
    id: "sci-f2-c4-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Mengapakah imuniti pasif, sama ada semula jadi atau buatan, sentiasa bersifat sementara?",
    options: [
      "Kerana antibodi dimusnahkan oleh vaksin",
      "Kerana badan tidak menghasilkan antibodi itu sendiri, jadi ia tidak diisi semula secara berterusan",
      "Kerana imuniti pasif hanya berfungsi melawan virus",
      "Kerana imuniti pasif memerlukan beberapa suntikan",
    ],
    answerIndex: 1,
    explanation: "Dalam imuniti pasif, antibodi datang daripada sumber luaran berbanding dihasilkan oleh sistem imun penerima sendiri, jadi paras antibodi menurun dari semasa ke semasa tanpa diisi semula.",
  },
  {
    id: "sci-f2-c4-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Bakteria memasuki badan melalui luka pada kulit. Susunan tindak balas pertahanan badan yang manakah paling tepat?",
    options: [
      "Kulit → vaksin → fagositosis",
      "Halangan kulit telah ditembusi → fagositosis oleh sel darah putih → tindak balas antibodi khusus jika diperlukan",
      "Antibodi → kulit → fagositosis",
      "Semua pertahanan badan berhenti berfungsi",
    ],
    answerIndex: 1,
    explanation:
      "Luka menyebabkan pertahanan pertama, iaitu kulit, ditembusi. Sel darah putih boleh melakukan fagositosis sebagai pertahanan seterusnya, dan tindak balas antibodi khusus boleh berlaku terhadap antigen.",
  },
  {
    id: "sci-f2-c4-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Mengapakah pihak berkuasa kesihatan mengesyorkan pengasapan di kawasan wabak denggi sebagai langkah pencegahan tertiari berbanding hanya bergantung kepada pencegahan primer?",
    options: [
      "Pengasapan menggantikan keperluan vaksinasi",
      "Pengasapan membunuh terus nyamuk vektor dewasa untuk mengurangkan penularan dengan segera semasa wabak sedang berlaku",
      "Pengasapan mengukuhkan sistem imun manusia",
      "Pengasapan menghapuskan keperluan amalan kebersihan",
    ],
    answerIndex: 1,
    explanation: "Pencegahan tertiari (seperti pengasapan) menyasarkan kawalan populasi vektor secara langsung semasa wabak aktif, memberikan pengurangan penularan dengan segera, yang tidak dapat dicapai oleh pencegahan primer (meningkatkan kesihatan/kebersihan sebelum jangkitan) sahaja.",
  },
  {
    id: "sci-f2-c4-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Seorang bayi membina imuniti sementara daripada susu ibu tetapi imuniti ini pudar dalam beberapa bulan. Kemudian, bayi itu divaksinasi dan membina imuniti yang kekal lama. Apakah penjelasan terbaik bagi perbezaan ini?",
    options: [
      "Antibodi susu ibu bersifat buatan sementara vaksin bersifat semula jadi",
      "Susu ibu memberikan imuniti pasif (antibodi 'pinjaman' yang tidak diisi semula); vaksin merangsang imuniti aktif (sistem imun bayi sendiri menghasilkan dan boleh terus menghasilkan antibodi)",
      "Vaksin sentiasa lebih pantas berbanding susu ibu dalam semua kes",
      "Susu ibu dan vaksin memberikan jenis imuniti yang sama persis",
    ],
    answerIndex: 1,
    explanation: "Susu ibu memberikan imuniti pasif semula jadi menggunakan antibodi ibu, yang tidak diisi semula dan pudar dengan cepat. Vaksinasi memberikan imuniti aktif buatan, merangsang sistem imun bayi sendiri untuk menghasilkan antibodi yang kekal lama.",
  },
  {
    id: "sci-f2-c4-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Jika seseorang mengalami luka pada kulitnya, pertahanan manakah yang paling terjejas secara langsung, dan apakah akibatnya?",
    options: [
      "Pertahanan ketiga terjejas, jadi tiada antibodi dapat dihasilkan",
      "Pertahanan pertama terjejas, membenarkan patogen memasuki badan dengan lebih mudah dan meningkatkan kebergantungan pada pertahanan kedua dan ketiga",
      "Pertahanan kedua terjejas, menghentikan fagositosis sepenuhnya",
      "Ketiga-tiga pertahanan berhenti berfungsi sepenuhnya",
    ],
    answerIndex: 1,
    explanation: "Kulit ialah sebahagian daripada pertahanan pertama; luka memecahkan halangan ini, membenarkan patogen memasuki badan dengan lebih mudah, yang kemudiannya memerlukan pertahanan kedua (fagositosis) dan ketiga (penghasilan antibodi) untuk bertindak balas.",
  },
  {
    id: "sci-f2-c4-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Satu senarai penyakit termasuk diabetes, leptospirosis, kanser dan denggi. Manakah dua penyakit yang betul dikelaskan sebagai penyakit berjangkit?",
    options: [
      "Diabetes dan kanser",
      "Leptospirosis dan denggi",
      "Diabetes dan denggi",
      "Kanser dan leptospirosis",
    ],
    answerIndex: 1,
    explanation: "Leptospirosis (disebabkan bakteria Leptospira sp., disebarkan oleh tikus) dan denggi (disebabkan virus, disebarkan oleh nyamuk Aedes) kedua-duanya adalah penyakit berjangkit yang disebabkan patogen; diabetes dan kanser adalah penyakit tidak berjangkit.",
  },
  {
    id: "sci-f2-c4-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Mengapakah antibiotik perlu diambil mengikut dos dan masa yang ditetapkan oleh doktor?",
    options: [
      "Supaya badan berhenti menghasilkan sel darah putih",
      "Supaya semua virus di dalam badan dibunuh serta-merta",
      "Supaya antibiotik bertukar menjadi vaksin",
      "Supaya antibiotik sentiasa berada pada aras yang berkesan dalam badan",
    ],
    answerIndex: 3,
    explanation:
      "Sebahagian antibiotik disingkirkan daripada badan dan kepekatannya akan berkurang. Mengambilnya mengikut dos dan masa yang ditetapkan membantu mengekalkan aras antibiotik yang sesuai.",
  },
  {
    id: "sci-f2-c4-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 4",
    lang: "bm",
    question: "Selepas seseorang pulih daripada jangkitan, sistem imunnya menghasilkan antibodi sendiri terhadap antigen patogen tersebut. Apakah jenis imuniti yang diperoleh?",
    options: [
      "Imuniti pasif semula jadi",
      "Imuniti aktif semula jadi",
      "Imuniti pasif buatan",
      "Tiada imuniti terbentuk",
    ],
    answerIndex: 1,
    explanation:
      "Imuniti aktif semula jadi terbentuk selepas jangkitan apabila sistem imun badan sendiri menghasilkan tindak balas terhadap antigen.",
  },
];
