import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c6-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 6",
    lang: "dlp",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C6QuizzesDLP: QuizQuestion[] = buildQuiz([
  ["Easy", "What is the property of circumference angles subtended by the same arc?", ["Equal in size", "Always different", "Always 90°", "Always 180°"], 0],
  ["Easy", "What is the relationship between the centre angle and the circumference angle on the same arc?", ["Centre angle = 2x circumference angle", "Centre angle = circumference angle", "Centre angle = circumference angle/2", "No relationship"], 0],
  ["Easy", "What is the circumference angle subtended by a diameter?", ["90°", "180°", "45°", "60°"], 0],
  ["Easy", "What is a cyclic quadrilateral?", ["A quadrilateral with all vertices on a circle's circumference", "Any quadrilateral inside a circle", "A quadrilateral with one vertex at the centre", "A quadrilateral without a circle"], 0],
  ["Easy", "What is the sum of opposite angles in a cyclic quadrilateral?", ["180°", "360°", "90°", "270°"], 0],
  ["Easy", "What is the relationship between the exterior angle and the corresponding opposite interior angle of a cyclic quadrilateral?", ["Equal value", "Differ by 90°", "Sum to 180°", "Sum to 360°"], 0],
  ["Easy", "What does a tangent to a circle mean?", ["A straight line touching a circle at exactly one point", "A line passing through the centre", "A line intersecting a circle twice", "Any chord"], 0],
  ["Easy", "What is the angle between a tangent and the radius at the point of tangency?", ["90°", "180°", "45°", "60°"], 0],
  ["Easy", "Are two tangents from the same external point equal in length?", ["Yes", "No", "Only if the circles are equal", "Depends on the angle"], 0],
  ["Easy", "What is a tangent-chord angle?", ["Equal to the alternate segment angle subtended by the chord", "Always 90°", "Always 180°", "Has no relation to the segment"], 0],
  ["Easy", "Centre angle is 80°. Circumference angle on the same arc?", ["40°", "160°", "20°", "80°"], 0],
  ["Easy", "Circumference angle is 35°. Centre angle on the same arc?", ["70°", "17.5°", "35°", "105°"], 0],
  ["Easy", "How many common tangents if two circles don't touch?", ["4", "3", "2", "1"], 0],
  ["Easy", "How many common tangents if two circles touch externally?", ["3", "4", "2", "1"], 0],
  ["Easy", "How many common tangents if two circles intersect?", ["2", "4", "3", "1"], 0],
  ["Easy", "What is a point of tangency?", ["The point of contact between a tangent and a circle", "The circle's centre", "Any point on the circumference", "The intersection of two chords"], 0],
  ["Easy", "What is a minor arc?", ["The shorter arc between two points on the circumference", "The longer arc", "Half the circumference", "The entire circumference"], 0],
  ["Easy", "What is a major arc?", ["The longer arc between two points on the circumference", "The shorter arc", "Half the circumference only", "A diameter"], 0],
  ["Easy", "PR & QS are diameters, ∠QRS=90°, ∠QPR=45°. Find y (∠PQS).", ["45°", "90°", "135°", "180°"], 0],
  ["Easy", "Arc PR = arc QS. The angle on arc QS = 40°. Angle on arc PR?", ["40°", "20°", "80°", "140°"], 0],

  ["Medium", "KLMN cyclic, ∠LKN=104°, ∠LMN=8x. Find x.", ["9.5°", "10°", "8.5°", "13°"], 0],
  ["Medium", "∠KNM=98°, ∠KLM=4y in a cyclic quadrilateral. Find y.", ["20.5°", "20°", "22°", "18°"], 0],
  ["Medium", "PQRS cyclic, ∠PQR=4y, ∠PSR=2y, line RST. Find y.", ["30°", "20°", "60°", "45°"], 0],
  ["Medium", "From the above, find ∠PST.", ["120°", "60°", "90°", "150°"], 0],
  ["Medium", "ABC is a straight tangent line, ∠OBA=90° (tangent-radius), ∠AOB=42°. Find x if x+∠AOB=90°.", ["48°", "42°", "90°", "138°"], 0],
  ["Medium", "Tangents PQ, RQ meet at Q, ∠OPQ=90°, x=∠POQ, ∠OQP=66°. Find x.", ["24°", "66°", "90°", "156°"], 0],
  ["Medium", "Tangent PQ=14cm. Find the length of RQ (another tangent from the same point).", ["14 cm", "7 cm", "28 cm", "21 cm"], 0],
  ["Medium", "x=24° (from right-angled triangle OPQ), OP=14tan24°. Find OP.", ["≈6.233 cm", "14 cm", "12.8 cm", "7 cm"], 0],
  ["Medium", "∠QSR=60° (alternate segment), PQ&PR tangents. Find related angle x if x=∠QSR.", ["60°", "30°", "90°", "120°"], 0],
  ["Medium", "Arc PQ=2x arc QR, ∠PTS=180-2(48°). Find ∠PTS.", ["84°", "96°", "48°", "132°"], 0],
  ["Medium", "From the above, find x if x=∠PTS/2.", ["42°", "84°", "21°", "48°"], 0],
  ["Medium", "∠QPR=35°, ∠PSQ=45°, arc length RS=2QR. Find ∠SPR.", ["Depends on diagram; approximately 35°+additional angle", "45°", "70°", "90°"], 0],
  ["Medium", "Cyclic quadrilateral ABCD, ∠ADB=30°, ∠ABD=20°. Find ∠BCD.", ["130° (180-30-20=130, based on the angles in triangle ABD)", "50°", "100°", "150°"], 0],
  ["Medium", "POS is equilateral, ∠SOR=20°. Find ∠PQR using the centre angle.", ["Approximately 40° (half of (60+20))", "60°", "20°", "80°"], 0],
  ["Medium", "∠KNM=55°, KL=LM (isosceles). Find ∠KLM.", ["70° (180-2(55) if KLM is isosceles with base angle 55°)", "55°", "110°", "125°"], 0],
  ["Medium", "Circle diameter 16cm, ∠ROS=70°, ∠QRP=40°. Find θ (estimated from the angle relationships).", ["Estimated from centre and circumference angles; θ≈35°", "70°", "20°", "55°"], 0],
  ["Medium", "PQ=QR, ∠PSQ=30°, ∠SPR=32°. Find x+y+z (estimated sum of related angles).", ["Approximately 180° if x,y,z form a triangle", "360°", "90°", "270°"], 0],
  ["Medium", "Two circles with radii 4cm and 3cm, centre distance 7cm. Common tangent PQRS. Find x if cos x=1/7.", ["x≈81.79°", "x=45°", "x=60°", "x=30°"], 0],
  ["Medium", "A tyre diameter is 50cm, distance WY=1.2m. VY=WY (two tangents). Find VY.", ["1.2 m", "0.6 m", "2.4 m", "0.25 m"], 0],
  ["Medium", "From the above, radius=0.25m. Find OY using Pythagoras (OY²=1.2²+0.25²).", ["≈1.23 m", "1.45 m", "1.2 m", "0.25 m"], 0],

  ["Hard", "In a sculpture diagram: arc PQ=arc QR, SQ passes through O, ∠QOR=50°. Find ∠QSR.", ["25° (half of 50°)", "50°", "100°", "12.5°"], 0],
  ["Hard", "From the above, find ∠PQS if ∠PSQ=∠QSR=25°.", ["65° (180-90-25)", "25°", "90°", "155°"], 0],
  ["Hard", "OSU and PST are straight lines, diameter 16cm, ∠ROS=70°, ∠QRP=40°, ST=TU. Find θ.", ["Complex estimate; requires full diagram, approximately θ≈35°", "70°", "20°", "55°"], 0],
  ["Hard", "From the above, find the length PQ (3 s.f.) using trigonometry in the right-angled triangle on the diameter.", ["Depends on angle θ and diameter 16cm", "16.0 cm", "8.00 cm", "12.3 cm"], 0],
  ["Hard", "∠DOB=158°, DCE is a straight line, cyclic quadrilateral ABCD. Find x (related exterior angle).", ["Approximately 79° (half of 158° for the related circumference angle)", "158°", "22°", "101°"], 0],
  ["Hard", "PQRS cyclic, ∠QSR=36°, PS=PQ, RST is a straight line. Find x (exterior angle related to ∠QSR).", ["Approximately 36° or directly related to ∠QPR", "72°", "18°", "144°"], 0],
  ["Hard", "∠BCD=126°, arc AB=BC, AOD is a straight line. Find x (related angle in the circle centred at O).", ["Approximately 54° (180-126)", "126°", "63°", "108°"], 0],
  ["Hard", "Two tangents PQ and PR from external point P, ∠QSR=60° (alternate segment), circle radius 5cm. Find PQ using trigonometry.", ["Depends on ∠OPQ; estimated using tan(half the external angle)", "5 cm", "10 cm", "2.5 cm"], 0],
  ["Hard", "From the above, find OP (centre to external point distance) using Pythagoras OP²=OQ²+PQ².", ["Depends on calculated PQ; OP=√(5²+PQ²)", "5 cm", "10 cm", "OP=PQ"], 0],
  ["Hard", "ROS is a straight line, radius 3cm, ∠ORP=25°, PS is a tangent. Find x (angle in the right-angled triangle).", ["Approximately 65° (90-25)", "25°", "90°", "155°"], 0],
  ["Hard", "From the above, find PS using tan25°=PS/related radius.", ["PS=3tan25°≈1.40cm (estimate)", "PS=3cm", "PS=6cm", "PS=1.5cm"], 0],
  ["Hard", "Triangle KLM with tangent PMN. ∠PMK and ∠KLM are alternate segment angles. If ∠KLM=60°, ∠PMK=?", ["60° (equal alternate segment angles)", "30°", "90°", "120°"], 0],
  ["Hard", "Triangle ABL in a circle, KLM is a tangent. x=60° (alternate segment ∠KLA). Find y if y=∠LAB (corresponding alternate segment)=54°.", ["54°", "60°", "126°", "36°"], 0],
  ["Hard", "Why does the angle between a tangent and a chord equal the alternate segment angle?", ["The Alternate Segment Theorem, proven using the 90° tangent-radius angle and circumference angle properties", "It's purely coincidental", "Because a tangent is always parallel to the chord", "Because all circle angles are equal"], 0],
  ["Hard", "What is the best strategy for solving a complex circle problem with many unknown angles?", ["Solve step by step: centre/circumference angles first, then cyclic quadrilateral, then tangent properties", "Guess all the angles", "Use only one theorem for everything", "Ignore the diagram and calculate directly"], 0],
]);
