import type { Difficulty, QuizQuestion } from "@/data/content";
import { buildForm3MathQuizSets } from "../quiz-sets";
import { MATH_F3_C6_QUIZ_VISUALS } from "./quiz-visuals";
import { MATH_F3_C6_QUIZ_EXPLANATIONS } from "./quiz-explanations";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];
function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c6-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 6",
    lang: "bm",
    question,
    options,
    answerIndex,
    mathNotation: "indices",
    visual: MATH_F3_C6_QUIZ_VISUALS[index + 1],
    explanation: MATH_F3_C6_QUIZ_EXPLANATIONS[index + 1].bm,
  }));
}

export const mathF3C6QuestionBankBM: QuizQuestion[] = buildQuiz([
  [
    "Easy",
    "Apakah sifat sudut lilitan yang dicangkum lengkok sama?",
    ["Sama besar", "Berbeza-beza", "Sentiasa 90°", "Sentiasa 180°"],
    0,
  ],
  [
    "Easy",
    "Apakah hubungan sudut pusat dengan sudut lilitan lengkok sama?",
    [
      "Sudut pusat = 2x sudut lilitan",
      "Sudut pusat = sudut lilitan",
      "Sudut pusat = sudut lilitan/2",
      "Tiada hubungan",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah sudut lilitan yang dicangkum oleh diameter?",
    ["90°", "180°", "45°", "60°"],
    0,
  ],
  [
    "Easy",
    "Apakah sisi empat kitaran?",
    [
      "Semua bucu pada lilitan",
      "Semua bucu di dalam bulatan",
      "Semua bucu di luar bulatan",
      "Satu bucu di pusat bulatan",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah jumlah sudut bertentangan sisi empat kitaran?",
    ["180°", "360°", "90°", "270°"],
    0,
  ],
  [
    "Easy",
    "Apakah hubungan sudut peluaran dengan sudut pedalaman bertentangan sepadan sisi empat kitaran?",
    ["Sama nilai", "Berbeza 90°", "Jumlah 180°", "Jumlah 360°"],
    0,
  ],
  [
    "Easy",
    "Apakah maksud tangen kepada bulatan?",
    [
      "Garis menyentuh pada satu titik",
      "Garis memotong pada dua titik",
      "Garis melalui pusat bulatan",
      "Segmen antara dua titik lilitan",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah sudut antara tangen dan jejari pada titik ketangenan?",
    ["90°", "180°", "45°", "60°"],
    0,
  ],
  [
    "Easy",
    "Adakah dua tangen daripada satu titik luar sama panjang?",
    ["Ya", "Tidak", "Hanya jika bulatan sama", "Bergantung sudut"],
    0,
  ],
  [
    "Easy",
    "Apakah sudut tangen-perentas?",
    [
      "Sudut tembereng selang-seli",
      "Sudut tangen-jejari",
      "Sudut antara dua diameter",
      "Sudut sisi bertentangan kitaran",
    ],
    0,
  ],
  [
    "Easy",
    "Sudut pusat 80°. Sudut lilitan lengkok sama?",
    ["40°", "160°", "20°", "80°"],
    0,
  ],
  [
    "Easy",
    "Sudut lilitan 35°. Sudut pusat lengkok sama?",
    ["70°", "17.5°", "35°", "105°"],
    0,
  ],
  [
    "Easy",
    "Dua bulatan terpisah di luar satu sama lain, tanpa bersentuhan atau bersilang. Berapakah bilangan tangen sepunya?",
    ["4", "3", "2", "1"],
    0,
  ],
  [
    "Easy",
    "Berapa tangen sepunya jika dua bulatan bersentuhan di luar?",
    ["3", "4", "2", "1"],
    0,
  ],
  [
    "Easy",
    "Berapa tangen sepunya jika dua bulatan bersilang?",
    ["2", "4", "3", "1"],
    0,
  ],
  [
    "Easy",
    "Apakah titik ketangenan?",
    [
      "Titik sentuhan tangen",
      "Titik tengah perentas",
      "Titik persilangan perentas",
      "Titik pusat bulatan",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah lengkok minor?",
    [
      "Lengkok kurang daripada 180°",
      "Lengkok lebih daripada 180°",
      "Lengkok tepat 180°",
      "Lengkok tepat 360°",
    ],
    0,
  ],
  [
    "Easy",
    "Apakah lengkok major?",
    [
      "Lengkok lebih daripada 180°",
      "Lengkok kurang daripada 180°",
      "Lengkok tepat 180°",
      "Lengkok tepat 360°",
    ],
    0,
  ],
  [
    "Easy",
    "P, Q, R dan S terletak mengikut urutan pada bulatan. PR dan QS ialah diameter. Jika ∠QPR = 45°, cari ∠PQS.",
    ["45°", "90°", "135°", "180°"],
    0,
  ],
  [
    "Easy",
    "Lengkok minor PR dan QS sama panjang. Dua sudut pada lilitan mencangkum lengkok tersebut, dengan bucu pada lengkok major masing-masing. Jika sudut pertama 40°, cari sudut kedua.",
    ["40°", "20°", "80°", "140°"],
    0,
  ],
  [
    "Medium",
    "KLMN ialah sisi empat kitaran. ∠LKN = 104° dan ∠LMN = (8x)°. Cari x.",
    ["9.5", "10", "8.5", "13"],
    0,
  ],
  [
    "Medium",
    "KLMN ialah sisi empat kitaran. ∠KNM = 98° dan ∠KLM = (4y)°. Cari y.",
    ["20.5", "20", "22", "18"],
    0,
  ],
  [
    "Medium",
    "PQRS ialah sisi empat kitaran. ∠PQR = (4y)° dan ∠PSR = (2y)°. Cari y.",
    ["30", "20", "60", "45"],
    0,
  ],
  [
    "Medium",
    "PQRS ialah sisi empat kitaran. ∠PQR = (4y)° dan ∠PSR = (2y)°. R, S dan T segaris, dengan S di antara R dan T. Cari ∠PST.",
    ["120°", "60°", "90°", "150°"],
    0,
  ],
  [
    "Medium",
    "AB ialah tangen kepada bulatan berpusat O di B. Jika ∠AOB = 42°, cari ∠OAB.",
    ["48°", "42°", "90°", "138°"],
    0,
  ],
  [
    "Medium",
    "QP dan QR ialah tangen dari Q kepada bulatan berpusat O. Jika ∠OQP = 66°, cari ∠POQ.",
    ["24°", "66°", "90°", "156°"],
    0,
  ],
  [
    "Medium",
    "QP dan QR ialah tangen dari titik luar Q kepada bulatan yang sama. Jika QP = 14 cm, cari QR.",
    ["14 cm", "7 cm", "28 cm", "21 cm"],
    0,
  ],
  [
    "Medium",
    "QP ialah tangen di P kepada bulatan berpusat O. QP = 14 cm dan ∠OQP = 24°. Cari OP, betul kepada 2 tempat perpuluhan.",
    ["6.23 cm", "31.45 cm", "12.79 cm", "7.00 cm"],
    0,
  ],
  [
    "Medium",
    "PQ dan PR ialah tangen di Q dan R. S terletak pada lengkok major QR dan ∠QSR = 60°. Cari ∠PQR.",
    ["60°", "30°", "90°", "120°"],
    0,
  ],
  [
    "Medium",
    "TP dan TS ialah tangen di P dan S. Q terletak pada lengkok major PS dan ∠PQS = 48°. Cari ∠PTS.",
    ["84°", "96°", "48°", "132°"],
    0,
  ],
  [
    "Medium",
    "O ialah pusat bulatan dan ∠POS = 84°. Q terletak pada lengkok major PS. Cari ∠PQS.",
    ["42°", "84°", "21°", "48°"],
    0,
  ],
  [
    "Medium",
    "P, Q, R dan S terletak mengikut urutan pada bulatan. ∠QPR = 35°, ∠PSQ = 45° dan panjang lengkok RS = 2 × panjang lengkok QR. Cari ∠SPR.",
    ["70°", "45°", "35°", "90°"],
    0,
  ],
  [
    "Medium",
    "ABCD ialah sisi empat kitaran. Jika ∠ADB = 30° dan ∠ABD = 20°, cari ∠BCD.",
    ["50°", "130°", "100°", "150°"],
    0,
  ],
  [
    "Medium",
    "O ialah pusat bulatan. Segi tiga POS sama sisi. P, S dan R terletak mengikut urutan pada lengkok minor PR, dan ∠SOR = 20°. Q terletak pada lengkok major PR. Cari ∠PQR.",
    ["40°", "60°", "20°", "80°"],
    0,
  ],
  [
    "Medium",
    "KLMN ialah sisi empat kitaran dengan KL = LM. Jika ∠KNM = 55°, cari ∠KLM.",
    ["125°", "70°", "55°", "110°"],
    0,
  ],
  [
    "Medium",
    "Bulatan berpusat O mempunyai diameter 16 cm dan ∠ROS = 70°. Q terletak pada lengkok major RS. Cari ∠RQS.",
    ["35°", "70°", "20°", "55°"],
    0,
  ],
  [
    "Medium",
    "P, Q, R dan S terletak mengikut urutan pada bulatan dengan PQ = QR. Jika ∠PSQ = 30°, cari ∠PQR.",
    ["120°", "60°", "30°", "150°"],
    0,
  ],
  [
    "Medium",
    "Dua bulatan berjejari 4 cm dan 3 cm mempunyai jarak pusat 7 cm. Sudut tirus x ialah sudut antara garis pusat-pusat dengan garis yang serenjang kepada tangen sepunya luar. Cari x, betul kepada 2 tempat perpuluhan.",
    ["81.79°", "8.21°", "45.00°", "60.00°"],
    0,
  ],
  [
    "Medium",
    "VY dan WY ialah dua tangen dari titik luar Y kepada roda berdiameter 50 cm. Jika WY = 1.2 m, cari VY.",
    ["1.2 m", "0.6 m", "2.4 m", "0.25 m"],
    0,
  ],
  [
    "Medium",
    "Bulatan berpusat O mempunyai jejari 0.25 m. Y ialah titik luar dan VY ialah tangen sepanjang 1.2 m pada V. Hitung OY menggunakan Teorem Pythagoras.",
    ["≈1.23 m", "1.45 m", "1.2 m", "0.25 m"],
    0,
  ],
  [
    "Hard",
    "QS ialah diameter bulatan berpusat O. R terletak pada lilitan dan ∠QOR = 50°. Cari ∠QSR.",
    ["25°", "50°", "100°", "12.5°"],
    0,
  ],
  [
    "Hard",
    "QS ialah diameter bulatan dan P terletak pada lilitan. Jika ∠PSQ = 25°, cari ∠PQS.",
    ["65°", "25°", "90°", "155°"],
    0,
  ],
  [
    "Hard",
    "QS ialah diameter bulatan 16 cm. P terletak pada lilitan dan ∠PQS = 35°. Cari ∠PSQ.",
    ["55°", "35°", "70°", "20°"],
    0,
  ],
  [
    "Hard",
    "PR ialah diameter bulatan 16 cm. Q terletak pada lilitan dan ∠PRQ = 40°. Cari PQ, betul kepada 3 angka bererti.",
    ["10.3 cm", "12.3 cm", "8.00 cm", "16.0 cm"],
    0,
  ],
  [
    "Hard",
    "ABCD ialah sisi empat kitaran berpusat O. C terletak pada lengkok minor BD dan ∠BOD = 158°. D, C dan E segaris, dengan C di antara D dan E. Cari ∠BCE.",
    ["79°", "158°", "22°", "101°"],
    0,
  ],
  [
    "Hard",
    "PQRS ialah sisi empat kitaran dengan PS = PQ, ∠QPS = 72° dan ∠QSR = 36°. R, S dan T segaris, dengan S di antara R dan T. Cari ∠PST.",
    ["90°", "72°", "36°", "144°"],
    0,
  ],
  [
    "Hard",
    "A, B, C dan D terletak mengikut urutan pada bulatan. AD ialah diameter, lengkok minor AB = lengkok minor BC dan ∠BCD = 126°. Cari ∠BAC.",
    ["36°", "54°", "72°", "108°"],
    0,
  ],
  [
    "Hard",
    "PQ dan PR ialah tangen dari P kepada bulatan berpusat O yang berjejari 5 cm. S terletak pada lengkok major QR dan ∠QSR = 60°. Cari PQ, betul kepada 2 tempat perpuluhan.",
    ["8.66 cm", "5.00 cm", "10.00 cm", "2.50 cm"],
    0,
  ],
  [
    "Hard",
    "PQ ialah tangen dari titik luar P kepada bulatan berpusat O di Q. OQ = 5 cm. Ungkapkan OP dalam sebutan PQ.",
    ["√(25 + PQ²) cm", "√(25 − PQ²) cm", "(5 + PQ) cm", "PQ cm"],
    0,
  ],
  [
    "Hard",
    "RP ialah tangen dari R kepada bulatan berpusat O di P. OP = 3 cm dan ∠ORP = 25°. Cari ∠POR.",
    ["65°", "25°", "90°", "155°"],
    0,
  ],
  [
    "Hard",
    "SP ialah tangen dari S kepada bulatan berpusat O di P. OP = 3 cm dan ∠POS = 25°. Cari SP, betul kepada 2 tempat perpuluhan.",
    ["1.40 cm", "3.00 cm", "6.00 cm", "6.43 cm"],
    0,
  ],
  [
    "Hard",
    "K, L dan M terletak pada bulatan. PMN ialah tangen di M, dengan P dan L pada sisi bertentangan garis MK. Jika ∠KLM = 60°, cari ∠PMK.",
    ["60°", "30°", "90°", "120°"],
    0,
  ],
  [
    "Hard",
    "A, B dan L terletak pada bulatan. KL ialah tangen di L, dengan K dan B pada sisi bertentangan garis LA. Jika ∠KLA = 54°, cari ∠LBA.",
    ["54°", "60°", "126°", "36°"],
    0,
  ],
  [
    "Hard",
    "Tangen menyentuh bulatan di A dan AB ialah perentas. Sudut ACB dalam tembereng selang-seli ialah 52°. Cari sudut tirus antara tangen dan AB.",
    ["52°", "38°", "90°", "128°"],
    0,
  ],
  [
    "Hard",
    "ABCD ialah sisi empat kitaran. ∠ABC = 110° dan ∠CAD = 25°. AT ialah tangen di A, dengan T dan C pada sisi bertentangan garis AD. Cari ∠TAD.",
    ["85°", "25°", "70°", "95°"],
    0,
  ],
]);

export const mathF3C6QuizzesBM: QuizQuestion[] = buildForm3MathQuizSets(
  6,
  mathF3C6QuestionBankBM,
);
