import type { QuizCatalog } from "./buildQuizCatalog";

export const QUIZ_CATALOG_MIGRATION_PATTERN = /^\d{14}_(seed|sync)_quiz_catalog\.sql$/;

function literal(value: string | number | boolean): string {
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * Deterministic SQL that makes public.quiz_catalog match the app content:
 * upserts every quiz, deactivates quizzes that no longer exist (awards and
 * history that reference them are kept), and adds legacy key mappings.
 */
export function renderQuizCatalogSql(catalog: QuizCatalog): string {
  const quizRows = catalog.quizzes.map(
    (q) =>
      `  (${[
        q.quizKey,
        q.kind,
        q.formula,
        q.subjectId,
        q.form,
        q.chapterKey,
        q.lang,
        q.totalQuestions,
        q.easyCount,
        q.mediumCount,
        q.hardCount,
        q.timerBonusAllowed,
        q.maxXp,
      ]
        .map(literal)
        .join(", ")})`,
  );
  const legacyRows = catalog.legacyKeys.map(
    (row) => `  (${literal(row.legacyKey)}, ${literal(row.quizKey)})`,
  );

  return `-- GENERATED by scripts/generate-quiz-catalog.ts from app quiz content.
-- Do not edit by hand: change the content and run npm run generate:quiz-catalog.
-- ${catalog.quizzes.length} quizzes, ${catalog.legacyKeys.length} legacy key mappings.

insert into public.quiz_catalog (
  quiz_key, kind, formula, subject_id, form, chapter_key, lang,
  total_questions, easy_count, medium_count, hard_count,
  timer_bonus_allowed, max_xp
) values
${quizRows.join(",\n")}
on conflict (quiz_key) do update set
  kind = excluded.kind,
  formula = excluded.formula,
  subject_id = excluded.subject_id,
  form = excluded.form,
  chapter_key = excluded.chapter_key,
  lang = excluded.lang,
  total_questions = excluded.total_questions,
  easy_count = excluded.easy_count,
  medium_count = excluded.medium_count,
  hard_count = excluded.hard_count,
  timer_bonus_allowed = excluded.timer_bonus_allowed,
  max_xp = excluded.max_xp,
  is_active = true,
  updated_at = now();

update public.quiz_catalog
set is_active = false, updated_at = now()
where is_active
  and quiz_key <> all (array[
${catalog.quizzes.map((q) => `    ${literal(q.quizKey)}`).join(",\n")}
  ]::text[]);

insert into public.quiz_catalog_legacy_keys (legacy_key, quiz_key) values
${legacyRows.join(",\n")}
on conflict (legacy_key, quiz_key) do nothing;
`;
}
