import { useState, type ReactNode } from "react";
import { CheckCircle2, ChevronDown, Clock3, GraduationCap, Heart, Leaf, Lightbulb, MapPin, Play, Sparkles, Tag, Target, UserRound, Users } from "lucide-react";
import { JALAN_KE_PUNCAK as note } from "@/data/bm-form2-jalan-ke-puncak";

const icons = { summary: Clock3, theme: Sparkles, issues: Lightbulb, characters: Users, setting: MapPin, values: Heart, lessons: CheckCircle2, technique: Target, keywords: Tag, quiz: GraduationCap } as const;

function Section({ title, eyebrow, color, icon, children }: { title: string; eyebrow: string; color: string; icon: keyof typeof icons; children: ReactNode }) {
  const [open, setOpen] = useState(false); const Icon = icons[icon];
  return <section className="overflow-hidden border-b border-white/[0.06] last:border-0"><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} className="flex min-h-20 w-full items-center justify-between gap-4 px-1 py-5 text-left transition-colors hover:bg-white/[0.025] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-emerald-300/60 sm:px-2"><span className="flex min-w-0 items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border" style={{ color, background: `${color}12`, borderColor: `${color}28` }}><Icon className="h-5 w-5" /></span><span><span className="block text-[9px] font-black uppercase tracking-[0.2em]" style={{ color }}>{eyebrow}</span><span className="mt-1 block font-display text-base font-bold text-white sm:text-lg">{title}</span></span></span><ChevronDown className="h-5 w-5 shrink-0 transition-transform duration-300 motion-reduce:transition-none" style={{ color, transform: open ? "rotate(180deg)" : undefined }} /></button><div className="grid transition-[grid-template-rows,opacity] duration-300 ease-out motion-reduce:transition-none" style={{ gridTemplateRows: open ? "1fr" : "0fr", opacity: open ? 1 : 0 }}><div className="overflow-hidden"><div className="pb-7 pt-1">{children}</div></div></div></section>;
}

function Fold({ title, color, children }: { title: string; color: string; children: ReactNode }) {
  const [open, setOpen] = useState(false);
  return <article className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.03]"><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} className="flex min-h-14 w-full items-center justify-between gap-3 px-4 py-3 text-left transition-colors hover:bg-white/[0.045] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-white/30"><span className="text-sm font-bold text-white">{title}</span><ChevronDown className="h-4 w-4 shrink-0 transition-transform duration-300 motion-reduce:transition-none" style={{ color, transform: open ? "rotate(180deg)" : undefined }} /></button><div className="grid transition-[grid-template-rows,opacity] duration-300 ease-out motion-reduce:transition-none" style={{ gridTemplateRows: open ? "1fr" : "0fr", opacity: open ? 1 : 0 }}><div className="overflow-hidden"><div className="border-t border-white/[0.06] p-4">{children}</div></div></div></article>;
}

function Label({ children, tone = "sky" }: { children: ReactNode; tone?: "sky" | "amber" | "emerald" }) { const styles = { sky: "bg-sky-300/[0.1] text-sky-200", amber: "bg-amber-300/[0.1] text-amber-200", emerald: "bg-emerald-300/[0.1] text-emerald-200" }; return <span className={`inline-flex rounded-md px-2 py-1 text-[9px] font-black uppercase tracking-widest ${styles[tone]}`}>{children}</span>; }

function Answer({ point, event, type, character }: { point: string; event: string; type: "persoalan" | "perwatakan" | "latar" | "nilai" | "pengajaran"; character?: string }) {
  const lead = type === "persoalan" ? `Antara persoalan yang terdapat dalam novel ialah ${point.toLowerCase()}.` : type === "perwatakan" ? `${character} seorang yang ${point.toLowerCase()}.` : type === "latar" ? `Antara latar yang terdapat dalam novel ialah ${point.toLowerCase()}.` : type === "nilai" ? `Antara nilai yang terdapat dalam novel ialah nilai ${point.toLowerCase()}.` : `${point}.`;
  const label = type === "perwatakan" ? "Perwatakan" : type === "latar" ? "Latar" : type === "nilai" ? "Nilai" : type === "pengajaran" ? "Pengajaran" : "Persoalan";
  return <div className="space-y-3 text-sm leading-6"><div><Label>{label}</Label><p className="mt-1.5 font-semibold text-white/80">{point}</p></div><div className="rounded-xl border border-amber-300/15 bg-amber-300/[0.055] p-3"><Label tone="amber">Contoh Peristiwa</Label><p className="mt-1.5 text-white/70">{event}</p></div><div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[0.055] p-3"><Label tone="emerald">Ayat Jawapan Siap Guna</Label><p className="mt-1.5 text-white/75">{lead} Contohnya, {event.charAt(0).toLowerCase() + event.slice(1)}</p></div></div>;
}

const keywords = ["Laiman", "Milan", "Pak Kiassim", "Soniah", "Kampung Kusilad", "Shell", "Ladang Tembikai", "Kolam Ikan Air Tawar", "Berdikari", "Usahawan Tani"];
const checks = ["Apakah tema utama novel ini?", "Mengapakah Laiman menolak tawaran kerja kerajaan?", "Nyatakan satu perwatakan Laiman berserta contoh.", "Nyatakan satu nilai berserta contoh peristiwa.", "Nyatakan satu pengajaran berserta contoh."];

export function BMForm2JalanKePuncakContent() {
  return <div>
    <section className="relative mb-3 overflow-hidden rounded-2xl border border-emerald-300/20 bg-[#0e1714] p-5 sm:p-7"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_10%,rgba(52,211,153,0.17),transparent_46%),radial-gradient(circle_at_10%_100%,rgba(251,191,36,0.08),transparent_42%)]" /><div className="relative flex items-start gap-4"><span className="hidden h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.1] text-emerald-300 sm:flex"><Leaf className="h-7 w-7" /></span><div><div className="mb-3 flex flex-wrap gap-2"><span className="rounded-full border border-emerald-300/25 bg-emerald-300/[0.08] px-3 py-1 text-[10px] font-black uppercase tracking-wider text-emerald-200">KOMSAS Novel</span><span className="rounded-full border border-amber-300/25 bg-amber-300/[0.08] px-3 py-1 text-[10px] font-black uppercase tracking-wider text-amber-200">Fokus UASA</span></div><h1 className="font-display text-3xl font-black text-white sm:text-4xl">Jalan ke Puncak</h1><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-white/50"><span className="inline-flex items-center gap-1.5"><UserRound className="h-3.5 w-3.5" /> Laiman</span><span className="inline-flex items-center gap-1.5"><GraduationCap className="h-3.5 w-3.5" /> Tingkatan 2</span></div><p className="mt-4 max-w-2xl text-sm leading-7 text-white/65">{note.focus}</p></div></div></section>
    <Section title="Ringkasan Cerita (30 Saat)" eyebrow="Aliran cerita sahaja" color="#34D399" icon="summary"><div className="mx-auto max-w-xl space-y-2">{note.summary.map((item, i) => <div key={item}><div className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.055] px-4 py-3 text-center text-sm font-semibold text-white/80">{item}</div>{i < note.summary.length - 1 && <div className="py-1 text-center text-emerald-300/45">↓</div>}</div>)}</div></Section>
    <Section title="Tema Wajib Hafal" eyebrow="Wajib Hafal" color="#F472B6" icon="theme"><div className="rounded-2xl border border-pink-300/20 bg-pink-300/[0.065] p-5"><Label>Tema</Label><p className="mt-2 font-display text-lg font-bold leading-8 text-white">{note.theme.point}</p><div className="mt-4 rounded-xl border border-amber-300/15 bg-amber-300/[0.055] p-3"><Label tone="amber">Contoh Peristiwa</Label><p className="mt-2 text-sm leading-6 text-white/70">{note.theme.event}</p></div><div className="mt-3 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.055] p-3"><Label tone="emerald">Ayat Jawapan Siap Guna</Label><p className="mt-2 text-sm leading-6 text-white/75">Tema utama novel ialah {note.theme.point.charAt(0).toLowerCase() + note.theme.point.slice(1)} Contohnya, {note.theme.event.charAt(0).toLowerCase() + note.theme.event.slice(1)}</p></div></div></Section>
    <Section title="Persoalan Wajib Hafal" eyebrow="Wajib Hafal" color="#60A5FA" icon="issues"><div className="space-y-3">{note.issues.map(item => <Fold key={item.point} title={item.point} color="#60A5FA"><Answer {...item} type="persoalan" /></Fold>)}</div></Section>
    <Section title="Watak & Perwatakan Wajib Hafal" eyebrow="Wajib Hafal" color="#FBBF24" icon="characters">{(["Watak Utama", "Watak Sampingan"] as const).map(group => <div key={group} className="mb-5 last:mb-0"><h3 className="mb-3 font-bold text-white">{group}</h3><div className="space-y-3">{note.characters.filter(c => c.group === group).map(character => <Fold key={character.name} title={character.name} color="#FBBF24"><div className="space-y-4">{character.traits.map(trait => <Answer key={trait.point} {...trait} type="perwatakan" character={character.name} />)}</div></Fold>)}</div></div>)}</Section>
    <Section title="Latar Wajib Hafal" eyebrow="Wajib Hafal" color="#A78BFA" icon="setting"><div className="space-y-3">{(["tempat", "masa", "masyarakat"] as const).map(group => <Fold key={group} title={group.charAt(0).toUpperCase() + group.slice(1)} color="#A78BFA"><div className="space-y-4">{note.settings[group].map(item => <Answer key={item.point} {...item} type="latar" />)}</div></Fold>)}</div></Section>
    <Section title="Nilai Murni Wajib Hafal" eyebrow="Wajib Hafal" color="#FB7185" icon="values"><div className="space-y-3">{note.values.map(item => <Fold key={item.point} title={item.point} color="#FB7185"><Answer {...item} type="nilai" /></Fold>)}</div></Section>
    <Section title="Pengajaran Wajib Hafal" eyebrow="Wajib Hafal" color="#34D399" icon="lessons"><div className="space-y-3">{note.lessons.map(item => <Fold key={item.point} title={item.point} color="#34D399"><Answer {...item} type="pengajaran" /></Fold>)}</div></Section>
    <Section title="Teknik Menjawab Markah Penuh" eyebrow="Formula Markah Penuh" color="#FB923C" icon="technique"><div className="rounded-2xl border border-orange-300/20 bg-orange-300/[0.06] p-5"><div className="grid gap-2 text-center sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><div className="rounded-xl bg-sky-300/[0.1] p-3 font-black text-sky-200">1. Nyatakan isi</div><span className="self-center text-white/30">→</span><div className="rounded-xl bg-amber-300/[0.1] p-3 font-black text-amber-200">2. Contoh peristiwa</div><span className="self-center text-white/30">→</span><div className="rounded-xl bg-emerald-300/[0.1] p-3 font-black text-emerald-200">3. Huraian</div></div><div className="mt-5 rounded-xl border border-white/[0.08] bg-black/10 p-4"><p className="text-[10px] font-black uppercase tracking-widest text-orange-200">Contoh jawapan lengkap</p><p className="mt-3 text-sm leading-7 text-white/75">Antara nilai yang terdapat dalam novel ini ialah nilai keberanian. Buktinya, Laiman berani mengambil risiko menjadi petani moden walaupun pada mulanya ditentang oleh bapanya. Hal ini menunjukkan bahawa keberanian penting untuk mengubah nasib hidup dan membina masa depan sendiri.</p></div></div></Section>
    <Section title="Kata Kunci Novel" eyebrow="Ulang kaji pantas" color="#34D399" icon="keywords"><div className="flex flex-wrap gap-2">{keywords.map(word => <span key={word} className="inline-flex items-center gap-1.5 rounded-full border border-emerald-300/20 bg-emerald-300/[0.08] px-3 py-2 text-xs font-bold text-emerald-200"><Tag className="h-3.5 w-3.5" />{word}</span>)}</div></Section>
    <Section title="Uji Diri Sebelum Kuiz" eyebrow="Semak hafalan" color="#C084FC" icon="quiz"><div className="space-y-2">{checks.map((question, i) => <div key={question} className="flex gap-3 rounded-xl border border-white/[0.07] bg-white/[0.03] p-3"><span className="font-black text-purple-300">{i + 1}</span><p className="text-sm font-semibold text-white/70">{question}</p></div>)}</div><a href="/quizzes" className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-emerald-500 to-cyan-500 px-5 py-3 text-sm font-black text-white shadow-lg shadow-emerald-500/15 transition hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300"><Play className="h-4 w-4 fill-current" />Mulakan Kuiz Novel</a></Section>
  </div>;
}
