import { useState } from "react";
import { BookOpen, Brain, CheckCircle2, ChevronDown, Lightbulb, PenLine, Star } from "lucide-react";
import { CorrectWrongExample, ExamSkillLanding, FinalChecklist, MissionPageShell, MissionSection, QuickScoreCard, WarningCard, type MissionDefinition } from "@/components/exam-skill/MissionLearning";

const modules: MissionDefinition[] = [
  { number: "01", kindLabel: "Modul", title: "Asas Karangan Pendek", description: "Fahami format, struktur dan teknik sebelum membuat latihan.", icon: Star, color: "#FBBF24" },
  { number: "02", kindLabel: "Modul", title: "Langkah Menulis Karangan", description: "Bina rangka, kembangkan maklumat dan semak jawapan.", icon: PenLine, color: "#38BDF8" },
  { number: "03", kindLabel: "Modul", title: "Contoh & Latihan", description: "Pelajari contoh UASA Tingkatan 2 secara langkah demi langkah.", icon: Brain, color: "#C084FC" },
];

const checklist = ["Kehendak soalan dijawab", "Semua isi digunakan", "Ayat lengkap dan gramatis", "Penanda wacana digunakan", "Ejaan disemak", "Tanda baca disemak", "50–80 patah perkataan"];

type Practice = { theme: string; title: string; information: string[]; outline: string[]; answer: string; expression?: string };
const practices: Practice[] = [
  { theme: "Tema 1 · Kesihatan", title: "Langkah-langkah Menjaga Kesihatan", information: ["mengamalkan pemakanan seimbang", "bersenam secara berkala", "tidur yang mencukupi", "menjaga kebersihan diri", "mendapatkan pemeriksaan kesihatan"], outline: ["Pendahuluan: kesihatan penting dalam kehidupan", "Isi 1: pemakanan seimbang", "Isi 2: bersenam secara berkala", "Isi 3: tidur yang mencukupi", "Kesimpulan/Harapan: amalan sihat berterusan", "Ungkapan: badan sihat jiwa cerdas"], answer: "Kesihatan merupakan anugerah yang perlu dijaga oleh setiap orang. Antara langkah yang boleh diamalkan ialah mengambil pemakanan seimbang setiap hari. Selain itu, kita hendaklah bersenam secara berkala untuk mengekalkan kecergasan badan. Seterusnya, tidur yang mencukupi juga penting agar tubuh sentiasa bertenaga. Kesimpulannya, semua amalan ini perlu diteruskan supaya badan sihat jiwa cerdas.", expression: "Badan sihat jiwa cerdas." },
  { theme: "Tema 2 · Pendidikan", title: "Kepentingan Membaca", information: ["menambah ilmu pengetahuan", "mengeratkan penguasaan bahasa", "mengisi masa lapang dengan manfaat", "membentuk minda yang kreatif", "melahirkan masyarakat berilmu"], outline: ["Pendahuluan: membaca amalan mulia", "Isi 1: menambah ilmu pengetahuan", "Isi 2: mengeratkan penguasaan bahasa", "Isi 3: mengisi masa lapang dengan manfaat", "Kesimpulan/Harapan: masyarakat berilmu", "Ungkapan: membaca jambatan ilmu"], answer: "Membaca merupakan amalan mulia yang banyak memberikan faedah kepada murid. Antaranya, membaca dapat menambah ilmu pengetahuan dalam pelbagai bidang. Selain itu, tabiat membaca juga dapat mengeratkan penguasaan bahasa seseorang. Di samping itu, masa lapang dapat diisi dengan aktiviti yang bermanfaat. Kesimpulannya, amalan membaca perlu dipupuk agar masyarakat yang berilmu dapat dilahirkan.", expression: "Membaca jambatan ilmu." },
  { theme: "Tema 3 · Alam Sekitar", title: "Langkah Menjaga Alam Sekitar", information: ["mengurangkan penggunaan plastik", "mengitar semula bahan buangan", "menjaga kebersihan kawasan", "menanam pokok", "mengelakkan pencemaran"], outline: ["Pendahuluan: alam sekitar perlu dijaga", "Isi 1: mengurangkan penggunaan plastik", "Isi 2: mengitar semula bahan buangan", "Isi 3: menanam pokok", "Kesimpulan/Harapan: mengelakkan pencemaran", "Ungkapan: alam dipelihara hidup sejahtera"], answer: "Alam sekitar perlu dijaga agar terus bersih dan nyaman. Antara langkahnya ialah mengurangkan penggunaan plastik dalam kehidupan seharian. Selain itu, kita hendaklah mengitar semula bahan buangan supaya sisa sampah dapat dikurangkan. Seterusnya, menanam pokok juga membantu mengekalkan keindahan alam. Kesimpulannya, semua pihak perlu bekerjasama untuk mengelakkan pencemaran.", expression: "Alam dipelihara hidup sejahtera." },
  { theme: "Tema 4 · Keselamatan Jalan Raya", title: "Langkah Keselamatan Semasa Menunggang Basikal", information: ["basikal pengangkutan popular murid", "memakai topi keledar", "memakai pakaian berwarna terang", "mematuhi lampu isyarat", "kepentingan keselamatan diri"], outline: ["Pendahuluan: basikal pengangkutan popular murid", "Isi 1: memakai topi keledar", "Isi 2: memakai pakaian berwarna terang", "Isi 3: mematuhi lampu isyarat", "Kesimpulan/Harapan: kepentingan keselamatan diri", "Ungkapan: keselamatan diutamakan"], answer: "Basikal merupakan pengangkutan yang popular dalam kalangan murid untuk ke sekolah. Oleh itu, beberapa langkah keselamatan perlu dipatuhi semasa menunggang basikal. Antaranya, penunggang mestilah memakai topi keledar bagi melindungi kepala daripada kecederaan. Selain itu, murid digalakkan memakai pakaian berwarna terang supaya mudah dilihat oleh pengguna jalan raya lain. Seterusnya, penunggang basikal wajib mematuhi lampu isyarat di setiap persimpangan. Kesimpulannya, langkah-langkah ini perlu diamalkan kerana keselamatan diri perlu sentiasa diutamakan.", expression: "Keselamatan diri diutamakan." },
  { theme: "Tema 5 · Sains dan Teknologi", title: "Faedah Aplikasi Pembelajaran dalam Talian", information: ["aplikasi pembelajaran semakin popular", "memudahkan proses pembelajaran", "boleh diakses pada bila-bila masa", "bahan interaktif disediakan", "pembelajaran kendiri digalakkan"], outline: ["Pendahuluan: aplikasi pembelajaran semakin popular", "Isi 1: memudahkan proses pembelajaran", "Isi 2: boleh diakses pada bila-bila masa", "Isi 3: bahan interaktif disediakan", "Kesimpulan/Harapan: pembelajaran kendiri digalakkan", "Ungkapan: teknologi memudahkan pembelajaran"], answer: "Aplikasi pembelajaran dalam talian semakin popular dalam kalangan murid pada masa kini. Penggunaannya dapat memudahkan proses pembelajaran murid di rumah dan di sekolah. Selain itu, aplikasi ini boleh diakses pada bila-bila masa mengikut kesesuaian murid. Di samping itu, pelbagai bahan interaktif seperti video dan kuiz turut disediakan untuk menarik minat murid. Kesimpulannya, penggunaan aplikasi ini wajar diperluaskan kerana pembelajaran kendiri perlu digalakkan dalam kalangan murid masa kini.", expression: "Teknologi memudahkan pembelajaran." },
  { theme: "Tema 6 · Ekonomi dan Keusahawanan", title: "Aktiviti Jualan Amal di Sekolah", information: ["jualan amal dianjurkan pihak sekolah", "murid menjual pelbagai barangan", "kerjasama semua kelas diperlukan", "keuntungan disalurkan kepada mangsa bencana", "semangat kasih sayang dipupuk"], outline: ["Pendahuluan: jualan amal dianjurkan pihak sekolah", "Isi 1: murid menjual pelbagai barangan", "Isi 2: kerjasama semua kelas diperlukan", "Isi 3: keuntungan disalurkan kepada mangsa bencana", "Kesimpulan/Harapan: semangat kasih sayang dipupuk", "Ungkapan: kasih sayang sesama insan"], answer: "Pihak sekolah telah menganjurkan aktiviti jualan amal bagi mengumpul dana kebajikan. Sehubungan itu, murid-murid menjual pelbagai barangan seperti kuih-muih dan barangan terpakai di gerai masing-masing. Selain itu, kerjasama semua kelas amat diperlukan bagi memastikan aktiviti ini berjalan lancar. Seterusnya, keuntungan yang diperoleh akan disalurkan kepada mangsa bencana alam yang memerlukan bantuan. Kesimpulannya, aktiviti ini amat bermakna kerana semangat kasih sayang sesama insan perlu dipupuk sejak di bangku sekolah.", expression: "Kasih sayang sesama insan." },
];

const extraPractices: Practice[] = [
  { theme: "Tema 7 · Alam Sekitar", title: "Kempen Cintai Alam Sekitar di Sekolah", information: ["kempen kitar semula dianjurkan", "mengumpul bahan buangan terpakai", "menanam pokok renek di kawasan sekolah", "membersihkan kawasan taman sekolah", "kesedaran menjaga alam sekitar"], outline: ["Pendahuluan: kempen kitar semula dianjurkan", "Isi 1: mengumpul bahan buangan terpakai", "Isi 2: menanam pokok renek di kawasan sekolah", "Isi 3: membersihkan kawasan taman sekolah", "Kesimpulan/Harapan: kesedaran menjaga alam sekitar", "Ungkapan: alam sekitar tanggungjawab bersama"], answer: "Pihak sekolah telah menganjurkan kempen kitar semula untuk memupuk kesedaran menjaga alam sekitar. Sehubungan itu, murid-murid mengumpul bahan buangan terpakai seperti botol plastik dan kertas lama. Selain itu, sebahagian murid menanam pokok renek di kawasan sekolah bagi menambahkan kehijauan. Di samping itu, aktiviti membersihkan kawasan taman sekolah turut dijalankan setiap minggu. Kesimpulannya, kempen ini diharapkan dapat memupuk kesedaran menjaga alam sekitar dalam kalangan murid kerana alam sekitar merupakan tanggungjawab bersama.", expression: "Alam sekitar tanggungjawab bersama." },
  { theme: "Tema 8 · Keselamatan Jalan Raya", title: "Langkah Keselamatan Semasa Menunggang Basikal", information: ["basikal pengangkutan popular murid", "memakai topi keledar", "memakai pakaian berwarna terang", "mematuhi lampu isyarat", "kepentingan keselamatan diri"], outline: ["Pendahuluan: basikal pengangkutan popular murid", "Isi 1: memakai topi keledar", "Isi 2: memakai pakaian berwarna terang", "Isi 3: mematuhi lampu isyarat", "Kesimpulan/Harapan: kepentingan keselamatan diri", "Ungkapan: keselamatan diutamakan"], answer: "Basikal merupakan pengangkutan yang popular dalam kalangan murid untuk ke sekolah. Oleh itu, beberapa langkah keselamatan perlu dipatuhi semasa menunggang basikal. Antaranya, penunggang mestilah memakai topi keledar bagi melindungi kepala daripada kecederaan. Selain itu, murid digalakkan memakai pakaian berwarna terang supaya mudah dilihat oleh pengguna jalan raya lain. Seterusnya, penunggang basikal wajib mematuhi lampu isyarat di setiap persimpangan. Kesimpulannya, langkah-langkah ini perlu diamalkan kerana keselamatan diri perlu sentiasa diutamakan.", expression: "Keselamatan diri diutamakan." },
  { theme: "Tema 9 · Sains dan Teknologi", title: "Faedah Aplikasi Pembelajaran dalam Talian", information: ["aplikasi pembelajaran semakin popular", "memudahkan proses pembelajaran", "boleh diakses pada bila-bila masa", "bahan interaktif disediakan", "pembelajaran kendiri digalakkan"], outline: ["Pendahuluan: aplikasi pembelajaran semakin popular", "Isi 1: memudahkan proses pembelajaran", "Isi 2: boleh diakses pada bila-bila masa", "Isi 3: bahan interaktif disediakan", "Kesimpulan/Harapan: pembelajaran kendiri digalakkan", "Ungkapan: teknologi memudahkan pembelajaran"], answer: "Aplikasi pembelajaran dalam talian semakin popular dalam kalangan murid pada masa kini. Penggunaannya dapat memudahkan proses pembelajaran murid di rumah dan di sekolah. Selain itu, aplikasi ini boleh diakses pada bila-bila masa mengikut kesesuaian murid. Di samping itu, pelbagai bahan interaktif seperti video dan kuiz turut disediakan untuk menarik minat murid. Kesimpulannya, penggunaan aplikasi ini wajar diperluaskan kerana pembelajaran kendiri perlu digalakkan dalam kalangan murid masa kini.", expression: "Teknologi memudahkan pembelajaran." },
  { theme: "Tema 10 · Ekonomi dan Keusahawanan", title: "Aktiviti Jualan Amal di Sekolah", information: ["jualan amal dianjurkan pihak sekolah", "murid menjual pelbagai barangan", "kerjasama semua kelas diperlukan", "keuntungan disalurkan kepada mangsa bencana", "semangat kasih sayang dipupuk"], outline: ["Pendahuluan: jualan amal dianjurkan pihak sekolah", "Isi 1: murid menjual pelbagai barangan", "Isi 2: kerjasama semua kelas diperlukan", "Isi 3: keuntungan disalurkan kepada mangsa bencana", "Kesimpulan/Harapan: semangat kasih sayang dipupuk", "Ungkapan: kasih sayang sesama insan"], answer: "Pihak sekolah telah menganjurkan aktiviti jualan amal bagi mengumpul dana kebajikan. Sehubungan itu, murid-murid menjual pelbagai barangan seperti kuih-muih dan barangan terpakai di gerai masing-masing. Selain itu, kerjasama semua kelas amat diperlukan bagi memastikan aktiviti ini berjalan lancar. Seterusnya, keuntungan yang diperoleh akan disalurkan kepada mangsa bencana alam yang memerlukan bantuan. Kesimpulannya, aktiviti ini amat bermakna kerana semangat kasih sayang sesama insan perlu dipupuk sejak di bangku sekolah.", expression: "Kasih sayang sesama insan." },
];
const allPractices = [...practices, ...extraPractices];

function PracticeCard({ practice, index }: { practice: Practice; index: number }) {
  const [showAnswer, setShowAnswer] = useState(false);
  return <article className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.025]"><div className="p-5"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-purple-300">Latihan {index + 1} · {practice.theme}</p><h3 className="mt-2 font-display text-lg font-bold leading-7 text-white">{practice.title}</h3><div className="mt-4"><p className="text-[10px] font-black uppercase tracking-widest text-sky-300">Maklumat</p><div className="mt-2 flex flex-wrap gap-2">{practice.information.map(item => <span key={item} className="rounded-lg border border-sky-300/15 bg-sky-300/[0.05] px-3 py-2 text-xs leading-5 text-sky-100">{item}</span>)}</div></div><button type="button" onClick={() => setShowAnswer(value => !value)} aria-expanded={showAnswer} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-purple-300/20 bg-purple-300/[0.08] px-4 text-sm font-bold text-purple-100 transition-colors hover:bg-purple-300/[0.13] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-300/60">{showAnswer ? "Sembunyikan Jawapan" : "Lihat Jawapan"}<ChevronDown className={`h-4 w-4 transition-transform duration-300 motion-reduce:transition-none ${showAnswer ? "rotate-180" : ""}`} /></button></div><div className="grid transition-[grid-template-rows,opacity] duration-300 motion-reduce:transition-none" style={{ gridTemplateRows: showAnswer ? "1fr" : "0fr", opacity: showAnswer ? 1 : 0 }}><div className="overflow-hidden"><div className="space-y-4 border-t border-white/[0.06] p-5"><div><p className="text-[10px] font-black uppercase tracking-widest text-amber-300">Rangka Karangan</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{practice.outline.map(item => <p key={item} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-3 text-sm leading-6 text-white/65">{item}</p>)}</div></div><div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[0.04] p-4"><p className="text-[10px] font-black uppercase tracking-widest text-emerald-300">Contoh Karangan Lengkap</p><p className="mt-2 text-sm leading-7 text-white/75">{practice.answer}</p></div><QuickScoreCard items={["Semua maklumat digunakan", "Penanda wacana digunakan", "Bahasa gramatis", "Had 50–80 patah perkataan dipatuhi"]} />{practice.expression && <p className="flex items-start gap-2 text-sm text-amber-100"><Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" />Ungkapan: {practice.expression}</p>}</div></div></div></article>;
}

function UasaExampleCard({ practice, index }: { practice: Practice; index: number }) {
  const [open, setOpen] = useState(false);
  return <article className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.025]">
    <button type="button" onClick={() => setOpen(value => !value)} aria-expanded={open} className="flex min-h-20 w-full items-center justify-between gap-4 p-5 text-left transition-colors hover:bg-white/[0.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-purple-300/50">
      <span><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-purple-300">Contoh {String(index + 1).padStart(2, "0")} · {practice.theme}</span><span className="mt-2 block font-display text-base font-bold leading-6 text-white">{practice.title}</span></span><ChevronDown className={`h-5 w-5 shrink-0 text-purple-300 transition-transform duration-300 motion-reduce:transition-none ${open ? "rotate-180" : ""}`} />
    </button>
    <div className="grid transition-[grid-template-rows,opacity] duration-300 motion-reduce:transition-none" style={{ gridTemplateRows: open ? "1fr" : "0fr", opacity: open ? 1 : 0 }}><div className="overflow-hidden"><div className="space-y-5 border-t border-white/[0.06] p-5">
      <div className="grid gap-3 sm:grid-cols-2"><InfoBlock label="1 · Tema" text={practice.theme} color="#C084FC" /><InfoBlock label="2 · Soalan" text="Berdasarkan maklumat yang disediakan, tulis sebuah karangan pendek antara 50 hingga 80 patah perkataan." color="#60A5FA" /></div>
      <div><p className="text-[10px] font-black uppercase tracking-widest text-cyan-300">3 · Bahan Grafik</p><div className="mt-2 flex flex-wrap gap-2">{practice.information.map(item => <span key={item} className="rounded-lg border border-cyan-300/15 bg-cyan-300/[0.05] px-3 py-2 text-xs leading-5 text-cyan-100">{item}</span>)}</div></div>
      <InfoBlock label="4 · Cara Berfikir" text="Kenal pasti tema, gunakan semua maklumat dan susun isi sebelum menulis." color="#FBBF24" />
      <div><p className="text-[10px] font-black uppercase tracking-widest text-amber-300">5 · Langkah 1 — Rangka</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{practice.outline.map(item => <p key={item} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-3 text-sm leading-6 text-white/65">{item}</p>)}</div></div>
      <div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[0.04] p-4"><p className="text-[10px] font-black uppercase tracking-widest text-emerald-300">6 · Langkah 2 — Model Jawapan</p><p className="mt-2 text-sm leading-7 text-white/75">{practice.answer}</p></div>
      <QuickScoreCard items={["Semua isi digunakan", "Ayat gramatis", "Penanda wacana digunakan", "Had perkataan dipatuhi"]} />
      <CorrectWrongExample wrong="Menyalin kata kunci tanpa membina ayat lengkap." right="Menghubungkan semua isi dengan ayat gramatis dan penanda wacana." />
    </div></div></div>
  </article>;
}

function InfoBlock({ label, text, color }: { label: string; text: string; color: string }) {
  return <div className="rounded-xl border bg-white/[0.025] p-4" style={{ borderColor: `${color}25` }}><p className="text-[10px] font-black uppercase tracking-widest" style={{ color }}>{label}</p><p className="mt-2 text-sm leading-6 text-white/65">{text}</p></div>;
}

export function BMForm2KaranganPendekContent({ initialSectionId, onBack }: { initialSectionId?: string; onBack?: () => void } = {}) {
  const sectionMap: Record<string, number> = { asas: 0, "langkah-menulis": 1, "contoh-latihan": 2 };
  const initialModule = initialSectionId ? (sectionMap[initialSectionId] ?? null) : null;
  const [activeModule, setActiveModule] = useState<number | null>(initialModule);
  const [checked, setChecked] = useState(() => checklist.map(() => false));
  if (activeModule === null) return <ExamSkillLanding title="Karangan Pendek" subtitle="Bahagian A: Kuasai karangan 50–80 patah perkataan langkah demi langkah." missions={modules} onSelect={setActiveModule} />;
  const module = modules[activeModule];
  return <MissionPageShell mission={module} onBack={() => onBack ? onBack() : setActiveModule(null)}>
    {activeModule === 0 && <>
      <section className="rounded-2xl border border-indigo-300/20 bg-indigo-300/[0.05] p-5"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-indigo-300">Mission Brief</p><p className="mt-2 text-sm leading-7 text-white/70">Kuasai format, susun semua isi dan hasilkan karangan lengkap antara 50 hingga 80 patah perkataan.</p></section>
      <MissionSection title="Apa Itu Karangan Pendek" color={module.color}><div className="grid gap-3 sm:grid-cols-3">{[["Tujuan", "Mengembangkan maklumat yang disediakan menjadi sebuah karangan."], ["Panjang", "50 hingga 80 patah perkataan"], ["Format", "Bahagian A · Kertas 2"]].map(([label, text]) => <div key={label} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-4"><p className="text-[10px] font-black uppercase tracking-widest text-amber-300">{label}</p><p className="mt-2 text-sm leading-6 text-white/70">{text}</p></div>)}</div></MissionSection>
      <MissionSection title="Struktur Karangan" color="#38BDF8"><div className="mx-auto max-w-lg space-y-2">{["Pendahuluan", "Isi 1", "Isi 2", "Isi 3", "Kesimpulan / Harapan", "Ungkapan Menarik"].map((item, index, list) => <div key={item}><div className="rounded-xl border border-sky-300/15 bg-sky-300/[0.05] p-3 text-center text-sm font-bold text-white/75">{item}</div>{index < list.length - 1 && <div className="py-1 text-center text-sky-300/30">↓</div>}</div>)}</div></MissionSection>
      <MissionSection title="Formula 10/10" color="#34D399"><QuickScoreCard items={checklist} /></MissionSection>
      <MissionSection title="Cara Membina Rangka" color="#A78BFA"><div className="grid gap-2 sm:grid-cols-2">{["Pendahuluan: nyatakan tema", "Isi 1: maklumat pertama", "Isi 2: maklumat kedua", "Isi 3: maklumat ketiga", "Kesimpulan: harapan", "Ungkapan: frasa yang sesuai"].map(item => <p key={item} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-3 text-sm text-white/65">{item}</p>)}</div></MissionSection>
      <MissionSection title="Formula Berfikir" color="#FBBF24"><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{["Baca Soalan", "Kenal pasti Tema", "Kenal pasti Isi", "Susun Isi", "Tulis", "Semak"].map((item, index) => <div key={item} className="rounded-xl border border-amber-300/15 bg-amber-300/[0.05] p-3 text-center"><p className="text-[10px] font-black text-amber-300">0{index + 1}</p><p className="mt-1 text-xs font-bold leading-5 text-white/70">{item}</p></div>)}</div></MissionSection>
      <MissionSection title="Penanda Wacana" color="#22D3EE"><div className="flex flex-wrap gap-2">{["Permulaan", "Selain itu", "Seterusnya", "Di samping itu", "Akhir sekali", "Kesimpulannya"].map(item => <span key={item} className="rounded-lg border border-cyan-300/15 bg-cyan-300/[0.06] px-3 py-2 text-xs font-bold text-cyan-100">{item}</span>)}</div></MissionSection>
      <MissionSection title="Ungkapan Menarik" color="#F472B6"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{["Pendidikan", "Kesihatan", "Alam Sekitar", "Patriotisme", "Perpaduan", "Teknologi", "Masyarakat"].map(item => <div key={item} className="rounded-xl border border-pink-300/15 bg-pink-300/[0.04] p-3 text-sm font-bold text-pink-100">{item}</div>)}</div></MissionSection>
      <section className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.05] p-5"><p className="text-[10px] font-black uppercase tracking-widest text-amber-300">Tip Guru · Jika tinggal 15 minit</p><div className="mt-3 grid gap-2 sm:grid-cols-3">{["3 minit bina rangka", "10 minit menulis", "2 minit semak"].map(item => <p key={item} className="rounded-xl bg-black/10 p-3 text-sm font-semibold text-white/70">{item}</p>)}</div></section>
      <MissionSection title="Kesalahan Lazim" color="#FB7185"><div className="space-y-3"><CorrectWrongExample wrong="Tertinggal isi daripada bahan grafik." right="Gunakan semua isi yang diberikan." /><CorrectWrongExample wrong="Menyusun kata kunci tanpa ayat lengkap." right="Kembangkan isi menggunakan ayat gramatis." /></div></MissionSection>
      <MissionSection title="Checklist Sebelum Hantar" color="#34D399"><FinalChecklist items={checklist} checked={checked} onToggle={index => setChecked(current => current.map((value, i) => i === index ? !value : value))} /></MissionSection>
    </>}
    {activeModule === 1 && <>
      <MissionSection title="Langkah 1 · Kenal Pasti Kehendak Soalan" color={module.color}><p className="text-sm leading-7 text-white/65">Baca arahan dan tandakan tema serta bentuk tugasan yang perlu ditulis.</p></MissionSection>
      <MissionSection title="Langkah 2 · Kenal Pasti Semua Isi" color="#C084FC"><div className="grid gap-2 sm:grid-cols-2">{practices[0].information.map(item => <p key={item} className="flex min-h-11 items-center gap-2 rounded-xl border border-white/[0.07] bg-white/[0.03] px-3 text-sm text-white/65"><CheckCircle2 className="h-4 w-4 shrink-0 text-purple-300" />{item}</p>)}</div></MissionSection>
      <MissionSection title="Langkah 3 · Susun Isi" color="#FBBF24"><div className="grid gap-2 sm:grid-cols-2">{practices[0].outline.map(item => <p key={item} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-3 text-sm leading-6 text-white/65">{item}</p>)}</div></MissionSection>
      <MissionSection title="Langkah 4 · Tulis Pendahuluan" color="#60A5FA"><p className="rounded-xl border border-sky-300/15 bg-sky-300/[0.05] p-4 text-sm leading-7 text-white/70">Mulakan karangan dengan ayat yang memperkenalkan tema berdasarkan bahan grafik.</p></MissionSection>
      <MissionSection title="Langkah 5 · Kembangkan Isi" color="#C084FC"><div className="grid gap-2 sm:grid-cols-2">{["Gunakan ayat sendiri", "Gunakan penanda wacana", "Sambungkan isi mengikut urutan", "Gunakan ungkapan menarik"].map(item => <p key={item} className="flex min-h-11 items-center gap-2 rounded-xl border border-white/[0.07] bg-white/[0.03] px-3 text-sm text-white/65"><CheckCircle2 className="h-4 w-4 shrink-0 text-purple-300" />{item}</p>)}</div></MissionSection>
      <MissionSection title="Langkah 6 · Tulis Kesimpulan" color="#F472B6"><p className="rounded-xl border border-pink-300/15 bg-pink-300/[0.05] p-4 text-sm leading-7 text-white/70">Akhiri karangan dengan kesimpulan atau harapan yang berkaitan dengan tema.</p></MissionSection>
      <MissionSection title="Langkah 7 · Semak Semula" color="#34D399"><FinalChecklist items={["Semua isi digunakan", "Ayat lengkap", "Penanda wacana digunakan", "Tidak melebihi 80 patah perkataan", "Ejaan disemak"]} checked={checked.slice(0, 5)} onToggle={index => setChecked(current => current.map((value, i) => i === index ? !value : value))} /></MissionSection>
      <WarningCard items={["Tertinggal maklumat yang diberikan", "Ayat tidak lengkap", "Tiada penanda wacana", "Melebihi 80 patah perkataan", "Ejaan dan tanda baca tidak disemak"]} />
    </>}
    {activeModule === 2 && <>
      <div className="space-y-4">{allPractices.map((practice, index) => <UasaExampleCard key={`${practice.title}-${index}`} practice={practice} index={index} />)}</div>
      <MissionSection title="Mini Bank Ulang Kaji" color="#22D3EE"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{["Penanda Wacana", "Ungkapan Menarik", "Frasa Gramatis", "Kata Hubung", "Kosa Kata Berimpak Tinggi"].map(item => <div key={item} className="rounded-xl border border-cyan-300/15 bg-cyan-300/[0.05] p-3 text-sm font-bold text-cyan-100">{item}</div>)}</div></MissionSection>
      <section className="rounded-[1.75rem] border border-amber-300/25 bg-gradient-to-br from-amber-300/[0.1] to-purple-300/[0.05] p-6"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-amber-300">1 Minit Sebelum Masuk Dewan Peperiksaan</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{["Formula 10/10", "Struktur Karangan", "Penanda Wacana", "Ungkapan Menarik", "Checklist Akhir"].map(item => <p key={item} className="rounded-xl border border-white/[0.08] bg-black/10 p-3 text-sm font-bold text-white/75">★ {item}</p>)}</div></section>
    </>}
  </MissionPageShell>;
}
