import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c4-bm-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 4",
    lang: "bm",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C4QuizzesBM: QuizQuestion[] = buildQuiz([
  ["Easy", "Apakah maksud lukisan berskala?", ["Lukisan objek dengan semua ukuran berkadaran dengan ukuran objek", "Lukisan tanpa sebarang skala", "Lukisan yang berbeza bentuk daripada objek", "Lukisan yang lebih besar sahaja"], 0],
  ["Easy", "Apakah formula skala?", ["Ukuran lukisan berskala / Ukuran objek", "Ukuran objek / Ukuran lukisan berskala", "Ukuran lukisan + ukuran objek", "Ukuran lukisan - ukuran objek"], 0],
  ["Easy", "Skala biasa ditulis dalam bentuk apa?", ["1 : n", "n : 1", "1 + n", "n - 1"], 0],
  ["Easy", "Jika n < 1, bagaimanakah saiz lukisan berskala?", ["Lebih besar daripada objek", "Lebih kecil daripada objek", "Sama dengan objek", "Tidak dapat ditentukan"], 0],
  ["Easy", "Jika n > 1, bagaimanakah saiz lukisan berskala?", ["Lebih kecil daripada objek", "Lebih besar daripada objek", "Sama dengan objek", "Tidak dapat ditentukan"], 0],
  ["Easy", "Jika n = 1, bagaimanakah saiz lukisan berskala?", ["Sama dengan objek", "Lebih besar", "Lebih kecil", "Tidak tentu"], 0],
  ["Easy", "Adakah sudut berubah dalam lukisan berskala?", ["Tidak, sudut kekal sama", "Ya, sudut berubah mengikut skala", "Kadangkala berubah", "Hanya berubah jika n=1"], 0],
  ["Easy", "P'Q'=2, PQ=4. Tentukan skala.", ["1 : 2", "2 : 1", "1 : 4", "4 : 1"], 0],
  ["Easy", "K'L'=9, KL=3. Tentukan skala dalam bentuk n:1.", ["3 : 1", "1 : 3", "9 : 1", "1 : 9"], 0],
  ["Easy", "Skala peta 1cm:10km. Jarak peta 2cm. Hitung jarak sebenar.", ["20 km", "10 km", "5 km", "2 km"], 0],
  ["Easy", "Skala 1:300 000. Jarak peta 3cm. Hitung jarak sebenar (km).", ["9 km", "3 km", "30 km", "300 km"], 0],
  ["Easy", "Apakah unit asas yang perlu ditukar semasa kira jarak sebenar peta?", ["cm kepada km", "kg kepada g", "liter kepada ml", "saat kepada minit"], 0],
  ["Easy", "1 km bersamaan berapa cm?", ["100 000 cm", "1 000 cm", "10 000 cm", "1 000 000 cm"], 0],
  ["Easy", "Apakah tiga cara melukis lukisan berskala?", ["Grid sama saiz skala berlainan, grid berlainan saiz, kertas kosong", "Hanya menggunakan pensel", "Hanya menggunakan pembaris", "Hanya menggunakan jangka lukis"], 0],
  ["Easy", "Bagi grid berlainan saiz dengan bilangan unit sisi sama, apakah digunakan untuk kira skala?", ["Saiz grid (bukan bilangan unit)", "Bilangan unit sahaja", "Luas grid", "Perimeter grid"], 0],
  ["Easy", "Khairul lukis segi empat sama skala 1:1/3. Sisi sebenar 6cm. Hitung sisi lukisan.", ["18 cm", "2 cm", "6 cm", "3 cm"], 0],
  ["Easy", "Apakah formula luas sebenar berbanding luas lukisan?", ["Luas sebenar = (nisbah panjang)² x luas lukisan", "Luas sebenar = nisbah panjang x luas lukisan", "Luas sebenar = luas lukisan / nisbah panjang", "Luas sebenar = luas lukisan - nisbah panjang"], 0],
  ["Easy", "Bilik 7cm x 5cm pada skala 1:400. Hitung lebar sebenar dalam m.", ["20 m", "28 m", "2 000 m", "0.05 m"], 0],
  ["Easy", "Apakah bidang yang banyak menggunakan lukisan berskala?", ["Arkitek, kejuruteraan, fotografi", "Muzik dan seni lukis abstrak", "Sukan dan permainan", "Memasak dan resipi"], 0],
  ["Easy", "Apakah ciri yang dikekalkan dalam lukisan berskala?", ["Bentuk (sudut sama)", "Saiz (sama besar)", "Warna", "Bahan"], 0],

  ["Medium", "Grid lukisan 2cm, grid objek 1cm, bilangan unit sisi sama. Tentukan skala dalam bentuk 1:n.", ["1 : 0.5 (atau 2:1)", "1 : 2", "2 : 2", "1 : 1"], 0],
  ["Medium", "Grid lukisan 0.5cm, grid objek 1cm. Tentukan skala dalam bentuk 1:n.", ["1 : 2", "1 : 0.5", "2 : 1", "0.5 : 0.5"], 0],
  ["Medium", "K'N'=2.5cm (dari Pythagoras), KN=5cm. Tentukan skala dalam bentuk 1:n.", ["1 : 2", "1 : 0.5", "2 : 1", "2.5 : 5"], 0],
  ["Medium", "Peta negeri Johor skala 1cm:10km, jarak Kluang-Ayer Hitam 2cm pada peta. Hitung jarak sebenar.", ["20 km", "10 km", "2 km", "12 km"], 0],
  ["Medium", "Poster 24cm panjang dan 8cm lebar dilukis dengan skala 1:4. Hitung panjang lukisan berskala.", ["6 cm", "96 cm", "24 cm", "4 cm"], 0],
  ["Medium", "Daripada soalan di atas, hitung lebar lukisan berskala.", ["2 cm", "8 cm", "32 cm", "4 cm"], 0],
  ["Medium", "Peta skala 1:400 000, sungai 2.5cm pada peta. Hitung jarak sebenar (km).", ["10 km", "4 km", "100 km", "1 km"], 0],
  ["Medium", "Siew Lin lukis segi tiga skala 1:1/3, hipotenus lukisan 18cm. Hitung hipotenus sebenar.", ["6 cm", "54 cm", "3 cm", "18 cm"], 0],
  ["Medium", "Bilik segi empat tepat 7cm x 5cm skala 1:400. Hitung luas sebenar (m²).", ["560 m²", "35 m²", "1 400 m²", "280 m²"], 0],
  ["Medium", "Poligon sekata sudut peluaran 36° (jadi 10 sisi), skala 1:5, sisi sebenar 10cm. Hitung perimeter lukisan berskala.", ["20 cm (10 sisi x 2cm)", "50 cm", "100 cm", "10 cm"], 0],
  ["Medium", "Bilik 3.5m x 5.2m, lukisan berskala 1:50. Hitung perimeter lukisan dalam cm.", ["34.8 cm (2x(7+10.4))", "17.4 cm", "69.6 cm", "350 cm"], 0],
  ["Medium", "Padang segi empat tepat skala 1:2000, luas sebenar dikira daripada lukisan. Jika lukisan 3cm x 6cm, hitung luas sebenar (m²).", ["7 200 m² (60x120)", "3 600 m²", "18 m²", "360 m²"], 0],
  ["Medium", "Daripada soalan di atas, jika rumput dipotong 400m² dalam 8 minit, hitung masa keseluruhan.", ["144 minit (2 jam 24 minit)", "100 minit", "72 minit", "200 minit"], 0],
  ["Medium", "Bintulu-Miri 4cm pada peta skala 1cm:50km. Hitung jarak sebenar.", ["200 km", "50 km", "150 km", "20 km"], 0],
  ["Medium", "Daripada soalan di atas, peta dilukis semula skala 1:2 000 000. Hitung jarak baru pada peta (cm).", ["10 cm", "4 cm", "20 cm", "100 cm"], 0],
  ["Medium", "Daripada soalan di atas, jika dipandu pada 80km/j, hitung masa perjalanan.", ["2.5 jam (2 jam 30 minit)", "2 jam", "3 jam", "1.5 jam"], 0],
  ["Medium", "Bilik stor pada lukisan skala 1:400 berukuran 2cm x 3cm. Hitung luas sebenar (m²).", ["96 m² (8x12)", "24 m²", "600 m²", "48 m²"], 0],
  ["Medium", "Jika ketinggian rumah kedai sebenar 3.75m dan tapak rumah kedai 8m x 12m, hitung isi padu (m³).", ["360 m³", "96 m³", "45 m³", "180 m³"], 0],
  ["Medium", "Bunga dilukis pada grid 1cmx1cm, lukis objek sebenar pada grid 1.5cmx1.5cm. Apakah skala baru?", ["1 : 1.5 (objek lebih besar)", "1.5 : 1", "1 : 1", "1 : 0.5"], 0],
  ["Medium", "Bunga dilukis pada grid 1cmx1cm, lukis objek sebenar pada grid 0.5cmx0.5cm. Apakah skala baru?", ["1 : 0.5 (objek lebih kecil)", "0.5 : 1", "1 : 2", "2 : 1"], 0],

  ["Hard", "Segi tiga P (lukisan berskala bagi segi tiga Q) ada luas 112.5cm², Q ada luas 4.5cm². Hitung n jika skala 1:n.", ["n=5 (nisbah luas=25, nisbah panjang=5)", "n=25", "n=2.5", "n=10"], 0],
  ["Hard", "Bulatan berpusat O, diameter 6cm pada lukisan, skala 1:3. Hitung diameter sebenar.", ["18 cm", "2 cm", "9 cm", "6 cm"], 0],
  ["Hard", "Kuching-KK jarak peta 5.4cm, skala 1cm:150km, terbang dari 1240 hingga 1410 (90 minit). Hitung laju purata (km/j).", ["540 km/j (5.4x150=810km, /1.5j=540)", "810 km/j", "270 km/j", "150 km/j"], 0],
  ["Hard", "Ruang tamu skala 1:50, jubin 30cmx30cm RM2.80/keping berbanding jubin 50cmx50cm RM6/keping. Manakah lebih jimat per m²?", ["Jubin 50cmx50cm (RM6/0.25m²=RM24/m² berbanding RM2.80/0.09m²≈RM31.1/m²)", "Jubin 30cmx30cm lebih jimat", "Kedua sama", "Tidak dapat ditentukan"], 0],
  ["Hard", "Kolam ikan air tawar pada lukisan skala 1:2000 berbentuk bulatan radius 2cm. Hitung luas sebenar (m², guna π≈22/7).", ["Luas sebenar=π(40m)²≈5028.6 m²", "Luas sebenar=π(2m)²", "Luas sebenar=400 m²", "Luas sebenar=1600 m²"], 0],
  ["Hard", "Padang bola sepak Rajah 1 (7cmx12cm) skala 1:1000. Hitung luas sebenar (m²).", ["8 400 m² (70x120)", "84 m²", "840 m²", "10 080 m²"], 0],
  ["Hard", "Sharon ingin lukis semula Rajah 1 (7cmx12cm asal, 70mx120m sebenar) pada kertas A4 (29.7cmx21cm). Apakah skala maksimum munasabah (anggaran)?", ["Skala besar seperti 1:500 atau lebih supaya muat dalam A4", "Skala 1:1000 (skala asal, terlalu kecil untuk A4 jika ingin lebih besar)", "Skala 1:1 (terlalu besar, tidak muat)", "Tidak boleh dilukis pada A4"], 0],
  ["Hard", "5 khemah 5mx4m didirikan di padang 70mx120m (anggaran kawasan terhad untuk khemah). Anggarkan bilangan maksimum khemah jika kawasan khemah ialah separuh padang.", ["Anggaran: (70x120/2)/(5x4) = 210 khemah (pengiraan anggaran)", "10 khemah", "100 khemah", "50 khemah"], 0],
  ["Hard", "Sewa khemah RM100/hari, diskaun 25% jika sewa 5 hari atau lebih, disewa seminggu (7 hari). Hitung jumlah sewa seunit khemah.", ["RM525 (100x7x0.75)", "RM700", "RM600", "RM525.50"], 0],
  ["Hard", "Segi empat tepat S (3cmx5cm) dibandingkan dengan I,II,III,IV. Jika IV ialah 6cmx10cm, tentukan skala S:IV.", ["1 : 2", "2 : 1", "1 : 4", "4 : 1"], 0],
  ["Hard", "Daripada soalan di atas, hitung nisbah luas S kepada luas IV.", ["1 : 4 (kuasa dua nisbah panjang)", "1 : 2", "1 : 8", "1 : 16"], 0],
  ["Hard", "Apakah kesimpulan tepat tentang nisbah luas berbanding nisbah panjang dalam lukisan berskala?", ["Nisbah luas = (nisbah panjang)²", "Nisbah luas = nisbah panjang", "Nisbah luas = 2 x nisbah panjang", "Tiada perkaitan"], 0],
  ["Hard", "Bagi bentuk tiga dimensi, bagaimanakah nisbah isi padu berkait dengan nisbah panjang skala?", ["Nisbah isi padu = (nisbah panjang)³", "Nisbah isi padu = nisbah panjang", "Nisbah isi padu = (nisbah panjang)²", "Tiada perkaitan"], 0],
  ["Hard", "Apakah kesilapan jika seseorang mengira luas sebenar dengan terus mendarab luas lukisan dengan nisbah panjang (bukan kuasa dua)?", ["Akan memberi jawapan terlalu kecil/silap kerana luas memerlukan kuasa dua nisbah panjang", "Jawapan tetap betul", "Hanya salah untuk bentuk bulat", "Hanya salah untuk segi tiga"], 0],
  ["Hard", "Rumah kedai skala 1:400, bilik stor 2cmx3cm pada lukisan, ketinggian sebenar 3.75m. Jika tapak rumah kedai 8mx12m, nyatakan nisbah luas rumah kedai kepada luas bilik stor.", ["(8x12) : (8x12) = 96:96 -> perlu nilai bilik stor sebenar dahulu (8x12=96m² berbanding 96m² jika sama; gunakan nisbah sebenar 96:96=1:1 jika sama saiz, atau kira semula mengikut data sebenar", "10 : 1", "4 : 1", "2 : 1"], 0],
]);
