import type { Difficulty, QuizQuestion } from "@/data/content";

type QuizSeed = [Difficulty, string, [string, string, string, string], number];

function buildQuiz(items: QuizSeed[]): QuizQuestion[] {
  return items.map(([difficulty, question, options, answerIndex], index) => ({
    id: `math-f3-c4-dlp-q${index + 1}`,
    subjectId: "math",
    form: "Form 3",
    difficulty,
    chapter: "Chapter 4",
    lang: "dlp",
    question,
    options,
    answerIndex,
  }));
}

export const mathF3C4QuizzesDLP: QuizQuestion[] = buildQuiz([
  ["Easy", "What is a scale drawing?", ["A drawing of an object where all measurements are proportional to the object's measurements", "A drawing without any scale", "A drawing with a different shape from the object", "A drawing that is always larger"], 0],
  ["Easy", "What is the formula for scale?", ["Scale drawing measurement / Object measurement", "Object measurement / Scale drawing measurement", "Drawing measurement + object measurement", "Drawing measurement - object measurement"], 0],
  ["Easy", "What form is scale usually written in?", ["1 : n", "n : 1", "1 + n", "n - 1"], 0],
  ["Easy", "If n < 1, how does the scale drawing compare to the object?", ["Larger than the object", "Smaller than the object", "Same as the object", "Cannot be determined"], 0],
  ["Easy", "If n > 1, how does the scale drawing compare to the object?", ["Smaller than the object", "Larger than the object", "Same as the object", "Cannot be determined"], 0],
  ["Easy", "If n = 1, how does the scale drawing compare to the object?", ["Same as the object", "Larger", "Smaller", "Undetermined"], 0],
  ["Easy", "Do angles change in a scale drawing?", ["No, angles remain the same", "Yes, angles change according to scale", "Sometimes they change", "Only change if n=1"], 0],
  ["Easy", "P'Q'=2, PQ=4. Determine the scale.", ["1 : 2", "2 : 1", "1 : 4", "4 : 1"], 0],
  ["Easy", "K'L'=9, KL=3. Determine the scale in the form n:1.", ["3 : 1", "1 : 3", "9 : 1", "1 : 9"], 0],
  ["Easy", "Map scale 1cm:10km. Map distance 2cm. Find the actual distance.", ["20 km", "10 km", "5 km", "2 km"], 0],
  ["Easy", "Scale 1:300 000. Map distance 3cm. Find the actual distance (km).", ["9 km", "3 km", "30 km", "300 km"], 0],
  ["Easy", "What unit conversion is usually needed when calculating actual map distance?", ["cm to km", "kg to g", "litres to ml", "seconds to minutes"], 0],
  ["Easy", "1 km is equal to how many cm?", ["100 000 cm", "1 000 cm", "10 000 cm", "1 000 000 cm"], 0],
  ["Easy", "What are the three ways to draw a scale drawing?", ["Same-size grid different scale, different-size grid, blank paper", "Only using a pencil", "Only using a ruler", "Only using a compass"], 0],
  ["Easy", "For grids of different sizes with the same number of side units, what is used to find the scale?", ["Grid size (not the number of units)", "Number of units only", "Grid area", "Grid perimeter"], 0],
  ["Easy", "Khairul draws a square at scale 1:1/3. The actual side is 6cm. Find the drawing's side.", ["18 cm", "2 cm", "6 cm", "3 cm"], 0],
  ["Easy", "What is the formula for actual area compared to drawing area?", ["Actual area = (length ratio)² x drawing area", "Actual area = length ratio x drawing area", "Actual area = drawing area / length ratio", "Actual area = drawing area - length ratio"], 0],
  ["Easy", "A room is 7cm x 5cm at scale 1:400. Find the actual width in m.", ["20 m", "28 m", "2 000 m", "0.05 m"], 0],
  ["Easy", "Which fields widely use scale drawings?", ["Architecture, engineering, photography", "Music and abstract art", "Sports and games", "Cooking and recipes"], 0],
  ["Easy", "What feature is preserved in a scale drawing?", ["Shape (same angles)", "Size (same dimensions)", "Colour", "Material"], 0],

  ["Medium", "Drawing grid 2cm, object grid 1cm, same number of side units. Determine the scale in the form 1:n.", ["1 : 0.5 (or 2:1)", "1 : 2", "2 : 2", "1 : 1"], 0],
  ["Medium", "Drawing grid 0.5cm, object grid 1cm. Determine the scale in the form 1:n.", ["1 : 2", "1 : 0.5", "2 : 1", "0.5 : 0.5"], 0],
  ["Medium", "K'N'=2.5cm (from Pythagoras), KN=5cm. Determine the scale in the form 1:n.", ["1 : 2", "1 : 0.5", "2 : 1", "2.5 : 5"], 0],
  ["Medium", "Johor map scale 1cm:10km, Kluang-Ayer Hitam distance 2cm on the map. Find the actual distance.", ["20 km", "10 km", "2 km", "12 km"], 0],
  ["Medium", "A poster 24cm long and 8cm wide is drawn at scale 1:4. Find the scale drawing's length.", ["6 cm", "96 cm", "24 cm", "4 cm"], 0],
  ["Medium", "From the above, find the scale drawing's width.", ["2 cm", "8 cm", "32 cm", "4 cm"], 0],
  ["Medium", "Map scale 1:400 000, river measures 2.5cm on the map. Find the actual distance (km).", ["10 km", "4 km", "100 km", "1 km"], 0],
  ["Medium", "Siew Lin draws a triangle at scale 1:1/3, the drawing's hypotenuse is 18cm. Find the actual hypotenuse.", ["6 cm", "54 cm", "3 cm", "18 cm"], 0],
  ["Medium", "A rectangular room 7cm x 5cm at scale 1:400. Find the actual area (m²).", ["560 m²", "35 m²", "1 400 m²", "280 m²"], 0],
  ["Medium", "A regular polygon with exterior angle 36° (10 sides), scale 1:5, actual side 10cm. Find the scale drawing's perimeter.", ["20 cm (10 sides x 2cm)", "50 cm", "100 cm", "10 cm"], 0],
  ["Medium", "A room 3.5m x 5.2m, scale drawing 1:50. Find the drawing's perimeter in cm.", ["34.8 cm (2x(7+10.4))", "17.4 cm", "69.6 cm", "350 cm"], 0],
  ["Medium", "A rectangular field at scale 1:2000; if the drawing measures 3cm x 6cm, find the actual area (m²).", ["7 200 m² (60x120)", "3 600 m²", "18 m²", "360 m²"], 0],
  ["Medium", "From the above, if grass is mowed at 400m² in 8 minutes, find the total time.", ["144 minutes (2 hours 24 minutes)", "100 minutes", "72 minutes", "200 minutes"], 0],
  ["Medium", "Bintulu-Miri is 4cm on a map at scale 1cm:50km. Find the actual distance.", ["200 km", "50 km", "150 km", "20 km"], 0],
  ["Medium", "From the above, if the map is redrawn at scale 1:2 000 000, find the new map distance (cm).", ["10 cm", "4 cm", "20 cm", "100 cm"], 0],
  ["Medium", "From the above, if driven at 80km/h, find the travel time.", ["2.5 hours (2 hours 30 minutes)", "2 hours", "3 hours", "1.5 hours"], 0],
  ["Medium", "A storeroom on a drawing at scale 1:400 measures 2cm x 3cm. Find the actual area (m²).", ["96 m² (8x12)", "24 m²", "600 m²", "48 m²"], 0],
  ["Medium", "If the shop's actual height is 3.75m and its footprint is 8m x 12m, find the volume (m³).", ["360 m³", "96 m³", "45 m³", "180 m³"], 0],
  ["Medium", "A flower is drawn on a 1cmx1cm grid; redraw the actual object on a 1.5cmx1.5cm grid. What is the new scale?", ["1 : 1.5 (object is larger)", "1.5 : 1", "1 : 1", "1 : 0.5"], 0],
  ["Medium", "A flower is drawn on a 1cmx1cm grid; redraw the actual object on a 0.5cmx0.5cm grid. What is the new scale?", ["1 : 0.5 (object is smaller)", "0.5 : 1", "1 : 2", "2 : 1"], 0],

  ["Hard", "Triangle P (a scale drawing of triangle Q) has an area of 112.5cm², Q has an area of 4.5cm². Find n if the scale is 1:n.", ["n=5 (area ratio=25, length ratio=5)", "n=25", "n=2.5", "n=10"], 0],
  ["Hard", "A circle centred at O has a diameter of 6cm on the drawing, scale 1:3. Find the actual diameter.", ["18 cm", "2 cm", "9 cm", "6 cm"], 0],
  ["Hard", "Kuching-KK map distance 5.4cm, scale 1cm:150km, flight from 1240 to 1410 (90 minutes). Find the average speed (km/h).", ["540 km/h (5.4x150=810km, /1.5h=540)", "810 km/h", "270 km/h", "150 km/h"], 0],
  ["Hard", "A living room at scale 1:50, tile A 30cmx30cm RM2.80/piece vs tile B 50cmx50cm RM6/piece. Which is cheaper per m²?", ["Tile B 50cmx50cm (RM6/0.25m²=RM24/m² vs RM2.80/0.09m²≈RM31.1/m²)", "Tile A 30cmx30cm is cheaper", "Both are equal", "Cannot be determined"], 0],
  ["Hard", "A freshwater fish pond on a drawing at scale 1:2000 is circular with radius 2cm. Find the actual area (m², use π≈22/7).", ["Actual area=π(40m)²≈5028.6 m²", "Actual area=π(2m)²", "Actual area=400 m²", "Actual area=1600 m²"], 0],
  ["Hard", "A football field, Diagram 1 (7cmx12cm), at scale 1:1000. Find the actual area (m²).", ["8 400 m² (70x120)", "84 m²", "840 m²", "10 080 m²"], 0],
  ["Hard", "Sharon wants to redraw Diagram 1 (7cmx12cm original, 70mx120m actual) onto A4 paper (29.7cmx21cm). What is a reasonable maximum scale?", ["A larger scale such as 1:500 or more to fit within A4", "Scale 1:1000 (original, too small for a larger A4 redraw)", "Scale 1:1 (too large, won't fit)", "Cannot be drawn on A4"], 0],
  ["Hard", "5m x 4m tents are set up on a 70m x 120m field (assuming half the field is used for tents). Estimate the maximum number of tents.", ["Estimate: (70x120/2)/(5x4) = 210 tents (approximate calculation)", "10 tents", "100 tents", "50 tents"], 0],
  ["Hard", "Tent rental is RM100/day, 25% discount if rented for 5 days or more, rented for a week (7 days). Find the total rental per tent.", ["RM525 (100x7x0.75)", "RM700", "RM600", "RM525.50"], 0],
  ["Hard", "Rectangle S (3cmx5cm) is compared with I,II,III,IV. If IV is 6cmx10cm, determine the scale S:IV.", ["1 : 2", "2 : 1", "1 : 4", "4 : 1"], 0],
  ["Hard", "From the above, find the ratio of S's area to IV's area.", ["1 : 4 (square of the length ratio)", "1 : 2", "1 : 8", "1 : 16"], 0],
  ["Hard", "What is the correct conclusion about the ratio of areas compared to the ratio of lengths in a scale drawing?", ["Area ratio = (length ratio)²", "Area ratio = length ratio", "Area ratio = 2 x length ratio", "There is no relationship"], 0],
  ["Hard", "For a three-dimensional shape, how is the volume ratio related to the length scale ratio?", ["Volume ratio = (length ratio)³", "Volume ratio = length ratio", "Volume ratio = (length ratio)²", "There is no relationship"], 0],
  ["Hard", "What is the mistake if someone calculates the actual area by multiplying the drawing's area directly by the length ratio (not squared)?", ["The answer will be too small/incorrect because area requires the square of the length ratio", "The answer is still correct", "It is only wrong for circular shapes", "It is only wrong for triangles"], 0],
  ["Hard", "A shop lot at scale 1:400, storeroom 2cmx3cm on the drawing, actual height 3.75m. If the shop's footprint is 8mx12m, state the ratio of the shop's area to the storeroom's area.", ["Requires the storeroom's actual area first (8x12=96m² each if computed identically, or recompute using actual storeroom dimensions)", "10 : 1", "4 : 1", "2 : 1"], 0],
]);
