import type { Flashcard } from "@/data/types";

export const geographyF1C5Flashcards: Flashcard[] = [
  // Foundation Review (Cards 1–20)
  {
    id: "geo-f1-c5-fc1",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah maksud Atmosfera?",
    back: "Atmosfera ialah lapisan udara yang menyelubungi Bumi.",
  },
  {
    id: "geo-f1-c5-fc2",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Nyatakan empat sistem fizikal Bumi.",
    back: "Empat sistem fizikal Bumi ialah Atmosfera, Hidrosfera, Litosfera dan Biosfera.",
  },
  {
    id: "geo-f1-c5-fc3",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah yang dimaksudkan dengan Biosfera?",
    back: "Biosfera ialah kawasan yang didiami oleh semua benda hidup seperti manusia, haiwan dan tumbuhan.",
  },
  {
    id: "geo-f1-c5-fc4",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah lapisan Bumi yang paling keras dan pejal?",
    back: "Lapisan Bumi yang paling keras dan pejal ialah Kerak Bumi.",
  },
  {
    id: "geo-f1-c5-fc5",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Berapakah jumlah benua yang terdapat di permukaan Bumi?",
    back: "Terdapat tujuh benua di permukaan Bumi.",
  },
  {
    id: "geo-f1-c5-fc6",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah benua yang terbesar di dunia?",
    back: "Benua yang terbesar di dunia ialah Benua Asia.",
  },
  {
    id: "geo-f1-c5-fc7",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah benua yang paling kecil di dunia?",
    back: "Benua yang paling kecil di dunia ialah Benua Australia.",
  },
  {
    id: "geo-f1-c5-fc8",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah lautan yang terbesar di dunia?",
    back: "Lautan yang terbesar di dunia ialah Lautan Pasifik.",
  },
  {
    id: "geo-f1-c5-fc9",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Lautan manakah yang paling kecil dan paling cetek?",
    back: "Lautan yang paling kecil dan paling cetek ialah Lautan Artik.",
  },
  {
    id: "geo-f1-c5-fc10",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah yang dimaksudkan dengan Hidrosfera?",
    back: "Hidrosfera merangkumi semua bahagian air yang terdapat di Bumi seperti laut, sungai, tasik dan air bawah tanah.",
  },
  {
    id: "geo-f1-c5-fc11",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Berapakah jumlah lapisan utama dalam struktur Bumi?",
    back: "Struktur Bumi mempunyai tiga lapisan utama, iaitu Kerak Bumi, Mantel dan Teras Bumi.",
  },
  {
    id: "geo-f1-c5-fc12",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah lapisan Bumi yang paling dalam?",
    back: "Lapisan Bumi yang paling dalam ialah Teras Bumi.",
  },
  {
    id: "geo-f1-c5-fc13",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah yang dimaksudkan dengan Litosfera?",
    back: "Litosfera ialah lapisan luar Bumi yang merangkumi Kerak Bumi dan bahagian atas Mantel.",
  },
  {
    id: "geo-f1-c5-fc14",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front:
      "Apakah nama selat yang dinyatakan sebagai selat terpanjang di dunia dalam sumber pembelajaran?",
    back: "Selat tersebut ialah Selat Melaka.",
  },
  {
    id: "geo-f1-c5-fc15",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah bencana yang boleh berlaku akibat gempa bumi di dasar laut?",
    back: "Gempa bumi di dasar laut berpotensi menghasilkan tsunami.",
  },
  {
    id: "geo-f1-c5-fc16",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Gunung berapi terbentuk daripada bahan apa?",
    back: "Gunung berapi terbentuk daripada magma yang keluar ke permukaan Bumi sebagai lava.",
  },
  {
    id: "geo-f1-c5-fc17",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah nama kepingan besar Kerak Bumi yang membentuk daratan dan dasar lautan?",
    back: "Kepingan besar tersebut dikenali sebagai plat Bumi.",
  },
  {
    id: "geo-f1-c5-fc18",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Selat manakah yang memisahkan Semenanjung Malaysia dengan Singapura?",
    back: "Selat Tebrau memisahkan Semenanjung Malaysia dengan Singapura.",
  },
  {
    id: "geo-f1-c5-fc19",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah bahan utama yang membentuk lapisan Sial?",
    back: "Lapisan Sial terdiri terutamanya daripada silika dan aluminium.",
  },
  {
    id: "geo-f1-c5-fc20",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah bahan utama yang membentuk lapisan Sima?",
    back: "Lapisan Sima terdiri terutamanya daripada silika dan magnesium.",
  },

  // Practice Review (Cards 21–40)
  {
    id: "geo-f1-c5-fc21",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Di manakah letaknya lapisan Sial?",
    back: "Lapisan Sial terletak di bahagian atas Kerak Bumi dan membentuk kawasan benua.",
  },
  {
    id: "geo-f1-c5-fc22",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah sifat fizikal lapisan Mantel?",
    back: "Mantel bersifat pepejal, tetapi sesetengah bahagiannya mempunyai bahan separa cair yang membolehkan berlakunya pergerakan.",
  },
  {
    id: "geo-f1-c5-fc23",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Mengapakah plat Bumi bergerak?",
    back: "Plat Bumi bergerak akibat pengaruh arus perolakan di dalam Mantel.",
  },
  {
    id: "geo-f1-c5-fc24",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Gunung lipat terhasil akibat daya apa?",
    back: "Gunung lipat terhasil akibat daya mampatan pada Kerak Bumi.",
  },
  {
    id: "geo-f1-c5-fc25",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Bagaimanakah gunung bongkah terbentuk?",
    back: "Gunung bongkah terbentuk melalui proses sesaran atau gelinciran yang menyebabkan sebahagian Kerak Bumi terangkat.",
  },
  {
    id: "geo-f1-c5-fc26",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah dua proses utama yang berlaku dalam pergerakan plat Bumi?",
    back: "Dua proses utama tersebut ialah pertembungan plat dan pencapahan plat.",
  },
  {
    id: "geo-f1-c5-fc27",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Bagaimanakah gunung berapi boleh terbentuk di zon pertembungan plat?",
    back: "Apabila dua plat bertembung, satu plat boleh terbenam ke bawah plat yang lain. Batuan yang mencair membentuk magma yang kemudiannya keluar melalui rekahan Kerak Bumi.",
  },
  {
    id: "geo-f1-c5-fc28",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Lautan manakah yang mempunyai bentuk seakan-akan huruf “S”?",
    back: "Lautan Atlantik mempunyai bentuk seakan-akan huruf “S”.",
  },
  {
    id: "geo-f1-c5-fc29",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Lautan Hindi bersempadan dengan benua mana?",
    back: "Lautan Hindi bersempadan dengan Benua Asia, Afrika dan Australia.",
  },
  {
    id: "geo-f1-c5-fc30",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Nyatakan satu kepentingan Atmosfera.",
    back: "Atmosfera membekalkan gas yang diperlukan oleh benda hidup dan membantu mengawal suhu persekitaran.",
  },
  {
    id: "geo-f1-c5-fc31",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Nyatakan satu kepentingan Hidrosfera.",
    back: "Hidrosfera membekalkan sumber air dan menjadi habitat kepada hidupan akuatik.",
  },
  {
    id: "geo-f1-c5-fc32",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Di manakah letaknya Laut China Selatan?",
    back: "Laut China Selatan terletak dalam lingkungan Lautan Pasifik dan terbentang dari kawasan Selat Melaka hingga Selat Taiwan.",
  },
  {
    id: "geo-f1-c5-fc33",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah yang terkandung dalam Litosfera?",
    back: "Litosfera mengandungi pelbagai jenis batuan dan mineral.",
  },
  {
    id: "geo-f1-c5-fc34",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Berapakah anggaran keluasan Benua Asia?",
    back: "Keluasan Benua Asia ialah kira-kira 55.8 juta kilometer persegi.",
  },
  {
    id: "geo-f1-c5-fc35",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Di manakah letaknya Laut Sulu?",
    back: "Laut Sulu terletak di barat daya Filipina berhampiran Pulau Borneo.",
  },
  {
    id: "geo-f1-c5-fc36",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Bagaimanakah gempa bumi berlaku?",
    back: "Gempa bumi boleh berlaku apabila tekanan akibat pertembungan, himpitan atau pergerakan plat dilepaskan secara tiba-tiba.",
  },
  {
    id: "geo-f1-c5-fc37",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah yang dimaksudkan dengan magma?",
    back: "Magma ialah batuan cair yang berada di bawah permukaan Bumi.",
  },
  {
    id: "geo-f1-c5-fc38",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Lapisan struktur Bumi yang manakah merangkumi sebahagian besar jisim Bumi?",
    back: "Mantel merangkumi kira-kira dua pertiga daripada jisim Bumi.",
  },
  {
    id: "geo-f1-c5-fc39",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Nyatakan dua bahagian utama Teras Bumi.",
    back: "Dua bahagian utama Teras Bumi ialah teras luar dan teras dalam.",
  },
  {
    id: "geo-f1-c5-fc40",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah kepentingan Litosfera kepada manusia?",
    back: "Litosfera menjadi kawasan petempatan serta menyediakan kawasan untuk pertanian, perlombongan dan pelbagai kegiatan ekonomi.",
  },

  // Challenge Review (Cards 41–60)
  {
    id: "geo-f1-c5-fc41",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Jelaskan perbezaan antara lapisan Sial dengan lapisan Sima.",
    back: "Sial terletak di bahagian atas Kerak Bumi dan membentuk benua serta mengandungi silika dan aluminium. Sima pula terletak di bawah Sial atau pada dasar lautan serta mengandungi silika dan magnesium.",
  },
  {
    id: "geo-f1-c5-fc42",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Berapakah purata kedalaman Lautan Pasifik?",
    back: "Purata kedalaman Lautan Pasifik ialah kira-kira 4,300 meter.",
  },
  {
    id: "geo-f1-c5-fc43",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Berapakah purata kedalaman Lautan Hindi?",
    back: "Purata kedalaman Lautan Hindi ialah kira-kira 3,900 meter.",
  },
  {
    id: "geo-f1-c5-fc44",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front:
      "Nyatakan lima lapisan Atmosfera bermula daripada lapisan yang paling hampir dengan permukaan Bumi.",
    back: "Lima lapisan tersebut ialah troposfera, stratosfera, mesosfera, termosfera dan eksosfera.",
  },
  {
    id: "geo-f1-c5-fc45",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah kesan pencapahan plat Bumi terhadap kedudukan benua?",
    back: "Pencapahan plat boleh menyebabkan hanyutan benua dan perubahan kedudukan benua dari semasa ke semasa.",
  },
  {
    id: "geo-f1-c5-fc46",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Jelaskan kaitan antara zon benam dengan pembentukan magma.",
    back: "Di zon benam, satu plat bergerak ke bawah plat yang lain menuju ke Mantel. Suhu dan tekanan yang tinggi menyebabkan batuan mencair lalu membentuk magma.",
  },
  {
    id: "geo-f1-c5-fc47",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Benua manakah yang terletak paling selatan di dunia?",
    back: "Benua yang terletak paling selatan ialah Benua Antartika.",
  },
  {
    id: "geo-f1-c5-fc48",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah benua kedua terbesar di dunia?",
    back: "Benua kedua terbesar di dunia ialah Benua Afrika.",
  },
  {
    id: "geo-f1-c5-fc49",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah benua kedua terkecil di dunia?",
    back: "Benua kedua terkecil di dunia ialah Benua Eropah.",
  },
  {
    id: "geo-f1-c5-fc50",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Di manakah lokasi Lautan Artik?",
    back: "Lautan Artik terletak di sekitar kawasan Kutub Utara.",
  },
  {
    id: "geo-f1-c5-fc51",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front:
      "Apakah gas dalam Atmosfera yang digunakan oleh tumbuhan untuk menjalankan fotosintesis?",
    back: "Tumbuhan menggunakan gas karbon dioksida untuk menjalankan fotosintesis.",
  },
  {
    id: "geo-f1-c5-fc52",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Mengapakah Teras Bumi mempunyai suhu yang sangat tinggi?",
    back: "Teras Bumi mempunyai suhu yang sangat tinggi kerana terletak jauh di bahagian dalam Bumi serta mengalami tekanan yang sangat kuat.",
  },
  {
    id: "geo-f1-c5-fc53",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Bagaimanakah tsunami boleh terhasil secara geologi?",
    back: "Tsunami boleh berlaku apabila gempa bumi di dasar laut menggerakkan dasar laut dan jisim air secara mendadak, lalu menghasilkan gelombang yang besar.",
  },
  {
    id: "geo-f1-c5-fc54",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Mengapakah Biosfera bergantung pada Atmosfera, Hidrosfera dan Litosfera?",
    back: "Biosfera memerlukan udara daripada Atmosfera, air daripada Hidrosfera serta tanah dan habitat daripada Litosfera untuk menyokong kehidupan.",
  },
  {
    id: "geo-f1-c5-fc55",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Berikan tiga contoh mineral yang terdapat dalam Litosfera.",
    back: "Tiga contoh mineral ialah bijih timah, emas dan kuprum.",
  },
  {
    id: "geo-f1-c5-fc56",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah ciri bentuk fizikal yang unik bagi Benua Australia?",
    back: "Benua Australia merupakan benua yang paling mendatar di dunia.",
  },
  {
    id: "geo-f1-c5-fc57",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Selat Melaka terletak di antara kawasan daratan mana?",
    back: "Selat Melaka terletak di antara Semenanjung Malaysia dengan Pulau Sumatera, Indonesia.",
  },
  {
    id: "geo-f1-c5-fc58",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Apakah kedudukan Lautan Selatan?",
    back: "Lautan Selatan mengelilingi Benua Antartika.",
  },
  {
    id: "geo-f1-c5-fc59",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front: "Berapakah anggaran keluasan Benua Afrika?",
    back: "Keluasan Benua Afrika ialah kira-kira 30 juta kilometer persegi.",
  },
  {
    id: "geo-f1-c5-fc60",
    subjectId: "geography",
    form: "Form 1",
    chapter: "Chapter 5",
    front:
      "Apakah yang berlaku apabila dua plat bergerak dari arah bertentangan dan menghasilkan daya mampatan?",
    back: "Kerak Bumi akan termampat dan terlipat, lalu membentuk banjaran gunung lipat.",
  },
];
