import type { StructuredNotes } from "@/data/types";

export const sejarahF3C4Notes: StructuredNotes = {
  chapterSummary: "Bab ini menjelaskan pemerintahan Kesultanan Melayu di Perlis, Kedah, Kelantan, Terengganu dan Johor, peluasan kuasa British melalui Perjanjian Bangkok 1909 serta sistem pentadbiran NNMTB.",
  quickRevision: ["4.1 Pemerintahan Kesultanan Melayu di Perlis, Kedah, Kelantan, Terengganu dan Johor: Perlis, Kedah, Kelantan, Terengganu dan Johor mempunyai sistem pemerintahan beraja.","Tarikh penting 4.1: 1839-1876: pemerintahan Sultan Omar Terengganu","4.2 Peluasan Kuasa British di Perlis, Kedah, Kelantan dan Terengganu: British dan Siam menggunakan beberapa perjanjian untuk menentukan pengaruh di negeri Melayu utara.","Tarikh penting 4.2: 1897: Perjanjian Sulit British-Siam","4.3 Peluasan Kuasa British di Johor: Johor mengekalkan kedaulatan lebih lama melalui hubungan diplomatik dan pemodenan pentadbiran.","Tarikh penting 4.3: 1855: Perjanjian Sultan Ali-Temenggung Ibrahim","4.4 Sistem Pentadbiran Negeri-negeri Melayu Tidak Bersekutu: Perjanjian Bangkok 1909 membawa perubahan pentadbiran di Perlis, Kedah, Kelantan dan Terengganu.","Tarikh penting 4.4: 1909: perubahan pentadbiran NNMTB"],
  keyTerms: ["NNMTB","sistem beraja","Sultan","Raja","pembesar","Perjanjian Bangkok 1909","Siam","Penasihat British","negeri Melayu utara","Johor","Temenggung Ibrahim","Sultan Abu Bakar","Perjanjian Setia 1885","Penasihat Am","Majlis Mesyuarat Negeri","sultan","agama Islam","adat Melayu"],
  keyExamFacts: ["Perlis, Kedah, Kelantan, Terengganu dan Johor mempunyai sistem pemerintahan beraja.","Sultan atau Raja berada di puncak kuasa dan dibantu pembesar.","Johor melakukan pemodenan pentadbiran lebih awal melalui kerjasama sultan dan pembesar.","British dan Siam menggunakan beberapa perjanjian untuk menentukan pengaruh di negeri Melayu utara.","Perjanjian Sulit 1897, Perjanjian Sempadan 1899 dan Perjanjian 1902 membuka jalan kepada Perjanjian Bangkok 1909.","Perjanjian Bangkok 1909 ditandatangani oleh British dan Siam pada 10 Mac 1909.","Johor mengekalkan kedaulatan lebih lama melalui hubungan diplomatik dan pemodenan pentadbiran.","Perjanjian 1855 antara Sultan Ali dengan Temenggung Ibrahim mengukuhkan kedudukan Temenggung di Johor.","Perjanjian Setia 1885 antara Johor dengan British mengiktiraf hubungan Johor-British.","Perjanjian Bangkok 1909 membawa perubahan pentadbiran di Perlis, Kedah, Kelantan dan Terengganu.","Penasihat British ditempatkan tetapi sultan masih kekal sebagai puncak kuasa terutama agama Islam dan adat Melayu.","Majlis Mesyuarat Negeri membantu pentadbiran negeri."],
  sections: [
    {
      title: "Bab Overview",
      subsections: [
        { title: "Sinopsis", content: "Bab ini menjelaskan pemerintahan Kesultanan Melayu di Perlis, Kedah, Kelantan, Terengganu dan Johor, peluasan kuasa British melalui Perjanjian Bangkok 1909 serta sistem pentadbiran NNMTB." },
        { title: "Apa yang akan dipelajari", bulletPoints: ["4.1 Pemerintahan Kesultanan Melayu di Perlis, Kedah, Kelantan, Terengganu dan Johor","4.2 Peluasan Kuasa British di Perlis, Kedah, Kelantan dan Terengganu","4.3 Peluasan Kuasa British di Johor","4.4 Sistem Pentadbiran Negeri-negeri Melayu Tidak Bersekutu"] },
        { title: "Fokus UASA", bulletPoints: ["Kenal pasti kronologi, tokoh, tempat, perjanjian dan kesan.","Bezakan sebab, strategi dan kesan peluasan kuasa Barat.","Gunakan kata kunci seperti kedaulatan, pentadbiran, ekonomi, penentangan dan pemodenan."] },
      ],
    },
    {
      title: "4.1 Pemerintahan Kesultanan Melayu di Perlis, Kedah, Kelantan, Terengganu dan Johor",
      subsections: [
        { title: "Ringkasan", content: "Pemerintahan Kesultanan Melayu di Perlis, Kedah, Kelantan, Terengganu dan Johor menerangkan perlis, kedah, kelantan, terengganu dan johor mempunyai sistem pemerintahan beraja. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Perlis, Kedah, Kelantan, Terengganu dan Johor mempunyai sistem pemerintahan beraja.","Sultan atau Raja berada di puncak kuasa dan dibantu pembesar.","Johor melakukan pemodenan pentadbiran lebih awal melalui kerjasama sultan dan pembesar.","Terengganu dan Johor menggubal undang-undang tubuh untuk mempertahankan kedaulatan."] },
        { title: "Kata kunci", bulletPoints: ["NNMTB","sistem beraja","Sultan","Raja","pembesar"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Mudzaffar Shah","Sultan Muhammad I","Sultan Muhammad II","Sultan Omar","Sultan Abu Bakar"] },
        { title: "Tarikh penting", bulletPoints: ["1839-1876: pemerintahan Sultan Omar Terengganu"] },
        { title: "Tempat penting", bulletPoints: ["Perlis","Kedah","Kelantan","Terengganu","Johor"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Tiada perjanjian khusus"],["Undang-undang","Undang-Undang Tubuh Kerajaan Johor; Undang-Undang Bagi Diri Kerajaan Terengganu"],["Organisasi / pentadbiran","NNMTB"]] } },
        { title: "Sebab", bulletPoints: ["Tradisi Kesultanan Melayu","Keperluan pentadbiran negeri","Ancaman peluasan kuasa asing"] },
        { title: "Kesan", bulletPoints: ["Sultan kekal sebagai pusat pentadbiran","Pembesar membantu kerajaan","Pemodenan pentadbiran berlaku di Johor"] },
        { title: "Kepentingan", bulletPoints: ["Menunjukkan negeri Melayu mempunyai sistem pemerintahan tersendiri sebelum penasihat British ditempatkan."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Kekuatan sistem beraja menjadi asas reaksi pemerintah terhadap Perjanjian Bangkok 1909."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta NNMTB memperlihatkan kedudukan negeri utara dan Johor yang tidak menyertai NNMB.","Sebelum 1909: negeri-negeri ini masih mengekalkan pentadbiran sendiri"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "4.2 Peluasan Kuasa British di Perlis, Kedah, Kelantan dan Terengganu",
      subsections: [
        { title: "Ringkasan", content: "Peluasan Kuasa British di Perlis, Kedah, Kelantan dan Terengganu menerangkan british dan siam menggunakan beberapa perjanjian untuk menentukan pengaruh di negeri melayu utara. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["British dan Siam menggunakan beberapa perjanjian untuk menentukan pengaruh di negeri Melayu utara.","Perjanjian Sulit 1897, Perjanjian Sempadan 1899 dan Perjanjian 1902 membuka jalan kepada Perjanjian Bangkok 1909.","Perjanjian Bangkok 1909 ditandatangani oleh British dan Siam pada 10 Mac 1909.","Perjanjian Bangkok membolehkan British menguasai Perlis, Kedah, Kelantan dan Terengganu tanpa gangguan Siam."] },
        { title: "Kata kunci", bulletPoints: ["Perjanjian Bangkok 1909","Siam","Penasihat British","negeri Melayu utara"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Abdul Hamid Halim Shah","Sultan Muhammad IV","Sultan Zainal Abidin III"] },
        { title: "Tarikh penting", bulletPoints: ["1897: Perjanjian Sulit British-Siam","1899: Perjanjian Sempadan British-Siam","1902: Pengisytiharan British-Siam","10 Mac 1909: Perjanjian Bangkok"] },
        { title: "Tempat penting", bulletPoints: ["Perlis","Kedah","Kelantan","Terengganu","Bangkok"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Sulit 1897; Perjanjian Sempadan 1899; Perjanjian 1902; Perjanjian Bangkok 1909"],["Undang-undang","Tiada undang-undang khusus"],["Organisasi / pentadbiran","Penasihat British"]] } },
        { title: "Sebab", bulletPoints: ["British mahu menghalang pengaruh kuasa lain","Siam mahu menjaga kepentingan wilayah","British mahu meluaskan kuasa ke negeri Melayu utara"] },
        { title: "Kesan", bulletPoints: ["British menempatkan Penasihat British","Negeri Melayu utara berada di bawah pengaruh British","Hubungan tradisional dengan Siam berubah"] },
        { title: "Kepentingan", bulletPoints: ["Perjanjian Bangkok ialah titik penting peluasan British di NNMTB."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Perjanjian Bangkok mengubah status negeri Melayu utara dan mempengaruhi reaksi sultan dalam Bab 8."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta Perjanjian Bangkok menunjukkan negeri yang berpindah daripada pengaruh Siam kepada British.","1897","1899","1902","1909"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "4.3 Peluasan Kuasa British di Johor",
      subsections: [
        { title: "Ringkasan", content: "Peluasan Kuasa British di Johor menerangkan johor mengekalkan kedaulatan lebih lama melalui hubungan diplomatik dan pemodenan pentadbiran. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Johor mengekalkan kedaulatan lebih lama melalui hubungan diplomatik dan pemodenan pentadbiran.","Perjanjian 1855 antara Sultan Ali dengan Temenggung Ibrahim mengukuhkan kedudukan Temenggung di Johor.","Perjanjian Setia 1885 antara Johor dengan British mengiktiraf hubungan Johor-British.","Pada tahun 1914, Johor menerima Penasihat Am British."] },
        { title: "Kata kunci", bulletPoints: ["Johor","Temenggung Ibrahim","Sultan Abu Bakar","Perjanjian Setia 1885","Penasihat Am"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Ali","Temenggung Ibrahim","Sultan Abu Bakar","Sultan Ibrahim"] },
        { title: "Tarikh penting", bulletPoints: ["1855: Perjanjian Sultan Ali-Temenggung Ibrahim","1885: Perjanjian Setia Johor-British","1914: Johor menerima Penasihat Am British"] },
        { title: "Tempat penting", bulletPoints: ["Johor","Muar","Singapura"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian 1855; Perjanjian Setia 1885; Perjanjian Johor-British 1914"],["Undang-undang","Undang-Undang Tubuh Kerajaan Johor 1895"],["Organisasi / pentadbiran","Penasihat Am"]] } },
        { title: "Sebab", bulletPoints: ["Johor mahu mengekalkan kedaulatan","British mahu meluaskan pengaruh","Kedudukan Johor strategik berhampiran Singapura"] },
        { title: "Kesan", bulletPoints: ["Johor mengekalkan pentadbiran sendiri lebih lama","Akhirnya Penasihat Am British ditempatkan","Kawalan British meningkat"] },
        { title: "Kepentingan", bulletPoints: ["Johor menjadi contoh kebijaksanaan pemerintah menangguhkan campur tangan British."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Pemodenan Johor berkait dengan usaha pembesar dan raja dalam Bab 8."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Peta Johor-Singapura menerangkan kepentingan strategik Johor kepada British.","1855","1885","1895","1914"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "4.4 Sistem Pentadbiran Negeri-negeri Melayu Tidak Bersekutu",
      subsections: [
        { title: "Ringkasan", content: "Sistem Pentadbiran Negeri-negeri Melayu Tidak Bersekutu menerangkan perjanjian bangkok 1909 membawa perubahan pentadbiran di perlis, kedah, kelantan dan terengganu. Subtopik ini perlu dibaca bersama kronologi, tokoh, tempat dan kesan yang berkaitan." },
        { title: "Fakta penting", bulletPoints: ["Perjanjian Bangkok 1909 membawa perubahan pentadbiran di Perlis, Kedah, Kelantan dan Terengganu.","Penasihat British ditempatkan tetapi sultan masih kekal sebagai puncak kuasa terutama agama Islam dan adat Melayu.","Majlis Mesyuarat Negeri membantu pentadbiran negeri.","Undang-Undang Tubuh Kerajaan Johor dan Undang-Undang Bagi Diri Kerajaan Terengganu menegaskan larangan menyerahkan negeri kepada kuasa asing."] },
        { title: "Kata kunci", bulletPoints: ["Penasihat British","Majlis Mesyuarat Negeri","sultan","agama Islam","adat Melayu"] },
        { title: "Tokoh penting", bulletPoints: ["Sultan Johor","Sultan Terengganu","Penasihat British"] },
        { title: "Tarikh penting", bulletPoints: ["1909: perubahan pentadbiran NNMTB","1911: Undang-Undang Bagi Diri Kerajaan Terengganu"] },
        { title: "Tempat penting", bulletPoints: ["Perlis","Kedah","Kelantan","Terengganu","Johor"] },
        { title: "Perjanjian / undang-undang / organisasi", table: { headers: ["Kategori", "Butiran"], rows: [["Perjanjian","Perjanjian Bangkok 1909"],["Undang-undang","Undang-Undang Tubuh Kerajaan Johor 1895; Undang-Undang Bagi Diri Kerajaan Terengganu 1911"],["Organisasi / pentadbiran","Penasihat British; Majlis Mesyuarat Negeri"]] } },
        { title: "Sebab", bulletPoints: ["Peluasan kuasa British","Keperluan British mengawal pentadbiran","Usaha pemerintah mempertahankan kedaulatan"] },
        { title: "Kesan", bulletPoints: ["British mengawal nasihat pentadbiran","Sultan mengekalkan kuasa agama dan adat","Pentadbiran negeri menjadi lebih tersusun tetapi terikat dengan British"] },
        { title: "Kepentingan", bulletPoints: ["Memahami perbezaan NNMTB dengan NNMB dari segi tahap pemusatan kuasa British."] },
        { title: "Hubungan antara konsep", bulletPoints: ["Kedudukan sultan dalam NNMTB menjadi asas kebijaksanaan menentang cabaran Barat."] },
        { title: "Peta / rajah / garis masa", bulletPoints: ["Rajah pentadbiran menunjukkan sultan, Majlis Mesyuarat Negeri dan Penasihat British.","1909 Perjanjian Bangkok","1911 Undang-undang Terengganu","1914 Penasihat Am Johor"] },
        { title: "Tip peperiksaan", bulletPoints: ["Tulis jawapan mengikut urutan: fakta + huraian + contoh + kesan.","Jika soalan menyebut perjanjian, nyatakan tahun, pihak terlibat dan kesannya.","Untuk soalan KBAT, kaitkan fakta textbook dengan nilai kedaulatan, kebijaksanaan atau kewaspadaan."] },
        { title: "Kesilapan lazim pelajar", bulletPoints: ["Mencampuradukkan tokoh dan negeri penentangan.","Menulis tarikh tanpa menjelaskan kepentingannya.","Menghafal istilah tetapi tidak mengaitkan sebab dan kesan."] },
      ],
    },
    {
      title: "Rumusan Bab",
      subsections: [
        { title: "Imbas Kembali", bulletPoints: ["4.1: NNMTB, sistem beraja, Sultan, Raja","4.2: Perjanjian Bangkok 1909, Siam, Penasihat British, negeri Melayu utara","4.3: Johor, Temenggung Ibrahim, Sultan Abu Bakar, Perjanjian Setia 1885","4.4: Penasihat British, Majlis Mesyuarat Negeri, sultan, agama Islam"] },
        { title: "Kata Kunci Peperiksaan", bulletPoints: ["NNMTB","sistem beraja","Sultan","Raja","pembesar","Perjanjian Bangkok 1909","Siam","Penasihat British","negeri Melayu utara","Johor","Temenggung Ibrahim","Sultan Abu Bakar","Perjanjian Setia 1885","Penasihat Am","Majlis Mesyuarat Negeri","sultan","agama Islam","adat Melayu"] },
      ],
    }
  ],
};
