import type { Flashcard } from "@/data/content";

export const scienceF2C10FlashcardsBM: Flashcard[] = [
  // Deck 1: Asas (Cards 1-20)
  {
    id: "sci-f2-c10-bm-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah maksud bunyi?",
    back: "Satu bentuk tenaga yang disebabkan oleh getaran.",
  },
  {
    id: "sci-f2-c10-bm-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah yang diperlukan oleh bunyi untuk merebak?",
    back: "Medium (pepejal, cecair atau gas) — bunyi tidak dapat merebak melalui vakum.",
  },
  {
    id: "sci-f2-c10-bm-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah maksud vakum?",
    back: "Kawasan tanpa udara.",
  },
  {
    id: "sci-f2-c10-bm-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Dalam medium apakah bunyi merebak paling cepat?",
    back: "Pepejal, kerana zarah pepejal tersusun rapat antara satu sama lain.",
  },
  {
    id: "sci-f2-c10-bm-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Dalam medium apakah bunyi merebak paling perlahan?",
    back: "Gas, kerana zarah gas tersusun jauh antara satu sama lain.",
  },
  {
    id: "sci-f2-c10-bm-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah jenis permukaan yang menjadi pemantul bunyi yang baik?",
    back: "Permukaan keras dan licin, contohnya jubin marmar dan dinding.",
  },
  {
    id: "sci-f2-c10-bm-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah jenis permukaan yang menjadi penyerap bunyi yang baik?",
    back: "Permukaan lembut dan kasar, contohnya karpet dan papan lembut.",
  },
  {
    id: "sci-f2-c10-bm-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah yang menentukan kelantangan bunyi?",
    back: "Amplitud gelombang bunyi — semakin besar amplitud, semakin kuat bunyi.",
  },
  {
    id: "sci-f2-c10-bm-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah yang menentukan kelaraban (pitch) bunyi?",
    back: "Frekuensi gelombang bunyi — semakin tinggi frekuensi, semakin tinggi kelaraban.",
  },
  {
    id: "sci-f2-c10-bm-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah unit ukuran bagi frekuensi bunyi?",
    back: "Hertz (Hz).",
  },
  {
    id: "sci-f2-c10-bm-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah peranti yang digunakan dalam Aktiviti 10.2 untuk mengkaji amplitud dan frekuensi bunyi?",
    back: "Osiloskop Sinar Katod (C.R.O.) dan penjana isyarat audio.",
  },
  {
    id: "sci-f2-c10-bm-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah maksud kesan Doppler?",
    back: "Perubahan ketara dalam frekuensi yang disebabkan oleh pergerakan relatif sumber bunyi, pemerhati, atau kedua-duanya.",
  },
  {
    id: "sci-f2-c10-bm-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah maksud gegaran (echo)?",
    back: "Bunyi yang terhasil apabila gelombang bunyi dipantulkan daripada permukaan keras kepada pendengar.",
  },
  {
    id: "sci-f2-c10-bm-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah maksud ultrabunyi?",
    back: "Gelombang bunyi dengan frekuensi lebih daripada 20,000 Hz, tidak dapat didengar oleh manusia.",
  },
  {
    id: "sci-f2-c10-bm-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah sonar?",
    back: "Teknologi pantulan bunyi yang digunakan untuk mengesan objek bawah air, terutamanya dalam industri perkapalan.",
  },
  {
    id: "sci-f2-c10-bm-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah julat had pendengaran manusia?",
    back: "20 Hz hingga 20,000 Hz.",
  },
  {
    id: "sci-f2-c10-bm-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Haiwan apakah yang menggunakan ultrabunyi untuk navigasi?",
    back: "Kelawar.",
  },
  {
    id: "sci-f2-c10-bm-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Namakan tiga peranti yang digunakan untuk mengatasi had pendengaran manusia.",
    back: "Stetoskop, megafon, alat bantu dengar.",
  },
  {
    id: "sci-f2-c10-bm-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Berikan contoh haiwan yang berfrekuensi rendah dan tinggi.",
    back: "Lembu (frekuensi rendah) dan tikus (frekuensi tinggi).",
  },
  {
    id: "sci-f2-c10-bm-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah yang berlaku apabila permukaan logam loceng bergetar?",
    back: "Molekul udara berdekatan turut bergetar dan memindahkan getaran dalam bentuk gelombang sehingga bunyi didengar.",
  },

  // Deck 2: Pemahaman (Cards 21-40)
  {
    id: "sci-f2-c10-bm-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bandingkan kelajuan rebakan bunyi dalam pepejal, cecair dan gas.",
    back: "Paling cepat dalam pepejal, kurang cepat dalam cecair, paling perlahan dalam gas — bergantung kepada kerapatan susunan zarah.",
  },
  {
    id: "sci-f2-c10-bm-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bandingkan pantulan dan penyerapan bunyi.",
    back: "Pantulan: permukaan keras dan licin (jubin marmar, dinding). Penyerapan: permukaan lembut dan kasar (karpet, papan lembut).",
  },
  {
    id: "sci-f2-c10-bm-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bandingkan kelantangan dengan kelaraban bunyi.",
    back: "Kelantangan bergantung kepada amplitud; kelaraban bergantung kepada frekuensi.",
  },
  {
    id: "sci-f2-c10-bm-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah kesan peningkatan kuasa output pada penjana isyarat audio?",
    back: "Meningkatkan amplitud gelombang, menjadikan bunyi lebih lantang.",
  },
  {
    id: "sci-f2-c10-bm-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah kesan peningkatan frekuensi pada penjana isyarat audio?",
    back: "Meningkatkan frekuensi gelombang, menjadikan kelaraban bunyi lebih tinggi.",
  },
  {
    id: "sci-f2-c10-bm-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah yang berlaku kepada frekuensi siren apabila ambulans mendekati pemerhati pegun?",
    back: "Frekuensi yang didengar oleh pemerhati meningkat.",
  },
  {
    id: "sci-f2-c10-bm-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah yang berlaku kepada frekuensi siren apabila ambulans menjauhi pemerhati pegun?",
    back: "Frekuensi yang didengar oleh pemerhati menurun.",
  },
  {
    id: "sci-f2-c10-bm-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bandingkan tempat-tempat di mana gegaran boleh didengar.",
    back: "Dewan tertutup, bilik kosong, gua, terowong dan gaung — kesemuanya mempunyai permukaan keras yang memantulkan bunyi.",
  },
  {
    id: "sci-f2-c10-bm-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah perbezaan antara bunyi biasa dan ultrabunyi?",
    back: "Bunyi biasa dapat didengar manusia (20 Hz–20,000 Hz); ultrabunyi (>20,000 Hz) tidak dapat didengar manusia tetapi dapat didengar haiwan seperti kelawar.",
  },
  {
    id: "sci-f2-c10-bm-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Namakan sektor-sektor yang menggunakan teknologi sonar.",
    back: "Perkapalan (mengesan objek bawah air), perubatan, dan perikanan.",
  },
  {
    id: "sci-f2-c10-bm-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bandingkan julat pendengaran kelawar dan lumba-lumba (Hz).",
    back: "Kelawar: 2,000–110,000 Hz. Lumba-lumba: 40–100,000 Hz.",
  },
  {
    id: "sci-f2-c10-bm-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bandingkan julat pendengaran anjing, gajah dan kuda (Hz).",
    back: "Anjing: 67–45,000 Hz. Gajah: 16–12,000 Hz. Kuda: 55–33,500 Hz.",
  },
  {
    id: "sci-f2-c10-bm-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bagaimanakah stetoskop berfungsi?",
    back: "Membantu doktor mendengar denyutan jantung pesakit dengan lebih jelas, mengatasi had pendengaran manusia.",
  },
  {
    id: "sci-f2-c10-bm-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bagaimanakah megafon berfungsi?",
    back: "Memperkuatkan suara supaya boleh didengar dari jauh.",
  },
  {
    id: "sci-f2-c10-bm-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bagaimanakah alat bantu dengar berfungsi?",
    back: "Memperkuatkan bunyi yang memasuki telinga.",
  },
  {
    id: "sci-f2-c10-bm-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Mengapakah julat pendengaran manusia semakin mengecil dengan usia?",
    back: "Kerana telinga kehilangan kepekaan terhadap frekuensi bunyi seiring usia.",
  },
  {
    id: "sci-f2-c10-bm-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah Aktiviti 10.1 buktikan?",
    back: "Bunyi loceng penggera tidak dapat didengar selepas udara dikeluarkan daripada balang loceng — membuktikan bunyi memerlukan medium.",
  },
  {
    id: "sci-f2-c10-bm-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah Aktiviti 10.4 kaji?",
    back: "Kesan Doppler menggunakan hon udara — kelaraban bunyi yang didengar pemerhati berubah semasa hon bergerak melepasinya.",
  },
  {
    id: "sci-f2-c10-bm-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Bandingkan permukaan logam dan permukaan tuala dari segi sifat bunyi.",
    back: "Logam (keras dan licin): memantulkan bunyi dengan baik. Tuala (lembut dan kasar): menyerap bunyi dengan baik.",
  },
  {
    id: "sci-f2-c10-bm-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Mengapakah dewan panggung wayang dilapisi papan lembut?",
    back: "Untuk menyerap bunyi dan mengurangkan gaung (gegaran berlebihan) dalam dewan.",
  },

  // Deck 3: Peperiksaan (Cards 41-60)
  {
    id: "sci-f2-c10-bm-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Mengapakah bunyi siren ambulans berubah kelaraban semasa lalu di hadapan pemerhati pegun?",
    back: "Disebabkan kesan Doppler — frekuensi meningkat semasa mendekati dan menurun semasa menjauhi pemerhati akibat pergerakan relatif sumber bunyi.",
  },
  {
    id: "sci-f2-c10-bm-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Mengapakah orang yang membawa hon udara tidak rasa perubahan kelaraban semasa bergerak?",
    back: "Kerana tiada pergerakan relatif antara orang itu dan sumber bunyi yang dibawanya sendiri.",
  },
  {
    id: "sci-f2-c10-bm-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Mengapakah jurutera bilik rakaman melapisi dinding dengan bahan penyerap bunyi?",
    back: "Untuk mengurangkan gegaran dan menghasilkan rakaman bunyi berkualiti tinggi, kerana permukaan lembut dan kasar menyerap bunyi dengan baik.",
  },
  {
    id: "sci-f2-c10-bm-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Mengapakah ultrabunyi sesuai digunakan untuk mengimbas fetus (sonogram) berbanding kaedah lain?",
    back: "Frekuensi tingginya membolehkan pantulan tepat daripada struktur dalaman badan dengan kaedah yang dianggap lebih selamat.",
  },
  {
    id: "sci-f2-c10-bm-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Seekor haiwan mempunyai julat pendengaran 2,000–110,000 Hz. Apakah haiwan tersebut?",
    back: "Kelawar — julat pendengarannya yang luas membolehkannya menggunakan ultrabunyi untuk navigasi (ekolokasi).",
  },
  {
    id: "sci-f2-c10-bm-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah bunyi dapat merebak dalam vakum jika sumber bunyi masih bergetar?",
    back: "Tidak. Bunyi tetap tidak dapat merebak dalam vakum kerana ia memerlukan medium (zarah) untuk memindahkan getaran, walaupun sumber masih bergetar.",
  },
  {
    id: "sci-f2-c10-bm-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah kelantangan dan kelaraban bunyi perkara yang sama?",
    back: "Tidak. Kelantangan bergantung kepada amplitud, manakala kelaraban bergantung kepada frekuensi — kedua-duanya ciri berbeza.",
  },
  {
    id: "sci-f2-c10-bm-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Mengapakah manusia tidak dapat mendengar ultrabunyi walaupun ia adalah gelombang bunyi?",
    back: "Kerana ultrabunyi mempunyai frekuensi lebih daripada 20,000 Hz, melebihi had pendengaran manusia (20 Hz–20,000 Hz).",
  },
  {
    id: "sci-f2-c10-bm-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[Tip Peperiksaan] Bagaimana menjawab soalan 'jelaskan mengapa bunyi merebak lebih cepat dalam pepejal'?",
    back: "Nyatakan: zarah pepejal tersusun rapat antara satu sama lain, jadi getaran daripada satu zarah segera menyebabkan zarah berdekatan turut bergetar.",
  },
  {
    id: "sci-f2-c10-bm-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Bagaimanakah ekolokasi kelawar berkait dengan teknologi sonar manusia?",
    back: "Kedua-duanya menggunakan prinsip pantulan gelombang bunyi/ultrabunyi untuk mengesan kedudukan, jarak atau objek di sekeliling.",
  },
  {
    id: "sci-f2-c10-bm-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[Fakta Penting] Apakah yang ditunjukkan oleh aktiviti membandingkan papan kayu, kepingan logam dan tuala?",
    back: "Permukaan logam (keras dan licin) memantulkan bunyi dengan baik; tuala (lembut dan kasar) menyerap bunyi dengan baik.",
  },
  {
    id: "sci-f2-c10-bm-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Mengapakah gegaran berulang dapat didengar dalam gua tetapi tidak dalam bilik berkarpet?",
    back: "Gua mempunyai permukaan keras yang memantulkan bunyi berulang-ulang; bilik berkarpet menyerap bunyi (permukaan lembut), mengurangkan pantulan.",
  },
  {
    id: "sci-f2-c10-bm-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[Kesilapan Lazim] Adakah semua haiwan mempunyai julat pendengaran yang sama dengan manusia?",
    back: "Tidak. Haiwan seperti kelawar, lumba-lumba dan anjing mempunyai julat pendengaran yang lebih tinggi berbanding manusia (20 Hz–20,000 Hz).",
  },
  {
    id: "sci-f2-c10-bm-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Jika seseorang ingin mengurangkan gaung dalam sebuah dewan, apakah bahan yang patut digunakan dan mengapa?",
    back: "Bahan lembut dan kasar (seperti papan lembut atau karpet) kerana ia menyerap bunyi dengan baik, mengurangkan pantulan berulang yang menyebabkan gaung.",
  },
  {
    id: "sci-f2-c10-bm-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Apakah perbezaan antara bunyi lengkingan tikus dan lenguhan lembu?",
    back: "Lengkingan tikus berfrekuensi tinggi (kelaraban tinggi); lenguhan lembu berfrekuensi rendah (kelaraban rendah).",
  },
  {
    id: "sci-f2-c10-bm-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Bagaimanakah cara menekan kekunci piano mempengaruhi bunyi yang dihasilkan?",
    back: "Cara menekan kekunci menentukan amplitud getaran, sekali gus menentukan kekuatan (kelantangan) bunyi yang dihasilkan.",
  },
  {
    id: "sci-f2-c10-bm-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Namakan tiga contoh aplikasi pantulan gelombang bunyi.",
    back: "Sonar (perkapalan), ultrabunyi (perubatan/sonogram), dan ekolokasi haiwan seperti kelawar.",
  },
  {
    id: "sci-f2-c10-bm-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[Kesilapan Lazim] Bolehkah gegaran terhasil daripada permukaan lembut seperti karpet?",
    back: "Tidak biasanya. Gegaran biasanya terhasil daripada pantulan bunyi pada permukaan keras; permukaan lembut menyerap bunyi dan mengurangkan gegaran.",
  },
  {
    id: "sci-f2-c10-bm-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "[KBAT] Apakah yang akan berlaku kepada kelaraban bunyi jika frekuensi gelombang bunyi digandakan?",
    back: "Kelaraban bunyi akan menjadi lebih tinggi, kerana kelaraban berkadar terus dengan frekuensi gelombang bunyi.",
  },
  {
    id: "sci-f2-c10-bm-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 10",
    lang: "bm",
    front: "Ringkaskan peta konsep Bab 10 dalam satu ayat.",
    back: "Gelombang bunyi merebak melalui medium dan mempunyai ciri kelantangan (amplitud) serta kelaraban (frekuensi), dengan fenomena seperti kesan Doppler, gegaran, ultrabunyi dan sonar sebagai aplikasi pantulan bunyi.",
  },
];
