import type { QuizQuestion } from "@/data/content";

export const scienceF2C10QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c10-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Sound is a form of energy caused by...",
    options: ["Vibration", "Light", "Magnetism", "Heating"],
    answerIndex: 0,
    explanation:
      "Sound is a form of energy caused by vibration, for example the vibration of vocal cords while speaking.",
  },
  {
    id: "sci-f2-c10-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Sound cannot propagate through...",
    options: ["Solids", "Liquids", "Gases", "A vacuum"],
    answerIndex: 3,
    explanation:
      "Sound requires a medium to propagate and cannot propagate through a vacuum (an area without air).",
  },
  {
    id: "sci-f2-c10-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "In which medium does sound propagate fastest?",
    options: ["Gas", "Liquid", "Solid", "Vacuum"],
    answerIndex: 2,
    explanation:
      "Sound propagates fastest in solids because the particles are arranged very closely together.",
  },
  {
    id: "sci-f2-c10-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "A guitarist tightens a guitar string to tune it. What happens to the pitch of the sound produced, and why?",
    options: [
      "The pitch decreases, because a tighter string vibrates at a lower frequency",
      "The volume increases, but the pitch is unaffected",
      "The pitch increases, because a tighter string vibrates at a higher frequency",
      "The pitch stays the same, because tightness does not affect a string's vibration",
    ],
    answerIndex: 2,
    explanation:
      "Tightening a guitar string increases the frequency at which it vibrates, producing a higher pitch. This shows the relationship between frequency and pitch in musical instruments.",
  },
  {
    id: "sci-f2-c10-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Which statement correctly compares sound reflectors and sound absorbers?",
    options: [
      "Hard, smooth surfaces are good reflectors; soft, rough surfaces are good absorbers",
      "Hard, smooth surfaces are good absorbers; soft, rough surfaces are good reflectors",
      "Both hard and soft surfaces reflect sound equally well",
      "Only metal surfaces can reflect or absorb sound",
    ],
    answerIndex: 0,
    explanation:
      "Hard and smooth surfaces, such as marble tiles and walls, reflect sound well. Soft and rough surfaces, such as carpet and softboard, absorb sound well.",
  },
  {
    id: "sci-f2-c10-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "How does a megaphone help a person's voice be heard from a distance?",
    options: [
      "It changes the voice to a higher pitch",
      "It converts the voice into ultrasound",
      "It amplifies the voice so that it can be heard from a distance",
      "It removes background noise from the voice",
    ],
    answerIndex: 2,
    explanation:
      "A megaphone amplifies a person's voice so that it can be heard from a distance, similar to how a hearing aid amplifies sound entering the ear.",
  },
  {
    id: "sci-f2-c10-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "The loudness of sound depends on...",
    options: [
      "The amplitude of the sound wave",
      "The frequency of the sound wave",
      "The distance of the source",
      "The colour of the sound wave",
    ],
    answerIndex: 0,
    explanation:
      "Loudness of sound depends on the amplitude of the sound wave — the greater the amplitude, the louder the sound.",
  },
  {
    id: "sci-f2-c10-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "The pitch of sound depends on...",
    options: [
      "The amplitude of the sound wave",
      "The frequency of the sound wave",
      "The speed of the sound wave",
      "The temperature of the surrounding air",
    ],
    answerIndex: 1,
    explanation:
      "Pitch of sound depends on the frequency of the sound wave — the higher the frequency, the higher the pitch.",
  },
  {
    id: "sci-f2-c10-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What unit is used to measure the frequency of sound?",
    options: ["Metre", "Newton", "Hertz (Hz)", "Joule"],
    answerIndex: 2,
    explanation: "Frequency of sound is measured in hertz (Hz).",
  },
  {
    id: "sci-f2-c10-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What is meant by an echo?",
    options: [
      "Sound produced when a sound wave is reflected from a hard surface to the listener",
      "Sound that can only be heard by animals",
      "Sound produced by air vibration in a vacuum",
      "Sound fully absorbed by a soft surface",
    ],
    answerIndex: 0,
    explanation:
      "An echo is produced when sound waves are reflected from a hard surface to the listener, taking some time to reach the ears.",
  },
  {
    id: "sci-f2-c10-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "Why can't the sound of an alarm clock's ringing be heard after air is sucked out of a bell jar using a vacuum pump?",
    options: [
      "Because the alarm clock stops vibrating when the air is removed",
      "Because sound cannot propagate through a vacuum",
      "Because the frequency of the alarm clock falls below 20 Hz",
      "Because the amplitude of the alarm clock's vibration becomes zero",
    ],
    answerIndex: 1,
    explanation:
      "The vacuum jar demonstration shows sound cannot propagate through a vacuum because it requires a medium, even though the alarm clock is still vibrating inside the jar.",
  },
  {
    id: "sci-f2-c10-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Why does sound propagate faster in solids compared to gases?",
    options: [
      "Because solid particles are closer together, so the vibration is passed on faster",
      "Because solid particles are farther apart, so the vibration has more space",
      "Because gas particles are closer together than solid particles",
      "Because solid particles vibrate more slowly, so sound takes a shorter path",
    ],
    answerIndex: 0,
    explanation:
      "The close arrangement of solid particles allows vibration from one particle to immediately cause nearby particles to vibrate, unlike gas particles which are far apart.",
  },
  {
    id: "sci-f2-c10-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "How is the sound of a bell transferred to a listener?",
    options: [
      "The bell metal vibrates and that vibration is passed through air molecules as a wave",
      "The bell vibrates, but the vibration travels through a vacuum without air molecules",
      "Air molecules vibrate first, and that vibration then moves the bell",
      "The bell vibrates and the vibration travels only through solids, not through air",
    ],
    answerIndex: 0,
    explanation:
      "When a bell is rung, its metal surface vibrates, causing nearby air molecules to vibrate and transfer the vibration in the form of waves until it is heard by the listener.",
  },
  {
    id: "sci-f2-c10-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "In the investigation using a C.R.O. and an audio signal generator, what is the effect of increasing output power?",
    options: [
      "Increases the amplitude of the wave, making the sound louder",
      "Increases the frequency of the wave, making the pitch higher",
      "Decreases the speed of sound",
      "Decreases the frequency of the wave, making the pitch lower",
    ],
    answerIndex: 0,
    explanation:
      "Increasing output power increases the amplitude of the sound wave, causing the sound to become louder.",
  },
  {
    id: "sci-f2-c10-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "In the investigation using a C.R.O. and an audio signal generator, what is the effect of increasing frequency?",
    options: [
      "Increases the amplitude, making the sound louder",
      "Increases the frequency, making the pitch higher",
      "Decreases the amplitude, making the sound softer",
      "Increases the speed of sound in air",
    ],
    answerIndex: 1,
    explanation:
      "Increasing the frequency on the audio signal generator increases the wave frequency, causing the pitch to become higher.",
  },
  {
    id: "sci-f2-c10-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What is meant by the Doppler effect?",
    options: [
      "A change in frequency caused by relative movement of the source or observer",
      "The reflection of sound from a hard surface",
      "The absorption of sound by a soft surface",
      "Sound that cannot propagate through a vacuum",
    ],
    answerIndex: 0,
    explanation:
      "The Doppler effect is the apparent change in frequency caused by relative movement between the sound source and the observer.",
  },
  {
    id: "sci-f2-c10-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "What happens to the frequency of an ambulance siren heard by a stationary observer when the ambulance approaches them?",
    options: [
      "The frequency becomes zero",
      "The frequency decreases",
      "The frequency stays the same",
      "The frequency increases",
    ],
    answerIndex: 3,
    explanation:
      "The frequency of an ambulance siren heard by an observer increases when the ambulance approaches the stationary observer, according to the Doppler effect.",
  },
  {
    id: "sci-f2-c10-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Which type of sound wave has a frequency of more than 20,000 Hz?",
    options: ["Infrasound", "Ultrasound", "Echo", "Radio wave"],
    answerIndex: 1,
    explanation:
      "Ultrasound is a sound wave with a frequency of more than 20,000 Hz, which cannot be heard by humans but can be heard by animals such as bats.",
  },
  {
    id: "sci-f2-c10-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Sonar technology is used in the shipping industry to...",
    options: [
      "Clean seawater",
      "Generate electricity",
      "Measure the temperature of seawater",
      "Detect underwater objects",
    ],
    answerIndex: 3,
    explanation:
      "Sonar is a sound reflection technology used in the shipping industry to detect underwater objects, and is also used in medical and fisheries sectors.",
  },
  {
    id: "sci-f2-c10-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What is the range of sound frequency that can be detected by humans?",
    options: [
      "2 Hz to 2,000 Hz",
      "20 Hz to 20,000 Hz",
      "200 Hz to 200,000 Hz",
      "2,000 Hz to 100,000 Hz",
    ],
    answerIndex: 1,
    explanation:
      "The limit of human hearing is within the range of 20 Hz to 20,000 Hz, and this range becomes narrower with age.",
  },
  {
    id: "sci-f2-c10-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "Which animal has the highest upper limit of hearing?",
    options: [
      "Dog (67–45,000)",
      "Dolphin (40–100,000)",
      "Bat (2,000–110,000)",
      "Horse (55–33,500)",
    ],
    answerIndex: 2,
    explanation:
      "Bats have the highest hearing range with an upper limit of 110,000 Hz, compared to dolphins (100,000 Hz), dogs (45,000 Hz) and horses (33,500 Hz).",
  },
  {
    id: "sci-f2-c10-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "A doctor uses a device to listen to a patient's heartbeat more clearly. What device is used, and how does it work?",
    options: [
      "Loudspeaker — makes a sound louder for a distant listener",
      "Stethoscope — channels the heartbeat to the doctor's ear",
      "Hearing aid — amplifies the sound entering the ear",
      "Megaphone — concentrates sound so that it travels farther",
    ],
    answerIndex: 1,
    explanation:
      "A stethoscope is a device that helps doctors hear a patient's heartbeat more clearly, overcoming the limitations of human hearing.",
  },
  {
    id: "sci-f2-c10-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Why can a repeated echo be heard inside a cave?",
    options: [
      "Because the air in the cave is a vacuum",
      "Because sound is reflected back and forth repeatedly between the hard surfaces of the cave",
      "Because the cave naturally produces ultrasound",
      "Because the frequency of sound becomes very low inside a cave",
    ],
    answerIndex: 1,
    explanation:
      "A repeated echo in a cave is caused by sound being reflected back and forth repeatedly between the hard surfaces of the cave before reaching the listener's ears.",
  },
  {
    id: "sci-f2-c10-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "A recording studio engineer lines the walls with sound-absorbing material. What is the main purpose of this, and why is it effective?",
    options: [
      "To increase the amplitude so the recording is louder",
      "To increase the frequency of the recorded sound",
      "To reflect sound so the echo becomes stronger",
      "To absorb sound so the echo is reduced and the recording is clearer",
    ],
    answerIndex: 3,
    explanation:
      "Sound-absorbing materials (soft and rough) reduce the reflection of sound that causes echo, producing high-quality sound recordings.",
  },
  {
    id: "sci-f2-c10-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "A stationary observer hears an ambulance siren whose frequency increases, then decreases after the ambulance passes by. What is the most accurate explanation for this phenomenon?",
    options: [
      "The amplitude of the siren sound changes suddenly",
      "The siren sound is reflected by the road surface",
      "The Doppler effect — frequency increases as the ambulance approaches and decreases as it moves away from the observer",
      "The frequency of the siren sound is always constant but the observer's ear changes",
    ],
    answerIndex: 2,
    explanation:
      "This is a classic example of the Doppler effect, where the frequency of sound heard by a stationary observer changes due to the relative movement of the sound source (ambulance).",
  },
  {
    id: "sci-f2-c10-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "Why doesn't a person carrying a sound source (e.g. an air horn) feel a change in pitch while moving, unlike a stationary observer?",
    options: [
      "Because pitch changes only when the observer moves, not the source",
      "Because the air horn produces the same frequency for every listener",
      "Because a stationary observer hears the same frequency even when the source moves",
      "Because there is no relative movement between the source and the person carrying it",
    ],
    answerIndex: 3,
    explanation:
      "The Doppler effect depends on relative movement between the sound source and the observer; the person carrying the source experiences no relative movement with respect to the source itself.",
  },
  {
    id: "sci-f2-c10-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "Bats use ultrasound to navigate in the dark. How does this principle relate to the sonar technology used by humans?",
    options: [
      "Both use reflected light to detect objects",
      "Bats use sound, while sonar uses radio waves",
      "Both use the reflection of ultrasound to detect the distance of objects",
      "Bats emit sound, but sonar only listens and does not emit sound",
    ],
    answerIndex: 2,
    explanation:
      "Both bat echolocation and sonar technology use the principle of sound/ultrasound wave reflection to detect the position, distance or objects around them.",
  },
  {
    id: "sci-f2-c10-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "A student claims 'humans can hear all types of sound including ultrasound'. Is this claim accurate? Why?",
    options: [
      "Accurate, because the human range includes frequencies above 20,000 Hz",
      "Not accurate, because humans hear only sounds below 20 Hz",
      "Accurate, because ultrasound lies between 20 Hz and 20,000 Hz",
      "Not accurate, because ultrasound is above 20,000 Hz, outside the range 20 Hz–20,000 Hz",
    ],
    answerIndex: 3,
    explanation:
      "The claim is not accurate because the limit of human hearing is 20 Hz to 20,000 Hz, while ultrasound has a frequency of more than 20,000 Hz and cannot be heard by humans.",
  },
  {
    id: "sci-f2-c10-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "Doctors use ultrasound to scan a foetus in the womb (sonogram). What are the benefits of using ultrasound for this purpose?",
    options: [
      "It is louder than ordinary sound, so it is easier to detect",
      "It is not harmful to the foetus, is painless, does not use radiation, and results can be obtained immediately",
      "It allows the foetus to hear music for communication purposes",
      "It requires the foetus to be exposed to X-rays for clearer images",
    ],
    answerIndex: 1,
    explanation:
      "Ultrasound scanning (sonogram) is not harmful to the foetus, is painless, does not use radiation, may be performed repeatedly, and results can be obtained immediately — making it a suitable method for prenatal scanning.",
  },
  {
    id: "sci-f2-c10-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question:
      "Why does the human hearing range become narrower with age, and what are the implications for the need for hearing aids?",
    options: [
      "Because the ear becomes more sensitive to every frequency, so a hearing aid is not needed",
      "Because the ear loses sensitivity only to sounds below 20 Hz",
      "Because the amplitude of speech increases, so sounds become too loud",
      "Because the ear loses sensitivity to some frequencies, so a hearing aid amplifies the sound",
    ],
    answerIndex: 3,
    explanation:
      "The human hearing range narrows with age due to loss of ear sensitivity to certain sound frequencies; hearing aids help amplify sound entering the ear to overcome this limitation.",
  },
];
