import type { QuizQuestion } from "@/data/content";

export const scienceF2C10QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c10-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Sound is a form of energy caused by...",
    options: ["Vibration", "Light", "Magnetism", "Heating"],
    answerIndex: 0,
    explanation: "Sound is a form of energy caused by vibration, for example the vibration of vocal cords while speaking.",
  },
  {
    id: "sci-f2-c10-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Sound cannot propagate through...",
    options: ["Solids", "Liquids", "Gases", "A vacuum"],
    answerIndex: 3,
    explanation: "Sound requires a medium to propagate and cannot propagate through a vacuum (an area without air).",
  },
  {
    id: "sci-f2-c10-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "In which medium does sound propagate fastest?",
    options: ["Gas", "Liquid", "Solid", "Vacuum"],
    answerIndex: 2,
    explanation: "Sound propagates fastest in solids because the particles are arranged very closely together.",
  },
  {
    id: "sci-f2-c10-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "In which medium does sound propagate most slowly?",
    options: ["Solid", "Liquid", "Gas", "Metal"],
    answerIndex: 2,
    explanation: "Sound propagates most slowly in gases because gas particles are arranged far apart from each other.",
  },
  {
    id: "sci-f2-c10-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What kind of surface is a good sound reflector?",
    options: [
      "Hard and smooth surface",
      "Soft and rough surface",
      "Carpeted surface",
      "Perforated surface",
    ],
    answerIndex: 0,
    explanation: "Hard and smooth surfaces such as marble tiles and walls are good sound reflectors.",
  },
  {
    id: "sci-f2-c10-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What kind of surface is a good sound absorber?",
    options: [
      "Hard and smooth surface",
      "Soft and rough surface",
      "Metal surface",
      "Tiled surface",
    ],
    answerIndex: 1,
    explanation: "Soft and rough surfaces such as carpet and softboard are good sound absorbers.",
  },
  {
    id: "sci-f2-c10-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "The loudness of sound depends on...",
    options: ["The amplitude of the sound wave", "The frequency of the sound wave", "The distance of the source", "The colour of the sound wave"],
    answerIndex: 0,
    explanation: "Loudness of sound depends on the amplitude of the sound wave — the greater the amplitude, the louder the sound.",
  },
  {
    id: "sci-f2-c10-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "The pitch of sound depends on...",
    options: ["The amplitude of the sound wave", "The frequency of the sound wave", "The speed of sound", "The air temperature"],
    answerIndex: 1,
    explanation: "Pitch of sound depends on the frequency of the sound wave — the higher the frequency, the higher the pitch.",
  },
  {
    id: "sci-f2-c10-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What unit is used to measure the frequency of sound?",
    options: ["Metre", "Newton", "Hertz (Hz)", "Joule"],
    answerIndex: 2,
    explanation: "Frequency of sound is measured in hertz (Hz).",
  },
  {
    id: "sci-f2-c10-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What is meant by an echo?",
    options: [
      "Sound produced when a sound wave is reflected from a hard surface to the listener",
      "Sound that can only be heard by animals",
      "Sound produced by air vibration in a vacuum",
      "Sound fully absorbed by a soft surface",
    ],
    answerIndex: 0,
    explanation: "An echo is produced when sound waves are reflected from a hard surface to the listener, taking some time to reach the ears.",
  },
  {
    id: "sci-f2-c10-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Why can't the sound of an alarm clock's ringing be heard after air is sucked out of a bell jar using a vacuum pump?",
    options: [
      "Because the alarm clock stops vibrating",
      "Because sound requires a medium to propagate and cannot propagate through a vacuum",
      "Because the frequency of the alarm clock changes",
      "Because the amplitude of the alarm clock becomes zero",
    ],
    answerIndex: 1,
    explanation: "Activity 10.1 shows sound cannot propagate through a vacuum because it requires a medium, even though the alarm clock is still vibrating inside the jar.",
  },
  {
    id: "sci-f2-c10-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Why does sound propagate faster in solids compared to gases?",
    options: [
      "Because solid particles are arranged closely together compared to gas particles, which are far apart",
      "Because solids are heavier than gases",
      "Because gases do not have particles",
      "Because the temperature of solids is higher than gases",
    ],
    answerIndex: 0,
    explanation: "The close arrangement of solid particles allows vibration from one particle to immediately cause nearby particles to vibrate, unlike gas particles which are far apart.",
  },
  {
    id: "sci-f2-c10-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "How is the sound of a bell transferred to a listener?",
    options: [
      "The metal surface of the bell vibrates, nearby air molecules also vibrate and collide with other air molecules, transferring vibration in the form of waves",
      "The bell produces light that is seen by the listener",
      "The bell heats the air until sound is produced",
      "Sound is transferred directly without any medium",
    ],
    answerIndex: 0,
    explanation: "When a bell is rung, its metal surface vibrates, causing nearby air molecules to vibrate and transfer the vibration in the form of waves until it is heard by the listener.",
  },
  {
    id: "sci-f2-c10-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "In Activity 10.2 using a C.R.O. and an audio signal generator, what is the effect of increasing output power?",
    options: [
      "Increases the amplitude of the wave, making the sound louder",
      "Increases the frequency of the wave, making the pitch higher",
      "Decreases the speed of sound",
      "Converts sound into light",
    ],
    answerIndex: 0,
    explanation: "Increasing output power increases the amplitude of the sound wave, causing the sound to become louder.",
  },
  {
    id: "sci-f2-c10-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "In Activity 10.2 using a C.R.O. and an audio signal generator, what is the effect of increasing frequency?",
    options: [
      "Increases the amplitude of the wave",
      "Increases the frequency of the wave, making the pitch higher",
      "Decreases the loudness of the sound",
      "Has no effect at all",
    ],
    answerIndex: 1,
    explanation: "Increasing the frequency on the audio signal generator increases the wave frequency, causing the pitch to become higher.",
  },
  {
    id: "sci-f2-c10-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What is meant by the Doppler effect?",
    options: [
      "The apparent change in frequency caused by the relative movement of the sound source, the observer, or both",
      "The reflection of sound from a hard surface",
      "The absorption of sound by a soft surface",
      "The loss of ear sensitivity to high frequencies",
    ],
    answerIndex: 0,
    explanation: "The Doppler effect is the apparent change in frequency caused by relative movement between the sound source and the observer.",
  },
  {
    id: "sci-f2-c10-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What happens to the frequency of an ambulance siren heard by a stationary observer when the ambulance approaches them?",
    options: ["The frequency increases", "The frequency decreases", "The frequency stays the same", "The frequency becomes zero"],
    answerIndex: 0,
    explanation: "The frequency of an ambulance siren heard by an observer increases when the ambulance approaches the stationary observer, according to the Doppler effect.",
  },
  {
    id: "sci-f2-c10-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Which type of sound wave has a frequency of more than 20,000 Hz?",
    options: ["Infrasound", "Ultrasound", "Echo", "Radio wave"],
    answerIndex: 1,
    explanation: "Ultrasound is a sound wave with a frequency of more than 20,000 Hz, which cannot be heard by humans but can be heard by animals such as bats.",
  },
  {
    id: "sci-f2-c10-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Sonar technology is used in the shipping industry to...",
    options: [
      "Detect underwater objects",
      "Generate electricity",
      "Measure the temperature of seawater",
      "Clean seawater",
    ],
    answerIndex: 0,
    explanation: "Sonar is a sound reflection technology used in the shipping industry to detect underwater objects, and is also used in medical and fisheries sectors.",
  },
  {
    id: "sci-f2-c10-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "What is the range of sound frequency that can be detected by humans?",
    options: ["2 Hz to 2,000 Hz", "20 Hz to 20,000 Hz", "200 Hz to 200,000 Hz", "2,000 Hz to 100,000 Hz"],
    answerIndex: 1,
    explanation: "The limit of human hearing is within the range of 20 Hz to 20,000 Hz, and this range becomes narrower with age.",
  },
  {
    id: "sci-f2-c10-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Based on the table of animal hearing ranges, which animal has the highest hearing range (Hz)?",
    options: ["Dog (67–45,000)", "Dolphin (40–100,000)", "Bat (2,000–110,000)", "Horse (55–33,500)"],
    answerIndex: 2,
    explanation: "Bats have the highest hearing range with an upper limit of 110,000 Hz, compared to dolphins (100,000 Hz), dogs (45,000 Hz) and horses (33,500 Hz).",
  },
  {
    id: "sci-f2-c10-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "A doctor uses a device to listen to a patient's heartbeat more clearly. What device is used, and how does it work?",
    options: [
      "Megaphone — amplifies the voice to be heard from a distance",
      "Stethoscope — helps the doctor hear the patient's heartbeat by channelling and amplifying the sound",
      "Hearing aid — amplifies sound entering the ear of the general public",
      "Sonar — detects objects underwater",
    ],
    answerIndex: 1,
    explanation: "A stethoscope is a device that helps doctors hear a patient's heartbeat more clearly, overcoming the limitations of human hearing.",
  },
  {
    id: "sci-f2-c10-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Why can a repeated echo be heard inside a cave?",
    options: [
      "Because the air in the cave is a vacuum",
      "Because sound is reflected back and forth repeatedly between the hard surfaces of the cave",
      "Because the cave naturally produces ultrasound",
      "Because the frequency of sound becomes very low inside a cave",
    ],
    answerIndex: 1,
    explanation: "A repeated echo in a cave is caused by sound being reflected back and forth repeatedly between the hard surfaces of the cave before reaching the listener's ears.",
  },
  {
    id: "sci-f2-c10-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "A recording studio engineer lines the walls with sound-absorbing material. What is the main purpose of this, and why is it effective?",
    options: [
      "To increase the amplitude of sound so recordings are louder",
      "To reduce echo and produce high-quality recordings, because soft and rough surfaces absorb sound well",
      "To convert sound into ultrasound",
      "To increase the frequency of the recorded sound",
    ],
    answerIndex: 1,
    explanation: "Sound-absorbing materials (soft and rough) reduce the reflection of sound that causes echo, producing high-quality sound recordings.",
  },
  {
    id: "sci-f2-c10-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "A stationary observer hears an ambulance siren whose frequency increases, then decreases after the ambulance passes by. What is the most accurate explanation for this phenomenon?",
    options: [
      "The amplitude of the siren sound changes suddenly",
      "The Doppler effect — frequency increases as the ambulance approaches and decreases as it moves away from the observer",
      "The siren sound is reflected by the road surface",
      "The frequency of the siren sound is always constant but the observer's ear changes",
    ],
    answerIndex: 1,
    explanation: "This is a classic example of the Doppler effect, where the frequency of sound heard by a stationary observer changes due to the relative movement of the sound source (ambulance).",
  },
  {
    id: "sci-f2-c10-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Why doesn't a person carrying a sound source (e.g. an air horn) feel a change in pitch while moving, unlike a stationary observer?",
    options: [
      "Because the air horn does not produce any sound",
      "Because there is no relative movement between the sound source and the person carrying it, unlike the stationary observer who experiences relative movement towards the source",
      "Because the person's ears are deaf",
      "Because the air horn only produces ultrasound",
    ],
    answerIndex: 1,
    explanation: "The Doppler effect depends on relative movement between the sound source and the observer; the person carrying the source experiences no relative movement with respect to the source itself.",
  },
  {
    id: "sci-f2-c10-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Bats use ultrasound to navigate in the dark. How does this principle relate to the sonar technology used by humans?",
    options: [
      "Both use light to detect objects",
      "Both use the reflection of sound waves (ultrasound) to detect the position or distance of objects",
      "They are not related at all",
      "Bats use magnetism, while sonar uses sound",
    ],
    answerIndex: 1,
    explanation: "Both bat echolocation and sonar technology use the principle of sound/ultrasound wave reflection to detect the position, distance or objects around them.",
  },
  {
    id: "sci-f2-c10-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "A student claims 'humans can hear all types of sound including ultrasound'. Is this claim accurate? Why?",
    options: [
      "Accurate, because human ears are very sensitive",
      "Not accurate, because ultrasound has a frequency of more than 20,000 Hz which exceeds the limit of human hearing (20 Hz–20,000 Hz)",
      "Accurate, because ultrasound is only used by animals",
      "Not accurate, because humans cannot hear any sound at all",
    ],
    answerIndex: 1,
    explanation: "The claim is not accurate because the limit of human hearing is 20 Hz to 20,000 Hz, while ultrasound has a frequency of more than 20,000 Hz and cannot be heard by humans.",
  },
  {
    id: "sci-f2-c10-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Doctors use ultrasound to scan the condition of a foetus in the womb (sonogram). Why is ultrasound suitable for this purpose compared to ordinary sound?",
    options: [
      "Because ultrasound has a high frequency that allows precise reflection from internal body structures without exposing the patient to hazards such as X-rays",
      "Because ultrasound is louder than ordinary sound",
      "Because ultrasound can be heard by the foetus for communication purposes",
      "Because ultrasound does not need a medium to propagate",
    ],
    answerIndex: 0,
    explanation: "Ultrasound is used in sonograms because its high-frequency properties allow precise reflection from internal body structures, using a method considered safer than other techniques.",
  },
  {
    id: "sci-f2-c10-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "dlp",
    question: "Why does the human hearing range become narrower with age, and what are the implications for the need for hearing aids?",
    options: [
      "Because human ears lose sensitivity to certain sound frequencies with age, causing some elderly people to need hearing aids to amplify sound entering the ear",
      "Because elderly people no longer produce sound waves",
      "Because the air around elderly people becomes a vacuum",
      "Because the amplitude of all sounds in the world decreases over time",
    ],
    answerIndex: 0,
    explanation: "The human hearing range narrows with age due to loss of ear sensitivity to certain sound frequencies; hearing aids help amplify sound entering the ear to overcome this limitation.",
  },
];
