import type { QuizQuestion } from "@/data/content";

export const scienceF2C10QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c10-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Bunyi ialah satu bentuk tenaga yang disebabkan oleh...",
    options: ["Getaran", "Cahaya", "Magnet", "Pemanasan"],
    answerIndex: 0,
    explanation: "Bunyi ialah satu bentuk tenaga yang disebabkan oleh getaran, contohnya getaran pita suara semasa bercakap.",
  },
  {
    id: "sci-f2-c10-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Bunyi tidak dapat merebak melalui...",
    options: ["Pepejal", "Cecair", "Gas", "Vakum"],
    answerIndex: 3,
    explanation: "Bunyi memerlukan medium untuk merebak dan tidak dapat merebak melalui vakum (kawasan tanpa udara).",
  },
  {
    id: "sci-f2-c10-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Dalam medium manakah bunyi merebak paling cepat?",
    options: ["Gas", "Cecair", "Pepejal", "Vakum"],
    answerIndex: 2,
    explanation: "Bunyi merebak paling cepat dalam pepejal kerana zarah pepejal tersusun rapat antara satu sama lain.",
  },
  {
    id: "sci-f2-c10-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Dalam medium manakah bunyi merebak paling perlahan?",
    options: ["Pepejal", "Cecair", "Gas", "Logam"],
    answerIndex: 2,
    explanation: "Bunyi merebak paling perlahan dalam gas kerana zarah gas tersusun jauh antara satu sama lain.",
  },
  {
    id: "sci-f2-c10-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah jenis permukaan yang menjadi pemantul bunyi yang baik?",
    options: [
      "Permukaan keras dan licin",
      "Permukaan lembut dan kasar",
      "Permukaan berkarpet",
      "Permukaan berlubang",
    ],
    answerIndex: 0,
    explanation: "Permukaan keras dan licin seperti jubin marmar dan dinding adalah pemantul bunyi yang baik.",
  },
  {
    id: "sci-f2-c10-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah jenis permukaan yang menjadi penyerap bunyi yang baik?",
    options: [
      "Permukaan keras dan licin",
      "Permukaan lembut dan kasar",
      "Permukaan logam",
      "Permukaan jubin",
    ],
    answerIndex: 1,
    explanation: "Permukaan lembut dan kasar seperti karpet dan papan lembut adalah penyerap bunyi yang baik.",
  },
  {
    id: "sci-f2-c10-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Kelantangan bunyi bergantung kepada...",
    options: ["Amplitud gelombang bunyi", "Frekuensi gelombang bunyi", "Jarak sumber bunyi", "Warna gelombang bunyi"],
    answerIndex: 0,
    explanation: "Kelantangan bunyi bergantung kepada amplitud gelombang bunyi — semakin besar amplitud, semakin kuat bunyi.",
  },
  {
    id: "sci-f2-c10-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Kelaraban (pitch) bunyi bergantung kepada...",
    options: ["Amplitud gelombang bunyi", "Frekuensi gelombang bunyi", "Kelajuan bunyi", "Suhu udara"],
    answerIndex: 1,
    explanation: "Kelaraban bunyi bergantung kepada frekuensi gelombang bunyi — semakin tinggi frekuensi, semakin tinggi kelaraban.",
  },
  {
    id: "sci-f2-c10-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah unit yang digunakan untuk mengukur frekuensi bunyi?",
    options: ["Meter", "Newton", "Hertz (Hz)", "Joule"],
    answerIndex: 2,
    explanation: "Frekuensi bunyi diukur dalam unit hertz (Hz).",
  },
  {
    id: "sci-f2-c10-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah yang dimaksudkan dengan gegaran (echo)?",
    options: [
      "Bunyi yang dihasilkan apabila gelombang bunyi dipantulkan daripada permukaan keras kepada pendengar",
      "Bunyi yang hanya dapat didengar oleh haiwan",
      "Bunyi yang dihasilkan oleh getaran udara dalam vakum",
      "Bunyi yang diserap sepenuhnya oleh permukaan lembut",
    ],
    answerIndex: 0,
    explanation: "Gegaran terhasil apabila gelombang bunyi dipantulkan daripada permukaan keras kepada pendengar, dan mengambil sedikit masa untuk sampai ke telinga.",
  },
  {
    id: "sci-f2-c10-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Mengapakah bunyi loceng penggera tidak dapat didengar selepas udara dikeluarkan daripada balang loceng menggunakan pam vakum?",
    options: [
      "Kerana loceng berhenti bergetar",
      "Kerana bunyi memerlukan medium untuk merebak dan tidak dapat merebak melalui vakum",
      "Kerana frekuensi loceng berubah",
      "Kerana amplitud loceng menjadi sifar",
    ],
    answerIndex: 1,
    explanation: "Aktiviti 10.1 menunjukkan bunyi tidak dapat merebak melalui vakum kerana bunyi memerlukan medium, walaupun loceng masih bergetar di dalam balang.",
  },
  {
    id: "sci-f2-c10-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Mengapakah bunyi merebak lebih cepat dalam pepejal berbanding gas?",
    options: [
      "Kerana zarah pepejal tersusun rapat antara satu sama lain berbanding zarah gas yang jauh antara satu sama lain",
      "Kerana pepejal lebih berat daripada gas",
      "Kerana gas tidak mempunyai zarah",
      "Kerana suhu pepejal lebih tinggi daripada gas",
    ],
    answerIndex: 0,
    explanation: "Susunan zarah pepejal yang rapat membolehkan getaran daripada satu zarah segera menyebabkan zarah berdekatan turut bergetar, berbanding zarah gas yang jauh antara satu sama lain.",
  },
  {
    id: "sci-f2-c10-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Bagaimanakah bunyi loceng dipindahkan kepada pendengar?",
    options: [
      "Permukaan logam loceng bergetar, molekul udara berdekatan turut bergetar dan berlanggar dengan molekul udara berdekatan, getaran dipindahkan dalam bentuk gelombang",
      "Loceng menghasilkan cahaya yang dilihat oleh pendengar",
      "Loceng memanaskan udara sehingga bunyi terhasil",
      "Bunyi dipindahkan terus tanpa melalui sebarang medium",
    ],
    answerIndex: 0,
    explanation: "Apabila loceng dibunyikan, permukaan logamnya bergetar, menyebabkan molekul udara berdekatan turut bergetar dan memindahkan getaran tersebut dalam bentuk gelombang sehingga didengar oleh pendengar.",
  },
  {
    id: "sci-f2-c10-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Dalam Aktiviti 10.2 menggunakan C.R.O. dan penjana isyarat audio, apakah kesan peningkatan kuasa output?",
    options: [
      "Meningkatkan amplitud gelombang, menjadikan bunyi lebih lantang",
      "Meningkatkan frekuensi gelombang, menjadikan kelaraban lebih tinggi",
      "Mengurangkan kelajuan bunyi",
      "Menukar bunyi kepada cahaya",
    ],
    answerIndex: 0,
    explanation: "Peningkatan kuasa output meningkatkan amplitud gelombang bunyi, menyebabkan bunyi menjadi lebih lantang.",
  },
  {
    id: "sci-f2-c10-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Dalam Aktiviti 10.2 menggunakan C.R.O. dan penjana isyarat audio, apakah kesan peningkatan frekuensi?",
    options: [
      "Meningkatkan amplitud gelombang",
      "Meningkatkan frekuensi gelombang, menjadikan kelaraban bunyi lebih tinggi",
      "Mengurangkan kelantangan bunyi",
      "Tidak memberi sebarang kesan",
    ],
    answerIndex: 1,
    explanation: "Peningkatan frekuensi pada penjana isyarat audio meningkatkan frekuensi gelombang bunyi, menyebabkan kelaraban bunyi menjadi lebih tinggi.",
  },
  {
    id: "sci-f2-c10-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah yang dimaksudkan dengan kesan Doppler?",
    options: [
      "Perubahan ketara dalam frekuensi yang disebabkan oleh pergerakan relatif sumber bunyi, pemerhati, atau kedua-duanya",
      "Pantulan bunyi daripada permukaan keras",
      "Penyerapan bunyi oleh permukaan lembut",
      "Kehilangan kepekaan telinga terhadap frekuensi tinggi",
    ],
    answerIndex: 0,
    explanation: "Kesan Doppler ialah perubahan ketara dalam frekuensi bunyi yang disebabkan oleh pergerakan relatif antara sumber bunyi dan pemerhati.",
  },
  {
    id: "sci-f2-c10-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah yang berlaku kepada frekuensi siren ambulans yang didengar oleh pemerhati pegun apabila ambulans mendekatinya?",
    options: ["Frekuensi meningkat", "Frekuensi menurun", "Frekuensi kekal sama", "Frekuensi menjadi sifar"],
    answerIndex: 0,
    explanation: "Frekuensi siren ambulans yang didengar oleh pemerhati meningkat apabila ambulans mendekati pemerhati yang pegun, menurut kesan Doppler.",
  },
  {
    id: "sci-f2-c10-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah jenis gelombang bunyi yang mempunyai frekuensi lebih daripada 20,000 Hz?",
    options: ["Infrabunyi", "Ultrabunyi", "Gegaran", "Gelombang radio"],
    answerIndex: 1,
    explanation: "Ultrabunyi ialah gelombang bunyi dengan frekuensi lebih daripada 20,000 Hz, tidak dapat didengar oleh manusia tetapi dapat didengar oleh haiwan seperti kelawar.",
  },
  {
    id: "sci-f2-c10-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Teknologi sonar digunakan dalam industri perkapalan untuk...",
    options: [
      "Mengesan objek bawah air",
      "Menghasilkan elektrik",
      "Mengukur suhu air laut",
      "Membersihkan air laut",
    ],
    answerIndex: 0,
    explanation: "Sonar ialah teknologi pantulan bunyi yang digunakan dalam industri perkapalan untuk mengesan objek bawah air, dan juga digunakan dalam sektor perubatan dan perikanan.",
  },
  {
    id: "sci-f2-c10-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Apakah julat frekuensi bunyi yang dapat dikesan oleh manusia?",
    options: ["2 Hz hingga 2,000 Hz", "20 Hz hingga 20,000 Hz", "200 Hz hingga 200,000 Hz", "2,000 Hz hingga 100,000 Hz"],
    answerIndex: 1,
    explanation: "Had pendengaran manusia adalah dalam julat 20 Hz hingga 20,000 Hz, dan julat ini semakin mengecil dengan usia.",
  },
  {
    id: "sci-f2-c10-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Berdasarkan jadual julat pendengaran haiwan, haiwan manakah mempunyai julat pendengaran tertinggi (Hz)?",
    options: ["Anjing (67–45,000)", "Lumba-lumba (40–100,000)", "Kelawar (2,000–110,000)", "Kuda (55–33,500)"],
    answerIndex: 2,
    explanation: "Kelawar mempunyai julat pendengaran tertinggi dengan had atas 110,000 Hz, berbanding lumba-lumba (100,000 Hz), anjing (45,000 Hz) dan kuda (33,500 Hz).",
  },
  {
    id: "sci-f2-c10-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Seorang doktor menggunakan peranti untuk mendengar denyutan jantung pesakit dengan lebih jelas. Apakah peranti yang digunakan dan bagaimana ia berfungsi?",
    options: [
      "Megafon — memperkuatkan suara untuk didengar dari jauh",
      "Stetoskop — membantu doktor mendengar denyutan jantung pesakit dengan menyalurkan dan memperkuatkan bunyi",
      "Alat bantu dengar — memperkuatkan bunyi yang memasuki telinga orang awam",
      "Sonar — mengesan objek bawah air",
    ],
    answerIndex: 1,
    explanation: "Stetoskop adalah peranti yang membantu doktor mendengar denyutan jantung pesakit dengan lebih jelas, mengatasi had pendengaran manusia.",
  },
  {
    id: "sci-f2-c10-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Mengapakah gegaran berulang dapat didengar dalam sebuah gua?",
    options: [
      "Kerana udara dalam gua adalah vakum",
      "Kerana bunyi dipantulkan berulang-ulang antara permukaan keras gua",
      "Kerana gua menghasilkan ultrabunyi secara semula jadi",
      "Kerana frekuensi bunyi berubah menjadi sangat rendah dalam gua",
    ],
    answerIndex: 1,
    explanation: "Gegaran berulang dalam gua disebabkan oleh pantulan bunyi yang berulang-ulang antara permukaan keras gua sebelum sampai ke telinga pendengar.",
  },
  {
    id: "sci-f2-c10-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Seorang jurutera bilik rakaman melapisi dinding dengan bahan penyerap bunyi. Apakah tujuan utama tindakan ini, dan mengapa ia berkesan?",
    options: [
      "Untuk meningkatkan amplitud bunyi supaya rakaman lebih lantang",
      "Untuk mengurangkan gegaran dan menghasilkan rakaman berkualiti tinggi, kerana permukaan lembut dan kasar menyerap bunyi dengan baik",
      "Untuk menukar bunyi kepada ultrabunyi",
      "Untuk meningkatkan frekuensi bunyi yang dirakam",
    ],
    answerIndex: 1,
    explanation: "Bahan penyerap bunyi (lembut dan kasar) mengurangkan pantulan bunyi yang menyebabkan gegaran, menghasilkan rakaman bunyi berkualiti tinggi.",
  },
  {
    id: "sci-f2-c10-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Seorang pemerhati pegun mendengar siren ambulans yang frekuensinya semakin tinggi, kemudian semakin rendah selepas ambulans melepasinya. Apakah penjelasan bagi fenomena ini?",
    options: [
      "Amplitud bunyi siren berubah secara mendadak",
      "Kesan Doppler — frekuensi meningkat semasa ambulans mendekati dan menurun semasa ambulans menjauhi pemerhati",
      "Bunyi siren dipantulkan oleh permukaan jalan",
      "Frekuensi bunyi siren sentiasa malar tetapi telinga pemerhati yang berubah",
    ],
    answerIndex: 1,
    explanation: "Ini adalah contoh klasik kesan Doppler, di mana frekuensi bunyi yang didengar oleh pemerhati pegun berubah akibat pergerakan relatif sumber bunyi (ambulans).",
  },
  {
    id: "sci-f2-c10-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Mengapakah orang yang membawa sumber bunyi (contohnya hon udara) tidak merasakan perubahan kelaraban semasa hon itu bergerak, berbeza dengan pemerhati pegun?",
    options: [
      "Kerana hon udara tidak mengeluarkan sebarang bunyi",
      "Kerana tidak ada pergerakan relatif antara sumber bunyi dan orang yang membawanya, berbeza dengan pemerhati pegun yang mengalami pergerakan relatif terhadap sumber",
      "Kerana telinga orang itu pekak",
      "Kerana hon udara menghasilkan ultrabunyi sahaja",
    ],
    answerIndex: 1,
    explanation: "Kesan Doppler bergantung kepada pergerakan relatif antara sumber bunyi dan pemerhati; orang yang membawa sumber bunyi tidak mengalami pergerakan relatif terhadap sumber itu sendiri.",
  },
  {
    id: "sci-f2-c10-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Kelawar menggunakan ultrabunyi untuk navigasi dalam gelap. Bagaimanakah prinsip ini berkait dengan teknologi sonar yang digunakan manusia?",
    options: [
      "Kedua-duanya menggunakan cahaya untuk mengesan objek",
      "Kedua-duanya menggunakan pantulan gelombang bunyi (ultrabunyi) untuk mengesan kedudukan atau jarak objek",
      "Kedua-duanya tidak berkaitan langsung",
      "Kelawar menggunakan magnet, manakala sonar menggunakan bunyi",
    ],
    answerIndex: 1,
    explanation: "Kedua-dua kelawar (ekolokasi) dan teknologi sonar menggunakan prinsip pantulan gelombang bunyi/ultrabunyi untuk mengesan kedudukan, jarak atau objek di sekeliling.",
  },
  {
    id: "sci-f2-c10-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Seorang pelajar mendakwa 'manusia dapat mendengar semua jenis bunyi termasuk ultrabunyi'. Adakah dakwaan ini tepat? Mengapa?",
    options: [
      "Tepat, kerana telinga manusia sangat sensitif",
      "Tidak tepat, kerana ultrabunyi mempunyai frekuensi lebih daripada 20,000 Hz yang melebihi had pendengaran manusia (20 Hz–20,000 Hz)",
      "Tepat, kerana ultrabunyi hanya digunakan oleh haiwan",
      "Tidak tepat, kerana manusia tidak dapat mendengar sebarang bunyi",
    ],
    answerIndex: 1,
    explanation: "Dakwaan tidak tepat kerana had pendengaran manusia adalah 20 Hz hingga 20,000 Hz, manakala ultrabunyi mempunyai frekuensi lebih daripada 20,000 Hz dan tidak dapat didengar oleh manusia.",
  },
  {
    id: "sci-f2-c10-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Doktor menggunakan ultrabunyi untuk mengimbas keadaan fetus dalam rahim ibu (sonogram). Mengapakah ultrabunyi sesuai digunakan untuk tujuan ini berbanding bunyi biasa?",
    options: [
      "Kerana ultrabunyi mempunyai frekuensi tinggi yang membolehkan pantulan tepat daripada struktur dalaman badan tanpa mendedahkan pesakit kepada bahaya seperti sinar-X",
      "Kerana ultrabunyi lebih lantang daripada bunyi biasa",
      "Kerana ultrabunyi dapat didengar oleh fetus untuk tujuan komunikasi",
      "Kerana ultrabunyi tidak memerlukan medium untuk merebak",
    ],
    answerIndex: 0,
    explanation: "Ultrabunyi digunakan dalam sonogram kerana sifat frekuensi tingginya membolehkan pantulan yang tepat daripada struktur dalaman badan, dengan kaedah yang dianggap lebih selamat berbanding teknik lain.",
  },
  {
    id: "sci-f2-c10-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 10",
    lang: "bm",
    question: "Mengapakah julat pendengaran manusia semakin mengecil dengan usia, dan apakah implikasinya terhadap keperluan alat bantu dengar?",
    options: [
      "Kerana telinga manusia kehilangan kepekaan terhadap frekuensi bunyi tertentu seiring usia, menyebabkan sebahagian orang tua memerlukan alat bantu dengar untuk memperkuatkan bunyi yang memasuki telinga",
      "Kerana manusia tua tidak lagi menghasilkan gelombang bunyi",
      "Kerana udara di sekeliling orang tua menjadi vakum",
      "Kerana amplitud semua bunyi di dunia berkurang dengan masa",
    ],
    answerIndex: 0,
    explanation: "Julat pendengaran manusia mengecil dengan usia kerana kehilangan kepekaan telinga terhadap frekuensi bunyi tertentu; alat bantu dengar membantu memperkuatkan bunyi yang memasuki telinga untuk mengatasi had ini.",
  },
];
