import type { Flashcard } from "@/data/types";

const pairs: Array<{ bm: [string, string]; dlp: [string, string] }> = [
  { bm: ["Apakah sel?", "Sel ialah unit asas bagi semua benda hidup."], dlp: ["What is a cell?", "A cell is the basic unit of all living things."] },
  { bm: ["Apakah organisma unisel?", "Organisma unisel terdiri daripada satu sel sahaja."], dlp: ["What is a unicellular organism?", "A unicellular organism consists of only one cell."] },
  { bm: ["Apakah organisma multisel?", "Organisma multisel terdiri daripada banyak sel."], dlp: ["What is a multicellular organism?", "A multicellular organism consists of many cells."] },
  { bm: ["Berikan contoh organisma unisel.", "Amoeba, Paramecium, yis dan bakteria ialah contoh organisma unisel."], dlp: ["Give examples of unicellular organisms.", "Amoeba, Paramecium, yeast and bacteria are unicellular organisms."] },
  { bm: ["Berikan contoh organisma multisel.", "Manusia, haiwan dan tumbuhan ialah organisma multisel."], dlp: ["Give examples of multicellular organisms.", "Humans, animals and plants are multicellular organisms."] },
  { bm: ["Apakah fungsi membran sel?", "Membran sel mengawal pergerakan bahan masuk dan keluar dari sel."], dlp: ["What is the function of the cell membrane?", "The cell membrane controls the movement of substances into and out of the cell."] },
  { bm: ["Apakah fungsi sitoplasma?", "Sitoplasma ialah tempat kebanyakan tindak balas kimia sel berlaku."], dlp: ["What is the function of cytoplasm?", "Cytoplasm is where most chemical reactions in the cell occur."] },
  { bm: ["Apakah fungsi nukleus?", "Nukleus mengawal semua aktiviti sel dan mengandungi bahan genetik."], dlp: ["What is the function of the nucleus?", "The nucleus controls all cell activities and contains genetic material."] },
  { bm: ["Apakah fungsi mitokondrion?", "Mitokondrion menghasilkan tenaga melalui respirasi sel."], dlp: ["What is the function of a mitochondrion?", "A mitochondrion releases energy through cellular respiration."] },
  { bm: ["Apakah fungsi vakuol dalam sel tumbuhan?", "Vakuol menyimpan sap sel dan membantu mengekalkan kesegahan sel."], dlp: ["What is the function of the vacuole in a plant cell?", "The vacuole stores cell sap and helps maintain cell turgidity."] },
  { bm: ["Apakah fungsi dinding sel?", "Dinding sel menyokong, melindungi dan memberikan bentuk tetap kepada sel tumbuhan."], dlp: ["What is the function of the cell wall?", "The cell wall supports, protects and gives a plant cell a fixed shape."] },
  { bm: ["Apakah fungsi kloroplas?", "Kloroplas mengandungi klorofil dan menjadi tempat fotosintesis."], dlp: ["What is the function of a chloroplast?", "A chloroplast contains chlorophyll and is the site of photosynthesis."] },
  { bm: ["Apakah klorofil?", "Klorofil ialah pigmen hijau yang menyerap tenaga cahaya untuk fotosintesis."], dlp: ["What is chlorophyll?", "Chlorophyll is a green pigment that absorbs light energy for photosynthesis."] },
  { bm: ["Struktur manakah terdapat pada sel tumbuhan tetapi tiada pada sel haiwan?", "Dinding sel, kloroplas dan vakuol besar."], dlp: ["Which structures occur in plant cells but not animal cells?", "A cell wall, chloroplasts and a large vacuole."] },
  { bm: ["Apakah persamaan antara sel haiwan dan sel tumbuhan?", "Kedua-duanya mempunyai membran sel, sitoplasma, nukleus dan mitokondrion."], dlp: ["How are animal and plant cells similar?", "Both have a cell membrane, cytoplasm, nucleus and mitochondria."] },
  { bm: ["Mengapakah sel tumbuhan mempunyai bentuk lebih tetap?", "Sel tumbuhan mempunyai dinding sel yang tegar."], dlp: ["Why does a plant cell have a more fixed shape?", "A plant cell has a rigid cell wall."] },
  { bm: ["Mengapakah sel haiwan tiada kloroplas?", "Haiwan tidak menjalankan fotosintesis untuk menghasilkan makanan."], dlp: ["Why do animal cells lack chloroplasts?", "Animals do not make food by photosynthesis."] },
  { bm: ["Apakah maksud sel khusus?", "Sel khusus ialah sel yang mempunyai struktur tertentu untuk menjalankan fungsi tertentu."], dlp: ["What is a specialised cell?", "A specialised cell has particular structures for a specific function."] },
  { bm: ["Bagaimanakah sel darah merah disesuaikan untuk mengangkut oksigen?", "Sel darah merah berbentuk dwicekung, tiada nukleus dan mengandungi hemoglobin."], dlp: ["How is a red blood cell adapted to transport oxygen?", "It is biconcave, has no nucleus and contains haemoglobin."] },
  { bm: ["Apakah fungsi hemoglobin?", "Hemoglobin mengikat dan mengangkut oksigen."], dlp: ["What is the function of haemoglobin?", "Haemoglobin binds to and transports oxygen."] },
  { bm: ["Bagaimanakah sel saraf disesuaikan dengan fungsinya?", "Sel saraf panjang dan mempunyai cabang untuk menghantar impuls ke seluruh badan."], dlp: ["How is a nerve cell adapted to its function?", "It is long and branched to transmit impulses throughout the body."] },
  { bm: ["Apakah fungsi sel otot?", "Sel otot mengecut dan mengendur untuk menghasilkan pergerakan."], dlp: ["What is the function of a muscle cell?", "A muscle cell contracts and relaxes to produce movement."] },
  { bm: ["Bagaimanakah sel sperma disesuaikan untuk bergerak?", "Sel sperma mempunyai ekor dan banyak mitokondrion untuk membekalkan tenaga."], dlp: ["How is a sperm cell adapted for movement?", "It has a tail and many mitochondria to supply energy."] },
  { bm: ["Apakah fungsi sel telur?", "Sel telur membawa bahan genetik betina dan menyimpan nutrien untuk perkembangan awal."], dlp: ["What is the function of an egg cell?", "It carries female genetic material and stores nutrients for early development."] },
  { bm: ["Bagaimanakah sel rambut akar disesuaikan untuk menyerap air?", "Unjurannya yang panjang memberikan luas permukaan besar untuk penyerapan."], dlp: ["How is a root hair cell adapted to absorb water?", "Its long projection provides a large surface area for absorption."] },
  { bm: ["Apakah fungsi sel pengawal?", "Sel pengawal mengawal pembukaan dan penutupan stoma."], dlp: ["What is the function of guard cells?", "Guard cells control the opening and closing of stomata."] },
  { bm: ["Bagaimanakah sel palisad disesuaikan untuk fotosintesis?", "Sel palisad mempunyai banyak kloroplas untuk menyerap cahaya."], dlp: ["How is a palisade cell adapted for photosynthesis?", "It contains many chloroplasts to absorb light."] },
  { bm: ["Apakah urutan organisasi dalam organisma multisel?", "Sel → tisu → organ → sistem → organisma."], dlp: ["What is the organisation sequence in a multicellular organism?", "Cell → tissue → organ → system → organism."] },
  { bm: ["Apakah tisu?", "Tisu ialah sekumpulan sel serupa yang menjalankan fungsi yang sama."], dlp: ["What is a tissue?", "A tissue is a group of similar cells performing the same function."] },
  { bm: ["Apakah organ?", "Organ ialah beberapa jenis tisu yang bekerjasama menjalankan fungsi tertentu."], dlp: ["What is an organ?", "An organ consists of different tissues working together for a specific function."] },
  { bm: ["Apakah sistem organ?", "Sistem organ ialah beberapa organ yang bekerjasama menjalankan fungsi utama."], dlp: ["What is an organ system?", "An organ system consists of organs working together to perform a major function."] },
  { bm: ["Berikan contoh tisu haiwan.", "Tisu epitelium, tisu otot, tisu saraf dan tisu penghubung."], dlp: ["Give examples of animal tissues.", "Epithelial, muscle, nervous and connective tissues."] },
  { bm: ["Berikan contoh organ manusia.", "Jantung, peparu, perut, ginjal dan otak."], dlp: ["Give examples of human organs.", "The heart, lungs, stomach, kidneys and brain."] },
  { bm: ["Apakah fungsi sistem pencernaan?", "Sistem pencernaan memecahkan makanan dan menyerap nutrien."], dlp: ["What is the function of the digestive system?", "It breaks down food and absorbs nutrients."] },
  { bm: ["Apakah fungsi sistem pernafasan?", "Sistem pernafasan menjalankan pertukaran oksigen dan karbon dioksida."], dlp: ["What is the function of the respiratory system?", "It exchanges oxygen and carbon dioxide."] },
  { bm: ["Apakah fungsi sistem peredaran darah?", "Sistem peredaran darah mengangkut oksigen, nutrien dan bahan buangan."], dlp: ["What is the function of the circulatory system?", "It transports oxygen, nutrients and waste substances."] },
  { bm: ["Apakah fungsi sistem perkumuhan?", "Sistem perkumuhan menyingkirkan bahan buangan metabolik daripada badan."], dlp: ["What is the function of the excretory system?", "It removes metabolic waste from the body."] },
  { bm: ["Apakah fungsi sistem saraf?", "Sistem saraf mengesan rangsangan, memproses maklumat dan menyelaras gerak balas."], dlp: ["What is the function of the nervous system?", "It detects stimuli, processes information and coordinates responses."] },
  { bm: ["Apakah fungsi sistem rangka?", "Sistem rangka menyokong badan, melindungi organ dan membantu pergerakan."], dlp: ["What is the function of the skeletal system?", "It supports the body, protects organs and helps movement."] },
  { bm: ["Apakah fungsi sistem pembiakan?", "Sistem pembiakan menghasilkan gamet dan membolehkan pembiakan."], dlp: ["What is the function of the reproductive system?", "It produces gametes and enables reproduction."] },
  { bm: ["Apakah respirasi sel?", "Respirasi sel ialah proses membebaskan tenaga daripada glukosa."], dlp: ["What is cellular respiration?", "Cellular respiration releases energy from glucose."] },
  { bm: ["Apakah persamaan perkataan respirasi sel?", "Glukosa + oksigen → karbon dioksida + air + tenaga."], dlp: ["What is the word equation for cellular respiration?", "Glucose + oxygen → carbon dioxide + water + energy."] },
  { bm: ["Di manakah respirasi sel berlaku?", "Respirasi sel berlaku terutamanya dalam mitokondrion."], dlp: ["Where does cellular respiration occur?", "It occurs mainly in the mitochondria."] },
  { bm: ["Mengapakah organisma memerlukan tenaga?", "Tenaga diperlukan untuk pertumbuhan, pergerakan, pembiakan dan proses hidup."], dlp: ["Why do organisms need energy?", "Energy is needed for growth, movement, reproduction and life processes."] },
  { bm: ["Apakah fotosintesis?", "Fotosintesis ialah proses tumbuhan hijau menghasilkan glukosa menggunakan cahaya."], dlp: ["What is photosynthesis?", "Photosynthesis is how green plants make glucose using light."] },
  { bm: ["Apakah persamaan perkataan fotosintesis?", "Karbon dioksida + air → glukosa + oksigen, dengan cahaya dan klorofil."], dlp: ["What is the word equation for photosynthesis?", "Carbon dioxide + water → glucose + oxygen, in the presence of light and chlorophyll."] },
  { bm: ["Apakah bahan mentah fotosintesis?", "Karbon dioksida dan air."], dlp: ["What are the raw materials of photosynthesis?", "Carbon dioxide and water."] },
  { bm: ["Apakah syarat fotosintesis?", "Cahaya dan klorofil diperlukan untuk fotosintesis."], dlp: ["What conditions are required for photosynthesis?", "Light and chlorophyll are required."] },
  { bm: ["Apakah hasil fotosintesis?", "Glukosa dan oksigen."], dlp: ["What are the products of photosynthesis?", "Glucose and oxygen."] },
  { bm: ["Bagaimanakah karbon dioksida memasuki daun?", "Karbon dioksida meresap masuk melalui stoma."], dlp: ["How does carbon dioxide enter a leaf?", "It diffuses into the leaf through the stomata."] },
  { bm: ["Bagaimanakah air sampai ke daun?", "Air diserap oleh akar dan diangkut melalui salur xilem."], dlp: ["How does water reach a leaf?", "It is absorbed by roots and transported through xylem vessels."] },
  { bm: ["Apakah nasib glukosa yang dihasilkan tumbuhan?", "Glukosa digunakan untuk tenaga, pertumbuhan atau disimpan sebagai kanji."], dlp: ["What happens to glucose made by plants?", "It is used for energy and growth or stored as starch."] },
  { bm: ["Bagaimanakah menguji kehadiran kanji dalam daun?", "Tambahkan larutan iodin; warna biru kehitaman menunjukkan kanji."], dlp: ["How do you test a leaf for starch?", "Add iodine solution; a blue-black colour indicates starch."] },
  { bm: ["Mengapakah daun dinyahwarnakan sebelum ujian kanji?", "Klorofil disingkirkan supaya perubahan warna iodin jelas dilihat."], dlp: ["Why is a leaf decolourised before the starch test?", "Chlorophyll is removed so the iodine colour change can be seen clearly."] },
  { bm: ["Apakah hubungan fotosintesis dengan respirasi sel?", "Hasil fotosintesis menjadi bahan respirasi, manakala hasil respirasi menjadi bahan fotosintesis."], dlp: ["How are photosynthesis and respiration related?", "The products of photosynthesis are reactants for respiration and vice versa."] },
  { bm: ["Bilakah tumbuhan menjalankan respirasi?", "Tumbuhan menjalankan respirasi sepanjang masa, siang dan malam."], dlp: ["When do plants respire?", "Plants respire continuously, during the day and night."] },
  { bm: ["Bilakah tumbuhan menjalankan fotosintesis?", "Fotosintesis berlaku apabila cahaya mencukupi."], dlp: ["When do plants photosynthesise?", "Photosynthesis occurs when sufficient light is available."] },
  { bm: ["Mengapakah fotosintesis penting kepada haiwan?", "Fotosintesis membekalkan makanan dan oksigen kepada haiwan."], dlp: ["Why is photosynthesis important to animals?", "It supplies animals with food and oxygen."] },
  { bm: ["Bagaimanakah sel bekerjasama dalam organisma multisel?", "Sel khusus membentuk tisu, organ dan sistem yang saling bergantung."], dlp: ["How do cells cooperate in a multicellular organism?", "Specialised cells form interdependent tissues, organs and systems."] },
  { bm: ["Rumuskan kepentingan sel.", "Semua struktur dan proses hidup organisma bergantung pada fungsi sel."], dlp: ["Summarise the importance of cells.", "All structures and life processes of organisms depend on cell function."] },
];

function build(lang: "bm" | "dlp"): Flashcard[] {
  return pairs.map((pair, index) => ({
    id: `sci-f1-c2-${lang}-f${index + 1}`,
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 2",
    lang,
    front: pair[lang][0],
    back: pair[lang][1],
  }));
}

export const scienceF1C2FlashcardsBM = build("bm");
export const scienceF1C2FlashcardsDLP = build("dlp");
