/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as ParentDashboardRouteImport } from './routes/parent-dashboard'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MindmapsRouteImport } from './routes/mindmaps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as CommandCenterPreviewRouteImport } from './routes/command-center-preview'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminContentLibraryRouteImport } from './routes/admin.content-library'
import { Route as AdminCikguIntelRouteImport } from './routes/admin.cikgu-intel'
import { Route as AcademyLandingpage3RouteImport } from './routes/academy/landingpage3'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent-dashboard',
  path: '/parent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MindmapsRoute = MindmapsRouteImport.update({
  id: '/mindmaps',
  path: '/mindmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterPreviewRoute = CommandCenterPreviewRouteImport.update({
  id: '/command-center-preview',
  path: '/command-center-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentLibraryRoute = AdminContentLibraryRouteImport.update({
  id: '/content-library',
  path: '/content-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCikguIntelRoute = AdminCikguIntelRouteImport.update({
  id: '/cikgu-intel',
  path: '/cikgu-intel',
  getParentRoute: () => AdminRoute,
} as any)
const AcademyLandingpage3Route = AcademyLandingpage3RouteImport.update({
  id: '/academy/landingpage3',
  path: '/academy/landingpage3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/command-center-preview': typeof CommandCenterPreviewRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mindmaps': typeof MindmapsRoute
  '/notes': typeof NotesRoute
  '/parent': typeof ParentRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/payment-return': typeof PaymentReturnRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/subjects': typeof SubjectsRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/upgrade': typeof UpgradeRoute
  '/academy/landingpage3': typeof AcademyLandingpage3Route
  '/admin/cikgu-intel': typeof AdminCikguIntelRoute
  '/admin/content-library': typeof AdminContentLibraryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center-preview': typeof CommandCenterPreviewRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mindmaps': typeof MindmapsRoute
  '/notes': typeof NotesRoute
  '/parent': typeof ParentRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/payment-return': typeof PaymentReturnRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/subjects': typeof SubjectsRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/upgrade': typeof UpgradeRoute
  '/academy/landingpage3': typeof AcademyLandingpage3Route
  '/admin/cikgu-intel': typeof AdminCikguIntelRoute
  '/admin/content-library': typeof AdminContentLibraryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/command-center-preview': typeof CommandCenterPreviewRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mindmaps': typeof MindmapsRoute
  '/notes': typeof NotesRoute
  '/parent': typeof ParentRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/payment-return': typeof PaymentReturnRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/subjects': typeof SubjectsRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/upgrade': typeof UpgradeRoute
  '/academy/landingpage3': typeof AcademyLandingpage3Route
  '/admin/cikgu-intel': typeof AdminCikguIntelRoute
  '/admin/content-library': typeof AdminContentLibraryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/command-center-preview'
    | '/companion'
    | '/contact'
    | '/dashboard'
    | '/flashcards'
    | '/home'
    | '/landing'
    | '/leaderboard'
    | '/login'
    | '/mindmaps'
    | '/notes'
    | '/parent'
    | '/parent-dashboard'
    | '/payment-return'
    | '/privacy'
    | '/quizzes'
    | '/subjects'
    | '/terms'
    | '/tracker'
    | '/upgrade'
    | '/academy/landingpage3'
    | '/admin/cikgu-intel'
    | '/admin/content-library'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-center-preview'
    | '/companion'
    | '/contact'
    | '/dashboard'
    | '/flashcards'
    | '/home'
    | '/landing'
    | '/leaderboard'
    | '/login'
    | '/mindmaps'
    | '/notes'
    | '/parent'
    | '/parent-dashboard'
    | '/payment-return'
    | '/privacy'
    | '/quizzes'
    | '/subjects'
    | '/terms'
    | '/tracker'
    | '/upgrade'
    | '/academy/landingpage3'
    | '/admin/cikgu-intel'
    | '/admin/content-library'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/command-center-preview'
    | '/companion'
    | '/contact'
    | '/dashboard'
    | '/flashcards'
    | '/home'
    | '/landing'
    | '/leaderboard'
    | '/login'
    | '/mindmaps'
    | '/notes'
    | '/parent'
    | '/parent-dashboard'
    | '/payment-return'
    | '/privacy'
    | '/quizzes'
    | '/subjects'
    | '/terms'
    | '/tracker'
    | '/upgrade'
    | '/academy/landingpage3'
    | '/admin/cikgu-intel'
    | '/admin/content-library'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommandCenterPreviewRoute: typeof CommandCenterPreviewRoute
  CompanionRoute: typeof CompanionRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HomeRoute: typeof HomeRoute
  LandingRoute: typeof LandingRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MindmapsRoute: typeof MindmapsRoute
  NotesRoute: typeof NotesRoute
  ParentRoute: typeof ParentRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizzesRoute: typeof QuizzesRoute
  SubjectsRoute: typeof SubjectsRoute
  TermsRoute: typeof TermsRoute
  TrackerRoute: typeof TrackerRoute
  UpgradeRoute: typeof UpgradeRoute
  AcademyLandingpage3Route: typeof AcademyLandingpage3Route
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-dashboard': {
      id: '/parent-dashboard'
      path: '/parent-dashboard'
      fullPath: '/parent-dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindmaps': {
      id: '/mindmaps'
      path: '/mindmaps'
      fullPath: '/mindmaps'
      preLoaderRoute: typeof MindmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center-preview': {
      id: '/command-center-preview'
      path: '/command-center-preview'
      fullPath: '/command-center-preview'
      preLoaderRoute: typeof CommandCenterPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-library': {
      id: '/admin/content-library'
      path: '/content-library'
      fullPath: '/admin/content-library'
      preLoaderRoute: typeof AdminContentLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cikgu-intel': {
      id: '/admin/cikgu-intel'
      path: '/cikgu-intel'
      fullPath: '/admin/cikgu-intel'
      preLoaderRoute: typeof AdminCikguIntelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academy/landingpage3': {
      id: '/academy/landingpage3'
      path: '/academy/landingpage3'
      fullPath: '/academy/landingpage3'
      preLoaderRoute: typeof AcademyLandingpage3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCikguIntelRoute: typeof AdminCikguIntelRoute
  AdminContentLibraryRoute: typeof AdminContentLibraryRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCikguIntelRoute: AdminCikguIntelRoute,
  AdminContentLibraryRoute: AdminContentLibraryRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommandCenterPreviewRoute: CommandCenterPreviewRoute,
  CompanionRoute: CompanionRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FlashcardsRoute: FlashcardsRoute,
  HomeRoute: HomeRoute,
  LandingRoute: LandingRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MindmapsRoute: MindmapsRoute,
  NotesRoute: NotesRoute,
  ParentRoute: ParentRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  PrivacyRoute: PrivacyRoute,
  QuizzesRoute: QuizzesRoute,
  SubjectsRoute: SubjectsRoute,
  TermsRoute: TermsRoute,
  TrackerRoute: TrackerRoute,
  UpgradeRoute: UpgradeRoute,
  AcademyLandingpage3Route: AcademyLandingpage3Route,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
