-- GENERATED by scripts/generate-quiz-catalog.ts from the runtime quiz catalog.
-- Scope: active Form 3 Sejarah Chapters 1-3, Sets A/B; metadata only.
-- Exactly six existing active canonical rows must match before updating.
do $$
begin
  if (select count(*) from public.quiz_catalog
      where is_active and subject_id = 'sejarah' and form = 3
        and quiz_key = any (array[
        'quiz-v2:standard:sejarah:form-3:chapter-1:bm:set-a:difficulty-all',
        'quiz-v2:standard:sejarah:form-3:chapter-1:bm:set-b:difficulty-all',
        'quiz-v2:standard:sejarah:form-3:chapter-2:bm:set-a:difficulty-all',
        'quiz-v2:standard:sejarah:form-3:chapter-2:bm:set-b:difficulty-all',
        'quiz-v2:standard:sejarah:form-3:chapter-3:bm:set-a:difficulty-all',
        'quiz-v2:standard:sejarah:form-3:chapter-3:bm:set-b:difficulty-all'
      ]::text[])) <> 6 then
    raise exception 'Expected six active Form 3 Sejarah quiz catalog rows';
  end if;
end $$;

update public.quiz_catalog as catalog
set total_questions = corrected.total_questions,
    easy_count = corrected.easy_count,
    medium_count = corrected.medium_count,
    hard_count = corrected.hard_count,
    timer_bonus_allowed = corrected.timer_bonus_allowed,
    max_xp = corrected.max_xp,
    updated_at = now()
from (values
    ('quiz-v2:standard:sejarah:form-3:chapter-1:bm:set-a:difficulty-all', 25, 0, 25, 0, true, 1025),
    ('quiz-v2:standard:sejarah:form-3:chapter-1:bm:set-b:difficulty-all', 25, 0, 25, 0, true, 1025),
    ('quiz-v2:standard:sejarah:form-3:chapter-2:bm:set-a:difficulty-all', 25, 0, 25, 0, true, 1025),
    ('quiz-v2:standard:sejarah:form-3:chapter-2:bm:set-b:difficulty-all', 25, 0, 25, 0, true, 1025),
    ('quiz-v2:standard:sejarah:form-3:chapter-3:bm:set-a:difficulty-all', 25, 0, 25, 0, true, 1025),
    ('quiz-v2:standard:sejarah:form-3:chapter-3:bm:set-b:difficulty-all', 25, 0, 25, 0, true, 1025)
) as corrected (quiz_key, total_questions, easy_count, medium_count, hard_count, timer_bonus_allowed, max_xp)
where catalog.quiz_key = corrected.quiz_key
  and catalog.is_active
  and catalog.subject_id = 'sejarah'
  and catalog.form = 3;
