import type { QuizQuestion } from "@/data/types";

export const scienceF1C4QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f1-c4-bm-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud pembiakan?",
    options: [
      "Proses menghasilkan individu baharu",
      "Proses menghasilkan tenaga",
      "Proses menyingkirkan bahan kumuh",
      "Proses pernafasan",
    ],
    answerIndex: 0,
    explanation: "Pembiakan ialah proses organisma hidup menghasilkan individu baharu untuk memastikan kelangsungan spesies.",
  },
  {
    id: "sci-f1-c4-bm-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Pernyataan manakah yang betul tentang perbandingan antara pembiakan seks dan pembiakan aseks?",
    options: [
      "Pembiakan seks berlaku tanpa persenyawaan, manakala pembiakan aseks melibatkan percantuman gamet",
      "Pembiakan seks melibatkan percantuman gamet, manakala pembiakan aseks berlaku tanpa persenyawaan",
      "Pembiakan seks menghasilkan anak yang seiras secara genetik, manakala pembiakan aseks menghasilkan variasi genetik",
      "Pembiakan seks menghasilkan anak tanpa gamet, manakala pembiakan aseks menghasilkan anak daripada zigot",
    ],
    answerIndex: 1,
    explanation: "Pembiakan seks melibatkan percantuman gamet jantan dan gamet betina, manakala pembiakan aseks tidak melibatkan persenyawaan.",
  },
  {
    id: "sci-f1-c4-bm-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah gamet?",
    options: ["Sel seks", "Sel darah", "Sel saraf", "Sel tulang"],
    answerIndex: 0,
    explanation: "Gamet ialah sel seks seperti sperma dan ovum.",
  },
  {
    id: "sci-f1-c4-bm-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah pembiakan penting kepada sesuatu spesies?",
    options: [
      "Memastikan setiap individu terus membesar sepanjang hayat",
      "Memastikan kesinambungan dan kemandirian spesies",
      "Memastikan semua individu mempunyai ciri genetik yang sama",
      "Memastikan setiap individu dapat menyesuaikan diri dengan semua perubahan persekitaran",
    ],
    answerIndex: 1,
    explanation: "Pembiakan menghasilkan individu baharu dan memastikan sesuatu spesies dapat terus wujud dari satu generasi ke generasi seterusnya.",
  },
  {
    id: "sci-f1-c4-bm-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Persenyawaan manakah berlaku di dalam badan induk betina?",
    options: ["Persenyawaan dalam", "Persenyawaan luar", "Pendebungaan", "Percambahan"],
    answerIndex: 0,
    explanation: "Persenyawaan dalam berlaku di dalam sistem pembiakan induk betina.",
  },
  {
    id: "sci-f1-c4-bm-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Persenyawaan manakah biasanya berlaku di luar badan, selalunya di dalam air?",
    options: ["Persenyawaan luar", "Persenyawaan dalam", "Penempelan", "Pertunasan"],
    answerIndex: 0,
    explanation: "Persenyawaan luar berlaku di luar badan dan biasa berlaku pada sesetengah haiwan akuatik.",
  },
  {
    id: "sci-f1-c4-bm-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Kaedah pembiakan aseks manakah digunakan oleh Amoeba?",
    options: ["Belahan dedua", "Pertunasan", "Pembentukan spora", "Pembiakan vegetatif"],
    answerIndex: 0,
    explanation: "Amoeba membiak melalui belahan dedua, iaitu satu sel membahagi menjadi dua.",
  },
  {
    id: "sci-f1-c4-bm-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah pertunasan?",
    options: [
      "Individu baharu tumbuh daripada tunas kecil pada induk",
      "Biji benih mula tumbuh",
      "Gamet bercantum",
      "Debunga berpindah ke stigma",
    ],
    answerIndex: 0,
    explanation: "Dalam pertunasan, organisma baharu tumbuh sebagai tunas pada induknya.",
  },
  {
    id: "sci-f1-c4-bm-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Organ pembiakan lelaki manakah menghasilkan sperma?",
    options: ["Testis", "Zakar", "Uretra", "Kelenjar prostat"],
    answerIndex: 0,
    explanation: "Testis menghasilkan sperma dan hormon seks lelaki.",
  },
  {
    id: "sci-f1-c4-bm-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Organ pembiakan perempuan manakah menghasilkan ovum?",
    options: ["Ovari", "Rahim", "Faraj", "Serviks"],
    answerIndex: 0,
    explanation: "Ovari menghasilkan ovum dan hormon seks perempuan.",
  },
  {
    id: "sci-f1-c4-bm-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah akil baligh?",
    options: [
      "Peringkat apabila badan menjadi matang secara seksual",
      "Peringkat apabila badan berhenti membesar sepenuhnya",
      "Sejenis pembiakan aseks",
      "Kaedah pencegahan kehamilan",
    ],
    answerIndex: 0,
    explanation: "Akil baligh ialah peringkat organ pembiakan matang dan ciri seks sekunder mula kelihatan.",
  },
  {
    id: "sci-f1-c4-bm-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Pernyataan manakah yang betul tentang perbandingan antara sperma dan ovum?",
    options: [
      "Sperma mempunyai simpanan nutrien yang banyak, manakala ovum mempunyai ekor untuk bergerak",
      "Sperma mempunyai ekor untuk bergerak, manakala ovum mempunyai simpanan nutrien",
      "Sperma dihasilkan di dalam ovari, manakala ovum dihasilkan di dalam testis",
      "Sperma bersaiz lebih besar daripada ovum, manakala ovum boleh berenang secara aktif",
    ],
    answerIndex: 1,
    explanation: "Sperma mempunyai ekor yang membolehkannya bergerak ke arah ovum, manakala ovum lebih besar dan mempunyai simpanan nutrien.",
  },
  {
    id: "sci-f1-c4-bm-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Hard",
    question: "Kedua-dua tiub Falopio seorang wanita tersumbat. Proses manakah yang paling terjejas?",
    options: [
      "Penghasilan ovum",
      "Persenyawaan antara sperma dengan ovum",
      "Perkembangan fetus di dalam uterus",
      "Penghasilan hormon wanita",
    ],
    answerIndex: 1,
    explanation: "Persenyawaan biasanya berlaku di dalam tiub Falopio. Tiub yang tersumbat boleh menghalang sperma daripada bertemu dengan ovum.",
  },
  {
    id: "sci-f1-c4-bm-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah yang dimaksudkan dengan pendebungaan?",
    options: [
      "Percantuman nukleus gamet jantan dan gamet betina",
      "Pemindahan debunga dari anter ke stigma",
      "Perkembangan ovari menjadi buah",
      "Percambahan biji benih menjadi anak benih",
    ],
    answerIndex: 1,
    explanation: "Pendebungaan ialah proses pemindahan debunga daripada anter ke stigma bunga.",
  },
  {
    id: "sci-f1-c4-bm-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah syarat percambahan biji benih?",
    options: ["Air, oksigen dan suhu yang sesuai", "Cahaya, susu dan tanah sahaja", "Sperma, ovum dan rahim", "Angin, haiwan dan manusia"],
    answerIndex: 0,
    explanation: "Biji benih memerlukan air, oksigen dan suhu yang sesuai untuk bercambah.",
  },
  {
    id: "sci-f1-c4-bm-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah penjanaan semula dalam pembiakan aseks?",
    options: [
      "Organisma baharu tumbuh daripada bahagian badan yang terputus",
      "Satu sel membahagi menjadi dua sel sama",
      "Debunga dipindahkan ke stigma",
      "Embrio melekat pada rahim",
    ],
    answerIndex: 0,
    explanation: "Penjanaan semula membolehkan sesetengah organisma membentuk individu atau bahagian badan baharu daripada cebisan badan.",
  },
  {
    id: "sci-f1-c4-bm-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah spora berguna dalam pembiakan?",
    options: [
      "Spora boleh tumbuh menjadi organisma baharu apabila keadaan sesuai",
      "Spora mengangkut darah dalam badan",
      "Spora melindungi fetus",
      "Spora menghasilkan semen",
    ],
    answerIndex: 0,
    explanation: "Spora ialah unit pembiakan yang boleh berkembang menjadi organisma baharu dalam keadaan sesuai.",
  },
  {
    id: "sci-f1-c4-bm-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Yang manakah contoh pembiakan vegetatif?",
    options: ["Ubi kentang tumbuh menjadi tumbuhan baharu", "Percantuman sperma dan ovum", "Bayi membesar dalam rahim", "Suara menjadi garau"],
    answerIndex: 0,
    explanation: "Ubi kentang boleh tumbuh menjadi tumbuhan baharu melalui pembiakan vegetatif.",
  },
  {
    id: "sci-f1-c4-bm-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah yang berlaku kepada lapisan dinding uterus jika persenyawaan tidak berlaku?",
    options: [
      "Lapisan tersebut kekal tebal sepanjang kitar haid yang berikutnya",
      "Lapisan tersebut luruh dan disingkirkan semasa haid",
      "Lapisan tersebut menipis kerana diserap sepenuhnya oleh uterus",
      "Lapisan tersebut menebal untuk menerima ovum yang tidak disenyawakan",
    ],
    answerIndex: 1,
    explanation: "Jika persenyawaan tidak berlaku, lapisan dinding uterus yang menebal akan luruh dan disingkirkan semasa haid.",
  },
  {
    id: "sci-f1-c4-bm-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah salah satu kelebihan penting susu ibu kepada bayi?",
    options: [
      "Mengandungi nutrien yang sesuai dan antibodi yang membantu melindungi bayi",
      "Mengandungi antibodi yang menggantikan keperluan bayi untuk semua imunisasi",
      "Mengandungi nutrien yang mencukupi sebagai satu-satunya makanan sehingga bayi dewasa",
      "Mengandungi protein tetapi tiada lemak supaya lebih mudah dicernakan oleh bayi",
    ],
    answerIndex: 0,
    explanation: "Susu ibu membekalkan nutrien yang sesuai serta antibodi yang membantu pertumbuhan dan pertahanan badan bayi.",
  },
  {
    id: "sci-f1-c4-bm-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah persenyawaan lebih berkemungkinan berlaku semasa waktu subur dalam kitar haid?",
    options: [
      "Lapisan dinding uterus luruh untuk memudahkan sperma bertemu dengan ovum",
      "Ovum yang matang dibebaskan daripada ovari",
      "Embrio menempel pada lapisan dinding uterus sebelum ovum disenyawakan",
      "Ovum yang matang dibebaskan daripada uterus ke dalam faraj",
    ],
    answerIndex: 1,
    explanation: "Semasa pengovulan, ovum matang dibebaskan daripada ovari. Persenyawaan lebih berkemungkinan berlaku jika terdapat sperma dalam tempoh ini.",
  },
  {
    id: "sci-f1-c4-bm-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah yang berlaku semasa fasa prahaid?",
    options: [
      "Rahim bersedia untuk penempelan",
      "Belahan dedua berlaku",
      "Duktus sperma menghasilkan ovum",
      "Sepal menjadi biji benih",
    ],
    answerIndex: 0,
    explanation: "Semasa fasa prahaid, rahim bersedia sekiranya embrio menempel.",
  },
  {
    id: "sci-f1-c4-bm-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah persenyawaan dalam manusia?",
    options: [
      "Percantuman nukleus sperma dan nukleus ovum",
      "Embrio melekat pada rahim",
      "Darah keluar semasa haid",
      "Debunga dipindahkan ke stigma",
    ],
    answerIndex: 0,
    explanation: "Persenyawaan manusia berlaku apabila nukleus sperma bercantum dengan nukleus ovum.",
  },
  {
    id: "sci-f1-c4-bm-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah penempelan?",
    options: [
      "Embrio melekat pada dinding rahim",
      "Ovum dilepaskan daripada ovari",
      "Debunga bergerak ke stigma",
      "Tunas baharu tumbuh pada induk",
    ],
    answerIndex: 0,
    explanation: "Penempelan ialah proses embrio melekat pada dinding rahim.",
  },
  {
    id: "sci-f1-c4-bm-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Easy",
    question: "Urutan manakah yang betul bagi perkembangan selepas persenyawaan?",
    options: [
      "Embrio → Zigot → Fetus → Bayi",
      "Zigot → Embrio → Fetus → Bayi",
      "Zigot → Fetus → Embrio → Bayi",
      "Fetus → Embrio → Zigot → Bayi",
    ],
    answerIndex: 1,
    explanation: "Selepas persenyawaan, zigot terbentuk dan berkembang menjadi embrio, kemudian fetus dan seterusnya bayi.",
  },
  {
    id: "sci-f1-c4-bm-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Sepasang suami isteri sukar mendapatkan anak kerana bilangan sperma suami terlalu rendah. Apakah tindakan yang paling sesuai?",
    options: [
      "Dapatkan rawatan untuk isteri sahaja kerana kesuburan hanya bergantung pada wanita",
      "Dapatkan pemeriksaan kesihatan dan rawatan daripada pakar perubatan",
      "Ambil ubat kesuburan sendiri tanpa pemeriksaan untuk meningkatkan bilangan sperma",
      "Pilih rawatan kesuburan berdasarkan pengalaman pasangan lain tanpa pemeriksaan",
    ],
    answerIndex: 1,
    explanation: "Masalah kemandulan boleh berpunca daripada lelaki, wanita atau kedua-duanya. Pemeriksaan perubatan membantu mengenal pasti punca dan rawatan yang sesuai.",
  },
  {
    id: "sci-f1-c4-bm-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah fungsi utama plasenta dan tali pusat semasa kehamilan?",
    options: [
      "Membolehkan darah ibu bercampur secara langsung dengan darah fetus untuk mengangkut bahan",
      "Membolehkan oksigen dan nutrien dipindahkan kepada fetus serta bahan kumuh disingkirkan",
      "Membolehkan makanan yang belum dicerna dipindahkan terus dari ibu kepada fetus",
      "Membolehkan fetus menerima oksigen terus daripada udara di luar badan ibu",
    ],
    answerIndex: 1,
    explanation: "Plasenta membolehkan pertukaran bahan antara ibu dengan fetus, manakala tali pusat menghubungkan fetus dengan plasenta.",
  },
  {
    id: "sci-f1-c4-bm-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah wanita hamil perlu mengelakkan rokok, alkohol dan dadah yang berbahaya?",
    options: [
      "Bahan berbahaya hanya menjejaskan fetus selepas bayi dilahirkan",
      "Bahan berbahaya boleh menjejaskan pertumbuhan dan perkembangan fetus",
      "Bahan berbahaya hanya menjejaskan fetus jika darah ibu bercampur terus dengan darah fetus",
      "Bahan berbahaya hanya menjejaskan fetus jika ibu turut mengalami gejala keracunan",
    ],
    answerIndex: 1,
    explanation: "Bahan berbahaya boleh memasuki badan fetus dan mengganggu pertumbuhan serta perkembangannya.",
  },
  {
    id: "sci-f1-c4-bm-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Mengapakah pendebungaan kacuk boleh memberikan manfaat dalam bidang pertanian?",
    options: [
      "Boleh memastikan semua anak seiras secara genetik dengan satu induk",
      "Boleh menggabungkan ciri-ciri yang baik daripada tumbuhan yang berbeza",
      "Boleh memastikan setiap anak mewarisi semua ciri baik daripada kedua-dua induk",
      "Boleh menghasilkan biji benih tanpa percantuman gamet jantan dan gamet betina",
    ],
    answerIndex: 1,
    explanation: "Pendebungaan kacuk boleh menghasilkan anak yang mempunyai gabungan ciri-ciri baik daripada induk yang berbeza.",
  },
  {
    id: "sci-f1-c4-bm-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 4",
    lang: "bm",
    difficulty: "Medium",
    question: "Selepas persenyawaan berlaku pada tumbuhan berbunga, perubahan manakah yang betul?",
    options: [
      "Ovul berkembang menjadi biji benih dan ovari berkembang menjadi buah",
      "Ovul berkembang menjadi buah dan ovari berkembang menjadi biji benih",
      "Ovul berkembang menjadi biji benih dan stigma berkembang menjadi buah",
      "Anter berkembang menjadi biji benih dan ovari berkembang menjadi buah",
    ],
    answerIndex: 0,
    explanation: "Selepas persenyawaan, ovul berkembang menjadi biji benih manakala ovari berkembang menjadi buah.",
  },
];
