import type { QuizQuestion } from "@/data/types";

export const scienceF1C8QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f1-c8-bm-q1",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah maksud cahaya?",
    options: ["Satu bentuk tenaga", "Satu jenis bunyi", "Satu jenis jirim", "Satu jenis gas"],
    answerIndex: 0,
    explanation: "Cahaya ialah satu bentuk tenaga yang membolehkan kita melihat objek.",
  },
  {
    id: "sci-f1-c8-bm-q2",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Bagaimanakah cahaya bergerak?",
    options: ["Dalam garis lurus", "Dalam bulatan sahaja", "Secara beralun perlahan", "Mengikut arah angin"],
    answerIndex: 0,
    explanation: "Cahaya bergerak dalam garis lurus.",
  },
  {
    id: "sci-f1-c8-bm-q3",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Berapakah kelajuan cahaya?",
    options: ["3.0 x 10^8 m/s", "300 m/s", "3.0 x 10^3 m/s", "30 m/s"],
    answerIndex: 0,
    explanation: "Kelajuan cahaya ialah kira-kira 3.0 x 10^8 meter sesaat.",
  },
  {
    id: "sci-f1-c8-bm-q4",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Bilakah bayang-bayang terbentuk?",
    options: ["Apabila cahaya dihalang oleh objek legap", "Apabila cahaya melalui kaca jernih", "Apabila bunyi dipantulkan", "Apabila air mendidih"],
    answerIndex: 0,
    explanation: "Bayang-bayang terbentuk apabila cahaya dihalang oleh objek legap.",
  },
  {
    id: "sci-f1-c8-bm-q5",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Pada waktu bilakah bayang-bayang biasanya paling pendek?",
    options: ["Tengah hari", "Awal pagi", "Lewat petang", "Tengah malam"],
    answerIndex: 0,
    explanation: "Bayang-bayang paling pendek pada waktu tengah hari kerana Matahari berada tinggi di langit.",
  },
  {
    id: "sci-f1-c8-bm-q6",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah perbezaan utama antara imej sahih dengan imej maya?",
    options: [
      "Imej sahih boleh terbentuk pada skrin, manakala imej maya tidak boleh terbentuk pada skrin",
      "Imej sahih tidak boleh terbentuk pada skrin, manakala imej maya boleh terbentuk pada skrin",
      "Imej sahih dan imej maya kedua-duanya boleh terbentuk pada skrin",
      "Imej sahih dan imej maya kedua-duanya tidak boleh terbentuk pada skrin",
    ],
    answerIndex: 0,
    explanation: "Imej sahih boleh diproyeksikan pada skrin, manakala imej maya tidak dapat terbentuk pada skrin.",
  },
  {
    id: "sci-f1-c8-bm-q7",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah yang terhasil apabila cahaya merah, hijau dan biru dengan keamatan yang sesuai ditambahkan bersama?",
    options: [
      "Cahaya putih",
      "Cahaya biru sahaja",
      "Cahaya magenta sahaja",
      "Cahaya kuning sahaja",
    ],
    answerIndex: 0,
    explanation: "Merah, hijau dan biru ialah warna primer cahaya. Apabila ketiga-tiganya ditambahkan pada keamatan yang sesuai, cahaya putih terhasil.",
  },
  {
    id: "sci-f1-c8-bm-q8",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Seorang murid berdiri 2 m di hadapan sebuah cermin satah. Berapakah jarak imej murid itu di belakang cermin?",
    options: [
      "1 m",
      "2 m",
      "4 m",
      "6 m",
    ],
    answerIndex: 1,
    explanation: "Bagi cermin satah, jarak imej dari cermin adalah sama dengan jarak objek dari cermin.",
  },
  {
    id: "sci-f1-c8-bm-q9",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah ciri imej dalam cermin satah?",
    options: ["Tegak dan maya", "Sentiasa lebih kecil", "Boleh terbentuk pada skrin", "Sentiasa berwarna merah"],
    answerIndex: 0,
    explanation: "Cermin satah menghasilkan imej tegak, maya, songsang sisi dan sama saiz dengan objek.",
  },
  {
    id: "sci-f1-c8-bm-q10",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah cermin cekung sesuai digunakan sebagai cermin solek apabila muka berada dekat dengan cermin?",
    options: [
      "Ia boleh menghasilkan imej maya yang diperbesar",
      "Ia boleh menghasilkan imej sahih yang tegak dan lebih kecil",
      "Ia boleh menghasilkan imej maya yang sentiasa sama saiz dengan muka",
      "Ia boleh menghasilkan imej sahih yang songsang untuk memudahkan solekan",
    ],
    answerIndex: 0,
    explanation: "Pada kedudukan objek yang sesuai, cermin cekung menghasilkan imej maya yang tegak dan diperbesar.",
  },
  {
    id: "sci-f1-c8-bm-q11",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah cermin cembung digunakan sebagai cermin sisi kenderaan?",
    options: [
      "Menghasilkan medan pandangan yang lebih luas",
      "Menghasilkan imej diperbesar supaya jarak objek dapat diukur secara langsung",
      "Menumpukan cahaya untuk menghasilkan imej sahih di hadapan cermin",
      "Menghasilkan imej sama saiz supaya seluruh kawasan belakang dapat dilihat",
    ],
    answerIndex: 0,
    explanation: "Cermin cembung memberikan medan pandangan yang lebih luas, membolehkan pemandu melihat kawasan yang lebih besar di belakang dan sisi kenderaan.",
  },
  {
    id: "sci-f1-c8-bm-q12",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah jalur pemantul cahaya dipasang pada jaket keselamatan pekerja jalan raya?",
    options: [
      "Untuk memantulkan cahaya supaya pekerja lebih mudah dilihat pada waktu gelap",
      "Untuk menyerap cahaya supaya jaket kelihatan lebih terang tanpa memantulkannya",
      "Untuk membiaskan cahaya ke dalam fabrik supaya pekerja kelihatan lebih besar",
      "Untuk menyebarkan cahaya kepada spektrum warna supaya jaket menghasilkan cahaya sendiri",
    ],
    answerIndex: 0,
    explanation: "Jalur tersebut memantulkan cahaya daripada lampu kenderaan dan membantu meningkatkan keterlihatan pekerja.",
  },
  {
    id: "sci-f1-c8-bm-q13",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah formula hukum pantulan?",
    options: ["i = r", "v = u", "F = ma", "d = m/V"],
    answerIndex: 0,
    explanation: "Dalam hukum pantulan, sudut tuju sama dengan sudut pantulan, iaitu i = r.",
  },
  {
    id: "sci-f1-c8-bm-q14",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Mengapakah penyedut minuman kelihatan bengkok apabila sebahagiannya berada di dalam air?",
    options: [
      "Cahaya dibiaskan apabila bergerak antara air dengan udara",
      "Cahaya dipantulkan sepenuhnya pada permukaan air sebelum sampai ke mata",
      "Cahaya disebarkan kepada spektrum warna apabila keluar daripada air",
      "Cahaya diserakkan oleh zarah udara sehingga bentuk penyedut berubah",
    ],
    answerIndex: 0,
    explanation: "Cahaya berubah arah apabila bergerak antara medium yang mempunyai ketumpatan optik berbeza.",
  },
  {
    id: "sci-f1-c8-bm-q15",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Easy",
    question: "Apakah yang berlaku apabila cahaya putih melalui sebuah prisma?",
    options: [
      "Cahaya putih dipisahkan kepada spektrum warna",
      "Cahaya putih dipantulkan semula sebagai satu warna sahaja",
      "Cahaya putih dibiaskan tetapi semua warna melalui laluan yang sama",
      "Cahaya putih diserap sepenuhnya sehingga tiada cahaya keluar",
    ],
    answerIndex: 0,
    explanation: "Prisma menyebabkan cahaya putih tersebar kepada warna-warna komponennya kerana setiap warna dibiaskan pada kadar yang berbeza.",
  },
  {
    id: "sci-f1-c8-bm-q16",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah yang dimaksudkan dengan imej songsang sisi?",
    options: ["Bahagian kiri dan kanan imej tertukar", "Imej menjadi lebih panas", "Imej menjadi lebih berat", "Imej hilang warna"],
    answerIndex: 0,
    explanation: "Songsang sisi bermaksud bahagian kiri dan kanan imej kelihatan tertukar.",
  },
  {
    id: "sci-f1-c8-bm-q17",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Jika sudut tuju ialah 35°, berapakah sudut pantulan?",
    options: ["35°", "45°", "70°", "90°"],
    answerIndex: 0,
    explanation: "Menurut hukum pantulan, sudut tuju sama dengan sudut pantulan.",
  },
  {
    id: "sci-f1-c8-bm-q18",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah fungsi garis normal dalam pantulan cahaya?",
    options: ["Garis rujukan untuk mengukur sudut tuju dan sudut pantulan", "Garis yang menghasilkan warna", "Garis yang menghalang cahaya", "Garis yang menyerap semua cahaya"],
    answerIndex: 0,
    explanation: "Garis normal digunakan sebagai rujukan untuk mengukur sudut tuju dan sudut pantulan.",
  },
  {
    id: "sci-f1-c8-bm-q19",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Apabila cahaya bergerak secara serong dari udara ke dalam kaca, apakah yang berlaku kepada sinar cahaya yang memasuki kaca?",
    options: [
      "Terbias mendekati garis normal",
      "Terbias menjauhi garis normal",
      "Tidak berubah arah dalam semua keadaan",
      "Dipantulkan sepenuhnya tanpa memasuki kaca",
    ],
    answerIndex: 0,
    explanation: "Apabila cahaya memasuki medium yang lebih tumpat secara optik secara serong, kelajuannya berkurang dan sinar dibiaskan mendekati garis normal.",
  },
  {
    id: "sci-f1-c8-bm-q20",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Apabila sinar cahaya melalui air ke udara secara serong dan keluar ke udara, bagaimanakah arah sinar itu berubah?",
    options: [
      "Sinar terbias menjauhi garis normal",
      "Sinar terbias mendekati garis normal",
      "Sinar terus bergerak sepanjang garis normal",
      "Sinar keluar sepanjang permukaan air dalam semua keadaan",
    ],
    answerIndex: 0,
    explanation: "Bagi sinar yang keluar secara serong dari air ke udara, cahaya bergerak dari medium lebih tumpat secara optik ke medium kurang tumpat secara optik lalu terbias menjauhi garis normal.",
  },
  {
    id: "sci-f1-c8-bm-q21",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Sinar cahaya memasuki kaca dari udara. Dalam keadaan manakah arah sinar tidak berubah walaupun kelajuannya berubah?",
    options: [
      "Sinar masuk sepanjang garis normal",
      "Sinar masuk pada sudut 30 darjah terhadap garis normal",
      "Sinar masuk pada sudut 45 darjah terhadap garis normal",
      "Sinar masuk pada sudut 60 darjah terhadap garis normal",
    ],
    answerIndex: 0,
    explanation: "Apabila cahaya memasuki kaca sepanjang garis normal, arah pergerakannya tidak berubah walaupun kelajuannya berkurang.",
  },
  {
    id: "sci-f1-c8-bm-q22",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah turutan warna spektrum yang betul?",
    options: ["Merah, jingga, kuning, hijau, biru, indigo, ungu", "Biru, merah, hijau, ungu, kuning, jingga, indigo", "Hitam, putih, merah, biru, hijau, ungu, jingga", "Merah, biru, kuning, hitam, putih, indigo, ungu"],
    answerIndex: 0,
    explanation: "Spektrum cahaya terdiri daripada merah, jingga, kuning, hijau, biru, indigo dan ungu.",
  },
  {
    id: "sci-f1-c8-bm-q23",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Warna cahaya manakah paling kurang dibiaskan?",
    options: ["Merah", "Ungu", "Biru", "Indigo"],
    answerIndex: 0,
    explanation: "Cahaya merah dibiaskan paling sedikit dalam penyebaran cahaya.",
  },
  {
    id: "sci-f1-c8-bm-q24",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah hasil gabungan cahaya merah dan hijau?",
    options: ["Kuning", "Magenta", "Sian", "Hitam"],
    answerIndex: 0,
    explanation: "Dalam penambahan cahaya, merah + hijau menghasilkan kuning.",
  },
  {
    id: "sci-f1-c8-bm-q25",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Medium",
    question: "Apakah fungsi dua cermin satah dalam periskop?",
    options: ["Memantulkan cahaya supaya objek di luar pandangan boleh dilihat", "Menyebarkan cahaya kepada tujuh warna", "Menyerap semua cahaya", "Menghasilkan haba"],
    answerIndex: 0,
    explanation: "Periskop menggunakan dua cermin satah untuk memantulkan cahaya ke mata pemerhati.",
  },
  {
    id: "sci-f1-c8-bm-q26",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah kilat dilihat sebelum guruh didengar?",
    options: ["Cahaya bergerak lebih laju daripada bunyi", "Bunyi bergerak lebih laju daripada cahaya", "Kilat tidak menghasilkan bunyi", "Guruh berlaku sebelum kilat"],
    answerIndex: 0,
    explanation: "Cahaya daripada kilat sampai ke mata lebih cepat kerana cahaya bergerak lebih laju daripada bunyi.",
  },
  {
    id: "sci-f1-c8-bm-q27",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah kolam renang kelihatan lebih cetek daripada keadaan sebenar?",
    options: ["Cahaya terbias apabila bergerak dari air ke udara", "Air memantulkan semua bunyi", "Dasar kolam naik ke atas", "Air menyerap semua cahaya"],
    answerIndex: 0,
    explanation: "Pembiasan cahaya dari air ke udara menyebabkan dasar kolam kelihatan lebih dekat dengan permukaan.",
  },
  {
    id: "sci-f1-c8-bm-q28",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Hard",
    question: "Fenomena manakah paling berkaitan dengan penyebaran cahaya?",
    options: [
      "Pembentukan pelangi",
      "Pembentukan imej dalam cermin satah",
      "Penyedut minuman kelihatan bengkok dalam air",
      "Langit kelihatan biru pada waktu siang",
    ],
    answerIndex: 0,
    explanation: "Pelangi terbentuk apabila cahaya putih Matahari mengalami proses termasuk pembiasan dan penyebaran oleh titisan air.",
  },
  {
    id: "sci-f1-c8-bm-q29",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah langit biasanya kelihatan biru pada waktu siang?",
    options: [
      "Cahaya biru diserakkan dengan lebih banyak oleh zarah dalam atmosfera",
      "Cahaya biru dipantulkan oleh laut lalu memberikan warna kepada seluruh langit",
      "Cahaya biru disebarkan daripada cahaya putih oleh atmosfera seperti prisma",
      "Cahaya merah diserakkan lebih banyak lalu seluruh langit kelihatan biru",
    ],
    answerIndex: 0,
    explanation: "Cahaya dengan panjang gelombang yang lebih pendek seperti biru lebih banyak diserakkan dalam atmosfera.",
  },
  {
    id: "sci-f1-c8-bm-q30",
    subjectId: "science",
    form: "Form 1",
    chapter: "Chapter 8",
    lang: "bm",
    difficulty: "Hard",
    question: "Mengapakah objek hitam terasa lebih panas di bawah cahaya matahari?",
    options: ["Objek hitam menyerap semua warna cahaya", "Objek hitam memantulkan semua warna", "Objek hitam menghasilkan cahaya sendiri", "Objek hitam tidak menyerap tenaga"],
    answerIndex: 0,
    explanation: "Objek hitam menyerap kebanyakan cahaya dan tenaga haba, maka terasa lebih panas.",
  },
];
