import type { Flashcard } from "@/data/content";

export const scienceF2C12FlashcardsDLP: Flashcard[] = [
  // Set 1: Planets of the Solar System
  {
    id: "sci-f2-c12-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Name the eight planets in the solar system in order from the Sun.",
    back: "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
  },
  {
    id: "sci-f2-c12-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which planets are the inner planets, and what do they have in common?",
    back: "Mercury, Venus, Earth and Mars — small planets with rocky surfaces.",
  },
  {
    id: "sci-f2-c12-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which planet is farthest from the Sun?",
    back: "Neptune.",
  },
  {
    id: "sci-f2-c12-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Since which year has Pluto no longer been recognised as a planet?",
    back: "Since 2006; Pluto is now known as a dwarf planet.",
  },
  {
    id: "sci-f2-c12-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which planet is closest to the Sun?",
    back: "Mercury, approximately 57.9 million km from the Sun.",
  },
  {
    id: "sci-f2-c12-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which is the largest planet in the solar system?",
    back: "Jupiter, with a mass almost 320 times that of Earth.",
  },
  {
    id: "sci-f2-c12-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: 'What are "giant gas" planets?',
    back: "Jupiter, Saturn, Uranus and Neptune — their surfaces are covered in gas and they receive very little sunlight.",
  },
  {
    id: "sci-f2-c12-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: 'Why is Mars known as the "Red Planet"?',
    back: "Due to its reddish surface colour; it also has two moons, Phobos and Deimos.",
  },
  {
    id: "sci-f2-c12-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: 'Why is Venus called the "greenhouse" planet?',
    back: "Its high carbon dioxide content traps heat, causing temperatures to reach up to 460°C.",
  },
  {
    id: "sci-f2-c12-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is unique about Venus's direction of rotation?",
    back: "Rotates from east to west (opposite of Earth) — the Sun rises in the west on Venus.",
  },
  {
    id: "sci-f2-c12-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which planet is often seen as the bright 'morning star' or 'evening star'?",
    back: "Venus.",
  },
  {
    id: "sci-f2-c12-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is Saturn's largest moon, and what is special about it?",
    back: "Titan, which is bigger than the planet Mercury. (Saturn has many moons, and more are still being discovered.)",
  },
  {
    id: "sci-f2-c12-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is unique about Uranus's axis of rotation?",
    back: "Almost parallel to its orbit around the Sun, making it appear to rotate on its side.",
  },
  {
    id: "sci-f2-c12-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How long does Neptune take to orbit the Sun?",
    back: "Almost 165 years.",
  },
  {
    id: "sci-f2-c12-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which natural satellite of Jupiter is believed to have seawater beneath its ice?",
    back: "Europa.",
  },
  {
    id: "sci-f2-c12-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare Saturn's ring system with Uranus's.",
    back: "Saturn's rings are mostly ice; Uranus's rings are thinner and darker than Saturn's.",
  },
  {
    id: "sci-f2-c12-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: 'Why is Jupiter considered the "protector of the Earth"?',
    back: "Its strong gravity can pull in or deflect some comets and asteroids, so it is often described as a 'protector' of the inner planets.",
  },
  {
    id: "sci-f2-c12-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why does Europa interest scientists in the search for life beyond Earth?",
    back: "It is believed to have seawater beneath its icy surface, and water is a basic requirement for life.",
  },
  {
    id: "sci-f2-c12-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the mass and surface area of Mars with Earth.",
    back: "Mars's surface area is only 25% of Earth's; its mass is 10% of Earth's.",
  },
  {
    id: "sci-f2-c12-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which two planets have no moons?",
    back: "Mercury and Venus.",
  },
  // Set 2: Distance, Gravity, Temperature & Orbit
  {
    id: "sci-f2-c12-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is an Astronomical Unit (A.U.)?",
    back: "The average distance between the Earth and the Sun, approximately 150 million km. 1 A.U. = 1.5 × 10⁸ km.",
  },
  {
    id: "sci-f2-c12-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is a light year (ly)?",
    back: "The distance travelled by light in one year. 1 ly = 9.5 × 10¹² km.",
  },
  {
    id: "sci-f2-c12-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is the velocity of light?",
    back: "300 000 km every second.",
  },
  {
    id: "sci-f2-c12-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Calculate Earth's distance (1.5 × 10⁸ km) from the Sun in A.U.",
    back: "(1.5 × 10⁸)/(1.5 × 10⁸) = 1.0 A.U.",
  },
  {
    id: "sci-f2-c12-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Calculate Earth's distance (1.5 × 10⁸ km) from the Sun in light years (ly).",
    back: "(1.5 × 10⁸)/(9.5 × 10¹²) = 1.58 × 10⁻⁵ ly.",
  },
  {
    id: "sci-f2-c12-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Calculate Saturn's distance (1.43 × 10⁹ km) in A.U.",
    back: "(1.43 × 10⁹)/(1.5 × 10⁸) = 9.5 A.U.",
  },
  {
    id: "sci-f2-c12-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "A planet's distance from the Sun is 3 × 10⁹ km. What is its distance in A.U.?",
    back: "(3 × 10⁹)/(1.5 × 10⁸) = 20 A.U.",
  },
  {
    id: "sci-f2-c12-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is the value of Earth's surface gravity?",
    back: "9.8 m s⁻².",
  },
  {
    id: "sci-f2-c12-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the gravity of Mercury and Mars with Earth.",
    back: "Both are lower than Earth's because of their lower mass.",
  },
  {
    id: "sci-f2-c12-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare Venus's gravity with Earth's.",
    back: "Almost the same, because Venus's mass is almost the same as Earth's.",
  },
  {
    id: "sci-f2-c12-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Jupiter's gravity higher than Earth's even though its density is low?",
    back: "Because Jupiter's mass is extremely high (almost 320 times Earth), outweighing the effect of low density.",
  },
  {
    id: "sci-f2-c12-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How does Saturn's gravitational attraction compare with Earth's?",
    back: "Although Saturn is a very large planet, its gravitational attraction is not much higher than Earth's. Saturn's gravitational acceleration is 10.44 m s⁻² compared with Earth's 9.8 m s⁻², because gas giants have low density.",
  },
  {
    id: "sci-f2-c12-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front:
      "Why is Jupiter's surface gravity stronger than Earth's even though Jupiter's density is low?",
    back: "Surface gravity depends mainly on a planet's mass and size; Jupiter's mass is so large (about 320 times Earth's) that its gravity is stronger.",
  },
  {
    id: "sci-f2-c12-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the orbit time of Mercury with Neptune.",
    back: "Mercury (closest): 88 days. Neptune (furthest): 164.8 years — the further a planet, the longer its orbit time.",
  },
  {
    id: "sci-f2-c12-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the surface temperature of Mercury's sunlit side with its dark side.",
    back: "Sunlit side: >427°C. Dark side: can drop to −173°C — due to the lack of an atmosphere.",
  },
  {
    id: "sci-f2-c12-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the greenhouse effect on Venus with Earth.",
    back: "Venus: a thick carbon dioxide atmosphere traps heat, raising temperatures to about 460°C. Earth: a thinner atmosphere gives a moderate greenhouse effect and temperatures suitable for life.",
  },
  {
    id: "sci-f2-c12-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Venus hotter than Mercury even though Mercury is closer to the Sun?",
    back: "Venus's thick CO₂ atmosphere traps heat (greenhouse effect), unlike Mercury which has no atmosphere to trap heat.",
  },
  {
    id: "sci-f2-c12-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare Mars's surface pressure with Earth's.",
    back: "Mars's surface pressure is less than 1/100 of Earth's — minimal effect on surface temperature (−143°C to 35°C).",
  },
  {
    id: "sci-f2-c12-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front:
      "What is the general relationship between a planet's distance from the Sun and its surface temperature?",
    back: "Theoretically closer = hotter, but the actual situation also depends on atmosphere, density and surface composition.",
  },
  {
    id: "sci-f2-c12-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why do giant gas planets have extremely low surface temperatures?",
    back: "Their surfaces are covered in gas and receive very little sunlight due to their great distance from the Sun.",
  },
  // Set 3: Earth, Moon & Ecological Footprint
  {
    id: "sci-f2-c12-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What percentage of Earth's surface is water and land?",
    back: "More than 71% water, 29% land.",
  },
  {
    id: "sci-f2-c12-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Earth described as a unique planet?",
    back: "It is the only planet known to support life, with liquid water, oxygen and a suitable temperature range.",
  },
  {
    id: "sci-f2-c12-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "List the factors that make Earth suitable for living things.",
    back: "Plenty of water, high oxygen content, suitable gravity, sunlight for photosynthesis, suitable temperature range, atmosphere protecting against UV.",
  },
  {
    id: "sci-f2-c12-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Earth's atmosphere important for life?",
    back: "It protects the surface from solar wind, harmful ultraviolet rays and radiation.",
  },
  {
    id: "sci-f2-c12-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Earth's distance from the Sun suitable for life?",
    back: "It gives a temperature range that keeps most water in liquid form — not too hot and not too cold.",
  },
  {
    id: "sci-f2-c12-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is Earth's natural satellite?",
    back: "The Moon — the only natural satellite of the Earth.",
  },
  {
    id: "sci-f2-c12-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Where does the light from the Moon come from?",
    back: "The Moon reflects sunlight; it does not produce its own light.",
  },
  {
    id: "sci-f2-c12-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why does the Moon have so many craters?",
    back: "It has almost no atmosphere to burn up meteoroids, so they strike its surface.",
  },
  {
    id: "sci-f2-c12-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why does the same side of the Moon always face the Earth?",
    back: "Because the time for the Moon to rotate on its axis and orbit Earth is about the same, 27 days.",
  },
  {
    id: "sci-f2-c12-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How does the Moon affect the Earth's oceans?",
    back: "Its gravitational pull causes the tides.",
  },
  {
    id: "sci-f2-c12-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How large is Earth compared with the Moon?",
    back: "Earth's diameter is about four times that of the Moon.",
  },
  {
    id: "sci-f2-c12-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What would happen if Earth's rotation slowed down or stopped?",
    back: "Longer day/night durations, more deserts, changes in tides, temperature drops in dark areas.",
  },
  {
    id: "sci-f2-c12-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How can a scientist determine whether a planet is suitable for life?",
    back: "Check for the presence of water, oxygen, a moderate temperature range, suitable gravity, a protective atmosphere and sunlight.",
  },
  {
    id: "sci-f2-c12-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is ecological footprint, and which six areas is it measured from?",
    back: "A measure of the area of productive land and water needed to supply the resources people use and to absorb their wastes. The six areas are carbon footprint, built-up land, forests, cropland, grazing land and fishing grounds.",
  },
  {
    id: "sci-f2-c12-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is the difference between ecological footprint and biocapacity?",
    back: "Ecological footprint is human demand on nature; biocapacity is the ability of land and water to regenerate resources and absorb wastes.",
  },
  {
    id: "sci-f2-c12-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How many areas are used to measure ecological footprint?",
    back: "Six areas: carbon footprint, built-up land, forest, cropland, grazing land and fishing grounds.",
  },
  {
    id: "sci-f2-c12-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which two food-production areas are listed separately in the Ecological Footprint?",
    back: "Cropland and grazing land.",
  },
  {
    id: "sci-f2-c12-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What happens if humanity's ecological footprint exceeds Earth's biocapacity?",
    back: "Earth will be depleted of resources because the rate of consumption exceeds the rate of regeneration.",
  },
  {
    id: "sci-f2-c12-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is a carbon footprint?",
    back: "The amount of carbon dioxide released by a person's activities, such as using fuel and electricity.",
  },
  {
    id: "sci-f2-c12-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How can individuals reduce their ecological footprint?",
    back: "Save energy and water, reduce waste through the 5R, and use public transport.",
  },
];
