import type { Flashcard } from "@/data/content";

export const scienceF2C12FlashcardsDLP: Flashcard[] = [
  // Deck 1: Basics (Cards 1-20)
  {
    id: "sci-f2-c12-dlp-f1",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is an Astronomical Unit (A.U.)?",
    back: "The average distance between the Earth and the Sun, approximately 150 million km. 1 A.U. = 1.5 × 10⁸ km.",
  },
  {
    id: "sci-f2-c12-dlp-f2",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is a light year (ly)?",
    back: "The distance travelled by light in one year. 1 ly = 9.5 × 10¹² km.",
  },
  {
    id: "sci-f2-c12-dlp-f3",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is the velocity of light?",
    back: "300,000 km per second.",
  },
  {
    id: "sci-f2-c12-dlp-f4",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Name the eight planets in the solar system in order from the Sun.",
    back: "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
  },
  {
    id: "sci-f2-c12-dlp-f5",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Since which year has Pluto no longer been recognised as a planet?",
    back: "Since 2006; Pluto is now known as a dwarf planet.",
  },
  {
    id: "sci-f2-c12-dlp-f6",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which planet is closest to the Sun?",
    back: "Mercury, approximately 57.9 million km from the Sun.",
  },
  {
    id: "sci-f2-c12-dlp-f7",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which is the largest planet in the solar system?",
    back: "Jupiter, with a mass almost 320 times that of Earth.",
  },
  {
    id: "sci-f2-c12-dlp-f8",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Mars known as the \"Red Planet\"?",
    back: "Due to its reddish surface colour; it also has two moons, Phobos and Demos.",
  },
  {
    id: "sci-f2-c12-dlp-f9",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What percentage of Earth's surface is water and land?",
    back: "More than 71% water, 29% land.",
  },
  {
    id: "sci-f2-c12-dlp-f10",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is Earth's natural satellite?",
    back: "The Moon — the only natural satellite of the Earth.",
  },
  {
    id: "sci-f2-c12-dlp-f11",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Venus called the \"greenhouse\" planet?",
    back: "Its high carbon dioxide content traps heat, causing temperatures to reach up to 460°C.",
  },
  {
    id: "sci-f2-c12-dlp-f12",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is unique about Venus's direction of rotation?",
    back: "Rotates from east to west (opposite of Earth) — the Sun rises in the west on Venus.",
  },
  {
    id: "sci-f2-c12-dlp-f13",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How many moons does Saturn have, and what is its biggest moon?",
    back: "62 moons; its biggest moon, Titan, is bigger than Mercury.",
  },
  {
    id: "sci-f2-c12-dlp-f14",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is unique about Uranus's axis of rotation?",
    back: "Almost parallel to its orbit around the Sun, making it appear to rotate on its side.",
  },
  {
    id: "sci-f2-c12-dlp-f15",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How long does Neptune take to orbit the Sun?",
    back: "Almost 165 years.",
  },
  {
    id: "sci-f2-c12-dlp-f16",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What are \"giant gas\" planets?",
    back: "Jupiter, Saturn, Uranus and Neptune — their surfaces are covered in gas and they receive very little sunlight.",
  },
  {
    id: "sci-f2-c12-dlp-f17",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is the value of Earth's surface gravity?",
    back: "9.8 m s⁻².",
  },
  {
    id: "sci-f2-c12-dlp-f18",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is ecological footprint?",
    back: "A measure of the ability of water and land to provide basic human needs, and the Earth's ability to regenerate resources.",
  },
  {
    id: "sci-f2-c12-dlp-f19",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How many areas are used to measure ecological footprint?",
    back: "Six areas: carbon dioxide waste treatment, construction, forests, agriculture, farming and fishing.",
  },
  {
    id: "sci-f2-c12-dlp-f20",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Which natural satellite of Jupiter is believed to have seawater beneath its ice?",
    back: "Europa.",
  },

  // Deck 2: Understanding (Cards 21-40)
  {
    id: "sci-f2-c12-dlp-f21",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the surface temperature of Mercury's sunlit side with its dark side.",
    back: "Sunlit side: >427°C. Dark side: can drop to −173°C — due to the lack of an atmosphere.",
  },
  {
    id: "sci-f2-c12-dlp-f22",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the greenhouse effect on Venus with Earth.",
    back: "Venus: thick CO₂ atmosphere causes temperatures up to 462°C. Earth: thinner atmosphere, moderate greenhouse effect, suitable temperature for life.",
  },
  {
    id: "sci-f2-c12-dlp-f23",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare Mars's surface pressure with Earth's.",
    back: "Mars's surface pressure is less than 1/100 of Earth's — minimal effect on surface temperature (−143°C to 35°C).",
  },
  {
    id: "sci-f2-c12-dlp-f24",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the gravity of Mercury and Mars with Earth.",
    back: "Both are lower than Earth's because of their lower mass.",
  },
  {
    id: "sci-f2-c12-dlp-f25",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare Venus's gravity with Earth's.",
    back: "Almost the same, because Venus's mass is almost the same as Earth's.",
  },
  {
    id: "sci-f2-c12-dlp-f26",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Jupiter's gravity higher than Earth's even though its density is low?",
    back: "Because Jupiter's mass is extremely high (almost 320 times Earth), outweighing the effect of low density.",
  },
  {
    id: "sci-f2-c12-dlp-f27",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why isn't the gravity of Saturn, Uranus and Neptune as high as Earth's despite their high mass?",
    back: "Because these \"giant gas\" planets have low density.",
  },
  {
    id: "sci-f2-c12-dlp-f28",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the orbit time of Mercury with Neptune.",
    back: "Mercury (closest): 88 days. Neptune (furthest): 164.8 years — the further a planet, the longer its orbit time.",
  },
  {
    id: "sci-f2-c12-dlp-f29",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "List the unusual rotational directions of planets in the solar system.",
    back: "All planets rotate west to east EXCEPT Venus (east to west) and Uranus (rotates on its side).",
  },
  {
    id: "sci-f2-c12-dlp-f30",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Calculate Earth's distance (1.5 × 10⁸ km) from the Sun in A.U.",
    back: "(1.5 × 10⁸)/(1.5 × 10⁸) = 1.0 A.U.",
  },
  {
    id: "sci-f2-c12-dlp-f31",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Calculate Earth's distance (1.5 × 10⁸ km) from the Sun in light years (ly).",
    back: "(1.5 × 10⁸)/(9.5 × 10¹²) = 1.58 × 10⁻⁵ ly.",
  },
  {
    id: "sci-f2-c12-dlp-f32",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Calculate Saturn's distance (1.43 × 10⁹ km) in A.U.",
    back: "(1.43 × 10⁹)/(1.5 × 10⁸) = 9.5 A.U.",
  },
  {
    id: "sci-f2-c12-dlp-f33",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What would happen if Earth's rotation slowed down or stopped?",
    back: "Longer day/night durations, more deserts, changes in tides, temperature drops in dark areas.",
  },
  {
    id: "sci-f2-c12-dlp-f34",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why does the same side of the Moon always face the Earth?",
    back: "Because the time for the Moon to rotate on its axis and orbit Earth is about the same, 27 days.",
  },
  {
    id: "sci-f2-c12-dlp-f35",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "List the factors that make Earth suitable for living things.",
    back: "Plenty of water, high oxygen content, suitable gravity, sunlight for photosynthesis, suitable temperature range, atmosphere protecting against UV.",
  },
  {
    id: "sci-f2-c12-dlp-f36",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare the mass and surface area of Mars with Earth.",
    back: "Mars's surface area is only 25% of Earth's; its mass is 10% of Earth's.",
  },
  {
    id: "sci-f2-c12-dlp-f37",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Compare Saturn's ring system with Uranus's.",
    back: "Saturn's rings are mostly ice; Uranus's rings are thinner and darker than Saturn's.",
  },
  {
    id: "sci-f2-c12-dlp-f38",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Earth's atmosphere important for life?",
    back: "It protects the surface from solar wind, harmful ultraviolet rays and radiation.",
  },
  {
    id: "sci-f2-c12-dlp-f39",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Why is Jupiter considered the \"protector of the Earth\"?",
    back: "Its strong gravity can deflect huge objects from hitting Earth.",
  },
  {
    id: "sci-f2-c12-dlp-f40",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "What is the general relationship between a planet's distance from the Sun and its surface temperature?",
    back: "Theoretically closer = hotter, but the actual situation also depends on atmosphere, density and surface composition.",
  },

  // Deck 3: Exam (Cards 41-60)
  {
    id: "sci-f2-c12-dlp-f41",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] A planet's distance from the Sun is 3 × 10⁹ km. What is its distance in A.U.?",
    back: "(3 × 10⁹)/(1.5 × 10⁸) = 20 A.U.",
  },
  {
    id: "sci-f2-c12-dlp-f42",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] Why is Venus hotter than Mercury even though Mercury is closer to the Sun?",
    back: "Venus's thick CO₂ atmosphere traps heat (greenhouse effect), unlike Mercury which has no atmosphere to trap heat.",
  },
  {
    id: "sci-f2-c12-dlp-f43",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] If a planet has low density but very high mass, how does this affect its gravity?",
    back: "Gravity depends on both mass and density; an extremely high mass can produce high gravity even with low density, as seen with Jupiter.",
  },
  {
    id: "sci-f2-c12-dlp-f44",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[Common Mistake] Do all planets rotate from west to east?",
    back: "No. Venus rotates east to west and Uranus rotates on its side — both are exceptions.",
  },
  {
    id: "sci-f2-c12-dlp-f45",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[Common Mistake] Does being closer to the Sun always mean a planet is hotter?",
    back: "Not necessarily. Venus is hotter than Mercury despite being further away, due to its atmosphere's greenhouse effect.",
  },
  {
    id: "sci-f2-c12-dlp-f46",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] Why do giant gas planets have extremely low surface temperatures?",
    back: "Their surfaces are covered in gas and receive very little sunlight due to their great distance from the Sun.",
  },
  {
    id: "sci-f2-c12-dlp-f47",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[Exam Tip] How should you answer an A.U./ly conversion calculation for full marks?",
    back: "Write the full formula: A.U. = distance (km) ÷ 1.5 × 10⁸; ly = distance (km) ÷ 9.5 × 10¹². Show working steps and units.",
  },
  {
    id: "sci-f2-c12-dlp-f48",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] How does the lack of an atmosphere on Mercury explain its extreme day-night temperature difference?",
    back: "Without an atmosphere, heat cannot be distributed or trapped, so the sunlit side is extremely hot and the dark side extremely cold.",
  },
  {
    id: "sci-f2-c12-dlp-f49",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] Why does Europa interest scientists in the search for life beyond Earth?",
    back: "It is believed to have seawater beneath its icy surface, and water is a basic requirement for life.",
  },
  {
    id: "sci-f2-c12-dlp-f50",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[Common Mistake] Is ecological footprint the same as a country's population?",
    back: "No. Ecological footprint measures the Earth's ability to meet human needs and regenerate resources, not simply population count.",
  },
  {
    id: "sci-f2-c12-dlp-f51",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] What is the long-term consequence if humanity's ecological footprint exceeds Earth's regeneration capacity?",
    back: "Earth will be depleted of resources because the rate of consumption exceeds the rate of regeneration.",
  },
  {
    id: "sci-f2-c12-dlp-f52",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Name the six areas used to measure ecological footprint.",
    back: "Carbon dioxide waste treatment, construction, forests, agriculture, farming and fishing.",
  },
  {
    id: "sci-f2-c12-dlp-f53",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] Compare the effect of distance on orbit time between Mercury and Saturn.",
    back: "Mercury (closest, 88 days) orbits much faster than Saturn, which is farther and takes much longer to orbit the Sun.",
  },
  {
    id: "sci-f2-c12-dlp-f54",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[Important Fact] What are Jupiter's and Saturn's distances from the Sun in million km?",
    back: "Jupiter: 778.3 million km. Saturn: 1,427 million km.",
  },
  {
    id: "sci-f2-c12-dlp-f55",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] Why does Mars's low surface pressure cause minimal effect on its surface temperature?",
    back: "Low pressure (less than 1/100 of Earth's) means a thin atmosphere that cannot effectively trap or distribute heat.",
  },
  {
    id: "sci-f2-c12-dlp-f56",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "How many moons do Earth, Jupiter and Saturn have?",
    back: "Earth: 1 moon. Jupiter: 67 moons. Saturn: 62 moons.",
  },
  {
    id: "sci-f2-c12-dlp-f57",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] How can a scientist determine whether a planet is suitable for life?",
    back: "Check for the presence of water, oxygen, a moderate temperature range, suitable gravity, a protective atmosphere and sunlight.",
  },
  {
    id: "sci-f2-c12-dlp-f58",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[Common Mistake] Does Uranus rotate upright like most other planets?",
    back: "No. Uranus's axis of rotation is almost parallel to its orbit, making it appear to rotate on its side.",
  },
  {
    id: "sci-f2-c12-dlp-f59",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "[KBAT] What is the key difference between how Mars and Earth retain heat at their surfaces?",
    back: "Earth has a balanced atmosphere that retains moderate heat; Mars has extremely low atmospheric pressure, resulting in minimal heat retention.",
  },
  {
    id: "sci-f2-c12-dlp-f60",
    subjectId: "science",
    form: "Form 2",
    chapter: "Chapter 12",
    lang: "dlp",
    front: "Summarise the Solar System subtopic in one sentence.",
    back: "The solar system consists of eight planets orbiting the Sun at distances measured in A.U. and ly, each with unique temperature, gravity and orbit characteristics, with Earth being the most suitable planet for life.",
  },
];
