import type { QuizQuestion } from "@/data/content";

export const scienceF2C12QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c12-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah Unit Astronomi (A.U.)?",
    options: [
      "Jarak purata antara Bumi dan Matahari, iaitu kira-kira 150 juta kilometer",
      "Jarak yang dilalui cahaya dalam satu tahun",
      "Jisim purata sesebuah planet",
      "Tempoh masa Bumi mengorbit Matahari",
    ],
    answerIndex: 0,
    explanation: "Unit Astronomi (A.U.) ialah jarak purata antara Bumi dan Matahari, iaitu kira-kira 150 juta kilometer (1.5 × 10⁸ km).",
  },
  {
    id: "sci-f2-c12-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah maksud tahun cahaya (ly)?",
    options: [
      "Jarak antara Bumi dan Bulan",
      "Jarak yang dilalui oleh cahaya dalam masa satu tahun",
      "Tempoh satu tahun di Bumi",
      "Kelajuan cahaya dalam saat",
    ],
    answerIndex: 1,
    explanation: "Tahun cahaya ialah jarak yang dilalui oleh cahaya dalam masa satu tahun, iaitu 9.5 × 10¹² km.",
  },
  {
    id: "sci-f2-c12-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapakah kelajuan cahaya?",
    options: [ "9.5 juta km sesaat", "150 000 km sesaat", "300 000 km sesaat", "1.5 juta km sesaat" ],
    answerIndex: 2,
    explanation: "Cahaya bergerak pada halaju 300 000 km setiap saat.",
  },
  {
    id: "sci-f2-c12-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapakah jumlah planet dalam sistem suria?",
    options: [ "9", "6", "7", "8" ],
    answerIndex: 3,
    explanation: "Sistem suria terdiri daripada lapan planet yang mengorbit Matahari.",
  },
  {
    id: "sci-f2-c12-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Sejak tahun bilakah Pluto tidak lagi diiktiraf sebagai planet dalam sistem suria?",
    options: [ "2006", "2010", "1996", "2000" ],
    answerIndex: 0,
    explanation: "Pada tahun 2006, Pluto tidak lagi diiktiraf sebagai planet; ia dikenali sebagai planet kerdil.",
  },
  {
    id: "sci-f2-c12-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah planet yang paling hampir dengan Matahari?",
    options: [ "Bumi", "Utarid", "Marikh", "Zuhrah" ],
    answerIndex: 1,
    explanation: "Utarid ialah planet paling hampir dengan Matahari, kira-kira 57.9 juta km.",
  },
  {
    id: "sci-f2-c12-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah planet terbesar dalam sistem suria?",
    options: [ "Uranus", "Zuhal", "Musytari", "Neptun" ],
    answerIndex: 2,
    explanation: "Musytari ialah planet kelima dan terbesar dalam sistem suria, dengan jisim hampir 320 kali Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Marikh dikenali sebagai...",
    options: [ "Planet Hijau", "Planet Kuning", "Planet Biru", "Planet Merah" ],
    answerIndex: 3,
    explanation: "Marikh dikenali sebagai \"Planet Merah\".",
  },
  {
    id: "sci-f2-c12-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapa peratus permukaan Bumi diliputi air?",
    options: [ "71%", "90%", "29%", "50%" ],
    answerIndex: 0,
    explanation: "Lebih 71% permukaan Bumi diliputi air, 29% daratan.",
  },
  {
    id: "sci-f2-c12-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah nama satelit semula jadi Bumi?",
    options: [ "Titan", "Bulan", "Europa", "Phobos" ],
    answerIndex: 1,
    explanation: "Bulan adalah satu-satunya satelit semula jadi Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Zuhrah dikenali sebagai planet \"rumah hijau\"?",
    options: [
      "Kerana ia paling jauh daripada Matahari",
      "Kerana permukaannya berwarna hijau",
      "Kerana kandungan karbon dioksidanya yang tinggi memerangkap haba",
      "Kerana ia mempunyai banyak tumbuhan",
    ],
    answerIndex: 2,
    explanation: "Zuhrah dikenali sebagai planet \"rumah hijau\" akibat kandungan karbon dioksida yang tinggi yang memerangkap haba, menyebabkan suhu mencecah 460°C.",
  },
  {
    id: "sci-f2-c12-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah keistimewaan arah putaran Zuhrah berbanding planet lain?",
    options: [
      "Zuhrah tidak berputar langsung",
      "Zuhrah berputar di sisinya seperti Uranus",
      "Zuhrah berputar pada paksi yang sama dengan Bumi",
      "Zuhrah berputar daripada timur ke barat, bertentangan dengan Bumi",
    ],
    answerIndex: 3,
    explanation: "Zuhrah berputar daripada timur ke barat (bertentangan dengan Bumi), menyebabkan Matahari terbit dari barat di Zuhrah.",
  },
  {
    id: "sci-f2-c12-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Musytari dianggap sebagai \"pelindung Bumi\"?",
    options: [
      "Kerana daya gravitinya yang kuat dapat memesongkan objek besar daripada menghentam Bumi",
      "Kerana ia menghalang sinar ultraungu daripada Matahari",
      "Kerana ia mengorbit lebih dekat dengan Bumi berbanding planet lain",
      "Kerana ia menghasilkan oksigen untuk Bumi",
    ],
    answerIndex: 0,
    explanation: "Musytari mempunyai daya graviti yang sangat kuat akibat jisimnya yang besar, membolehkannya memesongkan objek besar seperti asteroid daripada menghentam Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah dua bulan yang dimiliki oleh Marikh?",
    options: ["Titan dan Europa", "Phobos dan Deimos", "Io dan Ganymede", "Triton dan Charon"],
    answerIndex: 1,
    explanation: "Marikh mempunyai dua bulan, iaitu Phobos dan Deimos.",
  },
  {
    id: "sci-f2-c12-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah yang dimaksudkan dengan planet \"gas gergasi\"?",
    options: [
      "Planet yang tidak mempunyai bulan",
      "Planet yang permukaannya keseluruhannya batu",
      "Planet yang permukaannya diliputi gas dan menerima sedikit cahaya matahari",
      "Planet yang paling hampir dengan Matahari",
    ],
    answerIndex: 2,
    explanation: "Musytari, Zuhal, Uranus dan Neptun dikelaskan sebagai planet \"gas gergasi\" kerana permukaannya diliputi gas dan menerima sedikit cahaya matahari.",
  },
  {
    id: "sci-f2-c12-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah keistimewaan paksi putaran Uranus?",
    options: [
      "Ia tidak berputar langsung",
      "Ia berputar dari timur ke barat seperti Zuhrah",
      "Ia berputar tegak seperti Bumi",
      "Ia berputar di sisinya, hampir selari dengan orbitnya mengelilingi Matahari",
    ],
    answerIndex: 3,
    explanation: "Paksi putaran Uranus hampir selari dengan orbitnya mengelilingi Matahari, menyebabkan ia kelihatan berputar di sisinya.",
  },
  {
    id: "sci-f2-c12-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah permukaan Bulan yang sama sentiasa menghadap Bumi jika anda memerhatikannya dari Bumi?",
    options: [ "Kerana tempoh putaran Bulan pada paksinya sama dengan tempoh peredarannya mengelilingi Bumi", "Kerana Bulan sentiasa berada pada kedudukan yang sama di angkasa", "Kerana Bulan tidak berputar pada paksinya", "Kerana Bumi tidak berputar pada paksinya" ],
    answerIndex: 0,
    explanation: "Tempoh masa putaran Bulan pada paksinya dan peredarannya mengelilingi Bumi adalah sama, iaitu lebih kurang 27 hari.",
  },
  {
    id: "sci-f2-c12-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berdasarkan data planet, planet manakah yang mempunyai bilangan satelit semula jadi yang paling banyak?",
    options: [
      "Utarid, dengan 0 satelit semula jadi",
      "Musytari, dengan 67 satelit semula jadi",
      "Bumi, dengan 1 satelit semula jadi",
      "Marikh, dengan 2 satelit semula jadi",
    ],
    answerIndex: 1,
    explanation: "Musytari mempunyai 67 satelit semula jadi, diikuti Zuhal 62, Uranus 27 dan Neptun 14. Utarid dan Zuhrah tidak mempunyai satelit semula jadi.",
  },
  {
    id: "sci-f2-c12-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapakah graviti permukaan Bumi?",
    options: [ "24.8 m s⁻²", "6.8 m s⁻²", "9.8 m s⁻²", "12.4 m s⁻²" ],
    answerIndex: 2,
    explanation: "Graviti permukaan Bumi adalah 9.8 m s⁻².",
  },
  {
    id: "sci-f2-c12-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah maksud jejak ekologi (ecological footprint)?",
    options: [
      "Jarak yang dilalui manusia dalam setahun",
      "Jumlah karbon dioksida yang dihasilkan oleh planet",
      "Bilangan penduduk dalam sesebuah negara",
      "Ukuran keupayaan air dan tanah menyediakan keperluan asas manusia serta keupayaan Bumi menjana semula sumbernya",
    ],
    answerIndex: 3,
    explanation: "Jejak ekologi ialah ukuran keupayaan air dan tanah untuk menyediakan keperluan asas manusia, serta keupayaan Bumi untuk menyerap sisa dan menjana semula sumber.",
  },
  {
    id: "sci-f2-c12-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Jarak sebuah planet daripada Matahari ialah 4.5 × 10⁹ km. Berapakah jarak ini dalam unit A.U.? (1 A.U. = 1.5 × 10⁸ km)",
    options: [ "30 A.U.", "300 A.U.", "3 A.U.", "15 A.U." ],
    answerIndex: 0,
    explanation: "Jarak dalam A.U. = (4.5 × 10⁹)/(1.5 × 10⁸) = 30 A.U.",
  },
  {
    id: "sci-f2-c12-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Utarid mengalami perbezaan suhu yang amat ekstrem antara kawasan menghadap Matahari dan kawasan gelapnya?",
    options: [
      "Kerana ia paling jauh daripada Matahari",
      "Kerana ia tidak mempunyai atmosfera untuk memerangkap atau mengagihkan haba",
      "Kerana ia berputar terlalu cepat",
      "Kerana ia diliputi oleh ais",
    ],
    answerIndex: 1,
    explanation: "Utarid tiada atmosfera, justeru kawasan menghadap Matahari sangat panas (>427°C) tetapi kawasan gelap sangat sejuk (boleh jatuh ke −173°C) kerana tiada haba diagihkan atau diperangkap.",
  },
  {
    id: "sci-f2-c12-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Zuhrah lebih panas berbanding Utarid walaupun Utarid lebih hampir dengan Matahari?",
    options: [
      "Kerana Zuhrah mempunyai lebih banyak bulan",
      "Kerana Zuhrah lebih besar daripada Utarid",
      "Kerana atmosfera tebal karbon dioksida Zuhrah memerangkap haba (kesan rumah hijau)",
      "Kerana Zuhrah berputar lebih pantas",
    ],
    answerIndex: 2,
    explanation: "Zuhrah mempunyai atmosfera tebal karbon dioksida yang memerangkap haba melalui kesan rumah hijau, menjadikan suhunya lebih panas (hingga 462°C) berbanding Utarid yang tidak mempunyai atmosfera.",
  },
  {
    id: "sci-f2-c12-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Musytari mempunyai graviti yang lebih tinggi berbanding Bumi walaupun ketumpatannya rendah?",
    options: [
      "Kerana Musytari lebih hampir dengan Matahari",
      "Kerana Musytari mempunyai cincin",
      "Kerana Musytari berputar lebih perlahan",
      "Kerana Musytari mempunyai jisim yang amat tinggi",
    ],
    answerIndex: 3,
    explanation: "Daya graviti bergantung kepada jisim dan ketumpatan; jisim Musytari yang amat tinggi (hampir 320 kali Bumi) menghasilkan graviti yang lebih tinggi walaupun ketumpatannya rendah.",
  },
  {
    id: "sci-f2-c12-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berdasarkan hubungan jarak dan masa orbit, mengapakah Neptun mengambil masa yang jauh lebih lama (164.8 tahun) berbanding Utarid (88 hari) untuk mengorbit Matahari?",
    options: [
      "Kerana semakin jauh planet daripada Matahari, semakin lama masa diperlukan untuk mengorbit",
      "Kerana Neptun berputar di sisinya",
      "Kerana Neptun mempunyai lebih banyak bulan",
      "Kerana Neptun lebih besar daripada Utarid",
    ],
    answerIndex: 0,
    explanation: "Semakin jauh sesuatu planet daripada Matahari, semakin lama masa yang diperlukan untuk mengorbit Matahari — Neptun (planet terjauh) mengambil 164.8 tahun berbanding Utarid (planet terhampir) yang hanya 88 hari.",
  },
  {
    id: "sci-f2-c12-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Jika Bumi berputar lebih perlahan atau berhenti berputar, apakah kesan yang dijangka berlaku?",
    options: [
      "Tidak ada kesan kepada Bumi",
      "Tempoh siang/malam lebih panjang, lebih banyak gurun, perubahan air pasang surut dan suhu menurun di kawasan gelap",
      "Bumi akan terapung ke angkasa lepas",
      "Semua planet lain akan berhenti mengorbit Matahari",
    ],
    answerIndex: 1,
    explanation: "Jika Bumi berputar lebih perlahan atau berhenti, tempoh siang/malam akan lebih panjang, lebih banyak kawasan gurun terbentuk, air pasang surut berubah dan suhu menurun di kawasan yang tidak menerima cahaya matahari.",
  },
  {
    id: "sci-f2-c12-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah permukaan Bulan yang sama sentiasa menghadap Bumi?",
    options: [
      "Kerana Bulan lebih kecil daripada Bumi",
      "Kerana Bulan tidak berputar langsung",
      "Kerana tempoh Bulan berputar pada paksinya dan mengorbit Bumi adalah hampir sama (27 hari)",
      "Kerana graviti Bumi menghalang Bulan daripada berputar",
    ],
    answerIndex: 2,
    explanation: "Tempoh Bulan berputar pada paksinya dan mengorbit Bumi adalah hampir sama, iaitu 27 hari, sehingga permukaan yang sama sentiasa menghadap Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Antara faktor berikut, yang manakah BUKAN sebab Bumi sesuai untuk hidupan?",
    options: [
      "Julat suhu yang sesuai dan tidak terlalu panas atau sejuk",
      "Mempunyai air yang banyak untuk proses hidupan",
      "Atmosfera yang menghalang sinar ultraungu berbahaya",
      "Permukaannya keseluruhannya diliputi gas seperti Musytari",
    ],
    answerIndex: 3,
    explanation: "Bumi BUKAN planet \"gas gergasi\"; permukaannya terdiri daripada daratan dan air, bukan diliputi gas seperti Musytari, Zuhal, Uranus dan Neptun.",
  },
  {
    id: "sci-f2-c12-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Europa, satelit semula jadi Musytari, menarik minat saintis dalam pencarian hidupan luar Bumi?",
    options: [
      "Kerana dipercayai mempunyai air laut di bawah permukaan ais",
      "Kerana ia adalah bulan terbesar dalam sistem suria",
      "Kerana ia lebih hampir dengan Matahari berbanding Bumi",
      "Kerana ia mempunyai atmosfera yang sama dengan Bumi",
    ],
    answerIndex: 0,
    explanation: "Europa dipercayai mempunyai air laut di bawah permukaan ainya — saintis menganggap kemungkinan kewujudan hidupan di sana kerana kewujudan air.",
  },
  {
    id: "sci-f2-c12-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Jika jejak ekologi manusia melebihi keupayaan Bumi untuk menjana semula sumbernya, apakah akibat jangka panjang yang dijangka?",
    options: [
      "Tidak ada kesan kerana sumber Bumi adalah tidak terhad",
      "Bumi akan kehabisan sumber kerana penggunaan melebihi keupayaan penjanaan semula",
      "Hanya kawasan perikanan akan terjejas",
      "Bumi akan menjana lebih banyak sumber secara automatik",
    ],
    answerIndex: 1,
    explanation: "Jika jejak ekologi melebihi keupayaan Bumi untuk menjana semula sumbernya, Bumi akan kehabisan sumber kerana penggunaan sumber lebih pantas daripada kadar penjanaan semula.",
  },
];
