import type { QuizQuestion } from "@/data/content";

export const scienceF2C12QuizzesBM: QuizQuestion[] = [
  {
    id: "sci-f2-c12-bm-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah Unit Astronomi (A.U.)?",
    options: [
      "Jarak purata antara Bumi dan Matahari, iaitu kira-kira 150 juta kilometer",
      "Jarak yang dilalui cahaya dalam satu tahun",
      "Jisim purata sesebuah planet",
      "Tempoh masa Bumi mengorbit Matahari",
    ],
    answerIndex: 0,
    explanation: "Unit Astronomi (A.U.) ialah jarak purata antara Bumi dan Matahari, iaitu kira-kira 150 juta kilometer (1.5 × 10⁸ km).",
  },
  {
    id: "sci-f2-c12-bm-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah maksud tahun cahaya (ly)?",
    options: [
      "Jarak antara Bumi dan Bulan",
      "Jarak yang dilalui oleh cahaya dalam masa satu tahun",
      "Tempoh satu tahun di Bumi",
      "Kelajuan cahaya dalam saat",
    ],
    answerIndex: 1,
    explanation: "Tahun cahaya ialah jarak yang dilalui oleh cahaya dalam masa satu tahun, iaitu 9.5 × 10¹² km.",
  },
  {
    id: "sci-f2-c12-bm-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapakah kelajuan cahaya?",
    options: ["150,000 km saat", "300,000 km saat", "1.5 juta km saat", "9.5 juta km saat"],
    answerIndex: 1,
    explanation: "Cahaya bergerak pada kelajuan 300,000 km saat.",
  },
  {
    id: "sci-f2-c12-bm-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapakah jumlah planet dalam sistem suria?",
    options: ["6", "7", "8", "9"],
    answerIndex: 2,
    explanation: "Sistem suria terdiri daripada lapan planet yang mengorbit Matahari.",
  },
  {
    id: "sci-f2-c12-bm-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Sejak tahun bilakah Pluto tidak lagi diiktiraf sebagai planet dalam sistem suria?",
    options: ["1996", "2000", "2006", "2010"],
    answerIndex: 2,
    explanation: "Pada tahun 2006, Pluto tidak lagi diiktiraf sebagai planet; ia dikenali sebagai planet kerdil.",
  },
  {
    id: "sci-f2-c12-bm-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah planet yang paling hampir dengan Matahari?",
    options: ["Zuhrah", "Bumi", "Utarid", "Marikh"],
    answerIndex: 2,
    explanation: "Utarid ialah planet paling hampir dengan Matahari, kira-kira 57.9 juta km.",
  },
  {
    id: "sci-f2-c12-bm-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah planet terbesar dalam sistem suria?",
    options: ["Zuhal", "Musytari", "Neptun", "Uranus"],
    answerIndex: 1,
    explanation: "Musytari ialah planet kelima dan terbesar dalam sistem suria, dengan jisim hampir 320 kali Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Marikh dikenali sebagai...",
    options: ["Planet Biru", "Planet Merah", "Planet Hijau", "Planet Kuning"],
    answerIndex: 1,
    explanation: "Marikh dikenali sebagai \"Planet Merah\".",
  },
  {
    id: "sci-f2-c12-bm-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapa peratus permukaan Bumi diliputi air?",
    options: ["29%", "50%", "71%", "90%"],
    answerIndex: 2,
    explanation: "Lebih 71% permukaan Bumi diliputi air, 29% daratan.",
  },
  {
    id: "sci-f2-c12-bm-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah nama satelit semula jadi Bumi?",
    options: ["Phobos", "Titan", "Bulan", "Europa"],
    answerIndex: 2,
    explanation: "Bulan adalah satu-satunya satelit semula jadi Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Zuhrah dikenali sebagai planet \"rumah hijau\"?",
    options: [
      "Kerana permukaannya berwarna hijau",
      "Kerana kandungan karbon dioksidanya yang tinggi memerangkap haba",
      "Kerana ia mempunyai banyak tumbuhan",
      "Kerana ia paling jauh daripada Matahari",
    ],
    answerIndex: 1,
    explanation: "Zuhrah dikenali sebagai planet \"rumah hijau\" akibat kandungan karbon dioksida yang tinggi yang memerangkap haba, menyebabkan suhu mencecah 460°C.",
  },
  {
    id: "sci-f2-c12-bm-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah keistimewaan arah putaran Zuhrah berbanding planet lain?",
    options: [
      "Zuhrah berputar pada paksi yang sama dengan Bumi",
      "Zuhrah berputar daripada timur ke barat, bertentangan dengan Bumi",
      "Zuhrah tidak berputar langsung",
      "Zuhrah berputar di sisinya seperti Uranus",
    ],
    answerIndex: 1,
    explanation: "Zuhrah berputar daripada timur ke barat (bertentangan dengan Bumi), menyebabkan Matahari terbit dari barat di Zuhrah.",
  },
  {
    id: "sci-f2-c12-bm-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Musytari dianggap sebagai \"pelindung Bumi\"?",
    options: [
      "Kerana ia menghasilkan oksigen untuk Bumi",
      "Kerana daya gravitinya yang kuat dapat memesongkan objek besar daripada menghentam Bumi",
      "Kerana ia menghalang sinar ultraungu daripada Matahari",
      "Kerana ia mengorbit lebih dekat dengan Bumi berbanding planet lain",
    ],
    answerIndex: 1,
    explanation: "Musytari mempunyai daya graviti yang sangat kuat akibat jisimnya yang besar, membolehkannya memesongkan objek besar seperti asteroid daripada menghentam Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah dua bulan yang dimiliki oleh Marikh?",
    options: ["Titan dan Europa", "Phobos dan Demos", "Io dan Ganymede", "Triton dan Charon"],
    answerIndex: 1,
    explanation: "Marikh mempunyai dua bulan: Phobos dan Demos.",
  },
  {
    id: "sci-f2-c12-bm-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah yang dimaksudkan dengan planet \"gas gergasi\"?",
    options: [
      "Planet yang permukaannya keseluruhannya batu",
      "Planet yang permukaannya diliputi gas dan menerima sedikit cahaya matahari",
      "Planet yang paling hampir dengan Matahari",
      "Planet yang tidak mempunyai bulan",
    ],
    answerIndex: 1,
    explanation: "Musytari, Zuhal, Uranus dan Neptun dikelaskan sebagai planet \"gas gergasi\" kerana permukaannya diliputi gas dan menerima sedikit cahaya matahari.",
  },
  {
    id: "sci-f2-c12-bm-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah keistimewaan paksi putaran Uranus?",
    options: [
      "Ia berputar tegak seperti Bumi",
      "Ia berputar di sisinya, hampir selari dengan orbitnya mengelilingi Matahari",
      "Ia tidak berputar langsung",
      "Ia berputar dari timur ke barat seperti Zuhrah",
    ],
    answerIndex: 1,
    explanation: "Paksi putaran Uranus hampir selari dengan orbitnya mengelilingi Matahari, menyebabkan ia kelihatan berputar di sisinya.",
  },
  {
    id: "sci-f2-c12-bm-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapa lamakah Uranus mengambil masa untuk mengorbit Matahari?",
    options: ["1 tahun", "29 tahun", "84 tahun", "165 tahun"],
    answerIndex: 2,
    explanation: "Uranus mengambil masa 84 tahun untuk mengorbit Matahari.",
  },
  {
    id: "sci-f2-c12-bm-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Bandingkan sistem cincin Zuhal dengan Uranus.",
    options: [
      "Cincin Zuhal kebanyakannya ais; cincin Uranus lebih nipis dan gelap",
      "Kedua-duanya tidak mempunyai cincin",
      "Cincin Uranus lebih besar daripada cincin Zuhal",
      "Hanya Uranus yang mempunyai cincin",
    ],
    answerIndex: 0,
    explanation: "Zuhal mempunyai sistem cincin yang kebanyakannya terdiri daripada ais, manakala Uranus mempunyai sistem cincin yang lebih nipis dan gelap daripada Zuhal.",
  },
  {
    id: "sci-f2-c12-bm-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berapakah graviti permukaan Bumi?",
    options: ["6.8 m s⁻²", "9.8 m s⁻²", "12.4 m s⁻²", "24.8 m s⁻²"],
    answerIndex: 1,
    explanation: "Graviti permukaan Bumi adalah 9.8 m s⁻².",
  },
  {
    id: "sci-f2-c12-bm-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Apakah maksud jejak ekologi (ecological footprint)?",
    options: [
      "Bilangan penduduk dalam sesebuah negara",
      "Ukuran keupayaan air dan tanah menyediakan keperluan asas manusia serta keupayaan Bumi menjana semula sumbernya",
      "Jarak yang dilalui manusia dalam setahun",
      "Jumlah karbon dioksida yang dihasilkan oleh planet",
    ],
    answerIndex: 1,
    explanation: "Jejak ekologi ialah ukuran keupayaan air dan tanah untuk menyediakan keperluan asas manusia, serta keupayaan Bumi untuk menyerap sisa dan menjana semula sumber.",
  },
  {
    id: "sci-f2-c12-bm-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Jarak sebuah planet daripada Matahari ialah 4.5 × 10⁹ km. Berapakah jarak ini dalam unit A.U.? (1 A.U. = 1.5 × 10⁸ km)",
    options: ["3 A.U.", "15 A.U.", "30 A.U.", "300 A.U."],
    answerIndex: 2,
    explanation: "Jarak dalam A.U. = (4.5 × 10⁹)/(1.5 × 10⁸) = 30 A.U.",
  },
  {
    id: "sci-f2-c12-bm-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Utarid mengalami perbezaan suhu yang amat ekstrem antara kawasan menghadap Matahari dan kawasan gelapnya?",
    options: [
      "Kerana ia paling jauh daripada Matahari",
      "Kerana ia tidak mempunyai atmosfera untuk memerangkap atau mengagihkan haba",
      "Kerana ia berputar terlalu cepat",
      "Kerana ia diliputi oleh ais",
    ],
    answerIndex: 1,
    explanation: "Utarid tiada atmosfera, justeru kawasan menghadap Matahari sangat panas (>427°C) tetapi kawasan gelap sangat sejuk (boleh jatuh ke −173°C) kerana tiada haba diagihkan atau diperangkap.",
  },
  {
    id: "sci-f2-c12-bm-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Zuhrah lebih panas berbanding Utarid walaupun Utarid lebih hampir dengan Matahari?",
    options: [
      "Kerana Zuhrah lebih besar daripada Utarid",
      "Kerana atmosfera tebal karbon dioksida Zuhrah memerangkap haba (kesan rumah hijau)",
      "Kerana Zuhrah berputar lebih pantas",
      "Kerana Zuhrah mempunyai lebih banyak bulan",
    ],
    answerIndex: 1,
    explanation: "Zuhrah mempunyai atmosfera tebal karbon dioksida yang memerangkap haba melalui kesan rumah hijau, menjadikan suhunya lebih panas (hingga 462°C) berbanding Utarid yang tidak mempunyai atmosfera.",
  },
  {
    id: "sci-f2-c12-bm-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Musytari mempunyai graviti yang lebih tinggi berbanding Bumi walaupun ketumpatannya rendah?",
    options: [
      "Kerana Musytari mempunyai jisim yang amat tinggi",
      "Kerana Musytari lebih hampir dengan Matahari",
      "Kerana Musytari mempunyai cincin",
      "Kerana Musytari berputar lebih perlahan",
    ],
    answerIndex: 0,
    explanation: "Daya graviti bergantung kepada jisim dan ketumpatan; jisim Musytari yang amat tinggi (hampir 320 kali Bumi) menghasilkan graviti yang lebih tinggi walaupun ketumpatannya rendah.",
  },
  {
    id: "sci-f2-c12-bm-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Berdasarkan hubungan jarak dan masa orbit, mengapakah Neptun mengambil masa yang jauh lebih lama (164.8 tahun) berbanding Utarid (88 hari) untuk mengorbit Matahari?",
    options: [
      "Kerana Neptun lebih besar daripada Utarid",
      "Kerana semakin jauh planet daripada Matahari, semakin lama masa diperlukan untuk mengorbit",
      "Kerana Neptun berputar di sisinya",
      "Kerana Neptun mempunyai lebih banyak bulan",
    ],
    answerIndex: 1,
    explanation: "Semakin jauh sesuatu planet daripada Matahari, semakin lama masa yang diperlukan untuk mengorbit Matahari — Neptun (planet terjauh) mengambil 164.8 tahun berbanding Utarid (planet terhampir) yang hanya 88 hari.",
  },
  {
    id: "sci-f2-c12-bm-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Jika Bumi berputar lebih perlahan atau berhenti berputar, apakah kesan yang dijangka berlaku?",
    options: [
      "Tidak ada kesan kepada Bumi",
      "Tempoh siang/malam lebih panjang, lebih banyak gurun, perubahan air pasang surut dan suhu menurun di kawasan gelap",
      "Bumi akan terapung ke angkasa lepas",
      "Semua planet lain akan berhenti mengorbit Matahari",
    ],
    answerIndex: 1,
    explanation: "Jika Bumi berputar lebih perlahan atau berhenti, tempoh siang/malam akan lebih panjang, lebih banyak kawasan gurun terbentuk, air pasang surut berubah dan suhu menurun di kawasan yang tidak menerima cahaya matahari.",
  },
  {
    id: "sci-f2-c12-bm-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah permukaan Bulan yang sama sentiasa menghadap Bumi?",
    options: [
      "Kerana Bulan tidak berputar langsung",
      "Kerana tempoh Bulan berputar pada paksinya dan mengorbit Bumi adalah hampir sama (27 hari)",
      "Kerana graviti Bumi menghalang Bulan daripada berputar",
      "Kerana Bulan lebih kecil daripada Bumi",
    ],
    answerIndex: 1,
    explanation: "Tempoh Bulan berputar pada paksinya dan mengorbit Bumi adalah hampir sama, iaitu 27 hari, sehingga permukaan yang sama sentiasa menghadap Bumi.",
  },
  {
    id: "sci-f2-c12-bm-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Antara faktor berikut, yang manakah BUKAN sebab Bumi sesuai untuk hidupan?",
    options: [
      "Mempunyai air yang banyak untuk proses hidupan",
      "Atmosfera yang menghalang sinar ultraungu berbahaya",
      "Permukaannya keseluruhannya diliputi gas seperti Musytari",
      "Julat suhu yang sesuai dan tidak terlalu panas atau sejuk",
    ],
    answerIndex: 2,
    explanation: "Bumi BUKAN planet \"gas gergasi\"; permukaannya terdiri daripada daratan dan air, bukan diliputi gas seperti Musytari, Zuhal, Uranus dan Neptun.",
  },
  {
    id: "sci-f2-c12-bm-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Mengapakah Europa, satelit semula jadi Musytari, menarik minat saintis dalam pencarian hidupan luar Bumi?",
    options: [
      "Kerana ia mempunyai atmosfera yang sama dengan Bumi",
      "Kerana dipercayai mempunyai air laut di bawah permukaan ais",
      "Kerana ia adalah bulan terbesar dalam sistem suria",
      "Kerana ia lebih hampir dengan Matahari berbanding Bumi",
    ],
    answerIndex: 1,
    explanation: "Europa dipercayai mempunyai air laut di bawah permukaan ainya — saintis menganggap kemungkinan kewujudan hidupan di sana kerana kewujudan air.",
  },
  {
    id: "sci-f2-c12-bm-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "bm",
    question: "Jika jejak ekologi manusia melebihi keupayaan Bumi untuk menjana semula sumbernya, apakah akibat jangka panjang yang dijangka?",
    options: [
      "Bumi akan menjana lebih banyak sumber secara automatik",
      "Tidak ada kesan kerana sumber Bumi adalah tidak terhad",
      "Bumi akan kehabisan sumber kerana penggunaan melebihi keupayaan penjanaan semula",
      "Hanya kawasan perikanan akan terjejas",
    ],
    answerIndex: 2,
    explanation: "Jika jejak ekologi melebihi keupayaan Bumi untuk menjana semula sumbernya, Bumi akan kehabisan sumber kerana penggunaan sumber lebih pantas daripada kadar penjanaan semula.",
  },
];
