import type { QuizQuestion } from "@/data/content";

export const scienceF2C12QuizzesDLP: QuizQuestion[] = [
  {
    id: "sci-f2-c12-dlp-q1",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is an Astronomical Unit (A.U.)?",
    options: [
      "The average distance between the Earth and the Sun, approximately 150 million kilometres",
      "The distance travelled by light in one year",
      "The average mass of a planet",
      "The time taken for the Earth to orbit the Sun",
    ],
    answerIndex: 0,
    explanation: "An Astronomical Unit (A.U.) is the average distance between the Earth and the Sun, approximately 150 million kilometres (1.5 × 10⁸ km).",
  },
  {
    id: "sci-f2-c12-dlp-q2",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is meant by a light year (ly)?",
    options: [
      "The distance between the Earth and the Moon",
      "The distance travelled by light in one year",
      "The duration of one year on Earth",
      "The speed of light per second",
    ],
    answerIndex: 1,
    explanation: "A light year is the distance travelled by light in one year, which is 9.5 × 10¹² km.",
  },
  {
    id: "sci-f2-c12-dlp-q3",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is the velocity of light?",
    options: ["150,000 km per second", "300,000 km per second", "1.5 million km per second", "9.5 million km per second"],
    answerIndex: 1,
    explanation: "Light moves at a velocity of 300,000 km per second.",
  },
  {
    id: "sci-f2-c12-dlp-q4",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "How many planets are there in the solar system?",
    options: ["6", "7", "8", "9"],
    answerIndex: 2,
    explanation: "The solar system consists of eight planets that orbit the Sun.",
  },
  {
    id: "sci-f2-c12-dlp-q5",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Since which year has Pluto no longer been recognised as a planet in the solar system?",
    options: ["1996", "2000", "2006", "2010"],
    answerIndex: 2,
    explanation: "In 2006, Pluto was no longer recognised as a planet; instead, it is known as a dwarf planet.",
  },
  {
    id: "sci-f2-c12-dlp-q6",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Which planet is closest to the Sun?",
    options: ["Venus", "Earth", "Mercury", "Mars"],
    answerIndex: 2,
    explanation: "Mercury is the closest planet to the Sun, approximately 57.9 million km away.",
  },
  {
    id: "sci-f2-c12-dlp-q7",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Which is the largest planet in the solar system?",
    options: ["Saturn", "Jupiter", "Neptune", "Uranus"],
    answerIndex: 1,
    explanation: "Jupiter is the fifth and largest planet in the solar system, with a mass almost 320 times that of Earth.",
  },
  {
    id: "sci-f2-c12-dlp-q8",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Mars is known as the...",
    options: ["Blue Planet", "Red Planet", "Green Planet", "Yellow Planet"],
    answerIndex: 1,
    explanation: "Mars is known as the \"Red Planet.\"",
  },
  {
    id: "sci-f2-c12-dlp-q9",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What percentage of the Earth's surface is covered in water?",
    options: ["29%", "50%", "71%", "90%"],
    answerIndex: 2,
    explanation: "More than 71% of Earth's surface is covered in water, with 29% being land.",
  },
  {
    id: "sci-f2-c12-dlp-q10",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Easy",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is the name of Earth's natural satellite?",
    options: ["Phobos", "Titan", "The Moon", "Europa"],
    answerIndex: 2,
    explanation: "The Moon is the only natural satellite of the Earth.",
  },
  {
    id: "sci-f2-c12-dlp-q11",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Why is Venus known as the \"greenhouse\" planet?",
    options: [
      "Because its surface is green in colour",
      "Because its high carbon dioxide content traps heat",
      "Because it has a lot of plants",
      "Because it is the furthest planet from the Sun",
    ],
    answerIndex: 1,
    explanation: "Venus is known as the \"greenhouse\" planet due to its high carbon dioxide content which traps heat, causing temperatures to reach up to 460°C.",
  },
  {
    id: "sci-f2-c12-dlp-q12",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is unique about the direction of Venus's rotation compared to other planets?",
    options: [
      "Venus rotates on the same axis as Earth",
      "Venus rotates from east to west, opposite to Earth",
      "Venus does not rotate at all",
      "Venus rotates on its side like Uranus",
    ],
    answerIndex: 1,
    explanation: "Venus rotates from east to west (opposite of Earth), causing the Sun to rise in the west on Venus.",
  },
  {
    id: "sci-f2-c12-dlp-q13",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Why is Jupiter considered the \"protector of the Earth\"?",
    options: [
      "Because it produces oxygen for Earth",
      "Because its strong gravity can deflect huge objects from hitting Earth",
      "Because it blocks ultraviolet rays from the Sun",
      "Because it orbits closer to Earth than other planets",
    ],
    answerIndex: 1,
    explanation: "Jupiter has very strong gravity due to its huge mass, allowing it to deflect huge objects such as asteroids from hitting Earth.",
  },
  {
    id: "sci-f2-c12-dlp-q14",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What are the two moons of Mars?",
    options: ["Titan and Europa", "Phobos and Demos", "Io and Ganymede", "Triton and Charon"],
    answerIndex: 1,
    explanation: "Mars has two moons: Phobos and Demos.",
  },
  {
    id: "sci-f2-c12-dlp-q15",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is meant by a \"giant gas\" planet?",
    options: [
      "A planet whose surface is entirely rock",
      "A planet whose surface is covered in gas and receives very little sunlight",
      "The planet closest to the Sun",
      "A planet without any moons",
    ],
    answerIndex: 1,
    explanation: "Jupiter, Saturn, Uranus and Neptune are classified as \"giant gas\" planets because their surfaces are covered in gas and they receive very little sunlight.",
  },
  {
    id: "sci-f2-c12-dlp-q16",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is unique about the axis of rotation of Uranus?",
    options: [
      "It rotates upright like Earth",
      "It rotates on its side, almost parallel to its orbit around the Sun",
      "It does not rotate at all",
      "It rotates from east to west like Venus",
    ],
    answerIndex: 1,
    explanation: "Uranus's axis of rotation is almost parallel to its orbit around the Sun, making it appear to rotate on its side.",
  },
  {
    id: "sci-f2-c12-dlp-q17",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "How long does Uranus take to orbit the Sun?",
    options: ["1 year", "29 years", "84 years", "165 years"],
    answerIndex: 2,
    explanation: "Uranus takes 84 years to orbit the Sun.",
  },
  {
    id: "sci-f2-c12-dlp-q18",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Compare Saturn's ring system with Uranus's ring system.",
    options: [
      "Saturn's rings are mostly ice; Uranus's rings are thinner and darker",
      "Neither planet has rings",
      "Uranus's rings are bigger than Saturn's",
      "Only Uranus has rings",
    ],
    answerIndex: 0,
    explanation: "Saturn has a ring system mostly comprising ice, while Uranus has a ring system that is thinner and darker than Saturn's.",
  },
  {
    id: "sci-f2-c12-dlp-q19",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is the value of Earth's gravity?",
    options: ["6.8 m s⁻²", "9.8 m s⁻²", "12.4 m s⁻²", "24.8 m s⁻²"],
    answerIndex: 1,
    explanation: "Earth's gravity is 9.8 m s⁻².",
  },
  {
    id: "sci-f2-c12-dlp-q20",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Medium",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "What is meant by ecological footprint?",
    options: [
      "The number of people in a country",
      "A measure of the ability of water and land to provide basic human needs and the Earth's ability to regenerate resources",
      "The distance a person travels in a year",
      "The amount of carbon dioxide produced by a planet",
    ],
    answerIndex: 1,
    explanation: "Ecological footprint is a measure of the ability of water and land to provide the basic needs of humans, as well as the Earth's ability to absorb waste and regenerate resources.",
  },
  {
    id: "sci-f2-c12-dlp-q21",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "A planet's distance from the Sun is 4.5 × 10⁹ km. What is this distance in A.U.? (1 A.U. = 1.5 × 10⁸ km)",
    options: ["3 A.U.", "15 A.U.", "30 A.U.", "300 A.U."],
    answerIndex: 2,
    explanation: "Distance in A.U. = (4.5 × 10⁹)/(1.5 × 10⁸) = 30 A.U.",
  },
  {
    id: "sci-f2-c12-dlp-q22",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Why does Mercury experience an extreme temperature difference between the side facing the Sun and its dark side?",
    options: [
      "Because it is the furthest planet from the Sun",
      "Because it has no atmosphere to trap or distribute heat",
      "Because it rotates too quickly",
      "Because it is covered in ice",
    ],
    answerIndex: 1,
    explanation: "Mercury has no atmosphere, so the side facing the Sun is extremely hot (>427°C) while the dark side is extremely cold (can drop to −173°C) because no heat is distributed or trapped.",
  },
  {
    id: "sci-f2-c12-dlp-q23",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Why is Venus hotter than Mercury even though Mercury is closer to the Sun?",
    options: [
      "Because Venus is bigger than Mercury",
      "Because Venus's thick carbon dioxide atmosphere traps heat (greenhouse effect)",
      "Because Venus rotates faster",
      "Because Venus has more moons",
    ],
    answerIndex: 1,
    explanation: "Venus has a thick carbon dioxide atmosphere that traps heat through the greenhouse effect, making its temperature hotter (up to 462°C) compared to Mercury, which has no atmosphere.",
  },
  {
    id: "sci-f2-c12-dlp-q24",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Why does Jupiter have higher gravity than Earth even though its density is low?",
    options: [
      "Because Jupiter has an extremely high mass",
      "Because Jupiter is closer to the Sun",
      "Because Jupiter has rings",
      "Because Jupiter rotates more slowly",
    ],
    answerIndex: 0,
    explanation: "Gravity depends on mass and density; Jupiter's extremely high mass (almost 320 times Earth) results in higher gravity despite its low density.",
  },
  {
    id: "sci-f2-c12-dlp-q25",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Based on the relationship between distance and orbit time, why does Neptune take much longer (164.8 years) than Mercury (88 days) to orbit the Sun?",
    options: [
      "Because Neptune is bigger than Mercury",
      "Because the further a planet is from the Sun, the more time it needs to orbit",
      "Because Neptune rotates on its side",
      "Because Neptune has more moons",
    ],
    answerIndex: 1,
    explanation: "The further a planet is from the Sun, the more time it needs to orbit the Sun — Neptune (furthest planet) takes 164.8 years compared to Mercury (closest planet) which takes only 88 days.",
  },
  {
    id: "sci-f2-c12-dlp-q26",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "If the Earth's rotation slowed down or stopped, what effects would be expected?",
    options: [
      "There would be no effect on Earth",
      "Longer day/night durations, more deserts, changes in tides and temperature drops in dark areas",
      "Earth would float off into space",
      "All other planets would stop orbiting the Sun",
    ],
    answerIndex: 1,
    explanation: "If Earth's rotation slowed down or stopped, day/night duration would be longer, more desert areas would form, tides would change, and temperatures would drop in areas not receiving sunlight.",
  },
  {
    id: "sci-f2-c12-dlp-q27",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Why does the same side of the Moon always face the Earth?",
    options: [
      "Because the Moon does not rotate at all",
      "Because the time taken for the Moon to rotate on its axis and orbit the Earth is about the same (27 days)",
      "Because Earth's gravity prevents the Moon from rotating",
      "Because the Moon is smaller than Earth",
    ],
    answerIndex: 1,
    explanation: "The time taken for the Moon to rotate on its axis and orbit the Earth is about the same, 27 days, so the same surface always faces the Earth.",
  },
  {
    id: "sci-f2-c12-dlp-q28",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Which of the following is NOT a reason Earth is suitable for living things?",
    options: [
      "Has plenty of water for living processes",
      "An atmosphere that blocks harmful ultraviolet rays",
      "Its surface is entirely covered in gas like Jupiter",
      "A suitable temperature range that is not too hot or too cold",
    ],
    answerIndex: 2,
    explanation: "Earth is NOT a \"giant gas\" planet; its surface consists of land and water, not gas like Jupiter, Saturn, Uranus and Neptune.",
  },
  {
    id: "sci-f2-c12-dlp-q29",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "Why does Europa, a natural satellite of Jupiter, interest scientists in the search for life beyond Earth?",
    options: [
      "Because it has the same atmosphere as Earth",
      "Because it is believed to have seawater beneath its icy surface",
      "Because it is the biggest moon in the solar system",
      "Because it is closer to the Sun than Earth",
    ],
    answerIndex: 1,
    explanation: "Europa is believed to have seawater beneath its icy surface — scientists assume the possibility of life there due to the presence of water.",
  },
  {
    id: "sci-f2-c12-dlp-q30",
    subjectId: "science",
    form: "Form 2",
    difficulty: "Hard",
    chapter: "Chapter 12",
    lang: "dlp",
    question: "If humanity's ecological footprint exceeds Earth's ability to regenerate its resources, what long-term outcome is expected?",
    options: [
      "Earth will automatically generate more resources",
      "There will be no effect because Earth's resources are unlimited",
      "Earth will be depleted of resources because consumption exceeds the rate of regeneration",
      "Only fishing areas will be affected",
    ],
    answerIndex: 2,
    explanation: "If the ecological footprint exceeds Earth's ability to regenerate its resources, Earth will be depleted of resources because consumption outpaces the rate of regeneration.",
  },
];
